sprite $network_intelligence_center [512x512/16z] {
xDh15KH004H10BVEFrgupXamLHdi-xs0t0000000000000000000000000000000000000000000000000000000000000000000WAMG2ebl0k9RWFeM8By5
g7yOKW7v7GBaDm3v3K1-0v3V0EGt0Fd_Tnl8l1GS0Fpz3S3VNtz_VmEGNt_z3K1-_VKt0Ftrbrz__UVKJFybw8_-zP3__lxeZ_xeZ_xeBzVyVF_xVXFJ5P_X
RkoTENRsE0m44pq16Uz_subc-oFZcTqaXAhS-iGkaDhXm_vPL7ulggz_dYliqNIk08HZWeAZVlvvjhXLKJF_nOrZNpPTxjMVkHQePJm-_tIQgAEtuVUV1T2l
3kjg_HdeLuTbziyhXZepSR__hC8DtmBMCq3jjyOKWCk9t3-T9dnQFlXBxv92LuQuVALX-XVWIFC9mfhLRVhndtdrQNc3CU6_mDtw4_rNoLdu5vCATltYWLt7
lpp6sB6H587-0bfvvHAgWtyTx-z-DixiTUA_JjtWkchjnx-_01xb2MGT_FkpF7tQZ_yy7MRzJo85u5z4QIVikun_DRFt6Fyvsp_-OtJ1uZzd-yT_3gbNFIm0
ETK_2m3-yPy2yA_dsftbCy3eaIdJdmNWIGturpDYJtd_LvbgTJVy-dd__nNcMjYqqJ_-wvBqBJpnx-lAe2-0-eRHNy3ZFrNwXMEgG_y7JRIFn_-IWVyqJl-r
Jkcd_uyYtQXlLEgV0jZWIZdzrq9_0S-tNTv_tu3-0fuFl2NJtzzfWWBOC5rL-lNzVoa0XJ352GNw2soCgbOvmchQl_ZJ1LYWJ5TCk_Mp10XkrqbhQQT-tWPx
-xrMkiy-Iq3FxtGuyVF_hyn8CRfZ2En8AiLenmI5dDfqQJ4j-q2N9dZGBuFMaa1lsRk1sVeX1le7vZzm-8StTIoWipnm-syG-AS0q8z__5C0wCzd0LqbWQPo
VK4__l5F0Q0V_ppsfG2O_hm6XduM0FnJ0EZ7FoT_503JN-yVKIhzUfJBrwn5kgV_q2vTCMc9LkgN8K-51XzN-qzVAltHffbD_SUKqqpj0JMoPG6CkSu8SPxP
ql-OJmxKWUOnFAdGuFTM_-b9XGRVb-fFKoeq-BzJVuOfbK6FPSxxrukPyzsfFD8yZ2kKdkJd_J-kL3gYdr9v75ig3P57-kHnmXLAFnmTrizZIwKTyaZp2loX
zDUF_pfp_CSf_NenCSQ_Fj6yX72bqehS2E0VXkk7jlu1_u1_m3_W7_0F-0Vy0_u1_u1_m3_W7_0F-0TU003U_m7ymvp_mzojn2opukNxZqiBu50g-0_yNupX
UufxzVFztx9Cf_EyhbJe_w3thnVpZD6_mZ3IF8rdLWJzVxxYVoKDe5JzLFnubiNL5UzowYSyeRJbrO_q-mqWtzMNJ1f02rBfGyW7-l46qB5wyxXcan_7klYi
zgZhF4zXE3DQNq0zq3o3BPN-Q0zoaITuvAT6wpkyqe7c2TJJubtVGdc2ctx4bqVhWuGmHZlAUH7hipoQ6aytihNnMN2__rYJeG3MNS0pMpyCzm-3zGF-ORP-
YDdwORX_6AmVy0_en__W6__0zCV_OFqmt3-W7_-3J_w0wO__mVe1__WVgH_m3vpzuvy50FqK0Ffx-iUXsB-_029pGLNU1nx__70J42twmTh7n64xxFhrE_Ci
A6Yxw2FGNMDQ_m3RKdUq5Tws4Aq2VBOZa2OifUt74YxOHSxg3SiiOq9_FInJb_QTto6Ylu30c69paGNGNq3YgxwzTv_-JFHl2klnzHNVevy2o38RR8cl0RCC
-WlKvrqATd3hcBZkBw2O_XjhYgVAX_uzgEOcYyT_el_dHDcKiG2o2FxhsFJNbvL8VG7GhAjue3Ok08b_mvFwaYLTcOh6XFvwLifSIxjH1_zr2ewKVSMtZWd_
2lhiAMT_0cWgIAD6_EEV0hYDLed6QF_uNmtzetzqMs7yl_WNC3LF_0-D4__ufwyuQGR-6_cFqOtbkVrVCqfZUJkdinHyrOT_hN_zTuA-VSQ_a5-q2EdHMWx_
EeUdzlh1Vm6XmA2rl8CZrtsg1QGE_lqPXcexTV3llxcZbu7-0kwi73go0Fwjqz_Y0_q5h5c5vrSkzOz_qy-Wlu1LVvqhnqJ_bxj_QRX-PgNqJLKAW3CD-ZzM
UQp-N_JBrBIuApDSFtVbq5_W-U1T-K2_mC-nJZDr7lGNq4RrUFtNnmIXJ2gF-5_Oho2CAd-5QKmWI4hWNpSc47pA9V0l71C8fidnr_AAj_iXjawHgrg8BG4W
zG_u1_m3_W7_W7_0_mWeW0Nu1_nF0_yygC7_QW_CzG_uX-7w0V_u7wmVPlk7cAqVPlk7cAqV9ZVa1hgom73zC5m_3DSFm_N3SFqm_S8FXaz-c6uVnjk7yVO1
-N_oLtjmB000000moDzw5hkg4m000000000000000000000000000000000000000000000000000000000000000004
}

