sprite $bigquery [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000001cxyuE90TX883kWU7J-MUx0SpDcXb4FKM0z0hQTb_JfVgBIkaS-STr1Ow7-yiQYVD2xvM1l12m
Trd0ta70NWJWom1y4O0l0l150Bu8m9S0-jyV0JNwov80Mry4w4i0VGcWBm7q9O2-1D2N0FeIG5y2w0i0VWcWBm7q9G2_0D2N0Fm2G5y2VBn706n-No35xmYW
lw9QRH_yZW3w0e3VpqhXTmJW5m3w0e1V0l0B07u1m2y0tkqJ09lVeo3y7zGLpg_mxpBnemE0ly32yEypu2C2W3zWaVYNJhLY0F3dBXT_nSJYt_yJjjVk0S0V
l7JymSl7Vq20yKzNSXVuanl1dzmB_Zhjy3_lypC_6G3-oJtXJsuBlywArSap6aMQmw-z-ZkaNi3vBnYE0E3FwX9_pAiS_ffJuV-oshAdlG8GD1BjuWzj67_B
QPd_oz8qVctZpsfyyAyxXMU2Zp_wwCEl_U01w5_x9g3vkiK_htT3m6yC5_vd0g1j0T1qvKfy09hARnZuZMFWVp80sXK0pPQknZ-4tvx8_j2B0CJ-8v9JqUbl
CFW39eD_eaR2R8f-oyVUqEBwEl_AE83VUF3FLZly08Xzy6E3sFvsI2I_6U5V_ybO_Ww0xCO4G5yE0FuE05q9WARuf_Ka0E4jUGZ0tm6W8G7G3t_jL2x-v_YR
M3I_aUL-w8U_xMze1RO_VvsK7nj__bsG7G1op5yR0g0B_ffuSdr6nz_iblVGeltvRxi-mzizmlpRATkV_wXy0F3t0d3ntzhV-ZSVRU4V0-Bl0DZhWn_yAro_
tlp_Cm3Pnp__Li1_tUBvzyh-D_y5C-JFtzd5tzAN-xi0uEy0uCz_zxi__XPUOAxy-MznZF8tH_xhYl_Ddp__1OCKM_xy-KVSjl3lNlxvVrVnDqh-_Fdpvy__
eJNpvy-VF_-xmCydypTC_lpvy-VFdpz__lmdLyoVFt_-_FdpR_mB-9icV_xy-N_75Gj__dy_K_pvy-VFdpz__lpvy-VFdp__3LVCdpz__lpvy-VFVvpipz_d
l_ZpR_nz_wE0Ft_-_Fdpvy-VFt_-_FbFB-dZYlxzB_wzeF-O-Sqo_dx_bJz__lpvy-VFdtzFyUyF-VCVqVxyxv-lbklFVtxP_Fdpz__l_Fdpvy-_0F-wXVCV
IVwT_uiL9lhpvy-VF_zUyUd__9LBvrzY-wzVEt_-_5kG_yl5y-_y-HVbNx_wV-pSHu8U8Gn4OGTQQ5VtlwrNZfC7_vGQFPt0udlWoSVxZtx-5_w_9_hv1_xu
usz__lq1u1y7-EEFF_uB_Etyun1_hh-4_uVvyOy3_1ty-EC_n7y0Jd-k_yujHcj__5NEty1VszyGG67_3HU71m1_7e2Q_ePZSyzyz28tyjTvrzzVyhVR-7zv
mA7XhrB-rkj_gU0CGm0b_TNW-dkMkOM_y3S4KCRVU6B-0F0VXWFZ0J3uS_qj-rJnXzyLG6L_uV_mFsHGmz_4x_Vt9rtMNosklx_f2lusVlob0lwh_7FXf0YW
eB_4zPV24835tyK_9Oa7GCNyDnyJ3u1A-HjEoJp-byth3xzzjpB--Ztu3qC0Ld_1lx3Tqdh3vs_Wn__fMFtz_0JWzV-YfuE_8G2Fl_py122RVucpmLyUVy5V
Pilz_j_quk0_3G5izeV_jOdzYuuR-4SN_-7RrEyFlnHBSwP_DF8N_WP-7e2w_iDm8WJWyUVwIrSiZTSVVlV6SO2_wp08mEyFls9n3l0tdGG1-FtXrnMBu_I7
txzv7E3lEGG2yFl3hrWUZp_yblNzT_6gjt_t0CPZ_ssrbm-rzuzWTm9WSmBekZV-qPoV06QhdVt-78O_-LFyfo600_WpamV05O0_zqm2i1NWtpMJ09vEcqrd
7XN0YFyqLu_EP_uQ7e2_fnS_0JoTyrVC981NvlJzPXB0wzEAFmF_uXy7niFu2Q3-4n2FuIU0r-VCjJ89u4u5n0P-0gXQG6pW9u3NvgXjPXB0RGg83Vm4KBI0
Y0ty9mOm8kwVG3ZuCuC7e481OU0dW28_91hXuYS0_oCGBdu2y2SGOU8d07y24Mv-0l3_uhYVFtCImCO48iB2Jm3-22B2mDyaW1dxPfNUpqy0w-EJVvs_Qm0Z
N6DKVyhVDm15zvcP100_0RISp2G0BZy1m4y0NVa9GF0J0Fm4W3u1mF_16JfZu2S0lkX306qlFm48VW8uUfHz0o00INq3e02fRm048Abl01GW4S2xPnwetpS0
dW2fRm0K8Abl00GWzGs00YIr3O0296qEG0HGIRzl01GWzGs00YIr3O029BKDW08ajGs00YIr3O029BKDW08aTGs00gQahW5GW2Hr3O0497KDW08agMi09229
00nJ1fy0N5C0dm2yOyOd0FzSiNs6908eDEQRJm3-STiJW7_S-0JW7piz0VZ7Rqy0_Z784q2zMO1l500XJ1KOepzpR02JS_tHRhrG0Gp200pSV_ElUDZeovq4
0hHZn3y0uls9zoVUd_Z-H_pv4-zFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp
4yzFF3_r_5pVSZa7nW00000000000000000000000000u0S
}

