sprite $security_key_enforcement [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlVj8SvG9WW2wGIIxklzfVpDinXj6NKIHBoxG_Ub59auc8_kP4H6fuoTvd_dFC-P7ZjzDlKa-
kWNeVvxzG-ppIy3--YBOhwKWXTbVFoMeVKzS0_3prm2nHFmp-pCgu1hlUaQ32XZzjruNFgS1yCyqQ03zW0OKoq3zCoDr2T3N0FeQu88li05RMW4Clsi1-ku7
MFtN4_E8sF1R0ORV2Z3y-IkW7j40msy56FupMwkp0FnMWDsl08P_VW6A_GH-Am2_0k1NWBpinw40JlmLmEvN0FmAW7_n0hmMB01-6m2_0k1N01T-2e1V0Mn_
1S2l0FWL0F-nJIb0uRS0FF5L0EEl0FYpKbCAyCAVcZ6b0ExxEG8OVmN0xmXW-tixaF5t1C3l263xMm36Nm7mEmBmjm3mMm3BP4i2j03onz-3m7BjPm7q7NyB
O3V-Zra0rTh_k197W9Vnjm2ClpC0x_Ys0BgDlyy3yNSF0B-d0Fmj0FmM07yBW3z__0u0_2q0j_ujWFJSOL7yOt8RWmD0Gcubi01kpzq0Jtu8n3_yFt00s09U
-_8kWDkIyGOS9m1t9UI5VzW1W7_5597_4g_wUCu1W7-D2-4_FnFuWmlW0932V-OH_fxz1TJH0I3WzRwGvVtvJrX8kPy4vH_SoFmJ0Fw3_xpiUVoZ5Zu1CFur
uP_AzUU_qd_5Fv9_z3u1u3_uJmX__fdyerhxynzzBm3my-S_-FDt0-0Zmzy9O2O_V_vRQt_-Omb__lpvy-VFd_zevy-VFt_-_FdpB_v_4UV__Fdpvy-VVtNo
v-_vBt_-tl_3dpz__Zu0kgJ_blgFxVp_vEiVVFvdy_clAscw_ldx_2z_t__0l_Zx_XzV0EVh_xhvN-VdR_mLmFU_-lvd_loFplw-__zOtv__4VRlL02_0lJv
_IV-Hz1F4VFF_z55Fm3gzp-F3qi0lm9ay_D_Vwhjxt_pFtFRntty-bl6IrytTj3LVy2BVzI5Vo1W_FdFQi1nFDUV_va9Vpjr_Il0cGb_DtZy-P-vSDB9F_aA
83_uVvc-_Fpvyz-VoxzrvRS0Z3__ci9VGm6C__h-_2lNNm6CFt_-xW6wzsS167_-dlmgWF7dx-Yl0CQVl_5NWElysvFytGFOZVyVn_P_WBy2EFdZd_BSNm4y
ztKAwDhF0d3ofm1E_lZR_WfW-oi0VjS0tlLX0RZpem2slm9uwkiKmC4_Vm7WtrAK5C31Nm7mAm1-vu1RPtuBeDfS-Ic0XtuAW5y1y2i0VWNeUjjF0Ko_0hIw
xbS0_Eu4uhS1tFJLW367Nnhpl-8m5C2XNm5gBhyuz2j0hzrVpB-8Gxy6DD3FurS0mwy1ZlmAi3SQVWsm-lrYhDLl1JZhru0qVSczsVzwahu6LEFPru2jWRu6
kEJJ08zv5S17EpG0lm9O_WgmqA-uYEtFt_WhWF7dxxjy-SyU_xgNNwp_vS9V-0j_uI_yXR_m5_x2N_WBV-4l_8M_y1V-mb_u2t_Xlrxu2t_XB_o5l_0N_i9V
-0j_uI_yXR_m5_x2N_WBV-4l_DSBV-4l_8M_y1V-mb_u2t_XB_o5l_0N_i9V-0j_uI_yXVzwuI_yXR_m5_x2N_WBV-4l_8M_y1V-mb_u2__bKyU4TF4tiVpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__jhqRtjq8000000W
oDzwa4kX5G000000m3y000000E0V00000000_m00000000000000000000000000G
}

