sprite $cloud_sql [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlJj9SnLdWoZinobBETF-LrlDRRu9rLubeR3Yn0R-vZs0eI3hdlNFcJlqU__y73Dqw7_pZoo0
ZLx-YGLmy9V_jysieL_-aGMWN_wH1Q1V_f45e5_-aGMWN_wH1Q1V_aa5SCD_zKyiW8E__3C3GB_y8mj0l_mZ2q2__2CBGB_y8mj0l_mZ2q2__0CAG7_1_qtV
3a1_tR_Mvtc3l_ppBWBebtza0UYNVsG1w9T_P07ebtza0UYNVsm1w5_zKnu7e5_-9nJ0Hb_mpog0W__gd_Op0FtoZom0_VAFB03zyeyi0FtoZom0_VAFB03z
yaygW1l-gtzY0HpyvPyP0Fhb7ra0-kKVMG3wvHzG0FeYV_z_BeJ-rJ_m781--SSMW7xv-ry5q3VnF-Q38VZBF-yYW7xvHnQ0Vlb75e1--KSMWFxLF-jM0Fto
3pm7e5_-iGMWN_vcLm7M-Xd-jOQftS5V_daN0VJBFx80zCi_iW3qop-o0FJBFx80zCi_iW3qoz-X03QwWNzC0HpyvPyP0Fhbdri0-cFEaLe0-dr-MsW1wDSs
1Z3GtwbV1KIU0z2d0FIv2kWtVFGfG3yt_LhGHG1z2k32VrsFBG3zl0T2wFD347qU1w1F0UXp5RXdpKTVNm0V3DdgypX0iFRQfj_cyjes_p4EyVzextZmryOc
_NwC_yUE0bxpopPswFUJ_FK5p2-Tch_te_o_xVME-ZMj_c7-uWBcBTFf7-SlBM3UDet-YVwrzdf7_Pf0_qH_MG7pzWdq3_Q_zrPWJC76VRTyn_fh2fYY3O7-
MVwA0gPmTvpw8_nlknMOujsW7-1_Lm5pmsxG3_2_eu2vQJVe1_X_zStWtBWRzAFyrmkOcxUgd-o_VYim3RQYZ_zA0MDQRE667_-50gRDnYyT_FYl532jjgIF
_xUzrFhw0aeV_vK2fkN-kpx-AmLCs_qtVVnN7WTCwoteury5IFJr1OpHyL-v5MZp3TR-GH__bGBccsmiwEDV1RoVVctjme__zLPWljak-lWl533VS6DD7_yg
OBxf5lJnhvl1-SRxfe__saB_xWd-jInz_A_BqiV_kYnz_A-BqiV_kcUKFlxNjGFqyL_P0VpuB-q0VVoNTe0-_aixG1__fHsWZ__I3j37Vsa7wEE_j0FqyL_P
uu1_imd-A_C_-F6_T-xw-DyzRttyxv-pFlwA-UhZhvchFlwg7Q2Fl_aRGcC15F_RPtZmuo-TdJx-ufdfuo-Vbpx--ddfuw-VbJx--ZKlVVprCx_Xnzy_WBvl
RPuolmByzGKi580-1Q2lsTEZ07_zCG_TnyRfzFqFVWf0dmByzIb0_xb8IzRdLY1DdmBGfm3qzNiO5C23Vcu5-D5F0O7w5F0CrwU05g_FhK2qFWLawrD0jZu5
PElpdcWsFsy8PUjp4SZMfu1iVGh8rgU0R7qAoDQdW6nzRWQpF-ZW5E1yyBCJ_45qBi1Plvzo41iNOApVZ_4tBi1N_o1_um9SzO_oDox0K_ymV-C27FNFywyz
tG9mUzpJ-vd-jQOjGE__Mj8_rT_r8k1rwW_mDol0IZ_0twq08_q0Vxy2RFG3_1qBCD4FyFSim48_ph-s_NEHxVol7kbVs_o6q6RzqNk6l-j5OFUf7_-z1UpL
ntzt0GRw-6yiO9y-_Wu5xDB7twC02ttyrmjuAFtRaZx-jnIWyxz97t_z6qBgnptuU_qC45_uyJShGAgFlrq1Gdty3GkGwUDlMO187t_J0hJw-BlT30e-wC1_
OUtcDuGqZtlmTxq824xz-1iN8D37txW0WJx-nWK8zF4tBa2WZxzn0Lxw-Ai_5d2wuSTV_tw8z8OV__KzllQ_oTV-lzwMkF7N_mmGNFZnDov0e8-_SG42VVoD
2n3euszSW9i-_jhFHGGVTE1lMK3vcppkmL__Xj0t_vVYWmxyFNy622xy-1iNOA2F__ASzV5Np5SVVyrSzV5NpLCVVzcQgJx-NkS0wGq__jBP7VpuYsUcZxzy
Nlhuw-UbZxz-Nlhuw-UbZxz-NlhuwoVGT_QdWAVWSO-pFWNCXGNeKm3w582-O0-70lprcu22Mm5-z5C0-jmC9kbJG4EVMm5-z5C0-XI0FWMWlt7Dfe0E_vOz
DnU0FW-4Nh7w511-x5D0jZu5PEjJGBO-1VZeisU6_q3QvnIGVV1JGBO-1MJhKq2sFWLawrD0jZu5PEjJGBO-0MG_xk4DeUo3dtF0xVhiuLo0ituxvWZsBS1N
_w2__sDSWA_-GVx61RZgd-V_qHmByDG_oxzc-7w8uGr_Fz7VzI9WUF2VvszSW9t-YVx61PZf1_Xx5M2b7-3lLe2HVe2_Nm4s-W7-ZWMOw2Vvrnu6VqxKu0zs
jXxWxteAS3Zu0_nj2p3G3_3tBM2tFlvx2zYhZ__k0WpqyTzOW84-_XlV3jYbZx_7EM27_kZutn50M_0tEFZnt_26a9C-_lgBW5mVVwi2nFhucnKWrSVVhW2X
Flw61SZqyRSim4uV_zfJS3Ce-A1ZTFnjJm6AWnz_tm84-lWR5o3Gnz-u084-_iO52FJnDov0e8-_SG42VVoD2_3Jn_-k3uR-e_-uuNCU_3rF0LV_b-3Wnz-c
0C6f7t_Z0WJw-1iN8D37txW0WJx-nWLOwEElVpjWbhz07t_3Sq0h_otlT-2_llNFHLG7F_wUFmC4-lZx5c2WZ__glFNnlt_E-lWhvgkFlsQk-lYhTe0-_e97
Wjh7FVWBPtZmuo-TdJx-ufdfuo-Vbpx--ddfuw-VZpx-xrx0Is2Dlsi1OdJy7JuOghN-nluKiF7WHx_sS2l0Nx_De_QnSG9zwuEV0j2d0FGf85YV0fxX-XJG
mlKfW1j-2a1__vu61LZfZoaRjm9S-2a0VGf0dm9ozIa0VHu9ZcHz2iZMfu1iVG9mUTp3Mf0_sYxdWD_PkGi20880067zMnE4PHWlfszz1Rpr5V3MLy1RNm5l
VGMyzHqOUX_dyGfuF_mAUEihuAslWBU-0jxw2dZhA-2jhu2tljq1RtwlWBU-0jxw2dZhA-2jhu2tlWBU-WfuwolWhI-0zt4UKuBlXzyxuAslWBU-0jxw2dZh
A-2jhu2tlWjbtmD-hu3tmw-0jxu2tleAUEihuAslWBU-0jxw2dZhsntmvZSb-DRt4NZhA-2jhu2tlWBU-WfuwolWhQ-0jxu0thjxJ0c-7txlWBU-0jxw2dZh
A-2jhu2tlWBU-dO7l0VyNW7lXry1Rtq5qAyzE1O000006EHlFOfzrGK000000000000000000000000000W
}

