sprite $healthcare_nlp_api [512x512/16z] {
xTr9MiOW68J1BJlkVrfdvG31f_dfghKJUJ6E-PZ_0m00000000000000000000000000000000000000000060Uwu2FEqLz__VNNNt_zzTTVV_trrrz__VNN
Nt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__G4000000000000000000036Io3V7_tH7_tH7_tH7_tH
7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_sPrm8000000000000000000006vd-WF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZ
F_gZF_gZF_gZF_gZ_sxw0m00000000000000001uNb5x3wrgRm-8tx05CBr0_TmECCuZARTa_VDogzO_BxXi_VDo2zS_BxXo_VDoQzS_R-_YzM_Cl-ZVcN_H
lpB_edzb_aN_olgB_fNvb-x--W_zA_Cl-bVcN_IlpB_eNvbVV_c_TVVNV-X_G_u7WVG_qjErLFJNVqCd_Lys_vvI-Xzdso9kxQ__nbhwtvT_kQ-__fk3wNzX
_kMk_lhltr3wtvX_kQU__i4zfNy-V_IjvfdfLRm1zBzWLXoXJANzVVgx0SZl1g3_3FGddSWDG7yt0Fdrrty6-fFiumQWlnk0_Fhhhx_-yz3-w4_s-8Q9_kYF
_dVIVnxP7_qPwVxeZ_i_-gC_-gC_Vl-7_kXVEhx1_t_ex___zDS_p-C_-k_Y-H_zzTVVyv-D_Jt_hR_v3_gR_pBrD_z9_xZ0_3VzpN_Kt_pNolxcF-jl_llK
t_aF-Zl_HN_dF-dl_3VzdV-e_x7d_tQV_wh_2Boja_hR0AFo_7VzbsrlH__ZRBaEUowc_WdFByKO5_VNVtdswbF_WDsNUSChwX-GlCxwwp-R-zi0K_-3bLz7
oljJdf_o_9Jdfpm_vVcHN__A-iYF_F8traT-v9TVVVtLbrzz_TMNNttznPTV_FOvG6DeRn2SzEO0ReB-o8_-o8_-o8_-o8_yuwc9_Xl8hx_--ikll_xwow-_
_lhBhx_y-kkll_pwww-__Fhhhx_y-kkll_pwow-__lhBhx_--ikll_xwow-__lhBd-ull_xwJ_tbrrz__UNNNt_zvRy1-bEUd_R-jEUdF3_T_N6C1-tzQSzF
Ut_AyzFUd_Ry79mV00000000000000000000000000000000000000000000003W7G
}

