sprite $cloud_spanner [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000063sxSAm4IY8eQ3vk_-6Z_cYS0pQUIsCrkoPxL_VwUxJdZzz_lJvu-TFVuA_3dl-
Zfy_VVxq-UFdJvy_VVxu-TFdJ__r_kkcKX1q_uwVly_w-Jj-_lIx_BNRNzr_tLHUzRj_3_tz_jhiRyZ_SE4Ko8RSloxZB_xYB_xYB_xYB_xYB_xYB_xYB_xY
B_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_mlYF_cfHrELRd_tKiw5SNV0pz_-lpfywVFV_TmwpGazt_lB_dbWPy_VVxq-TFdVsr-yHT_
yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_JVVNT7yDzzTXkB-kwd-yVff-_vhkh-d-ckwluVwwaF-wrJJz_ZNTNzFzDTrVm_srUM__
mtsbwVUlwVwQxg_f_fhkh-FXbVwh8NrPm6lyrtbrnF-H1MJzSuU_7lsbSDGlykUV5_2W_ZfN-VFF2mZwFVvwzAr0UEYlykUV5n3qI_tv__jM8EXN-VFF2mZw
FVvwz6-ZGR_AdtzUGD2lykUV5_3pBL-jlnxzNYWSVwa__tzV20Rz9d_-kMFGh_Bddulu_FcBl_YBl_YBl_YBl_YBl_YBl_YBl_YB__t7N_p5N_p5N_p5N_p5
N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p57t_s7pm0-jc_Vm3qit__0kXd__u5uC_-_GEW
d_tx5q0_-_Sl07_sxry0_UpVFm3wsRz_0VIpV_y2y6V__W7Gp_up5a0_-_SlW7xs7xe0_A_tDu3FxDrdcjmu48DXFoC0jVU_y2O7R5uPNMoHDD_V3jFwn2fD
3aaOGgdwALH30DeQh-kQeRxpvqRKlwwBEzV_REtwLcg5wpDgqz5_VRNswBVsm_yPj25SVuIhXrBb_3FS0N-v8DXrzDlQez-g0ww_eZP2lpwRRFJdEaU_WPkE
ViEdLpnTt-ebd_xrycmw-ctnqM-jXz-uQNrRlBwrrZTkjVZDvbhykKhSk3pKkd3TyCRwpZz2w-4tR3hwRV7HRwtrZPlMjyNhMtNEHgDgALxyDqss-7EjXz_0
RHP__i601nP_87YN_mxiEVfjzT5lhOVVg2KGLsYsqP_hh6-WC3dNZonUtx9t-TTV0hXUi_hejzR3RrXZyUTMhs-jzOrhBFxSugFVMaU_WLlMjza-s9jhFVo6
DHP_3X-VpJRwyplW0rSdhhFuyn5G2zSt7_vDxu0Yhdx0slNDzLk1Iop-7DVERxh6m1ABFuSjwXUkORZ4uiznrVes-WhjD_hprrVJvHUkmR1bVSCP_Vy3MzOt
dj4_tH90a3y6hbXV4roXjG-_ORtHp-kji6Lzux2VuZ7wNVxTba3XUW96rFzihkU-77Sy_CRcoL_Vh3tw3Tonlh7vyDlQez-mOtr3TtrRU_GRDGokvx6xlitr
Bd-EA-NFTrmrvRUvtkNFSGnSSq3tuRU9d_jEVsDtVPldkI_76cAU_gZs-hRgWvzHGs3vur_MVWEKUFg_0zFbNxTb_IMU_jC-_DLtoVfBEFr70fNrh--MzHTn
-Wz3AUjVWQo_nDD_34fP_mfb_IMU_lqWPVth1Lb_2QT_Br1X_tf9s5zyz69jrvzIrhyKQFcVUFftGLgbMgHt6ax_3aXFPRL99mrE_q4FCtU2eCsT6q1cFFqR
wYVzgrdMN-BfF-A5nFLpMNy9fty6LDQ_1idwYpZz0vIo_gL1AkilyOVkJsQl8UjVGmNzusl7BVf3LKBtAtXtVGlwHrSF9DVl3mOJ45JMlzuYwoyY-1hEnVip
-TkKilxr9bb_YKd1XVipUVNG7K7zmNT0voK4OAlsX-hFXButFQW_-0xekuZWNwpO7qm681NshxSB-ult3xzDqJyV_OQNwjjpzIthB_7-uRUb-aF_fjZpLWVr
1zy1FPEK_mhBz0VhFmWTFxhWsVgMzHTnu_3d8-39_c0o_vX-ABRmg4e_wCpabo0kq9_9_8EKzQy9kBz55-66ZydxWpSXh-_-DOciluJWoitS7woxY73nktzD
9EiludP-cxO_amL8AUjVcaV-vj2Z_xuf-oEv-Q5GJKSX-F3VDbz_C019EX2OgpzO4SMEj_TdiFW7EYRf3ptZU6z_T2r-qskEf_k3UjJnQ7_eQSV7O_t1Lwd1
yKn_a9FqFnxeJqtaU7D_i8Mw7E_i3tAw_iTb706kFsN_uotzeMaTm_k3dTJi6DiVvEJzZu7zqKq37AFwizqlxTe55O1050H0TEdVc0pesKo2Szdtm-T9JTLI
60000000000000000B3b1hPEP4Z0daVOcvRR0000ZigPe8p0whV-0N3nUmRa8G00KFy800AkcWZ80000041Pe1oqkawAX070Gz2pptC70000000000000000
000000000000000000000000u0G
}

