sprite $tools_for_powershell [512x512/16z] {
xD970G0W4C0mzlVykyK5Cx7GnZK00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000wbOb
jgBLlM8hwZO6aB_rd_lhFoPxPxOblQx2uAn2OD_v_P_sd3tJirEzg0HZwVOVE-AJHPBgjeq3WFQhsTO1GFpDiF4047ypssy7fFsE_-Od0F7Vjm8IVmO0yT-w
0XB_JIiWxLSp1W3nPmKa_jjLGFeFSsrx0X1_rvN-KuyC-3C0YBzBC3OHxOUvM069_uud0F5d1IJ-303YlrK5fFr-vvSLaFZp123-303Ypm0W_lLtGDeFSmMV
0FniBbR7Vtu2sDFQnt-iY__v02ZdF_5d011_5mFWb_ZhcEZ8Zh-V00m05CHVpNNr2S3JNxBZpm1mgHJ6dm4GZ_-Z2lxp2eZw_gCe_jkU0DpznCuBqJlWzlXZ
7VmP0Aqw_jTNmCRTRm7yNJi7WChE-FC4W3ohGlXp1zI2wG-pZGE0kv_Qqu9ijmCIVrP04FzN1G2My9_ukr_10R1b-XzPyR--0kh88-8_5uxnavezAvQ_rFYp
0bOiVp0NTq3Ypmf8_6-hW2n_MH_yC00q7Fz7PlnP0Od_N925Tq2MFvYL2W2-yXsFFoiWyMS5h5V-vlWp08Z_N3Zg1u2XblsEVz4JWBlV_D-2nKWba_zC_xF_
f5cr0E0htq_yisgk2XMG-8ypUXf_1W1Mi7-Sb-CVfPi3WFYFv-JunqWVTGEWvST_F2-eMU8Je17_NxWVFm7S0QsO_Iu1A-0Dp_rkTzy5pJi0JFy0-sSwb1Km
6FyhxO_u-fOD0E8_8WHDMW6Lkz_4_XX1SmQ0e23-ZppsnvS0HFglWeEF_IVs1qajH1eO0CslPg7dVX8bHoFJ022iQZRyX1FBtnWP1q2ZJe1kFrrFtlePuT9C
5R2tdxvGuZ_YfPgd0lQkVaLl4x21_Quy5R0x_e82-AUstvKb07hlJXwu-qtiZvFUMm7TVXCNbi5V5iNVfQyFW7R2_Wvn0NpiVv7zuzQxW6w_VdzTUUjdl59w
NmLq-rl0bypob_O4cDdVzVihoyV-OnGEWExulnFndro96W7G_n9ENrlkVl6wwJ60ss_VNrtkViEry0dma_tjIxgEnV4_glaVVmBqxkNlxW10wjE_P0NiZlzN
0ijV8l_ZJu3-Zn3W__Nu7mNmZnu0EJy0RhzDldZYNp00tFxsFNdWxlSO0Shu6A3_AvrSPJxtAnW0Rd-RKBOc_YZbV_m0zFy42Hu0uf__LJ2ttoQSoPxbp_sl
601zXhyBVEKxWV-n0z1T9bCLmv_-TrUJgR3UntsnalqkksG0MkykbRbGe_pbzrylzxy5q9PlzvEY_iSF00AkTohywVzy04wMFnUEfLxvbbNzXrqR02tWYkTx
vVkGE3t6fR9h1q1F-u_Nfp_n7qClzR-9t1y0XkZ3d_wV7004G9SKV_flElFVv0cXqkv7_qTp_Cy9MNO_-Xyn0DOqWBjy-DD_L-pMhHbsFpJwVrgnLzuoBF_M
ss3_Yx3_8lnZtKAd_sSL7Bmfxlwr7Z00z3y6_-lzrtx6_q7_pIps2Y75xV_MVG3e_vNustYP3fmlV_tS0D3_OFmrm_C_TFf_K_dJaM00MYy_05go_CMufVsy
_yUQ_YCf_iZmzd_hJmm0_S-Fl-j9_7kpCTFM_iV-A2Ha-FWFtjblLj9_jH0XUFVBy3t_xRtzXZ5H0V_BxtukdCBVxPy70DOR04bP_cma683sqNwpUW608kKl
td_zRFzL5N2v-0z_uIB10BHtzXSAW7Z_stBupzsoT_PN3G1vFVu7ykr-yz64s_zEnVn7lFtvyNSz9kdlzjSCW4CJbB-Ct_zJtVvR1c1Z_6qa683sdVrcbVpN
4hjVlF_czbSE0D4AjtxY1m1k_oy60CluZotBtvnMS_jp1K1z_8VhjW20st_V013_smAWkVsL0q2qmYlVyG6WRd-r023-ynS1q2Rs5za1HJFOd-_d_vhRN_a4
U82xtrV_KRZzwKy0fd-y_ytjpnu0tFtY1q3T_ie38CJ_QxEQsr_P_n3x4xpo7Hq0vlPN7W1Hul_LjCBjdsh-LqPeLVjb8VnzNDl4_XflWWXAVDmtVW2qcMKS
WFhs2qO2_vibz5zIsj-Ax7ukY9hL7m30ZELlmaKk_oKT_JRAuEzIApS0S_k9loli48mVWDhsOwIGvGq0IML_k-2LRmv0D2E7g37zVnBo-1yV0H9d_uNVwea1
u7fHzXD_Lxp_Gm8L07_stOy143y1ul0J_-01GF00n4_0Om9_dkT-383u2P1OzsqKm3zq0FJI0G1y0iBSvwqVb-MkW6QcPqD0HA0Mgt7dAzyy0M1_IZ4V0V_T
PbNA7tT0-qi-0lAzzm7e9zlz601kgS-0pu7_Cm7U9on_303x95K0y7O8dLhFLxwl3u0Z5F-v2kBF4m0M8Ev-ENP0uWyTWm6m3lxjrlHd1RGuSVUxFW0U0VZN
BdyC0EBF2iZTh_xBu2n_68C1GFpt6W2MlxFuimAo_F44uEx7023-303bwLzb1qGS_lNjPm1mz-C0WFWN-a3ms1r_dFQV0K3ykGDcjZz-zsC0yDPFzGy4Zphu
FuBnPm3mra_z3mGFtlfPH-s20CYAF-xpdoT0_lAd0VRlkGCU0VWNtVqO0FLl_J001c_zC01oft-x2NyE07S_xe3voz-pql5Mr5BbBrvKRlnl4_qd_Xo0hUsd
_zZ0Vcfp_2cMF_g_CVuKyQV_6vS_QdFyAU9F_pSkVnJnf_zvyCUuMDJUvOywzav_QdFyAU9F_pVU_QYzyQSUZl-EzbERbp-A-DF_ZV6dTYz_z5ztjfzY-l-_
FJWG0000013aRpt20jK10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000W
}

