sprite $web_risk [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000000000000000000000000000002OlVl0QfX9eZ3A0L5T-z_mn9uyd5y6jsdftMy3X5kFZ1rJ
twAwG-FrTSVwQtJd-gkRl_7pnv_chsx--FFynL_D7t-Wl_YhK_t5NvtcB_xYB_uQ_A_IiQAEzbU0l_YBl_YBVq3ynL_ynL_ynL_ynJyX_k8l_k8l_k8l_k8l
_kAlZiwbjlYBl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_YB_mPLVLmc_azkLCNwywyg_fxr_-CV7Rl7_wdwcVldNrLV-zzy__nh5hX__gFgZF_xdl5_mlGp
zy__g7hC_ssx-3zX-d7xvtzKVTV_ylldNxF4_VElYlNdNxD4V_vLiVxyQvRepxygrfz_pHBz-LV5-lElMQ8__wfOV_urI_JdNnNhpxzcYVxygsBz-TSiqPz_
LQm__veb-lElYlNdNxD4V_vLiVxyQvRepxygrfz_pHBz-LV5-lF_h8hrvr-pG7_-drMn_lnh5kZFlsOtyFVuBulrxNzzU-Flxn-mV_uBidydm7zjFq2vk3__
sVTCkklo_lndt-5VU03yNz_Z_Drr5N_-nuaUvU-kA_Zp7wTxY7_z0V1_VIVvPxMpF__nhKxmhpa0_hjqWd_10V3Vg1Fy2mw0_qQTuU-kdVpvVpwrB_ZN703_
7ViZ_kxFc_hpdqt-pji__zanrlFptxRHw_dvu-UFdpz-_bVW7q-5ve-VFtx--FdZvu-V_vxyVV1_VjVXxmNG_7VZ3_RdFphOd__eO7_-euFz-OyEzkS_EjYV
_-XWV_wZW_tvZmxsvpyws9__w61__gE3_VcFlfa__pxED_fc_lpxWKRVm9__2lxZl-A_e7tvnt_7Vq4Ry9-D_u9sNh_zhsz7Vlj_NJlpyr_VplpyrxS1_pty
-VzVvg_gc_dpx__R2Vux-FFlBph1Vtr__e-GZWxmj_yJ_BVnvryh-VVtvrzd-OFzVVy_EjZVp_z6tzUV_pZ17-dlzp_ZRtMmlz__ZhwvF_-w0J__HQzxW3__
8zgVVsNxywyHxS-_iltvrs_xl_-m8F-k5MNldt_rsSRfRkZFlqwtqfl__cy2_pNzvjim7kXQ_lphkVm7_pKTl_PMZ5NpV_jfIVvzZRVYuvNnVqhZ2lpyrvNj
px_w2V6_tm6C1rk9pNzb5vi___LV1Ow7--2_ibhS5_eH_lnd-txqvxzv_1Tt9_wt9yG_PVtspvz_u-U_PmV_5pIYvy-_yVFFvUVV-Fa_r5ZV6__NPVxyS_dv
Dtx-kVpy6p__N7x-dStFVqJpy-ziVlwDdtykF__E_7iF_ZqxeiVFlxFv-NSsF_yZ-bC__yuUF_-kRpU-t_ikzlpxMkD_UtxyzzMt__Lby_FlQ7t-tLVHVriI
_z3jp_XtgZx_MQe-_rcgFlzPA3x_dksD_xuk_dzhAtdxVtsX_FnxbktFlxFz-NUsF__EzkVVsVxyEzkVVsVxy-ziV_wTxS-_i_tvTxO__yxsvz-TxS-_i_tv
TxO__yxsvz_P_loxi_tvTxO__yxsvz_7A_tVVo7-Vr3s_lbtjZ__xcn__ftjpxyxsvz_P_lpxyxsvz-TxS-_i_tvTsVxy-_EzkVVdUtFlplRdtztjZ__xbn_
_hFl-Bzl5l-Vz1cxV_wpN7_-is1__hDaV_wppslvyzSL_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_DTNuY_-uY_-uY_-uXyGV_4NV_4NV_5FYh_u
Yx_uYx_uYx_uYx_uw-1_bJwNbEslK7_n5ty5-uk_Wlt5N-7-2lONVuNxQsJxQuJxAznV8znV8zrV_BTfIFfpUt0W00000238ttgGgmy00000000000000000
000000000000000000000000000000000000008
}

