sprite $free_trial [512x512/16z] {
xTr7kkiW381H3xX1ZDx-T_k-stkDue1rpWxmBqYF_qq1000000000000000000000000000000000000000006ZzYA9_exL6BuleVnDpIbXE8KRvNCGKJhqE
0FvowjFwvRGTpRS8h_O1Ihzh0K1aQdqrU7UVwi_vK1y00A_t0028_dE0hGy00000000000000FxocMf_-Wo0tzVXNczh0W00OepnpOi1ujRjXJgYyUo3IL3z
MHpJUCaWV7vDZcfyfSeW_E12r1c0CaV2hvPVO0AA3C9Vrcm0Lf-4SnPg09OTX9JbcO0VcUU3nSGr5T57fhYrn6QN_zd85xVMo4wC2ufRLQiRWMTngqPs8v3s
xkA-rNjjUs-mk3NBPezxZFt5hQJiqjzCgfzfl77p2MhsvwJ_jPokp_v7_qhqHtys_MUnNO7zFmNqT_ZhN_Bqrn_zqT-3l_uL7_prHt_qztc__gSzsF_eZ_xe
Z_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xedqn_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_
z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4V_2zCV_T4V_T4V_T4V_HcJoUwV3_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tpwO_-w8_-w8_-
w8_-w8_-w8_--Fy7z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4V_LFgZF_gZF_gZF_gZF_gZF_gZF_gZF_gZ
F_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_hdqX_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_z
qH_zqH_zqH_zqH_zqH_zqH_zqH_zqJ-N_kYF_kYF_kYF_kYF_WUdF_gZF_gZF_gZF_gZFvl-bx2jGd_AzaT_DlrpRMkftf-cVvwse4t_BDkQz4T_z4T_z4T_
z9y900000000000000000000000000000000000000000F0V
}

