sprite $gce_systems_management [512x512/16z] {
xDfN0SC034F1RljF_DcMH6TqH-79dSaX0G00000000000000000000000000000000000000-oxfehu5o6y0yXk0_By_04P_v_zkGN_qhoA__lhhh_-acVwR
du7-w8_-ZFxENt_zMmQ0_kYF_cnbV_H7VxPj0EYF_kZFwFy1pbz__MzffRz7GFNVe3_wrv1VV_trrzyN0FqtNuV-w8_-ZFwkNt_n3S0Blm4uVHDG_y0BuCdU
kQHPYuL0SE8dpDZ_RdlOqxykekJ9Y0LKNOWKtySh6v00Tlko2O0x6t0tYDq-Cm3z903x903x903x70YYdn60_R44G6z8Hkemq29vchl9bEA90NVuy8xJx3yU
yEFttGVfRzgx3p-GQ6qcaPBSxUxKCNIsavIbkkasENFJrj_oPt4rANvlL8epq1SzVkzKojFiYjEJEfUQ_eP1fsk9lpOhpo1Q7R6xRA-Y_sU7PZSKVsrN7aJd
cMNBktPLUHIDNiG1-g5n6TFSFtZhX_1-IGVCDtymrW_u1s_zS7k_dm_ccpyOwmVyWxT-26__OAuVq3_VoCZ4Fqlq400Mw8hSneN_bpUSKAy3_SR5e5-W8FnB
x2x50e1-WRBmhtMnz9880FefxaFYy0RXVtL_gF1Rmg4t-5_P6if4ly6S2wR_XgrYKQbi_bJxFdoA5Vyh-k5SCVg3cj7_5NnydaQO3m2sWuyAntyOVuqO_MbT
VTYV-Z__So-b0BXl_cC_zD06eFyQdQxuVvCNVk4nFK3_E__6TbMeQ_Mnxtj92zC1i5d_grrEWm0eLVrwuF1_vblyiNGNWFwtJCJAReIT_--sGvrse3z7q6W8
-Z_-__XVy4Ljqm2WFuVPrfKB_--UV-tj2lhp3S8W0EZl_HJylrOb0N3G7wKLWC3_sMlt5WDWPuMnP23X_wi23IO0_XVyClo_Lfzn0F0VzGF7103_YtyT_XTN
vnA0caEyl1mdyB-vElK1mFf7T_NujlsNW7w1xKit0AS_0Xm2wTOD00y0IumfWVQ81k20a9w_28n4lWyS0BK6XGflkG2m0CWHSyfY0J2D6gK2m0AGLKS4W0M0
5rKfuvy5u6k4a0z0hKMZJd7_jHYHEfK3KAiHAJJUVHDtsUk-4fsDWqvN-03ylb93S02K12grgWs0kqIGkRxvcl_8FYM4IhMXCm1A2fboHVn7YH7PGtFrygbs
b20o1UyV02M9JiNv537J3552fkJv0Q1eluzEpMjt02MDKD4xTm25_xTOk0Eeml-BRFDVflulNV_tm2S8xVnNiGDuimlunp_-Sxj__6VDCN094F_FdqGlypyu
04gVU-8YcimbOFpFT73gNeN00G3-XpgJGlxndx5E__m18FurrWQOye__iVOa_aSOleSgzjug_fz-XiB9F_wdUfIo_l6VKLrkOV_uxxSffVtZFtFNYy3to_xn
dmBhLk5_T7ukq3_i7_y2dubg583_Plls-w_0_-Jcitybi1hqZ_-CL_JtlE5_SlUvtty5_YSFdmIMhH_qZ_-CzVwhy3zv-gJmsHByJvu-Z-llpvzxpZ_-ynRu
Qj6SV_ndpkllQyF_v29gyxVz-jhmFxY6pYNmNRuv__ZFLFXevPn__6T-vR_Vfk3vxx4uPURw1DmbJwnOH75UVpy0mVl_O_up1loFZG3y3wpL_OB-_Xfc-1zS
HVk5K_--lp7_-C_e_vNv1CIKV_nd3kWV607uZo7_cM_vRqcqzZ__7PrybwY_q_2F_tNyUDsaZW3_luq0_1yKW2nR1hwaIm8u0D3ZhWV0VwGiw3Sx0201YV-7
0y3t7rCQxuqV_tcZl-S_KXnc_-a3W0Ha6lid0BCToWF0_k_tJF88q7_Y0200QUoV14G-H100GLxgJUGfeF-dpkGn1Ff_2C2Lvu3ztW3G1_q40FsDzNlqmVvV
3utoB0BzhOMqzK7_tpeIUHhObni01E33VkHve5ye01m7Hdxg_ye3OUFN600aOC7Zqa40FYCsj2BFn7pp9m21_jRNjFJHzqy0-fNZFtm3SE4_Cyit06dkdm0a
_hC8m4BIEW0aO5a7xZoNozr_52E00U0SWBJsJm0800am3m012Fn_-QCg14O00OZ1ZOyHy9t__FHdhTd1481lNqREpo40twv5mIAo_xCu-WF_L6a4480Q-8Sa
uEDElFlhXkic0FCdGBCha920Qti0QlIf8uu39N9_wCLc0l3lnCmv1WbGAdhWSzq4GA_e-xdBwaa2mliQA0b8xm3S1C3wJYWZW3kX180062U0fs7C7mvA0k3z
VA1ynUm4-k4d0Ru1IEi0i1E8j4u0nu765y0O0GI0uy18wmHm7EXz5uGH48UN7CR7WOJ-pt__yXi1cKAf_yabHm6DWbMh_lsl4m3v9TEkLbFnhrrv_syJ0DdQ
7_hJ708Arl_aorVu_vIP9tgvEzeeTMyVXdeR-Dz0mv3c22W2iAQzvlU1I03-6G6d-IS0KNyWpFsJ01dz-W5W9x1nLIWIuFus09zfKbaXZ00eNmyiP__i1BmV
WEKuqFej64Q0zHFmN0nGVWKYV4S0_f_e2mcex_dkIqli14BI_rDTOGJK1fg_sUXhhOhwvn-cC_fKwvaBeqNpsdaOVQhvo5VXsx_MwKlTv-clQFzM7_rLv_cl
1twfqsVwhHP2EV1MmbrDRfTLSUF4UmahxflKBfxvZIxs-xNMDfuPK24p-lkSvRyQydL6m9PxfxMHXdsD1DJJXBH-NYxlWt-Hmu2QGa0_2LXLwbKMv1gMLLek
YDZl4-RwMM1xuuLV4X0B2oqtRfDLrS9SFwjgcVjdLQKB_IogP7pgZ_ygxyqV_-Mj7_zLYgV--9yljfm99_-5_gy7GAmg5_tbzg7HiDQF_wfGju__FdcNCVW7
_0F-GU3ZieE0r-OF-0Vy0_u1_n3U_i57F-0Vy0_u1_m3_Y5V8seXuBNv0_u1_u1_m3-4jN-ul4__m6Zp1_m3_W7_W7_0F_3k5_uDDt_0F-0VpFM3jtwupVM3
kNu8pln_uh_su4000000G92_zGGRL0C000000000000000000000000000000000000000W
}

