sprite $cloud_firewall_rules [512x512/16z] {
xTmt3S1G04F1rLluims5bDyitJ6mtkxh0000000000000000000000000000GAeP-ux--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-_
_lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhVpO0000000000000
000000000000000088DK7B5tZzL_CVtrrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNN
Nt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNN__r00000000000000000000000000000018DMFVqrz__VNNNt_zzTTVV_tr
rrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_trrrz__VNNNt_zzTTVV_tr
rrz__VNNNt_zzTV_N0000000000000000000000000000000P92A8_xkiVeleB_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhh
hx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwwxyV000000000000000000000000
0000091gnlwbl_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-_
_lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--gy7000000000000000000000000003S
}

