sprite $kuberun [512x512/16z] {
xDkt0K8n68F1JgRp_jlIkoA7NtShV8ANzmi100000000000000000000000000103hkC_BKBO2K6uDTl0F8RWFmr_T6VL0y0_UNNNty3q5z_-VNNtm3qrr_-
hDrC_spqBo1_qG3G7_tbBnm0-gC_AmRWvw-__ku1w-yFG7xzzPy_0FGd-klVE03q9_hhtpW0z2Vwwzyu0FHdnG3y_1lxepyn0FaR-wC_CG3vzTTVV_qDG7xz
zVSXYFx-0EJNN_-H0q1_eh_-ZGD0VrPrV-xjEMi0FDXnI7-UAlWp_G4000000000083BQPUG_MGAofk1z3QW_S0DY6y3ufk0-2OWlWc8RmBgMu3u5g2-1QXl
0kfRWFeMeBu1o6y1wbk0-WOWlmMeRm7o6u3w5Y2_0QXl0F9RWFm6eBu1o6y1yXk0_0OWlm6eRm3oNzcxTyJcSHW0mfsD3lS_xRvtsUrl1Xm3j6Vgc6BqGSfJ
oT01aFz_Lpjxf5d9_-lb3ezRZad-bzO33bhFZZEy-eOJ1i2E4nJUzge1a7zpHM3-ifO1vtuVgy7Vi3DVVCty0T0_LpN_rJK38F-F5yLdaK_-mghuEFB93_W3
MqAIlxOkkIi--JDX__i7GFu45kZtrp-Jyvy_0F83_i3saEJF1Fnl7G3vUV-Suwz_0lvzcpJWn0B-umP0VjwV7m3huWzwKhdav_tvpVB9d_4n0w1_zlldQ7_v
UNzYn_BVV__d_VKFmd_cju7bvydQVqYj_tvz_j7dB_-goJ-OtSg_NuT_ZF7NFt1__haqYqAqF_zGg4Kfr9_VgKMnj_a7iLEBSg0_lq_vwv7-_3RrhrSxJFCk
vQ_7-iTmV_q3z0zua_Bp9nTuwIn__GFn3t2B5cSh-3TiqE9qLNz-WzlflwDmqd_lk92__9iI1Vy2F-UlVs402lwnKIOr0Fh_W6FVlyXF-dlvxuFi7ghAZms0
_WMIZKCLz2D1V_qBAgl2c--yaF2Nlpu03MC6383-6LjjiXJugHk0_FNd10jVn3FRIokSgnXKuPsodvwfoVoyl_uPlTKtbrQwKeAEtbjQwK8PmT_cht-Eqrzn
_lAlkldrVwd7um6TfkYCckp7uyFmEV_ivCVy_-nZyAl--OlQ-3d_V_i4VEhoNutYNvNyhn-1vsC5-sSJFti3MDrvuVF-gnP-tdzrApxxuN_LnC_xhox6v_rp
ZlxgbF_gClpL4_ycIIS_xx-Q_VaUSVat3W2_ezVzLpTT-Bp_gfcVlm6i1kBt-sSxF--_6eVVxvyJ-7d_LJ_-BF_4-OVuh_e-tzi9vb_1_8FyLpqN_ap_7C2_
WlrN4_7vspy_0FnUW7CCut-hVpB-m7a6zUVxvqyiB_TVDNpAH_hdkqxw_Vxy03m-nN_KAFBdckU_tp-HhMI3_mFclz-_yBBx_VMllMw-_sEoV__dNFdD_leN
i2xmrvzyc6Yyl_xmCpkJ_VKF_bcYiJy0q3y2zL-DyzS_NWnOfzjV_rZn_gi1_le3p-nk1FlhN-UY5umMV_rZrUI_elprhpdn_YlQNt_-d-z7BTnV_oX7-Az0
V_rZnVdN0_prZnNkN--el_wnckw_ElBp7_tZS13__kxrpz5_ifTF_vR6yElVrEozwCytOYVwDpPW7_gtrhuB_PlhteF-LZZPu_rNr_lhd_fVSlk7Ujxm0K3_
PrBTuAz_SZsd--l_JBJP_lhdNON-NvtyNnvsHXcbmVxwKqjpUzQVF8qiqGX__NFLGQH_CVJKiVohj_BhNrYS9CBzzIylpWiXg-iFh4uAdLnTVs9nMaZ-rnhk
7_gpDTw5sm-TfZ-L0n17ylQl_uMNl_xnrVuEG1nAVYxz3LA8Ox7laNsdVnfvkSJ1Fkxort-j-97-3i39N-gyZb__it__Ou2__j7eFv_V0IY80aVkzDT_TwNB
_Hq0th-VN_y0-4i3eB_-_VmEG1tpp85XV_tZGd_v-KkdJWdE7U_l3Q0koHwNztS0UFz-VlsZoWyDWForBlUF4VxU0BW_636Ptm7W_Tczspl-Yrjb1nVmEm31
-SUHZQCv0EJdyF3bR_G_tAzkOFhbxm2mtyE3-OtzDuxb7GpdTm22zO_YZXF80IXTlOKbfl7x1m63ze_QkB8v0Foly9NsokO01EyVi_ZrZrEN__uoWVXRRDRW
Fv3V0NZF8tmD_FgNd-G_ju72Y58v0B5UHFj7OKB1782Jft_pIFty3i3x_8FdjpZPNOSt_Qtv_7VpssX_djzw0ThvhHUWdT_kzyzArYeWl_wz_DPAqCzl5_jd
CUFlmjxz_IB0J_tzFf3Vz_5dGT1HwbbSbcA_jql70W000023_At7iByOkW000000m0000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000002
}

