sprite $network_topology [512x512/16z] {
xDId0GD130H0AB7hlrjJVuveVwO2nHrp0000000000000000000000000000000000000000000000000000001KpzJu6CkFFu5U6ZEMdtW2VSJsjrJkwXr1
-5nwbnk87ahV9VeNAcxvJY1t8lq6wv-AQim5X8wZ-aq_zixYm68WXg6BOzr-_zKkqpdWoDgd1YBFqs2emFz7CVH9W3OfX3u9q4P5q2S1sgo0cbW9LbvNA9sh
elj_QZnz4X0t5Af7uBTiXgKkBJ-Oy5Udm2yf3V_Osk5VEaqy3UCV05qX-4VXdre-_2K2SCc4MLFn4u2O-fUkr8B_m76CRS0AYRysYJaWf7Wv2Fw6Wt_-501_
kGZ-Rhq_VmI0ltm4_tx9IV2VLi7eXo7WVuxd8Iq1__CEh9P_Ky3_ILjKfsuidk1lRJ_chKZuT-pGoxKnuDzqFbCH0O1_DPmmmj_MU-UruEzcFUtZI3p_qSs3
0M1izt_gFso0luzlWulo_7V4HtmP04nglIgRDIi0y5yD2sRuT-jAPmHWJlStk3ZylGaGWDZkNnrx9lW7u2S0WTtVnO6__ZT-0b21Htyj9XW0Gl4J0DlwJ8Qb
ahWFRElKpOU_m4y0tF73d_-_6JaButy3lxCP_lyAV_x_xEKjZlzjFduPsecQ1Cexdkv-_5K6zE7l684oiENLtBa_22d3GZIG_ojxzutUE1G4OJ338CFzRwjK
tgk_5gOwNVUJHM8TXNTUnZyp_fBuytVvNzd4VsKKV_xy-VDNvUr_jopZR_ojzBzQfiIVlwxVUJWVV6jy_FCFvwrlMU3F_sbyuD7mxrd5e-7Fdpz__lpvy-VF
l_MJriDV67zX_8Nn5yPV67zX_8Nn5yPV67zX_8Nn5yPV67zX_8Nn5yPV67zX_8Nn5yPV6F_ECFx2-0lZBuo_CFx2-4VsQiecV_vl5-pmvx_u6UD_5Oo_yJV-
nj_uxnf_us_yTuw_yJV-nj_uvpS5j_xbNu2VVmdmRyBFlmJuD-ddNm7ycyBoUVnx-VDz_FEN_e9ZWFcNHEKJ-LVonnhvD_Bd8laNyWSh-VVn9pFvr_57E_ct
yMT3-JVzlJ__xm3ycshofVox-DEf_Aluewty-VElue_6ykVFlvi_NykVFt_-_FF_z9V_Hq3-PM__T2x_mFZpFtx7_-3_Fn_D-KlZpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-Vly1t-V_-BFdx_FV_FtzH_y-VFdpz_NV_Fdpz_zN_Zpv-_-R_pT_v6_-x_oT_zd_kx_pj_v3_oT_yBV-K_ydV_6t_cF_9t_
oj_vp_oT_yx_IvkgIp___APBdtz-quNFFxyfmETl_8t_hl4t_iRV-1l_NUDl_8s_yJV-gTKzaVppOPund_zwunjNF6FydwOKXF4NnbyOVs7yXV4NnbyOVs7y
XV4NnbyOVs7yXV4NnbyOVs7yXV4NnbyOVs7yXV4Nnb-OHrCOndzMFytyJrtU__oz_tNnryMV__EEXVxyt_YM1VxyF_ZM_l4t_iQV_uVRcSMVFt_-NW2gN03k
5MNyZR_nv__nDBa0j2KPVwTIXowszKLEfUV_mCvv98eAmp3mLwoTxt_RTmKIIeGosbFaaKrd0Vmd8a00oWt_sDvLBd_QNwSKnrzHkpCloI00y2-3qM-mXv4L
Bzlsqf2o-8lnBwK6e8pis9PMms80J2W7lnJ5NrktlvGSWCFbbBPCpwqrAGP0HFjBuG4mCIFFzYzDgmZ0UScx_Ha0_npQp1e_Hu1vHUANalWhT0_WVwnsevDQ
Yfy1eCpDmx-Msj59rMhy300bX0_-ymoqhiW7_1si1cnueYccLGJWe_XROW0yV2TGy7VH0a_UPJnqYuv0_dfzY-LK40Q0z79xTHP_0k1RG_W_Rqo2__S3K6zL
jk5lQZdfPNhur_FsDAw2lxNd1Uk7lvNfUhAW3NyNr_CPg6-K3_x_xlUgAohuVz9sQqBhySE_vQI6_-lQ6p_yUs_yyE-zySE_mR_w_Gy245A3_gRsnW__ziMV
__ut0OYfG7zNPOa_dpy1w8tv4u1g5ot0pqb0zyRy2K2K-nuJ0QZUc3y92FFUGo80OTuxHZRqO___IW3Yd7UKJEWd_l-T10JwxZpLblYxmVza0chZxs99G6tv
QmJE0_Wt2Wa8dNlL-JhsUo-Mvf_eYAGMkGS_4QXSlzNRQQypuvgdJmOwGZKCdnIa7_U0_zCU7100000G0Fg_6dvK1m000000000000000000000000000000
0000000000000000000000000005
}

