sprite $data_catalog [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000000000000000001Wzku4EK8SXi9mgkMMLIltF-tiezazXk04-Vtl0cdqIRQXKxHWpDmFsQ1l
5k7lGpNmMqHqFpI3lbc4QWUWd_wYcm3wwHzThWFWJt-zJG3zzDVj0FJJN-8OG5usze_kxH09mv_-afi0-kaliWcWF_RNkXU4F_trDW7qqr-i0z0V-sTy-mv0
F_q5Zm7mfx_U9e1--kjs0FhflzynW7pO7VxH_NNi68O__RKs0VJ7_kKV2PDcz_f7t-yOmF2dlzecW7ucvjDtsmJGJt-bOm3wOt-PHyBmfx_QCG3zzDVj0FJF
-_D86F_ucp_1d-1Fy2Vu4_m9_WH_WZ_1d-1FujDvkdzyEjhy-0V--Eloun_Q_lWtQNxyGziV_mx_Plui01t_4s7yyTVbnp_mnn_--luq0FxS0uQoFmj0n_z2
67_yTVdn3_pnr-N7F_37NvSV_z3snp_Wnr_tqG_-mVZZhykFV-2Flou__e4__hhy-8VslH_-NNhyyG_jySS_67_yTVdn3_pnr-N7FxJzyM_I_FY7zhqV_dth
yLTy_sUS2_nb_6c0E9McwT_YL1Z_8lui02UlIzN_sDG_TFrP0CxlQwB-vnl0fSSV_u2_l7_z1i2_u__VwTzsHL_bx_weQU7UB_CL_jqVLozM_ynQ_zHd0NXg
Eo_rx_xUh68RTlCwV_Tdb8p3tpXh_Bi_OcRwUiNwbtA_V_S2GyFgVxe1RjpusG6Uz3-DT_gxb_d2XF7FtENVVSl22Tp9tE7VlLpb6F_v1fZR-5a0gkvYd_Ft
Tz6J4-EVkUxVVR_Y2Tx5lgxvTszxF3cXWw_uk-zJFZx_MV_kUnMGEvWp_jstgo3TE-tV_RrZ2MdUENz_xrf3UlV__RllN4G--TY_--RVdlF11_xTt_i_Gc7X
-Yz_VsiKaeVN_-RVNUSh5Bes_LDVgfJSjxG_-tTtjVjeRblIFpT-cMAoPsK7vDAljm3msFB3hFjBxaaQ_1dpsb-aEVxV50eAFoKLuwUcZ3_VfZ3-L9NnfwmE
Vu45W8tgzl2F0Ap-J5QZ0PunMPq5W0CWdnD-mNMAqry_w5J6N_0823zV0E3FfuLVzLQLmrySz2lZBte4XD_fMCQVpmm_Hq0EVtGjuq_RyhKlVSluyydXP-NY
y4VlCluR_iy2uz_eNiQVpm-_uB-jm1zqCEElUly2VwE76N-k0lu71NyAfyrFuHpzgzcZSkBwr4wRdzg9wrCzRNtAzxadLyIhJu_uy5D0RNqgYFwo6lQw7zv1
FPDUU8GO_ZjIk8ZY-fGH_LlIgjQnttDc8LNdI7lugMH7_xQKB2NwzwNaAC5_CHJpPUx7Th7cZKwUY9bv-7kxYsfplpIDlfb7z9qweDal_Z7JrkYRUVoKxdjT
LOiOTm0nI_zzEi0i_MSk2ltqZt3VuwBIVzm1wAT_rghLlfNvk_zu4q0__NUO5hD_zH-TRk5F_-gRW6NIVwAjqK__qkkbsT0_ekT5eMzZ_-Z-EahbmmR-exP6
F_qBhvTcC_x1CS06_cMdnMpAdsE0sS2_whIOJVdJ0MO3_xAriYb_ZW4l6_eNxG2py_xHlJ7y0_yoqs8svSycO3RbN-iOO7RUF-EE_i2_mBJOLVzSsE0V-3_y
sPdPhF-uhT5F_qBhfTcKFnrWTiQ_o370RDvVUXDusRn_dMcnw_vQZuJDvltBT83DfarVbBP--bTOBytE-0jtWDbf_-UlbsRt-cVSLVNJly2qs2L_mME0BV7F
z7U1Yqf_kKt0xAh_Wuy1PXVy5Jl0x4R_fto5zhBh_bh705lid-d-y8jgAoyA_-Wx-MVmn_zwyCSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pn
nnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pn
nnz__F777t_yySSVV_pnnnz__F77ttVqxuTY0_ZJVobzlNzUb683-FCBzGN-tT_75ZdlNw1GhzN-UL5w7U0b2hNKl_knKpxE-HSfr3B_xgzZivpoBpCcQ_pT
Zmrpmh_E7hd0FtjQjWEyqWbfsbzNFzCc_MiLwaR_l9MHNWAys0dfuox_rDVk02ztGhh5l_iXaK_xztV1YshepzRAInPgtd-yyTC1NhDGRUm_k_7J0LwrK4D_
blxPOddTGWtyqPzTBxroeKxwT_T3DWF_kYUaK_x_eay7UF523VnP-YUUdNdvGetznyymMG9yWp4P-RFqZslbEpmQ6VYFRsJf0D-ZK0F_qOh6lQ3lKgY_-GzM
DF9l_jttkQh6nZzRAzzeJ5xfFzlJT81lTK9AV_GdQ-MR5IhzsVYdQkNRZOcPDJR-sLhvrJ69EDOceb-zg3RRq-IoVYnkW1O_PVb5aUlyqTV_YJWU6FJNuppu
jHpePmhybGM1VxbCWJVpeBzEfXTuDnFwwuw03tmx5-dnLIoFVpyNmvyf_QVE1_trA0LUqOZ-EfE7lQIHU0opmh_04i3mhn5vy7jwEVMl1sa5tjIC_hfDkS2x
cbdwryrZePUrevyf_3VdW_vwYm8_sC36luwY5_Z91gP_dKGiw3fIXYAg-kCVZ3yBm4RZJzfw3VWv0hBwimCm_Xm1MtL-6g0Ls6t8mfbazMS7uF374L1W_F5V
4FXfW4ST_aZN7dyYpa_mnr-OdsWV_eXhZpyHvoVuuo_CJxGFVwHhZpyHvoUi_lWBZp_HzYTTcv-8ynFyloVumqy3-F7D8UBZJyJv2Vxu2_CJxGV_f6kFFn7d
9_ZZBynFEFpXBpp-1FxbeG7mnnz-6g0TZmiH7t-YpK-QjZ-1_q9-R0yE10000004-LiFSZK3000000000000000000000000000000000000000000004
}

