sprite $premium_network_tier [512x512/16z] {
xTq7rfqu383H50xcLEr_jTCdIazuy8E5xbr0YZ-BzbhC3G000000000000000000000000000000000000000000000000000000WB7zGZmGMqfsWdct3Opy
RrYYAUbj0ktJY9wqjmUqJr60-FQ0-BQ0stiN0oRV5X3VYK1yEq1zMq1yZuZLTp7eRizfG7qxG7qxm6dV3Z3xTe3PTpkelcE08_-jEu1rsyKESEYt0zJtL5Xz
Xm3vxG3rdGJKTmYGtmvGtmQGtrM0-dF-_SmpTzSV0fXltieV0kIlyGzZpBt2ezOECFoL_esKMTVPtntcNHwrzce4zLPps03pvLzgNg_AN_M1YcT1iunHySrh
-ElEpxqRGFxE_mdvI_z7v7_Ekec_rtZOPVELzGt_6lDH__Szyxcv-B_fiGzCtho-_34tzTyqVynF_3VB7oMCvlNTAe-MzULFuf-SFuePwf-OFmfI_wpy8qfQ
JualVvJLihxyQNIkxnKov4T-kjP7VhhMHtvyA6elqs-r6h_HM_n_T1r_zV_JExylGMcUtpLIn_pgftRvX_eFwZyC_x4bQZR-Hlyh7VEhdphcLp_9twI-_AtZ
ww--_EhBh_uJ7eKD-O-kokWp_aPVVlM_9B_wBVwtJlloTnrz-HVrlxOs-Z6lqRg-j_o8Bx_w3rgHHVu3zTTM_t7r7xSWG_vrUvMNjtotTTEZl_gh_7xMeCy2
UCWllz7_NxSBtw7-KrR3-6zlEFpo-n5Rxsls--LhAhyKG_rzQx5-hVRjZ_gVxAoV2g-6-g_dJsN7V_Zf-WFvKz5n64R_FyjB-PEZVy7wALxCdoekYlg7yoVZ
N-oqdw9dVwF_Z-LG_bHjPHRrSmeQzbV_bFn9_YhnKpJkh_uIXVhBlvqiJicV2YrHgBz5cVx6VzrE5utxTntz5F70_cLVz_bfd-qDHEl-HHxadbq_nHpzvL-t
6upGVmhRBI9cw2__Dd_-PFnBrqzHjh_ynutGVmAZmF3ltG15hgGT-v_PlywZdr4fVth6rP_yhsev_exzgUNuov_Avayk_8yucD_uhmNk-Yj-_dFPiGuU-1-m
b7xVX_p7lLnV_zh7_lHIVFb7WVpr67y_PYc__1txos_yvHyT-wjl_ENNN_vHuJxONR_nRply-Y_o6t_vzNVgFrk9HJ7ynbz-_HtxpzRwVJ_o3_q_YOOs_MVF
x_0_v7VuT-ft-3Vy9slxcJ_vzPT_w3zzVkCVwkill_ujyyiVyklVeVx7fF_dEkJ_-1Nvq_FpP_SKIVz6-LEF_lf__97RLtNeVqF-TFV3Np_WTKl-zFJ3l_uV
VowI_jVcrt-DEOnsuv_kxE_7Uz_QXxlwrvgIVkEV8lHVzEzu-4yFpVzE_z-pTXn__LExcx_K_lIll_vnTNxzOoxwwrysl_x7bSwl_t4z-z-rb36TzSByxlzZ
Fa_9d_JVvRBy-e-OKO7yDLx_ZL9hbPwHF-c_qw7yzGu0ToraJEiH-TES_KVCQtb2_dHn_bHjjTAssnhpkZX_gfO_7Hz-d__wIxdbIe_wTiUBywTwovNg3t-w
Ed-gjrof_kodg-kdUlLJvSk-horNnqyPlvxsN-_4q3w2jM1u000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000u4y
}

