sprite $bigtable [512x512/16z] {
xDctWG8m54J1G2vK_zNYFKHus9aMzft-0VC10000000000000000000000000000qDV6Z4JVcw7ihm3pEmBc3tm2xAy00IZ0_WAmlm84e03x2y3-8GNG5M1_
0GX00VRFAu3HR_Eha0V04o001TXV0G88Pdy524010WXcVmK8G04222001TXV0GBmgv00F042K8007041U084e001_6a1ZEG0y0JG5U06_4i0U08e6ua5KCkf
LmOmvZUp_aRI4q2v5dm4hBynmuw0fzyHyCVl25Z_bK_0znTWVKV0_8w0zHq1ws_KVtq2hEy8cDyHi7xC9m7hruqIUGJCt_hEahqxMN1KsO4ml90oyOxtVzex
JprajUnV4EIjqFOCRVY2K1bSxf5N9k1uO08yEN-OWHEWVoha8IJvFNyCC3_O0fil0Uihbu0-0TRt4Z3_Z_DDbe3rjra2ORLEVP00pLEXSNS0_6jQ-QWRWYDj
rthnxxO48kFaO_rT4v0HNG5mzM-u14Oq1C0N_xOLa14i0TRVEW5P-Nzx-k-xFkI6O8Oe0FvsdaTKG4Ie4k3lPXeXJq0e0-1lPGbn0aQ4D07-OZPj039q0R2-
FW4PC03Mvv-uYv0z5KhmVwRZYrzV0U3_ZCVw-WI4C02kVlqxWH04m1U_e0AEXRym0DRNBu4G1C3LlvoyD07Fz_VNSCS70uuY905mzUkNWDxVrQz_9n220BZw
jKj0wk_groy1jR-hNxy4xA__hKhbKo6flwjVlmIq_gv-VGAq_gv-_Oy1VVxcVn_r0HNmkV-dcNVrPqGy9W6V_Y-E3qlFrHy_Z6O9S7-qz5pzbrS0ZrRn75d_
0FgI9S3zFmk_gtynWey68F-9_LtzYXy3k3_djxvW2M3_zVDGLp-04rG0zr-S0p_aXsnvnrCXxZ-1lwjVimIm__f2SVM3dzi5Iu3wJ-3lwXSdWFk3K-7grou1
dRz_wgzFNXajx5yu6zOd_3V-x-s_dpwl0EG_cR-hd_Fp16pdR_trtEe_vVwkVlw7FS_V5_z9vYx_mdcnVdx4poRtztVrtrS1Z_DtzVEvtdyA_7sxhpnx-xlw
-Upjx-hdSwN_5FdxXW__THxx7vlgvxjfURA_BtwY-V7BiV-c5__d2wFVVsxil-VjlgRQ2FllNFsy0ko_ipvFWFrtNlmyGlRVN9zN0FS_le7_SJwp-da2kF_S
sVyiN_hw9ptDOKhx_tqEW2-jVbu1zYSFiFJLpnDW_ny7l735nSyJO7yoN5__mK7xiz5NFq_0_lxMvt-4_JTV_Bm2zFxMv_oV961pVrS_Ju3zwwE_tTSV0Fil
HlmH3puasdf_Lp-VhVrT_NpszlVjFZvx-xlw-Mpjxni-VFRsjpwVhVrzkuzFRktlnSzdRtzNFv-j_NsxZqzkxU_gvxEtls_tyNc8lo_-3Csa_G6_llhvoFtD
7zgnFr7Y-l99-mCcNltwQVUtlq2VZFq15DVNJm9_-tDz_TX_FRd1ukTZ_zMqyuynuccJnu3-zZ-h_7FEZ4VDUBsEGVpjVrRdx_pFIi0uNd-ROtxiR_zybt_E
yPJgdwz_pc5_zgLRTVy7LS1u_MVcH_xs__ohXl81rG_zxK--Qcheg_-_SxplRt_wLMCfhVuVvpr_-sTsVDLSogeV-Tj_pBF3VmvHzHD_-sVr4FFFfoi5rK_y
xP_LGuo8okdAcwiV-Tj_bFcB_dFSMlt4t_wZUeGH2tzI0RpwYR_zitg44Gj_aW1U_SZV_gDuX15l-yyXgVwwl_r7zGXZxGyg05S_yRT_Le_mY_CrI0Bwgxzy
_z_-EOf7-FKjuZ4cMmBzrLzu_c__KJp2nVdILi3ue_xuwZ3idzKZh3mY6Z01_TK_lZmE-u_Y4IxFbsO9rAlV_ejPyq_qD_Eo2kYlVlkl_KVj2AFepvT0V_Ml
_Uq_QaSOHN--1FghV-rl_wmTOLJz-HBeh_wrl_tdQZuwNtm9z5U__TSJsU0FAc3SKFtsNq-CQ_tv4k3LR__rnEpsvqk0L_-2H-1lVx04GFMh_EtFAu1NlzpV
_Zm1lFhr_lRdIu1Nl_tNSua_hm1U_Nf_-_C4yEhN-zkVBm5U_Q_h_Uq_vqKLCEZYVztYR_yvOGNClA3wx_lyh_rdznB8WrR_wqP_-pSlWOch_rP_-xSiWSRg
lztV_hm2HbVr2_pjtxG4UFNB_EtFbm2lVfs__Na5qEfN-jkV9u1LlzRV_dm9eEeN-zkVLm2eVhc__Na2GFNB_UtFbm2eVhc__Na5WEgN-zkVLm2eVfM__TVp
TWM0wfVxsvyl0L3zSd_xyoK0gb_kRt--143rOt_xq_F5bm2e_XL_lx_zknFmWp-e_eN-fVxsFu-s9T1P_TVxsxzU0KSf0NtLVxs__VkNG5_rz_k7_HV-VKkW
f_e5_lRlM0ApiVhh_W7yxT-w13ggNtJzsvyl0QwlyhS_NmAy-g_q7_PV-r-_1A0-zm_xh_tv4k3wd_hNJiye-DiVBW5U_Uk1TxEZw6z_lWJunL_tBxxonN7R
doy1hbyQT2ixxL_ovqk0Lt_TFwilktRSzkTBW5_yTV_gYnwruxO_Jm3Nh_jNNtAMZjl-V0dmwg_xLrznVlcVs7zULG5S_yT_enhXtrM__TV-ioS1_TN_MljN
NsqMGcF_sRu4NXqN_zA_-cApj3Bitru17Vfh_-9B7H4LV_jt9Q2p-jV-rTEJKVAtFmt0ZrlWrLBz2_ywVqOK_UtVcO0M_RL_yUoCYBA__JiJq53zI_yoVyP7
_lRd0U0N_zg_U796n6V-zkS9mFe_plldPaG0V_l31B3gn_wH0VpjZmE0Bdxgdn41_EtF4m3qiNy4yxS_Jm2eVkWVGVtjpmC0Bdxady7zxSyJ0FI9VmJmjtzV
0a3rmq-6Sd_xym20Ynz-Bfpxsvyd0EZB-VtzNpm1eFhXBmLnV_lp0BnryMF-uFpsFsTZ0e3-nVnf_zMLSFGbe6p7-IFWvM___WguxU8Fpc___WG0VG6__RkN
WA3wWR_zkolW45G_uBT_SmA0lfZV_dm9wAgVl_EpFwy0hY-u-EqF4h1hzTiVBO7Dgz_-j0BshdxxymJiNltsvqjW_-gtFw-0_QlV_Zm1-rU__ViJ8D0NyFlx
_tQjVllp1EnT_VRd2TYt-kqV7G7Oj_hj7oq9s5RV_lqt13b_tiHl__Q_4kOujhhuxSyIyECSE-hRlsq9lFQhVlitLi1-5x_zEnEmixxzUG84rG_FeVqx0o2w
-Fd9itzB0kxLZzuRsVOlVtJcRN-v_goC_M45FBJwPt6EhVrFwiyJyCZgd_MnFri2eFhL-lRd5N38gf_hsvydu11KFzItFqx0sdyZ_Vtz3-hF0t3iM_txl_yx
gJzFmB55zQ_vxGyIyAE_zRVpvxynVBZwPVudzkSLSEnS_VRd2NYzZWFmA_NjpmdcSPwkVed_oVsvmZNwARZuxGyIi5_rsvzVYgv-eVy9_877tjL_dFP_NyNL
_pp_4_XZ5ht-yQ6-_RcCgr_lVxxdpt72rR-rFmz0kFeVuty2Vvo0dJ_ZOV_hcLpzL_kVnF_w2d3rN-j_Cl_h4x11zTl_qYNWwh_E_spqFrEG0EiJ_nFxymf8
a01NF_8_WRzs2UWlVljBtmbOd_kVm5-S05S_zpyx_FMtW_oavpF_4_ZBAY1T_MoEnQ41Vy4ISFNJ0ZY1lpW1hduUWC_nVlXFHJy6kFhf0Fyv1HM0fbVV_lCG
9a2lR_-fNWAowhV_soSfXGauBjAt_zK_1kI3gz_-yYMWhtxxAzu9wAlV_k84wAlV_hebeB_TP_-dLm1V_9wAlpu1-kgt__LB8EwlVi_QNv20-wlVK_JNBm5z
zTjV_LIeNzzJyDSjWUkht_E6l_wfq0NwdfM_QWdapVgUWhzk2LnV_Pw2l_gTmANwdeM_AW4vXFeEmA1dc2TWp7VmERzduI-hWFUykRvduRz70hY-Pux5cPSj
WLkVz7ZcpCKFW9e4vBZvudS0nkB2Koq1WRuJaA1oXKlWC1-VOyuCqBgw1DYkhG8M1I1wAfItwpi1Sp6Y9M1zmLU8xB84p2_uXNhXEm7hEm7NwtisM08Ryxi2
-0t1yOrnd82CxmVY9H2Pus-J4VlpkmBE-6o-hRwNWFMz1F8xQtW96EJ_B06vWxuJ87igP7u_5RA-tmcOuA_jsZS1mm0G1C7oo-VFrY2il3CKzfILlWXiWMT1
zLq4rBS0zLq4vFT2S7CiO0FnNGJmCk2jS0eWFW0cFG2S0gWFWFG0C03g0o0-0Egl0gcV04WF00EWFW3Y_Pdu0AWFW7f_uWEWtf_w04Ztnm2ezoS-02RUd_gV
8DHF0AJxOm3K-nFlJxq_zG4Gxy_4-rFlJxq_yVxKytD4VW00000000000000000000000000W1y
}

