sprite $bigtable1 [512x512/16z] {
xDct5GCn34H1MlJViRoNCeKxqyBntIU1zWy0000000000000000000000000001OQuqMYbbdkxT4hBfPBG-pdl8YGDs8WE-V5m5sVPWjZlwBW028W028W01S
xD4oKB-jtc8O0CP6W5uV30JT07FUWeowynRq0n01Fm0Hy0GG0Ky0Rq4_W8G8K7SYu0ee0WfWAwG0jaBU02aHODQD2BW2U0lQ0tWBEW19Mo7wvm4G0GT011m0
Rq47G0GS014m1n01aq03GTjWMo6N014uidUcIuygEn1iBItx_L_udfM8GrpFPxb4My1K_P_D2PcVWR6f04Q02hZ0Uq5E15307IB0YTg_Km7U25pwhX0djfly
dX4W_MqVHM16NFY28AVs_zFnkqM09p_GWFj5WFItwMyO0QeVZy0jtWlovCSZuFUv84Zws-JtYW3LpmYGFgw0SOC8KFryByYJdn4W_GKHQByWIFNxNxF4RXS1
JdGZC_rS4V21ZOElqKpW2BXJ1FZOjjyX0Xn-UMxwIWNeAIF0fpMx8z3_Nf3gPmJuh3v-1Dmf0dnGdn7W1tUUAm8w5epglr04P7nv_BocKrqGj0KAeFgl4m4t
6ml6ztoD4PWV7eiB6a3rNoG2lltcq3W7oAkQpwL7W7YU__SE0AhVTOnjrX-1ZJ_O0Ag_zcRBJX01xFV-SvpNhxXB-mL1y7yZStRCnLRjZS24VcjEFrL__K7H
9HySue1TE2cflpy2U_uD2g3wTvEs2u9kVGS0rOz7m0wA02uNlkUhgxy_0lYXLH_Ltn-1JtvZJcE1-biZO8q70DNV7m5xlS7b6Wgel-y8a9dbhsF1gFxs26YE
Vxq0L3y-_M84R840g7uTm5eYOB_QsCRPClNtHy0w0q3rjzyLiiO0KFtz4R2M053z_H7evK_rzryGxELFzVT7e9C_rTz_LqZ9_nVJfUeNLPLJH03dxpV-205P
gdxPNDqV0Po_8ysZ-lSqfVa8mFdxvhsnZUf7R2wT4S3vMsoxdVhdOlLlwuy0pjy2vK_rjny1TVuID-MlyJNrzqS0vpzt_Ad-CZnjk2k4y_Vup_Xy5oBl_WZW
_2sA_Ad-_WZW_2LG_bH__n5GvpzX_bH_UmJg_2tse_gFPAMB5L3d7oX_ghy_0dN-Zl6d-kluwn6eyvUu5tzRgtu8qVeZ0EVlZVpxrJ_hwg_JhqS0vo-Hv4_r
Awh-nGf8yy-zOdCqZEh7_oGfy9Uu3NyzhVfNHw30t-_2NswWVbG1YlEF5VofVldkGy8mVtt3d-f7mr-VVe7_l0D_cHTGFp3HrVmb6lXtgzyRr0zE5lEtw_FN
k83wyUbI_XFWJ_KZzF7fEluI5-VlWFgRmezFbl7N3lvKl-Y7d-wXY_ZxB_XJ_QBhw2Erq2NyvuNvwqNLhzZF2xA0lyI5-LzK_VYF37euVstWt_Ec_tpqwn6e
yxSBy_TI-FlLNuz0dR__5lpzrFJn9mJh_EU5-Mko-pREgVvw1EhyuyBynynzDUl9Jtuy0dN-Scd-OyBm--dN8q3-GzJdhzZdNir-zUCH8F_jbVZlKJ3T4wzZ
F_rw1EhyjPz___hLZqU0_F7rd_pr21JvMoz_qgyV0RVWJ_NZ4MZXJ_fvDCiLS0_-L3z-1Do2FzMFH-0U_4aVLy0T-5Fz-150_ZZzzIS_Fha3VweVdzw2FzMF
Js_1d_JnoHtuK_tuj8K_wVUV_Dlq5lofVdno2_vKFpwv0t_InwUtu4_ruvDRyEVbFdno1_vKFpwz1N-g7v-GVm5_F_twXFnnIFtghq_9luY_VlBtJiW_isNq
-oVaZpkwhlx-AVaVUVehGBzvGlu5KdNrzq_8_uSjLt__5E1F_YXzdtQs-IJ_cghreqySSJlLvlCPGlu5Lykd7pdc9wB_UFwv1yoV_6Ma9_7lvbdK7yz_5XX_
ybVm4mVz9EhVfW1_yjV21mxxATI_RNxEd_nb5FZ7F8Fwjpq-vK_-Mlx0SMzL_twVyIT_br7c7-6TwiVva__qSGJ_c6tgn_cJlqTebVysRr4_pf_yFVxSo4pq
FVy8Rr0_p9_yPsJvgrc6Vym6zMFyoN-cln92pPBy8xnH_Nd-vEyHIVvYbkA_pRlKd-TF_ZEI_CNiG_unMzIVvq_-CoB9NstR9zytuSlLZ_CdVuz8yjUFNwzj
_dNrRuiV-PE_pqZo5-3xSh48rDM_xQ7Z9_xaFoDo_ENTz-NhzoCmtz7tCNxWJ_uUaUIlzeO_487bwfVn4t_odwyW9IyN85yxFdlK_ve_-S_8yHTxCUoh9xr1
_Q_va_-C57-nbqE_VDQxrB_dJ_upKlp5ylpn2AnN_vu_-Nka-8kb-USZqA7-FN_oZnn_0_W34LYfVfm_-Gl0lnY1kleNye-xyDSSVyFuunS3wkflvK_-U0Jg
wfzZa7zgyWN-Gy48uEflvq_-U0JgwYV_zEhySvl04G2gluy_-UCN0-OIzVVp9__wpu5rzVVp9_yXG0GGzVVp9tyy0hZwk_cJ_vHo143rspltn7h-v1zXzGYi
KFzyFh_1d_nZwbltVXW1VqS_TFmyUpo_n9_y8mwEGDJL_tn-Zp_v9oAWYGWSgFvlyYV_Oo9mdFg_ov_yan58AE0GzJVm9_zK1EBDZb1_5t_oZwd5dmFhwk_Z
J_vR1F2B0MNrD_8d_te4Ykhlvq_-4OK8G8_sRkflva_-zGYWwjTuFllva_ysz1bXNFtz_Cc_7W5S_VtyoRyU0Lpz_Vp9lnu1IFtT_CaVZi2C_G3rz_CdVpm2
6hi1wc_bJ_uQknKZK5F_VWzTnv_yyuzsw0S_1vRKlv-FiPe_-Uy1rYDmcFf3ncB-v9-FW6Sl1YJLBmdrB-LF_ciYi43zo_cJVpq2s-kUKlyZeVx5_Cb_JGGM
g7y9V_9V4u4ZrB-AlupTo7z11Ehgh_C7ZrxohqUWhdw0loRvszYD_1T4eAX-YB_a-Cy4V_878r1N_vI1yTUHusy9_kGFHw2kVf3_oF6VQVxaZqS0Lp_AVoJv
Mv8_-UCHmDMFyjUHv6_ad-IFHm1NFyXVnqZoT_9Fy5yH0K-e7-Gl8yi_z-ycVpm2kFfH_Zf6alyqW3_v0n40r8_obv7bxqR-2VxWfpuehFw7Zu7or_HVs85_
D_a34LYWVldLlqT6alzyy-yc_x1w1DQeNyDV_tiqBIotT_p9FwRK8x10_VFvVCrVidzNptYF_2FyW0WSh7vxF5_pJ_-_n9dj7ld74H4uLltFvsl-altQ0hSq
V_8_90B_iD6DVatzB_Ydw0_PwEVvatyr0jlc9lwY-b_prv6ORUhFyoV_T0Hc_Bpd8Uf_pL-otrhZ1l0d_oCYy3Dz-_1caIClpaIlUv1_FG9rzHVvJpEKF_dN
8r1J_qOVvs-6yoV_UWIAwY_o5wlm9_zw1Ehgn_cBMOa_-TSZK5O_pb_jAFxa7rEn2E3gB_8NUpiTYP5_FWAUu0-fVvj1z77-v8z7u3N_WDI_JGlgppqkIFuU
knKZK5J_VW_avCVppy__gaTWh_xYVmnnuEHFw9_y4m808m2g7p_zrQnq-fF_sFWT4O6Q-lTJGFsf-fD_mW1O11BgppuYfi39ZzYV_8T671I1ilgtJO0-Q7_o
tnHGZy11wWy1r8_Rd_o7p4CYS8pwBNdou_Od_pKHU8Oqg1_0J_vB8j2WVWW_-KCHUCkcN_quVlAlHw1V_VYFVkHVZq2_-l6Jd_pn2FIh7p_voRyUWRhwlO4-
-QCHk97woNzz1Fnv0VMJFng1zUgNLVJ97u_0FTHF_dW4Rg5-yiSZS5Fra_ys0o9m0_MJF_39FpTGF_a34RY7-iaVZy1brK_-9WiYS1trax-P7161owgV_4qF
ZO36jTHF_dPC14p5F1wNKp_vPoCm0_Zyj-Ngrr4R-HyLWNZsgP_y3UI_JUiHkAJwoV-m25n7_VBtRiLVg_ph4JY_-aLzVm1FDnNoFoO2vrQ_-azlNYxFNwhy
wn4uh_h5PhoPNvp_gFBV9d04KFKFNKjVPoGsoRyOWLVgrsxrYqToUcN-iyo_7e5MzUFqjzcL-NkLVpq23qZz_VIt-PNvAyuVZu3_nBzV_Gdwj_6_LFdN8_1e
K7zIJ_V_-MzK-TSZy3YL-cS3_Zx-NkPVZy3ZkkgFi75f_Whphny1EZV-LrL_k8nhyvSo_te47YTHltwiVhtwzVyvolph4NYSGltIeFvs_bRcNpy2Pln9_uBg
lyFzNrd07pe1cqv-NFqoRi1_ZWNy0GhTwfyjwk_dhmlu0nQc-flu3vI_BZWLkzGVJUhlv-ym_m7mG2VdKh-ESHV-0-UlHHzJ_VtylS1_54zAgh-V_wZm5wkG
eVhx-Jl47sTZkbxzlDEJvpz0_hYRJQd-q_0td3-EoEIQwfywnhtupr7Wlpu2GlMlvIyO__L707w9YJVvy_nz5FclZu1G_UluZmh_kW8gHm3LN-Sl8FyJHa1u
kUzZ_ZP0_j-FWF8c_-7yVO3ySL0uEw7w3-O_1yo_FG9KVvs_uFnNH03zZPNgX_ZBgFFlVo-eIn_jrN6toGu_ohyl0aBrrvOwid7-w-yAATLV3u2EAl_-7mEK
D_cHYVjxY0b6ZH4OeYfZfVfjt7iu__1nXYDWDDta9_y86-qHQBpJG_uncoFGUxcF_ECo4T0LD_d9loa2_UedV-2rMd1Ng5NzvDyQWVMN-pXDy3zr1AHokO-J
7F-OklO8Q58_b-E__hrWZ_evoV5V7m5jKJ-NvnzngWWSSfEVapJ_zH5eK3-d2VvjxmNNt-JdDC6_BGBhd-_YDC6_BGBhR_9pak3V5u7rwkSqmR_XWc3RdHug
8BPrHC3as-hdDC6_Dm8wLzxav_G5_xu8MAVw6O5vz2kifGgeVrNzLC0i6xOU0P-kAgBcyPtBVPpi-7T7001VVC_7-UwLRu_01F0NrC_9TFjhaTvS787lgf_p
-Uc9PsFf4V1jzLC1yzFqdYK2EWuOPzDt0UYEWCrlgvyHSA2x3H5Ofdv689BhZm3Lt_l_gViZOEFmSHPnXGZKrS_XzzlxBmZEPUhdT08HMFfZm6-kVaPWVlKc
FoT-jWZCLlKp0lsF1hZFF-Scet-CGFtH06mwlZLkRGJ4WCdutZXfZK0_VSvQBmZsgv_pxlU2_IS_8z1_L-WFzktZW44WYe6eJUY_PCA5s07pt04RD5_IEhhx
MY7I3mA15TOAXQKV17u3wTSAaNwj4EdN2jMa7mJU9s18tNsjq4cP_VU9bU85lTK40G_sG804W41scXS8OW08-Ayk2CoPbG411u0NT02qGWw0LiW1004kW1UK
0_22aa0G27G18606187S2C0B8W0880088810405uGJ6WLeW0W0010042m0iI05wG00W4PG0W45a04F0GW1Sq0VA2020G100G000G001Ui1S1yO8Y886W0S0O
u1qWBvYz_xoW-Gy4qlaF2hZyQtjmB000000moDzw47kh3m000000000000000000000000002
}

