sprite $automl_video_intelligence [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000001WzkuboL6T2S1eXI6adEN-L_i_xfqr_S86bL2URm4TX8zIRU72dhbOfvwLunzP
CFmM07_--2q0_YrFXR_m1g0U5e3nvuz_eLByQuRV0k3VirZuRG3EVXQ0yUUFtmBWl-U0yDi0-5i0-Fax-ra0nfy_VWk0lmM0Vr9_xM4167_-pduMWF7dZzy2
u6y1uEVlpPy5OFpvur-c57_Xhnf_uLV3NoZZpn-_-0k_ebwDkl4NVl6l5dxn5_wgEVl9-AlZBvJnvuzV_8LVKQ-UClvozgkOyHT-yQyOVZdxoVXNpDbFnb_u
LVNL5NxjLVrb_DNht5YHyHT-yHT-zQh-Clugz32jZB_mYx_mgvNs5_vBmx-dZB_mYx_mbmb_px79-0k_-0k_-0k_FF0Zuo_yuY_yuY_ywlCyy2FZB_pYB_po
HNyo_lB0Zuo_y8k_yClPJyPV-CLV-CLV-EM17nb_uHT_uHT_uLTR_e4V6N_X5t_X5t_XLn_mm8-Cl_2hB-_Vyw_Q_h8yjfqe9ol2-9z2VEMX_Rd-mV_WV-i6
CE6hZV-SOHxZF-lPBw_tVmtm7_fo6_-Fz_1d-iU_TVmVlub_el_u4pB_EH-knv_Rc0MGPsejRooMz-zt-MyZ_Dl_6lLgk_FxgNzUxTz6-hlnlurP0EVusx2N
c_-vzdlzMnlitslT-ZcsZTa0pl6tSTDMVFnpEriU-hhAlztklyUXslpd_Lzl_PidzE_qZsEBVT5Vlzj_kyc_3V3l4STAZtzkvxl3VsyZ_EDd5U2Vth_zqD2N
c__9BlTlt-hV2_FdzaxN-hTZOr_kPVpx4_tR8FyUlwpk-EVsLXVwjr7-yUiMEVljm_ptg_pRpnizRMN7FxVtkiY_JU9VbZ-tDxl4lutpl_Qru__wtB-rUVoZ
A7zkx_QnVnlf7ylxzy7-suV-RQH_ZpzMOFndycz3_MCo_pwM_xp_1Gjb8l_fdfUFv_c_-2yu_ldNOFbS__c-C6D-_wyyjBf_Uwv_Nkw_hUC_upVcpE-_vQ5d
-hUOS07qKVpy8rRV0FA3pfZb4_tZJ3ci_Od-oV-oleF_fEWA_d6k7DVy_bzvQ7N_zZp_lCr_Uxv_nEeRGC-FEicMp_AFGykT0NEiV_A_hE7yvpdpmiRxHwoy
0FZppvlzjoVxntlbkERt_whdtv_ZdxVxRy_rZrXz0zW7-6zFzUznQBMF0PB_BQELuxg9dt_4oWk0F__yTTx_HQo-0Ffz_lnx3gjVlqJT_ubOVGF88VvVp_Jl
iUG26E-VF_RrYC__Odd__7K-_uyhod4zn_yrXJ___7N-_YkkASVr5F-jal-Umzglu_Vttn6hRm3vwpp_q-EgUexhAd_-4Qjl0FdhFFyPLvRZgktFlrznKRx_
8MBr3Q0FyN_bZtrLzDzpN9ylIT__5B7w1f2_plV_zJYqs1cmynyv_f43-_1wVFzhFDi_P_FddqFRnr_F1Vm3ll-xnlXd3hYSQNx_uNB__V7ycO_npu_zir_i
7ylxvpJ-EU3tVmhoPpx3Vv_mzx-MuCy-u7ec-lt7w_nZ3VySSEjdgjz_dTS_lwS1rxFWx__6yluvZN_Ez_lV-pBycRFxvyN-cP_xn-NroVnpOVyy-1VQ_O_D
xPyt-6UVpJ-_iJsEvIp-h-lzZrj0gTt_sCp-UUZhaaqZf_BFxstSzNpEdzir_jdVzO_b_NCM__tDVo7_glVy-tBycRFwvwt--PR_WlpPHrtF6Fujpos0Qhl_
iQVuRzVwPqxWdpCqw7hEyG_mpvF-iRn_pniRmx_bkGLW_3CFrrF1l-oD_sD3-FDI_l7-RTdnpvpC_vM7jc_tNvW_zm7NSuPmGlzOsJz7_6yqXdyp_kyqu7e-
sFttR_UFvVtpxiQC_sRytwhdEXb_uPVTNyPVnb_6NyPVFlVJ-d_pARk_lFcJyPStVpB-mYzdFnb_EVl9-ClPJyPV-ENi9-ClPp_XlpJyBMNyXL_U_CduowqV
6V_Lmx_dOz9UUlmr1x-S_MJyvO--PFo5Nyv-Clvour_6Nyv-Clx2Bs_-PFpbSpyPVtdWHyPV-ENi9-ClPpyPVtdWHyPV-DMMzfVnbxEVZB_mYx_movi_uRy-
3_p8-2iAbk8l_5NZB_pQerujPVohXb_yXLzHhvx_IyPVBUgrOpV-mYzl_l0NYpf_uLV7NotZB_pYNp7ySkj7nhzYpduo_i9VDVx2hptgrLF6N_XBnb_uvSQ_
Z3__mW_ygFRuQw_Dh-B-mi-_yDbFjSTVlJQ_YlkhCB_ugp2_-AislrfjVXNtLs5-yLTjVlNQd_kfzlXhhysluhk_2e-_-Aislthj1tvKVFnLc5_yXPz_uLi_
CluhzT_su80000040T3_ryse53WD000000000000000000000000000000000000001W
}

