sprite $cloud_optimization_ai [512x512/16z] {
xDgt5SCm44H1F1powxzRvN8q6R4pBUodP_y6000000000000000000000000000000000000CEf3fw0ET0Bhoy2P_z3gZJ3hZju3gpw8mBLV0-PtGs1-fm7x
Iy3DdmGS_XAmlmJiVspsOzZVIS3jdm8S_XBmwKS1JW0AiBy2xAy0-oj000gmlmBihm01A400VXOJm3Qd04Ofm1aWjG04W08G07uF-Ke80g0KG0a01I002QG7
m8el004eG00Iy6E819m252002GX00G9GWBj01JW5A4002X200WIW004e82C01800510S008WF016U008u0O1y6BlljRZrhaO3FkHQNATuVwlzg-xCv4pbc11
r8V3NLBc1HSdKU5tfFxCa2sP1I3rZpoj0EZdDa3dXVI-mxzq0KZ_RzeE_xe58FstVCxlBu0kA03si_y-VmtPSea_-3F_g9tevWKWhVTz_wfb2q3wd6dvxwRB
byrT0F0_zwzF8cUS1K0_m3-g0EZF_Aq-IPCrJd_qZo__AYrG0FHz_la5GD_ldry0zFt-_W9iEX3q8_rb603e6_oJ2q1wW7zq0T2V_HN1BrdyqPyp3Fwn1O1_
Zi4_kG3e-w__vXS0_dn_VS6VZFvYnYi5aA8BGFhhSVZd5m3-ZFj_z-FsHx_t3z_z__a5WD_m_CyL_flWFwy0tN3dP-W0WB-Rd_-b0FwCVYJwOGpudWBWtuz5
fkGN0Fxy0cpc0i3VEmC0_aSM0FwX_9ZyuL_iLP7mE_7p1q23tw3F3f2QK_0f05TyyjFm_sUC-Wo0_1Zrymk0_m5z1W2tUZ40u7zG0U2Ny5yc7dqA07z-0V2t
w3C0uCyF_lfu_Ve-0u3dkna0y2-GxRa5W9y1ODVF3_uFusS0mCy0W9y1y6tyDUKP0m3-sirz_D_WVpMZVYc30N1DhFprIiPI_l3N5q81Kb_nOHZxbqy1_4ty
TIGZkG3m6_IdC02o_DtwSs8l0yBlrCz_C-GR_XxzEVVQ0E3lTN8Qtm2DQIVpbo4C05_EvMzbIMS0cD9EvIzRbE_FyYzZqly4mF8VPKrd09oV4_dBdc1__AiU
LW1P0x-_00m00xytaVui_whb2e1_8dzLZl-cAV3x4xO1u5-rP07mp-Il2l9d-TS5OGCu8qR-_08m03xEy1zrINgoFylVdmX__EkoHFY_m__S0k3Vwi8CEOA_
V_cFSuO8_XSl_nFLxbg09o__Vkx87lLg6WFWIly3ozNz8-Bl7_yMgvm2uA_zcA3kCG3mzp55501_xSU8jD86mF9lUZaZe03uxyOCXBytoVpv1S3VhvFfFnyP
loX_lnmdupBGta9_sxy9dEMlGuaO09F-zAyVw3--HoPX00Gywf_dx-6V4p80j5mCuz_2ak2lhuJbttH2Ha01yBzmLKRxu-yt2V37tq2IN03yjR0_QGP_7qYM
F-D_vFaF9ONjNrfX0B3zuv-VQG9Uu6_MIFAFAboRFWI__xYr_uddM7PTdVfdliFVzstCNxd-zvW_Rh_-d0H_ANC0d7-YrKZZhyB_Px4SQPN6NtM0Vsd__kCq
wyVjvvzZzhVnUtzIsz46QVmrhEE_tTE__pn7lu2c-LV0zf-s0JZVS9h6NxMU_t3wd_bnuzzaI3lct_TpD_-Hx2zBals7334Qu7_oa-xP_lZtpxAUF_xuuuy_
_lZZZp_--EEFF_xug-z7z_R7lvtfZx_I_5NxaS4_uFfFgh_kvY_dC2mPKlWVk241V-S5mCJxluotGsNwo-e_AlC6GCCZ05hFttlAPUpzt_indlOTEVvTTm3c
FVznf01wfB_Xuuvw_kluur3uwm9-zmE9Enz3rlEVVd__n-rlWAOO7eVEVFw_s_pzpt_dlv0Wtryc_pcyS2JW_Iy6_rM3Vp_cJ_BV_zPY_Ha0-UE_YUI-aRNO
_l4FsFv9xllV3Vuazlm7lpy9EV-buPzoQ57--Kzy_VCVMPP__XlBttyiRMMU_-Ztpr_XpNuiSVxvh-lxRnFnT5gnDIFd_ESo77ITdvcv6Owbppp_dUKllS-9
z2_hJu1_VW6I-Vt--5VJosaLxe-_whYH_uTUbL-watzTzIDt_3CAKAuV5l_C0J3dWX-qunzKWFhs7z7AZt-hLpEqar4dyllz-GAW-aeCFzGruvy1eFfQne65
7xJyyUzrOThLonz_rOKH_ja5M9-V0Q3B-2FyyUzrITeP_1_u7m_BFyr__GACK_Yxn02uPG4KjFpnLo0__W45iFBZlyNu2_uhakElB7xybos08fS__WhYD_Yp
0IGKOC0_-J-f00hsnr_Th7yYVzCAUGihWEx2toK6W2DE_lpbZx-6Jv_bF_ld5K3mPmy0VwxILyS_eW3mP_y9m1-NFlwl3u1Dzss0RFni0FaDa87VuCytG4i3
vE9d0EJ_TS2GYN_Wdpy491T_boX0TWKa-4t-yHk1lfJ-PFytGm5CCTWR-1a0tkp8ms_oVzUowG7-303u6G3mCm12-V5_Vxf-rxFzD_WP0F2lwV-y0ep-KZv4
0PPV_EilVmO0_0o0_an-1W3y5A3tv_hZtsFvAK0-F_xlQ-glpyy0w0_cPm3qS_WfG5jBVtr-1a0FuAS0uVZmQrkl0FryVWR0smBuQ_Ep0upUNVpul-Sl_3X-
2W1_Vjel-czApiFvsG6MvgS0lVw8mNy8_pkz5kX9V-j30KPD6UVvmwyjkW1LPIs0IB9__IIFkDvB0Qgi1T0K_9CAK3k9li-N0kJx3sM70bGP2w0_GvgX0Dd-
sWy38F-CsCXN-r20VFyF6K81BlQNP_7ZFoU1Vov0W3u5IFUN8HGWmXzzsvl1voJx-_KP0Ezv_W7w523LNxPGW7n_hHSAe7_4gy-5W3bH_cvz1i2SV7yvGm4s
-T9gDstoj-DJW3cnrt-75Wu5qBw_aa81_Fv6VFpt4tN_hzoX07D2xl__TxjrRS1030LHy5ZXxxzQSwR4J3lJmZx1MX44K9sWWo-0UZNcxosWKWYWBw3LjnB0
N0WWc026-X_ChW01f1Q009WL883K0X00im84e001A4002X10NW5C2d05A4002X2010IW0Bz02RW292001GZWLai5Ku1hG00I480652020OX00IeGW10Ke0W1
V7y2A00141q0_e5CuG4W00NONm42K83z5I001TXV0VPNWFqLO7y5s5y2zbT0qFuCwVjZVmdONmBcbu3z9H0zFrFy_fWVynVcPp5_OVu3h7_1RUC300000000
0000000000000000000000000000x04
}

