sprite $data_studio [512x512/16z] {
xTt7OGCn34N1ouhW3VrNwvnpKAB-J0iF1DUslEe70000000000000000000000000000000000000000u-pLdNcliqW_Fr1zySI_JV-5pY6-4H0_v29GVpwp
1DJVtmImLdstWCE_hnN0jd9z4-3m6m0tlm6GtsEWtMy5o6y3oB_-1f1_FZ00Jhy1aDy0-C7FGw3y5e3y1i2Zlm5m_3q2o6y1sFu6mF7NN_vlwH-w_Jq2EluM
WFwZOybl0UY_THxvBG3zzT_2VlZp8w3ZRm7ehx_V_Ha0nrz__VNNFu0FVXW0_VMt_lNNNt_zzTTVVuz_j-JNVsNwww-__lhhhx_--kkll_xwww-__lhhxyF_
yllxZ_xwww-__lhhxm5GV_shSxW077_zzNS1w5-P_ULt0UZl0j2_B03lVzDV_xEblmKWlmMWlmKWlmMWlmKWlmMWlmKWlw_-z-K_RW37tmqWlnl0DpyP0CVV
8u3y7W7aTmF8Rm3aDm3o6u3lyxDRO03azt5W-Tq1yXi0-Gs0-YP0VWEWlWcGtmJar3S1fRu9I7w_bmaOLOw-6KW--VumTAlk7UNZdJP17nS0000000000000
00000000W1SjLUM-Kalv_RzPZLgWVUgh5SMlyYNgth7i5Plgcm3rJO3w9a1z4-2hrWs0msy2v3S0Thy1aDyNByZlZmBo6m3vbnq0-Gs0_1u2vVTZeFmf0o3_
c3Dv07pCQne0srz_-VS-06mvbxy1SFprz-nl01n__UKt0Ff7SViR0CTVVyVV03Z--Zl-YxqVmF6t0FJNt_htML1F_nQ0zQ-__lhxu8S1SFthR_thhx_--kkl
l_v---StW1x_BG3zdN_zdN_zzTTVV_trrrz__VNNl_Ht_htroVaFuEy_Zh_--kkll_xwUm3KN_yOBW3vzTVV1Q3_BgA_t_wv01n__VNt0E3zJnQ0usy1w6y1
o6y1wE_zxzdqloGMWFoU0FHt0yXl0UXl0SZl4L1-0w2_Hm3vFGB8xmQGtm1ilHO3u3EV1a1-0o2_0P3V0EGz-dabKFd1pmgGtm38Rm3KDm69-Gt0AFLDWFec
G7qJa5lVas35_t-_BL3Xl-et0gDkMFiFJ44V5G0000000000000000000000uq6V6Roax4xarr1ex_LqNb2vzvUJibXyMy3HprW2wdi_lVecmBVL6m27tmGu
_0R0DvIQ0BlV0DZz1a1-0o2_0P3V0CXl0EGt0F8lEm3oZpaDWD_w6G3RVt-s3YE_1U3oDm2Elw-kb_zMixkuxMy077_zFVmP0CTVVyVV03Z--Zl-1i3nrrz_
_Qr_0-3uwnzn_FMt_Ws0zQ-__lgx_hqVpFLl0LZ_-kkll_xwwv_6ux_-c_x77037Nt_zzTTVV_trrrz__VNNNt_zzTTVV_trDm3-_gE__lhhhx_-7W3rrrz_
5u3y-kkll_uU0FIt0EJNNtyNWF_-jG0SV_trzttllWNA0d3yBG1V0MG1EFv-1FJ3dmNW-7i2aDyDeByRG7utW8S_Du3ZxmRe1zJI0o2_Hm2Nlm5m_0s0_7u8
aDy6aDy0UFGp04w_0N3w3O33RmBaDm2zFDyBCafzAy23dmbm-4r0R7qJKDcRtmICAaVV21moFhN235JushS7Hjqv_h470000000000000000000000000000
00000000002k0G
}

