sprite $data_transfer [512x512/16z] {
xD2f0S0W402m_fMt_xGjdmAD8XaXCHa000000000000000000000000000000000000000000000000000000000000000000DVPF4KiWNFmz5vBFtjtaYGf
3WPXT05cmSxlVzeUjQeno4gH87z-0zdxVhfhBg3_gN_1zm3zj_vT4R3_rhyo0lZ3lo01-6VyE_wV4Fxmhqe0_dd_iQmr-iE_Cm7umt-P0cpVFk1VMW3zuLzQ
0FtXNre0_U7VLO3_w_lMlxG0_CE_e03wv_mhVbAG_l3l_0JW7_wT1T0V_gq1u1_-dGNG7_wj0U0V_fq5u1_-fG7G7_wj0U0V_fq5u1_-fG7W7_xF2i3sRO9_
Nm2EV_Yt1e1_-7SMW7_uDmQ0Fz-i903y-VKM3W1_tjk20U3FoIqK0FvyP6i4W3yVt-C3m9y_t8C3mB_dC_RC0F3di_PwNW3uyvbxFIi0_FdiFIW0_7icx2a1
uC-aFI40_9cuk_lptvFU0F1d-kuR0FuzwGq0VoxQBVtv9mB0VybUDmi0VovUTG3uarlvuoyEW7yY0FoT0V3FbwtQ7tzIxOy_UNqjF_zyzQhvyUVLp8y_-J9-
_hd5gldn9r_oRmJmpsrMpOy_gVxsuq-w-VcdcXz_BkNddzkjcXz_SXa__znnhsP-vv-qyZl_iMf-_0b-_X_cj_tX_CbqVkUVMw-KtzT_R38__pIF_vu5PyxV
yEFdpx-6_pYEr8x_SLG7WByu0Fw3VmHWTVoz0JZ_mJ-MM2V_6Fwzol_uTcw_bN-CVO__CIQ0xSJsjVW5i9tRklnZy1lyZv-l5H__6FtL_O-ZF81z--0Mvnzh
FNtyOsv_NV_ZdRdzLVsFzzQgZtyC_uh-n_kZlvx_SMQj_Cv_h5kV_-77V2lu2s3RAlq5W5y0-rRiBu1jw_GN07u1RCN-0jYsOdy1RAN-0i0lWAtPNm1Rixy0
jb9_0U0NGBMw0Ahf1L0jBu1gUm5qumkWMby0rVW2QCKN07u1xDNw0gZM5q2jlW3m2w1QNm2r-WB0Bu1QVW7W5q0rlm1gzGM0Nm2r_0B0Bu1QVW7W5q0blm2S
lm2Slm1g-GM0Nm1j_08upxzdmGd0-GlWeVm2SFx7Qki-V_v7jp__0_zL_WBWBu2xyVC_ki-V_-7yB_0N07y1NCr_73Vo5y1-fVy0u__ELlpy3w_R-0lWOlun
_kziEVzJJ-D_BEJ_BTOz_0LmFVyO_tUsqFaVtwpAd_-Sj-5_oET_qklmFyD_rllmFy9_sWlnFy5_tXlnFy1_uYlntzz_vZlntzv_waln_zdcyyzzA_wR-qz-
BVvxV_vdlnV_hVsdlnZ_dVtdlnd_ZVqlU3N--_fVyMxyj_MV_d1__yDy_vNvyMUVuuz_xFb_zmF-bVZF-tVp-xkVyA_4Vzv_PNxygUR7dsf-_AdcnvzgVlof
_Zz__4arF_vKy-DFDJ_-LFFZJpK__gJwbtpmfveVVwhvyQUQ7tzIpOy_rVpuK_rx_V2dcXz_KisFFzNy-9DQVlp3Fxty-BFZB-3ty2d3Zny_VlpuyUF7Zny_
VlpuyUF7l-JmuyUF7pz-_FZnuyUF7pz-_FZnhpVy_gKD_Fnx-Vcdcvz_kldvfvkVVxhv-QURdt-w-Vcdcvz_kldvfvkVVxhv-QURdt-w-Vcdcvz_bkBdVtvB
yVC_lsNv4_xlR5d-XFyxMvO_uV_EbkLF-B-pPVaJ_kziMVwatD_u2u2_0FWBWBy0-0k0lm3u2u2_0FWBuEzswPW00006OPX_rpCnhYOIe8jv4G02G008004W
00I001000a0020018004W00G009000W00I0018004002G008004W00I001000a0020018004W00G009000W00I001800YFzF_7xYznE_d_ZznEydVZ_n-udV
J_n-ulSJlv_u_SJl9tu_yVk9tq_yVkBt4x-V-Ft4x-V_VW00000000000000000000000000000000000000000003W
}

