sprite $policy_analyzer [512x512/16z] {
xDUt4G8m4011_2jJ_zqIOtEutGuq9_Vx1m4000000000000000000000000000000AjaVo2-BI2-BQ1-mkowMN4xRL6lJpm_yVp4ynFFJpm_yR6V7N9RpvZs
xKyyF-tRdsaVV-9_Vzh7d_RnPzh7dtP_ula9z4V_AFqlwnkcVVnfz4T_z4T_z4T_z4T_g_zZ-kkll_xwww-__lhhhx_--kkll_xwwtzdXmu40000083yNnkH
GFs1-WFr1-eFr1-eFr1_eFv0_O7w0_K7wW_K7wW_K7-W_a3zWVe3zGVg3zGVg3zGVw3-GFs1-WFr1-eFr1-eFr1_eFv0_O7w0_K7wW_K7wW_K7-W_a3zWVe3
zGVg3zGVg3zGVw3-GFs1-WFr1-eFr1-eFu0zUYa008HXA7R5ls8qy6TRdeCs_Fdpvy-VF__v1zhx-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy__tZnvy-VFt_-_Fdpvy-VFt_-_Fdpv-y1_lpvy-VFdpz__lpvy-VFdpz__lpvy-UVC_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
dpF-_Fdpvy-VFt_-_Fdpvy-VFt_-_FdpvnybwptGsRkJNCTX60p26oFaxh__RHiyGFl58KoHKjNQGePFyGn79L7_27_2d_0d_0b_mf_m9_m9VyAVy2Vy2N_2
d_0d_0b__F4d_6bWX3_XJ_WJ_eG_uK_u4_w4VsH-q-vs-4Sd--CVdUoFVtIcF_xt7qJu7vITx8z_TB8__j79_lX79_lZ7zd9_lX79_lZ7-4VRRsADztcZl_6
-f7fkF0_UGk7_rwV4N-ky-2VlzV3j7dudtoeYx-dFYp---j7sY_y_L7QAlpzSTec_Fsdj4Nu-yzfUlXVdkhIuF1tpoVy3zQFy3zPFyB_PFq8_q6Plv3XFoD_
hPFzqOzEzaS_mhzjvYKP_XtpmaxsHpywsH_zw6H_z2Fy2mGIEttRxmhYxylJil3t5cb9-7kRL1t-tYmLXhytJ4NXxqrJGVXxu_Hk-5_Ul4klXR-F27_ytmn_
_F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz_ARBv_lZdYSxmnz_qtsnpV_nDVxInF_vNuWl1VtrLBllvuszwa6tcZt_bItKB
_zeNQnR-nQ_MA_prOxQ3F_xwkMkyF_wNCWttnr_9HllZhtI3_V4tvMlaZtyzloxyrQGr4ZRJ7t_Tzs31WVxuwwRaqlZtz_yyNQ6R_jiyV_mVwaVMt1__l49Y
r7X__7yTP_WtA8sG63dV7__4q0l_zIKDKeCd--EV7ttXlxmiVyruDGn_VzHaV_prXhy6--Fl3vlhZxzb-QEn_lZh7NzDzCS_Vnil_lZZZx_XlxOw_YZ_-lt3
7__cuPyBV_EViZtyyK-_SeG__dQqF_xgxOy__lZRqVxu2tz-__YNJm2s__Zp-yUVyp_3Cc-TuNyJAu1kv__LBFp5vly-_F4l2F-kZVIll__lQ7_yVLj_3Ja0
_FJtrypstW5GZX__dJS0hFwZlVsLvD_VNtlxAy7Vnfy9S7L__eS6nmeWFrwJc-DV__olpm7-sjfVNZ1OisllV_L-_gV6rtq2z7x-h-OtrJ_FcETtxT2s_b5w
LBq_jmH-KXJv__-mi_YZyIi0M_3_FzggjlvvZATqVVof_F__eddy-5lrgwek_Aj1klYJDrq3g5du-rNvkYg9lES4CFMB2V0fUs6j2lyo5_oP03tvyQ-XmN_W
zIahc01g4ok0lCxDaKDpVlppgu1xqVR-J80SqL_Bp-77_xdI5ulFy6S2F7VwSkcP_FZVMzdtowxs9y-KtwrVp4-UxvEu8rYBh_oGrvJOJnmU_lUw-3C1rl6J
zPW0bzP4tc82wEIO0De-_6-KyTU_zkpa2c4OY8BWHK_3JVbdImpiIrUbq5y2suq1V27605m0qG5W05oY0y00C03605m0nG5W01W0om1S0Ca1O00O0F7ynFFJ
pi_8_qe68By1xDFaBu3yRe0vOGPmlXxJpi-AvoUUdtX-ulc9vsV7wnFFpxJpi-FrYUUd_hq7X_y-1h3ENw1--AdN9rwVYTTdrUjJhq-zFlcNVUIFFbC_-HJZ
0m00000000000000000000000000001m1G
}

