sprite $cloud_for_marketing [512x512/16z] {
xDit0i9034L1ycwd-z-MbXoTPCtqLEy3ZZ4J000000000000000000000000000000000000000000000000000000000000002WzKUY0FfBBUhH_bfKuKVV
17prJK1z2r3V0jIt0FMl7I8lJlqfFm6-_1OWlm6utcC0llpk2yZl9q1-0v0__G3aDm3v3K1-0v3V0EHt7K1-Fm3o6u3-1Y2_Gm2t_Fxus1BnJyEMVG3yswyL
-0UGVwLlY35CkgG3OAXkEViptFzsmW4mPBDy_HasMRa1o7yjGN_-wJN_04wJJSgLt-4NTMRlZDLc1M4Wsl2PTBp_szxwbZ-EcMmuqo-8PuYunF2HMsCZFInZ
fIZ_uXB-WfWYQdJPjXZ0xs_Ljyq8Vt-pdamJ-7lRzPUW0h-_ONUo4VprBTUKeO6kWDAn97FJc70AVtlJovXn37vxsodG0sCN__soxRavv_3FxYN8u6ysryz_
TWJ_TTxwSdzt1dzhwxuF3y7lv-ylGKVkHq5qSPUWGsdZFw047VmbuQL_2JhuwziNu9zu70Ny8x_IH6Zp-ETtcZfTOmv_IX0UtfYOmV-1__6icC2V0cIlRaep
_kklpSVPhkxaTu0bS7Zd_tyEGBvmpWKdCVqm_tVZ6vWDaaUIs2jwydzxkpXykU_-xy7pUx81yeLcyfzLVSIV-UxF_zAZ6y8_tofQvt-6WDna0wH0FvR_lLJS
1l1FYHf__o70DjS0AtE00RJyXTFdejEtdVn3MKHUEO5kEedZTxx_5YncPmI0bCh6FvJyjJVn8lmPhZkLGlxx7lufrs_KVwgi5yRX--RwRmMyuYSD43d3067W
Fo40v2Sor7zLyb_NyBSSkvWjwZ_hQVqU__nAplhlVlxmptVTUl77BVmpcmQ0q0xZ7IpudrZck6DzlSuoM3_6_n3aqWK0mHeyynVunwn364kERjNXz_FFtyIl
ZU3wrFbC-9jEOOkAivj3zVo2ltuDhWm0ttss7_0Nu3CQ85FoO_ZhJqmhul__zHpy3y7wNy1ElfENClNdF_CKhlu6EEgSy5_ZeZ3YtsdO_nc0NzgE0R-K5lpz
9VVXxqrMoRO6Y69QEOH_L0xRCll9_tjqrnhlcdBWXt-VacxBW9_yVsNsa_7GFNtaWN_zm2lmy_sVZB--CGD-DR4uU1E1l_NmhReKv0r_UmK2N_qF-9U-1gYW
nUJwFmrhkgT6kcz67or--1Ti1rfEk4ZuAtcSAzGfaF9M-lCFwsAYOF9J_rU7JDzO5D1NVeUs4lxQiJy5z0tr_-6leQ9zmhvhFHF-tsnyb1snzS9VWgkRplyh
ChhxUnfYZjp9_h_X_Lpvh3dunNZ-Nu_-uvTgGmOg-NzdahNdJq4b_vSgIFFp_-Do_di-Vqw-cbZs-ox-su2Vxt_76-2NXxokmh_N0FpQRPOFYgvp2CQm0Y2J
JhwEr6g0vTNuEGHhW05q_faS0OOutf3uC68HE6UyBt9qzkyfDHertDD86VjM0unxuWdhjiutm9e_seBfxvDryhFrvTTDhWU_zAwC62hyjtVCx7pwvHqoEvz-
BPOxNlv-iTenu_VhWj46-8_lJqmT8FZ_Lm5wdox7Z_hYB-a9DSJ_W-66DO37ZW_yNklfWj_KDUg0tzWzSk_ucmCG2kEjZnI9V_yiKt3OFn2tnfsmq_SxW4sl
qlUlLkc7Arb-bAxxyYkn0Ys14lvLdxwE6HPmF6Zr-jA9105v1th5HvV2Ob3GT8d8WNojkggh5X3riGTbfQZ-EEL3Ups8-evHrglt6mZuFHpIy0O2VfCwl86W
I9jAy5C6KTM-NhOrw7KpCphYpzIDTbg2QetfqotRbSJU5059ltnNSkToNDQJgftmlO5sL67aKmVEE6umFRhrLVmvxUkR4QmqAQvz5Jy1rMuOqof3PcFPdEmV
5lJNr-F106lWBS800svLjs797ptW__BcUAv6yd03VwV1nMShKEZtFy_zqtwz-6F-miXsAOAzG6A_UvIh_40TPl-0CWRd1c3szwbcLLyoXDd_zF7wx9enJtRK
l1CSekcV0BFmwyThFLSL_7hvhiJB7_o2CYO60u3VD-hYfJORlZKtGJ3xHnYWWem0lslWzHstnM-8kFQXEphko3ySKyu_Tal7_V1FBPlioikEBZV0kWFNt_wc
VblnZptu_VTfQO1E-6UlVZVyf-3707hyZ-z--mq0VzFj9W0uapxy-0a0qSVvy_blKqvkyp_07nz-0i2Lqp-sIHx-qPg_yquJ08QwlklNB-tu1zE_Kj6DVvhv
6zzv201-_dsc6Vm7iMZyyVCC_le1-_lqymydVyA_FmlwClxXi9nRy9yI_lN1oG21nt-d003_UVZXp_I7F_pzjmJ-6_xm7_00cC0_1gOxmD_VS__ZJqpRuV3V
y8S__E4FV_Z37_xp3G1_-6TB_e_VSV2VzwoB0VpXh-iG_Wb_-CCV_WFIF-4_wEkl-VpX7rx-y6zS_dpDvmz_GVVmD-27F_mD7-F1VreTB0D_-1lm6o8G_E4F
VqFbFOC7uM_3xpS0_FNuc_1VyFUSWDJbu4VuUqw07b3v7lvU_Fv817__WJj-0y3VZzyVZE3lF_pIRm3uHplyk-xqH_XdklZx8nByquRVRqhufm2_qG01VyM3
lpz_lGFWd-d0hx-yWFz9YnRy_ak4V-JV5CP1-uNAmMC0y6C0yE-LVe6V003-Ams0deq1cFuO0FpN6G2jlJ40any3W1y3W1y3WD-cIBEWJmW0_tm3eB2JnW1C
VXm0VHm0Vbu4UF0J0fZxf0K1do00VIm0V1Q3i2SCm1uN0FvVUt100000WW3e_-jkf09X0000000000000000000000000000000000000000000000000000
0000000000000000000000000000000u
}

