sprite $traffic_director [512x512/16z] {
xDon0K1054H1O2-y_hiLoGdPcHRU-fUPRm0000000000000000000000000006GM8oaU0AdkJxe78By1o5_QdnY0_AK3uDJVvsy0yXSEW5D_dxy1o7yRiudy
3e3-1Y2_5q3-gWD0341-Bu3y3e3-1Y2_5q3-YWD0341-Bu3y3e3-1Y2_5q3-YWD0341-0v1VV_qDG7u3aB-YFp40-Gr0VltrDm3v3K1-_VKt0FaDG7xzzJS0
-Gr0VltrDm3vFpu0Xlu-VmEGtm1SV_rz_WOWlm6u_lhx_0r0VWEGNt_z3K1-0v1VV_qDG7xz_Vy3_T4V_T4V_T4V_T4V_T7_X_H7V_H7V_H7V_H7V_H7V_G_
ziSKq1_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zqH_zB_Rk8xtP6uQYi1-1RSRzhpO5QQE8ZZ-Ik0hE6V-kxmrKqlwtzP7OdyR8x8z-OdyQgVtHnn_-bFxK
1_xynP_K7ttyuSSV_Mp-DF177t_uyKSVV_Yp-AEFF_pueuy__FYZZp_yNcP_zBtC_l1xcVtHzpBxm-zbzaVVI-mFlzSJ-wFl9VQ7tyF_G-jZKmN_3snih7-g
lw6_gSJ-y7i9_7daVnl-7z4uLiTVlZvELWJyA_x_tZXTOd_qlSJ-y7luAzR7jV3NQrmDVwtwk5mFys_H_lXxwluUz_zS7NzE0FuwZVj5-1STVmQGt9y5tFUl
alwS0Fmv0V7-3A2DsztrRsh-d82EFoSWipyduA9_iUzN-FS_BgNfR_DId81-ox_Y_wtAk5noVqx07V-cwiy92FMF7m0du8f_aVLd0JVygwu_BmNL_CkaSRFJ
_k9F01Z0UV-osPy5R9s8e3-joSQsJllNpGy0B63puyHX_xRPdm7iVgOWwKyB_uqBEEjVzWw00Un_jN3Kl-xrPm47NY-Uz6zx_Hd0YNSC3la_VG2WXV-s1Hpq
hyVz-V-_Tsd_9mEWfR-dwz-U-TFQtvFrBm_zQUdlwVblUW2WjR-dwT-U-zFItzFqByy7G6j_Jz6_xl2dfRydwDzinm1ewUy9-fSz_kJ-o-JywwO3GEw_JCs_
RVEdFh-Hcd-n_zJNV1OL2V-u0q0A_Zy-0A_vD5Bm3tm6I4h-pQuFW9Jyotr_YlOFFW0Kx1zz0AZB-DU80q1TnRyL2tWJY4Bzumy0gVWt2na0XVh77m0AzOy_
02JYNuC6GA7-yGU0GltZ3m19-3UB6W19-5Upc7U1g4Vwnny0al2lOGCW1VzMmWP02lxLmWP0qVuS0FnRt04W1VyIDm0Iy6yMDm0IyAzP1e3_laU0rzmI2VWt
Yni01Vlp281_At43807_Qc43e1xltqhS04Z0lrdS04Z0loOT0Fxn0o01_rPI3m3_Pc4380N_QZ-hpCUHW7yhbla4uDyiR00Kxiy0yAz71_3k3v62Vojcvvu5
1jy9_8yEO6txzW-HX7-pSmCmRog7VxMVzrhulnq01VXl7e0j_4CNW7_m0Dx_AUeQ_gtOcGKi_XITzWyUWEaF07_FxCG2Ld-AOlpt3w0i_FK7WF_-4x3wKrHK
_ASTMC3o3v6C_xJz2rZ-8Ueg_lzexNi_SBqIql6VjgE5l-e2y7UllJTWFHBgGlxJzlIF__AFa9B_j4sjFziK3Fzfkrf_igaN_jFsDRzp94ZBVzh5fbRuCm3y
fzriafG_0y1_Mke5u3zVgGU0__pY1DnBpf_70FodvLq0_Wm0__bY0NUIzES4u3yjnmBmPm3uim3y6K14qlxJ4Ym0Vqu0_fm0_3a1-EkU0Fp78NzEG60Y_le3
m3_qa-RMnt--ylBZxoNMnzzBp8-_briV_rdoykFl9TR7tqlCZx-NM1z_Bp4__bvYVVozpFpuUudryVSIy-FlPTR7tqlCZx-NMHz_BpC__bvcVVozpFpuUxdr
yP-_iaid10020G32-hSsXFSpAWpy_Edpny-VFd_y_3lw_F7pfyyVFt_w_5ly_Edpny-_gSyVFt_w_9ka_Edpx_BpR-lpB_7p5t_n5t_n5t_n5t_n5t_n5t_n
5t_n5__zyHT_yHT_yPUfn5_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_yzuVQ5VnVunT__c5-nVd5dt-ON_X7PO2ldJeq0X08O22e8FBxxnQDH3Atsy9D
iaEv__aXulbflp_n-HFFJ_lzYS-VU7xQ_Odd9vwVTd_Y-OddfzsVU7xY-Mdt9vwVU7xQ_Odd9vwVTd_Y-OddfzsVjVCJpq-xFsld9vwVTd_MpayyF-t-h9sV
U7xQ_LaxF_7yjFkpTdxY-RdVhfD2VFx4yzD-V-Bp9vwVTd_Y-OddfzsVU7w-vGS000000000000000000000000007W
}

