sprite $cloud_monitoring [512x512/16z] {
xTqzOi8w48NHBd8t-z_jA_N-XM9VOvXpLi3ukm4gKky4000000000000000000000000000000000000000000000000000000000000000000000000yFD0
TA_FQ5uV-OEy1OoVfwFtNp-ZTtwQvwTtVqRl_3JkZ_x87w0_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_
-gC_-gC_-gD_WlxeZ_xeZ_xetuZ-7gZ-BTMaVylwqz2_PVv9_vRvfzRzvQ-XVyVyq-ZTttzI7lgtKFzbTEml_zIol_nJo_xoJotxop-rx2__rBA__5FB_l9F
BVlBFxNiB__Kih_yKyl-yayj-yi_wVzDHcrhsL_-IV-lKR_Iih_yKyl-yayj-yi_jUml_wJ_RMUDHpuq_UyxQjp-p8xZg0NzRxpfzlmx0z0_VzBD-VS6e7_-
eblpxmv0__n1uxxy3ng0_jED-VS7e7_-ddloltS0-cTVrLZrtnl0qF_EQsx8_y01w3-bt_tVEm3zQoMR_xq3qB_Mildt-vV-zvwIpF_y0UXV8vG_C03z8vT4
yWS6e7_ea43-m03qZzsHpF_y0UXVWVo10UWVEsC4yWS6e7_iYa3-m03qZnsHpF_y0UXVaVpt3q3_uEiSg_ov0UYVFo6TFpy0_PClTPN_mmUWVqNpvmUWVvqK
_EwN7u3-Yq2rDbBvymFGVrceNf3Adn-0_kj2jHR9dn-0_YyLghL0_lm0z7-nKAq5ygS7eF_BYMfj1F971w3_s4XKQu7yoG7elvMerWBvSmFGVpDHhGNofmQW
_tQZMWlapmn0_x7HQ6i1utp-_03q_rMZEktOa1k0_hzi5CYVwp_q_o-_ZfJFdn-0_kD4f7J-_03qFnKfcpy_0FrFHahcpty7rFzqfLp-_03q7nTKIkNF3q3_
Iofb-kS7eFz5aHBvymFG_x9AWVpn0UW_BgmKo1yUWFwNLWhaZmv0_uih1V871w3_vPa2-MC3q3-GAP0_DG3z8va2-JC3QDy_b2cGFpE0vlrZdLBv0mFeqp-V
Vqhb3mn0_qYdLFx00Fhqp-UVKla30sZPF_ubBPG_C816_VFvfr3-m03qpuGAvGyCe57_VFufKpymW6RzAzr_IjGF3A11_tJ-lFm0z3_ECO0Aa3_Tl_hqhsH_
0wY0pybl0FN1ZczM7qz-0v3V0FGt0FaDG7u3aDy0z3S0-Gr0VWEGtm3qDm3v3K1-0v3V0FGt0FaDG7u3aDy0z3S0-GtWe7j-shT7hkiGxu_-w8_-w8_-w8_-
w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-bFxw6u3--ijl0FhhBxy1wDzX0F8RWFm68By1g6y1wfl0sFPDyVdPLd-1
_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_Xmls-__y1zUms_loTzk0EYF_Xoj1e3-w8_-w4_Z_EYF_0zX
00K00000000000000000000000000000000000000000000000000000000000000000000000307m
}

