sprite $game_servers [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000000000000000002OdVjCGns7mJ0w5KUtaFslTdglv15V7Cnv_wDR3XqvpqwI94drSoFM_a3r
F-qFD6BLporg_tCZs1d-8rZztgBwLIDQsdz4gp-se7xUVsJznud-LUlfv_r7qd-Swr-r7d-DT3d_SRf_BSTV8rxAVqpmhmNu6_xyQp7-6lao_cEEVot0t_3d
NmlmD_pvrqhyDKueuJ_c-HT__YzMyJzUBNC7-F1CV_uVNlZXt_VdNmlmD_pv5__7koNyRoCG_mK___ElP_lpB_xy-S_y_Oz_Wz_-HzE_rlJdpz_-7t_xl_px
RUdz_stquf_Lx_jdxm7yey_yVV_m0K3-UwguVpx-_Fdpvy-VFt_-_Fdpvy-VF_yNY3z__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFlouTV_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpv__nUFFdpz__lpvy-VFdpz__lnT_u4_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdptzU_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_FddEyk_Ol7lTOP_DUAVBkrV
dVZdo_fNB_xvalxLZN--d7_ruvylvL_T-FFddo_ZNxtuy-VFdt--X7-T5t_-_Fdpvy-VFt_-_Fdpz_cVFt_-_Fdx_O-__G_-_FdR_-Dl_vV_bjx_twxepz_v
7_xddVzSnL-I94cI94cI94cI94cI94cI94cI9Ab-QHk9zaErRfjegrzQ5p_bVvonTzEW_y-jgP_t7nt2Bd_VVzLxmBtg9F_nJKTm_z--6IVvLzqNVEpd_STs
WF_m7M0Rv_bNhQ8Vz3zk6BXnohzgIVw-VyCmSEEWVot8t_Tl60Pk7FMlzVZp_Zt1Q_dNSlnv_v7n7rFyQpd-l7zFy6B-jHf_thy9U37_Mem_xpyI_cEQVot0
t_3dN_oFrGJatw-Uvy-_-FDVXZ_lt_Mxd7_nvxy0_yJF_ya1UV_Yp_zbkZ_Rd_zzbOT_td_F-EzJ_Oi_V_xjds_o8_X_cEc__rlH4Nd_3o_yyE_xyo_-3tJR
a_xxxTB-_9-olB-5Tu3vpzdz3qnfn3zpzAil5pu4nh_sEJNuynL__loZNOIV_wHkZG-GWVYVtJKU_lodTGb-_lFQ6XUF2CJ_x2xmwES_jUdw_EUsJNxkvp-x
RR8-__dDU-BdB_xYB_xYB_xl4t_n5t_n5t_nVv_uYx_uYx_uY__xn5_ynL_ynL_ytoV-uY_-uY_-XwVkxNBJYl_p_ocD8PURnlzepxqY_dF_Vpyqfl5_fCJh
I7xSa-RmRqowvZJ-HsgCkkWq_WTgpBhyDFxzMRM_x3J-_L5LzyPRzTQ7YdjLzb_AlohwVvoVLlpZ_lLYq_Wt1ZN6rPHn_EF-zMBJ-3zMhU1V_EF-su5fJnBR
hkFFlrvh6l-7gZNywmh-_E_rSFVr_FdNWLxCd_zsjlzs9N_-zThJ-FFdpvy_V_xU__Ft_G__-nh-T_w-_-UVzB-VBtQVxi_Vx__sV-p_y6_iQpVsoNF-_Et_
yhV_pt-lw1ch_BYTl_D__9t_vU_yFt_N_vZjx_e_Us1QOnp_m1MxBZwDVt_cTfth_st7fl5lZ_rmjUj_VZWoZR_uYx_uYx_ulq_ynL_ynL_ynVzzuY_-uY_-
uY_-xnD_yHT_yHT_yN-V-8k_-8l_Sl5lf5NznL_ynL_ynL_ynL_ynL_ynL_ynL_ynRyVVtU0xzkbOm800100ORVs3sm9FhSAa080001Wvp7vK-fRG7q00000
000000000000000000000000000000000000000000000000000E
}

