sprite $cloud_inference_api [512x512/16z] {
xTetbbin54H1cN-44FjVhRpqel6kqQoRZcqKFRdVFKcI94cI94cI94cI94cI94cI94cI94cI94cI94cI94cI94cIzFLfxQ8S2d_-_Fdpvy-VFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_FdpvryJV_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpxyi_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvv__Z_Fdp
vy-VFt_-_8_tvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpv_yrnwZzKFZpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V_wl6dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpt_sx4d_z-
J6N-_4y-SFxy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpt-gzzzXfVXF1VxH-ld_VO5_Ddx-W3h_7TuLjw78VnzHYFzKu9-jdp_aUFzzM2d-qy7-rpwn4F_fKFzz
R5VSe6p_0ltuIKVvxuAkk5Mn_YNw-RiEyDzLNN7JelsltLU8_nJhlqjByP_2_ElqynTUOVwxlhYDx-2VclYBl_YBl_YBl_YBl_YBl_YBl_YB_PzqflgtEwea
qjtkBWZmxsYBl_YBl_YBl_YBl_YBl_YBl_YBVyxKM-0Cy8yxy9cwklK3_4CFVARsuWVu1n_uh5YD-W7-SGT-zzGs_53_AUwXxkhHJ_QVLjnJdGxyUFyfxgdk
gj3Fzv_YNkgemC_td-9Uwbe7ug-xYMBzfn3_gUAgd-y_vRtKNO6Vxp_5lTLHe7-2_xJYtkhAnw_md_BUwap6B_AVujxgNfdwTVvJt4STyl0x_QUuZxeauHVx
J_md_lpvy-VFdpz__lpvy-VFdpz__lpvy-SVDFNntvdlpx_jT_Fdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VDFF_3y-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_u1yUVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdtzP_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VF_-A-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_vryUVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-V_xacI94cI94cI94cI94cI94cI94cI94cI94cI94cI94cI94cIf1y
}

