sprite $memorystore [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000063sxWCvpM0BmgXAPkRs_ZVySWvOme1X-dnREBUd_afmJjAFL-wo7fnUsd_jtrktFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvyz_twTLx2_-rvjg
V_wPQd_-cMf__fbgV_wPQd_-cMf__fbgV_wPQd_-cMf__actF_zq-_DFjp__TFlpJxS__tJxyyzK-_FFLFlpprJxyyzK-_FFLFlpprJxyyzK-_FFLFlpprJx
yyzK-_FFLFlpprJxyy_mVtJxbVqprVxyCzN-_3FL_lmprVxyCzN-_3FL_lmprVxyCzN-_3FL_lmprVxyCzN-_3FL_loJRd_-K-tFF-dsvvzkV_xfzkUVgVRd
d-7_grt-fRVpppJxstyorVxyCzN-_3FL_lmp_6_jyzzxJ_zCix_z9_C-Vqrr7Q3SVzs9weNZx_y_lnX__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__fUh7UNFt_xvy-VFdpz__fUVTOu_V_ldpvy_V_xy-Nz-eKFy-Ti_V_xy-VFdp__pQ_7_x-oVFt_-VlzJ_1_SyBz_7rzk_-uopVxs
dqorF_zCjJ__JBK__mp_-_NndLx3FzFiR__9LFlpprJxyyzK-_FFyF_rFhxP2_bdcltjFvbgV_wPQd_-cMf__fbgV_wPQd_-cMf__fbgV_v9jp__gVRddtJx
yq-tF_zq-_DFjp__JBK__qorF_zCjJ__JBK__qorF_zCjJ__JBK__qorF_zCjJ__JBK__qorF_zCjJ__JBK__qorF_zCjJ__JBK__qorF_zCjJ__3Fz_xNA7
tie_q-nl_ybK-_FFLFlpprJxyy_m_tEVz-dz_9DcV_jFqktFFzt-_DFjppzlv7zvPV_BVTetDpVsFlu_pi__Vru9Ft_-_F7pny__j1R_gva_V_FdR_xyyVFd
pny_V_xy2_Zv7zjK-_DVpVxyVuhBdpz_hpz_w-Tl_lpDdx_vyyVF_pjTNgmRfFcRFtyVV_pvy_Vwy_zgdo_M3SpypPz_9Jz_7t_ypP-_Zp_-viyVFtyVV_pD
d__rFbwijPly7_xxZ-Q_rpw-XV-8-Ey7b6f_yq-A_V7l9Dt-_3Ej_lXttkC0-Ey7-cSw_Sr_v_W3MDR_S_zCdR_v_wj_fj0V_yuR703__GJ_J9s_-UySVm0B
_nVzCzN-_3DT_lXtNlm0-5_s4_qpJVxcltFy0Ipyt_7FLFlppzJuuzyv_W2MZxzl-cTA_Cr_v_W3MFY_xP-fzkUVQV37ltFy0ImVVxVuPyxtD_-TumzWuR_D
F-dsvv_3_V7l77y0oyVVxVuvmT_yR_VF2VxuR_TFjp__dE2F_tR_dE3lu-zs_yoX_kQ_S_m1BFo_x9-fzkUVET4V_yxn1x3mtyC_K-tFFtE0F_xR_JFL_lmp
X_dZtpd-01R-k_bdgltvPmxmnt-xVwRQdt_c77_yEySVmC9_N_zCjJ__3Fz7TDblufyvmz_yzzpO-_ZZz_-VNd_-vi_V_FcRFt_y_Bt-_0lcpz_y-Rzs7ul_
m_Bwy_VwypT__kRF_zNwNFmVcTUVlzUVl_dpDt_-viyVFt-lF_-2-VCtV_xcpny_Vwy_V_FdR_xyVpF_ul-KlFxylVxypP-_-VCtV_xu-Nlz-HVCdx_vyt-_
-VEVVPVmN_FVTsaUqRvFg_hrr_9R3rUQQd_pp_1_Qkl5_3Ez_lXtakdrz_6N9nu0_y_rYlwPKd_pt_bh_9_IUbN_5FZZl-AV0d-l_nN_5FYR_nN_5FYR_nN_
rFdZttdI0V1Vh--VwV8t_vtd703_zHR-cIP_yzzvoW7mt-_Yd-5__zRx-6SEz_VwN_VFjFYR_yxn1x3C_xl-cGv__3iFFm3-w_tyCmt-vh_pw0FWlzxIFtEu
l_bVzyzK-_FFLFlpprJxyyzK-_FFLFlpprJxyyzK-_FFLFlpprJxyyzK-_FFLFlpprJxyyzK-_DFkltvfzkVVxhz-QVRdt-w_Vcdsvz_fjgVVwRQdt-csfz_
fjgVVwRQdt-csfz_fjgVVwR0d_yP1_23l___vC-VFt_-_Fdpvy-VFt_-PyUVFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V__fZUt0i00000338tteMkwe5000000000000000000000000001
}

