sprite $cloud_apis [512x512/16z] {
xD8n4G0m4CEm8NTPdp_RekWKYO9zVm000000000000000000000000000AItYwIzLIJfyW3ofyi3o9yk3o1_kZo0_Edo0FAdomF8douF87-wF83ywV80ygVB
0yYVBWyWVxeyWFpfyW3ofyi3o9yk3o1_kZo0_Edo0FAdomF8douF87-wF83ywV80ygVB0yZ_sALF0mS2A8YXbmUw_svleED6v2yr8F9KV-u0yjSVF83yzGSF
87_zmGF8Nt_m0FBN7po0_FK73o1__S43o5z_y03ornyyWFpr1myWV_t10yXVV_00yjSVF83yzGSF87_zmGF8Nt_m0FBN7po0_FK73o1__S43o5z_y03ornyy
WFpr1myWV_t10yXVV_00yjSVF83yzGSF87_zmGF8Nt_m0FBN7po0_FK73o1__S43o5z_y03orvyyWFpV8GyW_-M27a1-z03oemUGtm7afmuWFtW0_MyxOVdh
VnyAoL__nr8u_le_IuNYh__pLXZ--h-AXU2l_-jQvllhlvJBT7_zbtkPxQ__MZ2J_VLVBsQkl_vRafdgh_-sPcRwwxyrced--c-lPfw__dkocUQl_xvkPldh
lpUSIVxwxozdZh_-HzAPug__iNPc-Ej_D9u9_leVh-Vz_VK_ayy_ktH20a0K0p6KE-jVyOhulGPI0Gtm9jrV_xV_PFlh_neWsL__zmAv_lfN94Zrrx-cGQQ_
_bKH4ltrhwkGvwz_POOqV_rhEsJvwryT8ibV__eIEVxwTwH8yTU_fqM6l_vTCHByzU-hSTzV_yuSr_trx-rnsr__xY2N_VNlBtBNN_-995VzzPzfSjDV_wae
5_trdwjopr__oIpN_FMVxNBBN__fC9VyzPylSyTV_uqqL_prtscpxk-zyd_Vom2s_Rrd_hS1BFjxh_ol0zZrzrxvtmVmiqilnP9WCGm55-hFilYp7GxFqxVi
K8g18W-31Hlm3mAuFVm2m2y0_8K1u1S0VW7W5m1-0U2l2G2_0F0B0By0y0i0lm3m2m1_GG3u1O1V0FW5W5y0-0M0Nm3u1O1V0FW5W5y0-F_d02m_teX_kAy_
nfyH_nS3oDO0y0i0lm3mVpxL0U2l3W1_TG3u1O2_DG3y0i0l0Fo50U0N07u1u1S0VW7Whma0lm3m2m2_0F0B0By0y0i0Vq40-0M0Nm3u1O1V0FW5WByW0Fm2
m2y0_0B0Bm3y0i0l0Fm2m2y0_0B0Bm3y0i0l0Fm2m2y0_5S3m2y0_0B0Bm3y0i0l0Fm2m2y0_0B0Bm3y0i0l0Fm2m2y0_0B0Bm3y0i0l0Fm2m2y0_0Buy-Fz
vV-J_Vtputq4W5y0-0M0Nm3u1O1V0FW5W5y0-0M0Nm3u1O1V0FW5W5y0-0M0Nm3u1O1V0FW5W5y0v_W5W5y0-0M0Nm3u1O1V0FW5W5y0-0M0Nm3u1L30Bm3y
0i0l0Fm2m2y0_0B0Bm3y0i0l0Fm2AE0N07u1u1S0VW7W5m1-0U0N07u1rF0B0By0y0i0lm3m2w2GNm3u1O1V0BNy0i0lW6P-0PJp2m2_0F0BO2-_03vV363H
OtiVmEVw3By0y0i0lm3m2m2_0F0B0By0y0i0lm0Q-0s_0F0B0By0y0i0lm3m2m2_07hu3Ry0y0i0lm3m2w2Gt_0B0By0BlDRCWbWpl_t3uEl-iy2cFD_rv__
B80n_vVz-Gy36F8lyES_2c34lyEVVxx3lyMVVxx1lyUVVzxpR_BddzVyk_pvvot_Dd_-USc_pvz_tl5lzEUVL_mx_Vdd3VzMV_vvmR_NdtyUy2_svvy7_8lz
-US1_s9__dd0lzYVVnxmB_RddmVyY_tvvm7_Od_-US2_s9z_7l0lzkUV1_oB_Vdd0VzYV_vvmB_OdtyUy2_svvy7_8lz-USVy1_ovvz_m7_8dt_c_9Vz-MVA
VzkVVsRyr_tvPy9_tvz_9lpt_Vbdmd_Vdtyc_FVz-MV2Vz-VVoRyz_tvPy9_tvz_9lpt_Vbdmd_Vdtyc_FVz-MV2Vz-VVoRyz_tvPy9_tvz_9lpt_Vbdmd_V
dtyc_FVz-MV2Vz-VVoRyz_tvPy9_tvz_9lpt_Vbdmd_Vdtyc_FVz-MV2Vz-VVqRyz_q5W5y0-0LGoo-0Sdu1bFCBe9jV0Dty0kZc5q0tlm2w-GNGpI-0Rdu1
TFCBe9jV0Dty0kZc5q0tlm2w-GNGpI-0Rdu1TFCBe9jV0Dty0kZc5q0tlm2w-GNGpI-0Rdu1TFCBe9jV0Dty0kZc5q0tlm2w-GNGpI-0Rdu1TFCBe9jV0Dty
0kZc5q0tlm2w-GNGpI-0Rdu1TFCBe9jV0Dty0kZc5q0tlm2w-GNGpI-0Rdu1TFCBe9jV0Dty0kZc5q0tlm2w-GNGpI-0Rdu1TFCBe9jV0DNy5lp_jGV70W00
0023_Ar7iQ-w00000000000000000000000000000G
}

