sprite $cloud_healthcare_api [512x512/16z] {
xTt9UXih58LHVnPGcPttVzgqtFuIzuLSUwrfPlato9rAzTu0000000000000000000000000001k_r2HbCzQ0O-t9pnM1WVVDQ1-o09ukBtGGrq6xVOAhQx7
pUzLG7qBKDy2v3S0N_NxJi3XTmN8Rm3o6u3y1Y2_0SXl0F8RWFm68By1o6y0yj_z0D1VVWEGFt40w2-_0SYVE03qbpzs0EWlV-m0q5_-q06WFu_dzN-iJ8x_
LEWVIdu3q1_zqJ-C_5FjXlxeZ_wqi_ktokJuJtKYz4T_z4T_z4T_z4T_-kdgZZ1ELtS0_T6VFaxMQnFqHt_qHt_qfusJjRedP7_xJy-y_j4V_Sb--QV77d_q
fsL_zq_FFFxeZ_xqwFoqxFxqtFpeJy_DZ_xqwFoqxFvq-Gt0B_xrT_mDG7u3ICjFo_wp3xhZRm3o6u3y1Y2_0SXl0F8RWFm68By1o6y00Vdf_HtgV-ByT8VV
5P1y-EdPXv-7_ihwZtK9jFwA-gq2M80NVby9XiItW1vzyNCSumd7KPV5yUMxvGP-_MjTclxJyS_oqqVq7wFkXVuB7zj_L3BzmnUWlmNeFogM_XQWlmNeFogM
_XQWlmNeFseFnjFznmdzDos0M-lZj_5xkvtGVzS2zF-XzN7ypxt_e_qF9_KVhJRGVshjpxy6wRstN-dFwZ_L1leldDVV0lJt8g2_Aq1_2z1_79L5VrU0_XQW
lmNeRm3wMy0uHN-6iPFqIGpW6Fz2U7oEy6kVzFg4VqGJH_ZP9xq-wVK9pqzwVTBp4vwVzFoa_woVyCDFUdwoyoE_-d7zaP-IN_sy_CYlllxgn-L7VlNrLpyk
F_Ahhx_wyikll_hogv_G7_a3FlzbgIgxVqs1_RtNgwR4_l9NPVUlIkvVbTs_Ahf_HVUNFxc_ntnKTF-gyFuLtL_-vFvLwVqhk7zLVFyAxb_1_VMlAlqhjNzj
uFZNE9uqplZVg1_q3_tydwhS_lhNfF-HsBzgqh_o-bVbzjU_AhY__XNSN__w9_qhgNzLS7_zAxY__dKH-gC_-kFxF_H7V_J7x__H7_qPpwM_2q1_5q1eV_sx
_jx_gRy1wEy10Ffx_iib-jF72-Zl0M2P_VMVOllhFuNtDu0Hsr__gL-dFsEZj_GVQtLv-hTtUg7YilrjGF-dDy1b-rk0_bEl9IxVtoMWlmMiHVItWBM0_WQW
lmMiHFGtWBM0_XQWlm6iHFGtWBM8_WQm5j7V0DOY-Xl0MaH_0rYBw6y0Qn7z3M0jehy1h4NqDu2rZFu6i1RUduZ-1h1sHFGtWBMC_WQmbjwVZFwZ5ZZI-nFG
VrIjSV7-Jm-0-FvSkl-ePq3_7zZRVzhNd_j__bVk0FIVSllhFsKFGF-AxQ__5DnVVmFGlxBxwr_1_VKt0Fqhkx_-bTjVV_trh_6qLfUalmj0_yhjhx_--jUE
_kYF_llfN_hhhx_--kk_Rm3ep-oHsv-HsvyP8_NhF_Nrbp-sl_fJuCz_rTTVVltLFxT_kwF-wa-1V_yZl_xgJp5__wl-_VUlaya_4jx_mrXAUF-d-jlxjutz
vT_VVsj-zTUod__XuoEod__ZCS41ptzJVsl_SSVzVN9GmFDV7Vvj_Vks_Ehlxx_f-UySOtF_CUtepzXDVlNrLrz--VLNNtxrFwm_yZFaLp-jF_8pWlDpZ4-k
LmY7t_5NNtvNl_mEl_pgZwEIoE_uwo-_1RZyBQ3Lc-1NlgJd9pm_wL_vaNxu2SzFUdtIwnDUd_JwfDSdF3xfyT7-xIpWUD85qXj0BHnVddJKtIAzF-7zIUzF
Ud_2-vFUd_J-XFSdlJ_X_MdX_KdlJtX_slFxzsUepuODd_ztLmZlJmllJtf_mljpXFSdlJ_X_Jd2-wC_M_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZ
F_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_eJdf_m_8Jd9pm_uVbf_r-_LGOU_Y__GyKW_EudF3_X-GdFJtX-mlCJdf_m_7nOVW00000000000000
000000000000W6y
}

