sprite $virtual_private_cloud [512x512/16z] {
xTot4SD034N1u6p6_hjL0NAOeGMvhmFypR5S84cI94cI94cI94cI94cI94cI94cI94cI94cI94cI94bbPRMjp5JXBdbKNzU3_DlHK_7dpvy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdtqUyVcvr1t_-CzpP
_eq_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpv__IV7dpvy_V_xy-VFdpvy_
V_xy-VFt_vS_V_xy-VFdpvy_V_xy-VFdpvy__tNnvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_FctJ_MFjN1f_4qrPhZbuSrmOraTV_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_utYJz__lpvy-SVxuQafkhnxkPfAlxy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFF6t_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvyy_V_pvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-UV8_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFddoF-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_FdpvvyZ_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-T_RYLURP_gdshnyg2MU2tDL6LbjQyhlN-yTlHK_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdt6Mxq
Sslf_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V
Ft_-_Fdp7-7Ezg_y_V_bpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdVsZy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xysxfo-PjAaYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9qWi
}

