sprite $identity_and_access_management [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlJj9S5k7WG2waKdlSF_J_fcRp0dqOrVZrHLU0MIxRUd_oTerD_JNUkwn3O3_j__pkITMWFxn
_pkZ6Y3xw1__MKl0w7_YFtC9q3_-0vS0_EC_i07qF_KVSWouyttR_pHWrOUEqV_KV-8nGF_uprm2y8__n2L0__X_im9N9SUTh-4VVmmO_OR_W3y8wH__aKi0
_l4Vi0JeD_oZ_XnmvslunpV0w3VyPnq3z8__p2K0__WFM0Bq6_u1Vn32R_bFF0Re7_-XIu3-ySzl0Fo-_xIx8FtZdxy4uFVzXzq5wH__cKk0_l6Vk0JW7__q
2j3l-myy1k0V_w4xWFxn7xW4w1__eGs0V_n7Le3-yH_R0FXz_-IV3z4__WEN0FtZ7z00-A7-fmAFQeH-W7_K4e3Vzy__O93-yH-v1EWV_w4x0Fxn7xW4w1__
eGs0V_n7Le3-yH_Q0Fh7Fwu2yFFzJmFep_G_3TZmP_fR0clnFmqOgi__D631J_It1Fhw_4y3zbHy_gS2z2FzDQ2lp_zK07wUlmRqzVcVxBNW9_fR0drz_gS1
rrHz_gS2y2FzDU3ey-_V1U57-Li2Q_6_kG6BVe2_9R3MuX_G0Fh7NmFufuJ_huK_V_xy-VFdpvy_V_xyzzvZ_Vdl-Zl3_FdN5pB3dtzzFPj_Em7hlW8hmB-V
-h7mxoHWz1CRmBy_-h4DuD-V_Tm6yEyFVt01-FVrGnl0lvzg9DsVVpKJxS-_sWdsvryt9DQVVzsIJ7_-LzsKH7_-TL_o_FbVTMFY_FbN1HI0VmP_LPG__xez
GVxygm8Am3-6dp__2l7dNnLG0Fvf_BL7-_El07_-LG45u9_8NtkqF_zgkF7Fvwyzsfz_lRK__-BFFw00_Fdp3-Ilui-_4Vx1_Fpvrnlwy-VFVu_svryLK03-
_Fdpvy-VVnm_V_x5d_yBmfy_V_xy-VFdpvy_V_xy-VFV_Cq_V_xy-VFdpvy_V_xy-VFdpvy_V_x9_Fnz_vS_V_xy-VFdx_VV_Fdpvyz_9_FpxsUWFt_-_3t_
apz__ZkPdty_i_tvNtFV_y7V-t_uxm1-_jx_nz_xFwFy-L_ylV-x4VxH1NXEzkU_K_pvh-ZnvzzFD3__VgBv-VUJpC-_dvtCpx-VAvcVVp_P_FpxIURdtyyZ
cfz_Fz7y_Fk9vkVVJ_Pd_lpxYHv-_lra3p__VgA7dty_ZsXz_ltiR7t-_MJhy-ydxDR7__w4uVE_Ft5hd__z-GrpppyX--2FzESVGCwVFt_-_Fbl_lpVBVpv
y-VFd_yUxS-_-Fzg-FFdpvy_V_xy-VFdpvy_V_xy-VDVUxG__tfv-FFdpvz__lLF0VP_6UNFlpxBpJNWd_aaY7L32_YdFmMcKGB-0VPv7U3Vjy_lmEB_s-nF
tga2g_Wty5ChmB-Ftw_0xEFVAq0R3U0VejzV0lm3yEEM0F--Vdu35l-6Vlun4C5VoVZz9S1_vxxkhry0ntzLmji--rdxFVpvrqda3k3Vrv_HWFNW_sckUcck
_Shh7_zwUVQs_Z_D3FsJpV-J3E1lhm3-VVvP1LZy6_hvPq0CVmtZFmMm_ay6y3SAmB_F7rm0_dt-WGLO3_w7Vs81Ll4__FCASDQ_0bIDB03_mp-p08l_uHzP
W0n-_jlw_pi1_44BWF_XdrW0_lnN5V-Ao3R-LSMVVm1_I07MR7_-bPPhB7_Ljlwh-FEVoL-rPwz__iQ_YlyTuSz_BVuLbMtyg_Zpvpzo_VCt_bNyk-7FVyts
vr-fkIRxM_zL_CUkV_x6lue_V_xZrZz_uzyj07_-_8Fv-Hl_Alxy-JVu5O1_OFYx_V4t_bNy1txsnz_udupqvy_VxO-_yQyQw-_snz_uLutrD_xyZN_LM7_-
_F5NZVNdpnz_NQFz-HV_paU_-TcJ_Or_rMH_urzrJVOt_bMJ_Or_rJNPt_XNJVOt_bNNP7_ZNpNQ7t_LM7_-_F5N3VBtjH_-nl_JZFKt_loDVnN_RsLTzN73
t_XNZVR7NpNCt-MFVt_y5M30-6_-wGLm-Yl0tlFudG0kVnQ0xQy0-pdkykTJG9_yAG1-1TYs_mzcVyG2h07ZRm7O_WhGuEzjV_xBbtuK0By2XFBtjxzdWlZ6
jvy3u5S0_0hWvrx1UJGAuDUUVXACNm62-QyAZmBicQzuy5GOJ_hmNB0rcLy1zan-1UZpFzU3-ycEBC0UztelpmRsZ5S5mE_r0Bl9VrLc5E3mttluonLKWFry
DtuBuFUjr6lostsy8t3Fv5S0h_Rpck0rcLy1Tfy_rry1zlFj-HLWlMpu-t_voLxzl6pu-_ooxiXBX__rTpy5k5xqaK-VNzRRhO2Tnwy0Znl_vW_aLu1rrxql
b5y1rWtwoVmAiDhwsVmAi5hw-VmAi1hwaVmAqFyquFf0_0gmheP-5By2z4-1TVJZ-1MWtu1zz3yQlmAibdx-V_mKO3Nk_2_WbxtkJaC_czyAE6aj_lmlUod0
-e7Hx_FlUhyem4bZzBCl_WfmqiBFvrU0TV0J-Jqdjf_ZzUONVxc2_7SAlpDWDhy2EFh_REUk3HY6WY0AXj_zDsnEpHQ-cHPsxyHg5w0TlvE0zkwt0jh3hm3j
-1NWh-blBduDQ3_lKO3sxdSTq3xljmBQmwy0xHC_3MYV-2d0beUV5UI_wL_vUosaFVnMGFkqNm7Qr_mQq1v-3MWFlwy4s-bR0UspVWreN_9hG7lrQq0xVGLe
fwy1xTC-3MYdhm7jpU-6K3jz3MYdxp3GJby3sYTz6j1ENmMUX1zO_1hG7dqLQ8Ul0gMzptYL_sYDlYtGddmLQ8Ul0lViewzqwS1Xb0UVgKxt000000000000
0000000000000000JW
}

