sprite $contact_center_ai [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000cBrxDn0RYO4ewCBh_BCz-zm59UsW2n4GhCTPVScFPlu_gHlu4g2l0FeIe2y0-WK5u5S0VG7G
Lm1z1U1N07q1q5S0VWNG5m1z1T1N07u5q7yr0FeAmAy0-WAWhm3w2i2l0Fe2eAy0_0gWBm3w2g2l0FmAe2y0-WhWhm3-0k2l0FuAuAy0_WBWhm3-2k2l0Fu2
uAy0_WhWBm3-2k2l0FxV5u1vuVzy0FGN_WSAeB_mFr00_ON_WG3mB_mF541_uN-W0FeB_mC5u5_u7mY0_iB_G07q5_u72g2_y3yG0Fw5_u42w2_y3nH0V-5_
e03y2_y30T1V-1yeWFx2_q01z1V-1mB0l_1_eG3wjVupeL_jFqE_st-w-VdFTElpd-dMvp_T_FndklNvptJhyv_frkS_tVpyPxhr-Szqw_EVRdx-C_J_Yl_l
JGZ_d_V_rOS8_Z_i_ynhPEdF_EcVA5q1y4_oI03ul_T_w5to-B_tV-Th4lY_zrzSwFC1y7_iXQBuF_NtIR47-7V--xjvCm3-lYhv3l_t_jNVbUM_kEhd0-3l
s_Blyk_zyxCvuSy_Fv_t_VbdDMy7mF_05uRm_zW_NyoZ_lpprRpeppyVpcl-_FFjFENFFz_FE_xyyqVc3N_--MFp-_tvFx3D7_Fd_y0-VywV_piRVU_F_vsL
llVd_z1It_lpVsUjx_tvlxFOz_xytzrixy__uTts_lpVtMxlp_-1zVXVlWdT_loJRd_-IRS__tJxyq-w_VadtVxyasv__kdsvvzq-_DFkltvfzkVVzBjpp_f
zkUVTFlpJpxqvszr_bvznz-hh_bxzJr_dxxX_ypmTmXQtLjG-NiDVga___3t7Ip-FeJNwyy_tVxyasv__actF_zq-_DFkltv9zt-_9DkV_xfzkUVTFlpJxhz
-QVRdt_IxSy_wVRddsv__actF_-4_ot_MTof0_xyPr700N_-FxZgI_xy5qV00N_-Ym8E-FF_uQLVyEU_kFWJ_lmt1Hpmvx-v_WF-_3SR7F3dlzhXW3__rH87
_FclrZZWpt-po2r__fEIuQy0_hK5y1S0VmNmxoo0lm3uAu1_Pm7y1S1V0Vmx2-0l0FuAuDzP07y1y5S0_yu2-0k0lmBuTnR0Nm3y5S2_im3-0k2l0FwT1V0N
07y5y7zYS_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy__vdklVdFT6_DVmxip7yrtIlpd-bUcFySM9V_QWuiotyrtRlod-dUbFySs9F_QhhNv3_JlIJ_ER0Y_zKSM93_Qhhtup_JlHt_ER0R_zLqhyP_fdin
_ZFTQ_6V0qlnNqttJlndkZVYFmVsuR-QxdNuptGlmt-cUnN-Ss0H_glfteF_JFSM_6UwT-0_tIlmdobVG02plNh-lNTmtlVdFtFWqlclfk321V3bZPofzEUF
tm-0-MxuXpx_sgCVV-BXvr-hZp_frkUVwX_y-9FgXnz_glNn9zr7F_zu-FyylmBe2o05_0B0hm3wxmtz7-qW00-_0kWhmD4l00-_0kWhmD6lW3G__0AeqrS0
VGKu-XLmHD_GLu2ZNm4UVW7GLy2JH_zUttZuem3w0g2l0FmAe2y0-Wf86x_ny2kWMj_uupu5nCDlw1j7l_7m6_h6qM_e6qU_QTOtzEdZnq-VFdtw-F7Jfq-V
Ftt--FdJvq-VFtx-zFdJvq-VFtx-zFdJvu-VFtt-zFdJvu-VFtt-zFdZv_yVUtH00000mG0iWlvjnO1l5LQBOD-_Vl_s_TltRz-_Vl_s_Tlthz-_VV_s_Tlt
hz-_VV_s_UltRz-_VV_w_T_Rnxv_-_xr-xVltxv__Vxj-xVltxv__Vxj-xVlNx__F_lOzw_Vltt_zlthzs_VVyO-zlthzs_Vltt_-ltRzv-oxr-_V_l-xVlN
xz--_swF3WW006401aMmVrjZw3-em8aWla-xd_W-yNtY_Now3m000000000000000000000000000701
}

