sprite $beyondcorp [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlVjOOnlNmG2wuITmX_T_sjllbFIOQY3Elvv9J1u0Ah6bVJB_c-mLYVcjP8F8_3Dg0BuIeFzb
8Xl4CR_F491Z_XaLOFAh0FeAm87VYQ3cDmBm6m7uZG1NVGh0cPy2CFiL07u5OFWNBG0PSoe0qry1u5S0-FaxzrC0sby1u7-dlubzmwLViGBGePV-uSVl_Z-H
pyHaFl_lkFEt0JBkcx-VDtBj0U1Et7eRlsC0i5zmM2kWEAa09ERL6T_XNnCymL_cNRbWWXVmP_zTaWN-zGAG-KpEvC_alun_VqxqFqeL0Fm_PSO2Vu410F-c
-_Vy5_0tzuyi6VepiyK0WByE5vNzwQ-xyL_e4FvQlu1_emC0_NdU6kdpfy-VFd_w_Edpfy_VtHx-cfy_VVv6_sSqBVmr_xY_yk9vV_hnu8V8VF0B84P_BgQg
l-QFbtoa-_tfnuOF4S2_OF_WumIE-_mzho5UMA0tlIHMyu-y9LSLGE1VIEtNUch_z-Alby0P6u3_TLjpwYVyx8_0N-DMrINyxlX5cSfT_LFmVvrIxtjRB2Ap
_yKxiZYh1luL_Uh7WD_-Nyt-gYLymkpG_57wllL7oyV_PxPOHsPyicRy-zGn_eMDu5y_6sr3uBzyoxQevONpNVnD_JFD_ios_ed_wFnhDVoPVVtnPuau-Njq
gxRrT-PVP9lmFxXFrbKbmN_BWxyf-TIwy8zDrsRuLzgdrlpuSynp4_XhzGd-HswHRBe-_DNwPFJcTuEqDJ_-RCxldqTRy-DF_DzEyD-UN_klBnG__omR_8d_
Jluel5XV-DYoLrhpQ_ySlVdzCERa1St0NzT_dR_uJ1Xj-DSBu7ldJXtQdtzyXxzM0U3FF9j_pjtv-UTt-FcNuy_p-8iNW4lU1VwgkuG_J-d-kllaiRRB-Xbr
Dmf_BlDNtYhycSlyzJUhCtzUm3-tsu78xWNmU_-lwLydA_pVZUc_qmR4R_-F-3VQWPtV03tQysSky7y_UwoT_wTzWt-B0lZycxAR-6Td_rZecu6_UW6iVLE-
jZ__MBrfXhzo0Un_vXJulwiPPxn9kdhx7zcr0EfUEfd-wxCmMbmxu__ERfntwtHKFlf7jYo0Ks-UQVzY_d7k4VJ0Nwe0JdzUGbd_zTJpls0JOsT-0wJHJr_n
rny0sjy0u6y0nBmy8nTY06Z_AYdO2QErlm4mc_cxasRy6m3Qtm3WRm3Crlu6mEty_8E_0T24dp__aGjH0DgVFty5m9z_HVx8Vdc_l_Ot00x-J-tirktFFtlx
yuy2knBud-kjtktF_-2_Hye-4d2szdS0m7PfWl-BOm14Mtx-sfz_xsUzAO2sxS_V-EV_-3Vs5C1X_3yK0s2qzkT_ns2In_sDVmE0Ft_-3W3u-VDt1u2_4u06
_0u0sfy_V_xy5O33Ft_-_8r__lpvtvDCUS-pqVWR0FpvHsj__lEkyESl_ByT_lpv1tyd07tzFGYaz-MV9q7jtlx2lsVu2t_X_rpuytS3YByRGFmT0FZpZxR-
_Fdpd_SbXR_mxnd-mb_urmZ__2J2N_WBV-4l_8M_y1V-4lnBHF-B_XVzB_p5_1VzB_o5l_0N_i9V-0j_uLyg_9F_tMdx_2VXBz7MN_ZBvDyk_Fdp5_xY_I_V
3V_m-b-NVvlwHuhtF_OCV_xyXVyjuUy2qDj_N01gV_xy-VFdpzy5W9V_6G3Qdpz__lpvE_ppvv-T_Ot_JDy0uQzfhq_mVryS_lFOojy__Xe03l_yZN_-_DTF
08xSDSQ_0Q3z-VEFfhVj-1i0-FdpRtq5m3yU_N3uHpe0QF-6DoVuyySV7aki_NiE0FpyZNy5OFppD_uRtWBYV-IZCG2qFt_-mu-0BibHWp-pxwy0jJz__jdN
7xy1mF-utH__o7G0qFuz_V7FL03Qdx_sVqSQ-cj_0q3xypy_eyZ5dmE0zkT__wkL8XM0zkU_PwfkGsT_xPyPTGf0-ni0PRie-Mj_1O2VF_zk1P3u3O1jKtZz
1e3spmp-b_8VcGQ0wT-p0FYdkzVQNm7WVt7YatCOYGL_0q3xx_ulMFYZytai_hdHQexSC0x-1e3sLm3uSnHO3_uoLpFu8ulbLvSanqBxzpW2QF_H-NuM_kc6
9lvg6GqA0F_Ysl1lk4aA0By2m9-X05PtPqRdqnlyq_djdZcsvrS0-3CMbea_jZp9zLEGmWjK0Ek9SvQd0F0hWCR3dtzakHHUcW6mdW8hKm1b-1K0VWNGc5y1
ZAoIep5_7kq7m2qbxGXGV_sHMwQtV-SdN2c0m9-PRUy2NblC2W2_0i2l0CglEBTF7t_y2k2kDIY0wCsl08xgwyobA83QgupSAGfWzkn-1O1V0IoSl7P9xElV
-Pqs2Y3eFtSCqFoLijzMpSRyccKsvjSlynP-Pu6nZ_wHiaNNpBxDRsuU4__zpHC5Fltk_1hebEyhICqUYhDkL4d1dPmJ_ojwAPx_kEiVMEhiw5nBoWNR6ZNm
yL-uj-_7ft_n_eu7FziwlxnpasFMqlUjaEFf3uJ_-GqVwv-alBwl1YvyX7tuVJqyzljvgWfOBuTvGr8M9d35hFDBTttfhY_TzQMvlWpwvQ82ZcmI5Q3tdGVG
Lm7qLK3abP7s-j9zy4jxVUcEBz7zg2_jyQNzt9Vs-C9Uu0jxSQelXxPFGPyfv7ySTG1UCTYIVxO7nm800000W_oj9x6p6W40000000000000000000000000
01
}

