sprite $network_security [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlVj83ns5eY0yaRdCplvNspdnWXFoLurkdINeBv2plsQZqdRY_xRvsz9owl_ftxC0yV_hFsUb
qyHV_JlT0kgl_ZqB47_rx_KU47_rxtGBgB_wjoj0_DM_MmBYh_xD4b1_zMzNWFYhVxS4n5_zcoMW_khVhW3nL_zk2OY_-ZTBGFtLlrq1ug_-tH8GV_Llbe3w
gt-x0iHV_Rib8Fxgtom1zLV_imiG7_Fd4n0Vy-SJK9_pvmiG7_Fd4n0Vy-SJK9_pvmiG7_Fd4n0Vy-SJK9_pvmiG7_Fd4n0Vy-SJK9_pvmiGd_7d4t0lO_3-
-wi0y-W3_i0b83xW3oJWlG_uC-y1Zpxcpry2ucF-V0BU-vW__Hvm0zb45dBYh_vy0jxxk3_r7d03tKGdFhr9ptkVzUTN7dtMdv_ui3y_xttMdrzvz5b_VkB3
_loyzrb_VkNHP_tvYG_xy_FUP_tvbKUVzUSdFkpFptkVzUTN7dtMdv_uh3-_KX_tznBGNt_zzTTVV_trrrz__VNNNt_zzTTVV_trHwU__lhhhx_--kkll_xw
ww-__lhhhx_--kkll_v9Kt_zyvyryzS_twsFl_vNVh2hYR_--Sb0M_rv_gGUxwz_vPKztL__bxowUhQ__dbZZ_RNFm43q9_dXmFGNt_zUNu-0Ftrrv_dvmFG
Nt_zzTTVV_rv_aH__VNNNt_zzTTVV_trz_E_H_lhhx_--kjV0Ax-1W3uwmy4eBy1w4yiL03w6u3-_8eCG7z-0GBGtm3qDm3z_HX0VpyBqDy0zFTZW0FyzK-r
zjS_rTfV_rHhV_rJhVtrJxNsrp_rT7_znm03uFtr9mFW_VKd0-3zzIS3uFtr9mFW_VKd0-3zzIS3uFtr9mFW_VKd0-3zzIS3uFtr9mFW_VKd0-3zzIS3uFtr
9mFW_VKd0-3zzIS3uFtr9mFW_VKd0-3zzIS3uFtr9mFW_VKd0-3zzIS3uFtr9mFW_VKd0-3zzIS3uFtrvmFW_VNd0-3zzUS3uFtrvmFW_VNd0-3zzUS323Zz
-G02Jdy-W83JdmyWuFJd0mWu_Va00av_Fe00qny8G7zuV03wiq7j1x1owR_zY4yA83-O_hkFzum0Ne7IV-_PfWu8uDNfl_baJmzWwB_vM0yF8Fh_T4dV0FHF
qYE0I_-zvrc71n3zlrlIE03zqQymym7etoo0qdzza8q3q3_BcdqQg7z8Vpu0_Ni5eF-wn000V_tX04h_vV4T6i1rmmMWVzDF0VJFChyAgF_Zfx_--ikVI_-q
dlxwwzzo-kklVwNpz4_l3VrxJ_zsqrz__VNt_My0K_zdJd_zzTTVV_trtmz0_eeNWCV_MVxwwr_ep__E_MtnwpzEzjTV_z9_3-Pm_xd9hpyOmEGkW4j_Fe39
NG1JVpw0USis-VK70hZJl_HVTW41aFxpw_cldBG1143wJ__wruO96C1a0YZz_ny1J2I0kKn_Be19133rlpq0tdzkyEiF1J3lt0Q__fi50FwVKgel-mg30V3-
ymB--Syf_li5L5uPvhzkGr__rmgej-e0_TVjwEl_G-RhFTS3wRzk2r__bVhzxmVQVztw8P_--xi_W0biozy0NlBAFf-G_80_S0C0_le30R3--fC1yFxwWm7e
p-y20tYS_nKlW8q0ZlVFTzE_yifuV_tP07X__SbNWFu60FhBdm47WFlhptuCmFhhZmU0--lF1t2-V-NCyVz-EO_mZ_uR0O3--lC1FDvV_v7Nfhy17EqV_VS2
GFtrvmD0_VNd0pZPVsHx1d2mV_I_8G3KNty-0FqDu4J_w7zJ0AY__dm0gB_-V007-bVkcm6Svn_zxmm0zTUV3q1_0pZ8F_hV7G3ghpyVG7D_0pZ7F_f_HG2e
l_vy0FeRm07-qNzZlVtr7_eR0EulVmOOWFxyYWn0Vtw3sy7-lx9l5xOLH3401CCMl_wh3Og_CEIJTgw5MVluy5_O0Fm5W7_LNm3y1N3A0GZWy5y9WBy0yE_v
Umx0Nm2p1YK0ux_cBu1zVm5q-VdpTmKm-7_xS0N8Vz9tWFnFrny_V_w7_mu_V_u2UFg1VuZV0fYalmy1ZJz__W98y_FFVlVXLn3ZRm5CmByQm1X_2y35lm1i
Vmy1FVeJW1S_2yTSDO3eFny-1F7PXxy19yJlNu3iD_y2k4rW6dzyyRyzLgpvdxG__ZFyBt3lPm6qnry0NNx-_0M0V-ruulzrF9tcmNzx_0NGvVSGWBy5qEON
0FxLuxdkFwTzrFtFwY40_Foxsry0xV4NG9lVUu3sStyBe7to5q1x-mi0F__kzXT0U_m5qEON07x-tPE_0Dhy0cXlVm6q-GNGvUVFNm1jVW6q-GNGvXT0czy_
OUq7FnP0U_m5qEONG9jV06r-0RJv1T3c5q2RNm1jVW6q-GNGvXT0cz-FmUtVVBqB2hppSGROz7-XUEKDq9v-rm3jSxzpGFlANm1jVW6q-GNGvXT0cry0RNu1
jFa5qEONG9jV0Er7_Wfe3xy0slm2QFCBeFswLm7juHT0cry0RNu1j4_z2cWFlm3Q_BuCRlDR0Mrz0RJv5T3M5q2RNm5jVG6q-HNGrXT0cry1RNq1j3_nL43x
LPy2sgjV0Mrz0RHNlmBQmw-0jhu2sleAQEiheAslWBQ-0jhw2cZVxqkWFVeAQEiheBtu9T0UVGcKy1tFD_xjlMy9j4TV0kt9rq1xy2NGnjS0-xVsu5W00000
O92_zIZsLHS000000000000000000000000002
}

