sprite $cloud_composer [512x512/16z] {
xT453SHG00N1WrAm_jtMGkdJowo3pUmZ9qcI94cI94cI94cI94cI94cI94cI94cI94cI94cI9Eb_B_5FYB_uYx_uYx_uYx_uYx_uYx_uYx_uYtz6_CLV_CLV
_CLV_CLV_CLV_CLV_CLV_3FYB_xYB_xYB_xYB_xYB_xYB_xYB_xYdn5_yHT_yHT_yHT_yHT_yHT_yHT_yHV_ZFYBl_YBl_YBl_YBl_YBl_YBVsJynL_ynL_y
nL_ynL_ynL_ydyTVE0h4N_p5N_p5N_p5N_p5N_p5N_p5N_p5FoJ-uY_-uY_-uY_-uY_-uY_-uY_-ug-jHEtysq_ovy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VF_-8-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xysyUVFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-_HVpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFlqpy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdB_uHyHT_yHT_yHT_yHT_yHT_yHT_yHT_yS-8l_YB
l_YBl_YBl_YBl_YBl_YBVvVzInJdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-QybC5R-bv8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP9q
}

