sprite $persistent_disk [512x512/16z] {
xD5N5O0m50Kmzk_pxnOHq75x4WkfD000000000000000000000000000mFap_0VnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV_rdyun__-CS__l6FV_pZ
7__unp_-yOz__ECV__Z7VnR_-CS__l6FV_pZ7__unp_-yOz__ECV_zdyun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7V-4V__Z7F_xnZt_yun__-CS__l6F
V_pZ7__unp_-yOz__ECV__Z7F_xnZt_yutya__Z7F_xnZt_yun__-CV_ioJ__jlmxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-
_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_UF_RO_UYG26OIY0ZVLM_cnZ
3lc-Euc26W000000000000000000000000000000000000000000002SzDLYVnB_FURVlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt__
_ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxzy_TV_pZ7__unp_-yOz_
_ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__XN_yun__-CS__l6FV_pZ7__unp_-yOz__ECV_rdyun__-CS__l6FV_pZ
7__unp_-yOz__ECV__Z7VnR_-CS__l6FV_pZ7__unp_-yOz__ECV__ZFvH__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xzfm4000000000000000000000
000000O
}

