sprite $cloud_domains [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000000000000000000000000000000000000000O7RjsDnn68Y1S02i5Ah_
Rgy5l_CQ7sWF6vZW9sm6Uk7esZql92TKp1_yNodwf_tntzt_ZU4x_4t--VdZxpY_hXf_-Alyy_puJnZ3HVxmv_qbVIa__lTn_lZdv-yMV_ZB_FFy-CVvDHt-
79Vvv_cPlxCOWHlNU_1Nbp_ychn_4p_-KVuoVrv_oi_VFVpCNoaC_F5Ncp_yoljF4J_-IVuwV_YTzs_Ynp_8t-UF_-Jz6pxxXVzuVmmt_FFyBl27lz4_puz_
3CCB_pZR_l0hFdzD3p_-ZZt5KpSkV_1_fLZa3t-bVvuV_qdnz_XpNE0VuETaC0B_E6VxuwzAV_YLzvyYVln3_9N-lFxal7yHF_Dt0AFN7_-9OAZ87_vM_pm_
_Xd-Kd_ubVTt4J_-MNxyyP-2ptxXFzWVmpr_n_br5VZ3N-YVvyT_Fe_XMd_uDV7vAy3F2M7SWN-Se3_--nZgzOTVUV_fvST_7yF5_l0hFdzD3p_-Jh_-fDxv
ux-FeM9_-3Lv_oP-_0Fy9VuSlu6nvky0FoSnnWT__FzSd09_-0lzy_puEywlWld3N-cVvyS_mD_hZ_-Sv7zZkC1_hZ-6w_vvVXVumz_jd-V7Vn_3k_yu-_xm
Apv_JS_h3tylOCH-SG87_pqCjVl3hydxD_BZlu_XUd_ubP-_uN-ktPFtl_5_usYPF-__Ih777t_r-0_yHVw1uf8__ljFSJdlp-jFhfc_umyE_BNWluKnyHid
_3LXVpNv_pg_c_ppHJD_fVch_8luySyNX_ahot--_ut_0aQ7F_ENz_Zlzp3STkFmtyVeykVrfwdndtXHp5yJvJ_U_yO_W15AclbhZt_1FyYVzyTVPVu3VvN_
Vj4B_lX7-7tWZJlVt-Vwt_Y_pI-tlFuqyHid_3KvVzNv_p2_w_ppHJ5_vVXTv-yWF_xQzN_mN-3N4d_UVw4uEN_yLUWFVu-_uqLT-3l6N-XVn8__n8jY_feL
VlpnNy089ms_hXh_V15_ASLVwGz_aN--EFYhWx_V__vEVzVuEvza_Xl-zv9_d5_uQrhchyaduM_oNorwmH__8B_oIGVus_sl0_rl_BVujS0VzzygJiGVVxNw
mz_ZxtXH5_uEyBlLFyAFltRz7_pN-3KjhpzDuiRb_V5NhJ_ykchyyqNZhm1_h__lyRlNF_xWq31_BV3N-Ml17_ymXlD9-EKU_tXH-Cij_9fy4dvDZt-yAFmr
BVngJTvVxN_ziB-P_rl-Tzv_jOY_59X_hV_0N-I_LFGV_F5t3R_pIVWFyx-N_V6V1VuTZ0dSkAm__khsXx_8Fryq_leelylzVuhVUN_j-Z_R_inV2_nD_bfv
SU0Vm2ZmXzyr_YwuSVW7-7lyuTVK-Cy6HigVK-clK_tXLzC_JfuV_m1_qX_-UlyfuiS_mD_h3x_p_WMV_VOU_35C-a-0F-WFVxz_4p_-xsBuO7_ubP-_J-77
__vfV_m_Kfo0F_p5_Zty-3lEhq_Dd-EZ_VFyp5_p_nZuuw-GFoUEaVVFy-EVvtV07_vk_tv-_3-Ld6_nnr-7-yFll7yJF_u1_bf_-3Lv_oP-_0FyjVxmApz_
yzal_YNpnp_Ehmdumr_ityEFl_yVmqN-y2_xvtznVabZhZ-TlF-D_mP_l__4Yy9V0VvUV_YB_FD5uwzjVf_a3_-wltRzdqyc1t__XV-kzDU-F_vv3EUJy6jw
_ED5uQzfuTVaar_Ex-Fz7_pVE5fu_jTZgCSVVntbR_YB_FD5_AK0Vwt_mEyU_tmHVxc6tmqtxlur_y7_9-RVxp_nel1NWB_N7_vL_po65_vnyA_WLpxfOdxy
R_mN-1VyCnZAtxZ1tu7vz_ep_nv_nukwy9yrVf_d3_-YltP_Z9-4F_ulybVwA-2FVmeZdpJyHVxv8lvIWB_MV-1tgVzJu8z_4iDN_iRXFu7vr_h3t-GVBmf_
JGk_9f-4NrUFVxme_BN0lpN6kB-NFll5NsVwC_yY_tnny7U0lzUV-VVu-qz5hzmu_AU5NyuduI_odvqlJV7VVVxTUV-5ue8__c6CV1B-8lzyqVXhWT_7-dyX
l_F-slL_OibX_dw1lyzV0N_yinZE9-7NzFZ7Yy9VqyAloIVXrzNc_pJuuz-CeS0_3luB6Et-y1Vvvuluom7-MlzX_aN--IB-cfRNdvpt_xRFVfNtLyW__uk3
_nt5c3Y_y5TW_ht-y2_uXp6yLpJ-gk5NFkdlulVn_dSsESpVB_3d_CD5_EMQ-JkVX5_JuxzGtF77F_yKboRl3xzgvg-vdXv__9zAVsNyySzZv9E6lyW_NyHV
2l3t-Zy_x-yU_mV_V-t1WG00002087_h5GQe3W00000000000000000000000000000000000000000000000000000000000000000000000000000008
}

