sprite $dataproc [512x512/16z] {
xTrNTkCm4WLG7rM0_cR_kvtEhV7nj1KWaJJk_UxeLqGL6F_p0m0000000000000000000000000000000000040iYbDyQG00P3m8JaU42dYSzD7t0TuEW9WA
001oXuWl1W000038fUyD9fuE000004wlHgoCqzAtX1FtWfab1P1xfll3SxUMRwz2FDbRB0a0o5WQR_5IA0000000Jaj_8eRu-W0000000000W9mg3WJvitRy
r4nnD5Ii2ldJspnqSdec9kI_13e3-NiFbFmNH5Si2ldJ7HiuFHKJyby2tGP0-Q_wdL6wAzQ4_EbV0-2wgx_yboR__6fl_sD2_akW3O3oN_Vah_E_tyIgU9__
OkyPffSU096__EkBJNyycFyop_hHtmNoNvRyCv3_gkHViI3aJ_yG2qB-zB838FAdbnq0aJ_zKo3_PSa_lz9bVsxEls8vo9_-9P3_girV_--CrI1_Uja14FdJ
lyLga3-zx028_Ebb1q3aJoyx029_sW0e_-a3mDkcc93_4kZv0q1kZGdvBu6UEW1cxG5nhPoQVv_FetDpnDLgtW1Ovnz6ROsuGKt9F_lyHzUsY5jaZVvXJlhR
Lm0tnpSUoR_6-RtHSI1aZz5rv-yyVsJKPeYRdMgSntbKJWX_woR0_SluzIMGrUT_6vsR8EAXfNpqluiWitgShp3wj05cpF6ZkoepBcHcLOznljweroFkLkEZ
47yutwVhrOW7r3ZFDJfVYtX4zdcoKIz5nAugO6GS2ZMaFuCA61K7mVmcq1a7nIdxuS4_ZemQQo_yL8_xmi_u6iWRIs3q5mkVpwxtwFcAO2nmt9DLtJt6HUmN
5mflSNeQuXKo5W00PCm5S9gAs3q000381t7OKy80y7OlukLECHT0te7OnbjC000007aLF2oqBG1E6rmP9hO00000072A9mAwCzP5h_xbDVclMG6dB-ck_B_f
M1Azz3Vuh7djuykE_rygTkmfzKaVvFlhexCgvk1o_Jz20OnHsTzKpEVulrIxJB-pVybu9lcVE_QcHrN_bS6yk-Fx_DxOM_eZgozLJERut-qGq7tkYEn-JWLG
vpqNG8zV0qbM_u-CEQYnsmAeSJcFLb-gZFMSLce1rU__7VcK9a2E_HN0gSO7_ugiTPl0MpnFxwq0gl_Vl-4r5M096B6Tx7-LODQN7WES2Afn4V-d5M3mcwDs
KW3PrpIWUdeJq0CgDj3ZolaZQsu5a6Fx6N2SVyhuNDRS9i3OUWRi6vUUkHL0Rpi2rEr_RzRpce02o7Ybl5Xtjgo0bT_FrTjrW1ptpXqrhGdGhzy3vFlPxtPP
Jwa01P2RpdwtLq36J7O1lUFc_rxDFoMi07AxdV_jSa8J8CUBHi2tEQl_fQo7cm3vyX6mvbIR2fX_CMWSO_M_L1F709k0VFubpPuzRUQqCS0CE5ut-sTCazKP
HvMx6W7oLSLMCS7i2Z02z0R3tnHP5O_J0JOu_2Vf2HNWB41jSFZFKbtn61rWxFdmpwU_ur07oDqU_XbNwFQWnnroQWDu-wJAElOdDn3xqIze0FN86dEwGIme
Poq04uhwU8S_VVwb7ZBXyD-K4R0VSSrVC6B7x077_U9VSiQ4oVFcd_5W_jSsc8mTCm5CJl_ZvP_J_hO3Z-GVdwb7bt_o9lSk0BFJ_sNiVVadxyp_flCB8_QA
SK_-fzlE_NNSufLVIQ7ko3--kNNv9_TvWUdc_EDQvzzYl-mo-hRyusfrXFPFtfJ_FLSNEdQCSNt-SOjn_-wV5xvNeg_D_-whox5lTW3Jqt_V_idzpe1NvJ_X
xg9zOfodf__DECZuHtsM_uIxI_UB_7V-6VUemun__3F_k4yV9d-cf__DSFRtC0-QzEpqlnc76V-fyQ6tUC3vCFbJ_P5uH1uxV_5FUxguOzVe3vnYZVp9_a0y
h0-Rl_WZDikVdEYkrXzJZ4FcR_ABM3X_ar_Cpx_Y8BJ-cEVyowWu1l77JB_Ixymu0gt_5FFpx_ec3a3ypxYfl7w8_Q7VoUdvZ_ubzaxhhvWjEt-BVHD_nSAq
_eoLK2kdpwwN_bT-MLdhhuobk0CqLrxwgIUddn-AtH5_nMB8bHk_zfyhDtvgfQN_50Vsb2rmhTRuLMJ6Noil_QJqnV-SfJ-l4jkXMkCNVyP7o1U9RUJpqj_n
rJZoClvQywEtr2SdUycNsIh-ZEDXmXTGybdf7w7yoSyRFsylzFArltBLrr-pSkCdLrxwgQvrxtIXEfVQ2yK5yWkbpytx_gnO4RPPPCPCy3PJR0_Wj8tv_sHd
Qcu0a9k9pG1msbHi25oa0030DWXmAH00lAGKiED_efWD0B0N0dT3GUvR_0i0W7q009e0Rrz5V0003qS00C1f5SGB0G000000000000000000000000000000
0000000000000000_1S
}

