sprite $local_ssd [512x512/16z] {
xDAr0GDH44D1yrUs_LThPhhyTgO4FTLl0000000000000000000000000000000000000000000000000000003aeZeoryXTJI9tesOXpwePO-LDjMAhl1lr
7MdHFwa-39LlgWipvRlgmKZvfQxOfMF_Z3eXwTa_sHH9t_w9-dtxUy28_edw3Vjxm87TEZSF68I289pmwKsc_hjrvCZtRPZP3bR_2e3y7pDg_VmXVOj_2nYy
_YrWWTU_1K3-hyIjdp-uzVF7_UpB7zm_V_xWriyVtFhvWri_VoxLio__ft7tpn_KxVC7nDtp1y3LFF-dKJtxyd-QKSy-Vt2LplzfN9NpVnfNuVoVHbKt_wSP
zThpXxLPr_mbdsL-fsZ-8D3F_zK8zFD_DUwHvy-e9vu_d54m_yzdWui__tCNiFwwM_xWtdR-u5vs_k3UTVwSyUpB__DnZpf_S4ywVt0FEdzmppb_hgsUVVb_
Vyxeal_durvo_d14ZxaRmATpG8dxZB3z0YR-7HSm_VnVI9T0-YrWql-ch0qN0F5_NsQp1JomT-Veakf058IT-aZpxd-tp-JDKvVwaXL_-3sWE4fbWH1f-nh1
HIsh1BpbfL5jdqQGVGbOKAAE8G5NOE6NW6Jfbu1X_pSe0UnB0FiICEMsJm9YzYL0wPU0j7q9O5y2NcdxTWVGBm4FiO-wVTJjesuVx9z30ZRiGKLyykCLju-9
sqVTFkfj7-gJ7tNxgDj7tJxOtu80N6oTeFwJ3_NIZxfzrEsZRX_rjW_noOyhRXyJjm_s_u04f8xjGxtfHxtq8suVKxOFzjdVlC43lYyBzg7jWxOFxCFdsA7j
WxaF2p_OnyCtUC32VwXWuDfG-ijBXeM_t3ImFuT-Cc8ssTzV0jYVznIea2Js9K3R9m7iIm3xZGHe-a_znNWjcFp7_cuiiIy15du9O5y2j7tlU7CC2-mV--Um
u5wl_MIQVWamzsi9qFPDU5Unjk_bdHAbtui5sZu9OFzzQFkwzYM0_GMD8Fk1TmoL_c_z7vhx2-nBWAP_PGBeTz84-njkIshxZjhFBGBiJw1ORU7QE9eMWPlc
N4fM0FPlHW3slS_rfBw5__N7zYqA0Fspu1huNpLyi-G2w7S5ZwDjd_zPFNZDpmigd-u0Aw0h3vptt6S23onEeufsx7looxvDV-nR16p-au1X_nZFRmDUs-qB
W8t_VWgmhmQKT_nBGBdfbm1D_zEnyCUPk7tKspvClEs3jkzTI41vWuS4b1_oQWFAvtie0REzxSF4xQFUzEF3x5lu3yhHzab0RMUdHO1z2M1V0buBshwBnqC9
c8-V_BZYfHyJju-wVHomlq-_1B0l0TLFUE0_sBVmWttsawKVsZvCsJuIzi4-xEs3jW_QFaJiWtsusmTj7zXdNm3ebm3sUmbWNm3Obm3tUYN0cs4IeFHB0FiI
mBu4iEzvaAP__vVRySVlCbON0QLV0jYN0FObW7q9qFHBWCdlTW3x4i2-HO1z2M1V0cpma02JNmBObm3s9O1z2N2lLm1iy900fLy2s9S0zh-ccm3sowT7QFgV
Sdu8lltHV6vtWDB_EvAlYx1_SoKN0VPlff00RL_v83bp_tAKeD8l0UnB0FlF2i2mVv0Dcn26_LEKpvIslSUfuag_1B0l0UxsVSl_MGAsDjIDFMBQlXi_1Yty
sW3szsuGuhySOlgd_FE5_t8Tut_1pnZ-Zr4EC_-lSfpvtt0lY__zOpMFyyz_ETFybrFD_vHppV-2A-F_67lFgEL__m3DD_hdlnnl_gzomFalH9p_9IFpK_tp
Nquv_-cSyrzEEl-fhFE_RKVqGV_yv_BE_yB1c0F--PzovFdllV3A_qtlilc_wLqu_pVbwFC_vNCl-2zVFVzVdy3m7py2gUxV0LXn_uv2dhX_9s0E_qdxD_mt
xT_K_ViaOjs_Bs34_Vi6qfNqp_xD9FspVrFtxrleJV_it_1_ssyIz-y3w4t_xDy4_BVr6vwsVGFKjc-8slOD4ll_XYdv7xx_ICS_rt_E1FpNx1ihzl_tQ5rV
dq3Slk6QUjjdkCnzm_LBUt0i00000338tteEkwiD00000000000000000000000000000000000000000000000000000000008
}

