sprite $standard_network_tier [512x512/16z] {
xTr76gH6383H3H_IJlU_hGVdt84YY7flRSzCywleGAgv0G00000000000000000000000000000000000000000000000000000000000000000000000000
0000000004J-eIQc_YPg7kI_M6jUyczg2cGQ0FaDWFm6G7vV0_It0v2_sm2WlvIZy-TIpLZ6G_jdjMCdFb5_TbJBYVlxyRv_VvRyBt5-_sPJuyVx73W0qMx7
uSVxV4FKEzQ6FnxxyJRVu0m2_Pzv1e4VRoDVU-uP1FhNaFwH5mm08-BbQrCVGTQ_7jnV_xhWJsX4_xfhVo9VYpjyXQnH6F_ZxR8ptMtwwpy-OFNfR_y_lk0w
flzIT-NzVvCjJo4WNzipIGDtGZUZ_-i_AcgM_lflOi3WtAo__b6V-ER_MkRkx-8T_VMVCB-BT_NNNtytxyXNefxApNiS_tNphk7BNyi1cx_TXn16NiFVxaC8
tzz-zUgDhlyHM_7hOy4TFuIoVzjTjxbZzsS_Uc--lIV-q7ptQT-_K_ltp-dhkmc_-3lC-naADr4W9nq0381X_o5cEeZcsND-H_ViEGFmvglLFsFkBpq689s-
PW2Slce0fdtsdAlwm-KB3vSlk7oj9mEWlm7mxBdN8bzn-uh6Si2MqR-jp9Xt0Dmu8d-OzhrH_u4FPfcW__Ay_1CFW3k73Nuqc_vjlzZPFlc6cI_mZeSDWFx3
dwomgQwMsVhdNzLK0-3tdyo31Y3rV-ZriV7e0PWgVtprydBk0N1rVxvfgORcpJz-0DBvNpSsuF5yymt032TqrDm341Fl_SSFm5hjECzrv01ajJF1wj_xoNrz
z00iJyyVkvD5pm4OzUmvPxdd1-9vHqOyf2q_yRWpOvpb63q7W6LGi6mv00nxpyw64q2-QNtY0103SqMx0M1ehlpGMjTYy7BDJrLNylSV08R_QBSq6W0Ew9GV
Ype4rnoroy_L9HYUo038NqkF0U2ej-ZCQJy4MFwR_4Qr8N__0U3GCFcOzm3vbtFwRwerozy0o6y0ulu7EEFu8FcTgEPQJFG9ENBA0OWMB-YK_N5-omFoZtP8
2WEmDZdFwQppitAk2LYwlAcTbI7oQvwCsZt_9h_dgNYNzu-wSW0MTufgllmtkOF-HuXJDt_kuKwHNVR-1Y1Vcd3vRt8N_GSxPCCRW2ul9RhrJ_qRBFyU0w3_
DHVcvZwXV-FblycTz1yZBjhUSOi1qF-o7MxkjUY_ttBTQikn5lqRBVzD3bV7qB-E47a0_JznxLRDGzHTMFwlv37qxv1_amVfqJ_qFqeu_-Erk7unvM7gUdR_
1g3_fxywLZvv0dpuVscTT03Aylz5J3a0PVd_9YSSW9fb-Hk0vSMnAlqZZnFtEyCoQgRyTW2RU16_GNy3C9nFVmR0yj_4f0EWlns0_0P0_pgnFpVSR4k30R3y
fza1wB_KCmU0zQRRRDx-Tl-RfS40-FJNV0T0t7UBwN-NZHnb0Ep-ptTqVnRzxydotpG-4KX_LuNgt_-wSD_-Id_B_p9pzzU_Pkrlzw-_vQ-__lgxBTtu0I3r
dvB-IzsCtR_t_yZSn8JzzRzW_vJwttTFFC_ortyv-T-eVujVOQVeht_-9s__cyZncXo3iVmtZ_xwlvo__VNlynlCi_lhdxVk7tK7CN7_jFohPisll_vhwRzE
t3zB_tfg_hXt_pgM_gd_Uphbrt-ycBg__dL-VltNke_GVx1UMwfQvTT_FFtr7vVVz__gTexy1ETztgf_tSt8_8x_LBIxHrBk5FeFU29re_xzNr8qU29rbm7e
UFVrqd_Kpq3LSAJN1gUUDzW3j7r53Pv8tcG2MhwWEbw_g-Fp2prlmjNWqjCU7mBgtcxrlDrg83yIBLzFDBZrH8S1Y9ulg1Wo0TM5-0TCG7MJDOm9gAT3VCvh
3m00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000y1C
}

