sprite $api [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000000000000000000000000000000000000000000000000020sRkFCxU280R25tvR
KFu1ozkBR8ips2u4y0ZYfxTxmZ_73Nz8-AUa0t_-8i1bgThp_E3wCvedt4eD9wlz3nIuR-kr_WSg35ptvvEL_YTAt3hq0l-2FK_ElCi__EUaZ1yM-1ViUNBZ
BVuFdf976J_iy0zFIihueT-_Ui_p0zVxT-zvVjzs__8zpyzRxj--v_brk_qltxDXt6h_o_UisBRPVw2hBwqM-nViMR1iht_1dWt3lZx_S33H_qafsBDYrrR_
WZqxPdrT_k5mSj9VVp-OE52urzzF9WuKxlKF5oJwFo45UzPiskXVlgV--eTBaaB_mOe-f5xihx_-FgBkyw_UKt_zNxWeB_t-3oxAe-qALUVVkgV--kklVxWg
QVDlwrVLLt_zzTTVV_trrrz__VNNNt_z2_mdpk_qyGlwZkRDdoN_S5Br_lg7lVxw1_Rwwn_s-kiVsEklVzZhhtzWhx_-OQ-__e6z_lg7nVxwmrv__SDYV_t3
Nd_z0tlzzGzx_VKFtEUl_-D9_c6ll_w1lVxwXyN--iDUV_t3Od_zmrv__GDx_VKFU_tr3-prrp_izTS_iDTV_x3NN__0Nd_zms9__SDUV_q3U_tr3ulzzOTJ
_lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhpzb_lhhhx_--kkll_xwww-__lhhhx_--kkll_xwww-__lhhhx_--kkll_v_-FTKdFR_LTNHllgd
np_Z_lg76lymxgy_FVwC--kV7l-C--iVUlmPzzUV7l-C--kV8d-c_VKFFVvXAD7_I-Zndx_wwvyY_qpxwnzw_CEql_uK-JEM5_q_9Jt-yrT__KEHFzF--bFa
d-co-gV97_s7_KEF_tnP_Udnd-VNFqt-p2NwV-8lyizqLVrfyf-kgd-Q_3FSLF_Gv3zTL7-Q_AF_i7-g_8TxwX-Q_3DSKt-Q_3DSK_zK-G-tr3yq-MUufFvK
-Gztr3zL_fcjg7-eyXzkg3zL_fajg7zw_EVvzGzL_iFrzAVAFxFjz4-N_smv_KELVsQxwK-N_smp_TFbdz4FU-eVklndQ-bFbtz6h_pwfyi_evtq3rt-iutq
fyi_etNqJvd_Q1VzGvT_HX_owN_W-4VtUTSUVHG0008107hQlx4X7BUW0l7__ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt__
_ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vlt___ltxz-_Vl_-LZFzx_Fltxz-_V__-_Vltxz-_V__-_Vltxz-_
V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-_V__-_Vltxny0000000000000
00000000000000000000000000000000000000000000000000000000000000000000000s
}

