sprite $service_discovery [512x512/16z] {
xTr7kkKe383H2PQOzVvNspbNkW6k0Pqph_WBHpw_dyO20000000000000000000000000028um006OFbBeXx0G000000000001bRoxSGsm0000000000Ceh9
Vo6M0705P9I78G1QV0m006uB0G20jeXu4G201wVOwBqV080hoW000020Z9UGPpXjqER_y_7j22z3qYgxzXU70S3jvQWB502WFI6MHRge6iDp_tS0G7z078li
FvIn1tAL_laSRUxxVzpsyE_URuZQftzozzC_-gE_dOvpBW3EthJ2QfT_w4zxWVxirn_zqH_t_-XFUvN-tF7-3_j_q1_xF_6T_UM-Zm800EJZ8gCmtpdjFLRM
rdJKOwAOZ7M_CFlnvy0PKv5FAVqY06-2z3S1yfi0_NlFZ4BeNyewC-1dtlURxFs3OUH_LvIcVuiroUy0eB_FPLl-iyMXB7y70ClV-jVV0CYlVwwgtwp5ZUYt
2_GlINud0Frxt8LUjJ_wqzSGwB-PbF-U_ha6ozy9GFuz-wC_NN_z3O3y2mZqBqb-_VNFg4l-NyMde3-zU7_oLyNRaLaaFXbVbyNha-eRWChrxIhAAVctsKz3
Mlq6G7u3K3M_7SLpJjO3Vay00E1wGErlthjVppc_wIPiuPdpcsx20I3d_ARelm7zumM3-xkkdFViUqgftE7qZ_xa7Vqple3-w8_-w8_-w8_-j4T4UFxJuYdS
y_m_yFxdNdZ_Ix-dVuyLa7Vj_yh0_i-j0G20ZufC-Vu7xM4nGuyzj9Y06G_ioBXHFgF_gkp_W9_-MlkH7Gy-isslYDNXeRt-Dqy0-RGvMmGozxsY9b_G_o-p
UZaxXFuwlbmZnNeyhUeRYIUq1SW_LhmF_P4V_Ud5-gC_ygC_VI-1_WUxFgplvOfHiFpfX_L7V-It1K3_jWpv1maiVon_z4T-z2z0VlqjVop_4l83-cuoiFpH
7_cdq3-N5GEHlog-DCaSiFnZ1jfermCZyBnFxM9kCP-3GCMrJvvzsYSVd831Yt-RYt_IwZS0XLSaMNlrS-Bgfvtm74EC9z2M5Oy2oFVC-UEE_Dm_6EO3Rlrp
QVi_1SfO7_gxcvrp0ZZvYGbPS_cZF_gpnEaV_T4V_T6VVDxU_JCYiFxH7yz_o6VjspzZ9An_xd__Y_qVw8_zdxGOXhQXRMynutK0GFh-muWhejnM000SzJfz
XIiX0AxueEifpiul8OyGtm000000003rtdO1001mqZsVJmFHoiZu0bb93EFViNL_87ivcryyoV-k30RcTmYGtm38Rm1o6laT0UGVIlxYYkUdU7wkslN9ulaf
df_Y-IbUdooUd-BvAPwVwlKfdf_gzIcUd-BvoUBrgPuVzSzX07ff9g1Z05xMoehT6G0JO00CW04m0VqTMLbipG2O00DW0Wo02QZvF0G3W0700D3VHVK1eFnj
8DK7WBRhP_k73G1xVhH_u02mGVof0u1h0ChV1fBn0JbAzCtuck0rrAnJ0Au1Y70DW07u5Ku1lyC0B0ItWKGlZUfRmkZ_XYC01W03W0700600C00O00m01W03
W0700EGnYDhV1oKwJW7bO00m01W0eiRbF-u2S0h00600C00O00m01e3iLG7G-ffm6GW000000000000000000000000000000Fm2
}

