sprite $cloud_ekm [512x512/16z] {
xTq7ikis38RHAHe1Kxt_rQOdIl9weK3hFsS1Tqny95rkUuq20000000000000000000000000000-YsW_nBwep_wep_wep_wep_wep_wep_wep_wep_wep_w
ep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_whw4_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-W-gr-yggx_-hqyg_P_SlwQMgV-y
tANgNw_lKFh_pmFYHsm1_I_1QzO_UTdw9ozS_-Ibwv-yUFsJbw__QndzzrUlXKh_sCDl1i67_tBedtduZS7X_rFf7tZuJI8xlr6u-o-H_UM_7FfdtVt6aPtV
FEJ_7_s3yfj8TduZoSvl9jdv3IKxlwbavpUMxFpc8lydw3-WzkbVYVtbl-Z__DlVQEH_n6oiSS7KzB_LejTgxp4S_HUkOF_fwB_uuJzmFFgldw3-DxdZeJze
FlhVD4NzjrpUw3xJVpv_sWRG_tBlAFNVBd_S1j3_ChVVz9zVsv7tXyFrlzJ0EFL_JFxB-Nv3qd_1pnhfFstgH_BUR4hw7sCZrN-Fspzu0-W_k_U6wTyhw1-T
l-jTvgJ_6lhFEgOVvkYWz1z_b1NTN_yEx--_Do_uz4d_1SS_zGBGlzVINt_zTyuVkW7qrr__NgwY--lV-czz_GS_0UWVi1Frrrz__VMVUdob__RzvyTxw3zm
_OS-0UYll_wjl_vFlepqrrz__VNNNt_zzTTVV_trrr__sck-rRVIVxFv7lex__VH__Jyx_NVHVy7sMhT2ogWF_gZF_gZ_vxqxqtxwz_wxqB_KktdgR7-dlwz
073zUmBGNt_zzJytxgz_R_D0JiqcZfthVq3Gk-vExUy9G7_zQ-ZfdvhU08w_2w2txwz_P_VNl-Ht0UZl0fZBh_y3Jrz5vxS1Mlyvym5Q_n7p1UHt0LHqVnT0
N_9-yjS6wBcjnto6tg8_DT1XDZ_p9Lh_2VCfvBS1kYVwCvz3VXkWD-jFtLZat2y_VLkKxltwS_ItgmNrr-LdFipHt-DuhKSltm7dO_xmhlwNSy7N7yZFflz6
ubJc9il-U_-3_-ow_fSrNtHVDi2dBuFwQL_hFlGKnrz_-Mq0-Mq07_pP08w_3L1QJ3YpJp_X-GdFJtX-mlCJdf_m_8JdfxBpa_wf7-6dd_3wXESdFJ_XF-r1
-k4dF3_fzGclJ_d4pmw8FloadttIppwLNf_q-fJuja1uVE9VyEFaSuR7Pw8_-gC_-gC_-gC_-gC_-gC_-gF_FFtH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH
7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tfTVRlpt5_V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7
V_H7V_Hdb_xu-s_eZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeJ_yS-kkF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF
_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYFl_zsA_tH7_tH7_tH7_tH7_tH7_tH7_tH7_q10000000000000000000000000000VWK
}

