sprite $apigee_sense [512x512/16z] {
xTq7qkCw3WR0hTySW1Nt_gTzEIS7IGn2zmKcV018qRJy_rS0000000000000000000000000003qKW1eVOAs2B9FaKkWtne0002G_L800000aBFGfm9eSz17
0W00W1oFNWZWvZS0hOy300000000a6UWRmG0btm05xmXA_FG1_4YibS3G5P-3g3V5G1aJPP-mFCdn20E_EDZk-q2xVm032dXAm7XtxS4S400m0u_FWhO2m80
01u5ieZe_uXMmsqRfLyBsFKg8n1zDC3ARnSWVWM0GjSL41ThVK4cOepJLq8CPmlm1zkbRmBe_hjyIO3TtcnY-f_hctVPVyu0c57vv8bYbhG2t683u2J81Z0_
qboDdg_jztv3q_zCCLFdFlbx37X3yy9Tvm3oZuu2gBS5bBy987y5iC3CYz85W08OhLa0F0NUFNyNWcm0Jre1o2l5I0eW3G2t0QhcRm-OfVA_z4YqxKZ__nlj
FycpLWqh00Q0rnwKBm3Avq_v0g1w0L0zVx9u0N39IM3V1rSE0783rGk0qlcZ0Fm8RfmgVQDXD-TU2lLJ7liftZ-icNyEf03Ml0mg_J5osGLWJFmKtm5GDF_i
vr80li-h07Q4_8zhEojU0AoQ_pPFVZd9r-CSMmu07gSfDG3a_q41tES_Llu31i1UvF-edB_y5O02g9s__9lyFvBpF5vroZdWQay0FCvb01oZ0DBu7ye0qFzd
gfs__DC2yAQSwb5x032u00ey0Sg_PF_BNm78N_uAO9VyaJ-FiWM0_6cFyzqzVmFWwpyTEmBges01u641a7_xWVmxyZ-14jWvVweF0EH_Y0hO_GI0uXi0v3-7
0kXBO5R-sPT0yGM0ulbJEt-ARm0fd3_oft3-o1_vdyW0S00e__PCnmA0_94_yaV-wv5_-tVo_vp-9pxo6Ej__-vO_iG61Q3_Bo5_v5-N_95_OVAdxPp_ySz_
gTl_VNloptlaBt_7_pQ0jdyZoH_vboP_Odu1VCd_Eld4jFoz0TG287yBWFS_oT_oB_y5nx_yyp_S8dysU0Bm_kS3yfdur2twdstpZwdvop-q_xRaFvm2-Feo
_Ws0nV8djYo069A_4u3yBmS6kjz_DW1s7__oZzhZN_uX_miO0Es_nJ7P1p00zcX_OhS2Y0toLm0ryfT_R1u_6SSibNy-rOl9fsAd0eYp-vyuQgVyixz90UHJ
MxS_iSq4o2lo9uxRfFrR_pjYamA8IzgVZ1DyFGxuUaKyaHy-_H6nmmY8YyO_SP8LupV-yxbOlmBYklo9MBq2MfduS_C2YFtQdunJZOy_xVul7W3vdW7nJs__
l4G_NNj1NE39i_xBulByYGsKQFzC1N25Zlptq6eNWFPF1J0yVyH_N_cAU4KED3P_jFzhSeWryvT_3bIt07BD-7Cu4s2L_7EQFagBhRINz3i80s10-rCyVkwq
yVETFnEWVoONfm1C_wjgEZPmNP-W_T-X0F84SOdi8vW0tmvQhFqfFlqfdZ_5uwTu_1JFd-Bn-x90nc867v1JgVlRdgxzRAluzATu_1IFdnOBQE_ef-9sxKzx
I_NuAHu_rUFdnl7dxXJ0W1jVtBJzs_vKmFlnan-8GHPT1j7zAyfn4o3l4p_j8xdMv3VyBGCsSwE_wbmzVfsSSQev1s3a0VjtlnMWvo7YFy8TeNPKNm3pF_8X
-sHXzYF-dx5o_74_6eBqJ_qCKEJAKxkpVaJf6w-0xWUCjmsPa3Zo8NfTGFhd74Rr3ItLFzMcJUR1__ZK92hglo1hSeYnAIsa-q-nwLPmnSfL063TCW5s-hi6
ctHLgzVzzW2GVNEWns3uVWJ7-G3O1KB-EufVzQAN1PZzz2q0ZW80000F0j1EGA-DrYy400208q70YH0000103aSlZUpJ0RG9wAV2Pu000000002G4z7h0S3o
JoyACFxfDQ7zCG38FXa0O1C00000000000000000000000000000tmC
}

