sprite $document_ai [512x512/16z] {
xTq7ZeH648PH1JHTYdN_qphRxRmBMbPC_U-x0RpgXabC3qcI94cI94cI94cI94cI94cI94cI94cI94cI94cI94cI9DLpwkzDgtPX_Zfgnz-spvy-VvTz_XO_
VukVlyNF7pz__Fpny_U6trluB-FqhzLy_sLFkS0_nF-zBoluwxRZQzLi_-NMydzRi_thmmxBVwn_VIhyG_thWmp0Qx9_VJhBVw1_dGZ_EF_eTvZvrydmZ_8_
Ada0-DU7UH_WcEjV5-gqYl_80U1Vby8_nF-ev07WN_pvfmu0_xeSVlu3ufyx0FphHFpvy-VFdpz__gi3ucy3uCz_m3dXpvy_V_xy-VFdpp-Jdpz__lpvhsX_
_isVVoO_V_xyswU__7ENF__cpp-Ndt_NXLxH_lnxJFmxcvz_Px_sux-Ybp__Nhdy_3t_bN-lQ7x-lIBv-U-ozVbt9Z__NQO-_rscFlzTfZx_7Nx-_Fdpvy-V
Ft_-TyQVFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy__w9Zuh-Zbpx_uy-VFdpz__lpvyq-9V_7_7l-w9yl_m_Zpvy-Vlyi_V_xyyVFdpx-I_VbNi3__2kRdNvNgpx_-fwC7nFyxvscDsK7uh-XxIFvzhXfr
6y5_VU5vwhUB_zUUfNvU_E_dtqtrvxz6V46E_tN-QGF0_vvZwQV6__hgdp00_A_pZna0_lSVoUg7nxzlFP1-NlolyyyQ0FxTT_k_-g7nFowSco4R0F_LfwiP
0y3_rLUgT_VdlsuuDKzu3SZ__kfokVxy-VElz_VdlwBz-HT__lpvy-T_jZ7-_Fdpvy-VVr3y-L-8Ft_-_5UAFt_l__3dpvy_V_u6W3__JlJdpzy0yEVV_4Tq
vFhpz_jF_isV_uay_y407Ad-RW4z_yS6qFndDPAVl-U_ydU6-7_HAVByTmFGmVucu6Z-WriNJawAloqW-UxM17J7-Xk0w5Ut_9i_V_xy-VFdpvy_V_xu-K-9
Ft_-_1V_w8h_W6p__2r_p_yz4t_-bUpFVmtWvs_vyxzK1Vlphm7y_2-tWltvhnh6p__2aGJwyryrd9__zKFe1yJVZxtvrmqDyEUFdpz-_lpvu-UFdpz-_lZv
Z_bhN_uMFt-Bdpzz_lJvk_3pXyyVFd_NVFvMFVy9wlp5N_p5N_p5N_p5N_p5N_plYB_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_u
Yx_uYx_uYx_uYx_uYx_uYx_uYx_uYxyy_rVynL_ynL_ynV-zuo_-uY_-uY_-feg_pOM_6U1l1FWR0VucWBy1u6y2-1i0_WQ0lm7WRm3uVxfNZuc_3O2_0U3F
dxy1uFzn_Fcl07_V_mlT0FZlLgG__zqhSW3uxxBz-NUsF_yZPW3usm3u_xFX_lpvy-VFtm1u_Yj__lpvy-VFdpz__WV_dH_4yUT_zBJukm7Wpvy_V_xy-VFd
pvz_LQm__wF-gsEyF_zruOU0_7DE1F_8nRzRuVxkWiBztGJnZ-JVyO_atqNxuw-AziTVnNzIA_gfiFphVFmZ-NVy-VEFuz_nvyy_Zd_7_ztZpt_LvVZ773j_
_lpvytVvt_5_-ue_V_xy-VFd__puy-VFdpz__lpvy-VFdpz_x__pz_aVV_ud2_Ndpx_ny-VFto_08ltz_eS__nNit_Yxa_rNdM_rbFYtvTyTw-_vJ_oFEjVH
yqhsxyoBFt_F_zn5-dl-xoxQlrVaviz_vnyGilqxb7yNxj_7qr_t6O2-jyWh_-v8zT-j9-lR0Fpzwxqj_h-srtrMHxY_mlqLxgzqVuNxAzrVwVvAzzTAznT_
hR7-aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9Fm8
}

