sprite $security_health_advisor [512x512/16z] {
xC5B0G1G102mzy5L_xQ2sDQx0G00000000000000000000000000000000000000001LzV-mTsVRaPne54QrfAY0Ezx_RRjPAzsZbHQL9Y7Yx7FhsVlZhr7I
PmiT_UxVrp97l_ld5a2_-wSM0F_X7vi0_UwVMm3zxfzQ0Fo7Vsm2zBj_RW7qktzg0V0V_h49qE_-kGNGx_uP1T0Vz-_xQ3SO_07_d2D0l_ld5a2_-uSL07_S
l-zejnlzXt_e4Q3V_LCBWF_mZqs0VlVFBO1-zmyeWFw0Vy2F1k0_ySyv0lIxVsu1zBj_QW7m7_wn2T3l_ha5qE_-0GN0d-k_qmSHqn_t3pq2zBj_QW7q7_wP
2S1_-ESMGB_x1nH0Vy0_u4S3y9_uvnm1-jq_jm3wtJ-r0FWF_zW4w7V_t0BeT__K0kW__3CJWF_mpos0VlSFA83-0l_DVzCu_BxMEape4Q3Vbra0_TBw5XJm
0NgNfz-NVWJeAu1-t-Vz2w3VdkuhwCU3dhvl1kWhmE6NWAUl0FftB81-QGDRz-F1J_XpdxuZG5y1z1NWntiIyFHlMm3_Dc77DVpvjsdRtvz_cxgz_VctwTlM
dtzfRzd7Zlxysnktcp__zkRjvC-_BTYnXp__jcph_VctfLlhpxyjtp9__csJhV3dtpRQk_tvjytsHd_-fUsuz_ZpRzjklZ__jlNc-lDls-zpbZ__Tf7n_xC5
w3yfW7-0_a01_8VnGnBWFww_Vm7yu_JxFb_nvr_QzVUx_lpRJSQ_xmNzk0BujxkDVvZ-ym3uy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__hLc-_C_Sltvrtykrfz_vS-_Xlhphyd-_EiVI_Fdpvz__VVo_FbN_lp_M9e__vhipx_K_rwMF_-QxC-__j-2_FcNQ7_-zKyMuy-_
9llpB_LF5-BFloRxyw_VBS6VV-NF_yztVt_-DTcVVwdFTdT__ZNPdt_zYztQd_yHxS-__kLkxC-_9llpF-eFTbj__ZNPdt_zsVZplz_urneS0F_Adtzg0Fnh
iZ__EhA28C0_vm3mhpKu0FwLF__K0FZNP7_-pvXl4W1__lp7-Tjz0k0_pf_jp_z60V0Vvx-JF_zn_fi4m9y__t7-smN0Vvn_ldyTNldr7pkUxjTB_xhyvmTG
wjQxbVyu_tp_LR3yoq__gu-9ln7eM63AV-3vJpu02qZv3_0F782zdp__SVxv1s13SVuZtrNOtf__EF_S0x2Ud_zPlztOdr_sz-S__lp73y3-_Fp7-SSFmFx-
_4lzTiUmrUNu-TVlDuvLDlRdFym_hdKjVlv77NxBpx_HsDUV__Zp7_VQbv__-2_xZH-0yqB-_EktEtzNR5z-_kFNV_m0b7tz-O_pZvjTdvz_QUqj1u3_zl-b
ym_0Ix_uUFny9_yVxhL_ysEE__hF_vlYNrvrcy_FV_stS-Nr0y3_4lpZSlFvn_q_e_tvjv-C_noxyRy5_-Ny-_j_BV3dFw2tzFdp7-TFzkVVseG0vl7pvyz_
0V-0u3H-_Wlu-VCVC9p6ptyz_th_B_wJ-USfUlxy-L-8Vznn2Z__nVpy-RykMVuUVlvbP0DKa_thrVnjt78YFt_-L-KNG1dcluK_V-TV0EFyE_iRVrln6KGl
mC_VynV0wkVFd__g2M2Sdp__6_0BmFFdpry0VoF_HxG__w_B-0kW3F3VzVmx0Fm5KB_R4Nt--JV-h-mSMLdsFO0oyFnddN_-vu834F7y-JyNhj-jBFGNm7h_
5d3-7O0I_FpvBtZ-A_m5CBnpcF-2_lmZdZ__jiIV_sKFG4i-_mv0YNx-3a0RtSVU_lpRWkVFlrtJlwMUVmV0y-VVRkWlWCCF_Xo0nS-V__u7eBJH7PVmTm2o
dxy3KFY_VsKV_xQ0Vz3V0IXh3q2vx_Ft3K3BVlw-1tYkz__alp00pvy_Vm64ylCl_1s01Vpy1tOiE02U_xpzsla0UFxpTsuKG8b-_lnRnFCNm7p_uoRy3e3d
xti0u_mtyNS0F7y7O38__vq2yFpvU_u2mC-Vlm2svET_yfyy1m2_0p3CVmD_1y3pTm0yVm54ylFdBu3z-VcVU_b_tiRV0NZxyxUosm4OvR-Hlsy1Sla5m9z_
mo-01VpyhnZ0iSnV0CNpTm0My-Vu2m2_05xdFr0F-EySm4VgytS0N7y7u6i7Vm7W5q0mF_zp2N-qlm0suXT0kGZ_9-051y3r5m1-0QpcF-3EypyNy8SzVm7W
5y3NflxyJ_m2m2-0L7x-vsJ-F7y1u1S0VW5qoFr_sOV_EOa_v_aBO3s_dNiKW5y0nmly7o1_SsMN03hZjPw_0t26ymkWPFCBu9oWdyKlWAyB-_C_IpQ_0Cu5
-Zln2-34Bu05-jlm2-0CvnT0cQc__q_x2k0SrD_f-Tjnlh60hnloEm1znu3-xVW5q3UWVqT-0Pnb0Fzs_0Be-_NaApW5y0kWxycxJ-0NG5_tokKNG3Q_0BBv
1P3DBu1iVW5aymiWcry0sVm2oEONm2NvhKpm3-Ht0hBv1P2jBu1iVW5ScDz-BVLVps_h_Gy8LmuW-_4B89jV0Ddy2iZM5q0slmAolzylWEp7Bu1iVWLaw_ia
0TdyJa2slWAoFwkF0B8VlmAozHMGhQ-0R7q5PEih85jV0Tdw2iZMbq0slWIozIMG_HMx9P3zy3MGRIy2z6R_Q0yE10000020_5yRGLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLK
}

