sprite $google_cloud_marketplace [512x512/16z] {
xD9B0K0X082mw_jg_xOMC86C2cDkqtFVinp-z03uqmFWDm3-wW3u3O3V0FY30-0t07u3u3S0VWFWpmo0tm3u3O3V0FWDWDy0-0s0Fp00VWFWDm1-0-0t07u3
u3S0VWFWDm1-0-0t0Fv31i1l0Fm6m6y0_0R0Rm3y1i1l0Fm6m6y0_0R0Rm3y1i1l0Fm6m6y0_0R0Rm3y1i1l0Fm6mB_OkPCRYM4WXgBdrulo3tToy1GQAf3E
mF_HoqdiJsNoIkEd_W0WZP_w0q0SF_K7W3X-wW-0F7xg3u0yVkeFG20_zGSWa9_w0qZaf_u04lcfFq0aF_K7l2FvgJyWav_w0oUJd_e3eVpK7wJoKt-Goa_z
8PQV-aCiF_L7BZ_rHou_zIUOd_eJp4_z9VDJ_rSoF_7-elc9znVDJ_sZ-KdtbyrF_QFv2VS_uVna-qldf_xH_4JxY-Sdsh_y9FihFz7-vIVON_aHxLz-SlrV
vOTOV-K7iVxA3wBzoq-gl_83qVxb9zHV-G7H_kKdq_-CyNS0lFVDfVnZALQUi5d-gHQ0hI-0yZDJVwb_-HcAltC0vMUe_MkbV_cPIdys3g3yZ8NVw5z-vi8l
743v6So-px_yJ6PVDu3oCnfzct_v6Ot-K__p__ijFuFyMFO2A3_3oI_tVvN_kTX0uTjU0ELd-elxllhOrV5rxR_6Ywnw0NG0yptSwtywW6TMNBU06_vt_jYv
ZmEvOIY0eSVDHF_LEj-SxPK4Ve4D33qF_9FeZVzdo-fV02Uz7teU5K3yVx-Msxy03duYO780yS_t9txLyVS74B_VNn10_0KWuCzV443y1U3ZpzyVGFoi0Z1-
05h3RWB7_tSBgty169zU_m0W_W7-1S1VhINWjmm0-XyVKdzR0F7F703CuSz_sGA8tpy0cCoVlp-0-0l0_O6NuVx4B_0l0EcdNURx4_y5_WKGlyMV0VnM_mA8
t-_F0FvP_aiSGFp-0U0FGFybrxBv5m22upzr032L7mU_VzVnc_mvVzSYw_XvAe3hljryXXiE0EB_jjZLVyqC08k_Vm1u0uZVxu-It-5V0F7FzsSEFpR-0l3p
vyyG_kNZBm3_5zhaJ_m5i2r__aC2Y9zrum2ksFyZD00S0T3nl_Oh30d_HPV-6W1Spj_nXyTR1c0Ocmq01l0Fy9S5uET_4V3F603ioCzJ_aiGGFo-0U0F09L_
_iH_sYe0TFxv4_yfgm2SdvVpPm2_rRy0_Fpv8-2t-XV0VFxy4V0B_0j0pFyiu1Vw-mEuT8ClRB3Mv03OOlet03Y1lqj_FrulOmDWc-FV0C3BlsRpypGp0BOw
_Wq0uj_9Vxa3O3l_1W3tviyV0V_-V-Yp0DZq-EUFW7_lhtuAW8sFV_wO-DTk_0N0viS_VpJyBvln5y05-yXViPdu2u0X_laJ_zbhxHu0W_mR0CGlylS7CEtf
Q00WuC_V6i1y_WO0_ije-IyENFVcRm2WlucM_uLRYhy06EsVF_4Nm0vtq5R-fs-AEn__0k28jMpy-IEuVsZpBm0EMSz2_lmHN3uK-1V0JVdpvvm7p7zf0xWr
VmC0mRN3_0K1t9I_0S313xNY1tXo1y1jZty3W2CVvr7Cx_TVK_xP-VEnlVj8ZXm60Y1uPMCYEF__xUAqtZi9ggmNT2WRiY1rniV1RtxvUzMN1V3Pd_zB-L-7
Gri0nv__txdqPm4SV_xuBG1__lWj07_--5q4u-yJ07xtGFZx183_cAxZFp0k_Va4uFYx28RV9m3-_F5R0FxyyLk0t_T_7A_At_6t07VrqXz_nzy2NFX_tLzF
2u2VFtyBWB_bhyNVyQykWEwc_sDYEVu-0U3dpzy2uD-j2SJV9m3yFW7mzma0Ftx-_F7ZnyyVVoFy-Fdpnu-VFt_y-1_yq-6lXf__mfyEFtx-RlmdMuv_EloD
yEFdZny_VlxuyUE_q_fAy-jAwmi_VlhywUEdpny-_WY-tE_3tpX4mY_-mY_-Mcb-PI_AosT_LVdb-Ei-bb-El_2Bl_2Bl_3Bhtxa-Clnb-Cl_E8l_E8l_2hn
o_6Nuo-tlkJuA_lWl1n_pUzqFTz8Slpv9v_tbEEl9h_uYx-I_E8ld_zryNVyBG1_6y3_3rBON_pv1nP0_CLV_CLV_CLV_FcVsOY_-8j_9_uMW3z__lTau-yJ
0FyrBnv_dm3uy-Tl0VZpvsy1-FFdRm7uMm3-_FbR0FuMWBy5u6y1-5i0_XQ0lmNWRm7uMm3-5e2_3U1l0VZR0FusWByDu6y3-5i1_bQ0loNWBqcI94cI94cI
94cI94dIcY-ApA_vTj7vwN-eFhyhuVNvFH1Gdz_Z8EdvyU_AyzFVfUV7lolFZtzNdX__hZm__LrvVloxylpuT-tv-KzvVloxylpuT-dvySzb_YDRyvUAp-y5
SENvyU_CVrpt_CNYytlzPtf-_DEUd_-O_wYk-Sl5v_Vox-py_FdZd_lm-OV_drMSt-z-FbIUt_7V9UVdpvy_V_pJdPy_V_vp_Fpy-VFdpvy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy__-xy_FbR0FFpDpz_ytl-o_oU_wpCpz_ptnR0_FpDx_rFvlV-jzhy_DlpMm3pU_-p-Rt_lJY_1J2___zYVl__gJY_1KZFRm7I
yrk0zFpyq_DRWFJy5Y0zlmr8psy1qlDRWFBy5Y0zlmqepsy1olFRWFByDg0ylnK8psy3klEx6cJ-t-uT
}

