sprite $certificate_manager [512x512/16z] {
xDAX0G0W3C0mExV_lqNZKJHveTrt000000000000000000000000000000000000000000000020ITaSyIqW_csPk7f-ulMfrwUUdtXzulc9vwUUdtX-slc9
voUUdtX-ulc9zoUS7_q9vqT_slc9voVS7_s9vaT_z2UQ7_tH7_b_ep-7lJl74HpBeIZgFe_xtssRyhe69WlnufzhYuI0ytDEIVp5N_p5N_p5__Vd04JynT__
V-NFd_zB_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-UVXF_LtJJuV_6_k9C2_o_-9tTHuv-4_yajrFWd_4yUGAhnJ_YVF7vMuv_m
FtduiCO_uN_ow6cDV_ZVF7ZSuX_-5_n9Yt_uN_0dAV4F_mlz92N-2VyB_gJ5F_ml-9D2V_xvWvNuX_y9VrBY7_ud_4c9V_YVy2Sb_k5_mf_K-FFFIHt-uP-Z
AlpvvwmA_xpjppzl--Um7-_FFwTL-ETHV_xySzoFzkUVynhyyw8_V_x9VJ_Tdp__rFlVyoy6s_tv_yLiep___DsMumN-uVylzZVxyrziN-oeykU_M5BWpt-z
ky2V_mvklwVId_zYKOi___tY0d_-bsZvowhy-VFdlrZMuy-VF__zrZ9__lbl_LFWpt-nz5r__lpvps_ovp_y-VFdpvy_V_xy-PzixFVdpvz_Yltv-_MVFt_-
_Fdpvn_-_1Vx-FFdpv-____9d_yq-VFt___vv_Vvy_Vy7t_FV_Ft_WV-tl_2Vxyx1VxylV-Dl_S_yb_WBJOK-_DFDlFz_loJvNI_l-y_B2RB_Vb_VJDT_lnz
_uS_V_w-_yVVzr_vy-Vl-z_yvvJ_H_lpvyz_3laB_FdF6N-5F_yvuY_nvpzl-_EV2_wN_VbFaJ__EU0lyEV_TS3_W3__urlYpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-S_B_lndvbr__j-53_hp_wvyq9__T-c3_lndlfxp
vx-ukD-V_-BgVd_-Yylx_Valhk_tvxyOwFVdlvZez-U_6Edtvx-OwVVdlnZgz-U_cAhtvx-Ow_VdlnZiz-U_cEptvxyOxVVdlvZjz-U_6Extvx-OxlVdlnZl
z-U_cE_tvxzOqE_FVx6Xtv__OaM_F_zPLE_FVrQL-_EVPTN-_6TVhJ__WqKz_lpd3rNfpt_-M0N-_0lYpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_vzyUVFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFN_p57_y3_k8l_k8l_kBV7__TlOi_VlwR-FFdtty0yFFlZpz__XFnrmAlst_0yjV2hjn_iWW__-xu
JnRXvzyT_uaMSFt-0tZXLk3l0F1V7G3y_F7l_PiF0FwzV_C1mB_tRpu0-FV-rGS0_zw_-0JWt_jt7G3wh_bFll3N-kzFWDvzYLOIFVqIjT1_sd_eUuaY_7B_
VUmF_Fi2_u2_dl0NV_4NV_4NV_4NV_4NV_4NV_4NV_4NV_4NV_4N_to9l_YB_oFnduY_-8k_-8k_-3yGVWU0l_W_6du7WB_u5uIVF___jKl70W000023_Aqd
iRCOkW200000000000000000000000000000000000000000000000000000000000000004
}

