sprite $assured_workloads [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000002OlVjASYD6eYZQmKGLvw_slzhnHku5AKoK6kWyxrl-t8IyTENLSLvjHx_gEC--1U2lu-mQ
0Fx_-f_7rMxql_7l-0JW_zR_V5wDHlzR_xPF0FuwpcO1sAZWtw40gmh-BGB07_nx540_-FSA07_sFyVLOFI3VwSd07yTPui0x579lq41LfNyMmI0F_itA81-
zkyG0Fxito80F_3B_WqASFmJ_li7O1yruT-W0CSV_1i4W3_ufpsl_KS_-pTu0l17_nO1qC_-3Gh0d_rR180_-pSeW7xsRn40_kpVe03wsRz30FYpVui0w6V_
1WNWp_uj0i2V_HiKG3_xDmq0V_Ply7k2z8D_WoS0V_3VCW0RTQ___WKu_kpV8W3ysRz10VIpVuC0yD_dVmuAM-Xd_vvF0Fxiltu0zgWR_1iKuFY3VuC0y0V_
1WNG3_uD0i2V_Li4u0T-sRzL0Ou_-wyVW7tK3VuD2d3yoRzB0FZd_VV_es7qit-39m1_z6yH0Ftitw00_Dc_HG3uit-30kXd_nO1uC_-3GgWd_qx180_-_SD
W7xLEC-M1U2_lbct0F1VFwvZ0VI_NPC0y5zXvtrxybn5VrpVp1FW-5SBmCOVu_V3G3_m4m3-1hyMG7_2lrS0-EyFO32-Mp_phn30YJdoD_1F0TXZ4VxhEbSg
mF6lxxz-0FWVrsm0-nT0l-fQm3y4WB-1Vmh07jN0FnLWzKVsk1e4u1zqYBjMz5T0LM__4tzl__D9luL_Ncz-_YVz7lvv-6_Vqlud_Xw__fFNMv__YR-7Vnxz
6pVMzp_nj_Zp7tazzFdduRzjdyqlWEB_nkZVjBNuy_1_OW3Z_FmzwN-Q_xd4yD-oJ-4NmAXLzWdy2gY5jXn_7luxjXv_7ltD__qt0TI22_mhRj2_Oq5_nU6_
PtVZ2-1Hgs_SHw-0sc77kSDwyFFFwwtF_yI_Yxy07jNONm5LZVq5KFnNBO0_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xynrjxNt6CsKznyF_p-ykRc_pqyjR-0cvbo9y_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd_spWpj_jy-zu-_ppnlNkgexp_5B-_A_VqF-d
_-O5y9_N_wV_nWNmdzV_nd_d0lZFwt_hVvux-_D_Jk1_uxzP0VpdzOF_jWdmloRqW_yM1V2VrG_-cnN0Vqu_-EzQ0F_tzHzLoN_J0lW_htStgg9_sbYNc__K
3_cp_swF0FzhGZ_uxrS0_tdzxBz-0VpdzRF_vWNmp_YJ_kiNm7zUF_ldZQty-LTD-kTjuy-_Qi9_nmBuP_rv_xpL_Vb_LCtwhry0__dJp_xR5y0_wy_xvpqN
zETVDU-_-oF0lshQV_i2-5VTvBz-0Vn7rKt-wnV0FxXE-EzN0F-gk_pNJu1_rMt-wnV0lwhuy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lol5lxyisnVV_xZ-lkw-lD_NlzS2t_-sRM5F__CsiAVVrPjuSy_e_RovtzSFwo1F_zCUdJovn-klu4__y3_nVtvPyzd1t_--VeR
-FEFrz_0dt_476S3V_xHycpWpp_pD_3dd_aR-FFF_0ty-MV-1lxyCty3V_wPlu4__ypVmPz_v6_Xpp_nz_3d7_Zx-FC_4l_-_lnVVB1ZWdyVV_uVrtKzAk_8
_Flxyt-y-Xz2Zy2_lZ__ZzVyBqiP7u5_7N_-wPlv5Vzu_I4VWNyX_tgzSRorKUzklBVwUUEyOPF--ODc_lNyHosxjVrVVzYH-FVtv__61qxy-_lppnywF_uB
-_C_WkXi06D5Vlvv0NGsWCI_lZ__-G0o_tx-_AS3oFpx-_FF0Kpmx-VFFmSG-BVqvpyHmCty_DSFuFfXnzVrvr_NgvtdzlxyvmCO-_lpdm_WE6xYvtz_08-9
00B_Xlxyh_e_0nZ7kRi___a0FewpWJ__543TT_xyrm-W6lZpZm5K0t_-CO0A_ZVmyrylW6hWppy6K0ty-SS0AlWlnv_z-Sy7K9lvyyyFm4G0zMNy-N_yVW0L
_1VXvv_tZ0_0-m7Kjlxyp-0_kMCH_db__bSZV_xdAlxN8lxyhqR-_CSQ_YDmyT_f0PZtlpvfjeJ_yrfezYVzdJ__SIqrc_Pt_lptvxVU_ZRc_DloUm3u2-30
pxyblm3u2-30pxyblm3u2-3uKlpscF3lo-y1-5ixTr4OGG00GJ3Kx_NlDXQEQQeiz1miDdtPpm2Q_lWRGDFv3Q3f_Fu3DftV5q3J-GsWwR_-1j3qnzy0-ipy
tBP_nqSoWARp6q3J-GsWwTz-0sYwlW4qdTz38KtdznNGT7u3Q3g_0JHTtmAQpcy0BUJdw-p-nm9V0Ktdju2cwpiPr7HzNm5DlzZH0fg-oyy2clxczp-WwVg-
19gkRm9DnpU1tZ8-0000000000000000000000000000003m3m
}

