sprite $cloud_gpu [512x512/16z] {
xTt9UTjg343H3J_zsA7_Rby3RqueKxhd5f10Fh0rSTWlJv8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aITByz-x-3-v_0E8l_kBVYx_uYx_uz-8l_k8l
_htuYx_uYtyl_k8l_kBVYx_uYx_uz-8l_k8l_htuYx_uYtyl_k8l_kBVYx_uYx_uz-8l_k8l_htuYx_uYtyl_k8l_kYxiLSUNtbyrVLLrrUSNtLznVbLrrUS
Nt5-nVaLvrUSNt5-nVd5dt-ONt5-yUSVvbUSN_pvX_d5_wFZV-ONqcd_-ei__p2_klxYhpY_clxYB_vgV_Ydq_xrLzDV_CLVCFzZUh2_-8k_-8k_-8k_-8k_
-EyNrl2d_zUTiZ_-NVwkVztrnx_RzEVFdpz__XT_zx_Xpvy_V_xy-VFdpvy_V_xy-Vzqhx8__vceFt_-_AVipt_A_lodwi-VF_yf-_EViZ__gVhpvyz_olxy
f-pFVwh-_Fdpdx8__odxypzfV_vJzkS_PN_-K_RdFrL__lpvJzcV__2_iSTFVZx1V--A_vJz-K_Pd_-K_VbFrPy_V_vJzkS_PN_-K_Ndpv__bFtvJzcV_qdx
yv-oF_yf-_EViZ__a_RdFsL__bFsvpzbV_udxSz_olxyf-pFVyh-_4_Qd_-K_VbFsP__bFtvdxG__odxyv-oF_yf-_EVgZz__lodxCz_olxyf-hFdp__AVlp
dx8__rVQd_-K_VbFsP__AVlpVqtPt_M_vmly__TZu3zbV_vJzkT_qlxyf-pFVyh-_AVip_yyTDPvI_oVEkgy8_xpXWx_6_gSKPyw6V_pt47d_lW_UCwvFVvJ
zkV_w37dvlXVZvvoRex_lA73_wu-OihbVrSVmS__jZxXoP__VJr_nlFK0Vcd9-IV_WF5_vetTF5_wkJfzoVyqnzFy4z_Eid_cZTq-3zrylINa_pJnoRmpnwQ
n9y___IHoVnFxCG4_kz_5A-qF_yj-_FViZ__hVhpvyz_o_xyj-pF_wJz-M_Pd_-M_VblrPy_V_vRzkU_PN_-M_Ndpv__bltvB_zVwxFzJ_h-J_otxCz_o_xy
j-hFdp__BVlptx8__vFsvxzbV_vRzkU_PN_-9-tFVyl-_BVip_zA-_FViZ__BVlptx8__vFsvxzbV_vRzkU_LN_-_FblsP__Lltvy-U_PN_-M_RdlrL__lpv
RzcV_vRz-P-qF_yj-_FViZ__BVlpFsb__blsvxzbV_vRzUVFd_-M_VblsP__IVlptxA_wt_lVJt_-j_yj-hFdp__BVlptx8__rVQd_-M_VblsP__Lltvy-U_
PN_-M_RdVwNz-M_Fd__zyUVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF__3t-_-zdRG__-7Fd__VrVRdVwNv-SyhpSz_9i3FN_p5N_p5
N_p5N_p5N_p5NsuP0xFtZOVuYx_IXxlgf0zvq2RznL_yjHO0Vz5V_BKM03z__i6F07NIPprf-VEt0FZvyxS0-2q0VlxyBG1-2u2VFtyBWDy2uBS0-2q0VWk0
tmBWjm3uRG1z2u3V1j2t0FXj07qRGDyAmBS2y7-yOQ_RVt9F-_VHynT_yHV_Nlp5N_p5lnT_yHT_yU_5N_p5N_nxyHT_yHV_Nlp5N_p5lnT_yHT_yU_5N_p5
N_nxyHT_yHV_Nlp5N_p5lnT_yHT_yU_5N_p5N_nxyHV_BqwI94cI94cI94cI94cI94cI94cI94cI94cI94cI94dI7m
}

