sprite $pubsub [512x512/16z] {
xTrhTkEu4O3HEGSGm7_O_shpJf27naC93GcfkdS5P7q5MdItxR430000000000000000000000000010-QkH3RKyCpAW_8CL4DyAUEnR0KVV0iXl0zIt0UhR
0FajWFoH5a1z2o2_3P3V0iXl0UIFlm1K_Hr_2o2_1P3V0iYVPW6e-Zl-5a1-2w2__lAlgYCR_Jq0vBS0-killmNG7_rJajyheFvbd0tzAVhhdsa1q1_zqP-Y
l_vX5W3zqH_zqH_zqH_zqH_zqH_zqP_a-SdN7_tH7_r9df-a_T4V_KcQ7_tHdyJvqP_4-T6VtFcfkVEZl_w9yvEyFydpapm_ykkVE3_9-vCyFydpKvFd9tbz
akSdUNwovoTxVRBN9tjzajVdwkrHVl1eVSJ5zLVjKSiJzT6klnXnSVr3R-tngFKVuUlZqLg__Yf3V_sdtgyfKN_zf_tzQV-a_zr11T6UqF_cf7gm-9F-_w6t
tnMi_gJ_pK45gp_fVtDGmUfF-hTxOjMValVlxRPG-QUUkNzxHQpyqrdz3MfHRw_Ash-zAjRXdtBsRw_heV9F6VktT_HG3_yfN__sdbZ7Vpgclq4jQEyxfRz1
RRyh_TkAKFad_U-AsR_bwT_M1CYl_ugO_TiH_GrgxrtftzkocFtR2VqDQkjTwT--CYctfV-Nxqf__VLltvcKszB_YBlINt_zryNitwBtRolqrrz__VNNFrn-
_VNN_pxzzTTVV_trrrz__VNNt_lVL-Yll_xwww-__lhx_n_wwt_efFp_prx7V-c1__-V_hDo7p_g0Vlx___xcLJY_WQbl_xoVsvItS__7yQWvByhwA02FDGM
wDyT_vk23YftVlr7xlu6rUM_AUYWvByhwAVavFbDQkzIwn_pliPtbByng5_g-DDVo-yP7nKh_tJqJPK_O5Bh-gatLMxnzry_ULy7nP-23sg_qswgbbUTzgoC
-7xJpplwqr579UGRxZWo_nHyKFkTKNz1z47jz-qt_h9eV4gq-DC1BtmhllZUF5ZElsx48xy5aDy2g6y3vBS0ybi0-Is0_1P0VWiWlmMGtmBehx_y5a1-2o2_
1P2_r160_Xu0yaTQ0FINtmBehx_y5a1-_VMt0FB7NW3qHt_vKou0-gE__2aN0FtHN_w42u3-w4_HN__82u3-w8_-w8_-w8_-bBJzqP-IRW7G7_tHd-JvYTqV
_T4V_T4V_T4V_T6VcZi_IVkZF_gJDp_wKpwjZfEGuVYZF_fp7VVxd-irFeJhBqxgFwzfF_hrTDRrM_bd_wkDtRYkv_t7ru__fnu1wd_x2y2Dwzg0VlqqvmFw
xzm0hkdfrzhlvf_ws4NzwRp-qzX4_UcWl_zSRrpT0lhrn3dzhoVwsC3XNtm0x3_-qzX1_Uah_Ul21IvG_v07mD8bhbD_VG7svv_ws4N-Qtny0HOkSfNwwmkm
F__-Hu3wK_li3mFTVZMTRC2DEJxnstNBUEAWupyj32ha3-Qj7_xFBy3IXTwB7sa7NXtdrA-riNukVxtkUtjG9LZyQQ7-nnTWuJcrVgqrwWzahuxqwkEPe_9F
lorSQAopFxqtqQcEPpwIlrqlMxZAOFcdj-fFuwdjzTSljxmgLlsfpY_yomim7PP_MhYyMFcdbN5UVJntMFvfPL2Xwa_ZMb37SwVbdrOc5J5_UQoDSzy2rF5S
lLOyollYvD-_06Fzy6yu_hsM5P7oJxLV2_PSrZWf_nGk__e2Z1_i6FDA_h8iLlxr1HX_OCUC5_AlYvH_gXlox_jMIrzu-2yBat_zG-2uPyDqhpVC_6iYvP_Q
XlhJhv_imelVgW3vrnUWZnVLbQckRq0h-l-iRphyqo-UwC9dlpKXyvUwKF-zXy5OjP1_IQJyqsD3_TqMllYl2Dc_z0tvT_ljWyT_2fc_F3RKt-zphtvJ3Tc_
z1trz_lOyPz2vY-FFVNt-zJndqBsBtqX_x4Bq4h4_cM7-l_xatJz8yT_2jc_z8MpV-W6j1AnVzdZiR7-VlkF_rH3zgyB-Szy1FIoISZ-fI_KF_8Hq4BsBxiy
DjVVR-LRl_hNXK_zHsv0sIPa_z8NwX_uCQ25x5_sQGlrp_7kur__6kItfystlsr2zYzH_g1EV-ljJ_-_pcs4yCwNV_tRDSBG_mtZO0Qblq6LdFtrrz-azDTV
V_trrrz__VNNNt_zzVVzF_trrrz__VNNNt_zzTzmL_hhRm5gkDlItyz_r160_h6FlqabxczG-kil_qtwwx-1szB_cwhyDmKTb9T__Ht_Eu8EIlwRQj19vUvl
KCdpEoYv-njKylmc9VzDKG-AL_-ReXwKvCVVe7BdDwZa-KqgUNwJIfxVfBBdDwda-GqgUNw3al-c6dHGsUkRbE_vtXJsd2G__0Qb_brH1rNLlodiEKbVtw1k
VkWZxYcvUK_Kq8CI_gQwTL00jFyoSj9-wYCdyJq6r8__4A2t6qPq3hyDKDy6o6y1vBS0ybi0d_ijWDDl0UIt0F9R0FajWFojZqZqzm2GtmBehx_yyHU0hh_Z
Rm7qrr_-D0k0_kWlVy85G7_qf-ll-EklVvW5G7_qHt_qHt_qHt_qHt_qHt-IvoTdV_H7Vthk_EJjZ_uapq_Y_kYF_Fed_Wrmv3x-zDpvITwVvFd9dP-UEp_9
-vCyFydpa_pxVlJaXv_a-ScUd-prILwVdhq-wWyh83uxomC00000000000000000000000000FmP
}

