sprite $user_preferences [512x512/16z] {
xTq7ZYF13OPH1475HkBzJ-kSPSFOAIt-hkRxhl18jaPXj--J94cI94cI94cI94dI-adN3we-8FeR_aCc0F-w9Wy0_dLD7W3ywnet0FZt_Gq0_wiF3V--lmF0
_-fqugzA-LSVc_Ndpvy__vqwa_YBl_ZhdVDV7Kyhvryj_bFZVtKYyHT_yTTA-bUBl_YB_xJuNvr9_CLVhwp_rT6qilxLiSHVQzhz5t_n5t-zqlvN1zDA-rUB
_zJuNot-uY_-uXy8Vyw_MlodnlzgyHT_yHV_GFXp_jNYB_uJut-r-8k_-0UYd_M_gWF1Z_ddHu1-o3y_0QhrnQxlLTM1h7x0FtO4wEVyynD0F-UVdm3wEV_y
1D3F-USdW7xEFpy1z7F--GcW7_0t0JjMQVtl--Sde09lCcrG9VJp_fzz2JzmLdQjNYd-lFztjQxAVEAyRvNMt_VFJq1Tdnt0lpq1jVB--Gcey7TEzdUrqikV
zxzg0p_-fyM-La0_xhyFLhc_BR_lbUNF-r-rXV_PSM_H1FIJ_f_LZdx-0EoBLP8_xt_L1lvdj-JVFmAralxv2QZptbrUlrHW-GF-FqEhEk3ZXMspW7x0_zVL
wfGVdkoZfVZp_bVjhtv-0FRLGlnv_wjsL__JFy-_FmArClxv2QWw-Gi6QwCu_xhY0r3NppkL__CzWHNgoWx0LTTEbUVVByc_hkG0rBLRnVs_KQrOLwogwmkb
-K_lEhpgOFppuK_vEm0l_ZV8-aVy7O0QxMy05lzRX7_3tm7WVtgp-VbNWF_D_pwjqUlF_yB_ixghQk0JWF_EzwySW2VeFse2Yl-E_laJW7z3Fp01cGE0lxe7
3m3_xiq1y0Iev-X_vW0arp_lNuyz0FYh-ya3KFntjl_y0UZzy7UFEG0U_fu0rl-p0Iy1hRy3OFqT0Ei_uW3umK__KjUvMN_-S_dvLs_7lno0G_dvrsX__XV-
pshp-Uy0l0zV_q43iAp_b_qz0MgqloV0udzG-B_bxm3mTm3MP7y7eFWVb_NdZt_Ftm3mvxy6-bTTfrVyFpxw6JK3tVXxCry4c8Zloy3d-_Vtkchk4u3-Nwgf
1m3-oKSWoP_NTmGgoP_NDm4roxz_UwFyZt-dnmcef7z--Kt05FvNjm7uxW5umlARW0dyrMq0ldm0QlJo6u2dyFjByE7htw7gqGVWEVm6O3Q_Hq0b_VFy1W3_
R-gX1w2UnUybGCrUVmEGzC_p6m3ylwi7FW1yuiV_MUll2V0u_xvDi_tv5_yaVxwdFV-BV_00vFqR_wqFWFT_gczLFSo_hF-lzRGFWAn_y03a-Rkj_w_b2q3y
J-NV7m3-zRmV0E3_bKxctny0_kK7mFVxu9T_xtNq-di0LEzsiZ__tgzEzVS0MFsLZkHt0Ag_rGh4Fy2_Cm3ywwdytQ-p_Fdtjpk8dt_rz-F_Vpk0Fp00_0Fy
WGdWNu_Lpmy0_pn_TwruB_un_kxthTVV2u3-xTtMdtzrTt00-CVvemF0FyuVdG3-bNtofmU0VtBvPmn0yG_ovmUWxzowCgqEnF-pvFBd1u1_XZzLvVtvL-Tw
f_tvTxQeF__gT45__jNvOlxygqVxst_-Dwl6-FFdpv__E-VFV_Nal__urrX__lpvN-FyQx0_V-__yBzBzj_zv_zE-lDVFVdpV_urpVyr-lKV_su3m9y_V_v_
ZZz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-Vlzv_y-VFdpv-_V_wPVoVz-VSaV_xy-VFdpvy_
V_x5Fnl_TywV_-fyEN_-FT6VFt_-_FaNV_wtukS_OG3m6m2V_di7kCRn-mg8xtuP0Fm6O4tYzz_0uJS0-0q0VWEm0lm683i1-0q0VWFmpl4RWFoxmPNZDm3v
4x1cyXi0_0PWuGyCG7O2y1i0_0RWDPdV02pyErs9PlCRWCB_XGn0JURt25ZdyXk0mcy0y1k0k3x-xYlIcirl00g_0S1l0F0RW30__qnr4tx-eMRxyw_H_lol
U_3pJrNye_7dpvz_BFxXx3z__lnF-1Xuhh-___bx_wy6-7l_Fte0-Fi0EDyrevxipxzwyW3mlzllllZx0YZ_FBy3CFlwEm2przy0M7_-SzVV05X__dFNtm3W
vp_t-Xk0sUjl0Am_V-l_t06etkewknxlltgh6h_-tQFzyNVp7tlz-Ll_xhd-rf__oUjl05xuzwkX1w1S_xysrD_w_pt-uzRV0QY9w-y0M7y7mAi_1y3r_zVU
qmQW7hBz3e3rDm23rvz_-TlF0PZopd_p_soE_-h_bW7mnlz-htLktldnJH0V-nk0Z7v-_VclyfLllmR07_JF5zNFdty3iABw-VKt02kWdzn-_fy5yDFhRm0-
wwwAqUVNtpyCE_iVUt00yFEVU_qDmEprDm1prvy_VmCmbvy_VmFWnT_vFmVYtu7udx_-1i3wyxV-9my0_mvL_0__mOy3uFflzEAVhuFnFtlz3O3rvpzt_Gr0
K2wm_hVqZuvHz6vNsZy_01M-8-6pNHMy_la1o3z8iloxHw2Fzh_3kub1_lq9gBv3U_ZX4n3Ktn-1laKR-la1oF7lJq3rcGFG_xC1_j_x-NdrYVvrh_SJOik_
Fm5zcpPMFpq0AVxz4QY-JnlwuGb8wUzFG1_cVy_tb6_vLlrLWVNVQkEfdvs0aFx-4UY3_FkNEzv_VrrNvTR_cs3LF-fy_tsjIlFlU_MFUu3_lbPLyFhlU_LM
3_6ltgeo_FjShzxk0VxLsrqLEFwxMlsLwdZ__agrmH-OWFvUX_f_dweo-Fco_dbz1Vndw9k0sVecOBQ-2PYjRm9cwvk0sVecu3XztTM_pjCt0hDNtmJCrZS2
1-Fh7luj_k8_8FxXfx_uYxyy_nNtnyzV_CL_OloBGY3-Sl-Lzs_n5t_ndnR_wa3YB_vwfVqxclX7uo_-K-DVBVvJuxywcbvP_mud_i7uY__K-5UBl_XFZ7_7
4_zO_CL_QlohOuc_t7-zS_xT-SG_57_ndnh_wc3YB_wgb7_V8l4FnBywd-o_Cluj_cTd06O__Gt0R7u3C9lV0CpcDm6dl_AJ94cI94cI94cI94dw8m
}

