sprite $connectivity_test [512x512/16z] {
xC610000080WXFrj5wa20000000000000000063sxGDbZZO6mk0Vx1qHTV_RckWWQ8BpqlKSmJLlyot2FzWpiyNHdzeFG3FL_lHhFm2zvaiVjZ2Flta0wFi0
yFEdxmEWF_DiI_WD07qV07t--4i-03rpyYSWVGDW-Zi-0Fhy7Vfy01w_Fm7f6m3yFW3w_Edx0F3x0EZpf-y3m3yVzlrpwZ40z7q0ffy_VH-0GvyxaCTl0EZx
0F3pf-y3eEzFGFm6WBuFW3v__E_ahwUJN_H5dpv-XxuEVPb-cNxH_rNHVwrClqn_MVIV5NsPVZdrY7vFfbz-yikXJwPVfbyUlnpwPFfb-kNK8_eo_NBg4NsP
Vld9BuS-cNwPVddySkYJwPVfbrEFwClqowb7z4N_n_z9w8UMlqCVVzFFt_It-Nly_1tw-9j-_gQVlrCFV_hyJJz_fnx-zFcRVlv-ylDtwEDl-lcRVluUFt-7
Flwcdx_fv-_Kmvy-VzFFtwc7Ftt-ff-_d_py7Vhuctx-ff__dzFdxz37t_JpD_tydNhuq-Tl-laxzV2dpz_qy_UJdxz37t_Jpz_qy_Vu-JlqyJVz_4q_VwSU
_lJvctx-JZtywVCt_VpdlVdvE_JnD_tyJJz_Zv-_Gnz_qy_VzFDtwk5Fdx_fpqs1lrDFrYZmfv-Q9l-vqI_odvlfB_1tw4jDa_-4w3VupytqD_dJFqs1lqDV
wfa2VzEVzOlyvsRw2_oTUa8p1VxqGwzfyf-RwI_mT-e9pHJuqqzDa_-4w3Vupytq5_WxzAMcoNz2z1ly9sJwA_pfdwR9Vq8EVGN-fZ_eb_XFoFGt-4_8eQ_1
Vq8EVHN-SpFz1VvEFQ6P0d_wgMdodn3z1l-vcVu2VuU-r3JvJuX-W_-4J7-5F_tJDFbFoA6lmD_q1_qI_mcP_WR_2JdqDVXFoA6lmdz2fh_0twddDbFaJ_ys
JVuJej_WFo7Jt-3lq7UR4lySVVwcdx_7pz-XZxz37t_Jpz-XZxz37t_JpzzFVluUFt_w_4q__wtWvq-Vl-ddx_7pT-ZZtw7Ft_JpT-ZZxz37t_Jpf_-6_Xu_
V_hyJJz_Zvy_VVwcdx_7pz-XZxz37t_Jpz-XZxz37t_Jpxz8dx_7pvz-xbNbJ_-qM-3lyOTs2_pfXvvjyjyR_IB_lPd-0d-7ljGs-M-8VeF_tan_WRz3NseB
_1twibwH_uPCVuK__TCs-U_Duo_mfnzwRPF_Xan_W_-6J7-3_zwSUfhyDqI_mNzlfh_0tw4ljKt-6wBVuBytqr_Wxz2NsWB_hE_GL-I_8TDVuK__j4t-6_Bu
6_mtvD1NuRyXqz_Wlo7Jt-2_8QUU2lyDqM_mtvlfB_1tw4jja_-6w3Vuxytq5_WxzAMsm3_hE_GL-M_8z5Vuqpzja_-6FFu6_mqvz5NuqmyE5VuRClqD_Xjo
wgdmtn3z0d-F_-R_rphryAVFt_JpzvEVlqCVVzFFt_Jpz_ZvE_JnD_tyJJz_fnx-zFcR_ZVpT-hXJv-_wUVl9pz_Xpx-ff-_wUVlyVDtwEDl-lcRVlvEFVpf
ypVz_9rw-DFdR_hVmzzFVluEVVnDFt_Jpz_Zv-_Gnz_qypVz_9rw-DFdR_hvE_Nmfy_VzFFtav-_Gnz_qy_VzFFt-FaxzF4t_VnDFt-d7lxq-Pj-_auz_Edp
D_tyvxVnytVeus_w-Pj-_Xu_VuS-_gPVfbzEFQ8lqo-d7j6NwPUV_7Bea-cNwPV7BuS-cNwPVZdrYBvClvnwH5_qwVzsVZdqoVJBzClZbqEVJBzClvnwH5-c
NquzeY_JBp_vvT0dqo_JBuzV3dqo_JBzSkeHVPb-uUTVh2_whlt5_2hN5tt-nVpgrjVJVUXJ-UCNVVx5fnvrw-j3z_Ihd5_q-HVhgvnVzFaNwmk_Er2nlieF
VVBu-HVhowadvaz0-WRWKtjsR0GG0011423KVxL05swtXPkF_lWtslc9rwTTdxsTdtXzslM9vwTTdwLzz14VF-twnAyUlle0000000000000000000000000
00301G
}

