sprite $security_command_center [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000063sxYEzUXi6m-X4ZyYPzx_R8BqtwpSkUB_phi30WHocVpv9EtXsxVrf_tt-vS1_v5yTF3tzf_ud
Nm3zv_udNm3zv_v7Ne3klR-H_y4duDD_xd_o1T1_xd_o1T1_xd_I1UZQ-ulyvv-0rjuD_ZClGBjgy1zw0VHx_QjhplJq-_shzJ4d-Ft-rO3vwJVu3xq0-Zt-
Cny2zBlynpq4jFOUury1QMrNtVxpBu1-lt__Gu1-k_-KXu3MteFzAqGjdtw___mBeD_lt_yGeD_lF-eX07--VmMjNx_Vl_y2wFVxJti8qE_txty8wDxxSFyA
Ozlw-_txBu1-lt__Gu3-9F_MXu2klT_ElmBRiFLs__uBeD_lt_yGe3_VV_v3W7vrwCy3Vxv__mNGx_TlU0ZG3_3lVmZGh-R-O5fxn_fNFlre_-gArkTVPUlp
tolw3_lyg-XFdtzrHUlphxBr-UyLZS-_YjRdNrtH-lohR7t-UqN_Unpyg-XFdtzrHUlphxBr-UyL_HVv-LVHdpx_wehMvrzbw_FVArgVVnMDpxzQqVhygsnz
_dj5w_El_BMUOVv-2Mp-hOttvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VF_yrUIp-yxUq-9_fdpmS_zxv-8_AXDqbxEPAz_V_ofZjppzvKFx9e_9VhnkMVv1-TGtpvvyyB__eYVadZyn_mF_qX7_c9XR_5_j7pyq_UN3-qQFpZvwT
V_Bm_5VezFpDR_wFSV4Fdju6ilcj89lV3l1NYtyclotW_w75Fv7V7hBvBIARtoQo-QqYczyky7_jClYlQ7_-ay5j8vlVEhBvxIERtqAy_VZdVlusairl9VXx
_oCX_EUt-8VmMmh-Xby0_0-BVmQ_jVWhF_mFclF-KnFtmh-5_jVUUp7yr_slBVvpnkpxyd_R6sw6__s_uZzXodxzNtkVrV2_FnN_5m_PeDzo0Vm_rUhYVtu0
_AUEU3_iwENmln_7_qKZZj2_gpdRuT_FN_5_mOJN5Fwg_ny4uJ-7lpfjFVoBl_q0-C_dF_y0-FVpL_nRvslWRpW0_WFvvny0_mR-fWFWtyy_yG1MdZ___Wtn
lxym_kEdAwN-0-0_PRZhQ_slsIlYVtzn_2SFL_oJ3e1__-UVyGjWVUWL_DM7-CU4tm7mvu_V0V3dZzy1y1V_qF0x0FxY7nf-1y1V_CLV_8U5V_u1YB_uYx_u
Yx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uAv1V_CLV_9N9B_xYhzN7lmQEh-3FN_mLoY_-ugzWVl7No_Z5N_lRTFl___rJR-pl___Adp__1utb_uwzEyaM6uTX
A3hHCJ73_dTRiqhV9pGfF6mW0Yyjv_Sjqs41pjG__ruTiy7VsOy__Xx9Z__-1J3-AqgUlfT__sGE_kzyArXjcGml0C-x_Gl_pfhJ-AqC_sTApHx-Vl_oxEZE
1TWs5lpz2Z_-SvgUjp_m-v0Jur-JcluT_bbFHSm5K4CMODXRaHT0wsU2QivCyE-_0jRFX0Ku3V_nw_e_qS6_yGeOE94eV_dD3PZp8H7-_HimSY1b5g1b0wQE
8yt_-A-c1H__oOsRyMt5-Ll3ttW_OS_Z7x3o7zodpW9_UNKgO1GiVSyaoi4N0FmAhLrUcvFZJ-yFuJbGz08m1V46i4-eFnS03u7-Rk1NTFcAvrTs_PFkNwn_
S7_wY_fC8BWy_gBxfZpwstdmvmB8ROw_ACu21DV6NxJUaoTn54hsPnOLoD_hBngp0C5zyHTrMO2SieN_5ydkYh_2gx805SEF__p1L7zD5Y2x9FuAxyW2L3G_
_XBzM820TlZFd54fnfy5w6zsyF-fXFTY0Igw5VvIU2SMG6vCgI47_vdNfJHneLa05VmpKsfAJTJ7tsfBpQi1lzMPy18iW6WmBQNcSFnPKNjgpjdXj_L29fyR
__cZB6axFmkWTGS-qVxu-yv4-yFl9zeVVqVxms_Z_-DKj3_-lZdH_l3xHFlZxsX_-ErSV_Znnz_H_l3R-7yh9zeVVsSasXz-EzSVVlpnTxG__7QqF_m-qVxu
EzeVVZlQ7tuR_m-fQ7_ydPXeV_ZjQ7_uxMn__9zaV_Xj2Nyd1tzd9ztVwSdsBoS7VvDaVziarz-aOyx3pqKo_H-JbabFNqjIWVucJQEUVoYIvc_IDkmDHo99
_YQDuzvn89BYNoQT0z-oZoJ2twHtv6ksaTJr_YRTCrzq5dAtlqd_r5UTXDphR_B6t9UTWrpfN_xPaET2V_zyo1db3tz_HldtN_vaXlz-VXPWvmQIM_oFoPi0
I_zvanlyKVolFVgW3I2AeG3M7Ut7dsqvtFsHI3O5lp3_Fsym_J_lCFi_hp7uFmimzJzhCFC_gp3nF-imxpzBCUm_Yp7fF-invpyxy3FaFvimuJ_xqFy_E_7J
_3-RqVa_-z7tFqVGyxzo21t_Sn3j_dCKlVvp6jNeFnVGvJ-NqE8_rt3_FrTn-J-NKHV_qm2t_jC4D_uhRL2d_okjSFO_xN3kFornvh_I52V-qnYr-J_DKHl_
Cm2x_ZC4E_up2Al_Cmory3y3KOl-CnKB_ZCPx_up7i__ynm00000000000000000000000000C0_
}

