sprite $media_translation_api [512x512/16z] {
xD8v0G103CEmUm24FzjEHH69WfqM00000000000000000000000000000000FwtuAvNaDu3y1f3V0Fetazy0-gC_-gC_-gC_-gC_-ZFitTUswxOIHD4xnkOb
wgt-_skTiqqSGQU90eMrtWM7sSsjhCSwx-xFbc_kpqL-St_-nc_cJntXrVq9VyAVy2Vyp_Ea7Vonnnzz_C77__-GH_rPVlpHnnz-_FFwr7SE-0VuyRzM3lYd
-V7l49Rxv_dnxne7_9Fy-7y5_9Vbn_-hrl_u-ZesuSV_yknb_V7_AlJl7Bq1F_wzapVYnnz__6z-S00__hpUZp_hZp_y-EEF_x6rBVxuuhzb-FFW3tzuyIVy
zmj_-F5_CTEs_irRXJ-hZp_y-7Fnnz-4F-6_NVZ3Zp_XJ_WJ_eG_uNzF-EFVTDa6_lWBV_pnnnz__F777t_yySSVV_m3uOy__lZZZp_--0U-_tCNV_pnnzyJ
-1Vsnz_kw6_WZx_j3lu6_lWFX7zm0F377t_y_xUNF_xk6Exct_IuYWV0M_jh4_zBPM_eZxyl_F1VFzU6VpxyySSVV_pnnnz__F777t_yySSVV_pnnnz__F77
7t_yySSVV_pnnnz__F777__w0V16_lZZZxyxlXluuszVw3xLVpn-A-0FMlnlQO0_5Fxuup-L7t_ylM3uuuy_btyR_y3wh-jl_7Fhdn-0OpT__8_S-kVzuRUT
tNxyyttNxkD_TlWfuy_wvyE_EHJ-h3_--EC_ZhO1F_uzjhtzyJ-ApZczRFYVDNjxF7FzyRTAvBIpF_ujm8z_V01OV_pNvyU_NWz__DVdnx_0RsT__FLH_FZN
2xOx_QNiTE6lsFhN--DVRwZ0-fUTVtwhJVoREXNTCk-FV_qMgrExQIpnN-O2eEZwI_X7Bm17oVhd_V5tLtBLzTSnmHz_HVYj5y8_Dm1j5t_yjUZwg-6V6W2j
u2_ygphLQpf_c-UF_xZeSJE_zMBuHmP0c_dZloQ_3lpd3u3MyHV-qmUWbOda_V4Vt-kL-2Ny9m-0khL7-kF_igtkN_-sf3_-ciDl3ON_n05Gl_PiV_ojiVBh
hsCLV_mp_mhuBp80xVd--3k-_iFXNrgIF--FVvQ_XVtnT_AFltLPqrNuvmVWzd-sFSaVVqVvn_sFi3_-ZleB_-9I_Frh_2n__1svxsVhFN_Xdnm0Vvm__ixm
zoyny_pnR_Fv_VvxZ_1F3O0_qnz_ByIlRuramx-yblCVV-yn_g4xWFXp_s_QRqZgkfG_Z__dhR-DVu0__CQVzVrv_Z_lhoVwy_hVw6hZ7-8FVEFFc7_3FyOl
vVtrP7_U__dgoVZVpHyP07s_l_0FyalulnkV_pjVFnN_E7_z0AZ2N_Zd-CS1tdnOr_1VbL-wP_t7PmN_yPeAYleB_uBj3mp0qDTxDFoZ_FK3KFVR0_Yd-QK9
_lX7-6zwJ-WvUXJ-8Vvx1a1r_iB_HlxH0QZtnp_8Np00HPgwxCJ_Blwn0GZv2_zR-8TlSGJzyQ_dBnY0GajTX_yT_EEtEYVuun_Xj-lk0PoZB-VWd-UtY_px
aZKtmx-UtoxWB_37FyHltxx-xStRdVXF-Otjk_qBRuX_FRyTlFpZd-UtW-llfklmdy9l1_sDVvpV7X2eNcByy_nsnVhNXtyb__XP3lZZd-2t5rn_dVZFuhSN
z1V-q_ZjuEKV_po_lTpwI_XNyO-VsWB--0VvxR87_-FXd-Ut5xlyI_ZFvBU3z_xmp_FRQws_XFzKVZleZt-UtmvU_l7FyzihhR-4_sH-E-YFVvxV3Zxunp_F
Rw-p_XB-q_djzVpntvDVml-talnvV_oTvC_xu-yT-INy_oZ9d_V7tmln7_FzyVSo_1uWApiDVoVvy_xu-sdyjTyXWBy3_5b_uV-talnvV_ozEF_D9-Bl97_U
7t-d-OyRtdkC_q0v_d6i-ZFnTv8_xu-_L-K_x_ZfkeR_l-hm9_qdd8f_RNb__E7teKuVxu-_yNz4Hu4__gp_uCduvyCV_vRnR_Yll_uJpiO_5_xuA-MlJ_Td
_Mty5-_OsXz_vVorjZ_-BWZ_fLFIltsyF_vDdLRsnzybuRzmBUil_DTT_tF2YE5F6_WJ_eG_uK_u4_w4F-5F-1F-X3_y-CEFF_pue_zq_xCaMjy_oGz_tXz-
_E777txy0_pmX_tXn_zsVcgh-a_X9w_g3p_-ANxuy_xmuv_YXp_l3p_-ANxuy_v9VlZp_l3Zd-A7F--Vv8S_xv_aXp_ld-I7F-__qVpm9td9-CEFF_pR-TDX
_5b-_D77dpTxuey-_bpvyGSVV-WVvUy9KT0VVlpXnnz-_E777txyuSV_H_ReG0e000QY4CBvsuvZxvT2-mxz_lNxr-zVlt_z_lNxR_IZtxz-__hzw_Ultxz-
_ur-zFlNxr-_V_t-zVlNxx_HZtx_-lthzw_Vltx_-lqt-j7lNxz__Vxr-zVlNx__HZ_w_Ulthz-_Vl-jVlJxr-zVl_zUF_hzw_Ultt-l7_t-zVjlzgFVVxSV
_Vwx_UZtlopQ_RJxqRzh3mva000000RvMz_ZgmO000000000000000000000000000000000000000000008
}

