sprite $automl_tables [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000001WzkuqpMqUXw9mdfGQv3_iVxKzpnypnmHDl6S53i-za26Nb9EPzp2oC_pFR0Zz
0i0___GB0F-H6w3_YW60CGL0_Vcd_o8I_FU4VW7WVsGpw3S0x7u2eFxyqoy0_3_P0VeD0Fu5W7x-xNu2eFxyqoy0_0i0_Ml_UAO0g3__TZy1K7_-wHS0_WM0
Vlvz-HC0zUUV_cj8y0_wCViHcPbGVmJzZL1__ka7_w0VinzFGlsxGZ_u1_sO_HZvDw3-wAeVwez1VoFKdt_wOVU3-eF-RgW_x7vG_uxG3m_yGFr1VoFevz_k
1_K7_UXwkg0VJzSVrQ7-67tqG_r1F_W7_HZN_wWEzGVzu1_qWt_GZxZeBPfGVz0F_a4_-0Vze1_yWtxm3_fn_mC_K7zuu0Vg3_h1F-Z7iG_yGFrXzuFwHsHV
wC-8xWdWFvxi2VqP_o3Fnel-dfVvRvm0zS-8nWcWFwDr0FpLHqJ71AZ_sd-Cx0R_VKS0_HbnUWBiVhd1Vyi4g7z6vm3Gdn4Im7_J1D2VqJe07lY9Q9m0zS-8
pWdmHr_HEG3gdn5T4q3_shy4yD_WLo7w5_wxZG0lUuXeb03rN_i_yYBW9UzPuB_L253_Z6YS0FepedC2lEahEWT0_JFYo0Jm_nphF_wK5w3-2__THe2NFKGq
Je3wPqJZ1D2VyOO167Q_0lyBoevR_SlyroTWNky_tyP_Z9hZLlyb7n-x_KUK7FUm-otz_vNT_YCgZblzb_x_pcx_4GN7JVyN_Nzizn_xZpiNyFylTlkFs7xS
zA_yboLW-t7R_HR-VoO0ptlwd-g_ybyr0lOVzw1_uRyg0GMhTdu3_ZzoMm8gZjkjduN_eX5GqJQ_-ttR_yVdFGaeEMxJV-6_vY9GSjnUzBVmNtCHg3bkzL_u
Bqb0pN47_Gl_5HU1ekFE1VmNZ82guwP_uRyW0LN7xO6VXV-2Yq3PSQl_ml_-4L1st7Q_XV_z2QYxqQh-2__RBm9rnpteN_ZVFG8AZzkD_uN_tGceF6xrN_ZV
V16eF6uF_2py_xO4FCVxd-g_yB_t8b1wt5xsiF2_zo9G-rv5zL_utvg0skD-r7_XV-T5eBXjkO-x_7zykiB_V5__kS__cfFzptdx0CYj_jUSwt_7EVB_yUbG
_tFUFW2omF-A8_sFUMG0dZVtl-P0_tFUFW2onF-QpwVvd_Fs08mg_slUs_zuF_zPvt_DIVxdl7q0PAN_DSyR-vzlTXTu5FjVSuh_EMyV05dkVyqH_iSyEm2N
-5zpWFzvlV_a_xSVR-wZG3__H--0_DSVRkwZG3__H--0_DTNA_Vn8ltyptbx0CO5_laVh_YG_Czv-m38r_ddFme60FyRz5yp0FBByF_CUmF0_xUPr_jF_b-Z
__m0yCz_ylyw_US785_ld__nblxvd_Fs0P1VXlzdtXi0_h_DlDv_yhz1_x416Atzyv_yRz1_R01odt_-dzp6mt-z_lC7GFA_yyLgux003FuBtwjOxp_vtwb_
vauAFmx_zVfpyD-v_fbL7uV_DRaR_klqd-y_lmp_iK5_RG06_uNJlzv_ybyt_Ui3a6_lFz_AVvOmRlN_xGIe_uR_fRpOVxwD_wpYKl_VJi1H-aTMCTRwh_6V
uxVx7nVLVntckCX_PYmn_R-SvhpA_pe1flyN_prvc_yyst_Mqi1_vc_pFw_tdpVwptFzPpKj_6Uk_TEVXPzdX__rAcZtMmVWoRriz9-vyA_-cQMVPuF_LG9y
-VilQZ_EJlzvcFyyWzhFy_cb_jS9SEldlwcEuqx_UP3_F8NgE3uR_MV-dt_wi_xpxFIV4Rxy_Iy7V9oD_at_rHFXMSmc_sxzh3ZYu-pmh_vhHXx0iVxd7lyu
q_z3_ychOE_fRmJqdlu2qBl-4j2x_X9mN_snmVybl_j9GE_TJm1wJty9wFtbJm1wrry2Ud_v4u3UzPU0k_NZKvN_yGx-ZO3UzPU0thkV0FIklmJqtlq4e7Vz
9Q2tVW7e_ULF0dhNtzsWtlKt0dhNNmBUGd_aYn20tlMNWDxw1Q3txtuIqBl-0j1szyCv_kalUtlWyVgVV256GE_wWtxO_Q3-y4TVK7_G3_v1FzpuX_h3xWVr
1_tmeZ-eF-n-K7-CynxuWVg3VlYZBwW_x7vGVtZW1-eF-c7tW_h3xWVr1_tW7_J3bp-e_sOyy0Frnsn8Wd_GtnN-GJ-UsOz8g7zNw0V_e1-p7oCp4-gFcFru
Q5T_q0zV_kXl1klyWtuC-hkX_g0V_7U4VhZr0_NlYDqFwW_wky8_wCTZz-k6-eF-ll0F-k76FzIV_yOF_A1t_V7qre_c_a4__urtF_IkFqPl_MZk7utrWtyq
rW_-qLi_ehT-DFUFnlh1Fthhn-ZzknzwrnzFR_reFltHkFxW7xtrO_H-u0VDwu_6-i4_wBy6_l_IZXqG0010C03htreC_5i5WBEl7mcW_040000000000000
00000000000000000000000001W
}

