sprite $identity_platform [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlJj9SrjNWYWyeI8vm_vN-zhRwJPf5nLY9HGd5s3Zmty8mar9xndLYXscfBDI2s0awGmE0Ft_
-kSMWFv__VCAO4fF_ba5CFfzphm0q7_oJoi0_MV_e0AOKkCVK00FV-CV403wZNz00UWt_W45eD_unnK0lyw40D1l_0CAGB_n3oW0_SO_k03uTGO4W7xd7r00
-er_G07eD_x11S2lCo00z3l_W0BGR_m32a2_yGyk07wT0G6Wt_a7581-unzG0FgDVt01yEiC203zpZ-W0FGR_u02q6_yWmk0NsT00EXt_W45eD_u1nI0VkCV
N03yEWC2GB_p3oW0_SO_e03q6__W0k3N6H00-fr_G07eD_u11Q3V-0SN0B_EW03Gx_m32a2_yGye0Ft6FxW0-7K6181-vnzG0FgDVq01w3V-mGN0hpCW0FGx
_u02q6_ySmj0Nwh_Jbu1y3_zNlz5geG0qEz-pyyk0Ftr4_EP1Q2_VdwE3oi0_lNb-PG0q7-iQrCVK03wwvM9BG3z_Gk0Vpcc0W90lvjDZm3qAG3zl0BWN--O
lGBWuUS8G3-j0FGVopZyRG0F__FK_03uwxwO8m1zFp__C8X-FvLS0Fnh7NC3u7zuZ7y7K82suVS7G06FVVZz0L20jk4d0Fze6tv_01IWRVZz0L30Onz-Vm0K
e47ynzFF_zOliry0wElLbJpjUjKx0g00JU7_uS__LvNPdm8qX5zIu_-KW2y02j08_v8Q_oQ1iG6WByCgNjtxyxiAG5-ELRowzyT90JRz-_dLxhtj0F0N0Byi
gxYyzGJWr_VpbzIFOU_F-mj0NwPbNDhwtfy2f1d-biz__680570CuIzP_C-gOG7myCksZWixt_XJWEuPsq9EOm0KeDtuzPLzx_qfuD0OV_ldVnF03qSRyikq
xJhJ2z2DOroBQzVFCxe0RSelrwQVvv02y2-3__W0WlsjQx7jUU5_qrYNujjq_3Vabs7N1_dZh_VwVtS0-2-p_ru70FxcTJZt7N_yyT-ANywDB_pVFkvLMF_c
RJj__2qxZ_zSVhz_1VZZF_80mB-Pkil_-2P__FrhyEqz_lZNj_dZBuF_s0C0V_pnN_ZZxrs1SVVnnt_Txuy__lZhLlzJ-3_Dhe-_NDkFF_xuur_VuO__OV3t
_1iG_lEkVtx_Kz7--DTT_lZZZp_--2_yySSVV_pnnzyy-EEFF_xuuuy__lZZZp_--EEFF_xy-m_--EEFF___1__2d___6-UFF___7t_yyLUoFp__MVZpyzy1
_lZZZ_-0unz_Fly9_ySGVoNxy_b_bUhFvx_o-R_uboRwy_dl1v__ViFm_GzQ8_tnBxx_vUt3ztzf3VN7l_Z-DzVm_O_-ntz_Vxx_LIlM7__-yQzFz-Vxtylw
-EFl3-1uh_ynm1z_uqgCZp_-6mRWuSV_nh6knSUF_v00ZZVvwzZ17__r7dzf1Z_-3-DgFFpuZpe0bj-_3Fpupml0m3_F7_zbzIyP-F6V68257t_TFBObUVZn
7nZ0uV4l7QkVmbyJ0rWE_z9Qynv__4tB-g7-J7xyvLdOXOU_EVtntos02m__XCSVVycojbxVm8__w00QVQrruVJ7Vru0w_YYVqd7Mjx77t__N5nXxrybhMNd
nzy_hw_nx_2rvlBZtmVGJ-zV3Rw37t__lBhIt-dhoxzSVRi__dfnkNNz5sfqy9yMW7-E9m_yqm8m8E9lcG1-_Bi9uCU_cm7y-ES4K0P0_AqJm8z_Dm5dF_xT
707y-7SJm8z_Dm6lVlox2NZuyMydW1__RWBEVlpRsUhXnzy_U-dZxv-zZdxy_RFNmu-_V_RInzy_U-dZxv-zzF7tpsRu-FjdCtty_RCPFlx-sGqVV_ziPu-_
VpQanzy_nnDyLVcDy9y_7dRyTvrvilZZZp_--EEFF_xuuuy__lZZZp_--EEFF_xuuuy__lZZZp_--EEFF_xuuuy__lZZZp_--EEFF_xuuuy__lZZZp_--EEF
Vzq-sVxzh82fmh_XJmq0_vKoAlmR_e0f_1l-l7S0_ciHG8W_-i-N0FnNv1J-3N_AEm3_5JjL-A_aKQNxh_2fRFyLFrK1_fq-0OJvF_CpgW3_Xf-f0F-6dwaA
y3Ve4y2k_Zq_emhmR_YPYl7_sxKpLHd-I3S1RE_lvoU0-VuUVgO-tF-0k9-gJ_R7rn30V7y_Fm7ix_-O-3E5v_kdlcfL7-c_Pl3x_VrOLRlvs_bB-_ZxZu2g
J_Etz-Jodnc0wgFyoynlzfzz2TZVtroJtN_w9M2-lvE_jA-__nAmlxypfTd-_al0_lw7dT_lF_SIiBs_BwHj_FsNWFd-9lxIxlx-Iy3E_gQATlBt1x2jloUY
xVpzbu3v_XR-07_39M2al-FL7-1lU0VCz3VyZM-0lok0-VxBmB-pl_yICDlVm1_WRxW43FKtlFe3_0tlWA7-XbT_WByXWFd-hwGJu6-u10pqD_07-1ik0KFz
3Q_-07_7Es2q_zLi0lnD0HmrqlyYF_uNBW4J_Q_nut_j4Z3F_m9_2V-hbu21_XUAmV_o9M2Q_oL-_AzV0cfjFSB_jKl0rlub_5yw0dZuj_Kd02Nx4u3mDrm2
UFLlwCyH80Nx4u2I_Gb0mVvS0ah1_Xm1Kh0_0IZPdm0KxCybe1Jipn4W1ViJW9Bz2K31_bm2Ii7-705Ii3y1ADcV01JipoMW5EpF4I05-nE0alq9GC7-N09A
mVuS0LAmFm48__a1u8y_1Q3F_JzNdmAozIaWMvy2ilKf85kV0hBrAI1RdmAozIaWMvy2ilKf85kV0hBrAI1RdmAozIaWMvy2ilKf85kV0lxDBXq8000000Zo
jnxa6EgjRy1Rtu2tlW5lVGFU-WQyzGruwnlmrZVWhM_0Mz-0jxu1Rtq3tle6lFKDUEiRyDOtuArlm5lVWBU-0Mzz0zxw1hpr3NZh6_3MD-2jRy1Rtu2tlW5l
VGFU-WQyzGruwnlmrZVWhM_0Mz-0jxu1Rtq3tle6lFKDUEiRyDOtuArlm5lVWBU-0Mzz0zxw1hpr3NZh6_3MD-2jRy1Rtu2tlW5lVGFU-WQyzGruwnlmrZVW
hM_0Mz-0jxu1Rtq3tle6lFKDUEiRyDOtuArlm5lV0Fgr1yS2000008FyhKUnhxe00000000000000000000000000001
}

