sprite $automl_translation [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000009YzEzj2LaS2CEeoB9AxUl-dxU7Cyo6eMAJslkq-arygFr71p00Ow-XHcVuZ2fBV
0j1VV_aj0Ftto47-_1i0VLW0nbz_-HSIw5-2_1Q0_Zu6aDy6uEnd0HX__UMt0FJVOeByDW3zBG3vzNVsim2Cl_xoMm3wMm3oBzQVRLW0nbz_PpyBmFZhBxy5
eBy58B_-Blui0EEll_pB2FH7VaOzU_mFnfzT_aACl_xoep_oC-hP0kDVbVpeZ_oCUdhy7yQVglan_dJv2p7--ikFin_67_chCVuu-s7yAv8VD_nW_96_4Fdr
T_R3-2C_LLzTv6Uh-g4wnfzU9p_67_dH7_dfot-eZl57VlH7VlH7VlQ5dgA9yKT-z4T-z4T-v4T_v4T_v6Vz6tum_hZX1-EF_EYF_2n_mm_67sS_Z3_oep_o
iztXXf_zRqH2nbz_-VNthG_zZR_--kilVud-pdwXl_7NNtxzzTTVVlszzQE_yTVVbxxqD_xwow-__lhBhx-pd_x6_-B-x9Vcrz_uwo-__Yx-zYJaVwUet5__
JV-V6N_zVUwdl_7NNtxzU-cpd_vZ51v__STQ_UVpwp_AZh_-u_zwqREV_dtyeEZuwpz-KZA__aD__NzGCB_-O_d-SOp-ezpuwpz-gnVBhtyVlrEil_xZ3qgz
zQF_-AFQd_lfFmhj_lgFFol-e3_FLQmz_hvajLVEB_yOjVlhFqhdbt-KkE67yRTAZx_ye_ZPp_rLjSVV3JQzSdxvnwZzf2_znzBZprY-Vxn2_r5w_EKVnH_o
xhcAouu_uuYjylZBFyQYLt_aUn4lp4_6Lp5XVlt7Wlt9-JfUb9-UyvNSRjA__OCN_je4WxRC1X19-xSC_VDkfVVut6zhV-znklypwwlSxzS_8i46a7Vyysu0
2VFhFsxsBd2F10iWSVxLDu3GVsB2rbi0yTK5yCZTVopVFxxRloNFl_e2Y8YS6y1su_vT_vTdEKV-rJU0YAGRGClKVu4pODx-BV7uhxu1H6JO09AE_nYhBu2U
edzxwV-kVy_tBpbPDEduhxu1H9R-y_dpzz_pRm2HPW6a7F_LDu38qpzV_cqilm0YwG9eASP_-VwHgNzBj_illm0YrGAuUFprZ-iz3uJDcJ__0aYT_r3Rz6U_
ULt_umiWrVYllW54llujJVvjBBy08kS2Q3d6V_d-4IaNm3D9_jKNG4_Q_vhy-iSNfUy_nkeB8BxfMMhynzZotH4UNrKWV-uD8BuiTVz-wwSgt-8fpuzIupyY
MV_ukbBvH_wd5ETV04_ZVqo_HVym_eb-fI3_8J2C_s6tw1y5ygVi7rcqunvnaNs1_14t-OMV6hj_ilwHXzq_mw-Kvby0OVmdzNlqZ-Np3xzI_ke22ED_mZtw
h_wdVuzlwNV8l_hdVYFPBnRiaKgou_zI-QFdl_YROFUVbZp_rgOO_scf-xTfpdwJSkUVP_mdfUtVJf9_IlRyyvpzJY-0BP9ujbSO_maPnx-zoiNVSUdojpSm
_iSb-_Tfx-6jdwDIvM_lO_mFohCSj_PMyX-Ivj-dlPsBloFot-zrdl4_TaVuVUhFhXHl_HnOtlUP_HDRXV7_D_rcd_AtIO-qV_hJPdpZi-4jKNxrpnyLi-t-
l1ImdP1ez-VLUEsK5EFFExgraup_Ab_jQwSP_oM-sDVEo_Uvd_ZpgTffpdvhVAVpe_s_db_-vyIt1HFdr__niKvdLfNnN-YEZkqMu-_YRzO5RoMc7N_zOyfY
5tyMm0V_vhxraVx6dZZ1nLzcyuNcEVjbDXzetkql_lIFrsG--p5VPrxUyUUQN-_CUFPZFirvjxluim0k-GSzSew__l416SUVYVglky75dql0-AW4uxy7VpUJ
MtnUrl6t0E8gUSv-N50_yztUP8f__VYpfOllx8VnPxpT5X-2yKT-dFqm_dZACyOV-T4V-V76FyOVPp-CF_BZGNyOVvpzCFxq2sxumVWZFxxqXV77sG_ZZnj-
CFx8ZxCVnXzdFum_ygC_ykFY3-EVcnj-CFwCWWBzaRyg_P6VRTIp1yQ_AldH7_aPzVJu7um_-wXdaztu8pyk_kGlHdNzaPykVpN67_dHloBvyTOFnhyYPp-C
F_9NfJ_oipdxLMFyaRyk_P4VR_nZ_FKlVCCFjSUVhNP-YlT7VlqBd_seFVxqslaftf_2-T6VmldHdzhvsMldftX_2kT7VshdfzV-t8_QuyzMEp_5TtyAZp_w
Kpi_lVODFnGVVmhdHt_arx_mMpyO_vNyjpqu80000440zFzrCoe5JWC000000000000000000000000000000000000001W
}

