sprite $ai_hub [512x512/16z] {
xDD10OC00CF03GJKlre04RnoPw7flW40000000000000000000000000072U2xF-QrdMLu3rcmLONm7MLu3r5M1z1LXV0TOF561z1LXV0TPNWFKp1LXV0TPN
WFKLO7q5M5y1rbU0zHLWVGLONm7MLu3r5M1z1LXV0TPNWFKLO7q5M5y1rbU0zHLWVGLONm7MLu3r5M1-1TXV0LC02a01A005e00KW09G00f00IW01Q005802
K83PVl42d7RL0gol0Eit2x2-0gol0EihmFeAiBu2hA-0mFeAiBu2hAy0wol0-WgmlWAQwol0-WgmlWAihm3hAy3w2h2-0gol0EihmFeAiBu2hAy0wol0-Wgm
lWAi_rB0pTvzu3gEPZ4KRi2ILOZS_sed4652FmXMbKrJ_prd1HVu-ABJD7qMW3uBG9y5eCy2q6S1-VP7OLfw0KyLzNpkZVphBc0_VdNvjor0RwvD_rUNlzjN
rNTL-dt-RbzLtzNeT_gxVLLzLw7Vw-_sLVLTWNwplziBz1TSm6RzKl-61IZKLx_s-_tTlczhwhjlwlVxkpsx08MBwz_9tocu07sXwC_zE_ehjG1zgTZN_btz
lO15zLtaQ_-s_ea5wCi5z6_h__a5gA20_atzFxq0bHJGlwN_PnUWeWBwz_Rt0Whr__ghS07MNypV2zZQz1-5dpTe_HNzlO0s_RO5M7zLVo-WH5-DpnMs_ih-
Na2BVji2hB-wlnVGeD-s0EjFyFS22lIh5c3zAVvUG85-pGAiFyRVFVUjGBzY0TQVvk_l0T_GRrk0zSVvk-SMrMzSc_Md-klvtA8QRGkm_cX_Bo0aqRO0wy_s
Trj4eMq1riVVRK61_09EzV5tMrW_ku1JVVpT5jJFB-1K7t-t1VNp2pZLnzzjGVty0axryNT9_Vm2h7yI_b7z_08k-E9Ve-yI_lYNwhk0F_wj-gxT7__7Xsls
n_yHgDKV_qUeHd_y7y7Q_F5_X6lon__nXLhyyNzygGP__1zVBE2FVwk--wO__e-2lkMF_wEaR_ZZ_oWgxO__ewoaF_wFmcB--3-VMnt_yyZvuz-sWAT1Glxu
kwr9F-kFlzjQzFF--BkjHJ_lZx_R2lJJ_lXtB60tnFVyyNTxWNxK7_zlBy3w5VxukpskN-EFlzkZ-bN--Bizfb_dZx_a1IJqA_tn3op0-ft--7z-0VlngzeV
Vta10VqwV_m_ku3zbwltnrzUG42_r1z_UG61x_ob_lZB2mZeb_hZBoyWe5_gZx-yW81-gJ_-yW82-gN--CiB2EWN-EF_nWLO_qx--Bzn0TPVmX__wmkm_Xh-
-5zVm6RzXVpnTuSNy2RzVd_yhtyFiFww_lXx0QVwA_lZx_OJ_SNzyNVxYVxY_lYx_KH_SN_ytNwYlxW__cu_qL_U7tylmFeJ_V5trX_hZtyO9Ak_g3_-qbn_
_AMv_lXBS_tnb-Rwuo_DzSTVckkFlpJN7tzfhZ_-qbn__AMv_lXBS_tnb-Rwuo_DzSTVckkFlpJN7tzfhZ_-qbn__AMv_lXBS_tnb-Rwuo_DzSTVckkFlpJN
7tzfhZ_-qbn__AMv_lXBS_tnb-Rwuo_DzSTVckkFlpJN7tzfhZ_-qbn__AMv_lXBS_tnrploaF3_lxP-__Vfu_z3nmX_w-F_SulxMn__auwb_QsF_tah-9_h
ut_U2lxd-lYVzmN_c3x-hnJtZ-dZ_rfX_vW-_gyMzO_fu_zwGV-OFlvNYld7zF6_LiW_fe__rIB-CNtyhnVm3-hZVxs0Vr0V_-i5_2Fw-Fzc0V-0Flvgz0_f
u-zI_dbz_9CBQDF7Fxk0DdtyimjeqyS_ku0sVVop2sZJnp-xW3Pz_BCBQDF7Fxk0DdtyimjeqyS_ku0sVVop2sZJnp-xW3Pz_BCBQDF7Fxk0DdtyimjeqyS_
ku0sVVop2sZJnp-xW3Pz_BCBQDF7Fxk0DdtyimjeqyS_ku0sVVop2sZJnp-xW3Pz_BCBwDB7Ftrbbpx-wJkxzF5FNzgbZt_wrYvz_DFNTkdZdxwtIn__zCLT
-lYdR-xInpzzTPS-_kcxRwYFVs0dtVhuFv-3zV5tW_NnTpFr7VvkfZx-pitKnz-vYVhu_tUpzF7_UvFqyV-fEVhu_zmSVVn_Reu-_ZytGH__imReut_Q07ty
JrjV7__pLjR7_vNMrSV_jLRLn__LrjJ7__LMrCV_Iklfut-jrVJnlzfQ-lXVRorz_A-tbZx-rrj57__VRGrz_7-_5VJn_vCMqCV_Zrf07_y_wjxw-FzvTzR7
_ntTLn__ztHNVVpVrJtryNzVdv31tmtsnzyb_TNbZxyB-ajT_lYxeB_KvO-_I_cxBd_yNShVTVdZxrB-hiiVVvVoTrt--BkKl-lonz-b_5sNF_ukvU-w_F5t
MyZVTVdZxuwGl-lonzyT8NzNve-_2_cxCd_yNSZVTVdZxuwGl-lonzyT8NzNvO-_Y_ax_3zMlRzRoFzGMOFzqNVufr9fW_tHTuFzqNU3_T5tW_tHTuFzqNU3
_T5tW_tHTuFzqNVulw53DswmF_fki3_wRh0_-cwmF_fki3_wRh0_-cwmF_eE_mBzwWNWhyKRx8--6-oFlXliZxwRwu--s-Rwe--EkVxeE_oTvdRWhzaDznSD
zWVVTVddzQdBFwzFNVvvVUhop-jJbtzUdmhyM_NftFy8-BVgu-_g_KL57pVeLj77tnq1_rPz_5sbloBXx-hy5Gj_L-MlQFYx6d_5mzzL-8jgFsxGBQgFlmlu
b-hZx_Q0Vwi-_YxWtwgFlulxgoRyNTHVLU7lOlwg2tyNyLTb-BkF-wil_C-RhSy0PkkpWDdwB62sFWkOhSy2PkkpWDdwB62sFWkOhSy2PkkpWDdwB62sFWkO
hSy2PkkpWDdwB60zVTel-C_Mvtl0R7qMC5kV1SpMPm4hwzDnmNz5VTgUvytMvyV0FzkbOm8001W6OT_yIvwANYGMe5tV0Utw3cZNTq2xlWFQzHtGhk-0Tdq7
jEixe5tV0Utw3cZNTq2xlWFQzHsGhi-jwWC000000000000000000000000003m
}

