sprite $trace [512x512/16z] {
xT515K00042n4zpqRwi20Fzj5RPy0000000000000000000000000000CBvDWN_yun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l7_
Cl_unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV_-_oZt_yun__-CS__l5Vvn__-CS__l6FV_pZ7__u1m000000000000000000
000000000000000000000000000000000000W35fJlBltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz_
__xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz_
__xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_U_5m0000000000000000000000000000000000000000000000000000000ECjvYJ_
_cFy-_Vltxz___xz-_Vltxz___xz-_Vltxz__pt-_Vltxz-_V__-_Vltxz-_V__-_Vltxz-__nx__ltxz-_Vlt___ltxz-_Vlt___ltxz-_VVu9___xz-_Vl
txz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vltxz___xz-_Vl
txz___xz-_Vl7m00000000000000000000000000M04
}

