sprite $dialogflow [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OFVkmSHm8eY0AGr3CF-7p9e5cBmhpVWGQlHhkKJSzi_lNpZq_VGNGFxC0-WgWhm3w2g2l0FeA
e7z00VGLG5y1z1L0Nm7q5K1V0VGLG5y1z1L0Nm7q5K1V0VGLG3zJ07q5q5S0VGNGLm1z1T1N07q5q5S0VGNGLm1z1T1N07q5q5S0VGNGLm1z1T1N07q5q5S0
VGNGLm1z1T1N07q5q5S0VGNGLm1z1T1N07q5q5S0VGNGLm1z1T1N07q5q5S0VGNGLm1z1T1Nm7zzewy0-WgWhm3w2g2l0FeAeAy0-WgWhm3w2g2l0FeAeAy0
-WgWhm3w2g2l0FeAeAy0_lmLG5y1z1L0Nm7q5K1V0VGLG5y1z1L0Nm7q5K1V0VGLG5y1z1L0Nm7q5K1V0VGLG5y1z1L0Nm7q5K1V0VGLG5y1z1L0Nm7q5K1V
0VGLCA5lz1L0Nm7q5K1V0VGLG5y1z1L0Nm6dwTjD_-feFO42OlhFyuJydq01BVsOVw20adxEFr10Hp_e7oYWef_q3nJGq8_w1meew6Vz0mK4zBl-WG82-bt_
G041_Qv_e820VjS_K410l-iVA22Wt_KF513Gx_e72WZeT_tN2-ZhVvu3_3SAwD_zld-WWC3Tx_e72WZS_Qv_e830tU_w1me8w7Vz0mLKzFl--mLazFbN2dZZ
I-8VAE0jVVwP0kO_siC_KC32ttt-2mKazFdl5x2lVpqF_qe12zyC_uq20lhy5me8wFFVAM1Vdt-WW3rz_li51FJvBnImhCy_Ki2-Fl_z0WBw_1SA2EZpVwc0
W3x_XG82-lnVAk1LVVw10bxJvnyfO46V_zXQP-S_lzR9-S-lTMx-yskTcl_yMcVcFx_MYVdFhtLU_lDhdPR__5fdvJ-_radvpwzrJlxpQvsI__nQP-G_lzO9
-S-lTJx-yskTZl_yMcVZFx_MoVZFhtKk_lCBd8f_xQlwF0FZlxNMYVZFhtNt-S-lTHh-yslTVVxpQ-dpdrzBd__yMlhyvzSw0__vRPw0V_phkv-5yTzUw-y-
__ajwVElVedNiph--sjzSFxpQtri_lDhVMZ-ysjzPFxpQtrW_lDhVLp-yrluiFoDl_4t_iRV-1j_us_yZR_nD_x6t_WRV-Dl_8s_yS-Cl_4t_iRV-1j_us_y
ZR_nD_x6t_WRV-Dl_8s_yJV-nj_u6__E-1j_us_yZR_nD_x6t_WRV-Dl_8s_yJV-nj_u6t_ZR_oDl_77dzc7Li2_z02mpm2B1u3hxm60Nm3u1O1V0VG5W5y1
z1M0Nm3q5K1V0VZz7apV8y3_zYZ0vP_PpNM0toE0lWBeHtSHtk3t2A2l0FmAe2y0l_WemELN07t_AuJV8u2-0l0BWBu2lFJjJm4klpU1Y_l_kVmAeAy0_0AW
hm0lVGfm-GNWfKy17lqAyEZtWo1-1HoZRuV_vRVxyCjlNleKSFJbj-jmVSEl0FeAyDBdvw1ZBx-v_0fm-VqHeA-0O_cDlW3mAu2-0avzwRFFuVhcqQ-0e_dj
FbpVy7_j-DCNmCqXv-_o-nsWhs_u-TFdx-TU_Yu_Vozz_5r-_lJvu-TFdpz-_lJvu-TFdpzz_lZvq-VlV_huk_pyyVEdpvy-V_py6_g6dpzz_iVoywVFdpv_
_FpfyyVFdpv__ytFt-NdJvy_Vlxq-UFdJv-_bpx-BZ__gtrwy-Zdxz7F7pz_-lpzvUVlylC_uwNFN7x-zFdZvq-VlvS-_Yu__pCklxdy_Edpny-VFd__xkFl
ylC_u_8RVVv7F_hvu-TFdpz-_lJvt-UStbn-_lJvu-T_dhxvkPU_oy__p9S--xZydW2-1FlU7XmG0020803w_xePbG970000000000000000000000000000
00m
}

