sprite $financial_services_marketplace [512x512/16z] {
xDr76k8m383HJP2qc_kVTdeZ7nsCRVpU5NxBgP0lBG00000000000000000000000000n3-r4cAlTl9Z4IVK4jZYj3fj-oJ4R-RVCV_s_Za_3l5e__bN076A
_T_EVtl_d9tXD_-6Nt_N-u_ttwP2tAe-4B5mVpAQzCyf43lctzwll_pwow-__FhBdtkr3Fbj1l9R0lAVbbFU229U9cjYnjyAaDzvWFnMWFmMWFxRmsfMyji2
vBS0zBS0vBS0lEhzk1pxfN2YiHePBvhfF6_a1q4iFT9qxP-ziVOX7VtbRzmV_RC6n9ANzEYF_iIA_T4V_OdL-gC_-gC_iLn_z4T_z2TEoLlK_DX6cV-j1sAK
_ja3FVltnrhzqH_zqH_zYLCEDwb7PM7-qH_zv-JnJph-dsJ-qH_zqH_zqH_zqH_lVwC_-gC_-gD_TiBQyq-SrEp3ZblX_r_GVup3FslFFsltvz2_VtR4slFF
slt9tlsp9zxH7z__YiBt7z5_M7htxv_ZSBgNvxNxqMzy76e8oA--_EeFaZ-FLJCuzgi_RdxKpteBzGs_-lAhlnrxS_qyjht-fZ3nIjkTEZyMOEMj7_NxK3_h
4bpoZRfTg7zunxQVEo_fZqUyAA_-sFrpRx3R0QxtC-xIElzfUOn9h_NpoSqExtQYl_gzF7F8hgTX_rTVV_NrLt_G_dbAFGNNV-fFq3_VDFpgct_tUgVe7_K4
OYnZV05UVlk_lslKNtxzdVdrw9_NrNFmei1qv5TV_woMv3Vx-gill_ZwYo-_-FbfrcwF2xqHwL_eZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xe
tnW0000000000000UFyN_T4V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_SUdF_gZFm0000000000003U__pM7XqG0020803w_xeRgN01_ECV_o_vnp_-yOz_
_ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-V_AFV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l6FV_p_v1__-CS__l6FV_pZ7__unp_-yOz_
_ECV__Z7F_xnZt_yun__-F_9F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xn_vD__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz_
_EF_9__unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__un_zF_l6FV_pZ7_zJ_ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz_00000000
00000000000000000803
}

