sprite $datastream [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000009Yz-y2DNiU2A8pe1aW2T_-hdJp3UTbmoow6xopW3pfrInHRuRi0q7v5tGRv8a2-
2B1_JGBGsqG2s9S0rIy0zF-QKHT2_wJNYJZrEmVGBm3ANm3ejmYaNm7G_tu0zayF_Uyur2FydtCseN-o-yuoMYu0-GoW1Vtd8u3s8m5OzE8IBU3_kWZmNst9
1A3b2Y2_oOmMzAy4-Dy_0Vpt7_YBHYq6_PF0PUPsy7zp0lZlxNrwxGh_rPeAu3-J0EIbj8a0yEzIa7_BGFwT0_WN0Fu5mFMVLI3_Le7y2m3_0k3tFm7W_ri3
W1zRYZS1SF-V0F1_s3w00FIe_rOxuVaV0U1V03p_BG3yxny00QWL_FVwCXW1_tSLWFT_ZNPY00IW1yS_7m1dWChvpmT00TH2_aTz6MH6Rfa2GF20hn00X0it
lGk0-BHb2m0B7Eja0D1NEDB10625C-t8-SSIHpaO02nnY8C1m1B7D-WVVO6ZsvC1m8Xlhupuxm187LEV3800u6R_401q0H20Y_tZyWB0pVuX0BZOFmG0u-wV
0T0lBW0u0-1k_nWN1m0A09S_3uQx2W3E0500403m3m70uVwX0A00e02W0200u1y20FuX01WN-uS2mAN-eG2W0D2F2W0K0Am0e01W4mZE0706W0A00e02W020
VmW0-8S0uDJNma81mFEWK01G0500K01m3GW50040_n00NFLrE2W0-3OC501y6mO2W7wfVoW0-4GushsxGF25Q3G1482rjm6X0200alSjzCK3CD81L00v0R7h
KFxp0SWjH0KWV-nlNeeAGAw8-Czl16zmDI80_PJxaj2U2u0TgHslJzhN2FmYjN80tZv92a1lNsCi-qjgFzb_I_yp9WiVlfC3C9RGdptA9wnGnmB7lRr7PGXl
b-GF_iZh3mOWjq8vxDpRtgO7QtF_2kZPqUlj0TQUcLgRwA5lZ-0rQhkklrey01wV6RcZtvx2ZJFP8HnP_Qs73fO0J9B-MtAvB02JaFxMLZzIzKa-7YHXulF_
rv7mdzikI_ZF1A17GhTwJmRyXm8GqB-1_xvq0Opj_RT5z2k0ZFws_4P9m7yW037_BJd--_klGFrlvR-tTmdu3mGWfRzbnt__0XYR-szP__iNGEV_Z-b1__a0
yD_EyP__JxRlWVzy0EfC_wCzmHl-em7WlxKx2g3Y_ldF1Y3jd_-j0r2Ve2_id__ABl_vZmTWL_zjTV_z3V_n0F3_FfluhwX__lC1w5Vxvx_6bVxr_-GS_zP_
zHMkzE_wRxAR_yx_8_ed9-p_y5zVv-xzV_vhyF-W_ttqJ_Z_9_lwhxVPsx_xlzvdM__yroDSxtziwh-UmlCVxr9R-f-CxVppNy-oilzUQmUWRwn_SktplsNy
_yEb_ci___LTxE3V-ryYHsFKPnW1_T40Z7F6VtBN-v-g6_zFY4ozT7Bf0gWJ_Kzwsd_V-ujf-pDZK8a0RFVHL0J6_z0lbGh0Xjz_G6zFCNRy_Wjs6l_9MEpK
900h_xD7hSx7xW5O-PzTopCt2WAChVHF-Zdw_yN6Qy1H4SwmNw-FS03Qc_HAiRNzEVvx1w1Na0FqJrvR1g32x2f_wf_ijmYi5TZK_VI_xJcWy8Z-V0AY-kdF
1o2hd_zy0gBswPzKYgXz-lC9657x_ESJ4DtmfN_ogXJ9_Jx-9vMZvoQV_aabwQcJFlsJkXB-9wyw5VgL0FyIGFyT4G3_e1-tweVnnuj-uqy__HTj0SBuWtvS
s_um_ZX9Fum_Z3_e1_-W7_o3Vl0F-i4_wCUrl_l1-6D__J3-CFum_Z3-CFum_Z3-CFum_Z3-CFum_Z3-U1sl7yOVz8D_q0_-GJzU6_g7yOUN_S3um_Z3uW_6
7_I3Vz0FdtY2yOVn1_tG_Z3-e9_-U_p3-CFuWtxGJ__D_l6wL3-CF-YdtzVTwV_9yGVzQByailBFw-T-4Xd-l7_o9tVgPtzofNxs9prmwW_ufp-OW8-0VlJs
MGBsy_eD_oHWF--V_ia8sdzUFqQRv2hWjOj--biFo8_xL_wJ7kZzk7xw9m7vUVtqJmBcyp_wqpy9dEJpuq__vD4nfv__l7xwdm_0tVhvhmtqqxzj0Rmg1Vzj
0VyLWFw0_qtryrzhwaVRlW0g0lrv__JpNsduRq7_5O7-l7_w-QzTuB_evvz-_e_Jp_z8-Ay0_CSMWFJpxmTV_kddl_Q3V_fT_-b-_Wq__-ppJp__OVleF-QV
VlV_iE_-F_hv9z_z_-nx_YU_suV-C_vVHj_pt-pph_Yz_uDx_fM-zt_jxbu0-cF-AmRwTuz_aUxzlsSW0FGB0Fq2qEjY163KKU3oyaU_Mp_6vVfnkttSll33
xSEFwsSV9X_S_pz_RmyE2000G100_N_TZLGW400000000000000000000000000000000000000007
}

