sprite $cloud_functions [512x512/16z] {
xC514G00100myDU_hHvkstu5000000000000000000000000003CaKi7DG30G0p3ffe_vw6uLyeWgkFzMpeVxVjvxVjftry6G1l0A0EW3M2K0T06CCe0Q0CO
PG2q0Omo0De0HXa0RG2Z380sW546G1l0A0EW3M2K0T06CCe0Q0COPG2q0Omo0De0HXa0RG2Z380sWBNxQGDOkvysWBNxQGDOkvysWBNxQGDOkvysWBNxQGDO
kvysWBNxQGDOkvysWBNxQGDOkvysWBNxQGDOkvysWBNxQGDOkvysWBNxQGDOkvysWBNxQGDOkvysWBNxQGDOkvysWBNxQGDOkz_5slSJl_-pImS200003CBy
hGDf2Eq7O7u2uXb8fo2SWsmIebb8fY6OXrmYOfb8fIAKYqmo8jb8f2EGZpn2uXX9eoICaonIebX9eYNeuoM7c1XcKgW9uMP-SkPdPtvwvkTdVeBcPsX-YkRd
Q7wIvcTf_g6c-NcQ_ovgVgRl-HqWzku4DM9UYODuIAlTkl-97ylxTW5MGMSKKNK0OVpxPyzuvE_e2d_vULVuoy-xmbz-tXN-ylEky9UVTuM__Bmh_ENdNU4l
F-yAV_bvL_ZBpxl2NtxU5VxoywxmbvztXR_yl2lyvUTTuIy_xmf_-NbN-ClFky9VVjwb_gdios9Sw9ybxDjgNEUVyxM_LOtB_7Dk-Ei_QrpbdtFBN_zPuoB_
d9l--iyQr_ZdtFRNVzQun3ydyDT_rhZ2FoVort_MkC0_9_3N7mpWIF-Sm5z_C80Z_NCIV_t104xqpudyzGS3ED0_9_FN7mpWFF-Sq5z_C83Z_7DIV_t104xp
pudzzGS3ECm_9_VNdmsWtv_pSt_zPuq3_04_zDSV3A3R7_1JV_t10Bhz0J_rrnyEeD-Vyp-wlkq10pZ7FvVwptj__Ta0-lqv_vQ__ii5rFW5_hdKt_BN7moW
tv_p0t_zLmkeSRX_hlI1l_vW0Bt-b9_vwxzUG8s3_NEX3_pr1mDezsVyt5__zG9gVCP_RF0lz86__d00eyKVydD__TSBg76WVoxqeR_-O03z_fYV--k_Na2D
m_npeO_zzIS3wFVd_DnV__K2QXpadojzxgy_6q2_F-Vd_lgl5r3Z4FzSwtD__Ua0-lqvF_VNVxs06WVuvmjzuAy_642lF-27_lg_N42D3_ld2ttWhpyOGBS_
u8V--hzUG8qF-kU6Fl3N7moWpn_mGt_zDnPGuqF-kQ4F_FK70-Zq1_pGN_-j1TJuW7zkw0D__S40Ulq1F_JNVtC1DNxOFpVqWR_-O03T_e0V-kk_lO0QF-YV
G1_uwmy6qESF-A6__c01DNx8Fu4-yDSV3A3J7_13V_tH0cf4lty2VU2lFnf0fp_WX_xwmmNKQFPFe0_yzSS3wFC7_CnVVrpLQFHFeC_yzUS3wF87_DHVVrwD
9lzyGDXVVpw0SSn5SN_zUNc3l_uy_SzBVzFVz3VzJN_Jt_Gt_Kt_ozFVz3VzJN_Jt_Gt_Kr_qz_qNzVplcPd7Qh_kfRtjlkAV_G5ZjYyLFrHuEqDppnKVr3B
-rj-nxBlbhT7qF-F63-uhKSUgZ-vfmrMqN_enlSM-ZD-QlKL0QmwBbL_Va_v09eF1TzPw0y-KAdLAOVgpsygj_ejXpxwHmVLTxpe6tn70IvLVtfJ-G1-ow7w
HmTLlApbKFrleDAVrt1JWt_rvzy1z5-g_XrKqK4Ld_JNF_I_q3_qv-c_xYjUz_NPIzN_VIs71ZvKV_trrrz__VNNNt_zzVVdF_tz_O_-5r3f3_BlF_hxzr_z
_VyF_Vt_B_tz_q_z_Vzl_NtzX_w-_aj_N_-flw__rj_dF-Zlyr_qz_bF-llyD_rz_gF-FlzL_olIt_Gt_Kr_qz_qD_rDVzFVz3Vzxqn_qz_qD_rDVzFVz3Vz
JV-Jqt_ax_3NFxF5FxBEzzU_Cfhy8-jqV_qheyq_SjRH_lfNHfi_603nDwu_Crhz8-UiTd_zEN-ZFnW0yJUgFpFQ_IFdd7MQl_xr9t-RFnr0lx_-DV_ax_QF
d601ZVxwrv_ydVve0Ft--jVyax_V_yy1pEhnDyRVxWy6GFnjNtzczFl_Tm2p6lmDyVVxWm4GVzlHN_1t-Iy7CAl1Nt_0t-uF1a3yRKD_mT_elnx0h0P__G5_
hpyO0F6t3Vq5Vw__UW2p6lpr1_oD_c00nDzUwg_v-_tN0vZLuAy_uE_o1mCW_lPMVsPyt3zoBXV0_Gtnz_k30H1_UwS_CuxmZvoB1N1_G_pz_c00nD_UwC-C
O_mZvs81rD_Uy3_n0Nyu0Ewl_rf_Fd6KV-HSB83v6-Vlz-S3q9NxrzpWx_BV6i0iwc-Glz-V3u3xwrzpWx_DFs9t0BEul_wSFqQBFny0zzU_vZP_H8i_6S2i
VNyZ_Ft-S03SN_-QWB_B7mvWrgQ_4Vv-Vpu0ugz_JS3VwCy7C6l7to1_lpyVm9w__ZK1Vxi_7y2ir_x6-Vlz-G1qVLjDmD_k3mQ0_Aq0_r7-aPFxMm7-i_mZ
kRyLu3_CFnBxMm7-q_mZgRyLu3_EFnBwMm7-y_mZcRyLu3_GFnBvMm7-4_qZYRyLu3_IFnBuMm7-C_qZWR_-WFzG_qZkh_yJlzu_alhh_yG5_f7CN_ydhl2F
9FxwFt69V-I-l_vFNECVkUkl_nCN-KVk-Ul_n5N-aJl--ZzncN_aQt-h9wxpZzJrRHaN-DEhieWB_1q0BIxmTm2ukC3V0U3Y0dy7W8iB_1q0BYxmTm2ukC3V
0U3Y0dy7W8iB_1q0BYxmTm2ukC3V0U3Y0dy7W8iB_1q0BYxmTm2ukC3V0U3Y0dy7W8iB_1q0BcxsvzSf__t-8N_SuC-J_zVu_uzTEf0100006EHlVP2dq1BW
Yoe0KW6Ee0BW502c02W502d0W540Y08W502W00C-0U09W4u0S09W4m2Q0CW402O0BW5W2O1A0502O180aW2811W02O1703W2e140Z01O180Y0181W0YmvH00
XW0e100X00O180WGEtGW0000m3088N_RWtm8TLoGNW7dVF9Vyyb_pIV_DP_yrtpoN_F9Vyqd_pMV_DTyyb_poN_D9_yrd_pNVF9Vyyb_pIV_DP_yrtpoN_F9
Vyqd_pMV_DTyyb_poN_D9_yrd_pNVF9Vyyb_pIV_DP_yrtpoN_F9Vyqd_pMV_DTyyb_poN_D9_yrd_pNVF9Vyyb_pIV_DP_yrtpoN_F9ptU0jGS7CW000023
_AtlyLLN000000000000000000000000001
}

