sprite $cloud_optimization_ai_ [512x512/16z] {
xDUn0K1G44H1a5__tP9B0FWxqyA-WteO000000000000000000000000000000000030k59XRAy1uoSbG3Sk5E3q5M1-1LXV0TONWFa32Z2_0Fpq2S3n1mN0
C0O7m3Jk9m3NBm0lVm6ONm0pUtUp7QUkn56y5oMeckdzd_P-ZtpKruYISlGNUuzDeiMlX6FY1k4wLFSR0EeKVOi__ea3v8C_SOnyy2UEqW___77wmTz_vAVg
Xt_cK94eRxYbF_x9etMYaWHKzgUyNtdj0E3F1G3-MhVonx_KdhW0yEd-ZVpnF_1d-tU6F_vR303-dpVvqo0uJN-AD_jJpF8_8-hoeJ_DlqIiFW7ej_m_m_nN
dW3oQFlNeVvHbupYV_aW_s8_YbXu0j0VxMzV_SFhWi4___g_v2M0FFwqVzGLO_FF_VbFO0BWdtV_Py4188-VbJd-Lwmt01H_xVnJ_b7gSi4Vrn1_-vb7exfQ
y8VF-VsF28K1W3zYYd-9nGQ0OgA__UmCZG60FyuPl__jeJ40y8Vd_G_xMOJ60C0VCU7pNoKa1W3-zZU08yblLwWC0FpXup__6w4o0F1737_-mnaw0m1_NAEV
_-BnIrvN2Vxs1U18y9VujQik4_nnDX2Vyvl7xzLrmZ-iqV6KlqH83G3ySJKTd_6RXzO0m1zHhDKZ_ZD2R03W3xV-9_bQkxXRgNCZZzkTrgwR_uhRxN1MlIvS
T6JVwdjFR8cEjjbG-lpXzhsEbmL5JrwLKfjbJ_d_xEOxGgChLVrsojj_tFiVTno0k9aoVoqZ-7SS08_xIVeFVl-px-KVVSdorsgvFec_N5A_dTerQzGhm9-T
DG5-cGd80nmP_lq6mEDPUlpfxm6FLo2m-VK68B7G1Fzc0n29D5RkjL5MFxy8VVu8vViLrbbo5GByMWFWsIKUrb7w51O1Vga16B30ajBFBqIVFqA5lrsdVZjL
_ok41s3OuhBwjRhe0CIO5lxkVzLR9V25Bm0nADVR_lcNk-WFG0nhsTLBB4VVFrxFN_Nk0SN8rFov0CJGvFdplTe_5bozouoaFdzKDjkh_ODJxKB-WR_0gfJy
Wuyf-BlzsMWo_h6z_xAdTLl_m7-LXU5Vy4_pz_jpbj_iN_1FB4tVFzRVPFZZppU0qFPtHN_yzKyn_lZdL-VR-hk4FnU0qBu0h7k2ySVVt-tF1iF_Q_ZZZx_Z
docn2kOJ_-bTh_R7l-AV2N_k_-7F_N_yySSVV_p7Xp_--EClnuy__kbbu5_nnt-1kp_uy_bV_FK707_yNSWVVrVQ_lYFJsRxuy_p__0VtxlzyNSbVlp7j-oZ
F_3d-V_uy_uF_7d_3_wy_mj_tl-7F-__n7zyBiEFF-__ndzyKlpuZy-L-F4VdnG__kCh0hTzy9-PmEx7VsO2-lXFJO0V_wa9wEC_CrzP7t_UNuB__EOl7V_L
cxjk_1LQSiduK_mtz-iinVvJAUVb_Xf__A_J6ftN_lxaLx6lbSitzYUxrPx-TDZDZltygLX7PJD_iivsygTYtPLj_CaUzMf_-CrUxG-_cRu_MIfnVx9aqlva
wOJzwMFfFhh-P0FQs1_-Er-pep_yZxzKtv-RldtJKhRoP_id3f3tXpznZBm__8d3bFpfgUF6_l0dZfJofmJYflxmfmvMygUSeBe_9G4tz8TVO03I_eG_VV9w
zfS-AlvaC_nDnPz6sE6VRSvoyTTx08mKV_vFmN_Yel5VlcZq6d_y__QNl0w2m_zHSz_oYxyeVyGB_F7ttChnTst_v2jVyAyy_tbJV_oz_edABF-oWdzD9B1u
_5tOFzB-NF_hk_tnzsql_-7uvywYQ_i7_jbxQFlxury4-V6VFm0LVut__yqdnO__-BJqyH-VZdxUdz__R2U4Zp_5R_7v3_pv_1V-VFuJV_pnv_aF-FFy5_nv
_XF-FFyDVvx_YF--pt_5d-S_uy_pt_5VylqFPJO__hp_1N_U_uG_xt_3d_S_ui_xN_7d_S_uy_vt_EUapOz_ldVhur_VpOz_VJS__hLOTwLAXd-xTsz-_6kH
tlpuvpliPaSL3_zsufT-_FFvLUnhvVAwTVX7H5odDJgln0A5mZyYtA-p5FjFfPoNEs_NMykVfslxMv__Wly2YyD_oINwrlxun-zjwuz_t6jBV_pZVjlvunzz
xUMFVtItZp_-yQHT_F6FP-tXZtyyRWD__2EHl3_-aKhS7_z89ksFVwGJziS_yhciF_uneYBgZt-CITCVVuz1IVhZ7yCIzCS_tkoFVupitVxuXvW__e4__eiD
0FwQ_FZZxqB--CVutkkFF_xuXum__e4__lZZFpGHVnReh_PdWJ4s_F777tz_yUd5dzEBVpxyv-UlzcU1WJ_-h_I_NksFV-piZxylliB0VsxuVmr__F4lhnvF
_0D__8LMn_q__FNl_pC0-ECV-2_XpzfcyxF7rlN7dwMLRVqh_dUA6Ndb0f3QSrNRl-8li33y7V-gx9y_pypb37uP_s0iyHTO5S__aRdIub-5_AEofctzVRqB
W0lxv_dPR25mJShbOlwXl22U_vs_seQ0Fy__N-by5_jlYlpjtk6VNxCrchGQtl-ps01OewuPk1O-XPlorr7_PZtibyguMTGTWAlMBIy0TginPxWA3q1LzOzU
_NR2_BLkoLyzktRhgdvBu1nko9y_yTQPAdz-0AgsVtpNpq-0Qvp4t6tV_GR07fLQWke0r6KhSRSyV_jdGQ6pkCtkpv_-ZpskgFBNkidcpmDOgcTdjAxG9ln9
0Kicor-hidwx_kzanRBr_zL5yNoLAf1t3u2bExgtak2EyQfGluCDw4Zmy-cPmKLNDw_jzl_plV_lh2hLPU4TDtU6-MkTjwfMT5HkuDyP0Jt-TbBq-G6uRkZV
ce1p7N_ok5il__TxXRxE_LEAcvtT-jyl0NAxdm7mVlxlTumkDNu6eDpWl_yheYlTGwEds__vfmDEhUtFlm7BO_xs5M0bVdgq_LCV3xgK-1c0iyMV6W0bVWQW
nPyR0DVXPm2khFzXFpjr-1c0qk3FNW0MuwU-otzw05o5dm7m1d_Q_rJXPm3EXdz-05Ju6O3IuC_xg_1p9z2c-Bi6FmFWhS_nv0VWMf2VhXi__TSX_kUI_FId
_8l6h_im0ESSVzFO_0n0cUI_B3_TyCyFmBhyz2VyDVGP09laxolpqtJ_nVLfylL_TNwQwx--Fity-Kz1dsRU__6wVcIp_EkRmxzAH9QMmnz_K_Kd_F5Fq0dp
4_vaURpZrVvS06mhV_pjtVpu5_ov02GE_rJfyBVaqM-90R0j_V6tr_3JyLZH1FmfnxW_Frcxp57wuM-fO_HZ02nnW51aNQ1cM_hZtwxdIpKZIzVc_sTxTM04
40n5GH3qNxCQ0BZT3ZAND_yZYESddfzuV-JVpGTOllzyukCddfzwVkAdd_hugTUddfzwVFBr4P_dsmC0000000000000000000000000000000000Am
}

