sprite $stream_suite [512x512/16z] {
xTsvUUH038L1fp-2tkIVxPhhx24Hke1NbSBVQ0sXELxl1m00000000000000000000000000000000000000000000000000000000000000SD-lPFBVoIT0
_k03m7Kx0CRV2P0_yW38xmJexm38xmJ87tK0k1q0-Pq0-ICFWCMV4s3y7G3vuqu0zPVc3e3nTm3aTmBaTm3qh_W1c6Nn-Cill_xzsxf2Rt_ZR_pbbx_S_hlp
6t_ZBx_yyikllyMV_CPVVlaz-htPPVm7CFxooo__QTp-_lWRV-Cll_poow-__lBBBx_y5dyU_Oo_yPT_9laj_Zpw6VyZl_5VHdxvIt-FVe7vZR_yybyMVrxx
6t_aP-7Y3-EF_CYF_iYF_8nR_67yaH_vqH_vaH_zaH_viVZ3-2C_ygC_yYC_-YC_ycFnX_57VkH7V-HF_P8t-NtBbr_rBVcD__R-yijlyIU_yTTVVldbbr__
ojZyo6_yvPVVuaz-u-_h_UMt-DlLNtwtl_nkV_tbbrz_l-iflz_rbD_jR_4dl_7tw2U_lQ_5dzjV_grAVez-yhlz0_lBV-J_Euz-yijlyIU_yRVvoSYFnHzk
V-IdMlan_iYF_EYF_7ZjZyKVRd_annz_Z3_o8p_w8pzU-sFnXziV-V777-EF_CYF_iYF_5ZyOVoH7ui_N_JYQtxazoLlyiklV-d_TyPVVldbhwpy5d_6t_ZB
Bx_y5d_7ev_ntyFjBx_yyb_w6t_vvPTV_kw3Jzdx6d_ZBx_y5d_o6t_zvPTVVldzsqT--VLt-yjlyIU_yV_vBldT_kDP_CdljR_yRd_zvPV_w6_yvKT-BFum
_iZFtiKVnX_vaH_zaH_viVZ3-2C_rNWFmIV2-2C_ygC_yYC_5dyOV-J7uW_ZZ_p8Z_x8Z_nO_67ygT-JBBynFnP_hdZZBxxylhzOVgEll_hooo-_-XP_yayS
Vqh-1iDlyIU_F_xoZxhzaPyxiJ_o8x_yNllBR_nj_UGt_XP_yllZBx_hNtyNWFmk0A_zNG36tmKWlmj0VnU0J_au0CPVV_trbt_W0K1_7iIiDO-0F1pb9HS0
JplkwC_pZ0lwKusAamy0_OPdV7zQ2SVtfrTmSd_qfnbmTdzEC-3w3Q3nFoyNWEjV_mRzqH_zqH_zqNy4_Kl_5li_xF_n_x-PzA-L_V7-7-v6mtjyV-hvT_bL
q0U0VFwZyy41VFvhFX__zRF_Fl-zvIkWyFb_z2StF_fpiliZlmiWk3_X-T5V_-3y1ET7VyBp4vuV_VKFpazuViBp4vwVoiwF_6w0wFo4voSyF-dr2SzFgUy4
HESdlJxX7_B55_nn6hyEimC_yze7000000000000000000000000000000000000000000000000000000000000VW4
}

