sprite $apigee_api_platform [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000001cxmwoazU180fFHAjdjV_Tlj6Rve1_MRVKwbe017_N3e4Sk6OHeRBBd09cllXhGqTlv1-RBV_b
TE3ospNzL_lecCtyUOt_pORiD_Bfslwh-P_uppSR_viTYTy9nBh9RhbkghXFBDv1ftvV1EADoMJvnbh_YnsWtmN4cpFNxmBYxHdhTm6nOwRwNK3icgD-5n3x
PiVV0SJUMUbt0R5z4z3VjcX-dqj04cj-axU7Hp9hVOjBG79hVZw09DVyyE-0aUnQ7xq49BxP_5m0wR3cfm98ZpK_4q2whFc90D9dpRy_W7HQy-yE8BtM_5jV
21ZfjkRV6C18lpN_jW16EgxvDmKmqdFDloM0aQvh_Wq1ZFHTyxyUm4ZdDV_B0OpqNlE_-q9Gcc-s_vi1fFsQ_yK0ye0Lud-lAmF-rswv0FzyFI-I_-qxEDj_
xcaCujznB-Asws-p3G5mCFFO07QIR0uWjwAS6S3c2_BS6C3sFylpNnR7-HF5nIx-_Nzj7iRlVisXBiR0dG8KW_iOoVVvfqG4S10_-hJZRNxi_qnFuVT_uh50
doZW37-93i2TNph2VuC-4e33Mx7pW000_bK57F0CdFS7-8400FuQ0Qpbfm9Opq_-3h3cdv9Z03p_mXQD_OVPLugymCy7uCj_malGTl-36RO1B3ZxyG3i-IN0
7pZzgG00_Y81BE7d0x3dbopzFslu-G1My_C1JCFJNx8DO3K_7u2VlsGSW3s_1FW3_5G0zloQG020FnK0oCzV07X-FW1tVidhfrhApmSmr_Bp0LpgBv3Vtxy-
lxILFxLpHc763nlQEe3_lWk0ytToLkMNR7wsOSmlVVZV_Nm0m-Rq1m9W-UjV0BpvfKzDVitsNn00m0zS06xcb-YdVhn_NkqlafyFeFrbmD_-0aVoym6qlzYd
Vhm_pp-5ZkJd_PFt5poIdm-W_SNojpy-yAbV-yjW63yVWFhqbqJny_uXgVq5yVF-4_Vt6CFF-oViBvULufVQ_zUX_EtF3-LlVtueV_lpG_dRdzzc_lQNsHBW
R_y2_BO1jF_sx_9f_m3y0VuAJm1d-o_W1m9eVuY_uWj0xPzB9c3j3_Fp0RG_pyy7qB__UVvCgVt7MVwvT6Szfj6l_-JY2LY__WVmCm7q-tyyFnz0-_FyV03j
p_Fp0RG_pyy7qFuyFnz0-_FyV03Z5Fz0-Si6aEsFysVUwp_z_NF3hlMNlNzkcQ3rvt-0_7m0sVu0Fn10-vlpPxQ_NG2PjGEO1Z-SiNzkNd_-gvL_Rb_x6mMG
m6mUOVidillyFvwV09tGF1_Yr6KNWCJcUVfVvf_W-lk_y00ItMNV_pVj_1EUtUa_TTC58F6vdlwy_-S6_ip-_c_i0f0MitgOK_S4a2QpFFth-wVDW8T9-_C1
fD5i7kVKBG6arJnFVzu_lFdz0qWtVrduPzuHmB3Wjxi0fE4kEVqLV01fEVw1JbqHG9eEVw2oz0-QVzle1ohF03w-_8jlxWf-nSypuzzmoyG3bNi0FF_yuQts
HoFvZVt3WN_BdN0FLDO1qFn3Fspays7ytlv1ya_zl4a6G7Nd7S22Kt_BHQ0-lm880D1W0a2Yimy0eL0-Mdb-nUu0rlpUt_Ky02YkTW3WGSad0_Wh1y0Uatmm
XD_VFqW0_m0IyFSFOENVVFl-5aJu_Vt3uCMmFJIx-ASA183pypy6y7eJ4i17lypcV9ZvyshpQwmAWEVd0yY76-8MhmS0d0xCJmEytOG6mFDZ0V3yV001ymC1
LEJNYAS3-Qa0rlCFqOl7W_WD0qZYzES309_vyty5yFny00m_7m3Fxny0UpXMWp7y_W60_7m0F3yV0CZF1y3pym40R_YYRmVp_Fu1-1-FVB3A_1hnU1G_7q0-
tb2X001-A02Utp-0hEkV3Bz_000_4m3Cxn_0EVy0D_F9K7x_08xwGkP7O_Zz0m3ucG0mVly0yWR_PFZzNmW2-9a0a9Tz_0F8M_m9Vly0vdbNn47m-syhVmeS
mk-_D_ZRN-SCu6V6yFjlDN_xwwpjuXz2Do1-_-tXJy6Z-FstZh_zTU80Vc0Ol__MyBU_JjqA_lRNkNkRVmhVRFxd0Sm2nuRazz-_yRU_Jj-_yBU_pjzp_lPN
XJtbRt_LM6b-YURttnF-zbUT_SxV_ggqN_dRNxNs6t_xgzf-uMz_rTlt_EslYlkMl_rLSz_njx-gxXl-zbVThUMVijXi_bMdIllFk9Y_h_yp8gxbR_yPKJU0
RF-l-2Ekv6__6V_lGlxsdn5r0yZs_u4_uZB-zfyHTGF8zl-HF-8Y_lQV4NK3oFP_m1_H_600F7_45VpjFoFg1f3j_vW_eZn_-y_uQyNvst_6tsl-qf__C2DE
3g0_6-Lj_eYo_Eq_uviLvM__6T-j-S40UFw8WlpjF-FxDN-vpt-UySkQt_82i8i_eXH_-y_uTSqF1i3pHvJXR_yPJzRyHRx_RSQpDN-Dxt-CfolDhrly5MK3
6FbuDtt_SppUgCf_qVU_4m7uymC1CFnO0FxyKZxPFESVFoGg07_-vm4SS_fBH03-_40033ySW3-_LDTV8WBmvmS2OFZh1h207mW0u5yKG1d-LJSttAzs4X20
E_zSTuFcZrSY0l3dnmBW-Va0U7uW09oV3y2VNx9z6N2kuUS3u9_wKG7m_7m0FF_wc_Pym5BT0CP2VZu0wcSwztMW1Vn001J_-W0EvP_0uJRcbpv002W_7W30
Nos0iO8V-2i0VEQ_Fe0XR0luWG1O_lK1dCQVmCjjFupxCUAi06O-6t3aAVxI0MpWjtaxUEnve1lyOVwvxRxenohL3c0zFm_0tplW3_0J_svBtpKV0CyFt27p
B5Sg7i1-ZTm3mTyhvy_phwT8v2wh1_2O7z38iVcjRGa8e3w_jFDpmcTY_Fu1CFpIhey96lby4XE0EpyTG2Pm9pK3mFYbjxymOhfy61NXxyylvO9jkENA0P3y
KgxSwfjRkO-fF_rcRDfEQnU_pjDVgtS9lsJfF-cZ8Xdprm-0FohI9VpIyVvwPvRyV01s_5EN120B_t3prskpvAz_0PWcXqLovAyVWCrXaUxWbzhVF03Tup-D
Zelanby_0BDFOxc2Nvyp_RLXD_1BDlxJxC18FBzP0FEcqryIpd_J1S3lo4WNy4ljxnY0BlEVbiT6zVaru-jzBZlz9P7y_XU0-luousz_RLvrVgdzhGBGXVxE
XqS0lwb_69p-m4X-Fe3sbmj_-qyXC-5lVq6hp2_H_lv7I02_eV-yrby0lvz_tEildh_zHOxavmDeV-7yxS-Evcz_U31_-zDZ-TiV7yZV_Z9OHNwf_R40TBt_
EEfGYUFd_GVwpx_o6CdFFm5eVotbR__ZZfPG_lRdX_AtFp-Klt__yqFvsv_VAlxsrv67J2X_l_x73-LlVtvx-Tj_5k6V4UBMx__o_600xS_pWm6qFyyF1j3-
F3yNGFlp_C-FPllFKlmHf_47_UbljVWZ9AdzW_7d-IFQ7tm2mFD77EMF7z8em0y4q9__isnp0JyGGFlJ_2kEQllFQlny0FEe3u0im0y4q9__oZxrMtLastyM
u0S2wCz_H_dH0DhVdp_YQd__0ERB_F4foS_xy_nB0sZ_hCFF1n0c_eFsv_aZFjR-GxTU0783F_CayCplVnur-Fa0Hlmmeqji3Nu-0AUVB4q3c5lv8mhpy_x-
_16c_bu7sfu_u_4i-SFizwmxluG5mFFp_Zm_5W3lpmV0ymC10FoWVrhpsmSGlytnQclClpO0dlyZmml0jEMt3o1-d1pzSvhosmSGlqwU0GnBVli0XYc_yjSv
yWC1KAS_7y2muryOmCVZx0_hzzhiFjVF_0emu-V9EO1fnMyVG5ZpAn_CYDy-08S6WG00VY200lnADe3v3hyK3WM4lx-IB20NyDi6mDRtCW7Fxnu06jy61FlF
ym-o02wzRGw3-isV-OC1ybhGWFdzlrOXt-UN0he447VAM9X_bqyG1SHX_8eD6D0tUSM_RQxMv_tNYyoj-hcEOpr9X0t_LfIXxpPpCxyKiIk14HG_7q3ct86V
kUQ2l9vcHXpChrmpos_mZaLxpvxtLwxR_EE60NufLkwrMnQxF61wk3XWebUNNmhx2T-iooyTxzyNWF7g2_BDBxdprmr07lFchnk0NERCNpS0-SoNlsu0Sfeh
Vzq0v3LF_he1o6rr-QLn77y7eAKxZBy3qE8TnTy1QFaEuky0fC81o7U5-QL3-3i0gN00yjwioo_vy_SbOEZ53NFz3a0lpvg_0z3hy-Nl0eOsR9ZgTm3QD9xV
Vr6NNvfs_7q9qDPvwNS1sZuZ_Gv0m5pukm11Sz3l0WIErky218_Kxm9aC4g_2v39MXzuOtZAQB5u7rLShflijktKxul0bELsw7S2KyPx5xz_4GpPRxGz_0rI
_3vhyJi27RYcN_6COEZeZP_bEmQLNPF_rnuS20000008yhSUv6e50000000000000000000000000002
}

