sprite $video_intelligence_api [512x512/16z] {
xTt7kHin48J12pY3c_AFLjwSQ3ujA3sWgrBusNJhFdqu00000000000000000000000000000000000000000000000000000000000000000000zTy00000
m7X1dGy00020hgC0_WO6W9xlK7jWFgA__FgFa-lhR_pwgw-__FhBhxyV_VeRl_xoww--_lBhhxx-VMX-_QrV_tw1-lOl_uxz6JEuF_CI_UNNtz4U_TluxL_-
fywSgVhsVvFV-xyV_K_4pjJuxL_-w_t7PNxqsx_nwo-__khhBtz2VthgV-rluDioU-MtV-_z-dllrxyNsMVy-_Td7j6_rrBV_kNVf_zOpHU_9-pV-FMNNt_r
zPTVV_drLr__lYebl_rR__N-5mwdgn-m_wwrvFV-xmzV_OrVV_drLrz_-VLNNt_vzPTVV_NNzqT_z4T_z7SDZ_sxbv_-3w0_CrBzH6v-z2StF_eZVnRzH_r1
zlp9pO_-vEP7VtBpep-v-T6VtFpeZ_oFz4lqt_N03zdp9pS_-fER7_t9pO_-_WIOs-Z2zP_eZ_xeZ_xeZ_xeZ_xe_nxZ9RKD_T5VV_q3xYohF_fVTNj9VJ3w
ep_wNzUdERy_ze_-w8_-w8_-wEzF0FqtOV_eZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_x1zu7N7_tHtxq_z5zlr4UcF_gZF_gxzw_-p0o5vt-YFvx_ZVvX
z9-5_c-WlnT0ruxqPmPnpfV-eVJt0j1_L2pzlG7eFmlzO-a_2_rZwJyB_MFfFmlzO-a_2_rZwJyB_MFfFmlzO-a_wolq9w8P-gC_-gC_-eywalxeZ_xZcJgM
_kZVprGw-wV3-nFUd_J-XFSdl3_X_HdX_GdlJtf_DkY_zs6WlgpUAdp_z77z-ntgNE7x9xm_7TwVyFw4zqV_rSOQzQ-4zoUyFoEyF-7zEQR_MAJIXE-VG_ht
4XKeVV-4zoUyFwt_NplZp9Fm_kZ_Dbqx2Ey_Abxu_Wdlxusbm_kpT__Bntr8tpyxzr_mhmlX-oUzF-7zqN-1hdsbzoUyF-7zIUzFU7_2-zFX_GdlJtf_mliJ
tf_q_eJt9xm_7TwVyFwazuy_bxp3zqzuVzUH7jaV00008F4k0W3SNb3N00000Fxu1G000000000000000000000000000000000000000000000000000000
00000000000000000Bu
}

