sprite $anthos_config_management [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000002OFRisi2060XWQB6RklzfZ1dq8PKqBJvu5tptBo-mlC-QQPbtUPd-ROymr7VrF_qbtGFml
_jCMaFwB_rm5f0_--jU0-C7VlmBI1tzz0Uc3lxo0Pbt8N_yQqE47V_qAI1_yzGMaJ_xs0j97Vtq0yRE_lO3qsTzUGFhiBoyWVVRN1n0_-ziBI9_zrGNqi_Ts
VziluGu_--jNGFhixoyWVVRt5v0--_i3Y9_z_GMap_x-0j9dVty1wRE_Fu3usTzVGFhixoyWVVRt_nAEd_tzAo1zzlSNaFww7xkuW6vvURRpQQ00ysj0Xtyx
pfSvZWbNGAl_JHzMWBU0zFSNU6q1wJF_-Mlc2I3-vVmzOv-aWFJ7-Cj_Q0f8d_d_yn_x10Ma_x-_VmMq-i5VNq3wv6yleDMF_X20v9TmXv_zvIiWVVQt5v0-
-piBw9PtMSSD_kBNW0u_-yjNGFhiRoyW_Tlzn-4jmA-_ZflyxIkWmy_-_WBIPtz_0Ucpl_ar87xsbw-0zDdVNa3wx2yee9-zm7-pl_6NS8UV_Vqh8Fr7TkuW
sNKQ2e0eG7ZMJFlVBSCmpAicLzLstp60IgVjrFzA1Fm51QGF_CK5zFKkvkyFe8UV-_iBI9_x-mj8d_kR_aguKrxkBtu5zF1pVtC1wND_VG7fp_llI_1Nml43
VyKh87tkRouWVUvlAg1JtZb_nSbm3p_t5xy2qkV-vWBIv_x-0ZhbvVx-07hukR-_WFIvlx-0zBc_w6IuKrxkxty5zF1pVty1wNF_2k3pEglF_HKdmptyt5_y
2aYV-viBI9_x2mhebDVYtydmbFwy_tm1wGly1GMa3_mhOF2KL-jV00FwW_uLCA-lzQ-00Nsl_xxk7W0_vNNvpxy2Ris_jy0Vpeq3mFe6Vpvt3M16t--_hri6
y68V_29_FdVqPm-_rt--WBiz_dkUNr20pD_yy1S07z73BoX0vo_IznTm2Vm5-ju2xk4_hoy8GEglUFW51LZz3Vg20hJ-5dr_0Nx_rpb-Vm1-_nFwXWBK_W9z
GG5UVu6-881Bwo_uu5SKS6T_WRwW086_G5zGWCfVe2yA87_EBouWVwxlBI1_hgyj87_ERmuWVwxlBI1_hgyj87-kBmuWVyulBY1_hkyj87-khoqWVwul3Y1_
pYyk87-kxoqWVwwlBI1_pcyE87-kxoqWVwxlBI1_hgyj87_ERmuWVwulBo1_hkyl87-kxmyWVyxlBo1_hkyl87z-VvEnWFov_lxFk0B8d_FlzyWAo9_hkq-6
y-UlVcy1-ND-Um3v0qFmBqyMaF_ydRthu0pwvpy_H_tpv_ns__pppty_qJ___FFFF_zzD__yyyy___pppp___FFFlp__vPz__lddt_bF_lddt_S_yk_xN_al
ok_sptz1Vhb__elns_tpN_xR0VDdXaJVxv__0lfc__pV0_G5_lc3yVZddt_--UUVV_xvvvz__ldddt_--UUVV_xvvvz__Xn7xfy_br7xvyzXtFxvSnQrV_vS
vH7--G__h_BFF__k_yW___pppp___FFFF__yyyy___pppp___FFFF__yyyy___pppp___FFFF__y-GpylwX__dt_B_--_vr_l__8VyXb6Vtpx_T_-NEQjQJ-
-NCSyVqF-NV_H_xvvvz__ldddt_--UUVV_xvvvz__ldddt_-dF8U_la3npluvqyK_VxvCqEzV_wCqEwVFnIK--TF0Tt--ME_v_ht-x_yyz_FzSy___ptb_pp
pp___FFl_e_ybzb_GV_ybzj_4V_yrnBuW-Nb3xPtt9ylC7--kVF-yolCVo-jFrzZ_cjP_VagyrzBwy_NcVzo-A_VJlvaM_t-Q-K_jQdp_7on-IyuXhkYyp_A
V_wkwFpFwf-_Aph_i_hdxuhE_wp--RkYyn_Yv_ETrUR_szzIMNx__Ub2y__j8QhW_eTVBJH_SbVt-U4BVPe__ncjG1y4S7j_laK2VbJ0FVsHlg804FXp_Bd-
T04Z2tsOFxy_usxd1C_o1xiwMy3WGc_kp_Nd2nXUwAtziVvy0VCBVO0_s5J1vP0uW9lxiqsTBs1-eNVr1_hp1HnTw6tzmQRE5d1ueVVq1xiw7C3vXTxG7spg
T07d5tezqt-JEQhF5vh_XdDGdoyq_yrdY9zF_c1J1mgONMZ--pt72nXVQFxx_vmXVJxvWrqTA61YeVdlRyoGFf-d--zlpP0-dqVxx--DX7_lX_Z_SqrVt36a
p-VM_k_v6R-sPKYVpmVwVl-_Np_Zj_OCwVFvG5_W__67m9uQ2V_URtsh_-S5xCb1-fFpvdVwVrh0dXwWFpflVAN_vwC8O4_FMzVlxozWNlz9_d-_zl2ezVt-
vry1M_t1x_S_Nu3WWr_lxoz0e2_m5nJWq-V-1R21Vlp0N_0AcDVF_qG1SlsVQmi2S1Kmhmzc2_nT0MmJ_xK50QWA6DT7ixSW0441H_NFynV0Fg5_2VX10Au2
11_yY7y-05K10dt0xmpWbVu0Vw-0yRculcDUtoYWX__QclcNFViW02Y4WHZwXt_Fk63bQKZQAyU_hG5MlpC0VMU0gzyP8FYT0LO_0z0dWE1dWE5d0FeCG9y0
Wfy1XbybZBvAs2-lIbZPwmom-fq1w3i31ByG4FmCiFePW3u1Lj5dWE5d0FeCG9y0Wfy1Xfy1wAk4bRr-XfMzGi3gzpCSeiy0mIy433y3q6S0-WHGzZB0y3C0
VGQWhn9Mzbe1Xfy16VeCKFPQ0OAV0LQ_ds7qhG31pm33pm3q6O0-0VpoCi3mCw13dm7e-nbMzbe1Xfy1LVeCKFPQ0UtWPq1xzJEWJPy0RVeCQEDdG9i-0zhq
LSBjDvyLq1v-1hJfCw1DtndG3duhe3ty36ZJ9q2RFWFQ-1dGfi-0Ddq2jEape8sV0Mtw36ZJLmctoruhe3ty36ZJPq2RFW7QmS-0zl0pe4sV06tw36ZZPq2R
FWFQz0dGfi-0DduAjE5p0FhH7XmB000000pojvx4pke0000000000000000000000000000004
}

