sprite $os_inventory_management [512x512/16z] {
xC4f0G0m30GmkBBpxtO2zl8coGy00000000000000000000000000020saa3ZBgPxDc7hKCn30F0NsFklt3w16c4eTC4WOvIdkqrgHNcVkmUW6yBqBS4w4i0
VGcWBm7qVGdYjmBeMm7u1G2__m3y0e0_-TFFlUfmXxC23B-lG8_ypzTXkouOVzy0-7q2u1S0_0A0Nm3mEmNojm3m2u2B7m4m_lpn2m1__lW5WB-78FmM07yB
0FyU2q3nLoi2OFpvqolKZj-GvEk_OC5ljxuVmb8PVGcWFoy1zBF1Jw9V-EXAi_3t6vrckQdhjpbZ4u2_7u1bznVuRO0sF_z-0F0BG9-VVsRpyuyl_svhKwx3
wF7ddzdy_3Dx-_DVeyUVVsRpymz__dFv-OS__xdy_CE_rDNmvy-_oyy__2jTpOczEx5j68Q2A8Y34BV_YjD2B5EB7sLU0sjXSiUK2l4V-y-rnR_sD2Rl_-p_
4y3fxXUyqDVuE__1lz-0bydV-K_-pd_pT_y7_c-__ml_eOr-SUj_--lV-K_-OEfVmERF_qRy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xZ
uy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-bVZpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvyz_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yJz-CTqr_XClfBl6V-1LTDVu
pxk6xjhYt-bAqZksj_BhBlub_Tf7mCv7NVmVBXzNNdim_hbLTut_CFwakyP_ZlxzxyjNRhVvFz3EDvNNJiS_NzPTup-CF-ckyH_6dtJN-0_ZJxfh_8Vn9zqr
_iFua_BQYVZlD4boCFu7kdAmtVnWI_X_NweYcUNFFuVhhl4VnfzTNSimVFxvG_xyyq3bjVlnNt_VV_E_Nnwfl7Ot_kiD_el_tV9GtJN-_FaFua_AQv_6dp__
dIP97ep_dV82V_xy-TVux_zLRXNMnlZpJtdjj_7dpvy___Kc_yt_q_9mtJN-_0lnvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fbx_v_t__7d
pvy_V_xE_zLl0SFV-K_-_FclBaZxz0z_zt_Xpv-_-x_nvy_V_N_vy-Vl_l_y-VFt_1V-L_MFSQldpz_pt_Xx_YF_4edd__BVrRlER_wU_yx_-tRryx78pxz9
CcwDVvEalCR_P5sGohSQ_asIyXh_q-qgIE6pdt_DPDmQ_oP9UOt_OtKzwcUz-9ydcRV6lsSoRur_pwIznd_IDRJN-0-wZFeQ_pbNKb_ZF-LothJ6N_p5N_p5
N_p5N_p5N_p5N_p5N_prmzwTP4a8X40OtkGJTt7_s_O1UYf1DD0_bZrX-L73QqtoFVvXiFW2Vxi74dfsy8_x7i3aPkF-pteclk1m_tV_Im_-Xhl2g253rtwn
_gl_63Ry_HO0znw5VmUm_hkGE7mO-DkDWWubazig47-x0K25ceaZaLkO_rGecPX4538ByzyI9HF-jWt0_CTyoTJHo2pCVqsNp1qE_cu3mDCbd_4HYldlwPAv
0v9PsFyZKRBW7_ZN4sVwh-mf-lPzQI0_-pzbAxRDXS7VRKUsEFnxS_ZP_pEo9G_-JiWn-E_PYW-P3CN-pmtyttvpQQO__eNJmVK_R_x-ZtB3h__Z7yLpmVuV
1lo5nrO-5PFl_y8_wcTY5_u6_Ba7rtWY_FtnNqPhEl2FFl_D_-cF_zwOZolg1VxuD_F7yJ-4_zRfloxqJ_qX_FVMV5Rnj4VXxu__-ITXylqq4lxLDttyyrcp
_Oj_2_-zEOra-EDlV4EbIGpyl-Uj_lX_BxrKoIn__B_NrolyyQy7V_pnnnz__F777t_yjsy5QG2U__ZZZp_-D03--EEFF_w63O1_t7lz1t_TLlsKbLzhu41L
_6VS_rCF_jslsERhIF4tl_yJ_pLv-O_zGb9_V-5_PGFW7ncqjd6W-CV5ot_LwI-xsFjhyFY7Jd__1i1VylUNkxyCndyfdzbR0U1VbtFtbxc_cYltpt_pvfVm
xnu0v-qlRtyvZ7zMCTR-2lnByv_dnzbV5zUDDpP0lCa_ClNqyFZwgw5iu_ulcXfRVvbSTJhvapujuBh_R_5-LGtEilIFYulMTWtJzDZvgw5cu_wlSWqjMIXt
vwLUSlidZlZs_Kspjdsd0IhbZXsDx483HAMSfllJ0ALoHuz5Nk6_r57gj-EzAAVm4b2h5edZa4zeW68rJVRdFM0LgscoFoy1AYJhBvFG0HttRatXfmFKaX7w
T42eAGFuQG6rnLsV5WXrnWYVHC6-w8y-BplWu__LdXt8000000pojxx7LngTl_yF00000000000000000000000000000W
}

