sprite $quotas [512x512/16z] {
xTSteiCW54N17tdgsFzkxOxM4LtCdDfHG-nh9KcI94cI94cI94cI94cI94cI94cI94cI94cI94cI9AdTNj-yuyRgseR-_4VyS-FFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvjz4DVt_Lz_Fdpt_4dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdp__FUFF
dpz__hV4dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VVvdLCg_Zpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-Bue_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpx-cTOC__ztY
7nX__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvyy-lJex_kHtvhU_Fdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
dp__Q7B-fl-8F__i-FFdpnz__03Wpvz_wql5Fttwy-Tl0E3dlm3_UlwTV_xqDm3myySVF03uL-kBnZ_yx6S0u7zhnJzvxxS4cFplZd_koSy8CFaJHm3_cg9l
24JQJyDt6wYy_Zu3Mv8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIT85
}

