sprite $looker [512x512/16z] {
xTtPbkIe3aRXwbXUY3lU_sdFFEVf9DDfeX7wzcKFiOpsBu5TuQZnVG0000000000000000000000000007vx_VPlNgCarDVB0FkVC0f1Vh4fW0zptn3G-oKI
W5__S2i0cd_AwpKAOESt0in-Dm9cVu49GBy0q2y0Jdu2eFq5W7u1CFq5W7x-JNy1e5y0FFRr85Zx2u3sjm5e_zm1m9VdUa7_z7_dl_qrqe7lTNIb0U3qL_cz
48z-NpV-ZsJWXio31W3kzF89_d5VvQyA_la_Vm3Wvadk0F_W7pSzlahxvtySxP__Lrd__FFF_wyQ_d578__EVw-S_c7_X_i_w7_StySF-088FF_5HEFXNm30
wvR5O_JZZiNNCVvnw-7VCVvnH_yv_l4wKZ_YvW1ux7sXzuFsaMWj9lvl7FrsU_g3QD4-8xxKq0-yA_n-qBx6LEhl_EkFylVnZnRjwtmwqcSjd_3rVvq_Jy0D
_LkqFwBTuiC0cEZFtFxipnCmqP-w_TcVtmtyEba_-_CHyFgv_jTu7sXFC3xdjQb-zDRM1s3Ndtv4Uuw9_jp-wPypqPzx-hC_ftJtqzzATp_zhN3tqnzHMR_k
3yEV_ktl-q4_eZtCDVa-s4xsqLRf_qXP_VJ_WzTcvpwirV-HkhrF_pzubMfz3_rR6nyerFZqj_ZTtU3rIjxq_C_rjzP7OUXlRMm7uYtwTmq0tg5_M__uYUCl
wzys08WVzdUVwp_3F_qn-Oo9_Wq3W3lsFpBHdzw_ze_nEHFzkGEW_STD6l_qxne0hDL_jHFyy__msQAFJ3ZzFPwjiGTOgR-Vu5_xnufeZHt0Iltx-yVQlJ-_
V_wlSOiumZ_zSLl_2G7WV_3F_mOVl0AiivJQF_th_VTn9lmR0CR__BDZB03xE4hV__nVf_d7UaNyyyy__rTf__oFpVqZole7_uXbXXm0RVyZyGD0_lK__t7c
_W_-uVuVzVeVdl-3V_Z-1zeYH_px0u38xv__xlk_jx01N9lhX_T_qAQSwX_U_qGiyjHo-4URe_tvhzl-De2suaDZd8WVWDF-VlypAllt-x-jdJR-3O1uE50Z
0GR0FMEr_ViB84xGp_zzQv7AFwwd0v3BFzhNgVD7Vm9mNzu9_lc_xozowKUxGTpzl6kaXlzv9qVfzXU0oAKVlRL7zu1aJ_uHxze0nfPWmG38f1_F3e1iqn_F
dW3JjJzY_G0O6uDOxNzi3HOFW1XxWoVzHsdz0f1GFwu71q12_OXL0s3a06kU0OuiOCK6CFA0fmR0LLk_xuD5QVi245aF_dXc0AJLZtZ6_wY04J3E0zNz8mH0
0lYNW6K1wF-V62VZDyBwLsaZ1HBmZFbjnm7wZmT0_ndZZmRt_VTd69iW1T7-GSIDlg-J0VG98i2_2F0l0W8W0lnB0FyY800Im7-c1A1F0d1w0dJvnF-n2S2d
2g8VdG3C1FH-RW8mht_l9HBWT3zA1e3--G0uCG7uSkrxXGJGtwyR_lC7WFtv1d1M0X2JkbSC0Fqzvlxp9m2JgXSD0FkzjttyzpRU1ltp4s214K1_7oS7076t
vFs00E075Uy54a3_v1OmSm3metf7xW3W-c6vU-O087vQxfuy06R_-W6G_r4G_JtsyzzZB8V--GamvHw0XqhTKmO0JvMwbmW0_NsS4m0yMEcUBW1uij0jMm3m
R9rxWG3GFxa5JFCS08_tMJyi0FJVFm6slNyp2l5ycQ-lEqWS0EtVhxK9N1y0R5BbFoO0sAZ8yVO0OBCY9xi9eB-llgILfnDisMJlsW6mQutZ7G70nYMEvG70
tXLESGRal_3rqT_JNY9o3DT50K1BKjZWVy_6SgNqluSGWATfkTwqg-DVGGLWFVcUgSI30K36ObRmhvG2i9v8MaZ-zwcZ2_Tzx_VJ1E3dPAxXLTK__V-WU00K
i81_-XS50DS1rQljN_D4xG3edU0_Z_xyo-3VEkYt4lutegH_-WL0oVXNCG5GCFw_HPnMhul_vUrIUaNyNwSiYVyuiLXBtrxG_XPr3DUPhPBRlqwn0MWKwrfF
d5gdgx1_RM80g1B_S-Au8l6l_GL0YVXNejh-TKZjHq3yNxK7W0RX_rFYzFf4KV_6lm6WEloh3lyBTaV-jRyrybzg0F1_yPyAfU7VriZ_G_wRAPSBXU5VOQAs
Vut1_oDrkVZN_lppRw7yLne0_FFFlvMU0V_yyy__LQWg_F-e9lpp7_odmzDV1m0ruP__xy4___pppp___FFFF__yUm34F__yyyy___pppp___FFFlxMcWd_-
-UUVV_xvvvz__ldddt_-lVyH_7l_vtYYXd_-ROh1Vsh_LgegLke5OFxT0F3FlpiT_hM_jk3V0P1_6m3__8kvml3lx_yo_dM6zbSQ_cq0_FCV_2-eZVOt0FZd
lzOA-R_uFub-Udak-fyDWFKP0FppRta2eFtvhxOu_gEqV_ux_GO0_mQ0bPr0zE-Z_Gs0kklYlplOdCDrd7_jRm04_olznzYSjMiI04iwXtvSjOB_rTKAxMy0
r5qF_zro1A1m-_FVXTa0i1G3m4esGTc2_dVwxt9y1bU_oHdwqUzon1H3z9i4_GQ05GX0qUldlnU_V06uIkldlxV4rpx-0VeFoAyVFLy0w1U0o1bR0JZgcldl
-IuvneC8G4-UM4J_6RNZQW3qbkbYnmVGqnGrwD_HVu_QGHM0Nlmg1Q3drO-hFq1Bcr3qHzZxyc8iHW1wrcj3txNAaK2_8y2gIh_hej0VPBzCNcC2-fF4PjSp
fg0_IxPhGN-QNDU1le05UpxzYsXz3GlYjq8_egyZPkeFqsy7c1lfwsdZ6w2VnlWMAAuVnVMZk7uKru_Y-b5SFuhhHz2V5nCWHarC05_t4O3n22Yk7yNrexX-
L3_uetZpexX-L9_zADxyAAuVhRXz5D_vSHLlVbJNZ-Bs4SN_f1_Lcn_LxQEwVLItZ-hsKTq-gjj7zIVzkAgtFgAwVLIN3_9HNZxAoqTm3-xHE_NmSE-luAhN
yG0000000000000000000000000007y6
}

