sprite $recommendations_ai [512x512/16z] {
xDD9hYH734H1eIjhsEd-jzLE4pTUFq44oBPtWmXp_jcK94cI94cI94cI94cI94cI94cI94cI94cI94cI94cI93qsTgLf8_ypJXlvNrZZDlBd_jh8d_jh8t_k
hutykRysykV-siYV-siZV-wlZVovlpRov_xQo9_xQoD_xg-D_Bc_DlBd_jh8d_jh8t_khutykRysykV-siYV-siZV-wlZVovlpRov_xQo9_xQoD_xg-D_Bc_
DlBd_jh8d_jh8t_khutykRysykV-siYV-siZV-wlZVovlpRov_xQo9_xQoD_xg-D_Bc_DlBd_jh8d_jh8t_khoty_VwVCRrN-byl_Xd_nR-XEVmF_WtDuUVV
qHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVVqHn-_XtDuUVV
qHn-_XqDu1_jV_6_mJ_JFuz_pi-_epdy_3kQmy-_em7yK_r__HF_Z7-J__Nl-CVyy_tp-EVy_3kQmy-_epdy_3kQmy-_epdy_3kQmy-_epdy_3kQmy-_epdy
_3iQmB_Odtz0nPy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvz_0zHlxC_V_VE_Dlhpp_krqPz_tXz3_FdFY3z__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
dpz__lpvy-VFdpz__lpvy-VFdpz__lpvJua_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VD_lpgwple_c_xz2flZ_shgEkd__9pk_JfQpj_MTS0_vDy_W9Y_iUk0VyQ_Vm0fVslN0V-8V_y0Glxc
hWR_XDy0ClxshWR_WDy0Klx-0VJxLtu32Fdxk_hzAxy1fFpzNUt-bTy0Olx-hcx_ocy0ENz_LxD_vJU0W_orgzU_yXl0IVxQrUfV-GtWA7-jrR_o6y1P_bgd
V-KtWCFyjKR_ocy0f_bhVVwLtm2EyzVQ_2k_0PpdhtNvLtu3kC7VLvD_vJU0WFz0T_rJVWC8-4zqqp_bDu20_qZt_5D-0mZuptJBF-KtW83_K7VyKtu32FXF
TSC_vJU0WFzOD_n3VWC8-Czrmp_ZDu20_s0t_2D-0mZuJtR3F-4tW83_Q3Vy0tu32FZFzYF_bDy00lx3_SG_vJU0WFzqF_1F-GqWu3_Uz_uflm44_EVxsZ_b
Du24_tpV-gVy1X3nd-zB_vJV03B-yttdd_8RGCX_lg_yKtu3IFdFzur_ocy0xzUOdda1lm4q9qcI94cI94cI94cI94cI94cI94cI94cI94cI94cI9EapfvMl
UX_kCwRd5ytXlmutX_-nqF_zu9_o3_BF-Vd7_FFzAp__c7--V-Nd7_FFzw_y_6F--VwLdt_CFz-_ylEF-UVxLtx-CVzy_yhFF-QVxr_v-SVyy_qhF_-OVxv_
vUSVyy_th_pyO_xv_fMVVym_tx_oyu_vv_jNVlun_tp_oiy_vf_lN_dvn_pp_Ii__vX_ld_bvn_pp_Ul_FnZ_ld-bPz_p3_Vl_Bpp_dd-rT-_Zd_VF_App_d
d-zV-Vdd_FFzAp__d7--V-Ndd_FFzw_y_7F--VwLdt_EFz-_ylFF-UVxLtx-EVzy_yhFF-UVxr_v-UVyy_qhF_-SVxv_vUUVyy_th_pyS_xv_fMVVyu_t__r
u9_oJ_NF-Vdd_FFzStx-hyT6_qSO_oV_tlZpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V_r_SqGcDHJ4KWD0i3VXtF1B-TljA1mVak2CE-xkb_-WlUphW7vYwpbzsTS0_C7MPl-nhtZysTR-_x6pS
lpLrlx_iRTe_DNM_l-nksByqTR-_x6_MFpHrlxyyqHR__bJVNvvfWtz_gkylJpNktv_g-yjp3Vltf_h-ycIZ_lsflhyysw1_VwhlBqytvj-VwllBymtvzwVw
_dAY4V_-LDzVpZJXdv_g-ykf1lphKtr_ETU0Vtkgxoyd6_0lJ_NzvMm3_jsflh-SRi2_EjNtb_CD-3Ud-lvIQC2_EDNtbqQZ_jAexo-L1lsbKjrVEetvIwUs
lvGQyfTIPNzfDU8lhLRMNseD-4kj5VMNNZ_xIw-Lz9TYF_fBiHNqbsO_-KkpbVENQZ_uIxKLyvTkN_jBjvNobt9V-akv5VANTb_vIxkLyPTwN_XBlHNnbtuV
-qk_bV2N6_hGNsve1VpbZZxobpjQn_tbbZxmlsZgSDuJx-TVUt0i00000338tteK-we9000000000000000000000000001
}

