sprite $datashare [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000009Yz-rYItbQ2ABnXi7ANx_-qrqhw_JHPn4m3YNFMrqpKLs0eMZIjIX_bUvrtyoHXdkzFtrpnvxpZ
pud77tdyeSSVUlonnnzx_B777_kv_UcKX3y77t_myGSVV_3n1nz_yAFywP3mv-ZZpwyy-7FqyKSVVsxQn1zz_D6FyYT9-AEFFrT-_D77dqi__kZZZtwcFvNm
v_3ZZpx-yEEFFlxmuuy-_l3ZdzWX_3dy-CEFF_puytC__Xn-_E777txyuSU_FT4j-F4lVL0sF_vwNIm__hfM1VBZV-X6QVpuwrwLn8-_xXV3Zt-fLSPl_lYh
MyBnnr_zbkV7_zIJQcr-_4iFMvaVVprlNN_yDQ9L-V7NcDRanr-3EhVsnryhykElSQttmn_-6jbgnn__qiXgCNxyDRQr_F7NXMvTAQBuyVUFPVdZhu_h33s5
7__Ut8zb_F7N1xKdd_2E3_pxHs-Yuuz_dxy__ENzyNyq_GL--iM_mJ_L0kZJmjzNIlN7tzTQsnz__Q5wBh0mF_w-Mg8__hMrF_w-tiB--9T-M-tXZxz-tnY5
nVZnnnz__F4t_lXVRmj__F777t_yySSVV_pnnnz__8ymV_phwKsO-FFxB_xuvoy0_aUEF_xS_yFzN_ZZhwS6-EE_xWBWhyS2jR8_ptyLp_yru_bF_7d-kym2
yFw7gVtnv_ql-9yhl__9weJ_SyVI5Fwbpmn_7QrpPtC1uFslI_ZZV-fLTo-vzZeBWBzriTALyEVx3nil0Fw5Fzz_OW7u_Xk_0V3znxqk0FWVtdW1-Fvp-HsL
deQ_r-MtzJZyhUVPoou0_bwNtzRZyBSULLxR7tzR_VpUIi_3twlosneG_bQhiWCM0F_c73r56X7-hYNrRQiR_lqDEEsm1S3VFdGjpvKQuT-UfQTBZV1lFniG
i03uDmRgULCZ_8FIHE7F0k3F0k3F0k3Flmt4dqi0_Ym0_izxDS6z_V6tyK_kmWZtziVV5UwFV_dZy4_juWmB_ymk3t5lV_nT-0TsPufx--Dluv_MtJ7kxO-_
2_-a6dF4FwZM8FVsnz_6FwJs9FFyyI_V2V-07eqop1z_-MPP_lZBTpkZ_F5lbEEFlzmfnXz_kLU8F_voimn__ELsYVwbR-tXNtvGgF-tAjvVVbIb-dyht5z-
MBg_bEqlFwwo_QKpsLyUq17jBoNxosDAzfU2_ULH1VkhSltbWQNwIxd-yjWo_PNhh_Be0lrLNhXtB7UOlvJhN_waelmLwo_v4pjJ_9NhBtzs2VxAzPVy5Hrh
-olON_x2Qb5_1Vlhz9TNy_ZZB_cTBU6lQ7_9ipQBVsNx2_yNXVjB-7zSkh-qeVzvOrBn_gfj_MqBV-dSrz-EEntgjA-_qoQZNjlwsrc3KRTj_Ot__piszNVI
KFIasjFVGHS0FQksz3V-tzhH_uWv4HfHk7_o1K1ZsitV-F_SNlw5_oyTeVx95m2DRMz__2Ljuc_y_zZU_lXBsjiVVwd2_Ot_o_Rsnr_IVlw5_u_LNlx2_zVm
dxFIruN_XEbhI_77lz-HxL_uNoZN_y3_Qf7-nlzMjQQ_y1zP1VdZtm__hwqqQPFxLuY_jKBp-Gl_IUB-J_ov_nj_dl_eXJ_-AyVpd_Zp_FUNBG3-siaV_m1-
_7d_KtC1y8_dT-bQ-E_y5H3yD_uA4Fx7jfy1mr-ISlZnv_t_unS0V-_iZx_D0k2_wGBWxvtzyVVogH_-3aZTy7T2fLxuEoErmjyfgH7-pactmzz9wMRuEwhI
dV2tlUy2uE-yT3Ny7PakXRzJq-lmTt1w4VxEJdyE_t9--dtuUvDEVGj_RvY-nVt_B03-B03-B03-6rMIyDyvuPz_mlr1mZ-vrnCi_8ExCiAz_V5tk3_-vHVX
7zhL6HR-aLqVujx--DluvtLhYdlxus_Z7zRjCUxjZxzF_8FgpB4I_V4lNwxm3waxIFmpwayI_uIUZBAsziVVFl1l7PPP_UNRuTyTqOp-yltmRq_dJF2tyUyF
PZ9_kHV-xNy-hgdyvMOd_jqJKJFvo-tmxuvY9l_oW_1lZc4UVvr-5FxgD8-__B1ZRtyrcyPVVjw-_cetZRyyeYtzIm-QnbyUqtR-UjOq_lAmTlBNqwRnbmTM
c_ZhUTFuosEhVFzJ0vh6NnvUPVjhIDFug_mPnVfBwot0c_wK2lJNg6eUV_apY_BNk2Robp-xml-D2p3BtrAh-qjBBi1abwDQrRzk_AMrcB_yzQtcV_Uld6Na
kfRVs0B-hRzn9NzvgXRpx_ot9lDNUTOcy5TJSY5_oPtmjsTU0Dq9__7NyPNyLVWFFyKB-7Vl3SR_oSsoK_fBXVz8Vdi1_zO6u7_uKWluT_us_1yYJEmluV_o
ftyd-qk5_vZZRo_WV_SlnD_v_f8RuJ_F0kXn9_uDl1n_INlxuo_Lllwb4NYB-qlQrL_u_teHmF-Czd-rzFXxItz9U_lZBsblV_mbxUsFlwIz_V6NT8Juuzzl
Kt_X_q_x-EFV6GU__zUxPdRe2yC_vGQ0Vjlu5_uNTu3xFsfP_txn_kSAnzzwQzp_c-FVB_J-_seO1FXts_RvZyB_-tByDV_njoPkY-T_hRVwMolrkyjcmFF_
-7TQmV_iyw_YZx_xDyKgsnz_gSk_nWBWtry0QGD__AK6F_vHx_zjR4pG0k0lgV6sw3tzUVz_hUQFVsbWzc8BWByNlcs-r0Z_d4VfzJpy3mtAE_lp_KTxumNW
-w_UsP_lVvUNNG3ylIg_ImF2tulosneH_bwKtzQ8yFUgpqMLHeI_Qqb-MqF2trwItzQOyFTA-kFzyRSNvBVL2F-W3sjgLFZRjPf-Vm7mxs-0fqgDyE_FqxEb
HlZt9ke9E_KY_1lLK_gbBm3u_xizkpX000O068YN_HV6UUEQknLIxzKC0FqD0Frz1Ubl0EXl0EZl4A2_0Q2_0Q2_0Q2_Kw3-bW3z3G3z3G3zNqp_EFtZHhm_
zVx4-rFlJxm_8zwVUd_g_Qdt9zwVHRm_gtf_wlsfzwVUdtf_Hhq_zVxa-rFlpz3V48Zt9z-VV7_o_Hdv_kJxep_wepzh_T6VeJyB_VSi1VgZ_mxw7w3_6L_J
7m0000000000000000000000001W2m
}

