sprite $risk_manager [512x512/16z] {
xDGn0G0W3CJ0iTtUlria08pqpaEIEm00000000000000000000000000001z97-X-abb1C7RWUQzGFLEe7iVqBqFBFRk9Cj16Da2w8JZq4pxN-t_rVTLsSWF
GjQDUGBYFeLed3Py4M0l0rPyLmFmHK3Rjn3Gbm1ztpfWwZ_P1DGrsjOrcvUfhmdGbm3w4a1V0kZF3HAWqaIT4w3kU5vJ9oR0t6_U0zID3slhf0IO_9_P0kZN
dByM-UBlxao0-lMvVlsUuyjLesvAWFhzghvYyPq_xHS0-lMzFttDh-hrBSPM2V2Ez_ij_EkgjVsilnjMIrDhaN_E-kwkAj42L2sTr3S8_60BJtv6pEIlcU2V
yoTxV3tK0l3NmjpzedwsaGS2G7-XTQy5e442y2-uBHv9ABXpgbg-ZdhVjLSjH2zw6MZohrsuhnzDP0Jg3PFdhMVyDzkgvG3GJxoykTxw37AsJ81lPdppYbk_
EunG0F2lNR8bLu3yrupYhm3NRxSOo3FzrPCrxlCVyzO4u0zW1Hf09W3uNslRIHpSVS767w7ADu0vN-k3mpy3_840HDADlsPR_tp0ySyqVpu0zUj1-f3dkbB5
NaekRi17Gryty8zWatfZctjvsRz4ry1_RQnbwG_n9mCG6ox-EVlxP_EEV_r2CdkqrI80-ETund_aHeq_xxE-WyIuNVc_BKuLF-8tZxpcTDyVQCzj6i0ipm6k
6F_z_lNk05odB_w1gxFaKGV6Vp9_pS_s5u25iGVu6mS0__x--G3Wlvxrhq00yCUcVxu1v0E0Vt__MU40u1U0ZVpdllwvwO0_VrcsFcDdkm3W7tSE8VCU3F_c
_laEW7_U-Xhb-ktnwm3tyezxHn6T5_Zx-mj0W3y04Xf8cvKH__t-0i0_TthmhtFanzBW1E6_rry0rWVNvPNy-WrxxXFH-DSdOtuuoHw9lx__9G0_VS1PAVxA
3YZNorBZCVtp8qgUgHFu-LyV680hoj_4Fzy0he-R_i6DNyzakb6pxCzVqOdOP04GWC1mslfVqHEsDVzwAVoTIm3uyySl0FpvunU05wztr-liwQ_mfqe0-FF7
Bm3y-UCN0FxyyGi0V_xu1O0_V_m2m9z__nzZoDTpWnnR-hVz7xny0FhxvscgJSRsRm1rzFJdF_RxXx_Yt_K_t7QKwT0Nwo7_VD3xoxGuAyy5VHm-_Qk7VuC6
OFetyDS0RfwO_AlpzEUV7-jE_lCCV_xZKVyUmwtD0s3wQm3zfp__SSRD7_-vkN-BdENlTldNNInTNefS1-IzurLvc_dmgFyurRzw-uyj1hmno-ZeRm6uJOL_
O4VyNV4aReRu7x80Z8Vz-mnwdh80y3zWpErEHNNth_lzJV_XcfU_HQ-N_pp4d__W_sJNuryV_j1ZRkX_VVw9u1y_3_tz-HV_VwXgi2kNVsSCNFldpvz_9tx-
1mM0F__8WV7dt_yiy9_pnV-veRzEMlxv_tkTq_xvywyT_AkVlyl__KtgQ7_-ivb_l0Nop--iVohvy-VFd__hQ7_-at-x5dYyVmMFYN__pm2E1lww7t_-_Fdp
Fs3uRVtvy-VFVwQgzl0Vtnf7mF-4s__z_STVgxez0CWdal_AeMU7d_Vdlt3ms_Zp3np-xlxynnzhRGIrgp__yKKjxAwzF__nZVfGV_urlbaVwCz__AW-ov__
-77jxvyljR-_ug_uA_wAl-Al-2l-Yh_Yh_Wh_eg_ug_uA_wAl-Al-2kV_xolJlRdV_Byvt_o2i3_u6i0_YTV1V8_-KQ0_yctWlmFVXZ0lyQ6TVhtltcsMQT_
_wCdsqSj0FJVULBur_Y8EjtVAytYd-7N0_Zpvy-_jlVdxnUG-FlzL_xy-VDVA_xy-LSZV_xxDm3-_FdphwFz-Syz_FcFK_pvluxsvp_vFrlyHpT__kCyV_xy
VGQKFt_-_CSf_lphnbtlwjzfjtaK_lolu_pvv_Uz-8zE_5q0yi-hyES_Eldpvyz__mMWEllpp--zcpz__lnhlmi0_dcM4_pvy-TV-Vtd_VdtRm1rX3___8xu
v-TbtUL_yM_vqsXxl07cdtS90xNqvp_uT_NFm_3dFzhcZBy6m3yFSuW__zhFdtzUfexsvp-wjXd--pU0_lxyHukKyS_N5Q19fun_dkOGV_wLRG1vV_xz6q3j
viz_z0qP_xYDuhz_yHS0_lpv2m1__lm5eFl9vSzV0FZpvoy0_Fdp5m3-_FaB07y1uC-Vlm3mvyzV0FZd3pMvzVxdbtzrzkUVFzRWnY_-RVolv75zlMd-DP-j
w8dZ7_1l7W3-WSCBLWMZcTWmVms0V_y0vFtvvmFGUG7Wdp_Wz1qW_mC2aFFddmz0i07mhwFz-SzvPW3cKl7V9W3nZVBF1-1eV_wZmKjW_fi689Yf_R__OSvD
0j3Bl_Xl7u2Q2yL_dm04ndw_1VyHyET_SW3uptb201AZvxzF0Ax0yFbl503-0Vy60U0VvcyOWDe-0FpNHlhf_lolRnxsEjRH_ZMxrkkk00GESH__sRVgpKSU
c0Bydto77MW0_FSBmFhcplMVyu0019y1ycySWFuDWF_oWFatu0zM7HM0Y__FRx8_sP__l6u8G0NQKt__sQLMHxrv0-2_FEp70h3nzTzh7XQ0_WsWmSvs3S28
1e1__m2y7lcUeThLVtQhzQ7ltG3uhu-zImFext_D-Oa9gAqRmCsxEge5V3rVJ_Al-R416B_TI1sq_iyzwnsZU--QUF7VBG6fpvNdLV3FkJx4uATA-UUhbWVv
likYSQy__f-TXkWAmBz_04Ps1HWt--F_-PceN006_yTgRRoL_3H9tX__dBKqvE1d2VB5V_r7k9QVZHR-f-jQ6FbO342P_WrguRN7saT9NlXxrFXr11BlaFfN
pTqgGF6DAToPt_HVrwYl_Wv_wyg3RCFFVzwuLDR9_5h0sBckkLGIK6CSE_qbe2Sg_hnGcDwjVpu1QWPA0l1BW6j_2J3z-xyRngy9u3-d2dpirayJCFqb0Bzr
0By8zB_pLwxzrF7TN-5NTKFBxSslqcVyEerV7wZ0nkFyAdMcT-9NzVwJlEEDlthZpoUO_hA4twfox6C_XLy0y0i0VW5mvUSY4By0uBS6u1S0_0A0Nm2E-4rd
zJfyyYly0d0olwh3zHL-0S0l0VG5m4s_19Zy0a1V0l1B07rl14xIL_Gbm3sV19pyZvsgJk_ywdHzHTyo05yJy2zz8c3gYm1y6M0__xyzE10000004EHlFSZL
0m0000000000000000000000000000G
}

