sprite $cloud_build [512x512/16z] {
xTn9kiCc48LHVIeYCSl-TvjH-juF-L6-vspXTzb2W7zS1W00000000000000000000000000002WSW40Pn0g6ADY0017_G40rdm00017KrGmpde9000008pj
K3a0i3DCzOShFG00003O6QQ24PSVi3DCzG4miER3tpW0003U1c35ZnK_O6UOIWDO2r89000O5GjWX2hySIC0HunHVm30-U7g3m00SAK7WBnTNW0006pphXIt
CusRI437_n-AU_MBRL_WQAxZZsZXeYVU1e0rtmgLZU7HvKq0yEY2jM0SwFWQE-wl7m4u0dNy4QqLS3m8m88EFc5dc5xN1U7wYaeZlq-0-Zu0wl-gElBQ_BwM
UTkAtxfgcMifAyvUhh-HC9bSJtZuvweMuRuUqk7yATU3YiqVTgzdrSxuuNhSlcF0zHQr3cUR-hywAutPznMWla-0_BzgVZ9Q_VkBQWTS3HNg8p_ge_xxoA--
-lTtS7HpbUIlVjJlHVxXUD0gRycrM7LYzkTQjGZtzGvZp_gywTjzBdHKCnxxvYyId_ezzE_trSzecF-iXgpudnn-pXTStvo_mOhVbPvLecVVozwjwdDjapzX
bzT6J_Bmgtz5rvV_-kWLl_ptluYUVkF_pVtnwuzdV_IdK_x-_VKVM_MdqTglVt_p7zjVVzk--iyb2ltxqNyczzV_thE__iqk_5H7vd-kKkYF-rxetuF-Cxc_
_hV-RlkdzjT_xjSV_UcIVtr_zAV1eQ_c_Sr_Td_zPt9__UTgXVvDw3-J--j_xzoV1ck_nltD_zosF_hJBh_--ZUX_qpkh__ywFxwZtyHtT_ypwtxep_jykkl
VmFwpmRzQPTVV_stf_yTtL__cTnV_vdSN__Hf3yD3drrws_-PuV-w4-x_FhhlpFzPu_-w4-3jL-d_kP_TkcF_hJBhx_-kz9_9lVN_sxMdyKNVfBxc__PgJ_w
ipH_Sd_zHtH__MToV_rdi_xeJxly-kk_7VrdSd_zxvxzMNNeAxc_-PyD-wC_xVBhh_zMz9_9_VM_-_PdnTelkR_vdrtxepyByhVkpsxzxtzJQx4WV-Vvvrwm
zklSdmKNVkBw-n6O7zIVyFuioD-wFz_ry3V-ZteE2yQ_zVop87_d_gJtvttvhnVKutYXVzByCr-al_pwwt-_wgnkv3Vy-gill_hwto-hFH0z_DpglvNnFsiR
tAr_-1bV5FtLJtHznbk_-citVCRmSxuglJxfzPbF6xKpHlZmSuVN9xq-3wpuZ-h3Ml0E7txIwvE-vYDy-4dVuyVi-mIO_Ny708pQ4d0-h281HpK07CjL5m2C
HUf30000001dVIXWrrVzlZq1000OJTMly3O00DSc0G1_cmJ0-T4g500008nKPwK2E0ug300008vtKRa0Btkf_d1P262yXCe2082t0G0SbGjmm8SA0m00WEDT
L2x0bHug6sV50G007E-YriFR03YQeB9nr0e0eoKg6wDo00000E203xKQ0000000000000000000000000000003y1
}

