sprite $transfer [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000083PkvEh1c0WY8BiqatvPykT7U_MhqwXPkOzDTW-I-PSwV2VOvN3ltq2-BTF07ydW7zv
0lWR0FucWFzyMSdmTmBuUmhoTmBujqu0VoU0lmdWRm3ucm3-sY3-JW1_Jq7-WHF0tmdWxmJmDm7y3G1_4y1V6yJV2U3lASZV2U3l1F3VyGJmDm7y3G1_4y1V
6yJV2U2VUWhoTmBuEm7ydG3-9e2_0U1l0lXhW_Wx0Vmz1Vax0VoT0FvE07yJmDy0y3S1RxCQRT0W_LtYXrD6VFV5yZi1QNwfyqkSN-hyWbyRb2xynFfx2gRv
XRyJaFQNEh_4_QNkB_orGMb-uUyfcFON_av0sb_g_XBtbxg_yDS6fVs5lwTWsb_uEm5fVwdxIznVwlx2NnkKzXV-de9fV-7l1AJzfUulMN_XB-u_Vlxq-Nlz
yRVy3Nzvq_zRVlxq-UFdJvy__ltzwVFN-F2t_FmrFlmjFt_w_F7pfyyVFt_w_3K-_2s_N_tN-3W0bfy_VVxu-TCt0FZvqpS06X_-bjy0Q7puMtu3GDy0u3S0
z0q0Vdy8fky4Q7nCWEKt0HeViVpywVF7pvy-V_pywVDlD3vY-VbhVFXRVlxq-UFdJvz_Wr_eyzVuyBVy_3K-_2q_V_hy6_n2dpz-_lJvQtpuMtx-6X_-ZUKN
-lpnywVF7pz_-lmrFlmRooyQ7_wMdpzz_lZvq-VVuHVw_3K-_2q__rxZ8vQVFtt-JNwXpx_BB_JvTniVQI-_dAln4H4H4H4H4H4H4H4H4H4H4H4H4H6HjxcA
4V-eBMFc_CMdjCHdDF7pfn_rny-VVjHVuyFVyaVzDJxyBJz_-lpnb_pfyyVFdtxEN-F3t_Bpr_Zmj_pywVF77_2dpny_V_hyDJxyBJz_ZGz_oy-VFd_yU_dJ
vu-VFtt-6X_-bf-_neU_vUTFdpz-_lJvu-TF_yxzDJxyBJz_ZGz_oy-VFd_y1N_w_F7pfyzVuoFvvPTwuoFnvPSHrvSulyJr9SulRNqPxSP7uiil6X_-uUKN
-lp3_4AVFtx-zFbhVFXRVlwTnaT6U_c5Fd_y_Edpny-VFd-D3t_Bpr_Zmz_oywVF7pz_-lpnywVFN-F3t_Bpr_Zmj_pywVF7pny_V_xyJG1_hp_-JW1_9u2_
4y3_eBmmsi3V2U1l0lWR0FucWB-d87ydWByJmDy9uAyDuky4y3S1_0q0VnF0trEGlnF0_tmdG5xMfpW1rbyRnDy9u6y2-1i0_YO0lwSWVoV0wzy9iFvE0FwT
sY3-JW1-4u3V0E0t0VWz1V4x0NeV9y1llZi1BhysYBqJiD8n0U_iqJ4Dm40G1B7cf2sVFzlWYCQcuFShrF-9_xFuF_5_5lyd_i_5_wd_4_-d_a_ydyN_YV-p
-3_nVox-J_sV-3_rV-B_BFvF_9_5_ud_S_5_wl_4_wd_4_zdyN_Y_op-J_oVY_zJ_oV-J_sV-3-B_nF_P_5_ulzS_9_wF_5_wl_4_rdyd_W_Y__Z_xslFJWM
000001ZaRpsAVTK30000000000000000000000000000000008
}

