sprite $cloud_natural_language_api [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000000000000000000000000000O7Rkt4YI68QYuDw_jV7Vsss9ClO0Y9h8
PmApRY9gHVersCUkh1z__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__htnJpt-_zy_zRhE_xngvUE_f_BYTrx_izkVVxhl_zdhppyJpt_PwSy_Ky__sUVFFvFlVzdbpp_Jx__Puyy_Dxx_P8S__zpw_fVx
_lnpy_jlxlhpp-tl_xddppyBzd-IE_xyantxVycyF_zaqVvlPltvPzl-V-Ry-MVX_4Souyy_sJd_a_Jxyq_spdyblVxyaztpVqcVF_za__ndqkFFFtd6_6yQ
_9KyP_wRrgBrvxy__k8l_kB__FYBl_YBl_YBl_YBl_YBl_YBl_YBl_YB__TF6N_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvyz_Dlxy-VFdpvy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdB_xYB_xYB_xFZx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uc__bNuy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xFYh_uYx_uYx_vN_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpv__GFpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFN_p5N_p5N_p5N_p5__dn5t_n5t_n5t_n5t_n5t_n5__zyK-UuSy_QV5_lRBVd__R
gSd_NMxvgwpVwFykT_nLr6_sVvSR_Yhfj_gVCk-lWdwx_odJ_Yhe3_YVCkklWlw8_ocJ_Yhe3_cVCkUlWlwO_obJ_Yhe3_gVCkElWlwe_oaJ_Yhe3_kVqk-l
Wlwu_odT_ghep_kVqkklclwy_ocT_ghgp_kVqkUlWlur_rEw_7NqL_gVqkElex_K_vGEVntzI_w_njfu_5W__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv-__sx_RWM000001WaB_r6FPN7m000000
000000000000000000000000000000000004
}

