sprite $ai_platform [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000Pky-qXn4bYYCJYZGBFQ_skUzxMu-wK-KvsxXt8Z2bCWL8dA-CVDVytfZ
fWd-thyl0FxU_vhrmxzV079c_dK1X3_-phylW5oXVry0EVdZZ_pJ0WX__Ab_MG3XZx_rRmiWFz_lVqqGuz_uzmi0V-zl0V3l5m3-thyl0FxU_vmrmxzS0FXx
_we0mXz_xryLGFZZx_tB0k3l_OC227_yY_W71H3--1VnBmeWrvx-rmGn_e5_i03mh--l0FpbtDPV0VZZtzd_XNzVV_U0_5_uD_PNW1jQ_vet-Dz7ut_3xClz
5U2uoz_xto_0OVo_sF_wm0B0t_ZtVm5S_FN-zmk0VqD_1RWXbVjR0FVv-Tyl0Fxr_STh0FvlM03uE_-t5u3_jRf_-n38-FV-_GBmuB_tznhWXXN_6mi0V-KV
5e0_V_ozlmBmx-y1yQ_lRm7yOwxx_Br_LG3Zpnz_xryLW3z__Br_LG3-Q__-A_J7VzzV0NB-uvlzZmyKmFX7_lq2mD_xNpiMW7-_0F3VzrU0Xf___VFXZFzz
VmiWvR_utoY0yG_yWmM0F_1t3yY_N03u0_-k0DV8m_txuB_ltnT0-EFl_Fi2o4_ett_PNSxGlry0-2F_lW327t_dtnT0ZgVw7-o2yG_yWmM0F_0F2Y3yyGV-
VG64F_xElo-0N4_tloQ8yU_z-mM0l_TN0FvPyFV-2i2_2VxUloy0_jx_d5t2lry0-7j_1JYJp0VoIiA_vEyBW3_mjm2ClmLW_2q0_8iNWFyr7ykrYR_njm1S
_Ba4DFx-0k3l5y39_x_aPyO2CFuk0LtykGGq_XQ0yRS0ZBy5W5y1FFZdR_mLmCMVIq3ZRm6yALV4lrq1hebZ_2q0_7q1-1yJv-0VyCU__-h3dp_-pB_Ftlpy
hmd3lm_-pDy2uDy7_nh-2d3mBt8O_zA_3_xMNm7uyp_vP-7F_rdy7onQvdzzxly9UlxF-SzJ_ETp_jS-u_-7FCD_PhPP06Vhp_-rqVZF5FwV1Ydz-_7dVpwd
0CU7-MS2_uzp1Ay1WktFF_WBK6__-rdTl_XDmJRZlxx_EK41DXh_cRNzP_PP00d_pCh-Cqa1di1_yN_VroKVjFtlPrt_x6Ubr_B-m_-T1TXe_6TMzP_0lof0
o3y_Q_fV4nPWe_6VMTE__S3uFkC_SwpeVyniim3ghtIiw5z_MUH1s_z-rlFFForqBUi__3zHW8t6VsOr_-dzNzyr_lndJVyrZcPQot-DGwOssFw1VtZjjUBv
SAjyt7Cb_rMEYWluC_zPnt-TJyH-b__v3VwlJoRWxmeG-0VRFoW0_sZyxoVWxmeG-9VyVG5-LlVdVmNZdnKWy5-R_m_vA3__SpN_QwVptNh_ZSw7EnSyugNs
3mw7gGfmdKsUw_zgSZrd_E-_G0pyYqS__G8uippL_vKby0yAq2VWjm3u1_pFMG3upnaBmFWh0Fx8Nm7Eqjy2CFuMW7i_2y3uAm1-_lmL03z__Wg0_vt-2d1z
pPdm5e3nLm3y_Fah07x-_1K0_roP_p5BvoZl_Im0u__r1VZnwAVajm2ClmBWd_En2Vm2_uqAm7-AxEkFdp__sTSVFt_-ixK__hcszkS__FjCcNtzyVFdF_lw
u-VFV_YNcQzAxH-Q2N-9_MD-kLh_-lzqfVNFnrzI_vPV-4lft_FBjRU_fFuzltJ-ER_mbymVF__-oP-a_ltuI-RVymj_AVrxVlaf_VkBFqdz-_6NpB_d5_wI
-VVymbzI_vvV0l-FyaCx-1zVzXGX-vRd9_spRuQE0gpWZp_mvt-D0gpjR_ndZhkNWElxDyU573CMm1B-vVWhGEzVyVFdhm2zFtx-rRsV0lJ-vVWhGEzVylFd
hm2zVy_Fdxy2zFxuxxy6EFVolpxmuByE_m-ClmA4_Zq_V_uAqFlZl-__iul_TUl1lmNG-vVZhm2zVypFdxy2hE-FVpO__yjl1xVsnpy7_z-UOvuV_kduzzdN
7pz__hEnFtx-FXdAFnt_Fllwu-VFV_Rrny-V_spjZtyE_kM3_pxyq_7liwy_VlxyPsD__FoT5SO_7Vy--_hZvyz_zlN7pv__REsFVwwz_PqJVSVjCNd7-2l0
CG_9iIE_1M3y5G0___3YJm6C__hX7_1R0CyVVmMuy5i0_1LWKtwl0TpxMG36__7X7_1R0CPV0V3pvwy0-Dlm_mv-2y3uAy0PyFCt_Wg0tsi03_uj0EF_lF2V
hUFtNxDtjlR7pt_txEq_ih4_Vlwoh_y8VzdG7p__S_uSsTD__XhPp1y__ulwFsG___c7oCyI_jduosx-KqK1Vj-kVHe024K139J8j_-sMAeEvMw5mEzpAygF
_lof_-oXFtr_-VNF3lxvI_-vHjq_p8_-nFtB_EXFsp_FJzg_pO_-bFtZ_EXFsR_Fp_Bl_gJz-_na_Vlyw4_MNtxz-nV_fFtxtv-c_-Vp0m00000000000000
00000000000000000000000000000B02
}

