sprite $connectors [512x512/16z] {
xC653SD0400mgNauuUs_RGSeXibsZW000000000000000000000000000000032y4M_afJ1y4L-KF3M6t-AtF1s6VyMVUfu4mnWnHXuRmsWnMXuIZs6AcABd
iJ1C5LFbGL266MAEt1l3J377axtxG7gTrs4mdB4rfgPY_wkzvU_bbFYJOeZYYmMSuWUaajYJs2i0litVNm7mRVx-2e1ly_TN07sVlxy1lC_t-VihmEZR_FqD
0D_cxwy0-bv_VmFGz_lx6u2-tz_V0FJz_lu6eE_tzpS0VR-_lm7e-_tz3K3Vx-zl0Ff-Vty3qFVx-ni0lz-_Xmn1t-1lM07e6_mD3O3Vu6ze0FeEVty1I3kD
_lu6CFmkVty1o77Q_FqD8ASZlKW1qFVx-ni0lz_VNm3u_VxzaY_e-_rxo1xupswC997ZhEhVGyI1hcyc30s0twjkRmBy1lWtqvz8GzzAxzy5y5lf_Pi0Vgkz
lmFmJyoXWPZE0lYzW-zV0-XRyVqLWD-Axwy0_5PyVmNWj-hx6m2_5TzV0VYj-lu6m3-Wxugb0F0VMYRNqmM0NukbpmhyLdr_0nhyJdr_0oxuVvINbatx-0Q0
Nqid-ep0RzNt7mBmM_Nz3O1_GD-UqWM0Nuh91O1VoM8k0FpvLm3yLdt_2e3V-e6F_-CW-At3xry1-3UbJepvNzNvbJvr5m3y5C3zmY__oy2w_Dec5Gi0FmMO
mKy1Ma5-RPSg2m1-2W0_1JZcyLE0KBhCvAS0y5E04lpQF4KAC9kV0aHjVWe0FmM0dm8azuTVsjOVVWfmbEQd0F2_antzuQS0hJG_1O3_xUJtP_kp01X_2W0_
9m3y503-kzd67tuAy0m_1GZ6_yzyu2zR_lTbuL_EdnF0mU_tznG0_iNyAS2Nlzu1_tRVd_5Vofy5CC2Fl-xxmx-GFmKmVAyV_ep_6luKO9GVVndyVVml_CVV
12Rs5_xZ2w09Vhy_9m3-fkyA5_n-VnR097xybTB_BEtF0fZ6ZxyC_dv-_Fq5m1z_Fp_-olKeCFxL5y1SVloLo__4t_oBWNkDF_xAvD-ct_R5lnaBu1z__BMj
l_3_G05gZp_-VRFnnry6_wpZB_mZXx_mzom0_F7tyn_uV-n3mCt67tyP_F77ty2FVy82u8__9_dnbzNVF_xutyfkuu-_rlN77_-saZ_-VRVnnrzR-EEF_ml_
hwGP_0tZZt-o1O0__W_muwzb_O_L_F6F_TO__dUotVh7Nmlwuu__iPu__dsxySTVDVtnnnz__F6F6_wHcnz__mB07t_yyVTVdtWtr_k9RwH_8t6zc_YypNh-
nnF-rqFfq-Bt3-Fu-_tnx_ZZd-tunt-y0FZZZp_-Jdw_F_vzFt_y8w-_y9yWu_V77t_yySSV_xQkF_wHOFpnJxq0yCSVV_pnnnz__F777t_yn_dn7o-0az_l
ZtzFx8y__lZZZp_--EEFF_xuuuz_PFF77t_XFyqbgp_--EEFF_vHsX__AvK__im__lZZpmCW-3F_-EEFF_iVV_pnnnz__F777t_yySSVV_pnnnz__F777ty-
_p_mdm73y__uzsVzySSVV_pnnnz__F777t_yySTV1d_yAt__A_vHsX__djOVV_pnnn__LjeVVnNqFsRuunzB-H_FB830Vz4VWCUVt__57t_yySSV_nzb_FK_
_b7IN_Yl-V9Vmlz-cd7zymB0xw-Q_ctK7_yhi_-9l-7unn__Ucy0y0yjLu0N_cFyxQD_2mS0wz_WZp_-QVS__ksPPu3syOz7FlmFSG1yt9_nnn__Hmu0_1K9
_7E_0jnd_Big7m3u2t_yEG3Myuy1_jh-iQG_nx-4_nRhdmEWzlhd063z-mlWd__y7_uqiG0UycVyyST_arU0cM_zZlkp01Z_9_oFilE_w_Zht6C191r_lx_m
px_-MG1rnnz__2a0_FWF1F_a1KZBx_SN_jd7dmN0-7yzxId_XlyF4ign05uhBe0L-PjX_DS-09JFFmphV_4270ikW0N7FmpyfWNWBy1w_EhR-hVrJe3Cst_S
dmN0-8_vPoz0Tluk5La0okCVMSQV1S3uE_tz1N3o-_qf0FmF-n_wUjhk_l6mFmk0yH_sJrs0rFnTAhO058lxop3-Rl_C1SZCtrMn00P_jZ_-Muu_9m3y1l-5
2h0CVnZyaou0nPB-ies_tpzj0PRXj_XJ0FXD_g-91V3xXuRI3Fwv5u1YAN-Pnz_l_tW1ZFv-_YuAe33w-_dnLopXBptk7veJ2Z27d_6NMie29E1Fug_JKe31
1i1lBK3JSCBeBmj_I2o0IGKOvlUFFmKOQ03yPlzJrXLWrTUalvW2NF6mVop5Jm4KZ_fh7Z_-fmmD6F6_bkId037aFqu0luul-HzohG2RG1XUTgox09hasG4c
VLs6yL-v08Sy3J1T_cRWN_e4E2LB0qnNl-_hhzDU05qntrzv-2c055FzG_2_dSDMWFl7WEF2zytzTNunBprUWUUlUZFmPod0AJrSWSUlUJVmvob0avwjm8qh
xkM_KlhVZpwJY8Wx_fAMukyI1HY-zX7nZh-q7py5wBydVik3_dv-2c2_sXt_zsBtXzzRW6C__rQDNpe7ifj_D_1J0AS__6gZ1V3x-_b3UNEEP1__FXAfQW7E
FVoxXPy2-FtXbywnPFVle_mKmERlvm_bps4hWD-_C_xIEPgi_jtEJm76_Vty5E3CvzzdybE08vT_cynF0SvC_dq-FmKui_Xt0py5CFZ3VoEb_U6NIll3BvNs
XrygxG-_LDeVVgcqF_nIQN_ufTB-y4kb_U6NIll3BvNsXrygxG-_r2hxmo-zyBVo-uF_NzEakWN0NnLJsXz-gRG__DA1V--Xmi5VjLFQ7twfjhz4wlg7996g
_lerP2z_-E-ddh_-6hANF_ptKya_zA-GElxwLiYnbV_zuISL_FM3a0tyuHz9Vd_qnvBT7_t19FU7VpWx-kj6o6x-kXVosia_T3kaRUElBuNazaT_FFdzDHII
sr_38NdzDIKafx-cXUJprzIGNFwQ7fB7NuOGWt-o_BSzEXW0001W8EHlFONzhnGw-SS__l6F_nh_-CS__l6FV_pZ7__unpy0000000000000000000000000
00000C
}

