sprite $administration [512x512/16z] {
xTsd5OLG00L1ywEY_sxnA7BOC-k9uzyTRfyaIP8aIP8aIP8aIP8aIP8aIP8aIP8aINgVtFVa2FCNV_4NV_4NV_4N_tZynL_ynL_ynL_ynL_ys_4NV_4NV_4N
V_4NV_5lnr_ynL_ynL_ynL_ynRyTV_4NV_4NV_4NV_4N_tRynL_ynL_ynL_ynL_ys_4NV_4NV_4NV_4NV_5lnr_ynL_ynL_ynL_ynRyTV_4NV_4NV_4NV_5V
7F-jzz_gmtzH_CLV_CLV_CLV_CLV_Dln5t_n5t_n5t_n5t_nRyTV_CLV_CLV_CLV_CM_7N_n5t_n5t_n5t_n5_zs_CLV_CLV_CLV_CLV_Dln5t_PVn1_yHT_
yHT_yM_7N_p5N_p5N_p5N_p5Fnt__wHtBFxy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_wf-FFdpz_v3_pvy-VFdpz__lpvy-VFdpz__lpvy-V_cFZpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpv_-DnPy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-Tj_kEJx-FFdpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_iFbU_Zpvy__qtnvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpj_zW_u4_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VDt_eFpF_Zpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-Vl_s7
nlVnvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VF__p
aoH9aYH9aYH9aYH9aYH9aYH9aYH9aYH98m
}

