sprite $datastore [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000000000000000000000000000WDcd4nk7aIm8edEeG-s_nMi0jTS811E5
5nOK_qjEzFV3lJxs-splZ_q-tFkEdkRlOx_FDlceTtSqoTyYVoVoDydV8dydyZV9to9_9_8toTyYVoVoDydV8dydyZV9to9_9_8toTyYVoVoDydV8dydyZV9
to9_9_8toTyYVoVoDydV8dydyZV9to9_9_8toTyYVoVoDydV8dydyZV9to9_9_8toTyYVoVoDydV8dydyZV9to9_9_8toTyYVoVoDydV8d_R_Fl-Fr-U-eyx
-lFBH_tSygh-t_Zpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-h-xe_UMfNtVqxIXxtT6p_g_VUtf_TUgUxejFskqs_g-kDNde4_cxaV-BUmt-_NKYVv_udn_08dydylU1Vs00Y_oToD-LVs40
Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80
Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD-5Vs80Y_oToD_h_Vjexu-rs2Z_Qf8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP9-7-xziR-V
xVMnln_kvuwUvkzZ3_ClFkhlRccIlqN-JkHlahz5_axaRvA_HVvEv6-IlqN-JkHlahz5_axaRvA_HVvEv6-IlqN-JkHlahz5_axaRvA_HVvEv6-IlqN-JkHl
ahz5_axaRvA_HVvEv6-IlqN-JkHlahz5_axaRvA_HVvEv6-IlqN-JkHlahz5_axaRvA_HVvEv6-IlqN-PlZlz_-vereyzUQZ7lR_uuvUYwT-dU7Fdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y_yNU_MH44eCW03qLpBtFx4xDpPiJooSOE1DafCFphrIrxlalCx_W8y2_blyAVZzre3V4qpo1_BtVG6_HvZa3-Jl6mD-pp397yZVTmRy7cAIFv2_RmtuFSKa
Vo1_tnlmUun9_a3-lhdWvnoJ_87yVNV3Zq4c-GFv-_QAdv9CyWVoz_qTFqIPv4_1xxUM_8nbaZy5lz_QyYEOIVxSykESnlz28JIJ_2du_TR-z0ESIVuK_7vh
SFhz3p39duBVRmrEl_y19lbJyFkj0R__0IRvK_3xhG6__m4c-LFm-wt1s-z_W4d-tCClS-xDltDzlHzWaZzdqVzSar_rav_Sj0V70W000023_ArdiQkw0G00
000000000000000000000000000000000000000000000000000000000000000000G
}

