sprite $tensorflow_enterprise [512x512/16z] {
xCUf0O0030GmsNFTVrlg-3rFuj9l0G000000000000000000000000000000000000000000000000000000LD8RIVL_a77ppoDZOSy-ZYe8WY0AeXd_BUQA
hkl6snm3K5dTNJ_uxd-d1D3_wN-N13Zy__ZtQu3X_yS_lmBe3_zq0kWF_tG27Fxj7wu1Xd_ufrS0_ULVJW3zxPzFWCE__QirmF1l__0AeB_zomcWl_tp2N3u
jt-r1XZ-xHzU0VItVpa1zBT_FW4E__QlrW33l_t3Au3-zYydWFxspoV0uT_-rHfW-BT_U0NGt_xb1D3V_la4EFpRlre33F_s3wy0-jk_d03wsp-V08T_-rTh
WE7V_k4LG7_xbnD0V_ld4-3mR_zg3J3ysp-y0kXl_t82w6__V08S_krVhG66V_k7Lm3zxLzE0FtjNqu0_UqVJW3-xPyE0Ftj7qY0ptmNyB_cPq6pl_spEm3_
zay7WFxspoV0uT_-sHfWzhT_TWVWt_xf0D3V_ka4qD_-_GIeVTk_MGGD__OFhm3wsx-S0FhRFvy0Xt_xLsk0uT_-vHL0V_lt4q1_-_SJG7_xzsi0_dETxq-_
woy1Mx_hBm5Rl-o_7_vx-n_wNNy9sFhypw5_Bty9U3dylxmNmv_styz_URl-4h3r-PztXp_jhmQSm___P_K7_1s1eSz_9C3XB_ch0UVSsLyDuC-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V_mUxzP7bDX04KL2-PXVtFwsyzz9qausg_7iIo1Tmm_pB_VtLdVpZpmd-
tCC__fpYpwtzuyz9_jpKF_vEytSx__XpdZ-tyOy_P_gptp_-dElFNl_ubxFzrJx_-1Ud-rER_EFFgVxxjyR_XQluizm__bp8NyL_gJ-d-kyV77_EzTyzEVwl
NDFVgmL_6t-Ezj-wEluSxhznT_mvtd_RylYN3lvgatztVqxrtt-MyQUFF_7_j-ZbJ_p_8VtynVzlewC_yV-RwEfF_F_K2vtzlOZ_RwEtF_7_TVJt9_u_Znd-
nFydcUCl_j_797_Y_tLCyoV-dsAYF_5_LvdghnxYprn_flipsv_9_bpAVnFLM7yz_1_AunhfNpJmNyHLu_ovjFzohrd-fO7_Mh4Qv4yF_xKNzHH_ElclL9lW
Jpl_XMpj_JNrNmNNsv_6_ele-lhJmN__Xs1FVsRuhz3hvryc-J_QhxnXjmuA88PX60Z-Ba_nPtjYqJQQfJ29RNtPlsKu_kra9Fv607ylWByNmDyPmDy8uEy5
yFS2-3i3-1i1_5l4N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_o_5N_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5__7uvzi-_FFMVRdtwRz-RTj
V_xvBVlpRzF-_DkqF_-sxSy_PzcVVvlsvz-c_VctRN_-cVRdtwRz-RTjV_uvo_xysxG__pRjpxzj-_FFMVRdtwRz-RTfV_vjsvz_pgm_V_4NV_4NV_4NV_4N
V_4NV_4NV_4NV_4NV_4NV_4NV_4N_-VZB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xVZx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_u
Yx_uYx_uwpphV_9mUj8_BqXF-USTwVU4_xyzEhTY40QW0DRmSFdttpPzxWJZ2sa5xHa6xVyp5Dh-PpYq-y-8A6t-ImP5Y_yCZBF_CpQsC_-t38_p_ZC5pldF
DAZ_dvbGwlwNJ8QQ_vaGjVupAMhyPruS_y_KEFQVwV7_VrR0_j__daNmptyMmg__MGo__6Szb6__IvP4UVk__ZwV_xCojlV_MnR7k_zS0A_-Sn4y-yzryFYV
KG4000000000000000000000000000000000000000000000000000000000Dm
}

