sprite $cloud_ids [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000000000000000000000000000083PknCqPtaS0C8yo95y_mlFwjbwyf4co496zHxWNoZBf1sI
rAOpeIUcRxoyeBzXUUXCwAdf8Ri6_H2pp-pVIMT2hvaV33-iIdwmzuFy83_83-ldhNxg0yOVv4TViJyO_zUWCv3VXkJZ3-x-uEx_KYVqjpVwJKnJuEX7Q-pD
Z7-kDuWLtFuVGaHwjrJMosz7ajSNwO7SvzyO_mlrW_i_zAz_EvQs_e_-DbkUX_wOV_cFiCj6_pprm_ih_VFK3-zV-Sy_qmkQDnaE-fixVL3_yucoZlwGR63w
IUtf_SsDo0tzcpwh_-cSbdNsZ_l7RVt7_TCT5seyfzcFdt_Z-3y5EP3iKXdzlScXP1VAEFyDY7-Yltr9G_fRdVbtkEt7pR_nzEVzv3UoNQIUNDDhNaTywpls
TzZwO_hRT8lDVlpyrtl-AzrQaTyBg-_Vd-S_hzGVibsTpWcGXSGV8Y_Drm-0fZefqCJaj5HNXWrWC8VwqVrVKpy1y6cJO0EGhoIuAcm03kS8ygMWE_yPz3zD
lkPyHTW0uby5R791mELePx4074O_hZyV0fsdJQi_-5qAxW3nNlVtDnP0glhn-x-n0ExGn4FtO2o0vUeFtOUn01QhFtGlLcy1MEHdUBph3-6Nm_zPK2tb9Qww
9pFk0QlK7xepLi0yCa5tPxsOWsdr9B92_yZrP6b4p7xk_j1vDlblzBTIPAZO7p8NWvf-zfb_Pf_-rAS_zKlqnoP2VqQV_jH_Kd_x138m_ym-_QbFV-hJdp_u
wC_eqv_wJ-flPf21-MVuq_O7_K5_q1_q1_r1Vz0Vz0VzGN_G7_G7_K5_q1_q1_r1Vz0Vz0VzGNz84jRNGtzs0_gp1kZFpO3-x0BqPnEWFvi0_La1z6S1q7zp
qBEWFti0_La0z6S5q9y5G7-EW-ZF5a1_5W3zMG3qPm7GVv-gPqP_TW3wim3epmAWFmk0_fm4qfyDWFui0Fgp0EZFIm3wim7GdmL0VzD_io_qTT5Vh-kBOYTN
7ptMBl-nPoFhK2-Crj2grHzkhx_0wBTF4jHFtN-NnIMwSwYpbNP-g3lg_yvsOCtyGuRys7v3PrYbFdIEqld9hwNpar-hvYV_G7xwLyjFVlgJVo0__U_BZ_qJ
fN-qhSxuQs3-ByxCeRCn_lJFcX_wsFvx_dVWw3zp_BSQhmFfl_t1BXz00t3xft_bnpst8n-BjDhzJN-GPtbwV_gVVBx_5TbVb-l_abDsMKqx-X-cVvEdE-fF
Vw4__PzqfDEkzAV_wOzFRdET__SzgJ_pxzkV_bfz_rVnHFyscNiJyK7__EXF_qR_e_wjrlal_Q-z7Dva8V7z9Nj_qv_glF_hl-FHFx-fNm35yn_RT78_dl_Y
Sq0y_okjtlFVz3-s1v1eVFuZhaEylVBdlzh_4_3vppMrWSz_H_L7-wJuzp-0_ddHdmNGP2Q-_mqb-lE3Jtp_A_Z-P_3zxp5O0DRd4NY-yk7tN_86ulUVtceE
p_pmC12__tQlzbdHttzilv1t-Da2UeGcHreA1LS0l__Cxx_7sHr7drrWiVv34pV8bHzo0qjpz0TPJlS4yY-4_jfTeTpus_z0xTqVvAT_eVps0sgFFshdHwkT
7-IdV-7y83_zw-P7gvqVv4-B_jONmWBOdGNaH_6z7-pzzAyx_DZ5LtFG2sC3A9sV_jrREuJQDtuy_1bl-m2rHn-F_dk_VOJQauzDvah-jpwAZpqAPmVzyRZ-
eB_z6chFF_RQ_L6yFmht1_rHl3yAzmVzKRm_2lS7_L6yFnRl3_hR1IW-_oZU7yls1_tjCXIVVnJlZ-BziLn_qD_SOC7-vWZ5ztyKxu_Y_L6yFuhtH_7-gDqV
-mhzspJOQt_1BpPnLZi_2w1sVXP0NmpqbRM_QLM1zV_cbRC_zNyoT_fF6VjhECkW1z9_ozUVsN_FU_Y7PFsD-hFf_sfv-fF_MFEWEcK1h9UVuHzUuc31_EGV
NZdwA_d3wmyP-kiDo3-qk_iR-UVIOtVqP_ejx0CH-ebSCtjzjc-aFmnCCVm3h__2zHXDV-Ms_ZPuJoRvJyvLQ7-sW1x1z8J0_Yo0pnSX_e9kqVtRJpfTQyC2
uszJwx_U2Et_nLsRk__itTIXFpS1l_uQVgHsT__kiGMiUFJJtekV8k_-yLl0A_iJOMTEzkBFqwVtls5ysn_O0s__UjdK_hmAQ3E_5ibdTvlOdxS4JpxTTSzq
JElF5d3RfR5J_FktCwnEVprsr-Qu-VPF-XwEQRHrRewxNtz5JF_uFI2sFlrxxA76YVx-JEblTq_JfVvsaOPhavr-MNonVtDmeh-tDZktndBf7--E_iEp-Yzx
DhAVws-EPhwXK-3rdnk7-USuSEtNn07zawu0-W-N-hC0pjufS_KVtlUtgJZ_JJK8F_hRV4_T_-r8wesmZVvHrXx_eIFnaN6Rhiy4pUx4OOdsnw7_YGU0-sbu
pWc0MtuMmEkD3Ft11W1U0Gvc0n7_sfvTMm480m0KnDb_OgodWNZk9a3-Yne06cOBW0400M06m02001000kY102m21R2Ky2Oi-UGS0Wm1LW4AM1w604D0aHV2
_x6zsSkHvEShm7RGH000000000000000000000000000000000000000000000000000000009m
}

