sprite $project [512x512/16z] {
xTq7aXmx3aNHZXzL111E-r_j-EanRSJy3fN4kKlGmtqaMChe7_yD0000000000000030ivCL0XYS_uh9-TC_Ol80q7zu_lJl7G0yslMFI35CrR-t0B1wzJS0
z1-RlwSV0q1_-TE_PG0GBn7_r1rG-oi0kvy1eF_0_5t-303zvK__bW70Mxl-7rbY6QF_z0Am-na0bp_vqzy0q5_-Bdy6WFuH3-aCqB-z0CJVhxz78FhFAW2x
tpF20D1V_k8t07O_Eo3z5O3Tpm3GN_xqDm3qFpH_-Z-ZUm3ahm34FxC0y7Xsire7WFuAGFmAGFuAGFmAGFvsGF4x0Npk-we5a89hq5y1YDyLKFuAGFmAGFvs
GF4x0Un-FGMm1DYWlmBmlPyh8FqLWFWLWFpjWE9t0iY_fm0USco8Nm68toEG_1M0-Es0yhS3Yby1oDyEA7vNG9_xEW7ehm3yxAy0wAy0nAy0vEyHIFpj9m3Y
-JlW1A2_0X2_0f2_0X2_0f2_7L3yJW2V-pe1wAy0_Ewd0EYl0CIl0EHl1nI_4q3-lWSKlm8GlokW_1M0fny5G7yxeFYT0FBtGR3u5O3uFGB9Nm68Nm78Nm68
toEG_Es0udS2o7z53ivV_i-ioVdBlohdRe068AhgclvuF8zXLLNbrFmLGDRVkTZ-E4h_gfnfl_op_ib5_N6K_bKvKN_vrpi3ypS0KU_ajVWHHxJ_xW0ypmjG
0SH-_kB-o57wL-Mi-EMVzRzStFrmbFvLUKr_hAFqhngalmA8-a3EqTy0r2V4fxoTbvlyesgp0DQD_abM680jLdtAxz3-lV7BVu-iJybxwzzmMJbA_wfxwo__
VVrt2-1M-Xk0BQA-vBUr_wDT_uWq03-ZlYPls_xF20MmHTGt_1RzLw_-1c2BLT-HjzLV_djaVSjjdtuCm1QhlYTlgdzV_eyZzFzO0CzxwQy0DlNVBO0VbuWN
YTyEkA__v-Gjsry1x12rdV-jTZy3iCMg7Uwdl_otzTyjW5jT_Wp05glsk9l-U_dxEy1PUsJySY_z5S0EgtQ9Eqt_Q_olvOFqh_nnB_qLm0vHkznizpC0MzIH
-iUhvB-EqN_TIty5q7VvwzT_8_zn0-3ofm3e7_4OC03qLm2D-ZzVM7-FGE_KGFqLmFNTBzUTbjw8mGFWyhVsyZS0CQFz5O3TpmvezrC0Thzt341Eklprvn-t
lVoz7Q2_0h3xsG4xTpz_k9R-2c3mxgS0rldwFvxTB2T0_-wd03x7vKy1l01r0_qL0FqLWDtF3cZtymZKel-wwyVkA_R9XW6m-xa2Th5wszyLqEwd02RlVWeW
iez-_Us0KNtqw-y4U6IzEXaDkrz30VHy3xYgaVxsTmMCmzf_FQ_W2hZehm06N_xiW4b_E-1O_Pq0Rtb0_E_v7r00ZuOheFPt1TJ-7e7ehm36wUyHAEbl1nmR
lmBuaQDtFpjWqF-FHm7iamr_uzhlWFIt0_hPt--0_JJehm2qlntGxkSHYFvEW1lf7yy6x83qLm0d_Uwd029T_XI0zhS3qjyEI7-_0pRet_gvhnsG_gw0St_t
Km1lsSdroz_W0i3p0mf0_dP0yJi1vEzxGF4h0F6x0ih_j0B0UcwW0EXl1nI_4q3-FWWMlm8GlqSW-Ii0yIi0-Ii0yNi4ahyTKFnE0Fbt540Epb_-pwp9-Sk_
AkTkW0OWgkgQ_dWyZs5LLUNK_1L0rj-vsFuuIl-gd6c__BF-oKNzSPJ-LJbHV_dNEmFpDm1Hx-Ir-157jF_k03pF2r01n7x-ulx8KVfNvQpuvP_rlrpS_N2K
_bLvJN-ie_Il6gI_0eZwGCxHtm3K9yIdlCtv9rqn9V-esYo0DKUf5J6a05RLRW4CQjI86580MP-Iq_KVKW2hlc2u_bCA8EiBiZV_Hxl-4Nd-04JLPW6iOVhF
E07gQxAp_LUt_ZDEWAXl6Ap_a09OzHqvzFAt8eOKGDQtZDL_I06i-fuShtz4szRIhtzLqt_wYfU8__WTSDNFoA5FFpDEWAoVabDtlm5NmAYVamFr7r80gtOO
UFaRKW1HE-Gu_OSKmAezw1znujy1pjeZuvS_DVwtTlq_iiuhW5MxqF_44o1havot-msu0WRzDzh_t0Ae3UZ_gmTW7QF_edzV0RZyzUlVFm3zbp_wHpmEo7z3
V_ft5G3zdo-YVyiZKB_-zEyl0BjVl_w7Fm95RPAB_Wq5eFrxuXyo054RsFqQTi1E_Ua_f02oDh3xDLm1E_Md_v02oFtuwV_R1o1kU_bxetz30MZ_5g9x0En-
2e3-Cml0xlSu-M_Vh-S6z5S0Thz6rja3uFAd00veVmL0VpkWozyn9u3Tx-tvl641vDtoNrC_-540TZzNm3NrygS0x7uAmExNlmD6za7__XCWgW-xtnzG01SN
fKVMgvCD-iyfW5MlJlYRoUl04y3bJm6u_2a0-dVlW5aRqDyEIFzx5C3ZuiARrO3uNG6rVziZKFy9G7y5G7yx8FtxTy2LzLhGNm44_V-q7V17Ql-NmYDGD7pk
E_W4IFflO0Vqixyh8FsxY36_0tR4hm3iVdCVWNwazhS3JjG_ddqu0UXl1_Jmhm3wzNS3IF7te03iVdP0-ji1e_bpNxy3qjyEw7S_Ly29-Yk0jsn4_7zc0U3v
ZXrG_4u0-PzO0Eks0ObV0OZV5L3-2i3JZmAWlnrG_4u0-L__8FYMY5y1YDyZaFmLWFWLWFmLWFWz0idV3YX-9u3yL-JW_EN_p9gSl_ohSku6Q02YggxfZyVp
65PLLKxDNm5a_PsBxO-ZzA_AcVRBF-kVNDGVH-bVbHFrbt-zCp1_0n3rJbwB7t54--yEmFEy01L0xESlxeySfNzLpefV_bd_oyNT3qVfNvNNzCSwIl-gGVeh
WAWFv1pz3K1zGdpAstcvoJ_g4t98-nk0LPyofFtbd_KfUL5_7AL_rGZzvP_r1JaWVmCGzIK3sjy0rDVaHVjnbFvLf-jl05PzHnwkl_oplkMg_ZX9_wgyg3yU
9-bVTVK_VU4a_QlogluuIV-gF3P--KSDpjy0hDhXrFZb7xL3NiqV9-bVTMRy_WvmrXuPluZq6YVfNtLPVnoaV-M1-SW_Hkjl0EgFr1_h6FsNC7yDmoz_c7tv
mt3zCLj_3DSVitS_t7xtoyDsFmEW_Gr036j_-TFV0DZzv4z_0v1_Plo8srx-teJtUp2y_J5xzyDm_J5xzyEQhJ_iVjqO09S_-NUrFsRhZ-6NFzZzUf7_wlpW
1tQ_JWp0wcr_3D_zC7ltmpEoZtxz4TL7l_vuPBqw-GVgZrMDzBS_Glih0FehW9dwuvdqLm1ZzSTRZeuVQtRx8-Yl0EYl06RgZvNqLm1puqTg_quK0FqL0Ftj
WFHt0j3Vxu02-RE9sUsFrFuAWFu6WFvsGFehW67w8rBy2c1k-oFfhm3ehm3eRmSSg3zYjFvuoqREZXy000000000000000000000_We
}

