sprite $cloud_healthcare_marketplace [512x512/16z] {
xDmh0S0m5C10-bZzkvs3elrpPo4yAmS00000000000000000002OBGBzqH_zqH_zqH_zqJz0V_H7V_H7V_H7_m3zqH_zqH_zqH_zqJz0V_H7V_H7V_H7V_Hd
NGm00000000000000000001WyFz0V_H7V_H7V_GFq1_zqH_zqH_zqH_z0_H7V_H7V_H7V_H7_m3zqH_zqH_zqH_zqVzQ-WC00000000000000000003C3lh_
dlxeZ_xeZ_xeZ_u7EtTX8r4C157mRd64F_zebvb52ptr4h3Q9LbiyG-Fl_YBl_YBl_YBl_YBVtRynL_ynL_ynRzF_CLV_CLV_CLV_CLV_AqFZZz__lpvy-VF
dpz__lpvy-VFdtzs_Fdpvy-VFt_-_Fdpvy-VFt_-_BFZpvy_V_xy-VFdpvy_V_xy-VFddnr__lpvy-VFdpz__lpvy-VFdpz__h7nvy-VFt_-_Fdpvy-VFt_-
_Fdpvy__m-Vpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fd_Glpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdtzzUVpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__Ydnvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_d_Wpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xyS-FFdpz__lpvy-VFdpz__lpvy-VFFpl-_Fdpvy-VFt_-_Fdpvy-VFt_-qV7dpvy_V_xy-VFdpvy_V_xyy_tvy-VFdpz__lpvy-VFdpz__lpv
yw-Uu_dpvyy_DtU0dp__v_LUphzw3-TVTiSsgLVgoJyPF02xUe_cNzLqClzZzYPMRSFFd_-SzCtcmx8zEo4080XX8ERVDJA0Dh4mtNjT01n__VKt0Fdrrzy0
vDTVVmEGtpS0x_uk08w_0SXl0FBhhxy1o6y0yXk0_0OWlm78Rm3o6u3y1Y2_1QXl0FBx7NpyXoyElmMeRm7gMq1nVSIdg3q00000000000000000003
}

