sprite $billing [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000000000000000000000000020sRjln8XX68g2T812XVkVrZddx9N-l7wh0K5kfHrN8SqPJV0_
vcy4fYh-EytHVzFV4YZ-Eu_-A_vMG0NxMm6Z-8TqxF0_zdS7LBA_0HZH_gw0uXyM_bj_0r3yavy0Wt_q4w3uHvRDpt_gvX-_02R-iUKUV_xy-MVpyv_uPyS_
ksn-_XF_xFXl9Vxy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xyjOR7_ph-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdph_3cyFXlC_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_xy-VCV1vtu_shynL_ynL_ynJye_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8ltt_m_GV-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-V_-77dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvRsqU-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xynplzz-y3_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VF_zjn9y_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-Hzw_Fdpvy-VFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VF_-f-IVN_Fdpprt_oGF0l-Fz-K_H_lmxsXz_Jz7-_3lQ7tyF_eaTTri0sV_z3K3szZS0-BEV
02x_w_WdNlu689lV5M3vtyS_xUbd0Ep-g0dWtsytyG_YjmAozOr0zhrl1E1BEcyF3WW0040G0Fr_tOrK81y0000000000000000000000000000000000000
00000000000007
}

