sprite $os_configuration_management [512x512/16z] {
xDor0GC130H1ivIf_swTEZ7ptqmBUuR7UHa00000000000000000000000000020FZM1n3S1zIr0VGkGtm3aZnY0_0OWlm78Rm3o6u3y1g2__l8RWFxwosy0
-gC_-WUG_xy7WFxeZ_xeZ_xeZ_xeZ_uS-Xw7MGAS_qT_z2SuF_eJd1_z2SzFTduEsQV-gBwcPi4e-GqWDZ_U_qPwVYhzgnyVVUfh7tm00000000000000000
-ZcJINqBaDy0v3S0_T4_Zlpww-y58Vht_0dqHt_qPnVTdzBVrt_A0D0V_T4V_IdzB_Bnrrz_0pYoToPNeE8m4BpuMRef_spdCliERK3zLHK0hwsIsJ4F5Xx_
vWNLgxxnBx6594rAZd_hWkhFMmB_PwzWbjlvbhl-fA1QlTtzBmggbNjx-uzsVwftkzZUrlwpc_vCB_sP-BSkg5vh_BSig4wShI7-pRvBwNWIdSR-ru5GBKjj
x3zQPZVplrlwxrRgxUK_Bu1_ruBYNmV_YVzUzTH9_BShAFvZj7_yvt6YTF0VbpOQ3VphbRwsWN3th-TLnxVp6PQO9OHw3l8l3Z7oAVGi-B-rHI7EQK9gHFpV
tM0B-tgKwVxZoPTUyotk9vb-_XVIzeJ27KOOmcJ_-l2_dVnwZk3-ZxWvOTOSHOYFVsbh8TW_o3uGtj__FXatRcqdNqHFSTJ_Td_-hsyhyZkE5e7tF-vKFx_b
HWVkLlvr3lg_pCglkH7wO3qxy8b-QyuLj0M7Rlvi_0jdmGR-cVw7Ar5DGFz5rfc2jk7iQIyxWEsblzRhqvyZmAf6X3hWXVzh3H3LYdNshZSD44QpNt_gdVWN
2je3QQpp40jgklud-lMwL5ykXCM_KD36tCYQCpbJK7zYj7_8f07GFv2eUU2V7G3wQG3qun__YVxP1FvdW_wnq02HC7pwmspzi6Vx1_GFX0ROEHdyvo_0RFqG
i_q3-aT10wpyFJ1y-iDW_O1_cAqVOhP_uEH_1lXFm3-m_--p11l-twHdfIVunt_NOAiUXmRmZQP30nXa6qFh7IpwdwTrXN-mOpyTO11k7gsVhQ3_ULe_MWi-
_tcUraTN9l_pjAwmltuQe7Eug8BeFC6y9p-x08Tiq7W7kr_G3z6tnhxssGNu98CyZrCoY37-2zuej5ikwFfGzINzqBJEhrsHGiz2sqr-6i0q57JSpwxtCa4q
d6blHeA6_gtquzyW4k0VyEy0_iF8F_wzCW7-_S4_7_dXNmy5UxH_Y5GfJW3O_UE_5VW7_0F-0V-0_qbm_HS5tFy1dly0_W7_WFyvyFuNyFudu1_m3tp_1Np_
2Np_3Qp_0Ap_0daGWrZ0-c_0-e-ZOFtNNQDX_USeOFttmV3_XoZW_o_0_vy6ml_VM164_p-o2-3_h-Zd_y_6yFzt7VItR81y3VG_ZtSuxEjOXqE_pkeS3lql
u9qD_JfcqT1_7hDW-3-FGIhyFypgbGZ_CDO_u1_sHF_0yH-u0G25V_pJ0EWVmShV0p7r0I3m0W0K_l5F0w2VltpWVmgPm0lWKFZ7Fms0_d54GjHW4ceqwCS_
_WU3VlpZVp3edmeDiAfW-FI7sVeXyFy3SNZ13VGxTSpDGVAzdr3GxWTo_1-kYzrf70rmk2XkP_7uFrmJj-zvuk9WqHzMTuv27U_AMOGw7yBjQpvs06UhiQeF
9ovtq7_nqmWh_NhBi_V_CrRwQO3pbJ3p7_zhfyVq3o__nzkUwM_L0FbX0yJtBi_hz_AVd_dlicZp-in_sllNjnNv7T6W25PVyTSJPpxv5K-S1PVPch6Ph_T-
21bKz1WF5jJVVztSHBwF7X__ruy0NTuXl3K0_CTpJxtxtC2HVCLm_t7_ULUVLpSs_c_dLSRPmBuwZ9pklwH1veFeMHR-_njnY0tiAqF1VwdZouS8DKoDzn-N
jXcFfdghql7x3Gm__skLgcbq_Ei4_cV7VUdWZ_yQuhzfFRty5_uz2uf__EjvD_xFlb5JNluB__qAgdDsjJFyBo_z5HtZvc4QPW-px_-S_LDGDM_XtxUWUjwD
_xFN0DMAI_hnhpT0DQDRsZmB1LNo5luD2YgoUbsd-2_K7gtIk2rNcIUXe3SJxohydpmFhFO8MV6l5TGV_Ei0_Y5c-uTP-W7_W7_0F-0VOhH_M7cAgCbm0FYf
dVic0106020uKRRuTui45ch-pi9JqyRdeJ_wep_wep_jtp_2jp_w4yzFFJ__gmy00000000000000030bjtUJtYV7rlub0zizfNV1U3HxoKWlmj0_ie5mBgV
MyUiSEIF_2u0-MCN0FgJFVKF_N7if_xwww-_eR_S820pdVkD_kYF_kYF_kYF_kYF_XZ_Ht_qHt_2-T6VP7xqn_ulxFyadfzuVkBvYUUddfzwVVBrkIS-0000
000000000000000000000000m04
}

