sprite $automl_vision [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000002OlJj9SzM8WZ0wIPFCSl-hTJE-xcqfUCGvA_1NFu59gQZtPDpliKyp_UzJJ7uN
WFwzv7S1w7-T8l9Fv-zZtou0yzTV_XSvw5z1VXU0_hu6aDyDmDdF1M3--ill0j1_dHJvtG3qTm78hx-pdml0_FMNtmMWlmj0_dn_rkq2C7_zdVrS0EQll_mk
0FrT0FBhx-7F1M3--il_6WVzaP-xptL-XVbpoT_6_Al9Z_x8pzrd7So_bVpeZ_pSVVRv3UPFQtxCdor_6_El9Z_EVfW_yhSnVvpzCFz6ykE57ymV-Ol8hx-p
7-QF_BJ-T96VrVgbEkRFxicF-IC_-YC_-_LVgcF-o8_-o8_-oC_reh-YYVaZF_eZF_eZF_AZF_AZF_Bp_XT-C7-yy8Fv8p_w8p-lV-47yyVP3_D7VlH7VjRh
N_Z1_94Vl_M1-QC_yhD--FoOF_AZF_BZen_C7x_qXVaZF_eZFyv-c3zNKNxC7_dny8VvyxaNVZ1_VE-7-IC_k_piPsx5y-T-VV_3N_oug-Sl_xsxptwEskNp
TzRgpI-__lhVrVdblxlFVlhVrVEN_zxT-NtDMjQV__33yj7FzHtVN9ll_PBvy_tlshk_-UVxB_cdB_-uc-Pl_jDLaj_yxzzNrT_yfwRyvZzLlV3Zx3VLpT_T
Fzz_oJ-5FcXjch_vJxifluU_gUg3V_EVyldD_wVWZzilVVsnzRxvJ-dyvhy2F-vG_ot_5FwxYatpz_0thQRvE_jD9Kz_vf-_09BvpJ_V_-Jpc__KrD_yypU0
v-VVx_pUBty1h7X_7_taRm3v_Ex--Gl0ztwVyzo_cXYTl_ddRm39_EQVlm1s_Evl_laRWA_zimlBNm3v_kQVxv_FBt_-0l3mb__fxfB-vf-_0KJpct_-31Zi
R_xv_iVyF-IPmvgwF_hHVxlx1_A_u0PmFaV_AtG3oFUNFty3yF2N_-sgyptct_J5ocJ-ZyYVlm3CNt_pp-VFNm3v_Fhlalxovsy0TVFVWRFVQow0yn7cd--V
dx_ysGl0ztxwv-SlV_u2oEVNVvslMTrl-_ktbCq__KfT-2-3Tp_y-STqI-Q_ilcVs_yqtVtDVzfDPp_pdwhcR_vJq_pDVpB_V-tw0VDFJMS_T_-fQlxk_bDJ
VlEVTjF3d_bFLVCt_-a9_UNV9sNdy_lUxpuvttuXUPd_S89sq_pT_QUg_EO_UUCZaF_1_SydfUTi_jFuxsaY_wdAx-mtZLz23p3_dAhvU_YRglAR_zJKtqS_
KrL-yv-IbwFyULNpz_0tDUKt_sarzVVHprILt_odVIByt__vMDNv2UJ7tH_pn_mnVtplXxCVxlvu-CFyyV27-IC_Vki3yyVP3_F7sG_pHtuy_67-c3_c7o3_
TJ1_vCVtVfW_pdwO_zl9lyw7OFx8ZxCVvezV-iByaH_zaHyV_6F-EFjX_iYFF_I7-UFiX_cpmo_yOFx8Zr_wmlnnziFyyS8Fve_yEFjX_ZZxOVx8Z_x8ZuS_
p3_F2p-OFtUXW_x8tqf_v6VTVQw3-RUI7_sHdxlFFh_2_BdkFkjW_iZVoCCVvjzCV-Hdoz_6_94V_Hl9Zuz-CFz6pdwOF_AtqX_vMSv-RSmV-NlfZ_puu9_k
-LF-mW_TysTrvwUyFztvAJ_xqJr_TdT-oljJd1_zASwF_dJdv-hEJtb_YlEZFztvsTtV-z4zVrPtVihl_XJF7_tfpi_kVk67ylbJd1_zwSvF-KS_cF-R_D8U
7100080W0Fh_kXcL0gS1000000000000000000000000000000000000000C
}

