sprite $network_tiers [512x512/16z] {
xTq7ak8y6uLHQkonfkBT_sh_w2yd5MqXo-yvI-ZdMZHW89S2000000000000000000000000000u_YW5IDuh1UXk1yfRWVHM8BqDQDzdJr7QEmUqjm7nJK3x
qvuvs8-RQ7akbxv70l4jG7mJKDy2n3S1zIr0VHCGtmBKjm3rBK1z2r3V0jIt0FKjG7qBaDyz0kex0jJlNm3VZvC5kFWDG7qBS4Ul1RZu3K1z2v3_UGEW7Kzc
0Iv-0v3VMmBgEmBaDm3rJ_8NLpm_rL_kf_Z5J_7y5CzFAvwVulKfdf_Y-QdS7mDWBpu0KiE10M006006W05W01W01b250M006006W05W01W0RWWXjGQ00M00
6006W07GoWq07mt40300380K7W06G9Qq_L6H0HZ0Q_jBymQmxl2obkqVV3f4kXd0b-rRXuybo1iCu7rRh_5__aVzAzgMpz-_W07nrv_0ClNd3o0NCe3hylSl
u5P_9WFehJzz07k6sFM_FFzflsu0tpEG0NJadpc036S05-S_NV7dpaVetv5_mW3Al46rNlxn0sYLVgzyjVpZ1v2Fqxyt__YdWPd207hoZnz0fl6ny9nUswm1
P2e7GCVbFt00cSu0ElAFUZCeMM00-WyQGEdxLP-PVtjr_vLRxHyoVsR-_Zk2oj-o_j3-hwu_SilDjBhtWktRfT8nWDnGsGDW-rZ_t32_0MmV7a1kgsJ_xPFz
SxVy1h1TxLlMLQ__QxjS5jQg3M2RrDyHeBy1BDtV0DRllqtjRm25-nk0_WQW_otfRm2VKRY_0UXl08Nx6u3-1b2qlm7eRm3w6q3X_WQWlm7eVr_xCPR-3e2z
zli_1g3_dHNjhxy1wA-__j5_Mdu3q7--lUm1eBy3GFwaTd_zK_G1G7y7WFmE0FsR_kFoEm1QPj6_amFWWVdrZ-z-wlJG1u3NvCjV_zRQZvPfvEyqAFt_j2m-
W5UURqZw-VtZykyp9lty0UpoTzc7f9_VFxlyNSQadzy_ydVPHwG_PIhvkun8VsgPIluURK3wU_IF_3s6f3_xpoR_FnkH_dIiE81NYXcG_jIotW1IJaVw2Vtd
B61F3A1rfE_jlzO2KjA0zAVSmqlzlzCw3lnb3u2J-d-Z8_tg_PDlul-LC_w3-vy-6zy0McxeS__kEm2Eu0403m3eZ_wb643k3GS0-jCAz4T_zCSJ01m0w8_-
w4yhsH_zqP_s_5l0y0yW7W3G7_tH7_tHdwDsVrhH_kYF_lgF43m1G7_qHt_qHt_qHt_qnnk0w3_tg3eo6Hwgq1_zqH_zqH_zqH_zqP-A_V5P1VJ7PrNqhpC0
F050V_H7V_JNVuWzI-2e_Mt5LEcFVm3G7pzNWP-hG7_qrzyhG5u0621u043_WlGt0FtH7mD0V_IlH7y3q1yF01m_Vb6a_ycRAt-gxWE0-AVs_FwjDV5NE1oF
4UcF_r9_YNiaslNfJ-glS0Qq0Udx-lj8rHBz-zCRm8B_91zVA_zBUltt9PybjslI6y2FjwpN_opVGVu55j2kI6y0oxvITbnmuEk_y4lbxSjNlVuhlrVIHgG_
oTzdQlyHwK-x_5sEp7Eq4UbFyYzm08n8VsfUzkapi_-Gz2UNVwUP_TzFRm0F-D3yCP8RA3izjF_XykzKih_yy_it0nZNtm5moA-__WPGDB_-JVykxQ7z3_tx
n02Uc5__G_yk-kjl04lbrt_z0UZ__HYjwUy0M9x-ymUWlmDWlgQ_o_z1_R-Npgz_vDU_Rdxz8x_-TVFh7_drbr__cldrZ_pwryslV-Jlf__JykiV-VMVbb__
bjbcvjS_qydVxP7z8x_-S_Bhl-S6fkLt1s3kGFvUp-mV-JizCt_ax_NC_fcIN_yZTo5_d_sXFvajVwUd_cJssFpRB_QS701vGl-Uz7-KE01oAoFoVzl-HXQb
VsV-xH-Lxf-RkJR_Q-jITm1xxkRA_5ktgWF8-lqxwdVOImuWMNu07VNx57mVCBVqyVodLnRppFoPaFzKQm39yWDulxu1vBRQ-Fm6a1kRa7_L0HmFp9_Co7_A
QXwOFta__xuPmEhraodvJtdw0hA0KK_y321hc9T_U-Mv2sXPnBZyXTyHFhAED_A_jeiyyuD1MSk0T_nwVNlURK5xbZCZ_-bPDmUtB6d0xHxJ1l36FQiCo3-Z
_txPfnOC8CFxdwQ-ad5YMlvj-XiPVwH_FjT_6rU_Vm5Cox_TuaOcZbzaGl_Pzx7I-HVQBdUFpp4mAVysldx_00mWA_M_-cFC-kVp_RVRV8s10MH6_sM-neHj
X0dvbn-0_WM-nKx_0jzYgVys8V-g_VNt9TRwxqVH0UZlHopqF_JNl-e0z3-kisSj-liDG_qB7m3w-mbZ_VNNVy80M3Q__lglFm3zzzBzzJ-czaT__QS-_5SU
WFx7tFwyzB-K0-1RwVxwPwd-FA__aMdqprhzsVM_Z0FWLRg__gdStm1UfViRG2htrpzL-nk0_ju5IEN-3e1Kxcy0MRW_3-gV2GmWbViRG2htDu2ywGdz3M3F
4_hpyVnPFxy198NxMq2-PEt-1f0lMZg_1QHmVmF81LRjxwRGNEAU-HbV_xHUVtS5v48tpi_GzgVQ_P7_6WRGiY3ssfS_nVDJ_BkVSVdhNpW_nVDJF3_5yrCy
FwruVehdf_ZBFbI_-AcUd-BrsQlNftfzn4Vyy4Pw0000000000000000000000000020VmC
}

