sprite $workload_identity_pool [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000000000000000000000000000000000000000WDctRmHLOYYAWXYvZFtlbfpiqNAW
EkatO-fgh7gZsjG4VuzCe99OLJtzw0l_u0o0lWNWDm3y1a3V0l0RG6fRfNJsyHT-0y1l0FpvupS0_0R0dx_VzxiFSCZn5_-EySTl0Fpvy-UFtm3uynT_yHT_
yHT_yP_oyiL_w_YBl_YBl_YBl_YBl_YB_p_7N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_oVduN_Vj_Aw7xGdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvyt-kZZ__Ixd_mvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-S_suC-VFt_-_Fdpvy-_J_pvy-VFdpz__lpvy-VFdpz__lpvyu_-
FhvTBVhoFV_Fdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-SVAkmVVVNS_-7Fdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_p_zx_fy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdx_vFXzp_uS-VFt_-_Fdpvy-VFt_-
_FbFYJz__lpvy-VFdpz__lpvJuu_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpz_p_tDVVjGhxCkVFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vzyx_lpvy-VFdx_uYx_uYx_uYx_uYx_uRnr_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yTyo_lCJV_4NV_4NV_4N__xnDm3y_Fdpvsy0-FdphstJ
L5y-03Z-_FaR07u3mC-Vlm7WDm3yFKjjgvI-j_G1mF4t0FmMGDy0y1i0VWkWRm3utGVm-tuV11nz4u3_RWyE10000004-LjFi46r00000000000000000000
000000000000000000000000000000000000000000000000000002
}

