sprite $developer_portal [512x512/16z] {
xTqvchFA4WHG1oNbiV_TlW_xJRS5fIIeS-n_o8f8QFM4Zfi100000000000000000000000000000000000000000000000000000000000000000000CFw7
uwtOnn_innfSyUu6hlettWdOncss8mlZTaSwztmV2rpuRWFAjmBQjm4-w7ife7mhuBxluu3sRO3sRO3sRO3sRO3sRO3sRO3sRO2lzlYAa8lVBK3xDa3z5a3x
Di3hFgy3NVnk0Ugt0Dgt0UgVjm1i8z9st84HwxYEdtr-jhzy0TJVy3zUGerxx5rVRAgZcOi_zRzd7rVjkICmBegUWt59-2myx5LNfIo0-lD7ufcVSDMp5q3z
RvYCxT4P-tRGCnDUUJuBiFA05k1b4_By3wtRG-gt02kFQ05UEYC9drLjy-edudkhUrlz5c3fAIs0ARrPrw9JMe2bnxG0gun9oCzKxZ-htm8iFQS5M7fE2x3q
d1PWmJb9-MsQVMxz5c3HEKdvRTgQKpyfFqAxpQcVOT270m0000000000wdYfgkCPwZyIqroFYBZ-3pdDqf_kf_wHJq1GURglhlgJWAIoDCTQVnOGLP3MKEjB
0Lc5w4oqBWW8Aq5ZddLHVrhv-jBSwxAzEQvyVLTJtQ8rhtnjKTPj6WEBrnPatQWniN1TENxgLf--oA9rNKTrkxxCWdM5M1FqXHQhAyEQeY-rK4qHrZHjiKLg
2h0cQiijK5D-DLLRS76Qugl9sf8BqvHUJTSMNPIcyEe7sh8BKlhl2wzVLtRr4ttfXUYAhdwaBxu8NSdLpmJarsRh2kvJF_Dfs-Fi-Ylzyk-_ZqNNN_7rzozo
SlsLNt__9WVKh_-PHycjluBgRrpbq0NO-qBRhpLONzWRTpcr_ZeckQ6y-gl6_Ykq_df6_NVzCusd2QY_eV_B8tnI-g_8-gkz_dt2AlKS9x3-_lwFVo2a_mgi
lthhdx1EdUSv6ZG4rf1NHlyLLt-bt2yp-g-q-YlcmsN0Ff_2wg-SbyiP_LTM_TLOVyu2LD02L4R_KL-6gPm5s3FwFxwIqNy5rLz9zHzj6_r70VL7zd-4z5zj
zMVqd_QTsB37bEg_FzYE-bCiVKZrRnDEQG4gXdDEK3aSLFsEUgiAugotgoGEgtx7NQD-_PVwP_Pl0IhCqYTM_tRdBpLRWC-AMLIQjUlNVwd__lujG0LoRlqx
zteBuFvl0Rp-im1h7ze2xBxawUk_JkpxFmxi-x_Ew-S_75SY3dkH_lq0S0f7jG0EUZlz-mN03BlVSlw2PDJl-Gzxpuco7W3Y-H_ziVQeylodu5IlA_qdXtfT
UVvZVwQDFF-rFz96dl_SdsWJpt_t-6_l_z2UPoVl_-BjFxp_Kt-Q_JBwhmMEqwIy_sDdblqY4ZlD-BVwe-mNyuk9tlvtZep-Jvy9Ntbh3x9VvzWt_51GbRV_
loRjDvEl_Usu6ESBwl-wl1JdQvoyVYmvnBxPN_Demaz0XXrMUJH5G8Gz-eQl7mf8i4lRz5lzp1OGO9i5datJbr-2jldhH_hYo_3oXnFrfPUYxGJr0ttXvNZn
qwdwialITOQj9jlQeiloqiUJzIMNfkqKDL5VS7bU-7owljmIjPsZ9kcBBTFB7b3ObrggjfFK17sXvNhH4ohxCalsbaTKDaQMhUymTQF6nDBrdMQhcsoDWUMB
VqXfRrxvifzIsXvNljO3rIK1QGNeFL5zBI2i3Cr7ggy4P1KZxacb5H1Lalv3rHy499Nc2QVwr3_m4TGK4OyhbDCyptvYcPYcgphM92K00000000001Wh3yeO
Opi2R6ECuswCKnsFL-Dqt4_zfwNdLF_OZqVRnyG5KFzfuJdLVrfuJlMV5fvJ_QU5vrJ_QN_iAx_v2w3-qy9Zgl-qyfZgFoqyfVfF2q-f_jF2Kwh_j3_YTN_F
0gZ_jFL_ixTj0TH_Mdb6zPyM7b7zfwtjrj-_0Ee_hJoX-ayh3wZ-qrlcOnlVQMX_oeiKnfTUCXdZMtLCLED7zJE-zuQH61TKzwL_lNx69V6pC2uAduDzNBKd
Zy2uG-n_Vr3Z7lkLwxxnbIZZHWt_urMCs-rVNF9jzJDY7NTW6v6suoOiVl6pUlqitZxgzzNW3Fin1QjV_2pUFglNp-Bjio_-ke_LBtvMRv_LssVrzbczVLPl
dzNRP_NssNsrnmeiNZwht_TPldsMBvzz-G_wB7_Xi_bD7dRtV8PRFlklhtgyfHW000000000000000000000000000000000000000000000000000000000
000000000000_m8
}

