sprite $data_labeling [512x512/16z] {
xD4n0G00100mwD_PxVVPAYmE0G000000000000000000000000000000000000000000000000000000KBtnA7_Okm_a274W3AE0eUMAllzfDsZpEXke6kb_
tn7qcdOQPDXlbwwlT7s5yolykpujsG-_jcn-XVCht5_P_Dgo-HNkhrn-yLSul_Zpp-GNV-NoYxzo-SLVkVpYhrn-yLSkl_Whbr_ybSil_ihb5t_byek_Sld5
NxdyugzSVl5N4FzBJFpvVp7y_Fdpny-VFt_y_Fdpny-VFt_y_Fdpny-VFt_y_Fdpny-VFt_y_Fdpny-VFt_yuY_yuY_yuY_yuY_yuY_yuY_yuY_yuY_yuY_y
uY_yRrSNb-RF_dN1_FHxkVxuU_WVkxtkBjeVVnr9_9R_wtBzyVTo-V7t-FFFvCVVuyy_avy_V_wLou-VFt_y_Fdpny-VFt_y_Fdpdvc_rHkr07_-zKdy9-Ql
hpMZF__wJlpdugzlDuy___fHZVyK_FNpXlVdNwTwvZyqVwkp3Jm0_EkA1lN7NnVLHlJdNzV5VpZ-weKEWCU_Bgxb-kFlZJC07l_wKWO0_pTgG_Xx_DiSvtNW
_tzXbsO5y5_ltofv0FpTj-xD_O-FxJ_V5ysPyCVdh_QYX_LFlJIhXx_b-lFl_0R0ziyS0FvL1W0_V_u607-KF_-z3837FtG0-1T_Zt_g0F1l_3_8usy0FFxy
FVu6W3z__Fpv6m3yn-_TxLyF5lzE_xGkVxPk-rqdMGzQ-iT-zdNvRzjnmp7M0vVy-E_B6ssN7s8zTBcF_xQytNxf6Uxrw6Nw7qllcXKmCdyTYQ_yxCi7hTVv
rm2DxN-U__m0ZClVYtlyZ-MJjciEi0OfpNzTFkkflXN_aTxttvRFEouumAhe0NX-l_thjUUlrBxHiRxgjV_A_xJ_EEtBg_PeV_vhad_nF_KTmEZy_5_t5EtF
VwslrwRpvx_KDvhFd_yHxSz_Z_Rd_nJZpvy_V_xy-VFt_Hz_F__nhm1__dx_oz_VV_Zx-oz_d__Wx_DV_4Vx_2V_zfsUrl_dyzy3vFqF_Dx_uk_zJ_pU_-O_
mlqF-AzeuFjV3lmNvFud_Ev_e-_-H_fZtlyA_yxS_wnmVkNwYxzQDh_uMm31_EBFFvXVsVxQi_aLpY_-_8Fv5UwlR7ur_0OWc5_yRyu0j1UD--_WpZV-J4_h
tvkBV_glOSlL0z0cugyRorq0-7lJBO3xDy1aVz6SQW7S_-2qoVZhc741z7ANlmNGmp_E02mZ342RZhytvGBeZNrETIOBe9VBRm7qhjlzm_bR0BsBZeZ_W0kW
ryOye3gH1N3XKJwFp6y1z4uT3l-n5q3lnBTz_4TV0BqJvy9_-07e3N8g_3_lvdFrAjEK0z0Ru3ZuVzeTxmaqhp8ED033n9y_VmF0dpz_0y2VF__p0x3nzpRW
-F6t05x7tmAOXzy2u6y1yBS0lFzX0V2t0Bp_QG6uokxy0Epyf-2t05vtXF9R0EDVPMS1kF_D0d3_emLmlY7nBG1P0B80P0780f0580CW_Z80uYy38FxdCm3Y
BmCW_Z80uYy38Fuo0Cw7Fty3m9y_VmF0dpz_0y2VFty3m9y_VmF0dpz_0y2VFty3m9y_VmF0dpz_0y2VFty3m9y__qST0F4_6Ny3m9y_VmF0dpz_0y2VFty3
m9y_VmF0dpz_0y2VFty3m9y_VmF0dpz_0y2VFty3m9y_VmF0dpz_0y2VFty3m9y_VmE0dpz_0y2VF_xh1q3RYm7m-FF7Rm3m6m1V_ATeW_jvYmlGB7y3WDy4
q3S1z7qd25-_jWS7CW000023_AtlyLL_0000000000000000000000000000000000000000000000000000001
}

