sprite $cloud_deploy [512x512/16z] {
xD0n0G0m30IXiRUzVxSL4f300000000000000000000000000000000000000000e7OOrRFmsRkNx4Xn08YYFeOIEOlzxxRdBVeB-A2A6rkupvASMPzg_-eZ
W7zz0VmLmFypqZd-ZW3-2k2l0FwVFLtZxmZWhm3-2k0l0FuAuAy0_dNV3FDt1F1N07y5yFVDCF-28u2_0lWhWBy0-2k0lmy4-Ik0lqk0lmBuAu2_0lWBWBy2
-2k0lqy3-3i2-2zV07y5y1S0VmNmLm1_lmloTmJmLm1_1V1N07y1y5S0VmNmzsa0VqS0VmNmTmdmTmJmLm1_1V3t3E3l2E2l0FuAuE-VaUJl2E2l0FuAuB_8
Vp38tn70Nm7y5S1V0FmLm5y1_7qppDyHm5y1_1N0tpV3_1q1_1N0t--2_1q1_1N0Nm7yFGFuEmBuNo_0HfF_N03_CPhyvmBuZz7aFmV0VpJvpmNm7wF9Vow0
_nXD_lEd0Vp7QFAVZm3-eyb_FWBuZz7aFvy1_CUeyl_mdtOK-IjWdAp7Nm7ZT5N-duF_j0v_Hy1uAe3ZizJutrx0PwtnLq2rlmBuUmRmTmaK-ojWv__d7Lq5
yFSCuEytWH9_1V3t3E3l6S3V9S3_x_Uhee24VyyV3U3l6S3VCu2_0lXx1l1lUWRmTmdmLm1_pm3-ZW3-7eBy_zFsjSy0_fu1_3q3-7i6y7S9y6ygWBzBWB-7
87-N07y5y7S9yEyfWBzBWBy2-Bi4-3i2-2k0_uiAs7_Mdhyl1VZVkonG07_F0FwU0VmVsl7EIu2_Iu2_0lXx1l2_iAN_6Kd-BW7-2k3l8s7-DKS0VmNmLm1_
pm3-2mQmbZ__ULt-_ETr-_CVHuK__-j70F-lXVsl5y1_sxQL_QyNm7_R5_Q__iz8yj-sbVsl7m7yjsrb_-i5yD-sbVsl_mU3_BTjPV_hHm3_RMN_wmNmlrx0
MBW0_WhWl-rTbm1_Hm1_1V0lA23p-9_lg-Ip0Fv5Hq2cyN-mWBNz-M_VLLy8yf-Ngrl0dt_B9P1f_9iAo3J-JGNaVFnBdW6Pnx_e2CWq_WK5NF3dly2d0LVz
-PSy0t8s_ZMNGARnRoeWP-DVSmba6l-c0d8s_ZMNGARnRoeWP-DVSmba6l-c0d8s_ZMNGARnRoeWP-DVSmba6l-c0ZAD_miAMCAV__hV3ETi_6ikWKpZtrH0
fl5_Jm6_5l3dl_8Ha6dycmh8DFvD1UHy_4kU0Pd7l-W8o3J-JGLa6l-20fxsvx_8FoEPUVoBZe1CuzzKGARnVtK1-nB-_1VvPoHpDlurbq2cyNz-w_Zl_9_O
leh_mV-PBU8_-3-r9Vm__9zRr_dFVrwtF_-jov__lAxxd_-yxfz__jjUzVFFVrxNpp__ULq___pdTVlptxwg_FdFw_BdFw_SNm3V_1q1pVu2sFZ__WNmLm1_
1V0N07y5y5S0VmNm5u3l_miAyFEl0FuAu2y0zxy2_FmhWBy2-1S4m5y1_1N0Nm7yLzptDMB-ZW3-2k2l0FwU0VmT0VmLm5y1_9VRVa6RloE0lmBuAu2_Pm3_
WYE0lmBuAu2_0FWBWF_Rnfy__-pL_loJRd_-IRS__wJRdt-w_VadtVxyasv__actF_ySrVxyasv__actF_-asvz_kltv9qUrF_-asvz_Zcf__actF_-asvz_
qktFFzt-_9DkV_v9jp__fDkVVuvgV_v9jp__fDkVVzBjppz7jJ__fDkVVzBjpp-Zsfz_qktFF-dsvvzq-_FFKUtFF-dsvvzq-_DFkltvfzkVVzBjpp-vqvz_
blFFVgC__opddzpeppzPpZ-vqPz_ifn_SgC__wpddt6VF_zaEV_aHd_-oNB-oOt-_9Fb_9CR_VbdFV-CN1Z_6ml8-kEVTFlpJxhz-QVRdt_IxSy_wVRddxtQ
dt_IxSy_wVRddtJxyq-tF_-asvz_qktFF-dsvvzkV_v9jp__fDkVVzBjpp-_gltv9zt-_9DkV_uvgltv9zt-_9DkV_v9jp__7E_t5q2UtElz5P1dzt9_0UJf
_OI_lTS_R_PNG7vWx_LNG7vaF-5ltw_rJtx2tzxhdrVwAo2_sQpStzhzhTtV-FjTiDhVslsjtT_A_QtTtzhzhTtV-FiqeDhVslsjtD--olsjtT_Q_QtSt_Po
VsltjtP_uoy0_Wf8xwpTt_ZdZ_RWM000001WaB_r8FPM4m000000000000000000000000000000000000004
}

