sprite $eventarc [512x512/16z] {
xTr7Okme58RH0GZkhFU_sexgZ6F9puN-StQ0lmkYvFJJHm0000000000000000000000000000000DHZ000000000020zZd9NnMoklUxKN-bjtSW-S0dEJut
F_Unz_7SHtqS_TZyL7H-PdP-HdPzZkpyTFcT0F8RWDJyZEp-pEZyz1cTdvwTdoCxFoEwFpqxFqF_bVvqsXV9pi-HtPyf_rDp0CZV7G0VxK-_-m7GMp87G8lc
7S0rHoF7xlbvxCtHiQK603x7NmhOyZk_GCpUslmK0NTh0000000000000Fpi9_rrxKJVKdi1u2470A_T6G40y7vZZzUTr6ovgAgZfS9_WP2_Pc-9gDDClErI
Vnd1jrtvS-w0Vvzr9FudiCLP9t_E7N3ni9C_Q00MjntvSmRWXQNAVpeoLcq0wWKZPzM7_0kptTXrizwtLg-OFMRgHxVx_syUEUiUykSS0UjXbpzb0buyxkH_
-6JSvD9Z0kgzabO-Zox___IabSyk__z5BLt-fNky1QbtwVAl1AvT_bljZxe200000000000000000C3ugBe_wUNNVgxKJOXlzuill_ev-PdZKnAV_UhR_UhB
xy5_cdLhDhy1iFaz0kHt1CXl03pw3O3DRm3aDm3ocm3v3O3yfze0SnW0szyJG7u38By1aDyLG7u7WFu6G7u3u9E_Au3j_u3vhUe5Z0YrWlxoXmu0-ZDI-wC_
8x4_-gC_8xO_-ZCCWFnX_T4V_HbH2ltH7_spoA-__kYF_kYF_bdqHt_qHt_qJwC_-gC_-ZF25FgZF_edqX_tV_H7VqBxep_waziV_GdEZ_xazaT_neyslqqj
4Bp_qP-Kut_M2k7xd-3yw4zmV_Gdk3_w4vwVxFvC_Gs0_WOWDJ_ZIyrlLXTp0DZ_1a1_0w2_0P3V0EXl0FGt0FeR0FaDWFxU1CudKH_1jFyDG71-vipkpmpl
JtX-PdX_BlZGb_NfpmJCc-Ldv_hwkmhM1OZFZ_x_Pn3q1m0000000000000006XlgaIj_rVTIMyBycTy7Tf7YF-7jFWdxK_phikKlxVtw6FUiBxyxVsEcFho
hurRdN7oju_g8s2PfqFzXJu3rdaQhdqBnzm_loEWdUv-1BI7z2d_mjXxdGQWFUW8METfoB_j9Q1TOQY_wS7Ohd78lp9J5jeE-LTcoaBRq7-xHq2xqfH_eU_s
Uii0j4iTAGjjVKRdvv3V00JdPqRtfsVdPqJtfsVdP-Y_qfzC-p9pOoqO041VQlS40Bp_vH40qBVu9b1RqYuA0E2Y0m0005pntHLugc__uUqQ0000Fg82DXQ0
u_k-trUXgjhVo1hp-itH8b5_68aNV-eleLSTzK-ZPLB_r5iQzHq0wZi0r4yx0DI__W2WRw1UCTkzKQyxMYJnJxEt0E9x0eZlCu3utpO0r1Dn1vJVMm3zVGYG
_-C3GF-mYXu0wbcv1Cfl0FIl5a1-0w2_0P3V1CX_qGJqJUdl293V17pr6LVlP09iVoCWln7GtmZ8xqT4v0S0000000000000000000000000000000000000
0000-0K
}

