sprite $private_service_connect [512x512/16z] {
xC75WGD030ImGsT-xh_QC4C3Qqaz2G00000000000000000000000000000000000000000000000000000000000000000000000000000000000000G5Kb
wP6eWnpqEDH9JdeKwY8NFGLr9tTw0Ef17lJYg2TvqWkZNkH5hud_UYDlR7evr7jvhvT2VP9FUXNyrMVvxA_7sx5R1rK0W4081O_sRsm6ZllVK64KDZBxWt_k
453yWtzj1kWF_haNOFO7_zmXOFOd_zWXeFWd_zOCq1_yWo_0xE_-fKF0xE_-dKD0yU_-aHcWl_i7Nu3Pt_rBXu3Pt_qxXu3Yt_qZCq1_zm--0BE_-rSE0Lz_
z--L0FtTFt4Aqj_zSnrWzdV_oY7Ww-_-jHAWl_j73W7wkt-k0yp-xbyv17pztRzM0lHt_yWXG7_t3tH0EsyYtVrB9U3hx_wX4g2_-vSwWFxkd-e0ix_x7oW1
V_-ilmxWB_o5l_0N_i9V-0j_uI_yXR_m5_x2_xDt7ygkf30GXWL24k__mfjtiOjQFFUK6_TW_PLlfFfpEcaCBVsjgTQgsfh5b_cdVwloL6r1vfz1yUUgVOD_
-hSY_rEnq_tJtueiAdwqV_fNUP46YN-6klElAtweV_etkPHH-6T0_dN6u9yX-TSPWNy6vLzdX_cdludCbQfDQv4vFyi__Sjat-pVh_z4gzFlnad-wQ_oNBNd
h_zvbUVqq_uPxj6_jFdhlrxaAJ_7F_sVRQkF1b9KUQmSuv_-JHvJV_8VgJncf_YdVvdu9__v1b0-wvzXdlshJ_wZAW_v6Vxf_wowyWzvg9xXd_xoK5lwTvE7
uWJ_z6yoAhxsxqL6Te9_-gkCsYj_av6Uu9_-HKR-oh_Bg9pWd_uoqjV-AgEult_wcupQQt-JaT_VF_sRZEorVyZ8pl9FVv_gKp9gz_TFVnsUvOf_ETK__Uil
-klt-QT_1VXdwP-bVvR-MVgVb_wH-H-rz9y2p4n4t_IVpF_9tk-V_ZhDx0pwEZ8VfVz3k9afzEU3JKy4wO-QcKD_76m-MleJp8n8vuEzwMZfFwelPuuFwg_z
_OF-rlIlol0iRSgcvZzl0VV7pupdL_Ev3_bRbNTMMc3zyJFZ-TNyhIVRgu-yC1Z1p43-zS5ylxy9eX90V_pCU7urV-l9KFpxRm1xPyPNLmURs-mlgEfcVtt3
p92KsRyAhBRLNrZzTNsmkPt-9i02uu-V6V_elqJRwAy2p3RwAs1crDr_SlkSVn5W5U2FdXdFVq5kdxz00_Y3PyRxB-Zs-vj02u0_T6Qy_pMxG_nzbx_-QEOW
u9zEblu4CwFyB-Zn-rUmFtncVl_-2-tsTztZtwyN-bIzEdFZu9zF5hp-hVFv-pGpw04W_MidzBTx-2__w4tyWzx_zSpy_ixgRvtHl-tnJ__MAVrrYt_wrtvx
V_kSlwp_x4_zVPz_RFJtVhcO-1STvz-t-LlVwD-Fyr-VBEZzjTFvv_F_UBv4-zU-npye_TC_eFxpoxzl_lWl-Fojy_eRk__hamMvltPc_mC-_y_jNpgplmFy
2Rx-I-GV7_37V_tNp_Z-3xo_zNt-X3FZl_-Bsryxfpz-Plxl_np1_4lVwF-6bG4p4t__Dzu_YFtnC-D__eFSt_fEVzJCpQTeV_wBobyxhJz-PlpFVxBxbqd8
RTJO_F4putymcSe_-geAziVFZ6_RmH3-rbSrMUPm_f7G-UEl_uBtrxxA1UMFlvlHNl-9oR_qLL5G_lYPQQ__HkKVVPKAm9zuPleB4xxRt_ega_VxE_NC-0kJ
KlbhNnK2yAUU6NzXOYx_gWzDbXNdZv-Py_hlNFxhvu8cHFwZ2foP_uq9zlcx8Fo3O6Q2zt_Xzuy2yIUOcU7zd_ZzLK3--9dvt_-Dtzy4wC_x_c_yRqounpy4
uqymCq7y_XNdpr_wDs7rppRuku3yM_BTm3yAoZ_rxk1VXTW_G_kReFmzyVZzGs3-QNS3_qBkdq7zLM3-ASVlx_B5_kaVmk-VuVmhpf-VF_sRtC4_0_cx0FrR
if7xHq7wfngxlyfD_3E4VnMSFpz_-ijz_3DQVpn_bluPYJytV_gxG0jo_xm1505MsFdJNmLO-vn_Hl044FJywT----wVDu0ge4hSW3_zlPpvuZ_pJpu2b4_p
P-4NQqNUNRlA7-a4oo_NjCZxAhC-_zq_VnQWlSulDDcJ-wV_zVhlxDt15KH05011a7_CZku0keImrH-OUNlW-3w_0Bhy_FaBeCalWFFzFVlnf_Er0Dhy0d3s
vzyTVm6q-GNmpRE_3u5d7UtnTm9eymkWpI-0Zrxy7Siv_ktnTm9eymkWpI-0Dhy0slT-0cYFl_U0RNudW3Q_0Dhy0cZp2w3DBu0slm3Q_09eymkWpI-0Dhy0
slm2QFCBeCqlW3Q_0jhy0gZo2s3px_wdlm3Qmsz9K9lVAQ3DBu2slcj0czyfeCqlWBQ-0jhy0cZhAw3DBu2slWBQ-WfeR-rMG7lulGzipxvJG7ls5T3Mbq1R
Nm5jV0MqzINGnlSys7xUaq1xLRSBGVkqxpIm-0tMzk100000042Gl_KWLqC0000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000G
}

