sprite $security [512x512/16z] {
xTq7akCs40NGgQaLeAtKzp-jOplG4MLh1PB__IkytzqGnw4k4n4H4H4H4H4H4H4H4H4H4H4H4H4HaSTZpeeD_H_zKnj0l_tp6Y1V7ftPULHIZFx1Ft49q6__
q0RGR_-e1ZZxV-UVz10m-aV_n2L0l_r36q2__HCQuEml-ESy18p-qJzn2T1l_z06q6__W0Ou-ml-GGy1et_qJrm2zDi_j07qsp-W0Sx-Wd_GGy3e7_qJbm3z
zWzj0Fts3sY0ix_W7_GGCFf7_yGbGB_zGnj0l_q36k3iB_W7FGIC_j4_SGdGR__G1j1l_u06EFiB_a4F0QD_z4zS0lJRFxG1zDi_e07E_e9_q4F0w1_z4vS0
_VOFRG3zzWzeWBE_u1_q433wH__49K2__KCRGB_z0nhWx2_u1pq4ZFxHFt49q6__q0RGR_-01ZZx2_v13m6ZtwcQdSGbGB_z8nj0l_tp6k3iL-VW7_CGCFf7
_yGbGB_zGnj0l_sZ6k3iB_W7F0IC_i4_S0dGR__G1j1l_uG6EFiB_ZaF0QD_z4zS0lJRFxG1zDi_e07E_e9_q4F0w1_z4vS0_VOFRG3zzWzeWBE_u1_q433w
H__49K2__KCRGB_z0nhWx2_u1pq4ZFxHFt49q6__q0RGR_-01ZZx2_v13m6ZV_HFN0Bqsp-q0VJR_w8DSFOJ_ViXOFH3_JlqO_qxz6FzEx5ddt_dOVGt-ri2
M_NvpnZ_gbX__jL9zETVbUlFlohNdtzLh3__wYJwyw_AzUTVbUlFlohMdtzr4ltvL-Nwyw_AzUTV5UlFlpg9_lohSltvL-Nwyw-AzUTVdKH__bMv_lohSltv
LyNwywzEeZ__gbn__bMv_lohOltvLoVHdtzLhZ__gc1__lNwyEVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__YFNd_-ONv-P_lp7V7xz8O7-_1i_qPz_smVwys_yI7_-e-tZ_Fdtu4Vwyn-pjTFy-VVW9_hpR_n4V_vjp__z6RKvZP_gp__YgJFc-NKjp-Ts_m_-
hy-Q_VmXdtMx1S1_BkB_a0hpvz_sWVxy6__U_loV2_P9_lmRFyAV_z_OP_Zp_rp0xupx-VEVVsEVuS__kOJV_lSh0F-sNqZTpv__xCJvy-VFVqJxyv_y-VFd
_uQVVmhW-SVV-kVFdpz__lpvvpp_5S3NF_xMF__DuS-VF__ntkUV0XX__ll3dpz__YFQd_-yvFElFjxlnl-ppfCOV-kV__xnvyz_y3V_2h3Lt_ddR_pvyn_y
Ny3_TdyBmFZptn_-_CS6Vm-0xFDl0LZ__A_5pv__gDT40Qn__jO__xprpv-_0bZ__FU6F_-nQVqhW6___Ar__fdhNm6CF__T6T7-_ESB_5F-FL3-dtNUyDym
_ad-_4VLdGu0_x5n_Li0rZ__hHaxrxy267_-kyAV_zZghm36dx_nvxyfSw-_0XX__lioD__uLm3Rd_-EyES_jgz_1J3-_3TbxFTN0EFFVq_cVVrdj3__IlHt
_VaR_qwqF_uQ_1Us_tP_2y3uyz_5l__Jhm8OV_wvrry1Z3__3Vm1_b_ulshxF-gAuN_wyRS0iiVV0Z3-R_qpCF-Hur_yNy0_gcwp0FZFZF7lHFlZhm_-__Vu
VzQLm__Kuwy0tlxyJym_wkf9zBVz-Hl_3l_c3nj__iVC4_eh07x-Pzt-e-uH_lM87F_E1_yvJ_dbrmAm_T-HSF-HlFtvFsQwVqNxuw_AzCVFVypinrydrNyc
Zp__ptdcyLS0u_-sXFdZvpzi_zybpdyO_qF2_6SgF__cj_sFIVKt_fqCV_pyX-t_Lqdn7vSOVmN0p_yj_BP_9y1_p8kClmBWVtk-tDn__jSyAYFtzX_pEkEl
0EUP_b4vkQ__J9v-_eF_KcxgFo_6hm3Pqwy0sVo-0fo3VzIUM03P_0g0Vr_kv3yl-VHNW6n-_vVmZVpyQzp2VroMtmNOFVoZTaO1JF_cNDr_NfbV0RBvVGZU
kVlt7tyBO3-_NDL_NfvV0VRe7_dbWlvZpkk__HJW7FnoBV_7V36_NCb_l9vVhkC_lmM_NCH_V1j-cPVmdtENlmBizn_x-1LWl_-y6R-_1Rrz-1zreYX0BUSn
j_4hm7x_UKT-1NZ1wh_mttmKO77sRyhlLy0x-MSjHKxbFswihm0B-ZVcLu05_HlpAy22_Wv-sUu_EtiU_hBNVymPCFqAiA2_QVfbb_-OAVmAy3Vu8VmQiA2_
yVJBE_tdc67y2d0S_RJThm277_jn_0hGan_Ahm47_BZJhm0pcby1PlJkLu3iwTU0R7q5oDxz2f3Dhm7Pkry1ieVVlnoGFVrMGFRm-vz6P0-_5P2jhm3P_1gG
hUyLaCrl1MG_-nKWcry3ilKr85jV0RBvDI1RNmEoV_DfGBQ-0cIlVWt87dwVXBFrxO3ipQy1sREl0Tcphm7P-bw2sPjV0xBrdO5iV0t8FllEGFRiMmBPewy1
sVega8sl0Zduyh7c_raniGMo9ry5il5L81jV1xBjLU1A-28Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8jy3
}

