sprite $automl [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000000006RlJh8Sn84WWFgHbEKLUV_Rzh87zQmQaEF75JwHWWHNtJAlhql_OyRpaz8B
uVzp5y1pumi0_xf_lwa_VoS0_jT8Em7mEm7ukmN4__qNmEY5y7S2u0yw0UJvFVuZO02eloK0VYS0VxU0-0q0_jR0-6zx0iYOY3m3gFzRt0AyUY7gxmHGVoS0
VYy2BVwT0Efl2uH_kmlWwXk5lnC0lnE0_-lj1W1-Im3yJW3-FWR4Rm3mTm7WTm9uxUiPGFsT0FZdd1kS0FmD0FnU1FBt8X2_4m2_5u7ydG3udG3ydG3uhO4j
_lqUHFsT0FZT0l9t0U1t0l0t0F1x1l3ivsD0zNS2u7S0B4JzB_LN_vtvtVmv_TNVX-3uJN_-fZz-zUVlHo1py9l-dlrCV_LNV_mV-FzFr1y_VludVlNdZr_z
-Vle0x_f7nJywk-Z3r_yU-sN6FocF__cx_SUMS6l_XR_fZ_-5txJFp7yyQi_Vt_mCopgZt_WL___4zCVl-bVnNzRVlu--bZbhufT_7ljDpRtnxzU_wfOVZT_
_DM_pcH-_5L9_gR_x5_9_EfVbRVunt_KRn9SVzE_geBvJV-gUeJvU-rNlqyml-bVLIDfyM_wZ_fZekfl-a-vSfxz_DQxQav0_Kt_1N_y_IwfFmt_1Nx-U_Eh
VrK4F_w3l_h_QIBvyVF_vvm9_XN0h_x1_lX7_MsI-TM_AdhnZx-gvwZ_u1_1h_vL_ASq_n1-zQypcHz_LRO__uhXny_VudzE3B_wyxVudvFCh_vLqVpuwoF9
t-9_JZA_-bSTIVuM_tC2-DL_cxS0p-zbnr-LNN_-ZsH-_5KM_zd-ZsH-zQzw3t_yZ_f_kPBvrRyg-ej__9Mz-ETVqVN7NzatV_mh-kOFVqKl_l5NgJ__M7xy
LHR__6FhZxygoT_YVquKl_hFYU77pz_YVquAl_hpd_dvdydrnr_bjUz--QZFov5SV_MlYkR7NsNnpp-s_lZhsDdVudyzKVLN_pdRykFdR_6_dkZwuw_icp_-
PtBzyLSbBVuj_kUCvFghVrKqF_wweXV__2kw_lZhsjdVudyzoVLN_whePp_yLUhFFvOVVzKE_XR_1e3w6m0M_mQ0hpuC0DFV0B3uDm3Ktm2m-5_F7LV0wcy0
u7S7mDy0m1yr0F1VLGQ0-Xi05ly6WCM_0M3w6m1VoS__uBy1lm5WyRyRFt_rxmxWnyz_EM_At-SYC7u_1BRutvU_pm1_zLyP0FYFD-RlvpqN_-h_wEz9KlrD
_paZYT-ptvmR-kC_x-6F_wn_ZBy3hlxyFVlvFo3gloD_H_6R_dDY-2t--Ql_d2H-DtzpeXR_5lzpakfl-iyPIVoU_URmd_ZvM_o7yCyNWFhpz-oNmz-Twk_c
R_R7d-VVCVmM__pLVyuD-DtyfVgh_-YVJXA_wJydZj-pttm1g3z_Y_z8_cx-NJ-IesyH_4To_VjK_sJ-RlpP_iFYFvc_M_tvk_cBvUzEyhVudpEI-TM_Ethn
Zxz7TFtvT_JY7t-FwFhpxn1-_El-J_xRyyzHV_wnYt_ytUhFF_RP3t-t-dz37dtRHFEhVxV5Vme__-8_9uFVpH__-f5yzCsJpA_-tT6BV_pTwiy_Tl6Flrlz
-SS---7lJleR_nR_SwAdl_ftM_nloyzV_TVpoVpFpygdsEB_Pl_n3VmBD_OM_rFEMzP_gF-F3O2dwR-KgxVAyrFhZxzwimHFV_opl-c_bAEtotxJ_rJ_B_ev
-53_fPozOPAdl_ftHz_xu-zMV_vf_FZd2s27wV_mxFVvYQw_-dUlBVu7_cdnlrTscVwN-dzDegS__duD7tsifKFZjHz-q__irE1NVzCVl_f_PKp_0_-jelvk
_l2hF_uBl_f713z-7ttmLt_y8vBViv-FFjJVz3VzyQl_Ugvj_V6h_y7VzCTlyHyK_Ehlem_yw_bGVzCV_su9uRVuLt_rnu_VHn_yrH-_rtxgxwCF_Eh_CFrD
__U9Zpxmc_xy-UFt7nxu6m3uNG3ulVlbRm3WTm7mz-qdVWFWqSdn1pzRhim1WDy9SFQtnYrWgxy1mDy5WDy9S1j-UUqw0FWx0V3x49o_0O3V6jZYtmz1rTy9
WDy5mD_duFWD0FwU0V3x50I_4u2_5u6z4FwxVWxEtmc0tmamEYO-1L5_Im3yJW3-RW7nEm6EJeuJe6yM9y29toq0VoS0VWE0lsU0D7wVWZmi_fq0wkyMC9JV
FmTvy7S2u7S2XFhx5EJ4Rmc0tmd0toqWVYS0Vv5VseC30G000011_jQ3N0q000000000000000000000000000000000000000001
}

