sprite $cloud_logging [512x512/16z] {
xDn70G910C10ElpMlri4q3jtcR6GVyOV0000000000000000000000000000rhycWVxeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeZ_xeFt7wep_wep_we__k3FIFq1_z
qH_zqH_zE_H7V_H7V_H7_mxzqH_zqH_zqRz3V_H7V_H7V_Jlq1_zqH_zqH_zE_H7V_H7V_H7_mxzqH_zqH_zqRz3V_H7V_H7V_Jlq1_zqH_zqH_zE_H7V_H7
V_H7_mxzqH_zqH_zqRz3V_H7V_H7V_Jlq1_zqH_zqH_zE_H7V_H7V_H7_m3zxu3-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-zzD_SxyPzkTmlu7-w8_-
w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-wF-tz4T_z4T_z4T_z4T_z4T_z4T_z4T_z4V_tHde7w4_-gC_-gC_-dVeZ_xeZ_xeZ_uX-gC_-gC_
-gF__zDVV_rVfxN-w8_-w8_-w1-XF_gZF_gZF_ftw8_-w8_-w8_-7VgZF_gZF_gZVuV-w8_-w8_-wD-XF_gZF_gZF_ftw8_-w8_-w8_-7VhZ_up-w8_-wD-X
F_gZF_gZF_ftw8_-w8_-w8_-7VgZF_gZVut-vw4_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-jzFV_H7V_H7V_H7V_H7
V_H7V_H7V_H7_zdG7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_rtPw1_XFxeZ_xeZ_xetw4_-gC_-gC_-dVeZ_xeZ_xeZ_uT-gF_HEd_EgtrvzWU7HC0000W2ElV
cXASMmBL1m0000000000WFy10000000000000000K1O000m30000000000000000000000000000000000000000000000004
}

