sprite $gke_on [512x512/16z] {
xTtDlg8u4C1HVrGaxERzdtPcUcL_uzL84UgSVQ_-LU35qFxpAW000000000000000000000000000000W8W0083RXH750D3YIzgb4CK0S0i0000yx7qQB1CW
XW40001OJe38000j1L4OItmT00nuXe0NkW0009QHY6a0u1rYkBsEg0C0puE8Od3a16YLtnKXlW6ld83j0l0N2dYw1k1Z033hqsfmTYCD7lRYnh-E49DYVJ01
wXi0zKjCWB-Qrf_rjvLzBz3okmQeFzS0g6y2tFXDWEKVhz1h8Eh_pX8rtDJ__4s0sn1jFLGmx_AR0FNxs-8SkAz9uXtSnbWJ-UoVRSrrYqIi-OQUa5jEugQ-
cu3y9a1zZuJLVq8SXxwUKBHTivmWgxZy_VE2jFhvMjIb_Xhleyi_6SilVnjZbT_kpocGlnRrvL_6M0ydlzq_osE_vMZoMt_rzLTVVlKFxu_yh2dqLz_1mAR-
zwo__FghxyYVtV_a-jFMmlsztRrUWluk_VfF-1s__fPVV_NrLr__HVqNsVyYV_Dv_7V9vRV_wkklllwtsldj_wA-wx_w0mS0_RcNxeyF05GV02V2Y_Ud5ny0
zD-td8O9S04m0VgRW87l0E4G4BK70CT0gTuV0w3lnBO_YilJlsz_4NFJl-_P_YwkpFvlko8eMFyXM9_Mvxhn3n-0vP9ABlz3i_-pkU_PlaJ_ahl_eF-F-ewB
v7_G_slwXUhhdoY_llwrw-ill_wbw-i_lxwzGV-wowz_xVhw5w-l_xxxdiHtEhO1z2-x_FhNhgz_yVhwFwtlcUOl_WVzQo-__hNhwr-yllxdqdPj8-bVU_dr
lr3z5wuE-jVUVVtbrp_VVTVs4VeNtttztz7tj0dowrzt-VKlNb__S-lRf-a___Btdvojl_vjIFtnz3_A_PJrzJ-flXNkh_zs3FsBrzV_O7tVzg8N_gd-jPTV
_zhrzIzVN__n-cks1FfNNdxzQzVNltPz_Q-Ttw-1xggv_FR_8Rr-tVuce6_f8YYv_8_-z9Br7_sfMV_HdsE_zzrErv_SvS_lJshz_FxCN7_4Jy6Jcpz__ycj
dz-VultfnVjJlJ_L-pD1__ws-3Filxxwpqd_hl-Emt_o_yWR_mJxR_zpw-ll_fz5__pbrz_-rwM__lfdq3__ng-__TTV_mdettRrSVtrRpli_sVPV_trrr__
lclLt_vNww-__lhtp_VNl-_vJF--p_wx_bVhhx_--lSw_VMt__hhhx_--dVzxV_V7XOKxAz_-ywK_VNF6HtzVVwhIt_zzQzBV_trpw2__lhtVMVlht_RzV7z
VsDaz3-Iwx_--klVzrshl_xsNt_zzJ_uojztnJ06e0zW_u-rdehh__6kMhyz9RYNtFt7_bCp_wC_9Ui_-dEX-Y_z_XEvzVFtdzpy-Vt9g5-tlm7ewRy66NbC
m1c__o6rVdv_sdprrrV5Rv1xuy_VVtANFxy_gVNp-pD5_VwcE8e9UFnEoopxJ-xov_VdlFdR2B63wkU_gTwVultfP-hV1uhdOF_dr8Qftf_Y_RaNxu_-Srg6
ATwVbFxhXyJNKNt_gTwVulqvg7__h7WPrVUVulrfd-pV3X3lmV6_fvc0slLDm3NpCxX_Fq8CXFV-zfc0slbDm1dhSzm9mThrNG9gvpS1rwzFVwt_UeGuW2E2
Pzt_9Ox1AVj7DXDGkxvNHIPys7kRIhplDifJ_ViX8WD-uoT1Y_FeV-_VZX29ID__E0yJKBk-2QXTtm3K_jHl0cellmceNT-h8fNpiwvJrcUPIXJ6M_az4sQv
f7W600000E2PC03Cyh85lkG7kFs4E0IalCqBiFmLBUe2VEuaAWDkv_ae7dK004ia0fmJnX4FOY00F1D-_tal02n784O10020Mrm20000U3bdpl-E1aSyYCy3
W7OsH5t0Sip__zLEYgW700000000V2Myr45y2W000000000000000000000000000000m7y
}

