sprite $ai_platform_unified [512x512/16z] {
xDcd5G1124111vB-gxqSt8MrpBJmUHjh60000000000000000000000000000000GCQjcY5M9a1z4o3_BgiL6xybG7u3OF6t1SXl0P3V0EYVrO3yxHO0z2UZ
ym0GxVgZF_gZF_722u3-5W3hF_gZF_gZF_v_cDctaopRRHW6mmEwtjLC-rzj-kIcL-4Sq-13_TY01Xz4kVNcgdSc-hyQEqJgRsahmD3_ITZxzpIWXx_xCIAR
lw403VnD8m3--nhmkjtVT2a9VrNTF006_qu2Vty1jXxllIJ-LVTjsO5_4v0wn_N_zylmD0d_daFWDVPXClpz3RYXGCu2u5_b_970xuz_ELyZ-VtnhtBg-_tn
B-Vez_lZN-NS_7v__AkS-dv__Cl9x_V7lygfx_V7lygfx_V7lvpyVd_ygwpwVdyAK4vzFp_-PUNt-rE0Skhx-V6lCkW7-5E057uAK0RzIVmKe0pwa_WfW87_
XTga1cHjVdu1rUFNPmVxHy1y_iJ-20p61lZr4sR8cSrt25opzV-Mt2ittmXmykihv_7x6p1MFx80WeFz47YD6Vtl1FBxHy3ypVzE8h-_0UFrtudqzny2lj4l
hXpCxny1_ir_Jgw_lm5-_NEY-Vs7mCkf7rq0mS4r0eoR__KDV_yXC6BpurzbAS3bqyVVte3hmyIlBfJexs_0X-tWnzzO0F_enz_V0D_enz_VWCkjp_LVLm7w
-L-T_FZtD-0QiVdp_QyQsO1hl7x-2u0pKj-QZj5lgDnCV_y8-1Yy-VC_0F0tmAklXx_sRbttO_3ep_y0qD-0XnM-UVWfmBxpud_3Vmk3VmHSnj7lvwS17_RH
hnUF0jHjAtyOzVsRdn7mjKS_3M3qUry661u92_xfevyHqBy3NuFrQK2xmKXz6Y3u1n_yN0O81e47FuU0O11uy7C8VEs3dmU20aBWmKy36lWz1pyDyFlx3tuQ
uFVtwNC8MFtzevy6UFtz-ZJ0wJzRdmReOadwF1BMpP96FoD0LmlGfm7z_lFqQK2h_tnz2b0D_W6Zdn4Wu0Nequ16_-dw708D_W5lUHa1Wd_8wAS1kc74MruQ
SBz_W3wFX0N_W8EV4Q139XtyD42dp3xuQO0k5Q3Fqm31F-hWfm6YPzp1JmCaqT23dqD0zy_Hfm62V-Befm62VwG-3L3yC_Lv97oMJTPd19njeqS_3H1q-_G1
z3LWjlxwBRduxtWAC5X__INvizio0iRohtyaKD_VWD7wVqySlxy0iqV_tvF3tzi0l_-hWt-jM7xNdS3Cg_xe0bIr563FyTyD_3a5g4a56AU_ro7X_FNi0q73
mOz_Nm6sstyty4SLe1J__WOOzF7lBS3byj_Rw8__EnR_LpF_E-7yrR1Cl__UTd_yzG8OzF4_vRcLog2F_oaFhcNWn_-K1rSpwED_oeFB6VJnF-N11Gtw-1zo
FRYaWH__GvvSj5iVVxq0J_uiPD37_v0dbstMruD_FRcmdL_tv_t_ZIixz7L__8Mx0sbfW_w1iPdV7vs_yHF1nhUyPrpy1VwU1fY_x3Ly_-kFvgyy8z9Njt_P
AnPW9qJdRni1Ldsz03iZ4dzh0nm7_zaqal_CQlXPQEWlFO7yPzX77nPSRt_FwDTl0tPMXDl-lX7WqjSBi0DpKgogvWOO3_upRHo-3jJT0EV1B_32tzG00__z
_lZNHF-rdlB7lyhWB-Xt5m3_gb7-wsb__Al6-AzbyCU_PlYlvV77lyhllvRF7_ygi__o-kDVJl-rtFxuLxdyrmn-2b0E_xMc-EDVr-F-Qv0__bNF-gzf_1IW
dlDVQw0_1RWQ_UVpur_rYFyQwqy16lm3-2c0u6_b9vFzv_FJW5x_9_H9WB-BdmPq-Z-bJxByTNqIuE_Gfm46_nP-Cjk_Nv_Czk_N9wFy3VfaaB-3dypnz-YJ
AVukVJB3twTF9lWR-Sa0Vwi-iVkRzOdPtwvFhFv-VZBN7tty2Vu4Vu8_mP_WJ_372__F9wPG1ndyZujaZMhyzIMoJchyzGMYBjGk_FypITULAX3-KJSM8X7-
MNUM6XB-QyNwdoy3y5_7v7wdXVzQYVxdu9_wKN5zClYlpoQHl-hwuluhqr_8L_PV2_-gh-g_jCJwLoNvw_huLoNvw_puLvA_hez_LOA_he__Em7-cZxN_tzB
W7yJ_zeK8C1_BVm5lZ3_jV0_9y3Vm1zKW4hor_Nnhpp_rS0VN83AybyD_E45g23_rU2VNu0AyL-ty5E0-Vxetro0-jxzrstyD62-Fvk_yn2Oxz-v-Md0VFzE
VGw1-VvT-ZJW-ixy6_Gv1CRxTsv-3e7v_htwD62wVxS-bm7Z_NlrQS1i_zNDJm4c-wD_3lvUVN_mz-hxWx-Ltn_ylVh-uE_LzmT_hxu_-5lv_Rdmj-hxa-MF
lfuiVrsVHFdh_EIAyjVrIPQ_ha-o_7L-4kMlwvCiVrsVPFdh-YJAN-SdMVwwFidor_L9bh-kJwByTNwIvQ_hazd-_Vfajd-_FXdjtyzFPlltwvDH_WPzCiZV
ea_6-7luoJN4twLFPlZxz8d0t-Rlr2T-Voi_kTp-swjF17w3lrsV1knU_std9rR_FLcVou3jy_VhCm9sl_-Ue4yE_8t-UmG_4VGr_tC6wbE0tU__pYXzhWIl
VOZiVyuWV6Bm_v4zEX00001W6EHlVOG3h1J2F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__1_-
yOz__ECV__Z7Vu1__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ED_xTKn5G0m24F1
iVuTrm1iRF_E0Gz8HhJtJtZzs3_Mlt00Bp0zyVSdldxgwoVU_UIVdvFb0m000000000000000000000000000000V
}

