sprite $app_engine [512x512/16z] {
xDgrWSH054H1uHzpyi_sp5jcxgeKNelLTm00000000000000000000000000000000000000rAOUIFtG2R1M6O23tm3qDm3vzTS_PG0q_Ht--kkVDW3qf_JN
Ft40w4_fhxy1wA-__343G7_qbpzo0EYF_lAd3W3zAGEGFx4_-bC687zYV_Id341-_VKF6m3wK_hhdpW0zAVqrzy0zDTV_f01e3_wivO1EFprrrz_-OC6WFwK
0SYVs1_zgUG1qFHt-Ekllm78hx_-8GD0VrfqVowF-ei3u9QKlzLV_wNVv4lw0m000000CCq7BVsNiSmNwZ-6UOCLI6y4sgTiG7mJSAjd0evy4n3V1CGt0VKj
GFpR3Js0-au2wbk0-XQWlWMeRm7g6u3y5g3-MnV0DB-U0JZuBK3zdD-7vNSASEKt00U_1SXl0EeRWFmM8By1o6y0wXk0_1OWlm78Rm3o6u3y1Y2_0SZ_nzwP
hKsgWr3KByI4Ezx_QS-OCtHt_i5o4qAvrtrPo0AS5L00P8MRRGk0h7rqyvqBWFgZ_ZGUwW__v-kGsAVrWmk0n6U_v2u0wayR1TadxGaV3Q3-Oa1MLo8fcsLy
RJXaltcxi008m3wU30L0_UdZ8XjdcVuN491Z5W3rfmwF-bcVrBy8-lS3a5eM0FKpJkftXVuJP9MXyaEjQGg0b5m9FUW_lACOCFK74dfZ2lqpPkf_ZwX9IPh8
9_jd7ba0pEAJ_JE9B02cSF4n8FspUgcV0u3-kGBKlmVB7bAXVwu3zJzr9UZ_O1L7mSIfejR3I63UNboeAhm0I5cRjHi7vVeNQVsp_UkjnQi65m3zB_YVp_GF
WjQ5-YF_Hlz7Cl_qBnUPwOyk0FeFVAn4VmAnCsihOFlBQnmJ_Ua60Dl_a9UPwnyW_i-8N23ijNqw0r7GP5VzWw4_lW3elowtFmnfJlziVu6WwbS0vWVz2uQk
7z4v0EwoltwfFU40e7-HW098u9_wWGNGRKeDlW-K_WLAxHm0BeJhnnT0l7-sly2fNWF0uD2_E72c6G0S_-91k-I_XFcdV_6X-mm0wWSdIPoew_otPkz5QsrL
ZnpYHTCv-DfkV_96xjj2_-97NpW0_k8Tv0ziaNznv5pgVv1RFi2_P_iRP0lWuZzv2VJs8xkr_qi_gnVy6yR_85_Zx-pV9jmO00q-0Dg4HFAH_l7wxGDW0m3l
Vv1Xwi-fs_Y_z_FsVV_rvWPWJi_J-Ejt_sulxCK1qBrs0EPaapyFkKJul_qkWguprlaV992FslmNd7x0Givu_uCSxWTRZ7_8Kc9s0EVi83-F_mEoc8RV0G0a
Dbv-l7_KhPQlx076-1zix7xGm_pZvqZm3i2S3UI77_ujkeZGmltF2P7lxzzsytzkw7-md_n1clOVNDu1wD7-1pr0VmR_Tf7Bfu3Y_G-SzTC_VWS0d6ilMbx_
vK7-cvV-nFxjCYjt00zmjX_fNvRvhm4dWEYV_cCF0bfY_-27KtRttrpzqt-dV_gdV_ftF05OwVyloaFzsplvlv6Rkg7_jim__Hlzqt-2-TzS_DE_9F5V7-sV
_crF__HF__H_v3h_I_-y_bFR9UY_vlJFyx-y_yFed_V_PV5F_ntWd_vhrll_HG7tVzE_PVLVLnx-qNzvzFDVz2yW_uBotoFzqp-V_vv3_mMqeDWN0D5__Fj_
C4V_vQtyr_p-1R4GX_PFuTy2_0SKW4Z0-7_8yr_n0q1kBw7hXFu4_vPW0t1pQKLWxHz_zHzFh7__0f01wFMlGVxDZ-mx08FNVrjrU__coKR-iJDN1e3sZ_Ll
pfpv_G_gv4SXtt_1-RTSfFdys-Vjtm7j_ppu_JVwppK0Qe_pJ__n1T1Sz1TxB2NL03WrHVjp00HFV_h7cphi2Wa-_q__dbcA-FWx_L-dfl5_wYN_9L8_1u3s
6gK_lltfNrMx8AaQx9_-ooNzglsX-Za0XffU_VNtxVpJlogu04v5jJ_z-wTA_wFN0FtNLgeQ50u0_O4JSToVf_qv0FGdcij9tu5jvf_-TO3Q1fpE-eN-2p1R
EW1j0shJJ-Yhsvy3uBYcVz0heFdP_c3m-T8FQHMuvH-WDcZaYfJFzUCge3R5wgT_vupf0541jUkh-WzF__Glh_WVjFF-Td-0B6OYa5r0_PhUwfVoc-e2_VIF
JrhNRz3RMUK3wjdrEu1MfHWK5e1-azv-Be9QppRSBzClHi1fqqlqtlwY3_F--kb_JaNbhQixPe1zV-ftQXprncCjYE1Ibqe_mUSkWNxwzqoUUb7j4uutryy2
S5m18j3yAPwUI3yBe2kO1T7JF_BiwSFrim1icNsJ-_v9XIUnW-nJFuA8DFO5zasY_BC0t2i0DhUeFwoH0FO1GTD_t2JraH-ld_xbC9yIi1pwMG3LlWlI_K2W
_idXdL2aVBn-8YjIgdEM17iO7XP01CKXL58aILS9zM-KLyaHPh5tW0LG_88aidrlIQn--f_pSFqi065qlh00AlNxSyYkMOuBZ0CWFj6heY9oY_Gn4Rb7ze28
t2HvD4JkaZeKKkGscUCWWi1k4XS34GpH0LHx3I8e0iO-uBeK4I3X_tiT8c02_l4EH5m0NTdnrqyaDR-tPny54C8000Ily8z_j_mGG8UTiR3f6LiHpqyyF_8_
YW7Wtcy0J6C_nDT-wlc9voUUd_Z1d_ha9vwVU7xgzOddftxk9pxvgKz-ufEVUdtg-QdN9rwVALwVUdtozQdNfrwVV7tgySd79__5Hpu-bdt4H_g1z0kZG7ds
ZGu00000000000000000000000000000000000000000000000000000000000000000000000303
}

