sprite $support [512x512/16z] {
xTr7cYGX38N1JNqjjEB-fntl6KkFWnV_5KA8DbMPyyGaIP8aIP8aIP8aIP96VQZVDSQOzwVwelwicuT0JxNMIwFclJdvg__Qc071N_m3He3-uXyq0VHN_wG9
eB_wNpm16hNXVya4w54_h7_Kw7bcgjhmJre1-Aj_fdbDz5V_t1M0lpfi0F2l_fVT0NhKXd_613Zygt_i7O2_Eda0y5Sd3m3-wkG1m5zzqm3eiUT_oMy1Alxu
D_p31W3_ll-OruI_sW3mJxq1y5T73G3-rV-A6q2FNVyhDe1ghxvY0MZi-byn0AhDEla2m5zj0V1FNG3ugoq0_gaB07-r1S0_TG7WhxO0-6ysnV_ay5Ux0FWV
l03qzE_yQvwTur_j0k2_tHJ_SyDVxGBWpv__KHU0-8k_wj_wZod-ufyO_vxYB_xYB_xY7nH_yHT_yHT_yHT_yHT_yPVFVuY_-CldlyLV_ENxd-8lptyGVtd-
app_JPx_ACz_bUS_Yx-y_q7U_oBlVvBtlydx7-Nzh_B-Ptd_kqRjbNtyBO1B-FMehRBNlmMGVVmDGFRfDm3u-UTkVmEGpMy0ihU_0SZbzrS0_XP0zkLl0BBv
3K0slm78vZS0sVn-2yZ-oTyAoDOt0Dcxtm1ayvk0xDrl0B8Flzy3VgpVyzvyB3pxyBi4ilLDGBQ-2SZMDm7P-aOW1rzFF-K_QbwRlky_4aw-nke_BgMN94cI
94cI94cI94cgo-lBux_4dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__bVql_jFyHT_yHT_yHT_yHT_yHT_yHT_yHT_
yHT_yHT_yHT_yHT_yJyW_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k9_GFp5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5_u3u
Yx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_u7n1_yHT_yHT_yHT_yHV_o-Cl_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_gfdDdyG
_sV5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_mFYB_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_u7n1_yHT_yHT_yHT_yHT_
yHT_yHT_yHT_yHT_yHT_yHT_yHT_yJyW_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_WV4N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_oF
ZB_uYx_uYx_uYx_uYx_uYx_uIv8aIP8aIP8aIP8aIP8aIP8aIP8aIP8alGG
}

