sprite $performance_dashboard [512x512/16z] {
xDgtWSCm54J122P3_zqg4crAlpCjlFqu8uqp0G00000000000000000000000000000000000000000000000000000000000000000007sdZL3QpqOKyQEU
0LgVU0ISlWMuVGjm_04BKDy0vBS0zGr0VWEGtm3aDm3v3K1-0_0_FmEGtm2y_WOWVy2N0kJt0FZXRm3Etm2Sl_xEtm3arrz_0v1VV_tz4qZ-rpq0w4zF7W1D
V-Ull_u6uFdNt_cdz4T_Uke0q9-gl_FFw8_-OkVsLrz_x_oFlNEvWbm7WUX6nx0Z_snV0czc-dGZbr3T2i0MTG79Nvdovnwldd-MJfI-dh-s9q1Vpr-G0JJ-
W_ZhCW3wUlw2juDf_4VnbsK0jQ_dh_z20FgPkkT_WXi4q3-QVwvg5yeyWtzySgRIYYsR1Ci_PGRmE5V8Vsy6e0Oi2lxvL8DG7irVzgWG-lty-yzJlmWzNuC9
0V_c143jOFf_029zNmJw_VpxpnBrXT2FP9Q0Vri2e6X08sZ_FNC0QYZDK9Q_FWFOgrLG_bq907rr0-XFiQS-4XBG-PBWqLyEi5Nl4fJ_Rmc0efFFPlpH_VzO
r0ke1EN_Gmj0tOIUdVXN2X80_A86q7UPyeEWhqg0nfLARH7uOrDM_U7OCtOHO9F-xTrVtmB0__gyKfq7H3lDZ3qJInoH0E3NDPT7dW3W5xSNQGA0_u0CaoK0
-DyuoURne_MIUuqdqTy90lyhVIPqtGNy_SQ5OduX0VfjU-Lq-b30tszPtqaapuF17szyKtXgEeF_XHCV6nBuO_jxXWVdDFZtlcrwTbpW3nBx7jtiqH841tx2
mv-v0GQ_zRcgEbPVY9G_GOBVD4pmXtEUW_-kZvb9WB2on9O_Zf00-442u4O8GWR_rA03_jSvGGEG_YwF100_2Q3NiiLVPSuV3qW0vqKm2K01mDyoV1mWU3nO
u9Tk5qBas43SUfbU0bdZnudyL8lNdxG9GCmq04B63GBM-n7UM_Yp1A3yfmf7A7yi0J-c1FX_U1n2fjC0ZECa0GYJ130kV_Wladogy2R0_tC2aE8q0CgV1a1y
D80RuukRG58WskZqSMejelprYnmd_fJ_dqB295VycUsNI9J_h20z9adAlo6iTQbFo_hf5dNYWT-t0S0_ye-Y0OGr_lu649J_g2sCtBroVxDXNg-a_3jxjhbR
zY-stBnOOlNN7TmekoZ_LF1F-0_2RsrOME_g1t_xbzhCBND_gIsyBGjp_6dkcVihZUwctRlwonx-y0U_qZMzI-2VPXlbdttyuG_-Vj-u-jFZV-pvM-DFratV
HG7-AlXFnny6pe6_8JBuWt-6T_3FLlxm3_3FvzyV0lYhu3yNVzpd7lopk_pXloRXRoz_-4_4_o4Nx8kR-4S3_h7ycVwVbF7N-yVLV-p03_yQejM0Vww1yCzT
_E4F_du3cVxr-Bb_Ol0Akvn_tiiV_5Nm7uO_xh8G_YaeV_Y37_u3yOUfXU3l3mZ-uA_ItKA1VqxWdrVn1p_ymGz_lLBA7_xpySC__X7HJVXNRT4_IG_-Uyww
27_k7KdKTSe4_sVl7HOw7N-KiS2VTO4G-57wyKVWH-17QSeVWHz5VgDLLmYbS_cZnna_MllBdwvAzvVRgRTqWR-pGOsifqlm1sv-Q-Uw07-UipIPw2RufMxg
pOpP-FEmUr9yBwl5ZvtHQIBuzoz8UNgQn_9Vm-oCJYF1drygnZcP4_4_sDartimQdhFOcRzfDdxip1oO05tZnSxyNNFnOsTsQ2f-x8ni737hrUoHq4dzYC6V
COv_3iIFcpcGVzimiJDpNW8i2_mP0luZ4g3DLTpCNitg_jYPEIy1mWP_1lmdbV-QPcVsY_9lrJZ-QyobF_npXxZrqoe6FAhyuPz37llXPiBVo4xuLuFWh_Mv
xMOARkOkKVu2E-6ln0__qzUi8RWj2VzZl_R4pRJYNmqQQIVyuG__SkOF_tgJF_p3xnyL0Nz50z3ZFzvD-2zh_l0l7N_uwyTTplpX7qB-yDSFl9pvmxykum__
WZ_y3y4FVyK5zu6RkotulrXq4_v80d-zstKdV_YNO1pm7tR3jU2l6V4PXfU6F-z_Ukwf1l_NhTVUz8U_llH-e8-TkKSXthMcD0g-_rJv_zMviJF6yJzQyxgf
OC0NAyPLatdvOwStVzmqnu-Ttlnnqnm_Tdhpnqrp_DZfZHyx5_nFvR_O_sk_iDCSFtPstlX7CQ-QlCiVDnVuJqk0LM-gjVcZ65TDhVXHZ6kcgtEyIDhyzJih
e9XNJER5Zvtc-B5pWL-T0AkaSgUFdPqBFnG3Yqb3dmmOrhQU-aZe6JYHsi_xs0byxDmzvxCMm9J_seC30W0040H0_rzt8nK81G0000000000000000000000
000000000000000000000000000000000000000000007
}

