sprite $workflows [512x512/16z] {
xTtPajku3e3XBXEcV8VtVzgpg-PaAqTZT9eml_zwbaGVH6yIbM-N94cI94cI94cI94cI94cI94cI94cI94cI94cI94cI94cI94dI-4cvQ-pD0FkpZzmq-cVP
lL7Jh2cNw3Ok1F_qhwdVGQ5_-jVKxwXamswZibbQltCYkpLgcxNrEoTYQ_unYsjuK7Rc7xEwXWTbO_unsmz0Z9UxTU7lu3yR7fDR3_uU_hFZCSdr--ZYFpkU
4WrFV_wZi0RyNVndoqF2lwoMH-IMAnUT_6VB4-BMwlJdNnx_gfeUa0RyFVndqmF2lwYcn-EsjJ__qSAV__Yq-BySV_xHb7yC_iil0BUj_VcFJur_HJtv-VCV
I_lp_zZQd_zrpd6n1lxyhqA-Xp__-DkCyGR-_5z1x3O0SvwjzaUUJtfyMl6IO1__USR_cru4xE4_p_X_rt71h-i0pCd_LzrVrblS_vYJ_qil_mNV7wsZp__R
2l0Mzf-J_wil_vbT1s1E_a-QurctjlwJ_zDg3iIA_iVa_xpxk_hFoVytYfhZi9p_tDcV_zpPd__a_vkDT_IVE_lpdsN-_BEV_zpPd__SsT_wVspjpt_kxE_p
tzpPd__SrPy_Vx__p9tz_VvxREtl-e-vgB_hloB_GCVM_gx_d3lxk_uxjlPt_yVSrT_zN_pT_paR-Bl_ku7_XUp_qD3_7VV_iF_BnUCu2hB_Kpl_p29_-xzr
zCy-_lP_hFVFVlxsVwtdv_zjcvp-oVyB1e2_vpyiuPyz_3t_XR_dFzNxPoD__lmz_x6_F_yF_fx_lA9_Dl3t_FSw_-J_h0RyXVxnsVxyFrRspqx--KTgTVhp
hwy1Vvr_zl5l-LIiNDt_W_yFDU0lyyyk_XsVYvSD_BE7VyS78sOB_-pWdt-ugFZWryG_r_VFViz6pMpZdwlxvrTKmD_5FzVspw_fLh3sD_7FsyB--MKLdFnD
_3DNzSylhK2_YN_cYlxvrHNeD_0_Myi_b-ZMGF-2__LKeD_QNmNupVrLWD_SNx-ovo_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-
uY_-uY_-uY_-p-Cl_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_kBlETByFKUU_oXipbuJm7-KDalZtun_pDhuz-8VipZ-hVZ7h8v_9_uno-FVY7_C
-lZtuH-pom3m7rty9__Y-FCVVVmdV_xy6_2FQG3ubyL_ykVVXtzC0y3_zVZpvy-V_zpNdpz__dDVV_xy-Syyusy0zlFdF_VsvpztzUT_nd_p0PWR-_C_sz6V
VttZIQiTXKTrnxO3mF_isDQV_rb-UJ4lnB-yrWi0__wl0ySiY7_V2PWNurzVhmM0VtsD5W3-1e1_VKty-Hi0_WQ0VtsjFWFmhw_10i3V0F0t0FmD07y3mDy0
yFSr07y3mB-c5Zy6y_TZ87y3mB--8njD0F_wMbmJojzLmVpT6C2_liX64y2_lboXVVtvdqt-NrA-MVP_u9_s_zZLd__PiUa0y3_Rsvz_xktFF_Vsvv-jTWdZ
Nz-U2m3_isDhV_wvhpz__loJVq7y-VFdpxzHdl_Edt_ohuk_0UZ0pvy__-pZd_pvyw-kYt-syJS0ZVZvPmV_REHl05hnyy_L_RELlm5eniy_L_RFPluce9C-
_xCL_JFx-Hk1Edp-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-udyr_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8l
_k8l_k8l_l6Vnl-A_vHRnF-4_w6tdm7-zzF-LqNSyqtZV-8_6u5ym_Z7-EqY5sbK5BEarlxt69TQu6NWDegAMLLR_nYNYmLMgtNyprhwHuo_KKJZXR_U_woP
_wdVQWB6MDT_DlEFyKBHc__qBwwJVuoNYlxyzVwpZN_4E6lp6Z3MzvyD_4_-RWCmElZF5lunIefk_FnF_dO3C9hup_NzOvGL_7zeTVyOXKKpVlunIWl-txUq
_xtQ_zw9dt-CueB_zwtfV_8t783Hs__nh9xyPz74d_zzV4ft_j-sgd-CqMW1u5_Ftsu0-FCVlVqVJ-l4Npy0_Dky-Rl-5f3_iOX_ZF452m3_nnh-7-DJ--3_
LnVvZoQd__K5WFzZaTC_noV7_w-kyJzME_tZNsN6ltfj0U3_wESVtq16_6r__iTZ6V_xLVth4t3dVtQU-zrE_uWNBXOF_cUdR3F_UEtVVdnM1_zNkyv_VG2-
pZ__RFDPBK__UFK_S3Jsvnyl_nVkZ-lnZpNye-0_yRWU__mJZHB_-ZS0_8ycftzcVC8R0FxvHlxpAYp_Omt_AFcltA_2yi-T_Vdd8lurxoAZfp__AFdFy3zR
Z3_7Ylxyyyty1t_-lnl_tDcVV-xippztzkUVE_lppxCTF__nppzRBENFFyzs_FwNVnRKzlSV_hcnF_yigEtr7_opeAxNV_7FWhfU_yd_o88QNF_DlrQ___qV
_BEWhlT_yS-2Ujx_oV_8WZhT_ys_mBxp_W_s_rWZ-x_mj_yJV_k_yS-nxVwV_Et_ol-Zo_Ql_Ekp_pl_Uwljt_bx_Wj_pt_Ypp_uU_uZ_rNV0iOzg-BV__dF
_7FDFF-TVqOh_ZF-LTtZar_y-H-vpm8GaT_5FzSkEgt-P_phYi_avv_B5utupzhuPuEYqMl_6V_28hhnvws7V_Oeei47lszhuPzjYZOl_MSD_BDHqMRjFrlU
FriLqMNjFukr_RDR4LrE_hEL_RDXqU2L_vkMzS-26lmU51_vnItfdusB1Yl_jotcVsJp8lhedtsiuP_lqJtY6Vv7ldMAY5_PHswHuZ_z7_nRsakI94cI94cI
94cI94cI94cI94cI94cI94cI94cI94cI94cI9FqJ
}

