sprite $cloud_cdn [512x512/16z] {
xD0v0G0m30IW_klvTriLcG8II0q0000000000000000000000000081zqnTdlsVXirCVvme4C0o4-T0YZkg_sfVZYIM3DMhX7xjsajmS0FoolK_ZsFBft_a1
s5QV_iKV07wvCW2sqLz_BwaQqtz_ft7moyq1m2yt1m2_t1m0_79p0F3BpG70BpS70B_S703ySdC0yClD0S0lDmS0lzmS0FnoSm3moyq1m2yt1m2_t1m0_79p
0F3BpG70BpS70B_S703ySdC0yClD0S0lDmS0lzmS0FnoSm3moyq1m2yt1m2_t1m0_79p0F3BpG70BzS50F_n_hiyrzXoXF-u3y2qTcuC0FxZ_VUPDfw_97lQ
1s1R7UC_x0EmZQxZxoN31hyyB02cw_aximQ_t1m0_79p0F3BpG70BpS70B_S703ycwKu0FYtoRus0FYN975f0F0hxsl-0F0tVm2UFm5m_U_RDGO0Fny0VWA0
lou0-0a0VWA0dm3W9m3u2G3--G7WdmCRxOz_3cwmF_vPiR7--6VLXlhZdvKRwOz_Lc-WF_uvOkFyySzH6-QFVuxSA7_yS_G6-UEV4pR67_-Sj27--EV4ZV37
FoTlW3_-h-pIjt44CH15GMgQF_ziBuTRO4HLjm_v9W-ixwz_7bdUN_yyjBg__dbiSN_zSy3Q_lhdYANzzV_84Jyh--l_bKF-5_RN_oV7BEolVmvQrr__7BMh
l_u_EMnLV_rptAB--kU2DVtrpnLB-kkVIrRqrp_NBEYlVouQtr__N3Myl_wvR7H__NFTuFxwfy3O_lgdnD3--gV8oFxwfyp0_lgdqBZ--gVKiFxwfzYe_lgd
tA3--gV1cFxwfyMG_lgdoOZ--gVDWFxwfr5xV_tJghc__cdMsb__j6lihty6sDyV0000000000000000uFizHpSyxxVWmVAFxV_tdvu1aF_5BXtSMXR4811T
pVFTTVxPZaZXsn8bGKU0-zGZy7_pF06K_n7uvMy9eFmFm2z_Jm3bVmH--JS0pnyG-Byn7L_-1-2NVmCmtG_Wbty3C5qFu9T_0p3T3k2NVmCmNGxWbty3CDqD
u9T_0p1T3U2NVmCmtGpWbty3C5qCu9T_0p3T2-2NVmCmNGlWbty3CDqAu9T_0p1T2k2NVmCmtGdWbty3C5q9u9T_0p3T2E2NVmCmNGZWbty3CDq7u9T_0p1T
1-2NVmCmtGRWbty3C5q6u9T_0p3T1U2NVmCmNGNWbty3CDq4u9T_0p1T1E2NVmCmtGFWbty3C5q3u9T_0p3T0k2NVmCmNGBWbty3CDq1u9T_0p1T0U2NVmCm
tK3W_yPqHVaVW5_-0G4mzmFuvHyG07CzW5_-0G4mjmFuvHyG07CvW5_-0G4mTmFuvHyG07CrW5_-0G4mDmFuvHyG07CnW5_-0G4mzmBuvHyG07CjW5_-0G4m
jmBuvHyG07CfW5_-0G4mTmBuvHyG07CbW5_-0G4mDmBuvHyG07CXW5_-0G4mzm7uvHyG07CTW5_-0G4mjm7uvHyG07CPW5_-0G4mTm7uvHyG07CLW5_-4G4G
Dm7uvHyI06yHWV-RVhShI0B_DxZxKlWVWVyRte4X_0_0B_-C07v_Usp_VmFmXtuwFu0z_-ytQtyYVqO01_px00R77xDdptyGmF2-EsNHclyYW4dXvstQyfy4
C1dyn5LB_fi09e6VkMl7VnJ01F13bwtuhmAO07xejWt_MG0Jm0zTj-2_2s02-A7x5lnt0Km0FtJXWlykW0dWXsvSyDy5C07yq9KB_hi09e0VkdF1VnV01F13
boxuxmAO07xerWN_NG0Jm0zTk-2_2s02-A5x5_nt0Km0FtJnWlykW0dWXsvUyDy5C07yqDKB_hi09e0Vkdl1VnV01F13bo_uxmAO07xezWN_NG0Jm0zTl-2_
2s02-A7x5_nt0Kmy_tzswPWAO206GEY8VySLa25TBYn8u7sqWj_yBmSWVglXB__J0OZVglZ9_tO0uhSw_l4_7e3uhP9V_Ay787whvG__ym68twevuDy787wh
P-S_683uhQAL_s80uhUQDlwJ0OZVgbhuRmOWVgjhuRyPWFYjieN_PW3YjzeM_fi1YD-gM_Xl1Y1-gs_Xlnc0-At2XVzc0EAt6XV-cm68twfS-6y687whS-6_
6O3uhTA5_sO0uhTQ5_wR0OZVgXNuvm34R_LEVc40uhUA1xyn0F5RpOFV683uhUh1Rmn0_5Rtu3S687whVF0R0n2_rJxuZG68tweV_CO0n6_r3tvZ0Apy1XZy
nW1O_0qm-8q1iFWROF0R0s3nDy3WDmR0uc-0mMyCmCSk7H00004030FetvWKm5RXtvNV03F_Thtloc-0KW_Gv0S0000000000000000OxDkvQG1G30HHu_7H
VyVE7VzbLp0gGDS3PVeVJ7orwL3pPu2_wAy_TVwgl_wK-Sl--bFbh_lhJvE_xwy_JVw-l_uq-Vl--jFax_lhJu5_o5z_2ln3_lfJu1_orvy2_v2__XJuX_pr
fy0_vAy_1VuXV_qfy0_vwq-1VyXVV-Byq_xw4-OVzzUVAF-yl_ua-VVzzIV9l--lFqd-VN_zIVBl--jFad_VN_-l8F--l_wGvD_trvya_xw__bz1_dr__Vby
LURteh_-VBofylLpqbz_ajT_trz_alpx_lgJvD_trvya_xw__YJvz_tr9yc_xwy_IVvzV_r9yk_xwq-IVzzVVvBy-_xw4-0_vAy_0Vv3_leJu3_ahpy1_aF-
-XFWF-IlFm7-G_xw4-0_vAy_0Vv3_leJu3_ahpyF-0_xwyzpVlt_sBbl0WPY8022dxyKVxO6uQoTep2hKDr_1O1V0FW5W5y0JNu1u1S0VW7W5m1-0PmvVW4S
JhyR0By0xYg_9w1z-WMmjK-_09OZpI-0Dhy0slm2QFCBeCqlW3Q_06RZDylx_8ynsGXWFdwplSV_7lynvdYB_vXl_07Rfry0xTFl2PYKtxpK_nnpZW3Qfry0
RNu1jFa5qEONG9jV06r-0RJv1T3c5q2RNm1jVW6q-GNGvXT0cry0RNu1jFa5qEONG9jV06r-0RJv1T3c5q2RNm1jVW6q-GNGvXT0cry0RNu1jFa5qEONG9jV
06r-0RJvBGbhh_Qo9Aozt4S0RNuhWjgFlpzW-_GBe7twFG5fVhFRxFPe3uu5000000RvMuzYNtK10000000000000000000000000002
}

