sprite $cloud_router [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002ONVimUXqzW20epodB_AELTDwYdYFkhu_Rcq8FFEvPFPU7lyTpT_Yd0y0l0FoR0TWZ0U3_SS-v
uHS0_jK0y0l0dRy0y7iAm2y0_2i1u1S0VW7W5m1-0U0N07u1u1y80By0y0i0lm3m2m2_0F0B0ByVGl0B0By0y0i0lm3m2m1__taUFlm2m2y0_0B0Bm3y0i0l
0Fm2m2y0_0B0Bm3y_WZ2Bm3y0i0l0Fm2m2y0_0B0Bm3y0i0l0Fprh-VXmoy0_0B0Vtu0zaW0-0NWv2y0_0B0Bm3y0i1_-n1yFBy0y0i0lm2yzX40VW7W5u1h
lm3m2m2_0F0B0By0y0i0lm3m2m2_0F0B0By0y0i0lm3m2m2_0F0B0By0y0i0lm3m2m2_0F0B0By0y0i0lm3m2m2_0F0B0By0y0i0lm3m2m2_0F0B0By0y0kW
nmly9m9uprRgSVBvuwz3wLtzU_3_z7fV_qy7mB_tzVzq0FnxN_zF1y2_D_R_P03yUt__wm3uD-1_6G3_1lml0-3VWFzb0FpRyI_-lrzJ_l7_xHhpZ_-lrvn_
_7zPW_xn_sbD-iV_XpNg7__lrgn_poV_XltZtxH_w_wD-p-s_Lltxx7i7_yUk_uL_nwh_bNnxx7f7_-B02RyutyHm8H__2y2cF2F_qK04_xnlmXWmZ_-5m5C
-CV_8e09__XV133X7_-h01Ryutz30CVun_-608xnZ_yD0HpZ7_yR0ZZ6F_ut172CV_nl2E0O__ZV4C0n_l6_8O1Z_ED_Gm37-CV_XW2EyO__3G4Sur_yRmZW
5F-A_mq17E9VnV-60Cxmhuh_3G4SuLzL_6y8u0J_hiR_qm6Sxz_r-7ywWDFzu_zjA6Vxn_zRKKxsZ_-tevph7_zNe9pg7__Ne9pf7_zNePpe7__NePpd7_zN
efpc7__Nefpb7_zNevpa7__NevpZtplwz-4xnRyFttlw_-Tvn5hs5q3B_W9esLy0BViBe6L_0RJiBu2M_GNGihy0MlONGCl-0cZPNm0j-mkWPNy1jEmlW9Rz
1T2olm1QzXT0o_u2QDbV02tx2o3-7xm7_W_o5q3B_W9esLy0BViBe6L_0RJiBu2M_GNGihy0MlONGCl-0cZPNm0j-mkWPNy1jEmlW9Rz1T2olm1QzXT0_9S3
YFzo0F5V3Y3-_Fax__Dt_yVVynz_xt_uU__Bt_SV_hx__eyz-ZO08mbY86YkMVbd-zvJByKSnHo03D0Lu5z-eltBJxH_-OdsBp_H_kKdsh_yHFkNdsZ_yXFj
NtwY_SjFj7_vYVOlFz7-vIVQl_n4-vUVQF_o4-rVVgBzoq-qV_c9zYy_qVxb9zg__4Jxbvze__8JxLz-eltBJxH_-OdsBp_H_kKdsh_yHFkNdsZ_yXFjNtwY
_SjF_Vys_r-E-aR_-URyM_mjy5ldV-pnL_-dcnoR_DN_sIJ7Bd_rVxB8iSrV_PyBSkppL_-dUXmR_TN_cHp7Jd_rPrxZsEgl_lCOnrv_zP-sE3Rxg_yinR7R
N_qd9Oxj_keF6F1lzbT_OC2_sb_zmO1_jx_wmu1_kR_wOy2_tL_z6V2lzrT_0_xz_ke_uT_lh_uJ_lt-wZ_Xt--l_XF-_VxgF-7Vxw_-4_xz_ke_uT_lh_uJ
_lt-wZ_Xt--l_XF-_VxgV-4Fy5V_2t-0l_fV-0FyrV_27-2l_XV-07_rl_07-Al_XJ_0N_ql_07-wd_X3_1N_mj_WB_wN_W3_DN_mX_Wh_v7ihzq_oFRNxR_
aUulsV-elrp_W_fBzJ-W_ZBz3w3-4lq_yDTVal-N_FKNu7_Xhxy0_mj__GNuN_ZhBy3_mbz_0VuN_leByB_mrr-0_uM__jxkV-UllxVxt_dhxzt-Ttxgxyt-
TtwelxVw_nX__RtL_upyzkydxijUDh_kF_Rjee1XA0g0OBd7vzzjJ8Htni86FiRp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n
_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp4yzFF3_n_CJp8_-HF02VEHRn_CJp4yzFF3_n_CJp4yzFF3_oxyK3y9_p8PwVU7xY-Odd
9vwVU7xY-OddH_ujU01-Smt4ynFFJpm_yVp4ynFFJpm_yVp4ynFFJ_o2F_7ynFCJpqyyF_7yn4_x4CzFF3_n_CJp4y_FNtuFWFmUW6f-_l9x0EJt0CZl0P3V
0o2_1q1-3u3y7e2f89wVU7xY-Odd9pxo9vwVU7xY-Sddzm1Ctj8U70i000003FAt7iM-QW8000000000000000000000000000G
}

