sprite $advanced_solutions_lab [512x512/16z] {
xDSr0iGm34N1HRMw_scNcI6f_aoL_YcsrMC0000000000000000000000000001OxYmwalPrjFdkAEBNhSnZGFspZ4E0PJqJD03o6m1dlrU0_0R0uUyAaDy0
o6y0vA-QTG3zimu05bK6mEyVsf_It--VDW3eZ_xKDpgKxSy1uFZNNt_qHt_qPysUcIHh3iCWkEeNz5RtFstFiyDJz4RB1UjuzI6Gu-a2eiKVp7Da8QB7FmB8
O-JX_ofsuZ_YA0UOVWGQ_7yToUco4B_KYl-8WoB0mzyh04OSv03JxnR0lyUOasNw_GA8VuMSB1V_Bw4t_eDBm29Y5HljFzu1fh-gb_xp7M3w_GRGXtE2B8GM
6_Z7He2tVYqsod-i0qnVY_NqptU0wMkXWN_k6c3yMgooVtu4c7u_0XhdcIDa-fhW_xFVFPyRoK89x08XVx5VuUEa5l3m0z4KSSmYwEX7Cff20cUKWEap6Mqn
4vXV0Yv-oA_guSRqHT35dr_5YBwONpLx3N3qo-zmpm3Rbe35ss1uuq80OPxH3d3ng_GdRjmGcPCTuEBNJc4k_FbKipy6hW6EVft-5_nJ1C1k4M0zMYW4rvK_
YyiTP_qFSlJhySyh_Ye0XcM0ex_ydbVynPxON3e3ZtmRMVqCrkE_yfVVZee0t_bA_471NsJ5J0Uu-FNo9_Yh01Za0F_ihTDVyDTsMJJWMSZ5dvgdviyRippX
MSZ5Bt6cvgyDitS9kFYl6NqID3L_lI-k0lOh0HT_FVwQlpwpiGDS_0tymP8_zA5LUwq1llFLov_aNuR6b3N0z3L8QFwLRQQKW8jVln8oDV_ADvjcW5zvUykV
vby7mEvhWEzyzVAd-TT7jRXB1BZuDKHcmRyukuC3JB-FlyzVDC2xEC1gBDIzkzyNzivikP6M2Q8HhKnk_VvF---B9px2Egr4WIbLNSxObk1K9bIpDENFQy3V
ipkahHy01Fn1-lpAIg1hFc3WcB-HTFTdGA_oSla3_e41v6te2BG39d-0Vr03fay4Ewo0FX0luCzhm9tFWtfVztttn_pv52AV1dJabidbp_dp6d1_1lJ0Jy5n
_ZoDzay3kkB7nitvynfm_pIWAtukVywV6y3-Hy9j_Rnmu_pvdze_3MZhvwBb_7aDk7yQqFHvxSVvnoD0FiBrm9_B7_CFQi1uArCMFV1pO9n_FWNiGS2Eh3-V
_0NyinemBmNieyb_ks3TNau_cB01_f41vAM0_-Yy8-6FFyCMby8LuC_uvpLW_Zn8ayuxZluaVAqS-BbOEV-y1imju9htdS-YFmylj7u-M7F-UGsOPy2On54P
OF1wnPm-F_33-SSrO9u1-gdpZiS_XkCgA005-BDHPTFxQNqy_Z4SY3-O_07-SLxbjU3JpZiU_nZEjSzbclFF3O0F0g3pZiBF4o3Nr2Fdd_zf7XR0Vrm2o0E4
cFXp-UVyUGsOUu062Eie-SyZ6lZv8BsA_o39bUViGE7VBF_1mY5zNgLp_c5svL_RWuMEb_yOOKzoG9n_EBhaWy20uVFn3pFnvvC_pZ_Bhzm3p3llVFuZc_Pn
UNB-sIVattwSpt_mKA1zfCw0F_s8iVBiamQFy-K_31mqat_CdzU0UKWUF7m-_n68FnoSS_uy0NYCUlppDkIr7-UVP5aUQlwBvP_pvwDC7Yx0V-ne0pTcpf_d
sHx-e_bZMNB-UmoW-Qzt_u1_zb4ycly6-GVyLzU0pN_Vv2_ddoT0yzyv-UFyUROrV-_Zp_5p_doBSHxk-Z_4d_DF322Vn7mOVp-qQ_B7-VDFpFS0EE1_ulhV
kpPzNG7_eDoC7rzhyAYn_XzdW80OEVzinf5RsFYa_H-6Siq7u_NyttGWrEE3De09RF-AIUJyywpZvOGu_kFvcmoV-LGivyzhm7pymfrNRV-_jChzHy8_D81y
smB5Vpn_qUCVkVmv__IJywyloB_W-JzfoUGlvf_NWDpwYvt_umcmulIlKn4gI1w_wsRm7F_-CCOV4CZad_EFfvuW0OfU004k_mW89FppxCllVm7u2z__8oTJ
i9n_N0Fczpyvnhy_R7xoVzaoNCm_DG3ugGVV_yN3KFoq4iZbd_FFlu7r8E6pn3_NXype0oL7wilvSmS2z5duCF7Fk-Tx2e36OnOEv1_m3sj0tW6JlZk0_hnt
94dwgydJGO3BVp__X_cy3_J8jxuxaF_F0TxrcVTypZ_CGaxVJpgi6d-1Uu2ZgLVEFzzzml5F-gis_uU99MBTQGD_Q02edP_7NsHA98MFNdB-UGqeKEtuKOu_
QH4O19ZgDl27DQ146gZFuoz1SmmcVo7_t03CMkT7FVweIMWGS51s9_pp6f3cjkhp_q4gV138vP_pvuEHANu_wlEVwfRFaB7Zvlpp6l3kmAPFuFy3ELO9y0C_
EV_S039FSpt-FrWb7WG4v1_ppwU0GFp-iUKgoF-9THF39BLVpZyt03Bm_op_WloVm4EU2GR6W7_sTtZe-HdMYloV602nW1p_Ulw-IzzW7Raa_xa1H1cW3VoZ
19391B8YV_hiHe7yz_3NFUi7yg_A7mbO2hfp0tzk08Ah6INvyuUtF0Eydp-tB0cMZsNvy_fTKFxR-NC3q4KV7nNbJms0Mu1ty-VfAj5VT6N-Ny8K9Of_Ftyp
fsAJlzByJVk6hmdivo-zMANga_XZ0-0M8Etbp-bp-TVbpms0zwssynUmVjmu5UVF3O0F0lluS_5p-PVdRygG3mAR-7DxufUNrkKFqZxevHtykVLp-TVddx-g
-vUS_n3VjSbt3jNdVzy072m49lppLH_TbNzz_lUdW5VmC3ZZd-_wy3tvL-OFsfujhqaP_rpye5b00qNvWyQdsolaY7zE7pGBIA0cVz3wW3-6cFENWlq-G055
-PFcvzlhv80_fy_3VF9Ncp-pltnxhPpmp-TzY9m-ZpyG01CAE2aIy8_4Bv3NeFMVoL-cDtqfi820FpZMCVs-98rKdZ-G09D_i2OGyKUsuvVt_5Rd3wpKy7mz
o026K_yDSkSWynpGB728jI1_908-JGe70TiUtyEsWe4VB6-2bfVc3-3oIK8q2DWUix3relLVi5bWYAZC7_K3wifW4FW6dzsn7H_dVHZ9lpv_Y9SB1LZ0d3xF
007w8A_XVzVdppjAG2XW49ZGfnd0fndyUuDMLUOFd90AvVuWuC72MFomMMB_sVmbEexUbwWyQ5Xp9S_9XMMBFvN_buEEkZq8UDm9qv6VvZMmlFByoL0vGEtt
oY3WSIyiJfyRW9h_zt3QKNmG67T3tFhHSqiW_-hykLBkt_GbCVmyXEPzEA_1mi_dyEVtN_0ka11-7iBMZsf08F_A_Ba1KFdpGM2y5kWc1vxN5lXRPVdpZWBo
1nQGunycukTv3UHVcJ_lA77y90CyrYM0Wdj1WQbLviyxAhhbMM3mno4mMmjs2hhvVpdeA6G18mb0FpYrndwv-Iiuckc8luCtn3uDD_-Wew3xZYnUFcDiiQnk
_kBuxrk0G_wczE_djPi_wYWvk9fbf15S3WFmD_-Weq3_E-PlBdwUrysVTvIIY_b67i7d0_pDdtVK_V38mq4le46j-Hl8_mZ-l5t-Qlx00BAcQwo8e1k4hWDl
_Wxm1_BVPm3-QlwaetGs_o-nGQtv2-ZaGFv6pMh-N-OwuJ7Mn5SGGirg_fT-e_np_aRDQlvV1ZhPnD-B3K2iBvg_2_9l_Sz3DVNlOFpl-P-Fvwzvkve_wYUT
pjzH_T_FVtmsVobw_jVFV-MZ-JjR_sd-ZwFvMod_Nl_reVnvkvg_tiF_slpypy7BONh_Lzvs-RVox_r__FOElJxuhk5lhS8FszNxl_F6I-3e7mlbhnZi_Vyh
tvxEw-ub_64TUhzTe_cZax9-eUnQoXzaGDwkFlz9DqloZlV8my27UBlw_3UNINxyMoCF1I-OUn9g_kOlTSeF_-TN02YGl_h-5tPJ5kWdG3ymWFmA4EdLjqFr
_KyN40f-ZX3p1ype3O3g-z_GfYyW53pWUg7y-I0ml-hDQ6Jh-p-1KFXIMov_G8t8l-z_HUvlSFrhSFTd87-U0KQlX-lxd-Sw1mR0wESZW47jXkKF4hikVomJ
q4-KVcu0GaKfRzVLxty0RyfX8oL_p1hZ1nT10rlhzxzGcSp_pq3yKqX-4J-umessgz__H0_yC0FWz8DzO2OV0EKF4xlV_yTV_oRHbIE_XXyDBnAO_A7_xlT_
2lKJfwza9wWdYKWoG81_l_ztFXFc_KZeHrk1VM-KuVhsV13fztyB_WH74YI0WDV0RoQZpA_F7xWWC016FziCRF1T-1l-GEetVsmHrelxAXmS-A0vDr_u0ObT
dJ-HF-cd2mtyyx2v-5_B093Ne0Qio1yeWFHJG9zQW9Ch_O4N0VUhpNyEzaBz5D1dim2pcyfv6BRBdyCVl-3B2kY3383q-I00v0-cWDNv1nlXbXmKiIdyF0EC
RxjpQVx0_M0_BRagmhR_G2_XtvM2b0GIgCvVmKcOmFgd8xaau1ry6X2zz_8p-FkMT1NHvmWLNEp1yODUACzVmL5uG3_Z7mq2QSCgyqSZ7-zdZexpppCWFVNk
-lnzJ_uYqxuz_FcY01y1olFdykSFtJVnvti3UEDSbZzmlO3-5lxyEt83gCvV17zEF-6_tWCkFdwuB7zU-_5ftqx--JHWtXk5-NFvivsT-_dpQG1DWDBypLGi
iSfwFt_-b49u7R0k_w5WKt_6A-UVN_OYDWBKv0_bpvTylO5_k4eXLWDMvUz7TAG30Dl5N_GxYnX0LVvwZZzOMT_8ty4YzQnJQlBtJ0_1pWfT-_W7QIi_hm4B
yfzlUG7qWG5ivkzeIzYasHNvJnCTq0TAsinV2hxuF7iAyfysatUXP6W0EVzS_kc1GNq4V_FnK-3OtEzv_gyB9BH1nLk7_rJ-MFpWwS4-_lE6YHyPzGVmJyvo
WhN3FVn_pCgB3mAgo9-aFwSF360V_paitZX_8d-pTJEmNhw1Fyf9dW7wFFv2qpxGsHluqvJ4qm1_7dyJRH2ptSEVPoHgfZ-DlxHgkTGx-GkW8asrIlANRDj0
wy66cLty-TSXLZVfWMzzTo9_Wxiq2NrmSdmNV_njTFFc27by3n_7NmQNQMTlnjpFty5vJt1XyIaPm2_QKI3-e0RC-LDHo-IdmNtbHsU0qNtwd7vU0tB-kVp3
332uc6Xp95ViAA0F323Zdo_ynAU5m8keJn7_F1JGpmmWvvzFHOJm7sm16iz2d7vk03d_F0-v1O3EEypyUGBe2Zh-siwVfw44y9yw17Y0eEBFUpxddykVPy00
uVFn3sSdUKVs53Zdduz20ZF_0nD0WuKWVQwzd7yk_x1um9rtbFpdaT3dMm5p_hdy-I0mOFXu-O-XvUikoldd3fHaW7Zd7I__CS2u7SWlvR_Z8TJ0uGBy1Qm_
D82SVov_FWtG-VmzU1Xhdmimuvyl_4GPuC731VW3xGS6aFBFvSz3-a3-8y2VCSZvMsyuYpm-ZB_NyvSJ_c7gHM6f0F_nxZRa57B--T2JQsSq_sWhOCu_bt_p
JyDh-M-HV_FVK0CI_lcdvloRVwv4pd-3_9l_1WC8-IkNVyw_wxz0Yn5_1_YplkldFxaOS_vw4tyLv9yt8JS0pZ-IVnx-CFwGKyg3ymyMVlAG0lvdhlyAz7Y-
5P3ptob_1Uk_P_8dNPuIoVdd2p_SLGB-f-x_oYrWVe5wm7-3_1Ni_pfz_wUs603dpsURUG9Z-LVQ_orlg07NyS-_VR3_kyRv3sse0MVyTyZV2iv_L3d_9Mym
0CoVVqx-pHd-UkS_jS400FytoryApd_MElyjhPu2flpVBty5vx_htV-WjVobrVoz5hyKtFzGvFuNJYnYa_DVBty5zxzKlVz9QxS21lpVBN-frFrF_FutAtYV
3w6JyyyNVi8xW2PzL-G6G7lIaH12uCuH__NorrCDs83-QHbW6xmMGrvP0-Ryro_yYDnyQZkdlp_yBR00LXj0pd_zULym1vxqNPMuK2Va1X3mJzqb47_ro2qW
Du2SlzUtkZp-l2joZNB-kVnpyRS5v3LWpb-1_5lymLGevIy7_2Fvv-Bl35XZ03b_vV8Fddkr1IGEwvo_O_mjVgxPzNToSlvS_bl5tnQGeEByS_ct-FF-IGqW
uPyl_BJuyyeeD03Adyj_nnItBI0t0CwVB_paWrj7tb5Shfn_Bd-j4dzRGC1VOlondsmGVyy271Z0KlxUC_At1SHR0Jd_NFxQDErl2t38dvSJ-qV-jW0CZVFF
vNzj6Fcx403K0Fz0_b3yLrDURm4S6-TlXd-l-Fjn8E4co3-NlpVWRmi0u0Z_NFuRflrj0O2S0FzyuSTRyBS54Ea2_gdyDrX_5mAGlmpu1mi_MyNV5a35o_ad
vudWx-RHZmFvhnhpd-FNESzxsmAydh_NVz6EV4BDYHZov_BFovMEXNDgG13ndsVF0UBlMG102FXp-UyNVyy2k040_Y1tZX1_pm8yWSZu6-3_FU9l2p3bBm7-
GFu7YBzd0LCP0_vK_joMykYuWDO07p_dBm6M1uY_BS2t-3FvzmE_0wwD0WFvX3zO-3bA_6q1dgEPymVoFs2JJsyCGGOmvp_7htF4tnQ03O3pzq4rVpyC0WOm
vm_aVuBuEmE00Spvp-dwh96_4q2W1fpm1_8_G_nzRPJ1Li09_xdyZwxvsm8yGJhdF__P8yNVgyB-IRIUyf_B_t3nzxC0G_xpdpnS_6q1SrLF-CyNVewl-NiM
uCb_pVWRF2iuwaHtMy0FHVrV-5iJiWLg_duUF3E02NzGA1mvyMiBq0JjN_XFVhV2oD-5mDm0z7WQhY7-je1P0Zpdho_NgFgw4B0UzyDbnDyMuFluLKdyFGku
pR_0nAyj88W2ucyB2EAyaRz3BVuk16Z87lyEWryhDVAt1SZZpx3-tivT75eCW400lB1Sqt-rtzrTOAQ5nPuaQvhV5L3zbDgn-Os0zDEoeVbz7TZFg-dDRmIa
NrApczyLa7vPPfpzrBlYlrLpczyLKFsw6jlyHa2_nTJcTmMato8pptxlZAb-cnhP_4P0lzN4pMy4LBzL3Mn-8o3zLXcu-HL0lzsyvbS1rMzNupQ_BuFIRvTf
3tMIVezZ6AhVOtVxw_yS_nloH_x87_bJk_Ddz-T_ihFzaJ_oPtVyP7N-rExyYVZbxyTV1Q3z5O3u5S2s-4dwPQbZ3mKWVYl0y5S0uhS3iYL-akMRdoHzBIjR
drpubiO7000000000000000000000000000u1G
}

