sprite $early_access_center [512x512/16z] {
xDYr5SL054F1y2dR_glzp1ZxQAO4NUEkRGC00000000000000000000000000000000000000000003onq9_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4T_z4V_
JT8V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_T4V_NNG_oufl0trVrgZoUFM-kUaBdz6_wEwJu_7jVNFJLt-ZFvvqFS7Dktzw_u-gt-uhP5N
itfO8-z6_aTzfwyZ_wF2m_VLm1fxTkuckKqW0CBePWfwb_lVDblyZocDcQ9Vtm2zRv0YYrJ_rSMhaQ-tuJ-kxeApuJ-kxeApup-kxeApup_kmHSiW9nOtGLd
u3-kxe8py1zNTy71_sPr5npyRrPtmS5_NFKbuu_cyPS6W7_thkVq2m2_0F0B0By0y0i0lm3m2m2_0F0B0By0VEcxv0JWzFi1nENJBu3gwnM0wtt4_02w_ERl
0OXoVWz0hSFl0KZNwm7eFM-thVJukm2U-B7ZDBy0xf2V_svy2x__06dBkStFy5Hi0fXXlqO39_W5CBckMnFuyQ5t0Io5Fx_9j_m2M0f_VfV_tam04_vflrW2
-DzkvB1NvxHY0lY_363LepyfKVPlrTO--gzZm_zf01Fq5oq0_oS1JD1VjW3yRxSb4_GNBk1r_9PxjWIXRPat1JZyVhT1VybRW8rCd08SVW7GLm1-0U3t-0Pz
jm3y0i3lFO2-Mm1-0U0N07uV0l0Bu0-VsVSUu8SUxW1Elpi0VW7uv2S0fry0-0NWaxy0d7u1-EpdUm3ydWx1xnq0lm1yzXC0VW6u-mi0Ft_y0i0l0Fu2mCyV
lm3ypLS0Zl-C3Q2luNS3y3zx2S3nvuzV0Fpz6Wo_6u0FVm9m_FdZ5m1__lW5mD-V0V2x0V3t9P0V_Bi1EFxyyGk0Ft_y0k3Fdxy0yFFdpzztFm9m_Fdp5m1-
_lpvynS0Vlxy-VCN07x-_FdpzqDmptow0JZ-_Fdpv-z146__RW2EFt_-_Fdpvoy0l_pax_Zpvy-VFt_-lW7axmQ0dpz_uryy_iRV-FFt1G3_ke7dR_mBXvy_
V-Dl_3l7t_WR_yxnD_x6ltFyZR_nBnn__loDl-tT_iR_pDBippz9hx_VVp_j7OF_bPUeqv__ipypyZ__0lNvyyznRVxyytPT_loJuW3u5tnnoF-NBqsrF_wa
mvz_mT-E-5zwNSRZ_VadnG7mJse2yDU_2w_9UB2_uvzq1C3_-Yio7khFFoaEW7zI5a3U37zL0FpVBgaBOE_s5q2tlm2A-GN0Nm3T_WBevHS0Vm6CRdy1zF8B
WBy0HhU_08hv1S1V0Ds__1D0yV4N07y15FCBWBy0klq5W5y0nVu2m2y0_luMOFS6O08m0PW0J00c01E02S04O08m0PW0J00c01D0rfmD_WBWBm3-0k0l0Fu2
u2y0_WBWBm3-0k0l0Fu2u2y0_WBWBu0d-Xj__lpnyyVF7pz__FpnyyVF7pz__FpnyyVF7pz__FpnyyVF7__TC_o_6tx3R_WD__zsxAC00I06W20z_EBVBHRu
K7V6mkRgdm4006Rph7wi_k-3rO_yo8_yo8_yo8_yo8zVFovMl_pHrSzO_V97Lp-tQ7xav_uiPx-p_xR8Zvj_YRDVVgl_iarMl_poxv_X9hy12ESddf-Htm38
Rm3aDm39_CJpC-tynFCpxVp4ynFFJpm_yVp4ynFFJpm_yVp4ynFFJpm_isy5000000000000000000000000000000000000000000300m
}

