sprite $firestore [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OdJj9ZbjDWY1C8q6LTd7_q_OGFT4iUqOLWQIxN-0zwOk_4YkzfezVuQR-nyUlNzW5g5z_uWBi
lVhrRm5bfM_5Rw6bVlsn2r2__g05s57quO-OW5Ly-5CNe7xziGjGl_we1NZsfpze0ZxzwOzTWFhrnov0_VgZ5k3Pd_wW2VZqfpzs0UhN7xi0zUkFMe1dV_g3
9k3Jd_xO1QXVV-m2rAy_QW6U_UaFce1FV_fZ5w1-_RSlmDug-Pt-xSZIVFhd_TjdDgR-z2UU0VNh3ro0Pt_wapu4VFhJd_CXeFxq9vu1zUiFN81dV_gJFWHy
-jEVyo6W_lGddW7rwmzSW6T_-fC-17pwqv_p8Q3-z2UU0VNh3ro0Pt_wKpu4VFhJd_aZe7xziGjGl_x01NZsfp_bGy2dF_sPFmBgrn-x0FNhVvy5s7jDVgf_
U-H4Fltb_Yrjf3x1lsMaFiQ_PUJPn_YtHvhLWURVqjH7-ZVrmVxDim_sRm_mqzU_WVNrRs1z_HluxElV7k2dhty3w-lVmFhwD_3Prxyzm4zV_mRMrx-1zVLl
i7-LNVyP-Edhty3w-ZUmllwDVFRrR-2dhty3w-lVmFhwD_BPrx-1dxx-3QolVmFhwz_8Pr__1dxw-ZUmllvD_GlzNO3--gykIQZ--YTfG7_zZtm9vgz_HXX_
_Qi_O_ZhdxPz0VgVF_kp7-slVze54z1_XtxxYVxwfxrW0VglF_kp7-IlVze54z1_gtxRxwz_JhNQN_yZfrlhht-Ur4P__VF4jldhdoUto5__zxoWnmv__VEo
z1znz1lSVqRIdmlGV-FPt_yXeFyitnZLVmRKR_gd8VKRth-jFllxFmJqpwNf3zPl-eFrc_wiipzxwCzw-ZEml_eDxAz-qvzrzcSF_LbFVmRsLx-1_TLl-Z-z
jwpgqF-PPM5WV_KRs5_znlBtxCyEbhzFVmRsLx-1_TLldoX_p_xiOFdxz6TWV_KRs5_zzedoz-pF3ltRA9ZqdmKLs5_zzgd_EFki3hn_2pZz0u_jdzWdrVyj
pGwYVxvaBF-fRo3_8vaPn3__Cjldlrh_-FZeN-6DskQ_Lh__w_NViO3z_iVjzEk_OW7x_NCt_LR_bbkrnd_fsH_-jvl04l-LPt_uxrr0BcxVsH_-2nQmrpyt
rg__ABTgj__DyUi_U-HEBV3VfZ_zrvw1NDosip_zDonWdNzMwDT_nmAooNy1_l1V-Y6GYrkfF_tNde5StBQpF_rNBU3c_jcbN_zb2yXz_HVXJ_-b7mAvk9Nw
qt_R6RYR__jA_VhlNC2j_BDKl_vR5v2x-6_4d_vBFmHoSIlrf__QCn0R-Y_qRrcR-jCVk03nf__c3m7rlzc_PNdgrn-x0FNh3ro0-DEVzo6WVltFbvsfNt_i
0jIlFse1uaz_wWJKhpzs0UhN7xi0zUkFMe3uqvyw0VNhZrs0-lN7Ba3z-gCM8Fxqfqv0_VfZ5w1-_R4BKB_-g0M8F_sf4r2__jW5g5z_x0BKhpzg0U9FV-e4
rAy_TW7grn-x0FNhJrs0-FM_g8pKn_YtZDJ7-BSqzP7-JVm6zM_gW_qRM5__1jRNlv7nzMzWVVqRM5__1jRNlv7nzMzWVVqRM5__1jRNlv7nzMzWVVqRM5__
1jRNlv7nzMzWVVqRM5__fluAVnVm_Wec_HluwUlVmFhwDx2-_eryzlLluAUlVmFhwz_0-letp_x5_avWhxp--hydM7_zapIYl_xv4irV_xJMGFxw7yaCugz_
sWiceFzc_VQp_VLFUy42z5zwzcS_qb__j0iceFyk_VQJ_FLFks01-gyv-xFz_j7_BISwTllhdzFjzTS_Jscdl_vvMf_R_FL_orCxDldhdnUqnL__l2ZzPnZz
HlUVBJtx-py4z9_bMzB_IpJzTZz__TDe2z2_lUVRUzp5N_zSbFu9Lh_f3zPl-hFE_koX_pNbDe7zrMzWV_MR_gopFtlepthwCx2_-WtihtxJ_qKTMPB-BoYh
0lkhty3-wZUMlsT_fl_fiZoml_eDxAz-O_bxzcSmVv_-3EolVWFxgz_0_kgt1yjV_1dON_q6zbU_WVtLRm_zMmioiB_wJV_gWwFx1n_OFyrO_bFVMFvJtrZ-
6Hd6Fsrc1F_ycsot_tbzs-r_Nj-M-v_7jzt-v_Ljj_zvVTljVrxVblkVnxVj_ZcPRVRF4xAj_dbIjj2VvVFxJxsMuhR-wl_-Utbbz_PNl-MLtT9V_KiNa8jZ
d_rswGHoSJxzQnUGYrF_WWNSqFzT_KiMa8lpxF_h7dbbz_7twL_t8v2BK__Q1UJ6gT-2ohC_U-H7vTFtHq1z5w2-2_3i-o7Wq_T7G7qNeBuByEpx8U3JzqT0
VHUWlWlmx3i1dxuBKDy5gEy2FFjEmAVl0jHt0UhFZd3JlmMR_kqHRlgtyDBV7m7zNO3-dW7zNO3-dW7zMw3fxs-0_Ytm_jYk7HKn340n3EFFEYZoPOc2xrss
jY_T_DX_slLfrwSTdtPzslLfrwSTdtPzslLfrwSTdtPzslLfrwSTdtPzslLfVzL9-_HfrwTTd_RiqpvzslLfrwSz-xHFdtPzslLfppxjqwTTdtPzshDF-_Hf
rwTTd_RiqpvzslLfrwSz-xHFdtPzslLfppxjqwTTdtPzshDF-_HfrwTTd_RiqpvzslLfrwSz-xHFdtPzslLfppxjqwTTdtPzshDF-_HfrwTTd_RiqpvzslLv
rGS000000000000000000000000001W
}

