sprite $cloud_nat [512x512/16z] {
xDkv5K8n54F1nCTMzlhlbfWTGj1C2xhmztaB000000000000000000000000000WKuoJP6gH50T0qXm04O3vMmiW0Z1_QG2SD0T0RftfGHwO6aG0vYyDW1K1
-FaBmBNVdJKr_Fpz1PZVZG3x-mSmVqS0d0Z0pry0vXU0_GLW_fu0Y03CNne0EmBmynU0-GLWVm6ONm3s5u3z1U3HtpDxVXXE0H000a00dF80Q0u00L1u6m2F
WX000a00dDmh-ZQOtVq7m2eFWEO0403vrfg_W8z2402hEm1sz_wSrW0G0Cu1gTqV0I00xFyb0I00BkpTIQBag0v0qOaJCTF-T_k7_BxYFRii29qxZceo3yZH
clSQ_ru-MfpY3t_LT030N_LS0FHNFUyGIt_rfGj0CJwiuji0aSNP_AjM0m2_1O2_VW6ChCsb__aLiCi0m5-p06A71Q3ncwu-0m2_Am3--WLmPM7uwvy2v0RX
Nxa2y6zxL2J-4VE7zRu2y9yd3m3yznV0rNe1y9zVT5euVbS0_cylWCY7qZNkDt_SjSaLG6EyFW1S0VZFGmO0_qyUCvzP0B7PCm3ywt4D1m3_NCKj__CNW9zw
tV2_SGKey-UVx_ldDiy0-F_aiVDN7NK1u7yzxH_xBW3-Fthmd0LNW3my_hFtCm3-qm3uj_X70t_-cmy0_kCT_sWu0Bp-tty0yBy-VspCeWMG9-Jzt_C7WCz_
nWt_umU0pt_7u_wh6_uZNyWNG1xy_ey1uFj__nv__WqMWE__VuuO1_lx_Oy1mDyp0B__lODuZ3z_0y3zFsusUWu0_lS7mCZwtF_h-KRh0S0_N_BN5lnrxm7f
3hy1uFxVBVqjW4WBmFaVt-2ldVXNh_dhkZ7y3G3d__5t_cUF2u05y2S_o01m_lVjhfVzzQ6-2u0V1Ntf1K3L-lK3G3lOyzVekG1a08Y_HYD_6G3YB_wo0CHV
qTjVJVtb0Y0N03No5tzv0Y03GFp5NmsF19G18FxYhzZ0VsPPsk09OE_vuWBG_1K6Vqyn-CyiINluzxq6601UPlAt0FZtl0Pu1wZqhKRL-ri0_DjU0pm1y74J
Vmk0VyqrG7lv6m7yBG3-CywwcIV_n__xfzYlF05yzB-Vk_RA6GxyPvoZlt81UF0_lwV-Mok0_znG_yKLm7_6aUTvvetuRpe2IWvov3-tudzz1F2VSH3_Yl-3
_tb7ETSAHFFVe8xVP00yvZ-ZcBzc0V1VbVANBm3-iuw_pfz__JKWHka2uB-gtFxr2u3_hEIlz-S_up3_cDlrZF-iQWz-_cKTvJzYU_yyp7_61lpyApl8VmJ_
voldvrzR7EC_liB_siH_TOn_V8D_RES_T-3FpFpJmN_kvp-Zsl_3n_7_kohrprpnhwdG__D71lz3hm4VysVo_xuHSFt0F_aNLRhz-TSNM_XdB_-O6_MwF_zh
xjJM_kCR_NDkLRph_wVr_kS_-9l__7Ufy-i__j7v_H-l_rg__ylVvpy-_sdw-Q_zVyBtF-BB_7t_OxKUnF_relFtF_dx_lUB_gFVzx_z_iFlFtBBxS-_zUy_
-Vlzjzz_k_z3iRyRWF0_dz_zdyBzdzp_xH3_rlT_vE_-h-x_Uj02kFAv-BU-_pj_vpyu_w6kKdx-pdzwqT_vJ_SNm9yyfSlvRyylW3odSFwZyrytzdV-i_EV
dV_k_FTTUa-VVsxPE_hy8xVj8Np7_-Pfct_r0BtjdoNykyS_iblyRNx--Fb7lfMk_VpplLJ-vOlM_CP_jf_z_6r-_lZvHrQ4lzxVvkUV3JF-q-pdttRp6__P
dfz_PEFuPzzS_hCDl-rVd_YBl_Wh6l3BzXT_yHT-yHT_HKT_sVxYhuk_xT_9NyQ_-ClurrkdBiYpVnd_ug_nxpLzxv_zgkdsfx_gwKz_rPEV_ggbF_rLjFJ7
lzgCF_ADyA--RFihTZmpTcxcZtyL-_XVgVSFZOzl6V-wnczgEVvj_rNBxOz_rNBxur-TxwyODshBR_lpnpzYFbF-Hz7Qdty1F_wg1P2T_Vd7x_clB0Z_Acn_
_aNRlzwV_sYz_V6FU86_ofz_NZN-zVpyFtpObsv__Aj-_lm_VcHy8J__Znvwtp-szEV_WyT6w-tFVppBF-hz-V_emRO__yVueuq__ol_izd6dtzhVlvvnpzo
p_YVl_tvNpVyRmXURVoz_i_lsFxye-2v_w7-tl-t_Nt-Tvy_ShDy_d-VV-or_Is0iHxrXlziuE_xd_Zvv_VuMm07yskRxJyR-FFVRVlhFFx8W-EVMqr_lVpi
B_QQ_hBzwtB_B_pyPwc_ccz_5VDN-mk_1L1q0CIr0R_Y1d-txMy0cFvMmFK2_xR-5a3YT_wdwU_yNzlV-T-D-As0hE6FV2Uzev-nw_RNzSQ9hsVncmBvRBE1
l_0B_xtmZsmS_fbVal1hp9zrfMn_uHV-Fk7dZr_uXRzV-2CRXt_cwGc_y6ksynT-uTV0R_FZn--D7_nVlVs5N_Y5Nu7VviUFtoi__FZfc_xuyVF7pn__FzYx
ZmA0GG20WPtmnBzRV90x2-akusJj_CJpqyxFRESddfzsVkBvQUTdjlCJpqyxF_7yjFCJpqyxF_6nViGtTQ1zxIUUdtP-ulbfv-ThF_WJF_bfvoUUd_OdNsRx
v2UUdtP-r5-xFJWW0000GG3q_tKpAWLE0G000000000000000000000000001W
}

