sprite $runtime_config [512x512/16z] {
xTst0GCW34L1Hq7d_RVr0dHak3U2hjV_BP0aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIPAaTsMVgEkBO6__N5T2m5_ynL_ynL_ynL_ynL_ynL_ynL_y
nL_ynL_ynL_ynL_ynN-3-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8l_jl7FbxUzl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_YB_zxn5t_n5t_n5t_n5t_nFpp-
uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY__Vm-CFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_FdpRnH__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvfxg2l_YBl_YB_rNn5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n
5t_n5t_n5__tvV7dpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-Ok_-8k_-8k_-8k_-8k_-8k_-5V4N_p5N_p5
N_p5N_p5N_p5N_p5_wZuYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYxzL_xgZV4j5gYisyUTVBd9T_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_n5t_n5t_n5t_n5t_n5t_nNoN-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-zV7_HbrB-4kI94cI94cI94cI94cI
94cI94cI94cI94cI94cI94dw0m
}

