sprite $cloud_vpn [512x512/16z] {
xTqvjeCu443HXEEghFQ_sqvxWlvOg3ybtHjx4ETvDfAgAG00000000000000000000000000W9odEb3V8q1-3m3vDti0SAG7WAV_P8N-w8_-w8_-w8_-w8_-
w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-w8_-y-cF_kYF_kYF_kYF_kYF_kYF_klH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH
7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tH7_tHdq_E5_LQxFtq9_G_vHr0VYy1SMtn-dok5VgZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_gZF_ftf3_w
ep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wep_wvqpwzwu_Rkl-ykTH3UZV_mKWRj-l_hb6_yWJKOFq
7_VBnx1oV_tp1sBD_lf_XiUW_tppwj-nM7_zywPOgB_--OLb-kkVNuab-kkVNrkWl_uve7r__ND8zEwlVmwApltrpt5z--kV3uYk_VNFHqJF_lhdGrhsrpyV
qx2__lcWTltrFswzgKTUwzPV_zjt4ddXwDLV_pmNtrnfbVxw3rojIt_zlxxvtltr7w-O9zhtrp_g9xhtrp_6FiJdl-lIN__Hxt2j--kV_-epV0kT--jVTwpM
N_ydPejqwAz_F76plzDV__WCYqVEuPWmDlt_ssTE_sSEjaD__GVoptu1cDzV_z3_h_G_dZhSbltrhttwwv__zDZnHiF--jS-_VKF_P-XV-pPN__p0-xNN__O
kh_-fR_--kkll_xwww-__lhhhx_VV_JNNt_z_Vwll____F-ll_D_z7V-d_F_dF-xy_dVvd_4hltrD__3_BzeEl_F_Ezdrd1lE_zRV_F_1rd_8rRghx_rVwp_
5bkl_wL_rYRh_-b_ZDrqhjdV-h-VpTV_jVxxbwyT-bl_V_t-zlyuyaoqwgz_sF_d5lj_RRN_c_qVR-t_5-twwn-Rxl-fl_r_zRV_j_urOKJwJ_Qw4LVR_lhN
XF7eFzNBnboj--jVaIEgUN_zAoOCHlzftZJkMg6__ZLX9FfFyfgXrphzzQy9mz1_XbUClgfhV_tF3Gz1__bgfXWQWFxpHKqs45__-NxpGEgI_jMm_xcuUw_w
7mtoZzF_NE_y-e-BcP_yz4T_z4T_z4T_z4T_z4T_z4T_z4T_z4V_vlH7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7
V_H7V_H7V_H7V_H7V_H7V_H7V_H7Vo8lnRMyLk_69oUh5oDokdelKd-l_dD5lHNvVoZqHt_qHt_qHt_qHt_qHt_qHt_qHt_qHt_qHt_qHt_qHt_qHt_qHt_q
Ht_qHt_qHt_qHt_qHt_qHt_qdqz_z4T_z4T_z4T_z4T_z4T_z5-F_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF_kYF
_kYF_kYF_XnxzsVp_6oUdztpiszz000000000000000000000000003W3m
}

