sprite $launcher [512x512/16z] {
xC710G0G30Im3pnl_ssjeMsIr0O000000000i6_cOk_xsAM38W0000HXBu_-ZGq26JPpWFY7EK3ymnmW_c4E4Fym1uX_c0F4Fym1uX_c0F4FSu3uXpb0_CCS
8FvX3X3_C0U8VvW3n3_C0U8VvW3n3tE0-8SvGFp3723-OGuG_p07Y7-O0yG_p07Y7-O0yGzpWFY7EK3ymnmW_c4E4Fym1uX_c0F4Fym1uX_c0F4FSu3uXpb0
_CCS8FvX3X3_C0U8VvW3n3_C0U8VvW3n3tE0-8SvGFp3723-OGuG_p07Y7-O0yG_p07Y7-O0yGzpWFY7EK3ymnmW_c4E4Fym1uX_c0F4Fym1uX_c0F4FSu3u
pouTr000m408Un7yEvwEvT3GudA0-74vGFou721-N0uGFou7Y1-N0yIFom7Yn-K0yUDoWFXnEK3yk1mWVbmE43yk1uWVbmF4Zyi1uiVb0F7ZSe3uSJb0_BWS
87vS3X0_BWU87vS3n8_B0UB7vG3nutA0-74vGFou721-N0uGFou7Y1-N0yIFom7Yn-K0yUDoWFXnEK3yk1mWVbmE43yk1uWVbmF4Zyi1uiVb0F7ZSe3uSJb0
_BWS87vS3X0_BWU87vS3n8_B0UB7vG3nutA0-74vGFou721-N0uGF_u94Fz__m8SU_Tj9KaC155msTI9wR-t9nudsmFWeT3nNGYjIIL_yHT_yHV_MyLV_CLV
_CLV_DV7FzzLTHz__lbz7tMyF_-F_BKwsPz__gD3_VddlwlZ_FddKzLH_lppwUeOV_wvr1d-_2iNEy6VVvwelJ__F5MrzkV_aIUhnlxyCw2s_lmpfAR-_3Ee
wkZFFyDgwCy_0sldppz3Q-RFFuDhvSy_mslap_yZmwi-_lmpeUhYppzJQkBFFvDguS-_RktFFzDguC__9TDwsz-VVoPMk_lppzJkxS-_zlRddydDynT_RSwV
REhFdp__khK__opellxy-VElNVtvPqa3_CLV_4V6_oDBUkpfpp-B6k0l_k8l_cFYNxVsv_-IHRtiwCy_o-9_DVxYB_xYB_xYB_xYB_vdnr_U_yZxN_4NV_4V
4lylMLBnlvp_FyHV_EN_Rxd_8Fvo_qdklud_sRd_Alvo_rts7sJ_HVQVPFzDzXzb_tNNx3zN1t_-zj_vVypWR-FF_x7f-Z__h-pT2NBbE0m3q5JA8gdPSF_J
phvrEyltTo66QE06hIT2ikEalyX_CFdr_Uq_cEslxs__mUJNzxV_O9Q_lh_z1tFwzVtjFvZJh-zl_y7ar_Ut_zY8tQ_lR_yncFpw_lOVpExNzxV_288-pz_-
AXMGilxsv--0o3x-zX-3e4_mjpyl17s2l_s98U0J_EtFoqR5v_lRd_OR8gyxV05_-xD267k2l_svINxiRt_xsz_-zWzy7AUtFnpxE_RNY3U0-UrlV_khtFwT
lFVyE-typMz_-zi_e1Pl08-__UrlVw7wTthwmx6_Ot_7_Xhn1f3YT-plsDzfusz--zlV_W77ywyMRu0lvhThsl_zp4Jhn1YXvQzr_5VhfZZqr_Xw-UDn_ypE
_2E7_TzBphwNXVyMNCfVg_whstLnhnc9XxBTq7_-wv_LzM4kSbCg0ANw_sLMjqV6lMHasF_jrBV-sKl_N_zKyfUg_rdjtXh5UDOVVVpnh7zclz_bV6SSx5zp
Ddjp_DwA2_ahrV_R_jb3_xZ_InV_SSu_iv7-62br04ZL_-ppuyEFLzp-Ruv_fVm6E2yNT_EF8_xgE-2yMqWT05BrN_bXLjNV-wVzd_3FN8NV_iVh_n7_N51_
xw-q0PAULpoIUim_S_sFDc_cZyVzr_wKT1lsFr7_3_jdhVt5zduNsx-E-6Sk_Rt-aR5OtnyC_qnX_UFpR_y_-IkFPDc_s1i21u2OV-xyDNO0nIYK2a1d_8_x
fuO-oz_--ZiWnjF-h_R_b_zf_qoHuJ_k7_R_9tN2FzNrzqcX0q2e_cS-6MLzlh_zCvNrzqcX0q3YvTzf_wo5-4SA5O3G-Cyy4sLzlh_zCxNrzmy0cGB-GlLV
UJ9rmKzv-VxPtN_k_8Ltm1XVxOzr_S7stqTOV-yVWFrhvtykilfx_-pj7vVuPyd_lwofSm3erF_K_ckJd4MtVp7yKrFV_ljCYd-chFvnVwpf7vVwPyhoZzGf
087wP_cdgFuOOV-zVqd-rV4OJ7_xJwf_biRix_rLNW7fr7yb9QNjd_Rd-gVzFuh0xL_O7wnLbza0ISl1yPz2_FO_7xJmt-nFlVtJ_UEIft_xXuW_HFrLdW05
wb_Edx_m8LC0ClLV8lpsvzU__MKE087wr_O7tJ_lwZ_f_X3qjx_zn_73ScldNvD-_OVg1aYL0b0P_wd9p_Utl_tZZlwbwyzV-LGf09Nndxhye3y0fFthrlxH
oZyEr3_Hlw2x0UA9hVhIQlxv_cZc3uQ_HFtRF-_cF-d-1UKDa28N097ZVugDFzzVv01Gg7zz_-Il-xtyQor_sF_XX8O_6lgZZV_KzkUlVBJrXyJr7wlvnvty
o_uY5m2D-jVtXuG_zFqXuO_r_FC-_hMWVx0MNj-VN_ypvVqXuGzr_o7XZnNzeuF_ONxx_njbV_j3md_JzWy9VopW7ne7WCRurmh-mVPFPN_xm_wi-Yywlxu_
VmFm_L_nUQgjl_tHnf-_z1h-4lK_MVpw_iSNCDVshuNzN-WhZmUYwmy5_mt21M3_oVR7olu3doTMzi-b_K5u0BZs5Q14_PS0luP_TlUV7_hR_xMt_rpS7mH_
mW4WwrziVopkdnB-_Fgt_x0_uVeFTjXB7mB-l9T_R7-ivAzG00BZluw__UqFzjA7c3-__YU3Nzy_20MWxVyEVotb7_P_AxYBFzZ-qTM_sFveuPy2_fpwx-6_
2VX3pHy2_WL2BbZxwEbVatpzHnF_9Dn2xQ_t6M0A7002n_-K-l1FOUr3mPym_bn_sD_-Ass0EFDFsLRpd-JhFrRql_mLm9KV_jh_lKG__-ha3y__uTi_sHyD
_0cV0QlC_-pb7-J53nL_VlrFlNU_0elVpN-I_N4__nSL_z3qrpy0yle3u8hwr_SNMFnU_fFiZoNz8_Fgdm5UN_zb_miFW0lgluS_oFxPoNyUyjVdjx_zDu8_
uG1Gy2-oVu2GowTFmPy__bDp_ErlV_xgdssrMCA_oFveu7zL0R0Nt_xsdqtzmNq0o5Z0FywEVn7vzVt91S3tpmR-zkVMVrj_aFsZWt-H_N5h_-rQ_x3_gUJL
1y3LzJ-5F_mJE7xNzo-oFphx1yHZV_ByBv_9zIzScslzxO-r_ODx0EZNVzc_TG5Chd_XwbpfRtzqzmyidMhldrp_R3p-V7_z0hYxlm2_jdyqgF_M_k3wPuFn
P_cZkx_zxPyDwh-rFxWF0Dbv_6jrVllRFxZ-qQ3-M_k3wvyua3oOUJ12_j3sj_-q_-Uvj_y9_e9EgFxHkFy5nb_U7wlwupR-GVIFTVthBluW-cDTVn3z8HNY
5u32_lol_-oFbVrn5t_O_sj_-GytyG_F_nB-BoH_hEsFulXlK0ld0I1w-mkClxO_LlV7NVp1y8_r_OlXZvluOtr_sFytzklZGA8O18BeM8PRvP_jNjUDaSJX
gvjAuSd0j7ye-AU9F_KB00h-r8__UFY7Xd_E-RS_6lwO-5Fi7oh-MUoFXpyg_fZuH-a243h-MJl-SzHA_I_wzt-ItyCV7N_Ish_zJUu_XVue-LFepu6hMm12
op_hndyEtAtC7or_oloJ8rVb7sh-MUMFXJzg_dZudshyGyy_Q_nl7BkQ1G31QiP_sd_JqiAV2dyag_2d_RSjF_Dl_mlRrlUVzGK0qN9v_CV1FzYuzezLVsHR
zKzsgFsVbOl-EFWZNFk_NG02J1u0qUSVbloHRicVzj-zVEtV_eZduC-yVu3D0o3Bp_m203OFGEhwtsRze_sV5kpJhF-b_P-6WJy6EVZJ_azxpFc3y0DWn0zF
nl_s3onA0tzc_35fnXzz_y2a_C-__R79m9_X1I2mAOV7V_JzCUgFV_i7HkMWVx9VW_vODUYFl7zWLRR_ZnudhBeDZV-9_0E0MVBN_wizE1O000006EHlFOjT
rGO0000000002
}

