sprite $cloud_media_edge [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000002OlJlBLXnPWYZw8PQ7_cp-ettThPLzyi127dYupXb0bSGsI2wD-BqH_qqt3FbVqrsY
-1OJG9y5eCy2q6S1y3C0-2E6kiQVV3m4SETd0F0p0FmP0Fmy2OIV1m3u6G3-303-TluqWW5mzySV_eyDWF1_7B-a5L5K6C3nvrGw-2C1lzK4yFVrwoy0_t75
l_e55W2_MTgTl_y2y3zUJ-t2_tWhzGh_uytKAVoFjrEVy3-Cr2Ny3oiL2_z8uEy-0FoF8lvKZR__0F1_77SU0Fx7LDex_0_yyR_h0F0_AlbJPV_y0L1PVlpn
pny0uOz_INxyySyV0E6FVrd-V7zQnOy__cq6m01qLty6W3_-khC_0r0dVoh4Nz-V0UZE_Wn0T_Pd0BgpFmEGt_x-B41j_SdGR-LFXduhVpBq-_ip0LtHBloK
W8y_uVzUZwedU_uM_gbtb7hupWJWdxYJbC8tDu3_rfT3Fry8_wwNGpzVp3m_-4kV__b6cGFWZwF2-jzAyOV_gmByzWBml-1sMSxlbEAF_bSbzVC7y81_-G1E
k-lzuVzMCNv_0F1xBUJtU-5yuVSgnUy_0k3lLeZV7m3yVeNu_G70xvVENsW0gXp-_W3Wzol0xmy0VJqA-v-v_eA_zDjXvvaz0C4_tyx-Mdc6-CUt3FwS0UZ1
fxtM-CUlrV2N-ApdNFwN-Wn-EpthaOcF_uY_jSx_b9wNXOz_F6ciuZz5d_awP3oljJ_-mxkanzbY0FWFxue-Pmz__EELQll3x_l7Qpd-zGU0VvZ-vqR--1ys
_xVkxO__CFoB3m3_UADx--CV1dzfV_m3V_pnn_-rUldZ7pVnnrzx-XF-Tmh_KuH_oV2FFH__yN_Wp-S_ySU__lD_ml_veJ80Wtzh_oS7qZtyH_mn_AVvDQBS
6u2lRtGmW5b_bVUFPp60INxv_5h4V-C1u1-HEm2k_-RxAzy_ej00y9VXdyBF07n-Vm1ZiNyyYG6u_Bx_ukz_nvCOWCll3q3x-UClNJM0OVZdypE0UN_PDt8H
_y409lIbOVAh03-l0_hyyw-pDF7dzn_D6tWnFmD8ufVCMnV_nTdw_WAqo5_ulz8ZXryQpasx_ALV1g2ytxyrRjRKkp_-wo-7_kPVrQbtV_phNmuzWH__bpBi
gmv0-_hJ1Vmx-zE6_f0LyjS7_RcdVdm1MkWFViu4flJp_SbWM3A0Yx-NGZxE9mQWT7-oDV87e4N-y5Ty230-aeH_iacHhINmerzg0KhtfzDASrtp_vZdfzDi
mT-Q-VvqsbLuhIcL_mO3EgVw_6lDm_3tbmN_Btt-lQOSVlC_n7lowqlWt-Y91Fvo-Vr_Kk3VQm09ZoVmxpC09JoVX7_j07oruIxfUV1N6e2I7llDNU6_leJd
_Pq7qF5g_0P-pQyJukzdtpVZxU3_9pLeX3q0_1iKJbtu6K1OZHxy3624Lmz__CEjWp_-OTU1dm64t_x--0V--Bl1NsG0-EDl7LCqyCV_jGF3_qogy4aP_liC
0F_9enix--C_VNo1_nNLFvjk_lWRXuX_KbkSIXz__AywojXn0FYVPYtyyJ_jy4zfdxF0FwEDJgAl_uYuW_-bnzg2Ftwji_yvNI__-7DT_SyBQkGVVszqz3yl
gOj_FA-V__M7kx6_SNZuVzN1FrwgbN_20U_A7w_Mo3_bYFVqTuznPtxylOFkufzppEtv8_1_Tipx-KyS9_p60q1zVdy0-6ip_n56-_ld7NR_kt_4mDzu0AZd
Ft-my5_ahwty0_zh1p3suCz_0D3-_jhloPz_mDpzhtWRSEEBrN3tdn-0Ajxz_GS0_4UB5txNFm2eYRzKbn__Su6_wlChBXe0Ttz_06CR_lnt0TJANyEuy_Vn
nryoz7VqLnR_xlvIwK_xrng0ElfBmz3VpbzP_3s-jshWr-BF_oZe3RwtRCZluwzSVhwtNjrV7Qxuu8U_JZiryCTVfvbQ-EElqqeD_F7thwFOm1z_zxOL_hiE
8E4wolluupyIhgE-Zp_-2R-ZqCGVVqc5RwfKVlo_LVQ6mdz-0CExgVdTCdwi47_y-TtQ0k6FVm8__kq7CF0t-FluQ_Fm_-gE_FZZB_Y_kYc_uFS7e0xX_q-B
_Alj1dxNV_9_K6i0-2kLl_2B1_0x0xZalun_gKOE_oZ-71B-RsMyx5l_ZmZulvNos5z-0V1_QwpcZsZXhpPbFE_lFm0rwZggsCHVyBy0b_ONvQIKBWZ-XDVh
uke1909ShayNVuuecs6Udz8kVhn2eYe_hoSlmgZ9Z_yoZpHz-7t_fIR5-7a_UVb3SYLz_3_nb6ozFlnHwc-o6lhudtQQxUFs-7_y9Ldm_PPUHpGNwXFm-D_t
BLdy-Km6_liEuFYf1_ulrUGpcSUVqdlXVrxJcqTxdJqJIE0tUlz0v_HhBG3_qpdAA_XPm8J_ULtU8Vhwyml0_xmoymWTVNy1-8yi_zFyfiiaFmD8kFjRkOUN
mSy0rlkVxi7DyJE08lodVMm9-WnWlVzfN-bWofy15E4__IERucS0LVtZrLBu6S2lBRucTxnU0Zy3CFXh-XypuVzFMkmVxvJjpm2Kxt_w_fFy3634yrJRF_2V
xVFyfyyVQVmC8688_nilGAhl7qdyV1fWvMyourzh0fAqj_znGG_HQlyev7-8y4y8_cp_uvf4-1F-XF-2y1V-q-5_fFXJFNyb-ZC0_1U7l_1_EVn70t_yPVkh
cp_-mXz_Xp_VdrRu2t_yf_Yr4p_--hLPVZrsziTVa_pIHluCGDO0HWz__FMd3Fv6_lZBUV3FzwTL_bfovGVu7s-USnx_wmiOml-IdDDUvoybNlS9V_FCq_cV
Bs3efHxmPrqEFTN_-GJqUlZFtZfB_3zmXdpzR_8EK8cVx_zdtZBuDsp-HjY1NuBVU6AyT00gxC-TFty0AZm0-DC7iFniuRTAybzzll0_Za83K5r_xlxv0oXy
nl3d3w3mESEV_q9GuRE6Fty0MbWUF_wgpo-XR_0d3g3qkGl_vBU3wvuy_FaV2D67cjN7_t7104hV08BVldqC_UKzvldnzoUW0hN4h_DnQCD-UGyJ7_x3_7gG
AfO0Zt_hy3yoVcj6kmJ_aVjJK_t3F_wQseT_F4kzmp_-N-eR_l5AQXh-4JSU0FxnQaDbm_z8uE__481_n2S7G7Nv-my0_tYteJxX7--dDk4VmG3ml-a0y8yx
--C_uiu3uFCVuJPqNLIMdmS0_FC7GFZZNuuVV_pp1q3uKsd-V7_Qpt-eJlXhkN-eJ0pWWJ_N_zhPd_37lo1_VNy6e3lxCm3Xp-y_uC_ll-3Fxp_Twla_0z2T
_Hc0xkpF0DJGdzRmgoe_6Vgj_EbXw7Vw_0-bwqkrF_v11dxtp_yo0LtOHlxiGDTtxuT_6lzknyu9001208PjuDyn2b3Gn4BlfRtzYUUdtPzuVjhzYUSddfzu
VkBzYUSdFlSbllcfvoUUdutNfruVzHdn-TC300000000000000000000000000000000000S
}

