sprite $network_connectivity_center [512x512/16z] {
xDGt5S0m04F1z8pcZzQLWLVTKVXwAfi00000000000000000000000000000002UU_doS7Vwgv_ONttzrTTV_hZ-wkill_xowo-__l87z4T_Rltbrrz__UNN
Nt_zvJS2_PV_oo2_2z3V0FGt0FaDG7_zzJS0_VNNtm3qHt_qHt_qHtyQU_U1vI2Ggr7ulVbbgVQ_ug6PvDF7DC4kIYxTkm43dy29mFT_mf_mdp7yuMS0mgUB
EF-3YlCJ1t_ysVdnBufFXV49VohkJuNz2Nygxa_5_QcuFwNq1wJc_R_BJzy8WIJ-77r62IJmjwrNZpAD51ZiRtpws16eDNtmYtUVIcNv16Rs_EeHhN_2NyUs
GVHkzGvtVqH4koVXhppReDsTy5TXV-6lmlwgx8-_XB_g-cih-F6VFVmb_5NNNy9V-EE_MSpihvtW_wcOlps7_r81_-tmNvhJNuV2Nuh2_Yh6Rw-Qr9y1IBWD
Sl7ZlnQ5_OM_LDKVV_o5luH_KNxyySSV_y75fyC_d_z-N-tFvpzcd-z_-ECV7Fhu_VSJtV7-Zxyg7_e2VsR_xJZ_8vXzplzA5FnB_FfLbPydyDJ-wCSZU2vC
FjT_iUvS_ndjOE6f2_oNjDNR_9wxrhoVF_xPVoveIuR_zW2ynU_PQp_5MN_k_nG3zUEJ_6ixwuv_0lwkPna-Jlbp_yUsNtm3_yu0E0EWYtk_fofUrPvx7FQF
UTEBBl67vw-rtG5mvmXmXT-_Z7_DyNyr0INuryA4l-jNK-fxUvdZl_JdDdYRF_hr5l_QhZ_FVtkFF_fsSFZQTdl-FFynzy4_th-uz6z_dl-wevz-0evV5lpo
c4Kx_CbhVQBmhoZQlC7F0C3F0C3F0C0VPGS0Vhu5mCy0m1zbtmBWvqCW_0m0_F5L0m2_z2NFtg9FyzjIoN_WIK_qjVpfyKHVpPzM_9h-99E4F_ZN_ED4_i4e
FdNSP__dNHz_zF7dVNzkV-AX6sJuyyRVnJ_zrq0odSex59uZTlxz4Zv3YFngEfrF4qdumv_2FvnktdQcmli_cV277tz-xa_Y7tvJf3NsV_ZdywVOoKhxa_27
lwW_6Vxm5_NdmvzfjF_0Kq584li__ENy2NzI1_zI7m7WbtzhPFZ3NzIVf5dy2N-ASn-hBPd_hTy0I9ygoS_QbCO_VwIg_eG_gQe_uK_wO0-VBFp___zEz0-T
o7nyfAh-X3-fj3zPOl-QVmAm_zDjsqTr_Kq_9JuYFox-luN_YVNEYh_wTmd_lBzOIlVwgw2_bDLVwk8VszNprwzowRF_Tqvf_JN0NyNyfRJ-mhzxokklVlwn
NIr_vVKVysUwIldhX7_SctBwdy_pbdY9DSZVli0_Dfl6N_ZtB-yII-BuV_-gugyw_ecNs4hxuz__-n7-YPTup1R5_xbqYsRFuTz_HSD7fM4B9_p7B_c0pOf_
eaM_l5sZlIuA-qTxMUXGa_hZxtaNNaVhu6zAyVzVV_z7tkbzOyywwe-_JUI_Vx0xdAhuwt0L_F6tpHBxww8__g73JUYFlvVpnnz__F777t--_mVV_xxL7t_y
-Vs7tt_v_TS_xo_-__cQFm2Z__-_-7jUVpzH0V_kspZ_-L-dhehZ_A_zofsRYFzpUPVjXfV6l_3r7rp_4JMl_pBy4oonwbx_oVMVNF-Dlt7_X_v94zt_vSBT
lxd_I-dxFt7_9yiyiTcE_zp_BUuD__vbNc8Ruk-b_Btx4dF_vuy_B3OswtF_P-x_pltVOqmy_w5_gT-n1lWRpt_9r9_-FPx_9fx_bAjD_mBF_-FvRsjF_lsp
Slvhzi8_ylJXxHFRrNt-QuBzd-S_4_uy_nt_OL5XVyAV2liJ_cJuu_-P7buv1i2_C59jVohiJ_XJDl_u8qyR0-1z8_pZqD62_5nMU_-dmlw4FraI__WpxnKL
tly9VohkJyNzQIP_2ZzTSN-oqluaA-rFgkrFnVsfk3_9QlkJuSy0pEfFiLznVxhFF_RpswFY-p_9Cll7qUZovZFsVmu1bVt9Slh7cUYk2V3vekh-P8O_4u0_
4r3NdsJJ-LESIVQkVvp8qqKogxt_qyEijZ_937zcmF3dlS3-z8zhUPUeDVzyalqdxrjxDmfFK3v-1Y2o1F-hE094wnW303y34AE3doC0_0m0_0n0fK_-343S
oqzH-zXFKVlWJvwa-8W_wQV7YSqtpm50QroZ8JrERRmP1e2p3oHj-RSszm3eEVH_-qURUW12UWxz9__i0n3l3y13rVsb7Vzf3W4l5jlqA_XN__G345UkIzdR
-PVWN_tFJq1ytH4WZBFFjUC_stl07h_Wt_3toF1hSFYRxV0B_Yr_ZxPR6llz0J2TyOyPqpb_R_j53llz0NXmzQ7E-iTt_2CKExKbv-fJE-tlqOxasMijXB_E
-_iabzurk-0VSwLz_-j5zj5d_p_jdxyucAxvnqnffoXyCqelaFOhlEe1_r8KNdVyVogyxlX_QYj4hhkulx7gCKiwMk7H5xl_4kkUCcx7t_tOX_yQwrwN7t_y
vOcAznF-kVmvzk7FkhCDsbgijNvbzSV_gJJ--7jXVvyk_AsqF_uD_pF-Ni6VttzjAyUV_q1h-Zl-NjZVyVSP_PiE5Pp_vONztJdzUr9_WzzDBxF_DlCzUa_e
S_bNCNyV59T0jliI_eu_r_zNzM-r_V5lmjzh--FlXVqR_ak5_Hl-IuNz6_vBoVmZt2D63e0p03uaFHxszF8HOmR06O01zptGKzc6FsPFlneyWhTkVFR_fR6R
OB00_ai3Du5o7NwyQgysGNGlnoSm_DVktmI9xhkLqf-VduYVduc_dsAoI4VyYTDF27_YzDEO9Z9Ltlz9bVt9Ibz_HJo01t-kmVndEtTjm30G143GVFrtxDWC
cNvdMbZXa_mU0Vgx0FJt2f3V1Q3_smi0_MVxQD__D4vWHd_qHt_qHt_qfvaV_J7_mwdR7_F__9r_LcK2y7JlWlM_0Vhd3W6WVUSJpq-uF_eJxq-uF_eJxyyF
_MT1nEz_ulsfzoVUdtf_ylt9z-Uk__mB0000000000000000000000000000003W2W
}

