sprite $container_optimized_os [512x512/16z] {
xD0r0S10402mzRRphxOieFoKI4X-000000000000000000000000000080xPF-8ANJExT20000008CZVUf1Zg86y1k0F3SXRWDu1zWx0Tu2z0-mTWAy0V0NW
Am3V0FeAm5S0lWBq3Q1l07q3u1j0tm3w2j0tWBu1z0sWRm1-0UWRGDy0_0BGDu2-0VW5e6y0VGFm2q1V0Fm6u1U0lW7u1S0VUtUF66S8n62uLQVxtpPbUeFu
D3il1mY37WNR-qi1j7x1NvRtJnO0_jxXq2-ETt83u9yoAlpraL80qXmmClpEhlKD8CFEuU6VVWJu9uMtlW1yDyVs0d1phYe0bt_-HF3FIsrx0VZRENmM-Fip
szu07ZtzwZZmwzUE2F_GlBONWATFtvy8Vfa2y6AFcaK1Ce7CoOe29DAO5DLTV_mzpD--Lm3uxRG_1UYFOLnGLquEVz2V0lGd4FJlFp_yENyAq7_uj7z_2F2d
_2b0_xdp_lr1m1_mxuu2VnVujuG1VygV0lIVD-_V7mZye_mfGE2iGV_-KE1F-LE0_dFc_Ib0_ocNPxFvZ7d__d0sykVzAK0_VzwV0lJpcx-ETX-EHqTsTriy
FBg0F-1F0VhvS_xzIU7le3y5wESF-bE0VlwWFmNeFr2JVtzU2_W3_XIWzJHb_lsHBU0F-bE0VlwyFmNeFqZUV-fd1s_Wp_lVIvCBGFFyMzBSwtzjZ-E1AK0_
lwDVxam1wayGlaXcnRU0F-L_EL8k04tohynqdxyJ_kUZKe02_fY_90hGEdhUFp4R_XhY7vYE0WG6p_Zt9zlgd-VF-qkY0ArJv_sb4TbEz5U_l_wuk03oC-Vz
TR2u0CByUNzfRm7mr_72Fy2Vyf__HNo_xf_Px9llu-O2KB6_jA00q_pzob-ImWsW06hrLs3vUE7l9_wIA40hVzvViTNlZx-YYmASp9dtLtmL1Zk5F--l1wir
MVprQ7417F37_FLmjMMBlnulBe234U_xIwiBKC6Vz-zQ2ow0hW7LjXPV09Bmb_1_E9yALtV0-ETNHy8B-AtIrU-FFmMOFvjwrp9_uP_Alw00hPEfU-7_eJy5
-7b-gtvrvun_Vctm5_wF67x1tylyLP3qHdyAK7lzx_qD07zxLG4M_0bO4qY_FluFz-TPW0x-_4XRzF7dbM05GpGED4GV_nKDQCbx4R_jUdty5nIWBF1Tu_m-
lyqqlGsmgnFdyQW2VVp3gq1_JG4w4shanzyFrtlzbVwr6TdD-lcZuUz-_VaNG7LCRkV7Vtu3xCN-xvDISiIy_gKK5ljBFGNuMrp55q3_77_vfrhupvF0_o3v
0lrhMMpsZrq1UVtpDF2lQC3vvjlyh-rOq80xCSttrsV-ZtyD2EtQc7o_V-0AIEfdKi7_GWFo_85OyF-k0Oc0TlW7jeoglDm7_zCjimN8jsoclphyymt8Ru3_
wp-ciZvLryi2_uC4mpQXNV0_twHANz8F-yVsp3V0HNzVulzQotMFB-6V5ylhd-_vkRyw_QN2Foa2MU4VXdFtyyixFuagj5z4_s0L-7SE4DkoILyI_e5Duwyi
oZS0_tm3tFpwSlo3--Rrp-R7l_3Jk8eBWBzKfNywFlvD1T2JXVzfv4NwFfmV_t03yeCSZOz_HmEEnZWO7_zi0V9J73K0_uDLCSDP0V0_MaqJd8q_oh_eJwwl
1pZyfuhyDT9VJTlh3ml_qrMm-Sc_YF_nAjZwg05d0FYhOEUp1k1_k9hsrHyM_gUhODUJVn__urMmvyaU-9-kgYsV--ClDMtutXz_gMax1HR-1zCzbtZFZx-Q
FZLwZh_nZr2CyOyCWB-zsnz_UxS__jxjZx-zsnz_UxS__lPkV_ozsnz_UxS__lPkV_pjtVxuUxS__lPkV_pjPl_y1FXxjp_-zcv__EqgV-F_dgA77_zFB7Rx
us_lziVVdkSl_A_ciDiVV-_snzzy_pF--7F_3_377t_XZp_--EEFF_vb_Fq5m1z__F777t_yDSmVV_prXJ_-ZYxyySU_88HoV_pnry_vu-zkV_pzS_xuQwY_
Ulpnnn__Wc7mh-Ulk03mnnz__BtCFyzF0LxkXF_vQlRFQ-1lJ_IV47VUOjBtWFB6t-96plAtyRyzKhD__j3z_lcPcltpHyRV4_nTp3z_g7P_6__iLCt-Dlxv
gL9AE_WfmDj_5l_0wlEVbVFypwFiyf_tY_RyOWRy-_dx_ViB4FZt5lWtZjRWxzZgvVUGZFB-tsQCl_sflvlzbmptdNztmasXzm-JFnF-vRygxU2d07qljS7_
VBtqBuoN0ZZft_ygM_pjW7y1Vwb_uunv_-fiAO2p_krtA_vsphydsGh_sZ53_bD-jQAc2VyvkN81sBVzX_rbHL6l-azBbGj01_xm5nIWv-V_i4iLV-cY_xH8
cLOt_UiJDVwvn_y8D3Tl_-F_n1aOM5EU_xDd-LE0qm4cy-ClNVGVbYK5kB4_3wY_yLVtwt-vIgUDVMdxaVnS0D95_sanKW1TzEVtg4V-wkzUVuZCdjaO_lpm
wiuC_lu2vBR4ltz-mJ_x048_aDwE8-JtWZz_1l6VFtoU_WAWxrnm_GL0FydVxw_67_pziNbd0T99mL_fdzU7lxy01JcL9BRWE0FruRTI1nBy_zU24mNquUyz
aWgkVlYx2f3Nnx-_00K1TUMqws21VE3lF9aAzE4lAe1MyVEBhLIW3t_7-GBPm5z_GDNhmv__RbxjvUUGylXWuBTrUP6B5_kZBtjn0U2Nfotqi_mKO54SnXz-
2Z0tagk7fG26Vqa1q9TD0U2VkLRhms-ZlvhVHdyrlxsQ7twZVtva2c3unouUxrtXJm6Y_1H0_CJZby3Ljnq545ST1TXypr40YOxpIF3g1pefW9PVRnH0t6qy
6xnQdm98N6eqOC6DHW4gK-iu20NGyjSsKW1fUOafW4I1UMiOvUMzWRobZNS7pnhP-vRYQq5RAK0ysz8HAK0-uSRPQ40-xBw9A40-_Qy6e01xb_-r1yS20000
08FyhSUml_e0000000000000000000000000000000000000000000000000000008
}

