sprite $dataprep [512x512/16z] {
xD4X0G002CH0YwD_Mo80h-yYR9q3000000000000000000000000002e2vdynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_y
nt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt_ynt-6lJj9ZjY60IYwKOFPwVwdpJmdxGRRfb4atbzBnIe_U9R8rVxYB_xYB_xYB_uR31N_nSNT8Fvh
lgue_ggNl-B_Al0l6035yuxtLtpSPlxZdaWZNZVhNzkTJv7hI7z5kWFz5JErziSVSPI_hfZj87_56xNsnn_Hsvz_jFR77z7Q7tz4Qt_ySUtkhn6VQNT_nUVQ
sryPsuR-_BDZihE_ygfz_FbFpSfX_lWVzvCw-FCVa-CIk_hhckKyob_pceVxytzdP8xnvt_nz-d_OGVxyxzQ-_D_xwxOtvy_V_wZjJ__EzN-_kAlQEal_kAl
gxU_-3U8VpR-bx__pENll_pvtzlvo___zMZeBy__YRyy_otlV_3_JvENZxFy-SVvxt_A-z-o_uFYISF-Bxzd_wV7kVi_AJxLjRk_xFyu5t_x_ne0-tyRWCS1
_dB-WvgV_wBcvp_9-MyJ6O1nD_Ot02UU_wlcvpyhgz_NtmHSzrnxyIlnkS_VcK3ylHcIQbz-lO1FrPDVzVxZhaz5dwZYB_xYB_xYB_xYB_xYB_xYB_xYB_xY
B_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xyp-pUewXTFTRvrnSxxTzNjlhuuTmQRDyvtHKHPVwscBlYexvZzkhyVGc8busro_ElB38jNBtItm14jaMh
yo_chno0u5-kNpW1mR-qc6t1wloFEhupN_0_x_ZUV0_-vntVdMy4_sB-qW48_iNyfGCGdVtv1_zg_ie12FuRyqSSxS__vKKhLr___1V_YAJjaW4OYRNvhopo
hWly4ulpB-7FN_trd_xZBl3ddp3zOl_4ulpB-DSFm8l5Q_pvJzwnXf__-aR4jETY_vj_-QV_Tmt0YxLB_FdFVz7uzEhr_lppc0lzR_x5_F766qBNCVxyl_7T
qCpY_FdNn3z_unUipf__NUtF_-Q_Elxy-VFdpvy_V_xy_Vx7d__Omfz_7FdtF_x-_iy_thZlyLNB3_wU_oZrvn-L_gFSd__yJL-uqt2vF_-OlgVFyz_U_nYT
t__m_jSLg_s3__Vrc1o0qUFzJ-z_9wvUvX_b_lmZiXUF1Slphn-0U2IjbgnUwi__znANZMNBD_2t_rkyRl2t_-DnyRV_g_r_-Tl_lRc_yn_uDp__XNzrm_bF
LJd_pVblpd_aNzuA_dpyoujquruG__8Yrxqc_kMDZFww-9Tt9VGNnh--XFx24lxuIqQWQ7N-zSy6H-48ZjRymi-VFl-U-ghvM8g_-8k_-8k_-8k_-8k_-8k_
-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-ClsE_ot6m2D-5i5_eK3eFY_UlWhdhVOltu052ywsL-Hw5H_HR8Z_HNfplDNJDNQ7tz4Qt_y4Qtz
yKUqziSVqTeVVqHhV_mHlVtvHrj__FpnHnpkp__LcT9x-ojhUwI_hdZMkF_LYFzjPtzDVLtluiz_vgj51t_ylzV0d__a7ItyyVzURt_-ZxFz-S_VT90___jb
X_hZvyz_zZx-_4ThV_vnYZ__wyvqgZ__kuM_-2jw-ek_-8l_RFpv-mPmyVyzV__Zp_-nbx_y_q_-_wy6_lBydpp_dOx_wE0lx_ye_h-hoVj_YYVbhkRl_Vzh
Ot-DUDfhVVi_sF_dsjjVyRdkZVrb_p_ryvVzVsN_Rzd_Nyx_KBpHjR-_dFybv__9-P-QuJ_ENyx_Lex_N7ybz8_sLqAVlsCXZlPNmZvN0tvL-8-xS_pl7H9z
_ZHVzbExSaW000008EZ_QrVO8FC1000000000000000000000000000F00000000000000000000000000000000000000002
}

