sprite $key_management_service [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlJj9aok5OYWyUIcOlVsljigEYHkv3MN3jSvT0L_yGcGBRpDQT-qmalRgJ02Zn-ozLsi4q9Vs
OweIm2pf6_-o4c3hctzF2Q1l_cK90D_zUuu1zDs_gGJuci_zcqg0hU_-JIM0llitbG3uxbzJ0kYxVrC2-9hF_N-N0DrJXwqV-1UK0FhcN_2r8FZcNre2wBl_
_0JmDL_WNt0CiFNDlwa4q7V_fX80t_rhIW1zzwzB0FZkttCCeE_-JIM0llitbG3uxjzK0kYxVrC9WE_-DIM0lllN9G1zz-yv1i1t_wOIGD_zQqe0VFUlIm3w
xjzp3A3l_aqb0BxxDvK0-kxVL0BWktzD2Q3l_dK9GD_zUuu1yDs_gGJGT_-c4W3V_PjA07tthoa1zDs_BW7Wkt_FCO2--pUL0FZktrG2wBj_KmcWx_wL9G1-
xfyd0FrQVuu1IRN-b83Kwqy9IFW79G3-L7yI8E4V70FWJ_Md1AHUVqf0mZye0V2d-bC24lv12O0_rPy4IBt-70CI_a44m1_aJmcuFlvv1C2VvKy2f5v_ZW7v
u9z70FpJ_Ia13PkrrgW8uFzQyysgrsFs-OF_gy7xn270VngzJv81_0VY-oX80Fu3yNs24i1_A7uU0Vmdw-Vd0FwZzNsk807u3zFFJm7yn-lx1070Vv9-dW3y
f_Fd2S1_lhwFWW3WFu_V9mi0_kVhvsS0_YVpdny0_FDPjyt8Cm3_VFFF3m3-EV_y0E2Vyv__HG3-EV_W0E2VymyE0Fuv_-00u9_p5mG0_vm_d-FyyR_liG70
Fv_hBWW0_i7sFo00-1_DdtyDY7y1Vr00-8_bzra5_lW70S3_OFvBZrcFsNFzyOyM-TNTAYiFmFd--F_y_f-rTXW0_0_d_ztzJslFyiT_POlRDklS0E3l4ouj
-P3nzvd0x_xFdm9hX3_-Vtl_O-2F_nn-nP_qEjyVVptXlmD__4_Yl_I4Vn20e_pnNthIVn_kZt_Chtrq0F3Fjxy2_ptT7ty5_a40y3-4F_JVa_tnL-olkVxu
A_0F2W3_OxP_xh-d-kElL_5NXp_-UG7WVnv_xhyd-kD_LVlZhrVpNmt--ES5WF-9_Bd_glR7Vq_pntzL--Ell_3F3m3DzyS_Bm3yJ-377t_X_ug3_whsnt-V
xey__lZZZp_--0l_znpyxrv__F77VtsmF_xiV_pnnv-l__6_Ulpnv-S_-EEFF_xuy_j__Fdx7_ml_Dzd-FjV_F7Ndk-F__dR7t_-_mz__F7NU_hVm_pnv_uF
_Bd_vvs7-x_mdrG0tF_7_O_dRt_yVRZ_5_-B-x_puVx_yxS__Zwy_u7_ov_OlFtxF_eN_Nd_YVU_UF_jdk_F-v-gVlyJ_rlTx__o_hUgtl_6t-S9_plsn__y
0EJy4_pnlr_-ol--H_ZZhs1fF_DVf_BZxnCkBj0_mHz_PSkBz7D-_FE95XXzlckMF_w-nkZJpVdnLpx9EfEFTkqJ_F6_xcJstl-pSzy6iXm130MTlMqJ-MTB
bxAfFsuMzL8ezAWJkTQ_-lE_bqg_ny-_qW0__ri3_FmllQRz-Ry7-FdV6k3dVsk0d_-j1Nx-_G7aNFpv5-lpyw_syVo7_xKsl_DVhipl_BUhFldpF-zsJNx-
UTVhNllvzwloy-_NlVRpxrSz_FpxLVdvz_kgwlFlrzNdtw_BpxzVLvz_lwu-_tu5VVvFdy0fwFDlJ-2Eto_y_qK5_CBnDu1R1Np-pnd0zt3cpvy_V_xy-VFd
pvy__opxypzP6G1__lpvy-VFdpz__lppYCwol-EVJFdpvy-VFt_-_FdZJwRy-VFdpvy_V_xyyITJ_lpvy-VFdpz__lYJEN_-_FdpvyyVVyAVFt_-_Fdph_0_
Vm3y-VFdp_-LftMM_Ht_PDAVFt_-_F4d_FcNJE_nlySVVty0_Fdpvyy_JstJt_7dpvy__xFiZp-PzUVF7tyowS-VFt_--9D9V_xy-VF7d_3dp_-Vyh_o-2Rz
7N_-_FdZJsRz-VF7dqpwy-VFdp_-PDQVFt_y2N_-it__ZJ-PzUVF7t_2dp__lyx_QVvdsT_nJxRz-PzbV_m9_x_UEnyLVyS_cVNdpnz_iktF_opxuqy6_7tw
k_HQzdVyam5_V_9tQzRVyUUFFvdrvyyVVxBjp_zhsHz_ml_swMUWMN_7dp_-X3z__j-Htv-35ldVcMdMt_7dZp-PzUVF7tyoxOy_sVRd_xNiZp-PziUVpFhp
vuy_cVR7dypwy-UFFvdsnv_C-vzj_ypxPpR--9Df_nDj--li-fya6l2_yMl0_yQl0V_Rcxyc_JCJ_pk_1lnl_1hml_sNDmtutvxzjFJtluFy_E_y6l2_yMl0
_yQl0VyRlmRypyLVTVyglrvj_ow_Fjq_zrJsR_Ehwr_dLzM_pw-gVvzVHVyjVlyX-FogBNu3sFvz7mFOvZU0RNu3sEOtW6r-0zZcDu1jVWFOvZU0RNu3sEOt
W6r-0_Zsl-obK_0VuNS9sEOtWErRlm5iynl0Dhy1RD_wlGPiyxi4RFzl7mFOllKRmAEk_NfzS__ppfDo2TY-zXl0zhNVY-0slql0zhNV0BOFlmLiF_SRmFRX
Du1jVWlOrlSck7tdTmdOFlm6iCrl0Tlw5h3zmSy0jW-_1MphMy2slW5il_9RmFRXju1jVGlOrhU0RNqBsDQtW6rz2zZMju1jVGlOrlSBGd-A_yu7voAmVVGj
u88_e6y2sqVV0hQFlWbiuvl0Dhu9REERm2I-Vkb_Ll5jOFhWwyt-f_RWM000001WaB_rAFPL5m000000000000000000000000008
}

