sprite $cloud_data_fusion [512x512/16z] {
xDotjHWn54F1OF5nbAd_QkKwaESISriOaE7x_D-J94cI94cI94cI94cI94cI94cI94cI94cI94cI94cIfEVWbbtusm1_2-3_P9I6lo-0lm7mJuU5-AVjB13_
jEt7g0__z4URFFpJxWw0Vphipp_jxW3ufyF-_DDXV_xfi3__jBi3u9yE-_DFX_tvfyF-_DDXV_xfi3__TDYVVphippyTzkUV3llpJuVz-QV3_lpJON_-wR0_
_tJOdtywxCy_7VRddmxxyq-7_Vcdm_xyqs5__kcmF_zqs9z_EkpFFntsvvyE-_DFZ_BFs1Mi5_7tEdp-wJd-pxVudylVo_ZvfyVuv-5_E7-lUlpyqsFy7_xd
y_SYVlxfi3__z1p_X_yR-7iBF_zqs9z_-alTmSy_7VRddmxxyqz_jGlu-QV3_lpJON_-wR0__tJOdtywxCy_7VRddmxxyq-7_Vcdm_xyqs5__kcmF_zqs9z_
EkpFFntsvvyE-_DFX_tvfyF-_DDXV_xfi3__TDYVVphippyTzkUV3llpJuVz-QV3_lpJON_-wPO__x_Fp_yrjUNFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdp__SId-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvo_-uY_-uY_-uY_-uY_-
uY_-uY_-uY_-uY_-uY_-uY_-ulyNuY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-ul-M-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_
-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-Fzwd_vE_Fzx_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-7xqo_b_PesygY080Xc7yKL_D_bkMF5iKHEqFwh_zGVstFwZ_zWVrt_wW_jiVr7_x
W_flVr3_xG_gl_r1_RS_gF_s1_NV_g3-sn_KV_k3-cz_KF_j3__JJ-L_-gdyJpyLzT_-eFxR7zJ_z8lwdtvH_zElvVz2luR_6_tQ_Q_qQ_Q_qw_L_rA_HlzR
_Thyh_Lhyh_NhyN_Ohy6_vlzslklzclklzkljVzolyR-s_tQ-g_tQ-g_tw-f_tw_flxx_Phwx_Thwh_Vhwd_Vh-c_llzclhlzslglz-lgVz-lyxylzkbSy86
01W8WedVKlpP6eLELynGs9rRc_dfxx-Qd_h-k_bfxx-Sd_B-s_dfxh-Ud-h--_bfxX_8Jt7_H7vw-qVoKzi_av_M_g7ybFPFvQUpVom_bVrp-Mdi7ynFOVza
VlhwH_DJrp-RdxBy4yvFMVzqVhhwn_FpRUe_b_aDCEVo-VaMzN_SvJV053Z8Jr7_lwly1fWAH_aDC2KkylFzJ0ajRiXl0FaD8By1v3U0_FgN0m0000000000
0000000000000000VW
}

