sprite $cloud_endpoints [512x512/16z] {
xTq7aglO4WHGXQ05OMl_gnr3ZVVpCbfGpJax-9ELULyx_JeT000000000000000000000000000000000000000000000000000000000000000000000000
000000000000BAawsvuI_qtpTm2FIyLl0Ao_0x3-NW3rDm3YTm3MtmkW_WP0_0x0-di1rDy0YDy1M7ylWFeR0F4x0Ell1L1_0o3-MYSVWFNFxQcjHb5_Bu3u
lG3MtmkW_bu0yTVc0Fx1EZv_tmLIVo-0-Bq0_ktlQm3rzmA8tmjW_Rq0wky547zxJJu0t_d9xQcrSkhl1H2_VmAUxtcV_0s0-Zi0yTTsmWlWOxuCWFex0F7x
EO3y3O3ufn-0-1zrILu0zJS0udS0rjyBeFu6GFmEmFhxWo3rDm3YTm1Bwba3-1f0_Gs0-1s0zVUxGEfl0CJl09RKAl_W1L1_0o1-1-3FVRm0wcy0nEy0VD2B
5q3z3O3u7O3rzxj0wcy0nEy0HdtdH_ulzRyW0o1-1_2uu-_y-2wG-Xi0yJk00R_puyE1rTy0p8xV0IpBZVEN_yUot3T-1x0jFn3_RCdw7-G_MhB-1_4VFjQJ
VTIt2TQ_YVz7wtAozSqByBl_Pkg_dEwz0_1nZVpLFn-0OFsR-BiDGmUWWlLlLUe_U022zM-b_gC785Z_TkVuk_wZ1w22zM_gFte0WlLlwZzx08BrR_FZJ-e_
Q03o0_ZhSrV_qGCGh7zJ_za34An_6_t_wb_3wvyFm1giVrF_6mp0QxbW_elwvmDGmVgtmV7dzPy_06km_atzHmz0iFvD_KSFG0NhtmR7dzT__W1imVeVdke_
UW22zM_gFte0AbZ_DlWxFtdzvm_05gn_K__H0n2iVpinVlNF1w22zM-ZFkOhVNk-tW1imVeVLlKVFG31-hSpurV_l8F1-hSn7_DLOVs_vW2yWlK_FDL_z004
wzzEZ5_zym6eOFtRYFphXFhF681W_Tj3_KSFGB3-xSJurJyVW0hMlmrU_xp-ymTW2zR_eFwp1o1O_tPY_EgV3q05wzz6hx_yjs3z3-e_-m22zMzZuv__-hUr
8ht-WSlc_pYX_ZDVWEZIHzTV_jNh7n3_x0FObj0byzyhimzomQRbbiYsZpq0yRTe4lTzN-K_EVwArly7OmT0_Lko_WVvJus_1Ui_Vm34Nydwpny0-LUm_hCF
GFmjM7_vpu-_WlMVVG3gtuBrR_AV6dyBrlzp1q3yZolclxVv0w3-BLZ_-GSW_de4wo__lxKEMFyMhF_i0r3_5gn_a__a-EiPhFzN7e3eFsdeMMyKhF_i0L3_
5gp__0CGVmNhB_zq_VFySy7wppu0zM_1-hVeJoGkQBjL_1Mi_-m1iFujMFyc_wdrRy7wppy0yTSQhB_yV_78l_Dpac3zPn-0-hTW_Ply9yTVmVhd0s3zMvqe
MF_P0w3-BLZ_Dno0-4_9Vzrlah_yAwZ_x0CGVmlYR_D_2h3TEFuArZyU0FM_u07iRU80g7_-F-CLz6Vc0Dmy_ahMVtx-ygzW_MSVWFXRiFw7RNB-ugzW_SC1
KFzB7S3sxl-AwdyDmVgt6apybQp__FpbNxt-WHfC_FKurZ-mrKpYRxt-WPfC_hMdQZ3nrtRF0n2_0P2_0n1_lVRGLXE9tm38tm68ltOlmCYF-3K0wky0n9_R
Fl454F-poW2elmCG_xJy7S2IMgiCWFex0F5x0QPPRf2_0L1_1o3-FFzN1Qo_0L1_1o1-FmdsdHy3eFuEGFnU0F_sDm3gxm34FoJ_jUPRRvY_0L1_1o1-By1p
MFu6GFqTWFYz0BxpOm3KFxTUy034Rm2ilmDGVnyC9du3OFqTWFfx0SHl0Ao_0r1_Vn8gVWFWTtuSWFhx6i27F1e0l_FZ0Ao_5y27F1e0w-y0hB_l0lbJVmDW
_Hs0zVS2-B6V0NXyVlmEmFfx0Qo_0R3-3i3wUm5ytzy0gBy34ByNmB_z3O3wEm3nUm6ilm5GVmSWVXyFR_qDWFhxO33n-nh0-di1rDyB87vV0rX_Bu3w0m00
00000000000000000000000000000000000000000000000000000000000000000000000000000000mFS
}

