sprite $migrate_for_compute_engine [512x512/16z] {
xDEr0GC12030E7JilstgwBlV3O1Jxm000000000000000000000000000000yfib0ztoYwWfa3z4THI_0YrMKJFofzXU8Be_xM_B1Ce_QcJaFni9j3pxluqL
wCdU7IH72iC05DrGM3lV_xPJtA2dtLPazFu-IV0JX4e33FxhvQzsLFj6Mb_j-DKt6gtz-KU2l_YBl_YBl_YBl_YBl_YBl_YBl_YV5d_n5t_n5t_n5t_n5t_n
5t_n5t_n5t_n5__Juo_-uY_-uY_-uY_-uY_-LDLSNwCvlvhpYp__llmQlVt5lrVynL_ynL_yUyLV_CLV_CM_L_p5N_p5N_nxnL_ynL_ynRzN_CLV_9ki1t_-
_Fdpvy-VFt_-_Fdpvy-VVxFuy-VFdpz__lpvy-VFdpz__YxfcOTbSM8X_iUlpiZpvn_NoPl7Vpt-HR90_2tGQEtFFpwBFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpv-_w3_wk_-BFdx_jur-hvlwMPtJtTtCa_-rBCzwt7lpT_y-VFt_-_Fdpvr_mp9p_2VvtxAouF__ONML__h6_klxy8wEg_lo3F__zrVBd
pvy_V_x1dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvyrzRV_vVTvVKluD_rYztxjE_-NlyF__r
ZkRdlnv__eVpy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpBn9__wElFt_LV_4Vgvl6_Jhy0cByR0FYVpvz_XnF_yUORGFctk5MS_yjG-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_x4-OFd_x96V1f_kpr_-FpX1tzlWU9Vh7o2plxqdphxqt-wUlZJNx_RyUPVIJz_0lZNr5-lip_zfmR-
z5UNAFltu1-9tIL-cxdBd_xwsYSE8Vyh8gfDGDhFvny95Ji4x5ij_2Sz-P1__66j_V57jFR77z70ttb_pITWyXzHeQR-ZltEcBhpEsN2_zJNF_0_zVKF_4zz
_KTlVgVD-7ENWN-KhBK__eZM_lWZMllZZy5_UoCgntztKRghip_-YDR--2DQ--EFwEtFVtJsnn_HsXz_1FyjZJ00nVtj_lpnHxJsnnznX3__oN-zW_dd8GF0
Vu_H8GFW-i-DGlphR-Yz4QZ-0BZ_OoyF_-9REJRgr1y0ztzkj-6Vy6kNucyy0FnJPen_NVx60y0_QypudyF_rE5ICFwvvvdByKyKgNS0u9ygKlS0m3z_0FZN
vpS0_BC6W7z-SVW0tFmJ-0iF0F-Lej00yCylZX-0mJ-1Fsy0pe-_0U1VVm3uHnW0_WQ0lm7Wtsm0-4T2XGU0lm7WRm3uTnm0_YCw3m3_20F0tm3mDm3y3G3_
HWF0_uxKxbe3m3_20F0t0FmD07y3mDy0y3S0_7Ss3nm0_ZCh_3Nz3G3_d7hpyv-z-VdFtlpyPpDz_ki3iFK-_EIruJyx-VDV7u3nBd_-i_V-pt_o_oZxFtz_
_w_M_ix_vvly-GT____Zx____7t-nz_d__nT_zF0dt_mJwlYzRyD_Vcly_F_edhy_3Chnyy_jMhykVw3Vor-_jczWP-_1q3DLluU0CVV0o3vhtTNukUVtnlv
-N_UiVpylG22lpS0yVS6iCd_wohnyyzldFq2IFxU03pvBrI9dtz-fVZvvtSyF_-bIftvyy_lRFx1Vx6Z-MFoNsnKukUVtydywspyq_cpVixW_r6lv7_w6Hl_
1Fv3_SSylbFvxuKDc__JzS4tuh-7VsNfnwBQvz_80EJpZ--tx6UNIa_-2VmBQpz-XRQiRm0YU_VFZt-adcRMpm3KvzVOJXEL_RNH1hy1Y6XyykUVGD5qzpS0
-7qA40tz3G1-0t0IlwuTJj7MtvKWpVaD07uNWnx4hwktlvhpgpc_clEhER_m5ym0331PzURNrPjVmnz_Hu3E_7BmBv81k3ip600IVrHpVZNdLtD-NStvHJy_
0u3Vtu1_xTav0G0W3C30iTtmxnOVpPs5yFCEk25UduddHtsdWFHt3_N9Jxq-zVhKwrElJxq--VhKx_jCFJxMVSIt4rZrsPMU2mi-00000000000000000000
000000000C07
}

