sprite $cloud_test_lab [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000063spYJNSXs6OXD3qlvN_4U_-Yu-Zkv9H8uh1Y72zReR-ua0n1Vmsw6-yDZmtuFVrV3VywJsUpF6
B-kFv0FYRuyOl_e7mhd-_eJngt_6jVx-XF6hIpZMtvymVdKPj_hx4yQljd2glpzX_6eRa_pAWF4h0OFw8jFzIiGWlyPilv8noAynsQyEyBdwAuwmnlhL4PR1
vjUOwPTrY3J8hp7HB-iOQP1VOvvVra7I8B_6DB-iewJ1jtuIQvXV7MOPR7-9MNvr78Fy6fFywWOCyclCyQjRSCn_wHzFyQkRSEelF6FWHtzflC9p0_pgDZpo
2uzEyAiRCUWlFMplHtzbGFhpp_UhM_bmVta1Sp_wAyFHrtY-NztC1_itBDBcHtzzClq3zlUhs_bK_uPrEltehuwbVy3-VjN0H_htBzNlH__ec6-ysAyQ2C_j
ho_sVBzgeR__sTLC_UWVFVEDj_fbjP2Usv_rged6_lIdVyE21dxqrxO3tqzM6wtz6vRqywC__UbFV_gl6rxJUuuV_HlMTF2ZV_RDDr_fLsrat_OFaqNz_QeH
-Xlu-Uv_-hF_wKz_-jEV_lIdF_tfJt_wy_CV_Td__FwNt__ozn_-_iFVV-dFvp_eJt_wqv_-VFvxId_U_-3z3zx_eZ_zwS_xtxp_pVaFdF_0-IyZ-dF-4-S_
SVuRvxzn_YFzEV-Lyryv_vd-dF_E-U_S_q1_xd-HCS_F_K_qv_utxd_Z_aVwS_yhzxzo_pFtFtF_E_s_8svXZfz1Vhy1J_8poEysu5b-1labLXnc3VEhmmX-
5XjicbyQVERJQC3p_D8Wlys09_gbGNwJ0S_qIuFy3jzahR5-ZT_w-MwnoNujF_Xv3tYsNqD-xm5FzpF8Bw9D5p-flWFQUF4JyfkWJHS_eRu9sdJn4-gRe4qN
Fw6-2TfqyHFgco1E5p_X_NuJjE7YbyAl-btGPekVyD--4zfWyNCB3m000000000000000000000000000000000000000000000000000000000000000000
0DnVL5_WVYgB-ylmq--du_v2pO_xAHlkByMluNvQxYyM_BYVklV-SlpY4exrzoUCNrp6hVx-XF6BBPpgxqyOlzZ69ByoOFn2mA2-o7I_4378hp7RBsGCycjC
zei3VAx-gYEiiNvnX6NmgtI9dEaNnp38Bv4J_U8W1labSfvV7CKWlqHEyul367ph9x66-OM0mJU1TPnPVd4SW_mQa_pY1WpoQypnYrimoAynnUzIq_XttjEV
_l8p_VbrtFswyWlF6UGNcE0dL1GUVKX_-aiF6-JNUB-V451xthy__UK53F9hlDrFYAUiuT-V_WsBoDJjkFiPv1UMSUrF_uPrTAe1Tp-3_C9Abltftx6KJbG3
yMA_ZlvXiFqbtkjtDDbh-jE_PJMTh1RohNxHqpyCjh-4lv_7XdriV_hJd_vwhjx-rSOx_QAhVz3_NcnswsFxqv_-zAS__PUIP3svF_trLetzizh8L_hrzK-3
xI_nHh_ewn_iVmC_x_xiV_O__UbFV_hJd_xqfp_zwS_FV_pyn_vd_xF_-VqlV__Xxp_qz__xB_tv_0VzwKz_-jEVpt_p_WVlVz2Vzx_eJt_U_-RzRyv_uFm7
-dF-2-S_SVuJvxzn_XlzEV-Hyryv_vN-dF_C-U-S_qv_xd_W_XVkVw4_zpzn_nltlz6V-n-v_vNxNxd_cVkVwS_zxpq3dkCN0a9-xm5FyZF8xpRWMNu6-ILM
7MODyul327uEdxNCQNu6szzem3dFpo2_pO1pefz1VfC1vqm_W_mMtsIjiNu6t_ffr04c-xLiVky1p_PhoEyzuEb-1lb5jEdY9zLtG1ilVa9-4xJfuYVKDq6R
Bdv2VHEqwU8dr3T1cov-GdqJGdf_7Z-XlWif_IeTFo6-3Tf_g_W9xPtG1elVD-7_Om-E1G000006-LkFOby5000000000000000000000000000000000000
0CnYxyoIvWR16FX23Rh_YNE1B6D_YB-hqlsQ1T72inlQwSapo6FqDqWFcq5UeRz1Uj0CyXhz3U9J9f01-XkaHymWG-Z-0FMJ9v0nT7-0-haJo07m_dwCzJd2
gkNB4HRT7-3Y9oxXdKDikZz0_JFGzIURxWzG_mnq_Scc-mFKFmDTVxBf_W0l_KWlObOEi-Z-09S_Q07dE7H_WFev4qW1kZz0_PG9f0BT7x7-Pt_v42c1ztU9
Drdi7-El7t_ox-Qa1jxV3GOfhamWHVZ--emYs7_NNvzfWFO4KWNlhyvuUFjl-cjpOl3c1586xw_CaQ7jl-OFNNz_0gc3zrVbrBZst_87hhy_WLm0xw_8mK7j
d-Mll-Zw2_YJ2tpe_gYNVty1vmfuVpNEZcZ_87_z5TTVm3jNs7H_j_kd_7-v1DvV0Vkt_-F3sJ_5Nt-vzV_7N0Flhq9XCFkl-vjZ__Pl__PVkF5isN_5NuN6
MFPVyTTWtyk_N-NBDJRT7-_fl_-VvY9qV_zB__pht_wz_ktV_ktV_ktV_ktV_ktV_ktVzt_sx_NFxz_FV_tyr-z__Fx7xt_z_jVVV_Zx3_ktV_ktVt__pVVd
_H_U_-7zNzx_PV_sx_tVtl_j_W_k_-3-B-x_ulvFxl_a_c_k_-R-Z-x_wFwlxl_g_i_k_-p-x-x_xlaFdl_W-I-U_-BvJvx_vFbldl_c-O-U_-Zvhvx_wldF
dl_i-UzuVy05y2FnKm7lxnxq-2c0ztSJUlmS1-_lAkjpc7KuNmwpyFxkGb--EqVPU7-teSVVpVhv_lhGu-zc_Nn_VUZnTxD-lhy-2_xIPLLV-l7zzQ4ltXm0
x-ydeSUlri_truSUlri_tryVUleCqDyNqEFdDVhx3dhwl49_tqDFdyVexndqz7c4_fv3Jv-lqTyxwEa_-OAF_WRGm-_ybQs_EVJi-GFwEmez-Anu_Vrg3mu4
000000JvMu-mG3K000000000000000000000000008
}

