sprite $migrate_for_anthos [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000WDcxRtG7OYY4miry5jtT_sfVpj6X4p-rkmDub6zJrlIAaaojQANP09Ho_l0p0FvhEWM_
0i2_r00K_E6lD03X3py3uCy0yEEFVvS1AFZ3NsW0mfzMtiK0ucyT4FwM0g0ZdyK0uey__0o0_p45Wby1u6yC27zP0T0fFui1n1z_-1a0_zFiAlWL0FuC03_-
TdqmWFZZ3py3u6yP07u5W3y3m8y__5iPWF0tzSC0ucyC2By2qFuC8Fxumyy0-Fi4X5y1uCy0yEDlxCS0uey__BiO07y6W1z__1a0VlpXPm3yyJVrmm3YlwhN
0RN_x5a0T9p9jTe0uZ-pYld3trm0-7_-RU7DqF0h01VzbOu1nN_B0g3JsJmPGFpFDynMWby1uEzcQFZx2W3_OnX0_4lvs_Knmm3Y_qb78N_u5G3-bW7WLm0U
U2im0Fpumyy0-7iWrDJF1WL0juxVZ06rlmBG_WmW_WN7WU1N0FZx18HV0HZxCO3uus_inm3Qls0CgFqL0FuC03_-DdqnWFZx18HV0U3lE92f7mLWwiSweFRV
hG3SydoU583u6mF2xny0VpT3mxz70RZbcG747t-tF9yX1X1__E5d0Fptk1aQVWNWbcS647_yxVfW0F6t5Gn-1O2_dI3mAm07VXX0_6q5Wry1u5zmCxIf7mNW
m8yneFPN0Dg_-bOmyS-3giU0y2Ub1O1_NbJv2GX_zSMmndvv5GEuvRcClx5VKcm0ySytbOu1uVSuY2TU603-f8A_0p_vMGpWVRVcJq3uFH3fUK_7WUxPEszr
oNaT22Ry1ftn_P_scj-6QyJ62EogU8yHguXnMfutKbtwfOi706_yIsq1rBQ3_dvn_GC0LgT-gQuS06n__IoL_1eG_L9TzmY0VwazWBL7WdwfhXe0-9S80FqF
0XZidrEUfU00sFxwFUeI_-WF3W3_-dqg-MHez4irV01mqvSK703RNq-fh_c7CkWF2e3jBta3gElzer-gaGC0_pf59Ty9Wdwf-WS06FJ71C3srrag-IaW-gKQ
D03mB_K5OF0FzJRzKlKD030RwG-WTXDCVxce0GE0wI-51C3sVwv_dmYWflf7_tuGm0i60FuVwkyCeFRBGF-P0Fe70FxhXFwf0Q1V9_G_2C3b7wfD_-00sFxF
zPyDu3FHF_gV1z0_0F1Vp_NF3G3zCkX_442pV_mlW_un0Q1VZ_Lx0gWP_j5l2A1l0E3_gNvR06k0V_GR0_0F0FoNGNzl0BKVmFP_fjyJmFC10Aj3lpK0_m1W
-p_JRm-W1Wm0z1i3a3C0_5lqzmUmTZleDmVW7m3uVwAV0D1l2m3_Z_ZOzSyFWErlq6y8O81_zCyB0FzM_Vq1V7OdwFS7O1m0-5y6_MC2GByC-dq1uF_dARl-
-G6m_GtwdG7K0F_eTmHW603uhnRz_G4K-dyAWtvt0FefUBvdr4y0hqA_ZK6_Fu32_mFtJlt-01W09mzaRDJV7m3oU_Jt1y00q0dAe9y0_EWG7lt-0BBzwnm6
_GHWfMJ0eDyUG2NwbsRezmUGE03gElt-02hWHku1-Wq1X0q0ZTK_Fm3iwuLNMJ7-Qx3--G6m-JNwKjdyhXKa03yAq4y0w7TUCVODYqS0wFU0_zdw2G3z3xyQ
_v_9-f-UnaO0cgj_dVWcEapj5j1VXvP-uW10l-5R1Gw0qYiugMnzFG1sltV9bZUdvw3VE3FBCO9rb8L-Lm2kFQYZyDZlsJC7loC1o81poPPNGvf_lGt7j2e2
QD7lNhCM4qd-zKPCl-mYW7RzvwRrQhIXStnuwdz2KvdIyWV0zlyDEfwI4O3UY_NNNArhW_udgxPaOKG0-2-vgBxbGV_luFyDNnm0-bNoitgMg5xh7rhMw7xz
Stkgo03M-LrqvGourRzZ0JMN5HQ0P_zS-KG0_pz_RQN1L4u0jerJ6arA0BurAyrcsPOhGl_y02JJWjMbvtdV5q1vLYn0_oK1I5S7uDJV543_4BZd4Q0C-YyC
G3eUm6NR_q5Y5hPt1kWv0Vw_5K3v3t6umxzqOG3BU8xBPG6e9m0rqdQKqmN-fTi2w3pBQNu0kYk0wlhfjmIWcm9O_GUw3VSltHD0_yNE3q3N1F2rGntn__q0
wdjNF3e0wOO0rdSlkl3_pG1USDbZ0z3u00BEk3EYsG7KVe0O0DBa0DP-IFm0qE00zWd21u361h1F4Hs0fWRWNOL-rbNw_G7mzurFNZO1xCW0D3U0VHpyJmfW
EqWBG7C3s1xmFoI0xO8_SpqYWBMlA-1pZtz_0BMTP0m0JGvWUqa8G9C3s6xm_-e0jf_R0z3a07OB-7zh05SkaYBzxtUlrBLtWen-hdNfHidqltck_3UP_dVs
kwNuttnSyXUX_dT5tp23_rtSCli7gVvt3V3VKK2g_rtH_siI_xi6-FSNKB7-jy7_m0HY_GyxESz6gFzvHwUQg4Z_ClWVMa2YV_qB3F2FVloZtqMEV_JZN_qG
G2NVQoq2M6--_m-u0TmB0Q0V_xdw2I1RF_uB_Go0z-g7oZu01ZW0oWW1PEl7_mVz380twuUrdMJhPm24w-Sr8FeP0Bdw2G3z303qCm12zVCK4FqCW63z181-
_AEV0D2FV_GJ0Fhn_sBz-pY0VlmFqE_o3-Z7_m3zBl_WauD-1e0o_1F0LFrGFaCJReK6snPLqlOdWA7wmQD9QVu9OAP-gAEcqC_70ChqJm3e9u1i_Tm8CF0l
Oe7UoMu2mlL3jdweRFsWbr6x5GZN3-7J7y9tFuJlVWZN3-7w8Von7y9tFuJhXt3zKE7s8Lm_X3_nXtJz43xx8Lm_5FOf85e_ODyA8-2ptmsaRtv8VyaFwVOX
VV93-jw7J_hMXtZx42yVa0-u1mdt867-l-t10G4000W2eF-lkv4Av040000000000000000000000000000000003W
}

