sprite $database_migration_service [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000002OlVj0Trm5eZ2eJnSrtl-6NvYSWp5Af_ujL3SOUyBx7fMR7ezaV_pH_lIJ_Udpfv_eh_RW
R_b_uDzldnvVLqcfF_Wx-ldJvqy_nb_zmT_oywVFdpv_-lpn1_ZJvq-VlnS_VylFdtw0lwEVl-NdJv-_evy_VVwE_W1_-lpfytVnyxVy_EdpfyyVFt_w_Edp
ftzzVxK7VylFdtwOl_g3l-NdJvy_VVukVlwMdpzz_lJvq-UFdpzz_lJvU_7pj_n7-RSdqtiX--_ev--FTqsfzpfXUknNgvpekmFecm3y_Pig9Ve_Bc02wBi4
lFXDW8l_fzNzeky8e6y2yBS_h8w8ViOPiCsElak0_XKcG3tAikzI-l8x0Yo_2R3x9W3_IUxJlcVq7G7qJO2FVIR0nPzohT9t1D0t0VHFyhPgHtLbVaU0vJS1
lUvNwyaJeBUtBNa2-FzNzYN0_wtbJW1_4y3_loPy4Em7LNyV_nz-47G4z0H_4s3_JG3_Lpq6-ocgRQn0_yzF0MNklmbuN-RvF_uOxBSezVx_tDRjVgI_2QXW
VnDGnVzJvU8FylSKg61_4r35_mUrdghF_trRftzdVnDGmVuceDx7_oyVW-qMrVluHpu5Ul4Fde3w7F-pFGRfjzcz_NLRlylMRFZRMsw5_sb_d_glp6__2__x
wEVmyyVFluBv-LSmF_-UpC-_WldvLp0__yhbvuz_llzwuYgOt_vNC3__okJdZvz_1VFphs1-_fN9pny__mhcvry1_FpndzpVbxrxyzl_mZ_Fdtv_kZdyvn-0
jcCLlFrEW0hcDm65Vzu4qDz6cyXl0Chs3vQhZ_zzz0_WDm7uamPWUN4LpEy8g61-4r3uPxHEXrjVKZA_8w3mJyplV2zl0l_CxFxaxJS0xScI-Hq15Snl0YgJ
tmJWDm0Lp6y2BcvJ_zSlcTr_KVsYhGV2utS45Fx3ety4lmdeTP9qn5V2TQAKVlGhNL_X_5h3zPN-1tmKllrQmlsLxgzqV_47U5b_yUVFdtyRR9A_xB_uY__y
-2-3dSrVzhyFnj_v7-NV1Wltj_zjTtyv_yLV_CM_3SRV_lFdp_-mRmDAzb_ynV_YyL_d-tlosN_ndnR_TR1Z_6N_nL_ynL_ynL_yTTn_uZhY7_HtEko_-8k_
-6-3bUo_-8l_QUBV-7-J_HV_eFWl_Eq_V_xy-L_sTpx-h_XXk6J_O-EVzaCFVwS7V_pywVEdpvy-__dyIjSN_J-gtxTmVgNhArrVuVfQfbCj4wgNfVJbLxg-
mlMLpgzqVVcoDxtmvLUwljBr5QY_VPccWvxxl-bH-j6lz3UVmdTVw-6_3DUXANtvHNzo9k3SRpwbBxzkfz_-BgNlliBvjORhArrVwVuAzrUwlzBzTNL_WEjO
ZRy5db29l_YBl_YB_zpuhuFTqh_P_p-kdS-_-p_4dF_YlrFybnd-il_YB_xpwrNyrx7QA_rb_yLV_5ty_7tPor_ynL_yjy4g8Fil_iV5VpdUN_PV_CM_rrFn
NyTwpb_sN_p5lmrM0Tb_yHT_yHT_yHV_ryU_ZRLEyfVz5t_ndn__PQnv_hB_uZy__cqm_cN_e-EV-nUw-8zNEV77pvy-V_hyUvqi_ct7QbucmD6_tRDmVJKN
_-HS0ilKQc8cmD7V0xgg_bR1UGlMb4o0ezy4qEznXUkhXVChNL_X-bhedpJV1jGkANtvHVzCUGkssZcbBx_Il-oLtP-S8s3zJNLeIbz-fL_y2jzzfVChNL_X
-bhybPuTycr0dJQb7_swklysbjBtN-d-kgP_VraAtt-b-olTNrVnxvDI-FuhtL_f_WhtrnhkhtH_fVlhJFxR_Ybz_vNkh-Fzsw4fVF-rXlihtL_f_WhtLxg_
qlqLxgyMxgzqVwNxQvR_TesKllzAzzTh_Tizyylml-tJqHL0C030GC3-8vl0BzhShP2NQreSyVxK-nFlpnBlJxq_zVx4-tF4-rFlJxq_yVxK-rFlptF_8u7u
_zJxK-zFl3zBl3_r_kpdHm00000000000000000000000000000006u
}

