sprite $partner_portal [512x512/16z] {
xDI7RGK024F1T42D_RVD3cd-4NShFClxE00000000000wYlc2teV3lKrCuSN87_DvG78NtDv0FBNN1w0_3K6eF_NxBydVuq3qF-BDWtzwLJ_tisZzC_G_pBz
PpFG7_tHduzS_zeuAjU_5_slqdys0VtH7_sfPFzUz4T_zBz6_zaCz4T_thBzPwEeRF_U6FIdhlq_-gC_-lEMxZyRHANxzuQWFtNf_z4V_T4V_Qby_rxqlqh_
MVH7V_H7_m3vS_rxqH_zBz9_5ltH7_q3rC_sdzuuyR_U_-m4rFzaxmwo5OU2481EF1PlnFvtsskmWrBy1mlepl5IfOc9_u6_gm4DHfYZ2q13Ele6VziIgBxF
tz-0wlly_Gseli_Vtu3g-_pz3QY-rT_VWEhx_VqDgBxUlmtGMxdrzVx-1i1maUa1bK5VuA-F2D-mLfvQlLpyVd-jre7X6sU9bK5VxEzl01ui5GE_h04Olx-_
0J3SSwATLHY6N-BlBm0ifnPwBOE-oLy91j-vfTxBm6_mru71VDUXtikWB_3tD03oFldzPx2FdsTV0R3ejcErcE1Zlp8apx868E_gydoKFSC_vB8203k_Nj2Q
BT4VKbK0ZHe27ZmHeUtWtrG08E398w7Q0lv51K3kasSI0PAmyPF7sW0W-GO30OAHtry0P3zwEiy2o-uVSaS13bBlCDAvkVZz1K3-BMQZ20pyxW8Su0ZYvayC
gIg0FwY_W3-u01Ib_6GNm6TvXV9Vkm4w_gIg05q0IEHl0MJvW_paPMy0vSyl0EgluoSlM03bVrY0Be1t7l_VBS1q_8Nyv5Nl0ENFBm3gh-GdRre0vSyl0Eel
vIUlNW3b9__A0YZ_nGMeFtb90VgzdvYVJ5y07Ny-ozKBeFnayWAeFv_dwWLGVZ9t0PJ_uWBKdwfS_GvGVZ9l0TIVokGjWFBh2z05y4hYltO3TFofpzN-vIVx
3i0O_giBKFwx2u2x_SdR2r3-R-Nc1V0s-5ZuymimYyV_1pyjtG9G7oJuy_kvzHrWBFvl2tz-0KpyUYCBVtu1SA4_VvKB5y2u_BcFdxnk0S3ex-Vl1XYVFnRo
atVvZz6V1luM8CoVlyz5_cFrfuS_lm2unP_SNG1aBu1PxaykBm29u0KmRdykvIS_K82b01VuqvaFjh2b0Hv-kPU1NrO0q5W0_7L_klFH229l0SngV_hpsGGY
R07C2dyQ-4K586bj0FwmFtVaqvSVEVwpn9-B-SbFN_qn5A3-bWAGf7a52FZz_jXS0Fp7xC6m08BzENiBWFyRFQnV0BFTVnRnVpvvitm1mE2VLm3yz-1jVmUO
doVm4W3-U_5Y-KT0pE_p7uUJoi_jvu0p4GjWjl93CFx61J0f_XF9p-rNWSUI__hjCJE_Vlpr4V3lNG2Jny_btmDYF7dbt0M29mE7ixi0umeL1V3pOzszut_R
Vtpy-l7t-uyj4Dm7wkV7Elu3WV_c1J1EVl-bd_gFaLy__lge_5i0d8tZN_ynyAl7l_vuS5aYWPy1JmCZT06CWLz_xkVtPwh_6FWDus-w_jC2u1Z6t-2FMFyn
ysCdF_XPjlh3MG0ydxCGVZ9t0Oo1V_luy_Fa-izQVjhuMm01V-ZuW_-NNF_PoSyeVZBNVmpyWdE_fGy0jm0ugUFFPudr7or_wFY3R04K_A4V_lWyIFKV7N_e
-0ybIVKV5N_c-8E2j00GxTfSVZBLVtx8V_ukF_do-FiB0DNhtJy0Q5a0isFw2SFmQnFgFqB-eCUzymi0Vm5m8iSV_58o5y08-0tZRzRt5u3c0k0aZZ_upI1o
0Sot-Syb_EGxqdyC_9xjpw_7u6ye08H31-VmwnEv0CR7JnD_VW6aLoG5_8PtVoE_lm6G7eE0V_FuyvS9V0EOiKm_OHl-_0BGKG2SlF47Vvt41J02_fNZFpJ4
xV_-IW6WdJmuXp-_06_r_w_cF_xj3xg2k3U06J6_V_n1NzvMVtq1SEB6dzxOBm5y7YN_cFb1T-BU06Pq_32FF-YFoLzV0CYNBrRoTm6C1Ci__kTQVtq1S0pZ
Nt_J0XY55SpJNt-g_bKSm_Zh_7i9uFCyflAF_vdOyVSlW7awgVJxuq9_VG7mZTSUzLVbzQt_Ny1llkld2l_vsl__O51f6F_wwmk0ittywu_l7G2ER_phxry0
nph--VxlSF_iyJzpnVZF6FmVZF-SNmMiFmN-ko_zr1y6Vy6bd_eR5e34lp_sKN_zyvxwtEAFBzs7xXp_-liNWFFSp-zV_v3nh_zyv-TfdUDVV_y2IBdhf_wp
mvy-__hhZqCy_iZohx_pmr_z_GNGVj-6CF_wEyU__lvJGEUvN_tz2m2Vn3p-zTyTrF-20lZ6l_uT__hVor__wVQl_xtZN__f-DV_sl6l_-kYyQz_nx_-VVUl
VyU__kMl_tNRl_uT__ft_FlyP_dhlpEeV_clzN-N_sf_6ltBVtYBV_NhVor__QjV_sjF-kj_y-ptxpyCrjhN_-qV_tcG4vsXFtx-U_rfJlthR-U_sR_-Swz_
__vt_Jl-D-z_NCplzsy1tkCUVwD_FmB2n-_txmhmF-yvFlyMO7uGBlLl0IQ7N-_V1im2_vVBlmMOLUDV_uFxRleRZtyBC3v-ltyRCBDn_Ej_S06_rxy5U4_C
-ElzUpKOyxDWdNzNmCpkyQ__WPE__lxWXfzwd5_xjm5J_vI0-VolHVujm6jiu-_tRm7czs4__prBDlyyFARw8vf_oFpyYG9W1Ac_8nHaJ7dLVyCA65lgBmYS
_FNt1rRz-lipHlxw1w-0CQV-ei39Ntz_uE6lVsu1Pa7gBmkS_FNt9z5_wYyBhlQl_t7o-mjGVoJwWwxKlmkW_lxKNnM1VmlG-My1wfzNWFeFMu2U_nly0qy3
U_qFiolrVnZ3ztzjmEaNm2igK7yQ_5k1qnk0jWTVJUxuavWRubJf3Q3-bD-r0Ehlt_vT07UFVmlGyQ__lUFV0dJywt_l-BS0vQ__lTk_1RXx_5k0Zd-w_xDZ
VJfKGExuvnS0ZuzMy982aUEVxm_10Mi62ddZdry0oHTNgjSJMVpv1H0TiUpbHDBsp_TN7R9mcle3u3yBPCUiV3LJnZ_VNtVGqc52plXVy3YGqX-13_m8WwZf
r_lZWZl-OnQ0zA35iuI0yGylWFQWrRE4FUDVVshySS5lViSKWB_t9-CM0F-g_qjyrFfP2l0FBW1_xq-cBG2G-hmJ_VdS7tbF_V8hYU3N-vDf2m0q5g3-t3F-
zUTJVyJvWt-s08pmnzyP__eppN_eBa3zZG6_c5Vzjty0u5UptB_-O6m1wgyV__hZAd_GNu3Elv7Vxr__ERRGNu3wmph-_WBKtnJ-TVzNh_z_TAXT0E-B_FcZ
OAD_l_y7VvMh_27mD_7t3G3ttF_57-RE-pyx_lu2W9_aTS_ztupnx_CV-VwywVa_P8v_Fm9-w_dVZZzvq_FVfn_-d8y3-N__uSHDVzy1eFH7s9M_5W3Ytt_g
ztvHDmB8V_yFGL_xjm2_-_rFF_-XAHXdD0SccxDZoz2LiKPoMAAN6Zv-q9RNU2CefUJLnZ66nemzJm_e-Rm1nndGcKs_2VMxl_y3G62l2Ul_92SyO6O1wW_D
-EVxMsjatTl8zwVeVfxB_A7vy0Zw8_hqVfK_H2UFZFRVS3NHngze09XRW2MV9MtwYWemrd_DoOI7NzC0CBC0cyucDtrRWqn-Ac_WJ_GtVOTCvXLWtGKb0x-e
0c1S0HPUKZJeYnh0CF-TrvHNNge_s37-EZ9i_LR1eAzP0WpovyU9yzUFwy0t_aemyB-Ivw_NWeLVwiN_Jg2_NWimR7-T5nybqLy_gp3mIxXU2NUN-FK_Fnq0
kRy0b0Jn_fG43_WD3Q0keVvwAdZm_Kdq3x5g0-xMRmFkrcy3xjPl0-xMRmEg_w-z-YYCA8Y1AEXitPe_ssNnUsPLHU4fx9w0tVLDm7NrERN_t5VV2EnUVHEm
kxuHk3W-P_GF-gF_HlfFdeJ-w8__pmdzW_xeZ_xRw3zv7lhZ_jFl7_H7V_JVHlz90VgZFp_j_gb2_ohzqNyh_IVelvN-_wdYfzi_PUXVf3_wRwN_1FtHVoFz
KuV-DVgZ_rRwJshG7_UVlrx_703zI_H7_wtqdnIXF_ephVuv0leNw3_fm_xJwH_qlvi1sFtz3S3k_0PWTtu3y3RvUQv_pW4000000000y08
}

