sprite $anthos_service_mesh [512x512/16z] {
xC4X0G0000AWQlF_MrVOWDu1000000000000000000000000000000000000000000000000000000006Njdavmw4WR13K7NRkv_szdExqEE9trPT6SUmD6g
J6o4iVax1nr0tlal0Fas093_PSqSO2K9Lu3sqGAI94m1yiedOFt9Iqi3uqFV0bOIAa79DVOyWEGgEnv0SXt-023gJ_W3WAW_sUi0ai3xhtnH0EeFVeAbDT9_
-0E0g3yBFO01uFCVxL_zoHu74Fsh7tq6iFA50UW_Enn0thn_y3kG97002pW0YVxv0uZ-HVyIthy1W8IU_tsqV_tdQF_wN_eVmSU_w5_qB_eNx_z5_yAihtxz
--FV7m21_Gig80VuDu1c_S8vI85_mIJa0Fy6qAvV60yvmRy1zEkNDQyYd7-vtuRw3U1W_Vu4oB3-fRDRoM00sVlXRm3gDm3r-nn0_Nu7yAcVju7U-1c0-lrT
mD7s_NNm4VQz4tX8_rilN_ssy6EUyfi2-X43F0QWVWDGlm6etm3Er6y0wZS0zHl0iVeDu73z1g1-NnHMlm6etm3KRm3gDu0H_ShvmW2QT-bdZGtwPVgFU3l9
wAY0VdANVgPt1VHZk_G3J0lePtRfXnbt0_rx542zVxPT_phZZfDR6DVFxy93Rho3_kG0_UK1mBiSeByw07oN0_G3JmBHftv71D0mDQIV7uRdLJ7s3lhpEk3X
Nnb0xIxzbExDpvup0kXPl4p_6Vw_V_8K3zEFttB1NVhrzw_UF4m_PVz5gMRkj_u_KA-VtwMVry1r0lf9_oy_ivlKpmzpYF-ri_wb_u_m-ibTzB-ZVlrVPqVz
-h_EZlhrVvqTzUl_EZlgr_zrTjIl_-lig5__rzbHl_wliwD-_L_dRFtwJw7-P6mL_QTGVyB_AO81WFeJzOCNo-jFnXRHVmhr9-mV8Xe0h3zHFt31hFvxBEGu
_ok_Iw7-XDA_UADyyhp-XFel50VwJw7-15aYVnX0X_u4r6y0lFv4_LDF0PD2_Scq_jNZb4-Vrv-0_u7E07Zz2QZV07Zz2QZV07Zz2QZV07Zz2QZVkm1UVm8-
y_Tr05v_udq_602lFvdJRm65-fEvv7qQKA3_-jUw_mU_2U3whtyrvNzQ-2Pp_At4VL_aW4-OljjTmqi9sCSx6437IucGVWDe-LK2ejy0UdwL2EWtWAQt4eph
Du2kjn8DwpU0jhSIZketWBwt4W_gDu36FoMOqsy04qkF7KewbrR_69rBgt-CpgNLFqRdqkeVetDfzO_HkRJwn-XSMlrZT2wj_Z4wbrR_69rBgt-CpgNLFqRd
qkeVetDfzO_HkRJwn-XSMlrZT2wj_Z4wbrR_69rBgt-CpgNLFqRdqkeVetDfzO_HkRJwn-XSkbc_0PITIlr-YA_-3K0CG0n0340Cu40CG0n0340CG0n0340C
G0n0341I6S1x9W196WD8CX6098q192C1ID8OG38IW2ID0IGZ0KZI640o4e0aZG4a8m58qXX00WIW_fO04Y00zRS4a001gBybW0GBGFry00aGWFg10D1JgJza
0Fofr8y6m9zA_MW0_AdKZmR0dqhzQ03ygTIF1i2Vwa3j5rP20aYm0BPFOUK2R02vo7hq_vSkvJC198y4O099qXz0qXD0eltX09Ak0AB-oG1kjcC05txmKrDF
tBKbyMd0pCCWF-O6_S07sQZ_lW1kqCy4eFxx0tZ8Ikv0_Oy7y9YJt87w7mxWGIEv0v_vFpFre_gz2vWkFp_c1lqZ0QZ_gG2Uqcy0n5Ndnpobtm2GQyu7614d
-b_C9G_eHqwr_0pVXW2mDUBlV0i2uEQ8-gzIeDy0o8lbzVlnyUYrvX7OIQB-wy3w3O2-qDpEr2hw7pW0DRx-qQdvxVK_TfseVltprudgrpz_dQX-_VFNYUhN
Ft-Tg7xzyzU9wjS_VvseVltprydfrxyFEVtpxtHgMdpfV_uocmO_nF-hwZ9lE0Zl_tN86m1QJeFiulj_tdj_Tl1R_r_ni8E6yGt0E-ZdT-5HV-4m_G7ieP_V
XKVzTSFq1t20Vc0NXfVw_nlWjHy4zJSTgZ-0TShIgrC_FVy1-e5TKDIFxiAZVdGN7lMZk_3urE-_MS2X4BpnOuVX-NxzIVCk_NpvQ_v9KhrBFpTS9Qe_wTwb
dtN3HIBwdrOoy7IuXXlSK_eJO1VXzUj6_GQW_WC3KBy1gDy0r6y0wZS0zHyJWFeDGFq6e7u3KBy1gDy0r6y0wkyAGEc0VlGD6xBoEv3_kKhupr4x-2EQj1_k
g_DeFtvGj_f_GNe3a0atkG1oCo1hG3_mcK40FleDGFq6e7u3y6U_JmAzyVCsKFsj0SYwtuK1-9g_hmIhlpy0WJGSu5_zzG48vw31lu0AJlQlVWFmi-Hf_mBF
3_iNUdx0l_3p6m2F_YKvx0c0w5_qB_hdqV_IFuIFVnxzl_MFuVs_yFxL3w1_qJ-F_fV-ITxu-kWV0Ghfdp-0u8--XVeNV7trS-XVyFM_Jh_-rz7-3M2Z0mY_
llV-ABZ_XHv0yFNLpuAlhtuMV7tri-3hgvy5Nr_zBFXzrqBromiVFvzuQUb9y1TTuFu4VybjiVRbZMzFsnTwUlu0VxO71m800000Wloj1xdw0G0000000000
00000000000000000000000000000000000000000000W
}

