sprite $cloud_api_gateway [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000083PkvCikNKOYe8J7G4pxd-rlt7EtDjKDSIBkuKWI5hAadUIghzfPQJ-ORL2WsyNWF_gMiEZ
Rm-WRmNGpxW9wkvNjW33Rmim_BO0msy1uBS0y5i0-2q0_DCMWAv-PG5unMy1c7uBmDdlII1-6m1-2y3TpmB0Rm7O_VdZjm3mMm3yf_uk7ByD0By5m9y_VWi0
loiW__L_DMO3qD-zrHsm0BGZcUoFtmBm5_v9_bxxZlmuXBO8K_pnrx80Z3z__8CMWFRrvllZh_q_6Qer8EC_QWFG8tId-cjlwxO167yR0FvL0JT0_f4R0F_d
FXjnhr4PVnk0yNzrHVlpNz4tGFphZju0-Ay3_BLnPBi16dyR0FyXDq0zncy3CFxy-Q-m0y3sRmCm_lpvEm1i_pO0_lS9_df-ftO067y70FyrnDyt7_WRVmS0
_y0DW3z__DTo01Z_IHk0-8k_tfAePYm0upzn0n1_RRoaymxGyN_s1g2Bl_6FzLTj-5W0uY_-UpbWv063703YB_xoX5as0F4NVxa038x_jUG047zv1IGNGBa0
oWL0_EL7vd8157-v08Y_N03b0Y3-yWHOBe3YBnS0yHT_yJye5q3v3QWS0E8l_kfJUXD_boR-z8_euNy0gCyg-YT0-7lC1H0_V_pyyVFdpn__lh_lWFE_1sy0
-DiRWFtuYtzk_CK_D_xYVsBy_GISlmrWF_xYdnj_LRQ_ilrrPViht5_X_XheV__1By1q3_3VsG34tnx0Nxu18VuRPwBLnjyYu6y5yBS2-5i0_8zS0Fpht0MW
Ua2XBG07m5H__lNk_XQ0-UVFtmBWB_xYB_xYB_xYB_wV8lvNj3__nV-n-EFdpv-_lptblzuyFQ20dpz-Fm33xm4WVlxu-TFdVuuzVo8zhK_Xx_lE_7tSbx_X
vu-VltiVVn_qv6_y-UFdpv-_kpz_uy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_2q0_lpvMm3ylG7cRmFWRmVWRm7mTmRmzrS0_Eq1_FNs_kBlew_yVGE8lnNW
-v_Z5W3_3tfyTgsm-Di17FyM07yBWBz70VnxYR_y_w_YB_xYB_xY_odYVqVxy-_3_CLV_CLV-o_Xy9l_G_rLaQ__vESVylEl_VWNVjS__FpnywVFVwO-V_5N
zJ6zXRznuKz_ZFyzzY4i_dvq_DNyyOVwg_WRV_x6dx_nvnyKVnL_up_Flm8U__4t_Xln5__O-8j_Rlp5VsIU_pJ_tur_OlpNAmNxYx_2_HNkhsd-rsX_2o3x
dtyU0ps__IlUN_nFJFp5Nwx_ugyDVl4NV_6Nwv_uZul_jQObnx_ugvByvVed_dByYx-kS_tb-1T_UVehrpzv-YV7l_ZBzK-kVtBza-DV_ENub_4NV_5NX_st
RpB-uY_-kZwvlnw_dXb_Z-Vuy-VFlnFzFPyn_lw1nfz_fVdpD_ukWFnj0FpvDt_-0Vmk0Fnj0BP__iQVFt-l06p_De3E-EKlV-Fl-upyRG3y-UFdpz-_0Az4
Vnk0yUVFtpl02lEt0HX__iRV0M3yRG0zq9y_Vr_fTlhR08m___tnlzUuB03ZpxzI_VqAoFZR09e__q1-2y3uyw_kW9_zMm2nuy__skMVwkzhpHN0RmFe0UEl
dGaUow-DTpTzlh_k_frgAh_-5h57-ElwEyKQmg-_WknN0nxzgN-_RouD0UFFVwTh9MS1h4-VmlaLxY_y_8Fv5Uul_Fo3-HNkhsn-LJQ_mld5_vaiW5edfl3f
LpY_mlaLpgzmVeNpwmxdLpY_AfnVuVfAV-QhzE5NkhxYzHMlhuB_JTQ06x_-RG-E1G000006-LlFONUr00000000000000000000000000000004
}

