sprite $vertexai [512x512/16z] {
xDetbKC100F1E-VkysVhpWl1GJCKzgdJyOa0000000000000000000000000000000000000WFFBCUcHqVWPhP_H_1cjdsF7vPnivi_e-BEPFwFviva_-a_c
psR-ZERFPlxeh_zW_kpbrr__3ERNN__ehx_--kkll_xwww-__lhhhx_--kl_tNRpww-__fFvzO_--g_arz__Jt__N_tz__NFPdxzCrbV_qpLZ_ufVlH7V_H7
V_H7V_H7V_H7_r-cF_gZF_gZ_vEzEycI5OV1A3o08vXf_wkjRbAjNXEt4Xdv_dFnci_9oR1bHP7sDGDFxy7fl_v5sMlcjz-WNl_s-V6mU-yczVeNbQ_ftxn9
lVwWT8d-xPlKwmzgbxY_SPDw_KzGt7r_YvVh3wgxxs_oUlsFbVtlrll_-XyFy7Vwwt-ixN-pSlrf_QBpstcz_lhhVwpkV-kll_wV2gR--kllzp_ghx_-Vl-l
_dx_kv__XmNGwJyXjTmE-__wPoatwlnF_pg5sxJpV_th56g3-t-ulu7yF0t-Pa3_B_0t0_h_WRyPSFy7-9i1z_-0lnbm_nVuczNl_-jlz3Vw6_r1z3Vw6_sD
_Xx_wc_xX_xJKc_Vw-_vdVwUt-jl_ux-zk_fx_NFEdJDH61DuAy_M03qnH5_2Vr9rX_mVmH9NntnZz3t-2F--jTFEO7-7w5lySVyzIzg4Ny4VOdhZ_Zv3036
7q7VuTnVV_GCnX_nmFn-_RldlyStilpzJ_tFhVtrX-KPtypYyn_q9-Nwwn_VoQldF-b_ZFRN_zZKt_q__NdqZsx_N9fV_z2_y_n_ld-kpAz_wj_P_pVvzpz-
VcJ_xpd07vmVs_y_mJ_BKkVtJTh_hUFavqfkuVCVxi_xHvtVDyG_4-YFo5cehTl_mVtv_H5pr3dNyESn_VsV_Vwcl_-xtz_qt_zOtzy5WEz_RUJl_A12lzNV
zDt_VgE_eJD38k9oVeDvnj_eR_Gt-XlzZVv-XD_MloZQSGTlG_-wpltR-Vv5fVsVU_WNfVP_x-5VrNh_Omj_l_oZo1x-7rNhNp_fNVxU_wxpqNDu0u3-3Vp8
7xyxhgBzftN-X_DVm5EIDG2-nb__uqlwVo_zdV-E_MdzdNrn_ljyV-U_NqFzdV_Dx__gx_ptJVtrrz_vtrUBl_xEVzTVV_rpjh_xlyt-eJ-9_eduz4_4p_tn
0i1yA_Fhp_oI-Dl_rJ__cVkZ1zZ_kxv_OhvNy-kVc0_pE_-zqpynNr7l_FTkV-07syXpgtoep_qJ-AFv_Tx_hIKp5_6_yidv_KMv0Vwm_sTyzC-z-VM_jkRN
Fw-j-VNFt9jV_zoRN__CJVJrhxCRllv6VwE_qT_eR_Gt-ayvl_NylsaG97k2FyTly-VzMw3S_hzcVzw_MPJJsF_REGJO_bz4-1h_kuhz_uZm9Vvt7U__8C7L
_Rt_nmFr-iz_6-z_wz_V_t7hJmBv-lk_1in_qJ_-8mFc_-jF-hy7-3l_htl-_qthzM-y_pNVN__uHiRxwtzDzjU_O_wx_lhhx_nl_VL7zVgV-eEu_vVKV-tz
V_spsn_nwNyoldx_r1-5-YUhNtZ-kmr0-GR_R9t_ht-YUkwVoVYS_r-5FY2R_TFv_yIFFY0VyQy5q_d_n0y-uCm7_HFgZUH7W7o0_AF-cGnldZu2f0_8VDm_
azaDumU2oTFXprFWcm7-Hd-Zlz7Vw6_qD_eR_Ot-Hd-Zlz7Vw6_0-M6NlyTtgtIGP7F_HpP4_SR-dyx-7LFq3xRsV-Oteb93_p3mx-_VlHRxdPGhTTqVwB__
mJ-bRFI6Nl_-p_tb_k__NFgXpu3xdpm3DYPA7vvZPVyxUGRiJ87vBiFdFv3nX3jSyHym_mLbnDuq8AB-vxBpdpX_x33ZRS3yBwfVPuZ_0PxztlcFd3y6y5TA
-iSFvDt-jPF-4UFzQoZzOxv_BQL_ZFUlhVIF6EzVO-aV-_Zp5J3E_ugT_O_TztyYzlO_zjx_Zstywwpadu_wNw4_M02a0O3xS_u8_V_V1P3O7ou0o3__082t
XT1rnBj_ws3z-UT__1NmTVuNy8VytDy5a3yM_FyhF_DldF_EEoph1G3qiRyBuDaEwrv-5q2olcB-trleouyMmF7PDydrtB02-fJV1S3Jy9_Roky2wC_rAplt
OTH050L144_-6Ik4BIDtyviCg9vz64aNq5U0yGi0lmBSVW4O_mC3mFz_dUzG0SOl0Fm2SFiLOFm2m2-0r-WhmFW5W5y06wX--nMmTThZ5y3MQVChOEEaN-mJ
mDvcUlm2s3ffVWLidRI-03PFbry0Z_T__8jz2lXvh4zv_4x05iB_lA-VvmUmXSgttmdOHENn2s0Z9Va5y7Z_2-WhO2kbno-0BLBc5y0c2R_Ofu3jV_Ru1L3c
Ly3MAjz-0Mp_ylW5iC72_0hOP6Lz0Moqe_a5a7wnJm7Rlpz-0Hp9xsqX6ozy-vs0pNVe-0M0toy1n_t3Lm5-yVFluDW_V0Mm2_2fRYV0c_m4W5y1z0M0Nm3u
VLASlXE0Nm1Ux5E0yGi0lwU5_4TklnDW_0B0Bm0lzYd0-0M0tzj2w3i1-0M0Nm7q1O1V0FXlxDkvbGCn30HHPuRT7lEFTkzx1tgWP06iIk4tkATsMO2_sqoV
0VYYJVWPmE6W7VxOnm9EXwdxyJE0KxwLQl7JyR3-xwIsRpzFm70YzJn-1d38gLIBdzByoTHFdmMSNgWRFmCul5GnViez_lbQwRC0UJ4rucS0mykf73yb-FEf
d3xTzRsV9FcYUloqUFuQ6X_ztu0AyjF2-UjLStmd_wwYFgNF_rCp780gybFo_BynmmNK_6CV1USVyCS3KFtZPm0X__K0_BFo_FnRo1dnPmPGzksdcy-_RlZB
twdwyJC01UUVUW1Kd9y17D7vvnw0uleiu8pEF_y0pBenWF6m_wmRXL_-ary0D4j7lYX0lVBt9Fm9VyAVy6yQ_cCJV_mzy8_3txtzyLVY_9lvuv__-rztV_mL
yqzlwCy3i1K__XeHVoz_ScO0d_fp4t_yhVE2t_lmCu0HyBVo9uUD4RpzdVmfzH7_QVVafzod_zlwa-_ikLqwA080W44Ovj_rBEnD4mTS6PYE_iJpqyvFF3_n
_iJp4yzFF3_r_CJhKyzFl3xv-gZl0kBpIGy000000000000000000000000000000000001m
}

