sprite $fleet_engine [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000000006RlRX8SHP8WZ6vzv_U_xQpdNrqDXa4y3b38uts4o4ebUk2OVpcIf_xb81G7
Q73NmQCAFV0gUCQYYru4UOusUXM4HGhjDH15gRING8wb55y3APXQV0baQ8hnDP30gSQNmFqyvVWAk1ke7ry2jngzG5y1To85y7iBm3y1_U84-4-0Fr00_WFy
9N27KzXV0Vpp1U3F1w00_lq5y9zt-m_-i_rd-9_w1g207rRcwGqWKXF-_xKgOV_KrgM0NrSav1z-0rF0xyjnit_eBaO0lwkc_1llPVdl_kq0dbZlrmJ0_rM_
qE2_b_ftVwI1_rxWlu-kS6S0_3Tub1N0VzD7Jm3yUsRC5-3-hsRAV01-_ciPL06_erxd__w_SEK_V-nVEwm0VbVzarKgNC9i07x_spsn0YxvwCstPXR0joyH
0VYTUM10_cSyx4u01mpE_tjhem2Vc9eHG35_Vm02yCnh6u001732_Fm5yBL3008Gm0hWP7y1261F3i0xW004i2S6u2r0008GW004iFm5y8U701JWIz0FAa00
WU6RLc05SDIsy6zp2U3eTmO1AE2KuGKW00K8G0424C1lgo800GX0008Gm1uOW00480012400_0KW0048WF-v0U0V0V0NW4VajGzuTW3yPoe3k7yXFIBtvgzV
lsND-TypuFC1XDUL__rUTovrENz_006qkzUP_ttpPG9uQe7vPoxTjwun_qW0Sz71_n7-dPO0Xd-0lpc0QUIV-On_Vm0p_0FysNl0_7Bpttrl0CC_SFb_E03-
DonLqd-6Vu0_U0-ONtN-0kZnp_Fd0-WeW7_g0u7z0RZyim4K5C1_Lm01__xBFn_0P0FWdr-lV03pS03llVm5SF3bBm3-_VU0_G5yX3yVGCLJUG-x_7SR0hY3
9E3lye_zOMXEmkLV-d2GW0N_vW1s8nXk_di3s0rmkFohdmqHy7VvDmUmjG7iaPT_Fe0D1C2_EO2zrGJ_2nuHMHV07ksV3s1h0i0lWEM_-LMwZ-Rh_hi2kBG0
b_yZ0Mn30Fm5OFiFt0Ecpna8eFdo5y0UxY-0_QB_vxueeE7lGbp-pG44fkBV7C3jfx7zLmQGz-SlW0Fusm88d99_Sm0r_lmtwI-0_CkSwW3utxuAnmOmC_nd
IWD8-VFF1s03-Fr8B47j3m7y0qjmR03yPxe32DJFl_WMm0OGcByt0Fw1-Oi3kFLq_6TU7K1wT-MV3u1_OFhY04v_0mWCVqS0rxtGW3__Isy1hdkn_EF3t_TC
fSu03lQVoGOmmxzs--yFuFt-_6VQDe3f3k29oUiUh7kGVtxoV01THlmB0_ZzT0Vun_bdomBW7xxy0m7q-lCF1724F__-0AOvWARkym7O02gppmUGz-VV7q2_
VnGfF_Kn_jx-ym7qNmdyzqn_R__vEm3-WQ7vym_op_3dNtChn9y__oJ_Z1y0-BzpBVZ_HXlmvz_tzlzh9c_rv_yxwsd-_9V_5KVro7y1zMn__dkIF__bpvy_
_uicuS-Vl_sVFt_-_FcF___Xpv-____ddxkp-3FMESwV_yoU_laFd__QdPcN-lFt-RyjzlVvR_xy-VFVj3z_V__9dx-__zuCFt_F_sZqvxy1VlxDZxtq_Ayx
Zo_xxmVy-U_Ppt_blrtFV_Ryxtm0H_lpNy__vtyRF__-0FRex_-n0UpUgR_Jxiz_N_dzZ_pp0MHAzVsl-T5_qS-5oZ-_hXVez_Wl_uf_Stp_-ui2s0tyUnb_
6y1L__1kBJ__mFYL_lmtu5_UQF_yfsm0-KJx_VbFWV-XRm1pzFO__Elvp_0_E81vSlldFox_y95ljDb_dlNdFyty_0C1dEtFV_0_VfpfF_N-De1-Vlxv3-sy
vKKD_rm0Bl-UJli3c29_6y3KylFF170qlpU0gUBddzy0vWp-l7yurVu0flBojm5C4t_UtmOmt-BdVq40eJ7vLsm0qyIVlw9i03C7y1VxzmUGFpl_C45-G9V_
Ret_J04__-O0-iyRvG_uXo7c2VqfM4m1L3R7Fn_09C-7VtEB4oIPuT_sgYU6Caty_VwD0KpWBCdvblzVfPd0ARBhA83yu_mxXbl-Dt-Zn_p1KR2A0hW2QkOv
VluFVg_Z_73qymiWVpoqXFmNlm3Uoi-_Fm3y_GEybP__-mDeM3q17C3_7V_PpnIGltRuzmJGj7G2s3o_ox-guh2-oxzkZfm-_ixdDORu-RTEaj37tpnBZtx_
fldDOGBwBl_gQGBwBl_kSGBw-Ai7AiFddvyee8-_UgG0FlxkeThm-UUd2jZZBnyhODz_ePm-rmtq-0EJ9LwNHJ9RuE2V7mw_wIoG-MoG1hGwHhGx2i3Iz7zR
5du1u3zpKFoZTFncnMzQ_6VDYtyCZD_8-0rj9Onj7OuP7FyO7Vy1inymF7u1u1S0VW7CISCB0BzbCBU5m6yf1d_NOlHFB831Bm3y0ZXsL04CVW6SFAK01hyj
GE6lEImGVaiqP_9R9VpMQGxcjrI3Fx1QWPTJLxG09lrAod8MGFvLT8sYWDf7rG_-I01J-NI2mHyBOEe-ZpRuem5C_imVr5V05ISS_8y4CDDmvpdFyGjWicUi
qnV0JF9yfTyhfu3yVZFJmY-02RPMgQ-0cT1v0YzH087rdUH1FqLpEBy0PYhvrv7SdL_ExxXtqVlr7NUk_Glu7VS9l4FVSPV6iVmAyCul0FeAeAy0-WgWhm3y
2g2l0FWAeAy0-XAWhm3u4g2l0FWIeAy0-1g0Bm7u4lX7Ut1G00000G4iWlvj_IN0RQk9E00000000000000000000000000000000000000000000000dD4
}

