sprite $cloud_ops [512x512/16z] {
xCSX0a1G00Mm-5xxzpyjWAh2rZPU0W00000000000DectUHoj1rVHDEcY_JEtDvvgDUEwppqA_uCQ4hu_a_xLztfSvATJSEGXNLxcHnRYwHesP4m8uEerGaW
fjBl0h1M9EB1Da3mh2K8iuXV0igO083WfS0o20882a7v47W3i8Y1GF054WCf-faBalZTb99mW6Q0fI6S11q1IaRA_eOX4401cGZob6zM1S89kfDdmgH-tXl7
_WH0lKq0s42AG58_dK2UzRCudCAV28XzEMSv4Fl-YqA1pmHd6P0r_dmk5FkMaq0u-NnAGoR-H41AVsQ1hFNvhme7xWQE4f3IdpOWoPy8IExdhK3wFZ_0sDyS
RAsV0Nk_vGt0vlR3vcr_mERwm-xsm-Rwm-OFVM5p_G5vxBkM141cVin_-GCaI2ABGHTphtHy_Was289806Ypts_FPh8v3Z87d7Tunue5AwzwtmK0QNJfAG70
shzdTH3vBiI-a0B08ngOaQd_LK104iaGwFyVqlUxxhObqF-a032RyFrlQapI-0iotsyc6B-Hx3T_LBfC_oHplq2-rtFX-1F9VlzdPA1L_uC20DXaYUmA_PFe
N-8TMRl-zGDW6_iJTEkVHFzlc1_4ZMRzauyyzazGvg1P_oJP_tyyEkx73s3qWy--z_53VjgyymSVVllZCseXya4CqAT_ifJ-V0tJg7-ogNxMelJfdsoe7q2j
Iw_-yTDgCry-XEpIFobx6Fj_0atw9ykjVkJ05FJed-nJ_55F0Jtw_GCWfV_L01YlKxOSIFA_DY-Exr2kMDet6JgYGRzt0DXzuE4rV0twhGF0RERt6q0qw9yy
EVlRx9j7m7Y7SiF9_eVj43Rezmm06BthSHx3iq6_OG0SFja_9gulL82f_qa1WEMIVtBJM8qEdZRv2-nRV5kDf-c7K-tt7yUHxB_cFCmxHZBwJvV7lZl6ClhB
gFFJZsRqmoVxzUCP_IuB_fuZckp_dCDXOAF_hlGt6Lao-by7Jz4_I180IN8d_Sd-2Vy4287-PB-b_ma8HlyFU8Z-oOkF9z4F4_qVeuUEBnAZNx-DrxZK_mIC
_jRgZtBpFzeALlH_Zf_-yVMrokY7GB-V_na2qN_mBT2fNnm01Apr-wS_MAlwdu3H_mPbwd_m1JRMV_Zfr_idTjLV4EZtzqy0M-gdZNw2T_cVO3FzSvI6WtwG
7BtmTR29_fuXQwr25lx9v-iVdw3N3_hu1v-jls_aZhxaT_4_UQp-pi53zG2w-GVuIFtZDIJw0Thv9u7dwMyUmRRIR-T_yYpzpKE89ll6_l4W_Jyr3oAaUsZf
_K-Uehzz68zh5XxT_ECH-dzg7qTqw3VtFrbV_mKZsTJs-_kF_actVbBZF_gRQDOlyH_zl60mqL3xDVwtrpywwT9FKkG_-djfgVvK-O_-TZgAFsK1aBc_cxVJ
_oHr_lVM_p6ke27vPVxpu6SM0AJEV_JR1G0X3O3ezme0abB_qM_b7_mAqM_lVpJe5mH0z3i5W73qe_ydE_-WEW0srbzZc0K0f0AYtom0e5VWep_-nHAYtoi0
xh1Wep_-rHwYtoe00849L_tnpudUFwB_KYxTMwZbqa3Sgp_--Ltwhcml_HzM_lbzMY-C1BRGNqF7fVh9vikIwuz_y2tQhmhHh_GFy3qkk2ZWqVfh60K0t-S2
2GUWq1__O0ENI13eZt-2BLpY0D5_yLs3NLpZ04_KNyCc0DW2M5KNARXGV_opX_dJBZ9mbVxu1rlusftPdUCN_sm0Nxgv-fte_p3nts7_-5HQ_Pdeh-7XdmtK
rT1Ulx__SP5_r9Bwup_wuv_WcoojF_xVv5XPV_mBQh-l_lW_-0xWslhZV-liZtz__SDLV_oVY-kFVoJxlqdyr-hwuzyp-VtrnpyG_U-ph7uo-ZimyBzhziT_
El_utrP__6VkZ_za_xtyT9z-HBy1w_bdz3UoNFd78_J7FwBVWTNIVrtz2O3tzOCxwu__wE_d5lr7zBkmKlUti_xuH_HVmJAp_n7zLx1C-O_-QrZauV_I6zvO
V-sK_ieeNuPDqbzsb_t4FnhkCVejply4vEa_el_EVS3gtlGVqU_K5edrZ-Z_7E7G75B_8_g_X6vezjOV_sZm7_tjoCQ6hxFkqOO9W8vJdg9VWMPim9T1z4jm
tV0h-ZLyUExtYEWNmUl71doPw9VnuRZRRnxyT81-cxr7lmwIruuDej_SFvl7Hk-VqVyzfXshetwGDtuwE34ww0_HhmCz0L2D_lEvXzZ_nEMOv-YN-vzSCJAq
yH_zd-lf7nY-oX7zGi3t8g0cfkK_-bzFpuPXQV4V_Nh_axv1uQj0u3_wFy_FfY6XRVv7_-T-tX-FwFS63UNviVwZF_vhBTpq2De_eVwKVu7_w1SWq2Dv_DVg
p_nlrL_4Vzf_vm18_uUqV_6V_B-8-F_fKVxJ_s7hrP_uP_od_y_gluJuZt-Q-OUx__YF__H_yR_-Ufh_zVhxz--djlQV_AVkvyL_yZ_-3SOp_lluoQ3VjUp_
ylu__kDVFvvv_ej_r_a_tt-GwVzV-FdnN_7l_03mazjqnyNMVywr2q2jdlzuqWN7F_WYnzt-iPL_hDPESUlV_ut_zHy0oaW_xUg_zOmL_tXy_cFX2U33Bl_x
umjk_k5qZg7RpIBvx-oVhtAe_VjthAoNyKr__zKKlqlcilvfDvYqzUz__4Vv-OVCV_p_PEYV1ls_OmDG9kblr_x3D6Rz2q2z3cYvcBhS6s0u582Ibt-HA_y6
W0R-I-3VOpDD-Fa_wtKMr4_MWlKVRjFYv7R_S6p_z6kM-WPmejUlR_ySvd_OJG2Jf-ilMFYdtyGukLD_qT0_zl9VD-g7et-FbrPOAW1Ablwmy5-NkpaL7U3a
Blq5mpuAgxwr98wR0g1qwSyD_4idW8bAlt_vXykofTH_wUqNalz60L02_O8R5AtK7S_pNsBzW6FvfyzxAta0bC2-uFua_k6u0aJKc-ZqGt9xDF9lNW0c0ll2
kyDc_b7lex1VbFW_w3F_G_9yXEhWGlaJU7R_5FnewHZrXq1rG7fE_rZUFwkF1lUYyg-VfU7g7oN3Nx-JVwYgf1vjQsFX28RjosG1_Qx-BvMZofFZaVefc6OW
-E7f0CYbo__4ylbbuf_-fgDt-KzF073YE7kUWjab_ftJV-C2aFIduEUB9ajww_UidV3B_nEFgW24x6xEvbTq_XE0ltz0aFw2ykmz0KmULFrvEkuif752qm0m
lvM3ZlaFPG60gtxJkdaefXZJ0F3NRrYSZUx4Fm0WzGyl_ma0Gfl-yIy80DzxeElKV8WB0CpqQyGywuy1ts53_GLVCVBnGzqDeBvyYFPF4xsPER1o081o_Qeo
oIKA0DSj_gIpbf9b8vUT0g2_SaBWNrjfmFSmi6zT_b7U_eiqYG3_gzODZ_3FEWMPv9VzMYVMhGRMgm3WClvBwHyt1G0CQhzfeWXYtC0_3Lxu69T_cPP3d53w
203V1zBqzvy0YXturtxz864D_s07K2U_l_vJ7klAj1970C4MvFsOl_zY4zhSjo-HzGwGtfvv2M0N1ide-6U2RHZONppz9ze0xmEIUTz_T50M1K1V0K1useV1
LEnQ08gjGD3rcUV6JVvnl_-9btm2OW_x5e098AZxfWE34lXt3m12yFspQMTakf-rVjm1tXg44mC9xWMWm6l0bwwA8FpqOxd-5sx-9_Wt4IJPexv_I0v1k1aL
0F1wy2VNuFNWy7W8y-yz-4H0brrb_SCFzCT_E9osDKq5SDfMrF-mXcJ_Rno21jnl0ihSxvF-TP3oRyz00T7lUn6P-_yFEFW_xdW32_0Hm3Fp_2-3oNwO-CSz
0G0k3tmxR_-zsi750QoEbD2RmB5r07XNNVy2K0SN1WPZtiLf-0cUltx_zFS_h27wrVwz2a0Hp-tynfzfcVcg0Qju11wO_UDV-SdqS1pSzpZoiCP_V8v0lqm2
jWk0T-nFfCdctv4yPUeVNyTDVpNCXXjq0Hts9u9KKoNXDW609liJ0_qj1b1xp05zzYSA_Vu5OB9kylyqletUlsS1y0-0eplv9mBzWl6l5XPDVaK0WBL10DII
Cxya0ihRFwi7BDRsjo1CV_yZErVwmdiqOR87_j7G83MmYdsEDfJLt__CtfDOu4tVwCJaE5oNhJa1RAD_8XXPdqCl_LU4mQD4-YSM1-0ORSvBW4tqVznCdN-W
XC3ed1OGfb_uV8mBq5T__oDR0I_xat491kbV1Qy0A4FxDIv2clx-5M02Yi2BN_RsOw2_11z7ktO2rQ2_EG2EaYCOHSVD8sjYvHzLbG2OU6pZCYx5ulnp-1xK
1TpyYzm_3Lq0eEx1-gW-jBe_wqN61lxB_TZ--yuH6aCO07KNHtjDxGSWm6y0S0wjjt_KVQnoQZ-95tEUg3SO0dxFeGH0ozNYathlwPzrA-o803qW0G2S_zfx
6KF27BrxEI0F07-618-nWxm2HF-4v5ctmzi28FvHbG1musEeG5K2m8wXeom0EwX5YVzY2z4ly9y0iFMV060jIFmd0EB_O0_HlwR_0flOsdy20AmLYVzY5sSj
IFmNsoW1yUyR0CZY_uh-2zj7mDZQVx4FxEq_0S1QZlW_i7C4n7-TxEIejOZ_WlItxkBV3YXtseX_FwoEK8v_FO1ioutuTmJivbp8V_mNL9jlnByd46sy5Fyx
1G1MyH__1SdMU_5lombUGlb2CFf_u-0rmFLsGSQ_O2i-4APh7l7_PxX9170I_yfzkIqxtVYNRSWBkjJz-DTNW8bRT4U_DW00tYOVZF_FeG2ZpQ_Z_vwpEQ1D
_FX_0OE3MMHRoqV_lITstxwFSFmBAe2w471YxZyLO0AoyJq6wEY_re9gW7UZW0JuCl7_oKEJ5e3WgoaFOBgF_pR0km687ryU6g8q-jiZe1_yu3_6l_4Su4_q
Nru14W2rAWa0WVu4GFpRSY81y6ZzAG7H_sE01C2J_QS4xAq_0R2v_am2c_lFQk3c-hCSkBd-j07Hdm3OM7ycWStrfmRihZ-FWflhJmHihZ-h0PlhJnkmkVuy
2kokFpLWS_kf0NlhJmseRUsd1e1LLNlgpzCWM9CTxQS6r1_Op7uY06_j45xXIV8dPl9J1FIxaxh9JmJeDwX-hFiy3Q2-Z8Vvl23stuysWA0xPrr8841JGA9s
9Qq0PF939dqVqWlWh6r96QWR2IUmURiNWBHxQGT8gCppA4C2WDJyD8K0sm4MQlN2GHAPwpCXl34bu2av7pWhE0X-2XwzdXTcSWFad_zjBKu88OGGGWWXX112
22644C9_0m
}

