sprite $cloud_tpu [512x512/16z] {
xTr7cjim58J13OpcplS_hNCE-AYXH89uLLjd_sfGQKRlvmG00000000000000000000000000000000000000000z1400000000000000000000000000000
021zW2okzI7QslfA000000000000000000000038NzRwmyVOfjOBq7-alnBPhjFS0Cn_hjRwvpnk5VQ_HtfTyZi0z4V_9SYll_xwU_HtVN-Q_Tl-BF9__PQa
jt-l-EXl-_ghhx_y-ikll_pHt_hrb_-q_ZJzXynVVy_wjHD4V_C_hJ_wirNhZ_xeZ_v4_ttCFo-clyE_Qd_X--pzNUxRQsIY_Ki_bkSwx_mdirrovxt-wpzs
mlJdxk-H_k7wy_VNV-o4-lfxfc-iep_wep_wep_we_yAzCz8FqB_FK_9fVh-xJzFUCD0nVxE_tmt__xPnlhgvpy7FfXf9BbBVue__gDkV_JdLay2zIlvw8V5
ze_pdsBzqH_zqH_zqVyO_LEyl_thht-gzxV_fhyBmEpzqH_zqH_zgTSV_T4V_TdcTR_t_xe1DFjt0EYll_3wFrD7_xAy1o1zTlfdqzy5u3xzqP_Kxe_-Cz2_
LUwlVpwvOt_zd_g1ezNxk_xdtFvCz_Ik_Xu0dD8V_PdrfRtg_Jq3c8dxEm3wdhTkhdh-wv_3Fo-xLE_l3c0gzzVV_lNlBqIf_kW_fdyRUVmE_KBzxN-GVs__
FApZgy3G7_slugF0rkkF_PDjXrQjlmEW_IAhxfyz__6bptyN_vJlxzrV-hldhx_y-ikll_pPQSd-yhUzzF-Lmp-LNl-Nt_bl_cu0ya_KdwQ_-PVjpuafz3V_
mphwLoI__lgtNfd-wS-1opyfkN_S_KD_jZF5w_z7sV-xZlCV_T4V_UzF_mlk_sF_w3y5_PS-__MF_Pl_CltLpuFqDtxzvTTVVltLLrR-FzpbyR_yUPZ-rg-_
-iVrIyYll_pwgv-tcRU__FOlVu_-BsBz-giV_NSn_dEV_v5__S__uwq7jVxE_ZnBqz-bVwB-ykTijVjRl_w-mLVqD_vA_Ltwn_It_ihzVNFFdDHVV_lNFnFI
t_uhzzS_jVlRVtzvSlqpixRdkOfUZ-l_g3_k_w7_cFxj7lGVid_qH__Tz6ytSwW_ze_-wAz_kokV_sl_PVlhhpyftf_Q_Md5-rFyyH_5vq_n-LDy_XJFpu7y
P07okn5VNHy00000000000000000000005eVeYqkVO2ihoy8000000000000000000000000000000000000000000000000000000000000000000000000
W8y
}

