sprite $quantum_engine [512x512/16z] {
xTotbKCn34N1NLbcxBzRjV3TEnB0kJdjv9Xh9KcI94cI94cI94cI94cI94cI94cI94cI94cI94cI9Ec-eyoccLt5N_p5N_p5N_p5N_p5N_nxnb_ynL_ynL_y
nL_ynL_ynRzd_CLV_CLV_CLV_CLV_CLV_Bl6N_p5N_p5N_p5N_p5N_phzphRStFXJVExRg-sl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_WNYR_uYx_uYx_u
Yx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uruc_-8j_qVzhuS-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvt_VtfD_eB6zulup
GlN3c_Bdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
V_xy-VFdFsDFvM_-Ct_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VF__xzlYR_ykVFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_pN_aNcFzS8FE_-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-HUO_nji7rK-yv_vy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-U_lyJh-GV1-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_yQyLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_FalqzZHtDfxR2zqLV4NV_4N
V_4NV_4NV_4N_vxn5t_n5t_n5t_n5t_n5t_nxnb_yHT_yHT_yHT_yHT_yHV_dl4NV_4NV_4NV_4NV_4Fndzys_-z5g8aIP8aIP8aIP8aIP8aIP8aIP8aIP8a
IP8aIP8aIPAa3m
}

