sprite $genomics [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000WDcx4oHNTII0eWx4anIZzh_QdbizVB_uo6L0AC_Pmaqe5m6fPQIkHIMz8H3V2AXl
0jHVV0BOKcS2NFm6GFuP9o3dhdq9UnenGVok_HnR6ZD3_Axz46bOkzwl_5lj8l9tSrpyNViOh_I9EIx-hdsAz9avBlvkRrUIFysIlsjNaB-R9N_Nnf6c7u0y
PN_vqopvktOb_TDi_KkjbSlofrdoT_LlkAn_cYb_lm4ma7-X_lq6m5NzqrJv-ms0qexObkkVwt468AtMlzy0A9VqtoxAFzwVA_gdsVfdtRk1_ElqxpS0Il3-
FBn__c5_Jk-VPkkVwtyXU7-2zoTuVqBt9-ll8K2y_lZzJtjq__Apvpzu_Yk__l87wbyFahzjq_VVJxZyvU-cxzy-xK_4z_zwVjeQ_Ti9_UNlvky_StxVVppw
-p_vsxvM_rAlvFlFhSqr07iRGqehBO1eLp80--Ft_x2bpzd_PV_NDSxBpypzkzFoiysSlpkjFdFdxsBcj_-xAq7hs__VdLEV-VDtzySt06qr1C_FAtX-qY6l
jYg2N_n4hyyUlJxYSycB7W00000000000020zxR5DmFYHtc37z_kuSDzoniCW8i_oWHWTuyTOdPtsI6O1gd_JecvkrFzBkZkNlMxcBkxvU-2v4-x_Ez5ERn7
_j-8UNQF_DtY-JlvVsF1ZStwvm6np-xKlzwlwFzLppj3_elv3S2Urna0_SVb1_Ql9-JN_vWwXRFx9_cdlW6Kc_hhd-iSlf5V_vA7bVa787s1ot_o_ZLsV_th
7VtrptKQiVlhNzjRsvdzzI-p3q3w1lbdxj_5xgz_ZTrV_wh_Prp_-fV7zs_w-_sll___FV_n_4z_p_-3zDU_jC3zlVzHsgdzN_hFVVa7VVzBV-__UVztRu7x
U_-__PdjfFm6mFTVll-RFt_pw_-u1V9Vy_sl0TXZVF-_jRTy0cp_oqFO_xF9R_-N_WULTV9tyezOBd_Rv1-nJFtER_ynzd-_pMy2Mjpz_oQW1Jl_WmNQTy7p
4xq-mVCJ_OS_qIz-ejV7WKz6G7nklki3000fjO3mA4vy8w1-h0dW5VaBNBoEeRu9aDy0o1zf07W5NSI23t9uXLx5XE-nvGyn05Z8WOKyw8-5VBmMtSUBXRpe
ZuNyw8y3UT0V_Obq82lwep_wep_wepzRwXpAwF9VwWQ0_hZ_u_SV-gC_-gC_-gC_GVEZF_eJE3_w4p4_-cF_0_Q_43W_-XCyFy7p4p0_zh_Z_0US_uBpdmYU
d-ZvYLmVvp_Z_7V2rqVyl-EcxW00GEfQBEmUnuXl13oACm7gcm0BUjUU0BoGWnSorOyp0BbhhP46hT6-at_KGl5Dm9R6hLA_at_CAlbDG9IJUFAVaN_4Elcx
8l-0XV9t-X-tBPI_a_-u1VFdtM__1GTWpuUv_B_UlzwkvEDyWNlSi_CRW7H1_tg__9x-vn_7lDVxbNpJ03YGfzG9v9lwwrzdKF8z0w1_MRI_N__T_Fbh7kRo
Fsp-_2NVCG3wrngul_vr5lc6_lhN4FtrJxFdBzVtrxy-l7zfFw1_VNh_t3wdVzNVzQ-_l_zBzzVVxt_zjxZ__-ll-P_-dl_h_rxi_lgtoVlx3l3a_ctnzp_q
z_wV_lCFWFo_Sth_LcE__-_xd-Vrtzi5VFyLvFi_t_-MUhiByki_iJFw6u1NUupO-Ur_QVBR_oN_Eukl_-haVszV_FBlv7zlzVoT_Eyb-xzZrBV_lqIlx_oF
yFMT__EZ-0QWnMG0v3S1hxOeeb_yHA_F7hq-udD7V00000000000003m1d_3k_inYT_jRLduTe_8d-xoYhovWPKsDcDt3tPtsI5cTvyTWlFlxbI_Ap5tzwhV
1TtTBNytS_vkQojmXa20erkS8UBi7cS83UIFyXV06MBxN6UtoTyjU7OdUvvh0BRB-bT63v6U_-pkVIm_UQt-QIW_9G-PFdyQoo__QltJYVdrpslqhvtyOwRF
dyxCh_y-VV_jS7xokEdxfwFvAS7wowz__H7zo-pvqz7yv4yyjB_y-fSQcFwvHgP_ZKX_0w2_0T3V0EZVwizu_fCz_tigptyz1D2_wTwjsF_uwn-KsVflL_Hl
fNRwntl_hmy0w_NVMj01yFxl-FSVv35hVF_J1u2oKl_nxp_98zRw_hkESGDeq_TlevYjVxksFvFbRtFcrz_-B_k_hd5jVlQvyhVPyhi5_7h00jXNEua1YBp_
smJyYhp_tmIqMzom-PM1-7CDmDw-XBlZTz7l_GJFJ_G__KI_-8bU7_MDWFX8tph-sXuSo000000CyhU-nrTz000000000000000000000000000000000000
00G
}

