sprite $retail_api [512x512/16z] {
xTt9Ugmu383HEn2RdT__QNkeJSyDKH4-8Pspxy7vRTqg2DprTG00000000000000000000000000000000000020_MshcBaVK_yl6Xu7zVzihXewRVgnNwdV
E1p5rce3T5hntA_MhlzUQgqsmFREWkNVHxUFmwR_N-bVOQbnK_yAVzB5wV-ybHe0-Xi0-kkl__lqJqv__UTk0pZ_-kjl0-Yll_usWFxw6tLNcFeR0Fhx1AY_
0Q2_0Q2_3Q2_Yy3wsm3w-pqG_TCODi0L_Jq9fdyV2Iu2wv_zwG7z3G3zQvhx2VhNfR_-X_I_bm6Wlm6Wlm4mZbNjRm2CimhsDm369vJhRm2CJz7_3GNwZrhz
NGGU-kVwrG7zwohGVoJjxowG_ldf_-x9QVWLKFywCqJ_2tvciyy0q7yh-nYv_l6Fp5kB0Q3_BFT5Gl_FwFdAXAd_yR-__AC0-k__PxGU0FhlnIy2wr_qMhB-
9tL-QSxI__I_p03uUSwZ-c-j---H-iSUrB_vQtD3-Oyzflyyzoyp0BQVd_AK_YV_PGR0pvBzTo-J3lK_Lgg_0V2pPFzzrt_g__yy2b2rlvU95-ql_sK3Jlz7
q__j_0Q0_i-b_vlv3G3zdqp_j_8R02NxRstwB_tZnz_xO0hq3-VVMl-j0FglPG0Kw1_Extqm-bUWVoY_LuBgNuF-aVm6GCd-er__fN_W-1i01VhB_wA__eTA
zfV_HN_zZymo_UMFFmgW_rm5wHyu_Zu1bke_0xVzoz0_SFmDW0BzvN_HN_z39VlB_wA__eTAzfV_fNF_iP-X_opQN_x0em05-WVo6m3w-wjXI_MVyhyqwk_u
HyTWWVxo_mVzzJ-KlR_ySVNxlttRtm38tj_nZolG_uRy1e3-HHNeVtT-5u6Vqd_gVycZ04_jVqD-dm3pzjzYt_sc_d-Ng7-6usy09EYV8By1eBy1aA3_dVaD
0FqDW6y9-YV8Rm3KwZ_NEGR0ZmJz4nn_5u5JzbzNN_hnA42I_fcElm5mV_yK-JqAeBzhG0dw9yZlAw3-1a22_Wdo6m09-YUuxMy0tD0_mV4t0FBrJ_2uhul0
D_HFSFmDW6pzu_dHFy15u0Jz4-JtA42A_ZF1RNzV0M_gV__nrtzFq3_JRNy3847_1CVV04ZGFq5-0q1_0-26_cdo6m19-izx-Xi0IVjVa9_dzfy9lliP07Vs
l_xuisNld_2slxj02VedEFuU1RYXVyRylWBgxnFWFVtJvpS0xky_R-vl0EJgdo2_0N1F_not_Gs01Fqp7NylXBgfVzBy1a2T_YJkdoQ_Yy199EZlKG3vVGNC
OVFTxwOpvFXdO038Rm3eRm38Rm0K_l1d03Z-1e3-1e3y1a0y_rXSTY7DyNSNI7wF0XJiprxGEWVzQPmV_P6_4FstzJau_letpe_--lVDp-ZT7_ahq7-i41n_
_HldH_y7qrz--USAmF5dTioFuu_ZJzlyo4_h_4pvb-Elllxoow--_khBhxx-uiillVuB-V7w9nn_77ySV_J7knzpmF57VlH7Vdptn_57Vtptn_57VlHdTisF
uy_ecX_7dwrjVXn_skR7yQVSNwA6uu_V-y3nHt_anv_-EFuu_hZnY_5Fs_pepsoR7ySV-VNttL__biSV_VMNNtzc-_vipVlJlJ_D-zEyFytxqxi_i-y6m01W
zkvFi_xu0m0300C0_LcTxEYFcq2u2up-B1j0VXj0Vnj0Vnj0Vgy2qDy4aDyEaDy6aByi-Rjh_vkVEFo8dnu0000000000000ZB-Q9LOnrWcCV_THOXLZ7H7_
lnLOnNzlPBPnQ3r0Q1NCSSfABhOAnbaV9LOnLe3wBpLMiQq0-L-AhKBz2Z-ww2hahx01FcAhOCJKMCKcVrIDLGpvesgiOieVrNSLyhzakd8PftzOwrN8FpvA
h6B87rLZ5KF-gDxzzH-jLo7_I7JPDqx_kDQha7yKEFxwlwFrAkGVJxpof_zrjXAh6Ff7jLw5_AFtAlGVFLUXl_xoww-_LQIXVvp-KILMeR_-ykkVd_xwwx_f
_y3-Lg6_LUXl5VfRXVvnKt_V__JNNt_NV_NNNt_zzNV_Nt_zvVVxd_hhhx_dFxm8y4kUc_Rybm6Wl_vMuVqFLk7zB_e_oJRUv_rF1i3It_iVkwv2_zwhi05Q
hqB_rkz_jm5gNCjUCJR0Lc8L7ol61cYz2XkWzIfiWDQhi05Qhy86QBqA6w3pAco0MgkWo0zE_h0QFxVuh_ioJkgy2ZkWyohiWEgheCYFJVoBVtXDLs4NMCLN
0G0000000000000000000000000000000000001-1G
}

