sprite $cloud_run_for_anthos [512x512/16z] {
xTq7qgiw30RG3FPWJNtxN-thlUKFO2okpjd0BH-IBLFotQy00000000000000000000000000000000000000000003Y6mK00030YBe00DWh8IfZ1000Z0g8
MZ3x0G1W1ZJx0G00z6yHKHbxwKCWeWu0m0n8LCOe_I000IKQ0CeV0EW1EFgf1HW1WDdFRG07_m1GTea0ocuICGEQ_Qe-7ExW7m1WZpg0YYy8c_q0FZWk180z
Fuv_sol-3BCV063p02ClpiSNoQ5z0m0s4PW1YRSEtK440C0C23qFeZBsqeT0H1q0c04n0p9jfzu3RJht34X0rGP0d0201TeCQFO3000SpaO-z7At0L2K002u
qsJsCmEQ_T2C0ULVTWa19bN_7ja1Dtqj2hCV003iin1l7HpyCFi1GELRnzY6SAu1ZAiHRorgsMYwk7O0rO-B2a6D1Cn-SHYg7oft5l2hq9KRWFYnzJlQ0FfP
77pWTiIb5gq0x4c-4BNcGG1on0_xluWYS04O58fl0Rbt1YIoAVvEeRjtH_8V-CmljWsdAN-mJG7Ih1Szxg2f0W00Phy7p2kOfmSE_ZdHIW40ir_9DuxDVcP0
inzcFm00x0G1t_23Vf78my7_xV6x01orHmu2NNMdvM6Z2_l54lprMFd_6-S0xPorJrd4SRHhB8n_z3Y4Tg43yI-u07vh5hJBBNp4hdyq0zAcUCQteZqBscOP
2_zJuqjeK-M-8qcRRLrBtUCDsWqYATezycu2fUy24FzyroIvTWemyPqm8X7QxVP8WxR0AB874F_y2-34Cw6qLTQLxeYJn6yJA7udWVtXNkqmbuhYjr2C9vD-
Ugf_Nb6Al-woJ-dqAR3iZ_VApe2bIv_QwPi1fP-Kykzt5sYz1b2lz9q3_4dfna_jz95-FkBlaPxujuVNFxqbiUIfJ9pwY3-hGFuhZ-rhnwy1Y7_xYxktWBvQ
FfUR_ih_8xr4_lkVoN-XJxljZCuj_YzwBRe0yC0ltlPOJ_xzzlpdVjZnz1x0x9Uo_YdzdZUlbjJhRw8ovTzwZW_xz5ur__vNsyCMW1x_H7kEGFvhlkycVmr0
_DlVjB-R_4hvvLzvfJsn_ljfSPByBG3YVzNAN_xRttnsiMWdshyFIEwPD9J_VJPNG2gdxydf0N-b_liRDW8vywTw_lZammMszzhNzNlLUX-mhRBf0LdRF_8_
P_iIbq3Y_AcUF_8_wlLLhe3K-TDZdaVCVrGlVwhdZ_ndlkd_yfnG_lofdZ_odwRNl0BwKgqq6m5DUBcnaloFKFzp5fBNpIUoA7-_-9JUl0VqKFy9V8i3uFQP
-_D7_Pi1Y-MF-aV-o1_vK_ls6nSS_h-UM_uKRV_87_dJbjYIv4_TyaV-vFcGZ_p72hNhdzgdVnGlV-hcZ_mflloJw0LVvMy2l3b_6fpgwG1WZG3WrP8302pk
0000W1kwR6qAdFcXk_V5k6PT00000030lRujArfXG2z-lvTM502m5P_vQG00W86mwhX7MmO00000000000000000000000000000000000000000003W1m
}

