sprite $binary_authorization [512x512/16z] {
xC410G00102W2Vw_zGAeeWy00000000000000000000000000000042oHyT40C1048JQxyw_s-Z8B5ZWRc7wq__so__w_Ukl_kltRp_whz-_Vl_sU__w_Ult
Rz-__jI_Vl_w_Tlthz-__ig_VV_w_Ulthz-_VV_w0__w_Tlthz-_Vl_w_UiF_Dlthz-_Vl_w_Ulthp_mhz-_Vl_w_UltRz-__i2_Vl_w_Ulthz-_Vl_w_Ult
hz-_V__w_Ulthz-_Vl_w__xNxr-_V_t-zVltxr-_V_t-zVlNl_I__lA__wN_zQV_zQV_zVlN7_ttF__wg__w_UkF_ljVzb-_V_t-zKV__S-_Vl_w_Ull_Flt
hz-__kY___dNxz-_V_t-zMV-_JzsxXWBSY860cXWFxSotV-sX4G0wv57qzQlA_mgzHXsD_dZv-_wypT__lXd-EFdR_xyyG_rvv_ypP-_-VF7FyWVFt_pvu-V
Ft_--6Vvyq_-vi_V_AVvu-Tl_lpny-VF7pz__lpny-VF7_-R_VadV_FdR_xypP-_-VFdpny_V_xyyM_eB_obW9-_-VCtV_xcpz_y-VFdxzSVV_Fdx-EVF_wt
-_Fdppysy1Vp5_CNyyTl_eNXlpy_V_F7R_xypT_vny_VzNV-pT_ypP-_-VCtV_pcpz_y-Rzl_lpDt_pnytVz-Pk_vz_ypT_y-Pi__-Rvo_7lAK0p_zBmNzT3
oUxmZmtz-STN_MEzr9z_lD2VVnRxntgbF_-OxCy__dVMQ7_-qU3F_wvRFN-iqVxyOmD__i_nnnhjppysykTVpnzhj3__sCYVVpr_hD7-_ECz_lpZHjPR_Fd7
hVJvy--VVyHwXp__k9dP_lpN6_pvn-tCzkU_zlVd7nzajZ__jRi___Wei_tvhxtz-SU7sTgVVtoQzQ0__-Fd_MDZV_xnUTOM_lpx_t4X_fdy-VFdpvy_V_x9
dpz__lpvytzv-FFdpvy_V_xu-VFdpvy_V_vbyGS0-VFdpv-_Fm30lphy-VFdpvy__o9-_lmLW3z__lp_piS-mPy_Vpy0VyaVFt_-_Fddu_xHuD_u_FFdxm7W
pvy_V_xyW_yFvopmv--FWExeZvy__uO7eDo__lppvy-VF__60lJx-m0y-Ji0_3y8_tZElvcVFt_-kRi___u3m9y_Vmz0lV_LxSy_7kAFLy_V0n1j_lpx7u28
kVuUW8Z1_loZol_wq9z_Gm4Yklpvzn-0Y4B_pVWz0163_Jq0CTZV0n1HxBz-mvz_rEj7LFpyan_nZsZmpn-90n23_Vd7hMnq_lb7WVuR_Hs0QFFFzZW0SJyD
Nt_yQmz0V9AQyy-_xG143F9t0Ahvz_Bd7wNwN-FdVrOLe5w_tf__ymSW2lWR_3q0DGKeqT_mwzy3KADVEtyvl_O0H87-BluUWFhaDlv-0TOd1_Cx09c3_Hs0
_7b__lah-dczoDy1oConytS0CdFk_FddO7y5o5lfukUVrVfDy-VVVm0o1_ix07ax-_Cx09dVdB-SFtK0CdVrzm1aWNuRF__-0v23_Hs0pBd-3a2syVFlBq3c
6_mTW6paVz2V__cWV-RS-Ji0cJbt_du1PCwTlmEG-RBvEm3PeD_exm3SBm1-1s2mlmCGMPDLmC-_em1xpPz_VG7uAq0_lvnDBq3CzdS08dw2d_-c1RX6-ol0
_lpyO_Zy5I3sc3__iw406ypV0MWfmAhavzzRW31_1IZdNzaMBq3s--UDyEyfG2r_lxzlWCpPytS0qlmL0By25FEl1d_-1GKODty78FVXbxEd03Vuj_7t0gJv
Aq0XVwS___e2l9xV0SWlpt_bpSZvJ05cpzyBaFWLe81_Mty5o8tdpx--0EQl0AFulG2v1R-SZnKW2_ZtzVS2PDxqNo_XLm3pLu3NyFC_ycO3vl8hm71-1SWe
uk_tvt_a0y6l0FWLuDh1Nm7mAm1-1PZAp_zuW7ydVmKuy2i0VWNuDl_AjqK1hYtdhm3u5M08F__w1k1NW6jpVWKOpgy0nvVuLxuh2d0Ddhy2NA_XLu03lmBW
Lu0w_Nv-1QXl07u5MFlmAq1z0wu1_0emary1ZWBzdVaLuApIx-UNyxYHuVnEm56WlpE_0Xmtz3VWLu1x3LYJ-HNWciYl0CSD_JVnAy2HUKtcru3P_0hm5dxv
el_AbqG1PezV0sRpAy1iVWMOpQy1it_vAS3iyIl0R7uDcAsl0BFv5M0slmRCrjU0sVmACFkZNmDcZry1Pkjhm6n-1PYjhm6pV_TfmEpnQy1iVNzJUBQ-4p3x
uTU0sUFNWDdw6Z1RNmDcl_k-1MPFtn6OhQy1im-_2i3_gpqu5W00000Ov6yzYBtL000000000000000000000000000000001
}

