sprite $cloud_hsm [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000002OlJjRTnoqWYZiJt20kth_fytepCc9iGgqjxJMVOz_WVjpUvYk_7Er_KjwIiY_Q-yUi0Be
V_5_m0Ymd_1_m0R0V_i_O0BWp_hddm3u7l_MVfGhggKO_DDU0XnzWt_M2Q1ly4-x0FGD_caNWBx1F-q2qFVwvry0-dx_rfKWz0t-sQu0-Ft--HU0lj-_TUKF
_jA-Jub2t--V_mg0lxHJAL7e-_sRaWI_tp__0k0lBUq0w5KC_ba7GBKOQaa7GCLISrILC_XBywIKmL_QamS0VsbF7W3yfJrv0F2NzkG1m5_QamS0VsrF703y
-e-UCG3uzMjt7W3y-gWx3W1-pHJJduuD-ky23e3y-Fu9A5JmwqJP1m2_JfPu0F0VCfJrvG3morJ62m1_-Uhv1W2_jLm3W5_s4ldZBprt0F1BOW3m-qlWZx_q
t070NwMR3O2ECFpIJs1_Zh_Mz-WB07ufgZ_-sbD_yW3WboB-Ho3-sbUy2m3-bm8Ee6jF-1_QMe8BWDl_CGF0Nzjxj3_ywc7yyJyaBW2E_-Q2-EClFNW0-0j_
ZZy3uFZlxt9_-0_yEVvF7G3-mf_ZVs5FzkVuIpNN0F3d0e0VV_pp3m1_tTQVQXP_NUJFyN-92u3hdmi0V_pXnn__Yy8VV-i0A0q__lXhgp_y-ED_uC_rppy0
y7_Q1O0__lZNH_lZB_ov_kDK7-sFl_37__T4-1F-vyF_UBG__ihiJ_WJ_eH__l3d2K3yXV_luK_u4_w4F-5F-1F-X3_XJ_WJ_eJ__SAVy2Vy2N_2d_0d_0b_
mf_m9_m9_nk6F-5F-1F-X3_XJ_WJ_eG_uK_uKoxzTtlyyNV-vDKgjDuVV_FFwQNgQ_tnFznpSeEjzCVVIF_E_w2zoXz_a_t7_k-wvZhjJ-VvQtatwM_1y_lZ
Rpluy_xprq0t--Fln9_tdpTq-kDlm9_mzzm2Dd_y3Ve6_rb8Zp_-LHzrbBB1VyRIuO-_uUYR_ESrJ_lZRz3t-KzxdlF7_p3eU_qdHS_uus_GD_Xx5g3PyBVf
-_qdLB_qnz-gx_V_sFKRV_ohNT_l_w7il3_-BuE-mT-pW5b__0t_lsVmTru1-ZWgXiDlyBTU0N95nLVpfNJ1Nrgo0L2nrgmfL_2Nbca0LDorL0E0t--VPG7q
AlvQbW5GML5BCW0g2VoJBG3-qfup0FJnXv_x7_vQVtv-sb_g_zpT-U6lFwttyKlzllpmlpJ-Rv9qEtxu3qdIH_xlxi8FlzxD-Kkwd9zS-FF-xwxa9oV-lF-x
bFpmIpBupopWHyx8WE_nbvI87tx9xYybuOTVMk8lnUU7_v2M-Kl1-U6NblfBWVdXbvRxIq7vuPUs-4kB-UbmwllzrOFnS_ohTlfBeVZXbpRxAmu__8Vs-qj1
-E6NBl5N17xUvLDrbR_avoV3uRVu-sjDxk3Fux_XmGB-kFxsruVWB-Nnzxz02Fv4_lvNYC6VoD_-4a6UzbSY_-Rsv_WhaR__DSBm9_AtlqYS9_wKoB-v_Jd-
IkJlVvS8_8dyF_mIIJBm1_GFz3On-CT7UVbZ303-CLEty__kJslv-vZEmnzW0F2FBzF9Vdxnh_eY_0twCnduZHS0_2_3nJ-NZN__03Z-RHZoyE_tXt-OCl0R
1e3_fBun0_zMV_Zxi5OD_Fi6WF-mfvdQbVxmzx4Wlt-J9BBpZqMbk00u_cDPyIy0ZdyV2uj-0S0_rlQnMBzY0FYFrVLK5m3y_fm3m3yJ_xkW5m3-OrC9Bm3u
zm-Wxnm0_cDZN02cSlAFxXi0_1R_iRVE1U0e8V-xI1S0nx-FxTdygrB5yNyNvWB0VrnIDd_uz_lN3_mx_eRlTE02I5VUu_yE_pEzFFu6lPMl2Wxep_Ml_n8N
mEQkudV-N1TV0FYxmUxip_7N1J_ZJv0lZkRuhtWPKKzo0U3Vrxn_2Fylsyo_wit3DOC_nr-JzVWN0FuhFy-jtyQVwr_VL0q_ky4VVnF_V1il0FZN-KiR1X3L
7tzzNqt_0C3rttMYPlebBlF7NwSA-m20Vzt0BrtbppUzcMIs322cFzT_r-bwNd_yPIZ00m3-LXR_0EgZ_V4V0Vtnbwdz_lWBV_oZjECV0F1dzXytzSSVV_pb
yMS0-EEFF_u6_c03w8_snt_W_qlurqVxuw-i_lZZZtzzj3_-mjyO_lZZZp_--EEFF_xuut-JyCSVV_nv_XT__F777t_yUnv__7dz5_wy_fFN_-AFF_xu3_mD
uOy__a_Zv_CVyCU_uS_dFsNqnx_YRuZFVqpfp-U_Zhp--8yW_YsEFmFmy_Uenn__VjVlVy2_hxy0Hdf_llvl-TV_Z7hBXt--_wqkE_xu7_ikW67dz_jN1Oll
VnqZmFT_ucyveGR-pDS_t__UD_1lzyU_Jp0P-BVwCm2lKpFef-Jd0U2TWJ-MF_uQKyd_CrxgZx-6rQkEoIpyFzeG5y0xmy-LzFXp0Rmp_3m6V_oD5y1yCp-5
dn__mtm1x4y1ZZyF01g6qXv_7W3K0_7lzyTVkVch4iO0UfZZZxyo7d_ygsq0ZUi_N5m0TUxuuvz_0FxhdmiWwm2wWH__l0De7d_ySmwWFTgV0RZuyJyo3g3v
_Ba04Wx0m8z_hW5m_ESxlFxgCGRGpFvS086l0CFnnp_p028TVou0jR6x3VnS096lW5Z-3A2FpQtcn_zGw0LCy1lykG32FGWO-F6t3g1TCO0Unfy1IFi7i8uV
_qDx5w3v0RG0_bm0ZWLyysE_uwUNOG3M2RJlVcJ_pf_AuW6eZec-dau0VWPW_iJuKFpu5vtgYxTq6VZj_Wp0EWFzsWP-ghO1-9lcd_UdadK0y3E0Rk37F-q0
UdkGFmE0dm7u-Ub8EO3UJFvKCWt0pqybz0BczEVvwPLf07v-Aaa603y3w6skBdiCe6Xlt_CttIS6qDi6Vlm3Bk3n_0oWjuNyL68leBNdyZE0jfwVIjG5z2ty
L68keEtXfwC4N43Rna-rH5j0sybFfKHQG6sR-Qd4MK1h-_cfdCYgdu-V0HGt_dv-AkVouk_dft8sf_r-VghbV3Rx_VpqAfPCzFlvgTWw3FhR-QduodZwAPz_
bJ7AvYzlTAJobprAvAy5KHP_hObo-6jLT2Jmry8ekh_MHh7zjJoAwwyTKLH_ROeY-cjV5CzVMwDO_jeUnV7N5L4GVrqL1V3lkZ2wsbyNHsR_TFfqaNzLaEW2
VqMAZht-2XVjyrV8gExmL-1eiR_2HylybIDwBV1NgiZghuIHnr-9etF-ka7qZR_k6IlGu_jZUt0i00000338tteIEwiR0000000000000000000000000000
000G
}

