sprite $dialogflow_cx [512x512/16z] {
xDAn0G0G40H1a5__tOhbel-P5dRp2G000000000000000000000000000C1-fHtnBI2-0zHtWFmEKB_s0PpBhdqLC1H20HHZ-TUC1Vwu8vNGayVURx_JuB_m
yHi2r2T0VGBKRm10VWBK9y2UZm0VFm3g4w0-0Ue383y1wXDWpqU0Zny0zGbGt-CG-Gq1wXEWFW7g4o0_0EeJeBwzeFnHXW3r2L2V0FK1a9y0zGdmn8C07py0
wXEWFW7g0o0_0UeJOCz7W8yV0FK9KD_Z4FaD0UeJe3u1wXCWFm3g4w2-lQ3yXW3r2L2V0FK1a9y0zGdmn8C07py0wXEWFW7g0o0_0UeJOCz7W8yV0FK9KD_Z
aCkkNI1RhWCn62veot7slzy7mvT9PQKdlpOmyELO2boOVynZ7NFSyWX0N-ly4Ttk2a1_hFDtrhtE0FJhE1_cgFjS0V3FysbctUC2G5_dmzns1b3y3xF6Ntul
27yzqh_Q341_w-nxcdcN4c3sxPm1bC3bPjzrPm3w6sOVCs1Z6XJ_jMO0_1kA_yep0FuDnN_b6G1_eFYlD0FW3nI_VGPm0IJrvqFENZC0Vc_njvi1y3kBlzyC
AFoJ-laP0BzfzZMT0OM_utbFQWPm05IZsUUV0VWtB_xy3C3VKFoX6O1_XOi_EmFmZnT__nc0lw7uKpC0_tpnvsS0_laNFVaPW7---FCp07z_jCv49lvl9Jdx
yZC0__Zioyy0_FFFU_8p0F_yxClF0FpznP_F4lul95dy-Hc0VxBuypC0_sJnv-y5ySyMVxu4yFUdJFh-hCB_OG8lUgAPXV-VISw-_0p0F_cY9py3y8yMV_vU
47zZnjacPVV7lyv6iVlZVtJodsP__Eji5RC__khbFxp--CzU_hgrF_xprlwS__Bwupzw-PVPd_k_rOb_kVS__ceu__4tPlPRV_WxCxkDF_oZtttbNm3ZRuvw
_VZnjsTsQdxy_QcZsvSV-ETcGBxuyVT7dOeVVtzgDZhwyK_EWFpHZtzy1kIFVlpzKPTxFlppCo1V_FZxKwjJyUFlZrQduiVVdzdfwCVVdpew7Vtu-pDMfwCV
Vt_KwfuFVtzcX-B7Fpy3yiMFVtu6v8z-_FrHgwCVVtzcowCVV_yCoD_puMzD3KaQ5Pe1ynD_F_nzqS-C2io0ezxM_v61_u-u-T__Fpnt5__G7x7xup_q8BLr
1imF_ks6sH__qkFicm576Vvo-9j-_hjdm1hlAlut3W3yJUs_UmRe4rUcf0t--1jcWA7u0_xu6sQ0f_W3_lWRPe2d-0F--7zu1jJSSFG7_F5_zmnO6ux-Z3_-
_XcmnYVqW_xuQnY_3T3RnH_nnzym0op5d_37tr02bk8F-EFlkGAqFCMVzyVV_qXulbtyIN_yBJFW-EpHFwIeF_wk6M0u-WF--DjcmCVl-QIuF_x66M2uvmlu
u--R0ORY3_ZZxog1ckl_tf-6E_wB-UFl-nA_f2x--Fi_mnjgwu-_D0pwVVtnbyfmzFVrnr-Z3FeD_F6tbi1GVt_yVsGOz1luu--P0IKrySVVFmDgg8i__luI
CEZR_V6tf0pwVVtnbyfG_7tzyTSeG_6tzSTV6eQZlwy__b8PzFlwuo-LeVZx-kElKORYJ_ZZxvy1GshYZx__2lYNlJitZnoAWJ1eFC1c_jckgTDRuXF1hZ-5
0bldp7peP_Zp_wW_yBVxyv-FFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VF_-TyUVFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvzox-ljUVV-tohtlz-P_4-UV_KGVEF_-FAd7--N_KYOy__u-Yllhp_rdK-lF_MHG__vzr
4Z__dzMgR_tutryjqkS_KQ-PVluZLI_HvpzKBPb-_Y4Nq7L-YVzWlM3w-GzMlM3w-GzM2_JvJrOBff__PBr0d_zWrGkcd_zWjK2V_sIrOFhvJzOBzFaFLhrW
-laFLWj-sSj_ibem_VmdwmNJpt-oNg3FVx1QCFty9wi5-lmdwmNJpt-o9-ZplyvB5g22-VdNER7-_FlyNNKjRxr_rpcnZp___zFdVwtsxnF0ptzEd_-rrh-2
-VdNMSpl0Fefqy__MkVV9vZVlm4K_flRv5ydbzy_WlN1Fz4E_oxyGstmVuf-NM_iwVvzFFoZFTg_Jp2_rmFMg_HTG4Vhku2E_iBl07gVVbstvG8wUlfTGDD_
T3NjxsU-X_Vd_bslrNS17Jtz3g2ZV-Pp0HtzXTy5jEdt8K6n-WwWewVV1JHzdnGQE_r-8LZqVLXuxlIxWCh-PQy3wEpfTm6TFVqke3fUtxS1XxvV1z5t0VXT
07q7GDy5xFYtVgK__0hNLpg_qlKLhgyArrVwptmAV_YLhgzqVgNhArnVwVhoCz_Zueybm9y-V_pywVEdpv_-FtRjWm0068G1c7_NkE0rbR2mpqJmywVFdpv_
_FpfywVFdpv__FpfywVFNui7VvEVFtt-zFdZvq-VFtt-xdpyJNx-zFdZvq-VFtt-zFdlllE9oS-VFd_y_Edpfy-VFd_y_EdpfyyVFt_w_EdpfyyVFt_w_Edp
lyqlzFdJvq-VFtx-zFdJvw-jdx_9pvy-V_pywVF_fo_q-RlpyJVv-TFdZvy_VVxq-TFd__lE9oO_V_hyyVEdpvy-_o1zmS-VFlzOVGM0Nm7GLm16ejg30m80
0104GFzVDwDIu1e0000000000000000000000000001W
}

