sprite $cloud_armor [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000002OlVj6aXq6WYZeSD0cxd_QBwnUBHY12HALpr-PHOnQiQWnSzFutyoDVlG2u9i0VGkWdxK0-XO0
tmJeMm1z2w1l0V1DWBu5qDze0Jf6bxO0FKPd0Wv-2w0Vi03LwD8MeB6aclUAlaE0lWN0jm3wxWZGJpW4w5k0H_iMuD8t0VeMGDy2u5i0VSy8q7S8qBS0-1P0
tnq1-YlUvOsYF_CM0B-PB83-afUGZddTw3_ZWppc7Q8VUZFWuBS0-k-hW0Ku-2z_2EXOms013duBeE-EW9lzwtqYglNVT0jmy5i0VNS4tEmx1DpiMu23tmBe
koFWPjyXuDAt0FeMGDyT0LUHGy2bRm7qBO2-EmAk6OU0Izy2w5i0_SuT0LV8a_-IX4lVoEbR07rt1FmAbpi2r-kHeEzcmC7VMG1zTmGg3jyXuDAt0FeMGFzj
bUaFlylqfzzb-jFlCltfTvNf3x_BzAVVPVhJxpBzwNULwG-_o_IdtsNwq-yo_UbtDVZFxCBzfpBzwNUP_lIxolA7_xue__a-1VZJ_x80V_fVLhlxpozJWB_u
Yx_uYx_uYx_u1yHV_CLV_CLV_CK_8FxYB_xYB_xYB_xY7n1_yHT_yHT_yHT_yHV_issmCVxdkkCvmt_rFnaFyFVvrns_MVnzk_ZxUsdy_Qr9_kVlzsqm0Fxd
x_XjC03-_iuy_pE7_nO3uE_Vfl1Vppzg8t-V_qR_Ouo_VpB7Vpt_E3Rnz_cFSsNxywyj_7t-Vzcx3oJBMXu6mrDj8ogp_zN-ESVhxy0L1rujO2XuP9ZENL--
01QUFVxrw8l-Qm3mD_ZNryxv3md-HdxDM-TqV_mD3FWlzjVCHSxrnt_PXnFuE_arUOaJ_V7NvpdF7tzLSfe__ghbB7_yKxNqe_pnLpKd-UElUixnnr-_9GVu
uuy__ePlBCA_4lpnptN-ag40-DSIxM9__EE9Vr_atxzqVlX7HBh7VpuA_f_pHzpgZt_yAUrEV_pZpqah_tmL_4ly4Ur2V_pZRydPHllxun__a7QRF_xnJvb6
vFV7lyuVUPK__l6lQNMXr_hZ7_-UIK1-V_ph_FKN85_hZt_4umBqyLP__2EU5s2yrH__YCS5wEEj_lX7F2v0ZhVwun__EsqYJJpWRwCG_6VnH-Gy_cY6ySU_
mbzlWE4RYmh1ly9VRq1ngQtyyO-FasrAqzfwVlmB9fNC-6z66lpndy8_dYJ-6gC__dx-I1y__dx-YEN--EV6_95s_ZpTNnlpHpJttnKH_aR-2EFuu-_dZ_Jn
u-_dZqWhF_vHog_P_17Dme-_dxzUW3uc1Ny_Vxq0enxyj-UFI0C__jlmHwI17tyZV_qDQ6DAyFVprnimdm7_AELdDNz4j6K8-C_dTtnZKJtu-_bBMNZ--E_F
__TTZUd1Vt_-TS5_V_vVOsdmXn__A2NVpO-_2YRm7-WFlzFVlmNudnpU0Vxmumy__llo_uprmJzgEOOVV_ZnX__Vqs_m5_o5iplG7twdltyJy3yukWFyx-R7
Vr_-7Ek3F_puVn3u3_NFa_dnxnFzVqxch_ltSS85qE1tFlz-_wlvyTStJAAMiK7wpVxm3ztYdoVpuvzJ_WDWuAzBVTS_npt_0NnKm0dyXRtntx_gHjxAlnH6
z_ZdA_dNNStuxyy_3mV_TXw_9Fm_tieo_fyr_Feey1VyZ-6l2-6V1_7NZV1lX_9B-1SU02V_pn9-mLzu0ARoXvc_peJ__lof1GN0lxs4VwWU_3-O6Yj_hkJN
6luS9pu0Vlxv_lAF__x-xI3-kXN-UiEtU-It_6NmTpy0BlwfB9Em3Fnk_sRaz_lZhsFvwrfvix-VVxw_hdl-wtjA1_zR_STv_kqW_heN_ZBmx-clE_tJnh_U
NrVwrny0Fx_Vlvlu_HU0uJjzD_JNcVwji2q3F_x-2y36lzuV_iB6BFn-V_oj_FZx2s3Wj_lN3mb_0x_17ty3lzS_hVx-0jZu_Vxr8yA_pk_nx-EZuAzj-KTx
uB_cXBW0Vhx77y7rR_JtyqTxvi_uZpvXVpR-o1ty--02yF17SFr_mL_RyaVZ-lTT07x-ICRVTm7u-IEQR_pnz_D7yi7_5mgGk_97DCRVTm7u-ICs67ykW5ys
_aXLq-6VjKy_VqJwnXz_Ftz4y_5hK00hVxq0Sqy5Vpz_H3FnQr009t-z09FF17ydVxq0W_6VLG0_V_sZWDadSfL_tuk_VWKyEX3yjJT_HBQg5lxFzclZhpTW
m3zdmtx-UWNw6FXFsB6DlvG24_obBVluwqlr0X3-XJr_dJ_NBWL_VTFmQrnPWFFu6VzwxU7NkBG0S_dztrV6-DUB3x_6jGLmyiFlzzU-7_VZ_p05V_XlzMyd
yUDVttx2pmLmCR_6u08uXf_nhny1_Bm0j_9hK03bGVprySTVUI1_mPy2tCsFVpkEl-xF2-3dTuq_1LXYac_XnxyTnL_tvmKuXZzLvyTVQUOtZpy5W9__0i3F
2_1g_Zx1dm8uljNJF_uKu6v-_7KIVzsV0ZJuAS2z_FWhhVn-VmfmDpy5q1ty-Cy_eLz6VeC_1O2V0i2F_slu-oY40fp1NzyN1O2V0bpCZxzUmfz-VmhWuny6
VWe0FmM0tn33Wta8VqU-VcZQcZzb6tyAuEVl5duA03y5yFFBm4y1ticVW3yvllvo_ZOUXG9eEtx3xKy1uAS0y5C0-2c0ZL_mkyxoC7xILSiE_FWRZnD-2k3Z
bvsV0kXoVWfmDpy5I0j_tuMV0ZG3lpRYfm1tyrC0vLVvjHi_1MXtyrC0vPVujIS_1MXtyrC0vN9-xSnF0ThT_1H0kP1V-_DJ0ENT_1IWBU6NWP_aZ2l0fzyH
z9nyJkNNsuQV0hIycfy2g4tYrplvAO3Q17xv-ObS2dexFmMGPTMEsTiRe9s6d-Yh7j8f_1IWVY6tu_WfWEHTnnyQq2SiOTGdMioZK_WfG9r8sf-VQ0rJkqcV
0aWh_abxA43TIpgMdmRKWpu5W9y6e4y1uAS1w5C0-6a0-XG0VXg0FWr0dmAqiKq8mqy3qAS1wDE0Q_b9lroVDFHv1D3d5K2V1g3FCu3-xzkZWm400006GlxM
ezZhIg6gUZxvVUhxvFEfvvFV9vzFFfzyFl9np-qU00000000000000000000000000001W
}

