sprite $cloud_routes [512x512/16z] {
xC410G0010Em2Fgt5GE-hVO200000000000000000000000000000000Q7RhX0XW08PXsDwCF-C1iIXKlbmtDsZxxqiVW7zv0lWBW7yu0Fu2u1_-0lcR0Fu2
u9yCWBy0-Fi2-Pi0_WBWtmg0lm3u-mBvcm3-0k0l0Fu2u1_v0lcR0Fu2u2y0_WBW7_m2-Pi0_WBWBm3-0k3l2-Hl0lWBWBy0-0k0_vx0GVYd9e2_0FWBWBy0
-Fi2-Pi0_WBWBm3-0k3l2-Hl0lWBWBy0-0k0lo-GlmdWBm3-0lZPkPF4nfaOXi8RHOKTxd_QVzncAD4EcuBUkq0IVvID7gFzEG3yvwz0_KhuxvRfhm2ifZBz
boUrpi55-el7Vxj8Vy6_tP7eB_ZtI_GN_Fib-Y-sttw1_kBnlr2Wl-2_q97dB_YlbEU_uBzIdByqbvy3m9y3q6y7_wMED7_1Vwqq_pMOdmDGGpFvEG3yEG1r
D9QV5QYMuBzQbh_WlrgMl-RnSm3uSm3gQYG_Ar1jmN-z97_1VxqaVytYvm3mvm3KsJX-Lg1QWxzIZh_WhvJZl-2l5ECl_4l5-6iKFojGxS5VAyLVyDTAyL_m
rmhnLu0_pt_t0S2VuwyX_F1R0GS0VuF_v0tuWNur9Rm1m5zE0GS0VpsDFm3uC_tNd-U7tnfz06m_EzPVVaVmT_dt7m3ysVvo8VXp_1VyNxVSa8OU0Fosy_tr
H_tXjoOV0Fpv_d8X-7FyvLeiln3_vKey_2d-SYNuO_pbZU3FzPStWZ_NNxuMoo_CVzas_6vFG_A53lZZ_ENzu0_q5_m1_Wq7mF8BzLzFzhSVxCyRWF7VFW3u
i_mv03_PdmCm_eKDY7w0FnlGD-pHdm3mEsy2-7BZ-Jc0-Vw-Qs4RqDUBqAyNjG5TA8QV3UXAAVnCWCELKlWv09SAuMS3kbQ6FXlGnIBusO2k1h-zRdy0Xwib
yBC1NIw0dmDmlVlhim7TxkyviG7TxkyviG5Nkxy7nGHmi__oe3W0D_jxKcn0D_jxKcn0D_kx8JRWM7-FYWdWLl_bKN40RlNthDY0RlNthDY0RlNthDY0gzNV
ms82kD5_ULWSW1lzFIqse1lztHm7yD56CfAV3JZ8t-DY0lXjTIy_3k1y7SPj_fuN6z1j_fuN6z1j_fuJ6x3VtmFZ0DpaVtXWR40t-NjYR40t-NjYR40t-NjY
J82F9d-FZ0DmY__XaR41tUBlcR41tUBlcR41tUBlOV57WQt-7XeRq0t-XuV61dI3lwV61dI3luV60Pn7Wx_7nWRqh_j_U4nim7v_3uWDsDyaVYP0Vy_cvm2U
pSy6VFRoum0cFFmSm38n0OW382O0SG3FYmr8J03Y08W9G1m0iG692K0S0341Y0CWDY0n0OW382O0SG341YGc0740n3yB9JOWiG692K0S0B41YGr8R41Y0X07
G6n0OWDEFp0EuF1lzkoHoGHuzcSC1_3iaS46VFRAP0FgqGV01lpvjnhf39u0-ka0w3o33s3ZQy1_vcx0ZQy1_td6Ri3lTmQjy_zID-3EbV7uvqw0lQy2_xao
3s3dgy2Vkm4tlWhymGUmiJJW3zw06tU6V_06tFywy9z7tW5iV1tuWoU0lWh-Hnp0njQ0FtW3wkkMZN_w1jHtmH-_0VLjyATF07qV_E47e1zQy4TlGFtKmZzv
0-ho0S1_EkS0j17ykHD0Ey4VUm3QQi4VkW6r6VwP6r2xmH-v0RKT_8aJGFl1F-qJGAt-Ml37JG1T2l-q0z2ru0_RWBeO_5aRK5U3VzOdm6hsru8_Q0Ae4Fuv
1w1AyCTiG9M2FsK3gXRy8HjGnKxu8oQ0ok6VS02g1t_01jGBmN__3QXNWl_sVnQiGaahyEFiF80qVud7_zx_FPnU3VvRRq2z7Fntte1wFVXll07rXaxuRxi1
t_TryJ-ybG8Be6pSW87XNzY0IU5Vc019dS_svm1autzm007-RC1Q-3Tim803mDyAZVT_3e3zpm7mwtyEu77-Xw-qE80mVrzBiV7dFnn0P-FuEO3MXlDp0Fd-
ovKM1n3YxreApctDvES0kXhApm4qDPMV0-XfvlPZ0qgFyFThARfyVnVY06ByNOW3YF5t8GuWnd_v7Ir55-plzwJiLgg_pG5ibUdlGXn0ZB_V5GU0_-80gYNm
soh62epWjnLVahyzv00uW0X-3W3_nG5KIk6tuQyKms_3N-WU_1p0uGn_L-80x0p_XNybf_ZxTuF_Qb7yDlmNo-AtMNvp_TqH3p_-y4_qTq_mp_HtL_1Fz7TV
BBzv_kwCXnz_-2VvkpVuP_cxE_Wd-Ri_bjzU0_av0BU4F_nEvRVXtsaOFmUmt5eklyto-xbH_1o06yCVVW_Yvm3SNpI_pVBxeMn-c-NtVKFuEG2tXp_y7i7F
0JZFtrDY-NrJFh_DykltzsuSW9td_u7_RaxqzwpWx_LtVWtBBptyZx_PhGCQ000GXc4IxjyjFbXdeO5yuVWl4d_y_F7pj_puMtxy5ua_Vlxu-Lj-_2q__el4
7pz__FmjF_wM7_yzIlZvu-Tl-V6t_FZx_Vmx_CBFt_BZZv-_tyyVFt-_dpz-_lZvxtN2pz_lv-_w-VUkNuwVFtx-VZz_ry_VzVDVB_xu-Vlz_5TAhf-_u-UF
d_zo2Jz_ou__aWa__ow_slogBp_-otVjmO4C0000m21_wtjyrH8000000000000000000000000000000004
}

