sprite $debugger [512x512/16z] {
xTm5RYLH54D1mT0JpVvNEymOQ4jjkSuAycyvdCxRsoT9aYH9aYH9aYH9aYH9aYH9aYH9aYH9abw7Szzi_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_FcNnvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VElZJz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__cUR_ypxdsd-m_yiy_F_q30__u_jylF_r2m__y-jylF_qYW__wzjylF_
rYG__-yjylF_eK5-_Z-sny__f-Ru-V_S6Z__NnhZv_zhM_pyVskAd__lBV7p7nh0gVFFl_upC00ltmNmpzu0lolWNxm3VfV0xnRufww1tptmkmX-Dy6_SHNy
xeBVPV2x3NxNmJzm7_mkXD-DyBiI_e4xuNSf_6w5txNmknT-5yFlPlXT3R-xuU-_77wtm-zw-DqFlmlYTqFyheZV7V6x97wtnE-Q-DqJlulYBxafVWF0Rm3u
3G2_0U0t0Fnb0tXvyoxaLw7_bVpgyx-KNtN-r_AhpVzYVfNvNyslBl_B-LNbVps_clm3_2hoJ_2hnp_2hnh_3BzQ_4FyAl5FyQl3FyQl2lySlnhyW_mgy4_o
gy0_oQ_R-sVvTNT_Glp5N_p5N_p5N_p5N_p5N_mRUXrkmF-sz-NFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VF_pook_kVHyQVFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy__Vl7dpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_
Vyz_ykVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-TVKAs_-8k_-8k_-8k_
-8k_-8k_-FV7_sppy4yEGEVs_ia1u2_mpmq0Vu5_RW3u6_nZ0y1VuPyQ0FuE_z00y9VuPmQ0lyK_CW3yDVw90U3lyGyC07-HVs00-8ly0mF0N-GV603-8l_0
0F0N-GS6WB_8Fp00_4N-WG7WB_BF3G3_txltcqSopcy0-0q0lm7WDm3y1e3V0F0R07u3m6y0-0q0lm7WDm3y1e3V0F0R07u3m6y0-0q0lm7Wl_i0y1i0VWF0
Rm3u3G2_0U0t0Fm6WDy0y1i0VWF0Rm3u3G2_0U0t0Fm6WDy0y1i0VWF0Rm3u3G2_0U0t0Fm6WDy0y1i0VWF0Rm2lmpNm9mVmEbod_yg7F_u1_g81yD_-0eZ_
zZT0_BT_0C9_-mUW_BT_0S9_-nUW_BV_08B_zXz0yT_-0qZ-sty0pN_x0GZ-smz0yTz-09B_zWFG_BV_0GB_p_ohyV_CFnl_p_opyL_Mvx_Dpt-Sd_z4_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy_VVIL9aYH9aYH9aYH9aYH9aYH9aYH9aYH9
qdi
}

