sprite $managed_service_for_microsoft_active_directory [512x512/16z] {
xDUhOSOm08D19ejb_srB-dP_LAYx5Jubjfz_0m00000000000000000000000000ECympXaU02Vfx038IJhx1-0aQK-ULVAd7Vu3o9-sdUqlVxey0FdJ3fy0
ygS6eF_g8q3-jCD_0FdJ3ulzvK-N1o1_EZO0yaDRLm3zLnu1dAl_xXz0_lI7iVxofqC389Vk383SsevS0JYl-ayy0iWVsk4_WFpfRQU__Edo0EHFbmSWVzhk
NW7aJmr0_zK1o9--CD5V_dHv0FAdomEG_uszErbR7bl10EgZCJhZ_g_sd6ftzGtrXVmO5dETh3SRC1gN_rL70FLC-5yk06hR4_wN2u3Q4_xJHW3y-tjo0F3l
xw41mB_y1um0-1F-5_awa7eb_Azt0gWzuJzo1C2_loS70F_-7Xe0_Cj_w0Y0V_dFMmBmB__hdG1go_ZF7G5S_g_tn03WN_KU6W3ywm0OEWBWNm4OkWJWZz4d
0FuOF0BmZuYvCo3-vVyQ6W3yCNe9m1-Zbm3yaTy2jxXCuO-PdmFoNo-P603ysszUCsm9mFzSBnfv9q3pNpNtJW3-zRAfIm3-6Frb0Fon3mi0_pzvuPmb0F_l
t4P-7SZflseV6m3ywxLJbm3yCVehuVXZq5V2-V_DgwSi0Mxw_BQc_IR0JP_VrZus09h_UeEfIm3-6FsxKFpnkRyBLQyCVyB_yak0pM_LFY00-1F-OvO0_EjT
fYu1-6Fqms7mHvk7mwZ7dzO1_0d_BZCW-hyFmL7yiVSE0FjL1zpqIVYtMGBehphWz4_uzra2uAywcZyQF22GVgQEvO-zGG3efoh3d_3lFGFINxKzZ-EFlK40
w2ThEum_6ZmZbdw-djN-zKi0_k8c40d_vZCW_NmJY8H_ym3WpmSW4lxDPq3y-IaWalxr0L3t1LT-14JAl_KIuEBF1o0A_1ij0VXNRGN-fJCW_le0H85_im3W
NvNWJ_ZNp83uwmCGAV_M0S2VRm6Hz--w1E3F1o2o_lN_5cVlhwwjmBzW1dJvbmSW2lox1m3_-YWu2lmRpu3uLot-0l_M0S2_Ea0K-7TV0lYl04I1V_ib0F-g
2l_-Co3-LGN-0i2_-Go8VrM1lm3mRxu4u5zLv6y9u6y6pFFt3y0k0FpDW4Ny_GEm2m1_Iq0HV_y0x6S5u1cTYxyPa7zz0F3NLvb__Gp8V_drywyF0Fw2Dqdu
Mm9g_VDmBVmj0VawZAs1lnamNyUftMlzMmG0_sblblSt0-RhMB5AVm6eg8F1YlsRBm7yjmR-be147UrLwjzr1iHV7u1T0FYR0G-k0gpU_WB0tnAmgiAgfRy0
y3S3yXS0_cR0LILKDVu2mDyCo5y0-9i1-Gi0VpEW_Ky0-9i1-Gi0_ze0HADo_zSImDyCwFjV0i3V3EZxtm9Gxt-FVwXR4tzBWDz_MGBy_jCCwFVV0d2esPRe
_GNFVp03UlwB07Z-aoN0yzyi0Px_Q0Rq_DS10V3yPm7WRmdWRmRq_oy2mDy8uF_V182_0FZ_Lqi0VpEW_tyN0FxzHm01Y4x-0i1V05hpr_jR0jhor_lxEX1_
Iq03_WR-He3YYhx-0b1VqTPV0Exr_FV6_fQ0UlzexMy9AAvexcy9AArexsy6BApexoy0fVpz_GMWbB-_lpi17VbZ_uW0RE5pWCJUtz_Vzy7gB_x-_Yy1AE1l
x2y0fVpz_GKWYlNx-_jXS3r_th__3BY512Jq6_jxEb2jVdz_JuWirU_lBm1Hgj_VNm2YLZ_ltty9U4Vufx2-_fQ0V5Nhz_VtZy4bzlN-He3w44HjxGC2e3hx
2m1__nZCVtyt201_Im1_8m1_0U0l0FpT2U1l2-Hl2U1l1E0l0Fm5WBybWBybWBybWByHWBy0y1S0_fO0_fO0_fO0_aO0_WB0Nm3uMmBuLmPWZuBYRmdWRmJW
Bm3y1O2_9O2_9O2_9O2_4O2_0F0N0Fvz0Z1W2U1l2T3_TG3plm3u_ETQ0NYiuh_u1_W__hBS_yloxrUnhyy0Vi__lnZ_wshugyRvrrxy_V7h8-3ixwnVdm3y
dVNh4w3rDz1Frm3_nlh-_zVPx_-_yTVhroT0w-_CNny0hRyDVxwkvU_ipzT7-UFl5u3FvtzTgVNdwrB-Md--FiFVrbzMd-2Flx3w-_l0lxIw-_l0lxXw-xlP
Mrwj_V7t3O3MNrxtC_plxVor_dNvDpu0dFqz-VFLr1z_wm1e_PsRV_q8eFLNN_wz3m1dVp5_ym3Wvw_rr_5t3u3MtvW_NstyNVpyFTQXVm0-Y7-BWkAlzTT_
zDFtGo2jl_Boxty0QFtyjVug_lu1qFhvdrWl_Bq2eFNpr_eBwkjujwlvlmhE_gvrpF9U7m1dVnl_BV4-lVtnnt5gjVvQVqqTY5Rgh_Ktu5-T__m0EFix-6-9
T-llZpyE1Ylrr_hxFzU_pDy7_XLrEvfhUsJgbl1lVFQx_EiF0FmLLO3Lsr_hvw_rhogmsWhz-z_hvn_D_RL-_bf_tYew-FTl_VnlXVxzMp__-3R-MZz_hP-_
U_tyjNx-MZz_hT_-h_Nx_4_hvw_ryzVwtVz_vwlxsSzVw_VzFwq_NzktzK-qLQtVz__Tw_VxdyQjd_-Zhx_MNo_sQE1VqleDWAlk1_9lv_c_fcxzdl-XzUVz
ysotHrD_hJ_lduTh-lmlhJyVW7phxlJyl_hMpt_LFV7g0d-jt_DVjNxF_zRw-Mlz_BL-__-YzVDlt_e5ODlh_FktVlxxlZ-B_FktVW7OVb2gyU_Fpt_Vim6u
KEiNWEUIIlXh_NMrdN_v9uy0PtzfdNpvvmDGk_MhSuU_V00kq_hvBwnC0ef_rwzEFVtp0QXk_UhCqpyVW6f-TJ-HFn-0yhLFdTZyymcevrVdDVzy04uu-zLf
_Fa0dC6lpkBF9-2Kir-TDFlb0z1twxS4vFdp0JZdx5VdyES3q83V2L38l-gPyAze_Ug4qIz_19p7h-hvym4uyUnN1Vof-XEZC_bLTUlF7m6ddlrgg-NF1-1a
VbLwooSVW4yz-mKWOZyW0P_9Bm5Bxui1-0PdlxfzLVyMSL00Ff3V4H0HHmNWuyv-2OZVrEjh2VWiVdS4xh7ga2FWqyv-Zua-DW2Vmoy1Hp_4Qxsq_zal0l5t
jVtd8w05lqhO7zi36lsuJvt_HrxHk_MhqW0u-oLWDhy0p6xz0Z2xzGl0xBDV0cRp2y3irYy0irk_0Cm--oLWDhy0pEONW6ksVlLA-C-z-1q1i_a5O3Q_0Cnk
_G8m--ANWDdy0Z2RNm1cjtwV1CpcTmJCFli5OFQ_Dmd0YBDVRGd_GMU_8s0slm3CRlq2CBlrIy1iVW6OtVe5O7Rh5u3PPxy4pEONW7cjN_sf_-iTyqe0Pf_z
4Z3xx1U0sVm2CBlr-rxOxDRl29ZDBm2pMxy0uFz_Ut0i00000338tteMkweL000000000000000000000000000G
}

