sprite $cloud_security_scanner [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000000006RlJjBUQ94e2Wy2BipO_sghawjH_UPpIe6K177k1loGxqdSIrbc
PYFryBVi3U1F0_3J0FuaWBzP6Qc6FxS0_XG0FmdWJmBuKm3-580_1S1F0VXJ0FuaWB-LaMtmV_uAa5f78u3_sWAQ_hFM_pDODlHVNu0aFVj7IG1_Mu0_yO_G
0FvcFlo9Vu04u7SM84ty0mI0lpU0fgb_W0BmTnOWpVt35O2_cKD_uX-f0FpDeJ_n3nG0_6OE_eb_f0BmDtFmJ_n31K03Vdwr7ZS06d3eJ_nZ1K03FlwvV_m2
-DD0EVoZ1402PSgVmvy27FngVPC0M744uF0_CW3-NOWS_j42e809lyC_SW3ysq0v_CC7G07Avqy2R_cFVae05F0I_tZQIG4Gm4NyvyNtfu1h_6Eoy05Gm0N_
ySEY-rF0d_ZR-7d10w20qQwy_FCTv6yf0t3mxna07x2_odzSsnd-PYa3A3_m-_qxNw-mUG7LmN_G1M2MD00d_sC7-Tj8LK3nyZyMtTyiQG1rwfyf07jQfdyX
vk3Vtv_lrl5U_zSNsDyiRG3LpH__0Z3B6u2y_l4l0BF40NZvu_id-0HT_ESponn0MUW_Olgd3g3u-EDV06Q90y3VB7S0TQN_2ETlbZe0_BC7K1tyyVtDiWUW
JFvyfHx-B_7ZZ_yuQlYx-EFlah-5y8VVV-wAluC_v2xub_3-yC_tP_yQmXz-_-7BIl-EVunzo1_-AFk3lqe8V_ZzJq2E2o3izH-Q7t_u_VlvDm0goVt7I190
MNO1zDbu_NSEGAikW2Zy1Vx7VlIlcL__aSY_hWcWJmV_rW4KJLPu_LC4eCaght-A0Eg20Ff1_YEPVv4xWCxh7pW0UGFelFwH0oZE0FfF2ypFhm2aQYVnZnU_
6vCBGBKu-7dzOmHGzSEg7VFv__1F7ehZ-p_unTz15y1y4trU_pC2q8NDxE6FxryTt_-OoPy06lmd-jjo_t6YFm4qNlyp_Ol3FythJm0j9d-1_u-FfwxpZ_Sv
-8ClZRIwod-4yn_uNmkW1URt-nD0S_1l__eJGF7xypc_hq_QvH6LY_v-Vbv__NPt_mx9vpy2-fUxxEUxyo7L2_uUVLv_NTa6dmepyNVmuwyNTjjZgc_vyoqF
3lp9DlXam8l-OsF-KcgLr7kJQYbt-UkTtHH0gHF_OFfD_pr8_xMcSWE_tjrDzsIvxhyl_jFwOyy9RAC_NxiXWCaTq0Bfw__NdzRgztxp9-U-x3zle4N17zB4
_xc0lVJd-wh_F84smO_0h_wNDGNW_ru1DbqfZmfQ0Flf8x_bbwvDgyRVapXVk3j-wwg5mz_toFji0VW9mF_8-tGn-AM6l-EHz_b2y7_-2YZX_VMUVzz0tny0
5u3UzUz1-2NyvzFx_Zq8luJ_R7BuBmwWwSG0GlEhVp40wSi1uDysyjT7r_W9u3UJrxy7uES2c4r-_xuv_pm0_BN2lmVXbtBxuo_-2F1fMkFVe_1BUru0-0l_
FVdLhooCltRqnrzd-vUu_EhV241AV07Whyp--Ekhm_ynhVJlSVpRNlxuIoTS057yyHV-_vXsyLS2VplUlmVorpx--BVK_lWBV_pF3W1__7URDl7N6VxuT_oZ
182_zl37N_ZZZp_-qGF0_mR-81S0_lZp-t_yjrfoVttN7t_yySSVV_pnnnz__FdtlmhWZp_--EEFluSV_uW1u8y__lZx-V7VSBdzyMytVFuN_dp-6_w1Be2F
yEFFvx_Yp-T_ut_Fy6yR-FFz3_pxpopV_uC_t_-5F_xuy_sF_Fy_ll-L___Bzp_Zp_U_ux_vtmIiqiS_vXMmXf_F_ueQm6VvHyD_xm8YV-ap_dwB9Vny_c-G
gKxyVVhuHvbP_Tb_hDvU_lYRbVfR_rRR-C0suyV_aK1zyc-gnN4CllydcFzZvLyPr58-UewT-F6_uHnS_vx5xpWCF_xn0sZuRtKGllyP_n60t_FO2lu_hwL-
_V4V0VXZ-nC0_lWF_7SzIcv-_4S0VlmZ1z3mt_imSLz__FSFOF3wxrvp17xyGmOmy8zmd9Zy2VnZ1t3dyohutnt0SVVbqGSAnn_0FzI90l3Z7oM00N-y8ota
np_YcLe0Vlm_kIZy9G1_pARbNUn7HG1jQttyFxzxzE4VjikvVFhunp-NGp_SUy85u4yWwck2lp-1DhwxudXA1B0uWUCV4aTpu1zr_NCs1polFuVp3_ypnnCY
01uG_ZmVInW0_WJ0qy7V_qT_HkAy_fmHVaw9FwU4FyavySSVVYDq-3ag_bm0y7FOerPIFH5p1C3hpt7XvmBWSUGvCVuScTUVCyD_o0W0Vm9my2SA0FwIENpu
ZQF3Vzm80FyifuUVutD-7W3t7q-0m_CCuESf6FxN7mFd9W3kFGBWq0IGyiZu6_m4m7a98EjfyJVujnu1gFMCgHE0VgtrnsOPbFFy2K3Ia_yy0OF_j1T3Jslz
QV3FTyApaJJtVmp-rG6K3Vdd_dqrFm7OXlfp_zudfuliJm3IPV_UuR-mK0z9B_dte_W9eEb5_teGFm58h_ftmR_OtpRad_jtmNzbjdy1Uik_joFu2K1l-lTM
uBymsxi0lUtVMtX-0f33lml-AxDz2sWk_rxXlpBRjW3v_7k9p4y0ylgt0l-LsPO5oEtV6_oV2S1Y-FSA_uS2A5_Wz_itBpy1p1V0lml-Yzii0Atnxp7vkG9q
PHVy1Vyd0x1o8x_wXHK7Fm5SsTx-Gl_oR9S2jCw_m-y8uFBszQ-1-2bWlR_WTmHmIm9QwT_WVsdcsdx-lS3_qiovtVo5lgE06nhGMlyEwAkp5RlBtny0AxPa
9Qe_iuKBwCziyQx_c3M0FmLuDljHuliJW7ywqfy2yAS0_0a0Vmh0dm3mfm3yAO3V_rC0_XI0FmNWJm4bhpy5u4y1kV_z5mNKrFuaK2BuitBpJm3jK7ukWPhQ
dqkWvFOd0Oz_V7v-8gYv_KaWjpy9L8z_V7uQyFZ7voU2cjkVtnPu_EFpyvboAVq9mV7v_o7vgS7n_GydypFy2S3Z__TswPW0G200OjXu8_xT8k0503Inq5w_
Pe2bynjWykkVpU-0fVCROEdy1bWwlm6Mpc-0fVCxOEdw3bYeFZlxf-fpz4_djy3IyIsmT7mJxDNf0G000000000000000000000000000000000000000000
0000080R
}

