sprite $release_notes [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000020sRjtuzY1A8Q2xlMOVxRQ8C0IKUWJmMeQxojg-CdkdjN47__a0CHV_F7F3a3yySyEGFpnpmv0
_F4R07_--9S68FxYZzy0-FF7FpS0ySTl0FpvupS0_lpn6m1_yLyBlm7mvu_V0FYFHDy2w5i0VGk0RmBqBO2-1T2t0FeM0Dy4wFSlWBu5qBS0-XO0Fpy1yH-P
XGKiNo5j0LrNo2gjpz___xX2rl__JlbRGFiLiWheL_iheC_Vyr-k4FRyvuA_1InV8Mm1orT8Mu0hPFty9t_-MrV86W1__iDNoFBdx_ul_lnT8Up-L_vNqHl-
hX2-ckBtl_E_NwF-hf2zifBlV-5_nx_W2bdyWTFcdzJlzo-xGfO-V_oNU__ljF_npnqN_G_u1nxUM_6_urzvXJp-2ttbpu1_Y9z_u5FX3vNvujD7riNFV_CL
8loVTV_Z_mB_B_pyyRzVuWWU_lmRNo66_mA7y0puX_Zv5rmLpJzGXJ_-ymf9_hElaCH_NY79_-EdrUxF_wiV4lzvXIH_hv3aNt1CPVpyozRAFrhTNlbN7D3t
-VbNRfP_pUbyrfz_xt3vTntCr_pvTu-NVz-XVCMVV_-0-PUUn__wyrz-Yf6_vnW37wql_lpz_i_Vt__u_-hIvv-lIvz_lZvy_hx_mz_tV_a7wzBddwzBdt--
8dp-dl_cx-S_-ETBw_DlAwdFlx4YVFxkV-3l_fUylmBwrVuAw5VxgmMVl_jVy_xYhy2fDVgBl_WhS6Yj_kAlm9cr-ek_0aVMwY_-2fnOgx_uAt1WZVxYB_uA
d5Uhl_WhS5oj_kAlm6cr-ek_meVLxy-V_z8DuZNy_Fdpvyy_IzR5pvy__wXP6Jz__loJQ6ty_Fdp3whLyVFdpp_7riNFdpz__lnZReNy_FdpJy4LylC__ln3
SXd-Hd_-_Fa_BVpy-VFtU3j__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_u
Yx_uYx_uo_E_x_SF1yUVFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvo_-uY_-S_4NV_4N_xtuYx_uY_zU_CLV_CL_B_xYB_xYlnT_yHV_3px_pR_Idpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-Sl_k8l_dln5t_n5_-z-8k_
-8l_Nlp5N_p5Vo_-uY_-uhyNV_4NV_7VYx_uYx_uxyLV_CLV_FVYB_xYB_vxyHT_yHV_lVYBl_YB_rZy-VCNV_4NV_xy--EVJ_p5N_p57t_v0CHV_FFnDm3y
_Fdpvsy0-Fdpvy_V0F3pvsy0-FdZDm3-1e2VFty3m6y0-FdZDm3-1e3V0F3_jKi70W000022_AqdsA0KVXb0VWF8Rm3v3Q2-0-GtWFmEKDy0yZj0VGUeRm7n
BI2-1SG700000000000000000000000000000W
}

