sprite $cloud_network [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000cBrxMMuR1y8mwb83BU_m_cyxB6SpDut30ULIgy-_pChY-GWbiIx_llZ7LfFPY0SR
gzNS-SrE0Rl5jxkjjvzRto60Nm3q5O1V0FGLW5y0-0M0Nm3u1O1V0FXB1s3yyGi0lm3uyySl0FmT0Z3-TekDUKcOsx_o0M0VSTa-LhbPX0E0Ft_yNG8m_iRV
-ECl6u3nD_x6t_WRV-Dl_8s_yJV-nj_u6t_ZR_oDl_6tXlp6t_WRV-lBR_pj8wwO3u1m0CmSg-zy_ajcum0S03EFhQxZdzau007CR1o004Pcum3uPpOEG00p
6mSWW95PEG3RvgyTW6toDmv009dr0x0j_le1sDRXNpy0s-Al7u1jy7SCG04pywq2iBsRltu0jdNprm_0zlJh1s2tFVtw0LYCUBWnyyHMnTddPyxnh_QVzypt
3u3_iKDwZZ6-uCUOcVTVVzeW0FuFTy_E0V3_pDO1y5-z0-3VEm3-lGFWtpi0_WBWtpS0_WBWtpS0_WBWBm3-FGFWBm3-0k0l0Fxz0k0l0Fu2u2y0_WBWtoi0
_WBWBm3-0k0l0Fu2u2y0_Zq2u2y0_WBWBm3-0k0l0Fu2uDya0Fu2u2y0_WBWBm3-0k2_7y1SbSRV2S1V0Fm5m5y0_0N0Vp-0-weq_au0_WBWxoc0lm3u2u3_
VW1ZLHr_0V3V3s2zzFWBWBy0-0k0lm3u2u2_0FWBWBy0-0k0lm3u2u2_0FWBWBy0-0k0lm3u2-1O_6KD_2yE8FwoKl8Fry5_Fu1uk3hsZzV0VoE0-7QbzRzM
rV_v0SIniWN4YJNmFnr0d5Xf_QyLzxy-W16dLbh_Qs_llpRqInKG_tEhvguFO9Q-VX4x0GXWZihNBxOcW1oniUBy0fYnjzBy0fYbhrzSiiO1ZBXWLVa5CEAI
rUGNG5orYlm2YEjMZry0SUMgyGiWhbqjVW6Ck7YL-0KmulBnV-qzcJ_Ay0jWnZDMXLy0yPpLu1V0Y2UD_ullkVnHWLy0yRpnV_q0Hkth5riJmAXz_KOyTMEz
z5o_YCO7WEiNqJG0ru-_wtUBf--sNdQkNpn_8zzu8vu__lphyaVa6oz-OiNzPxxjPcj_Jm2Zjd_yp1p_colkFriV__o7uv__our__DGy_M-kkFzi-_JFdp__
uUcVVzNntv-__ksjD3___V5_ZV7dpvy_V_y1CFdpvy-Vl-T__lpvy-VFtty0yz-Ot_yLsU3Fdx_N__3dpz_hVulvVzJmv__X_H-lD-__yVu__jx_wmtW_7t-
Wyz_uE_pVmhv-_mld__5dt_h3u1r_V3x_EUdRdRszm7m8rC0Eol-y-Sn_Xkh_G162c1hnN_-_BMU_hu0RAO0jbRxEon6vau0lWFaLZlWp0e1-FxS7tdTn-WL
W2-07_dNtGLmRiL__imY0V1VF_IgFm6SMEq7C3C5K8N_sFNy0gZ3V-n7-7CAuBTM-m6CV3m1_CPgFu2PAO1g_CUkunT0FVvZL_4BO6Ub7y38Om8eoN_i0du1
RAtq8vYPEm4eeFG367bC0BNvZstT_09OjVMFZPzud-UwQ9__iKhNRzHEUAsD0Ehxxr-_5zlfdtuZWEh--zUlz0iRR-lOHW3L_VUltwlkHBeR0PJstxz-hxtR
gNBpv8hxxr-_6lkcs-q0wlllNx_wsm-Wlh_boV4N07y1y1S0Vm7m5m1_0V0N07y1y1T01ty13Fu2QEmlW7jlVm4aVm7m5q1NVm5C_au0_WBWBm3-0k0l0Fu2
u2y0_WBWBm3-0cZWBm3-0k0l0Fu2u2y0_WBWBu2w_ZRpvFWx0VWBWBy0-0k0lm3u2w2olztpvFWBWB-d0Fu2wEalWD7Rtzy1xhtz1P3y1V0-_ZRoxFWBWBy0
-FkFW9x-0k0l0Fu2QEil0Fu2wEml0Fu2-8A-PyunHXmROypCUmz_0Hp-EKVyOsDc0ty1n8Y76x7UUWAOyTrkgzHiG__1LgNPXdwV00GmuiHMeTdMpLy_0Dkw
-UiNO5lyzGEm4_pD0X10HFGDG00HZGCGm8WU0TWMV_q0x05_Mty1p8Z60GWWed400XYT_GKm8ne78828nW48OBRs5q1SjDigE07CYCO7W03YidsiSXF0Z6Xy
00XWTFQtZ6WSW4LFV-Dl_F6N3S3u6t_ZR_oDl_4t_iRV-1j_us_yZR_nD_x6t_XRGtxZR_oDl_NbD_xsqVlztzRxzhTRxyz_iSQtl_6tvlpMcD_uMtD-Qynl
_AqvlpNdj-RyrfpVclDRTtvhhc_T-QsvldNdjrlt5tjPzrlVHZpOM6td5FYZFJWG0000O1Y4S7_R2moXMWC000000000000000000000000000000000000u
}

