sprite $transfer_appliance [512x512/16z] {
xTsvbkCg58RHNcKjKCRxl-qDJz-EIhA4ZVwzunxhmnE36Ly9000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000-luNHfZz_mZFJtX-zDS_E3_wPz0V_T4V_VFeZ_xeZ_xeZ_ubRf3eNuAV9uR-qPk4z4z-gw1_Jtwlg7-F_h2WV_IdHVs7_lgd3W3z
X_xwfmq0_VNNNt_zX_xwwxyC_VNNNt_l__JNN__Msctzk_xpjFUO_pzlvVX5_xEMpb-s9TV_zU_jAfVstwVGlrteIFyoIcdwJx6rAntfNuRzln_JhdMeV_bG
VltRH_kNZ-JNlrtkOF-o1SJN_-7qRqVxyvpy-kk_HVVNlwtIN_yUtL__flzC-gC_-Z-H_YO0JF_fh_-H0K1_MF_Ksp-j_X_V0yRuh3lwhuFm_6JtPylEJtX-
mlCJdf_q_CZ_7YEWZro6m4W2000000000En_8pm_uVa9pu_--kVcfsVt9wi_-gC_-gC_utwlE_syrPzruvVp_LcvVld6_lh_lERvklxwlwPwjtyRe-k_NFxo
Hl-U-pInVFvojdzt__Fr_hpcEzV_ZhSA-hzMwH_-Nl41-Sk9_j4V5lIFlofamYV_YOxsRxVC5kZ_MgH_z7IH_jiZ-kjVZWKTvelNpw__SVhhh__GNt_zzTTV
V_rz_WleR_v7V_trrz_yh_NVuFxwM_-r_yl-ZxkiqT_-hxjiy_FR_tcSyn-PJ_xEVnNdFswopFbFvx-S_zwwyx_N-nFw_G_wbv-FjjVVzp_fhp_wep_wep_w
Cs9exVuVN0262m1n0IZZMW000000003GJXiPn3S4r3S2r3S2v3S0v3S0v3S0v2y3_TF8NmRwfv6_73e0Hbh__Hz4zT-_Xm7GsnrMoQz_-tX_z2UlF_gZF_ep
FaN_g-a_VjiV_T6VdFNV7VsVomhW5JU0Tltd-PR-JtYUq7-SxD-ZNoXopd_y_WVGzP-apyi_3lp_D_rdcL3_UF_HzN_S-Uz3_ttz9xgpVZdslzT_hWhvQ_KR
z3_31O2c2_NNFuJ-HN_zzU_H_VKV-dl-rp-1_aL__VNNN_y-IiOAeFxc__KlSGz__Qt_wryYy-jV8lFhNoBpwryoD__gNq8V_FgNWFZwep_wep_wetyE_T4V
_T4V_Hav-fv5Vqy0yXi0yfUzqCS000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020
_m
}

