sprite $artifact_registry [512x512/16z] {
xTrPbgCu443H7muAyU7U_sfx7fodMrqkbn61ujuLa7eXWSdffvi200000000000000000000000000000000Md5inUbVc_xwww__Neh-zh_--kklVsdwLw2_
_lf7dVxws__www-__lh7E_trZqNO_yx_cltr3_s7x7_zzRyl_VNNNt_zzTTVV_trrp_Ewwz_f6V_E_zhzjS_PlJNFvAQjV_j_sNgD_rhq__UzDT_kwQ__WjC
iFwrwNyd-kkll_xwwnzv-kiVizd_plz2_VNNNt_zzTypzzT_Fvdzx_olsL__k4T__UCCvqog_gUupJcbVstwvwE__lhhhx_-SU_--iUFQ51d-xi10EpjJ11V
q1O2003WvUjBjiRCRsuMUna0H7lY33YNnPtrepS0001UziQTFx1kRIQV-BsoyEEiUpBj1c21WzChOVLD082Zil8zJNqJu3791FZjPQ-3VcDh-2m8Pb20wBcq
UdgFTXNrC_JlOVFFNeL8O_2rLwlVgXfC_zdK7xagHDtDlxUBx0dqluMZlw3-9DGlP_P3S4z5_xdh4JqV_R-8MlKz_qsRW9vMrFskvxJrwCzCG2GnwQOOFIVl
VmUYH7qFWZCsHByB_RzOTlEFwVyibgq_fl-pMBk-2JZrkRZVq_IV_pwMt0_HRslkxt_qv6BT-e-HKFz9d7JqUmnOyqIClWBrdyIwzSVKVnAVh6y27ci-5lVL
sFnF5iu_Lhm-rUiJ9JxmSmn5yVfKF_gfNf_gzQbUd-hrAPuVzR_mGYYgVUAd-judAknzOcpjpGy07DyXUXa0mD5B0Xy5UW80000000000000000000000000
u2zs0a2aqDS70D3-pwLN5VELpPzhHQ9TnER_boFLLUa_VvsNhAz_UzrozVMFInVcCT3cq3_bqhJBgT_QDh18VltRknQeht_EzMavg7_9-w1eK-X_wHeT0z5U
jvrB_TC6u1XfYQZ_akDkDtxz8-L2jMJKVzbzwklV1gPy58Y1bf3w_sKVkC7Urx-TANb-_QETB75z_TiCbrwLd_yRszeabyxa_aas_uScu1ZOMshgtut-wkkl
lkU_l-mv-yoP0FrpxZRd_mtgexx-wkllJVzBSjxtutsrDp_gw-_m_vJG_u8JW1JtVnFW_3S1-fk0q7-QQ9L5-FvFg5-WlyS0vxy9q7yavI6h_pnxobki_lD4
odLJSvusITQheasG-Qfe9pjIF9oeVunSkj2FaJZpORJFuGX8ULMFFeMF0ZddiZDbhUzrLQIynSwhpvRo5ZklFZaNMlrvSYxqVVARW09NPGBsaTFUKctpwdFB
__-oZHo23iHGocqMqowAd0lT1cAeJs422boL2TX6-aIVhiynTEKwnv3wqqJAXPvtuoTIRZFrSznmNTMPW7c_eSdnkZu10EIu7n4z5pZwcm00000000000000
0000002YBupubXRHI_DlLQCNeBu9KB_C1D2-C0375s7pNpu1nFVxG7qJOE-R0FaDWFecGFrf4_3efw8D93e3E7x8XpU_0N3qcm3rJS33ZTyPOFDF6e2Z9wA-
2L3VJS2Dtm3O_2RWK7_Q1CJY4t1ysA1-pJF0qMy0r3S1ZtEedt02_79Kkr2qi_GNq7gqx4p0SPOsXmbmy9i0zTDC07khuj5VSKpMNn9dQGEE04T_ZGbGtmJ8
RmBYKW_rdG7gJt8Khu_yDm31uYzy0000000006A4LXWLyWF0_WVQgM1xHxGJ0Mp55NyfeN_-bwrtxQz__jVI-jUc_pt4lVhh7v-cl_E_J7_zzTTVV_trrrz_
_VNNNt_zzTTVV_trrpyozDS_hgE_yxzcV_trrrz__VNNVzF_FSiiNEW_it_aex_xV-d--k_dzzT_pqn_vt_P_lhhhx_--iUd--iVzwA_yxzcV_trrrz__VNN
Vtkll_xsl_wn1ls7xFyAz8_lwwz_BEVr_lh7YlHt_o_TN__uLd_zOstwE__rrrz__VNNN__LwA-__lhhhx_--WC0000000000000000000000000lm
}

