sprite $real [512x512/16z] {
xC410G0020AW2VrVM-aEO0e00000000000000000002ElJkvaHm6eY1wvItyztQEnAWMW40hAvNnlm4j1HzhzcNjsNA3_dc-tCY_pbMx8lzkrjpOxrbpWxyd
pOtzdZGt-7kot1NybybwW_ywMM_qNoRBNS5_cQmt-YzpzaP_pzaR_JrdR_JtPBah-jV9SbVqhrFsHd_FsHlzFLjm-AzJzaP_pzaR_JrRSFWlS_P6VyyM7FxB
RBqh_F_FrhkYVvajEFoNANl3lsVhNT6_p1RyDFxRdz0hcAhU_lnLJ-hHMtZB-lFNFkxdlTN7srgV-eV-ChZn6JzCmlLOUbw0txvJ_RFfd5j_0Hxxyx06pwiz
y5Ry3LwYoxFEr-S2FFf5oeB7dll3loCgl6OZZ_xnFn4fUiBG6z10lzPdmA-xFV3XROWASWjwcpwv_siD-OtN_lmz3wGoj_y5QA1VIrMGMzNRxudz3yJKs_uu
wb-mDBS_IE73wW-alhS-U01_uLkMvlPNANXE_O78UWNyKF_dC7bCi83_y6LRvFQ_05sFunw-jSRs2lWF0Glu6mKB-4y92_WR1GluJn4B-1i5bt_f_XUWWBzH
i83_5BA0lqzmWo_RzWAilRd10lvZpOVmrrizcF_u0bZ-tp47_w7e4_ZhkVB_CBxTqtij_E3-ZtVYZu3_DhByHsHJUptyi0wcwItuGe-x0AfU3p-u-A7E7rmN
O52kY1-6yHVO3JYFannXhk3ZVz3ZorNnWu3_iDRbZuaVxlU7CKSYhNNnWuaVxlK7qmKO6klw-0CYVhZJ7u6_85RsyGSHFzpd3vuBmEHO5_zhdQqr_dZuuHv_
nXnAKdKVVq333tVuC-XKKkhx-0CMVlXxVoQi0N_yUry09A5AVd1tnXz99d_hpvmbyxLrYVnnLFAN_eoQkpB-22AFK9VCdwF6-3DkoiRuxmaIYV-NpIqyPvNn
lqQZzbzAVyO7elG_FnxYR-G7Hz_dsVqPctSYkxp-hCK_zkxZM78WYA7WbJVux-rwy5Mj8f3bmKG-zWHbyw_aD_pvVpAx_WBWpx-Lt_0t_Cscl-5llgOxoi-V
F__svT_mlmn_mz_mNnp-CVmD_yhX_xJxc__Qt_0t_0r_mz_mD_mDVyFVy3Vy3N_3t_0t_0r_mzzu_iTu_i_mDzx_CFmDVyFVy3U-_uAV_xU7Ft_-0l3zHyFV
y1ySt_yMWFq_37_3tzZ_iM_uXpz__lpvs_zzAm3-_FcdrX__tLy0_0k7V_Wx_2i3CFpn7_mN0d3uMm3uyxVyJ_u1EFmj00v_2m1__lXx0Z3yyH_y1mDm-5i0
-Ay5WDy2uD_V0i2VFtu1y1y907_30c3k1x45mE4l08S_V_u2m9_dRG6OEvy50By5WBy0yETvLG3cBcS1m6y1iFfR01p-pW7nfq0V_yLjMXz_2lZnN-IczV4d
q_puiytFFzFw-9DfVlmfuCT_qPlcnvzC--DFfldnfu0V_qLlcXz_qi2FVzGV_rrlcXz_CisFFodmns_m6_m3W__l-Xlymy7XNrvpyFlNmQy0_7i1u7VcuUWN
07u1u1S0_YL_btq4W7_D7x-lXE7dZt_P7t-UrmQ0dpz-_lZvu-UFdpz-_lZvu-UFt_K__Ax_u-UFt_r__9x_mU_vF_oU_yNl-N_ytl_1x_q__Dx_zMsdTNwt
LiRrNLgbxzhADpUOpsq4aBUEJqexj_xABp35_AC1EBUsfuXpwo__3bF4RqyvrrRiAMaJPfUAfZTX_cxEfep_km6OAlv30FodpsS4C7qzGm2hrpDD2_zk06wO
Ncvdco9-0RYA9G3y0XZusJuLupR8yzLnLzVxJ0lpZXyl05V11E0gc00yrIy0NymGW2_c282_07mnJm3y1U2BkGBWBm3-0d0RL03y1S1V0Fm5m5y0_0N0Nm3y
1S1V0Dl-0i1_282_0FWt-GjWY5y0_0M0Nm3u1R3gBm3y0i3lBm2_0EYx45JrkmHW6nIt0cP01M1pIm7Ot580zhOKWBqj1V2K-ml0EPq0VDDP0BQs581hkWAm
jQa0R6qgWDLR-WBmJ8S0ff_f4i3CCvq2y4ot0BpK8m0lzGd0Izq2iAd9T02lY5G0-0M0Nm3u1O1V0FW5W5y0PVm2m2y0_0B0Bm3tfWI0Nm3u1O1V0FW5W5y0
-0M0Nm3u1O1V0FW5W5y0-0M0Nm3u1O1V0FW5W5y01Vm2m2y0_0B0Bm3y0i0l0Fm2m2y0_09msKy0tVm2M5xz1V2hFJee0020O00OOVtRge7T_O4bPm000000
00008W9q1G0000000EGF000000000000000000000000000000000000000C
}

