sprite $iot_edge [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000000000000000000000000000002OlJj8Rn09OYZi3vYYlTBzRplBMiqu91XrTJrTuPVLYG7S
8iCHNKoO0_xTUTlngS2mfeX-1lxd6t34H3dXVxW0CLdWlpMdYvy2Z2bYugS0xp57FFmKOCmI1py56FZF_Ly0_Z5jyBypp_9J0Fpn7zFxHpGk0FxHrHz__F6F
Q5m0_AEhF_xuun-T_V6Fhlxuuuz_TFR7Fxhwuuy__j7P7__ewey__lX7Pt_yuvdWV-3F1U19Ok377txy_S6V0XJZnnz-dW30ltvwy-F_Xj_hpm88VslWj_bJ
06K2VrlC-lYJMIJmjyHfx_Sd1llY_l2VQkmFlzJO7tyrzeV_5Fvy-flwuo_yuSSVVlnjmRzEuCSVVlpnnnz-_E777t_yuSSVVlpnntz_E4TSpR5VpkiN_luC
FPrjdvy_zbz5bzBo1mPtG_xvEd-cad_6p5z__JCb_SEiNt_zCrib_uoPl_xwPqhwXvc__lfdIle7_FdnVw80qQe0HuFrT_hx2y3wPrhwi_wPalwd-Dl_fhmg
-eTO_xjIqZ_uvkUsjF9d_Q-V0D6d08tMFwCC_dtMFzF0dwk-dwy4uTzh_JC5_G-xV_trpzJp3xj__VNFRENyJxz__VNFACFdlzNwPm7mxxZ-UGBWts_zCnB-
3TS_8_x_RxZ-cGt_ZkkVmR_A-bE0ixx_TFpxrlq6e9xhdy6_nFfJW57UVqh-VUlz14YDzMS0vFFthpy5EClxc_cldm0dT_zFiluCW7p-_lMd0BBu-zVVV0Be
N9vVhB_nGg2VNvElFmNGTyFwJtqlaBuTrd_Ysy6rn9jkuteCLLQXu7z_2GxyFsHk_enZ0F3tysTw5m1_oNW2uE_dbsm3WB-VdmBWB-C9WB-VNp8C0FvMVWg0
l_y4mD_Fxny0_4yVlxy0-4SO_7qd0Fv-Vly0uE_dznS0_p3usqy0_Fty_W70Fspy_WBW7p6N__5O0V0l_uWJ_ZpZqgOl-5E1QVWj1Q017VYbdGRW_q3mj_Bx
2_32tydlBy2cEi6V8s0AVWfWInD-2e3_KzdmD_2N703yfSO5mFzixO-_P2q0_cv-2k1DDVunChNzyV-zVSPH0Fpz-fcIjmBW_sVz3Fw_Jmtzz_ZVl1ye0Fuk
V6byp6G567-FIF9_paB-cLCP-0iLODmM2Vvw1HWt1luVPb7_0R-d07v_2l0U5_BMJrF4dmQCIrdM_u2_L076t0E0luhv3_Wh3S2Ol03uQo5_-3Cb_Fq5m5_u
kuA__s8G_YhcF-0lC03uuuy__lm1WF_K0u2_QlhZZp_--EEFF_xuuy__V_Zp_G_--5C0uOy_rtzd3lvy_Bd_2t_k_uIV-x_nv_aF-7d-2twU_-JvJvx_vkFF
-n_Gv_qlyFF-9_Xv_nlX_O-y_vNtlzRtv_tF_l3-T_pv_GVy-VqN_Fdz9_pv_JVydO7V6Nx_5NzpUllZ7xtvyO_b-BVM_lWB_qlfpOz_mEyA_lx37_zOX_yb
_2Si0EEFluaVVty1PjV7FvxYHnz_y3Ft6eqP2_209_wPsGfmFEgFltHCvVyqF_xIQIY0WH__Mq-1IVWF_6_mgUkl6uA_gm1-Vlpz1V2lF_ugwQ-xWl_XAO2V
7t__2U1VV_nLpbyVWh-X08tuyO-5rXz_sVmDbt7njnUWFZ_-OU8_T7_mby7VTnCF_lu2xCNvyOyRz0thZxzr0FO_HJspFv6uccD_EbFU9BsA_n5NypJ_DXL-
vXb_2j3m_JZfpmdGz_7udG7ux_K_MpmRHG7c_F1d7Fx-4m3-1mgmCm3RjEEVyVdx2y37F-Bq-VjF0FWZ3Fuz1c1pyliBi7SlW8hu3uE__mI0t_1uTAC1sF1l
NG3LyJzz_luJ0Fu8W__Y0x09_yu5a8H_tnD0jVp3uB_o06oIyEzR06NmxtS2A8D_lm7ObC6_Nm5Kpl_K5_BQUvu0KkFFFmEm6Vov031F0PJ1lzy9e0p-_GPW
mzy-0Cu2oE3F7O3Jd03gxCy9y3BuymZ8F2U0AlgVkYUS02hfho_cw7G2gAS_9u3Vty_F2I2Vlv-V_m5ay_VpyotGffB-UYJhdm3wSHRKvqgmIlhhmMphdW2w
bAM-zU5vW9TKq7-eGwQSn5a7MXG0Vmg0FoS0_Wm0_XG0Vqu0_1a0_2a0_fm0-3C0-5C0_3a1yAS0-5E0HVtn3_mfG6T_2d2szCS_qzIV0cIQ-LE0-o7m7vxS
u6yD-7Sse8y__9dA1O3_Xk1lp7lyFXIWzwUV0i1_J_2lniy0u4y1UlBZZpzV0k1F0LGwHsj__CUS_khjZx_w-kEFF_xgxO-_-lhZZp_-wksFl_hwuuy__khj
Zx_w-kEFF_xgpO-_-lhZZp_-wksFlphmKm3yyN-y0F1hVdu9V_nNvwS0SXG0__Vy_1Bytqi1VcbjVWfmwaEMvgS0Kh42d5ee1VYbLJ_y540_p8hyDE2jd-TS
J9yAw6hiv_w_xS6n00000C0WV-j9xAns000000000000000000000000000000000000000000000000000000001
}

