sprite $cloud_dns [512x512/16z] {
xTor5SH044H1iUHj_jcUVoI6cLS_X2w_omEI94cI94cI94cI94cI94cI94cI94cI94cI94cI94cIrAQiprZ7Vsb3nlhK_lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lphvMNqvryjZZz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lv_ryUVFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VF_y-
PPzwcbPKLYN-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-_b-xhmtVwgF7t_zpMd_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-TRKu_clZ
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
ptzv_Ft_ykVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvHuy_V_xy-VFdpvy_
V_xy-VFdpvy_V_xzYls2rttgQLfH4N_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5tzTUrLRn5_y
nL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_yOpN4gJk3lnlY5CkVFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_d_5N_p5N_p5N_p5N_p5Fs_ynL_ynL_ynL_ynL_ynL_ynL-I94cI94cI94cI94cI
94cI94cI94cI94cI94cI94cINW
}

