sprite $datapol [512x512/16z] {
xD4n0G0m40An0G7rxxOcVhj40S2h0W00000000000000000000000000TYJTnVrhT_7_qbtSltON_q-Npzvv83qFh43GfM53HT__j2_dpAlFFtZeli7G2rfR
AscqVeaiNyPZL3FXlxfc6fq5_PgT1VyQdGNzcfq5_ngT1VsIKPO7_NbcPy6_HcT1lsPdmRz6Pq6_mYZBw-t9In-a_KqC1e0-okWiwDViBFZNw2per-mi-DVe
BEXN66KHXxxoaAKj-YMCpe9-pSw2VutEWduzBRFWtwTehyPPq2yPPNdGdsTs5lnhT1RqQtOM_6jq5lJhCShouj1NdaRw6G0gO7GMz6js5lpl-n525Q0_JTnF
S9G7_pu385G3-lES--DiLS6XhpIhmVJ7l-Gp09RgG7-QQDB--FVO0eOgGN-QAD_yuTzd08HgGN-UOzF-qeF-mj-0H-NWlt00BDM3_ZHHtFxuzzW2XZg0_g8h
m5OBNXpwAja2db0FQF-I0R3K1VIdYShD7_xhsJxjBw4_JHIqF_vz1a1eyWAW_pVwkVxZd_q_-ldzdu8_W4nk0GVwq_IT_das-hd_Xt_k_wEVypzbyEmNv_yO
09p_PG5m_lzNm_C_1_rvLCanUVmN__Kl0E3vNvx_t_ZF8_cy02Y-HZ_-ey7hlz3F-x_mNyFiB2m0il3-Pzx_Y_-9xtzd0OpEWd-oyFqVilJXCIfPeBzvquHH
5Zu0ccTq5loJXUz_Zys2_zbPM02Zix00oD8LfrSaehzfqKPdmV_iB2m0ihJ6g6GF-lCu_LcE_dP56vq5_xEpi038qfyRFYLJ6lJVOrGpJdta_Tzbr3AqVrh_
FKObGt-AVN_FDgeP_ZFSFn8-9Sj5GV-d1a1yp-zP_DymAfcoeFyUevAX_tyaxbzPHZLJ4jh_tXC-9LCMzD-xZMgcDFY_OLGoPK7_FKPVHKT_tlzTHZN3Vrh_
FKObG_z_uTn_vkn_ozVL3F__cPlZs-C2-W7_W7uuS_m3xG_e1_m3-k7S5ESDj3-W7_0Fw0Vy0_hTGN-yWVO7z0F-0VrZu8___GRQ7z0F-0Vq6u1-_rCVGFi3
-W7_W7w8xzty0UqFw0Vy0_e1_u1-qFz8_6TMvMy_tjPM_xNZasZ_xbb4-wU9XFxkMVH2VvfTxLy_2Fxp79lsbuJ-DCjWyuV_7nW03bc4_ZHXf5_e_t-tW5E_
reV_y6b_wK5_cktJ_XB-yvphaqNeJxECiWZ_oZCw2_fbbONxVdbyz4kql_ACpe9-pSw2VutEWdwHfJal-HGjz5be_poFKHRqAy_iBFYNKPP0VvxPMV2lqLdG
Bwii_F6VXomzqQ_2ACiB_NbcPy6_HcT1lyZI3_aKxTKx2_hrCig2VkMPdGN_CieIwCypEml-DJeB-ZKx2_vb54NeJnFt8opyPmcLiEy7EAg1zizpEhG_2q1L
h1xjZt-V0H0g0_trMy2jEdZWftuB62g4zgyU04kLeBzu2tXK2_vhju1BnQ0_pQfjV_px381GEUYlsm9krSCV_sM_0OywGFjNNG6MEl2WFytoQNy9_pK38DG4
zAU9kiqV_ZssWA4se3zD-BI_XFvVFW2EEe7_D6kqVnR0AVdnZt-NVm3ERFty_blepwCcxCd__-0_xW-mP-ld_azyft_yhz7tVpd_SSfE__4soAV5vizd073-
h_09W3rRF-U_0_yy_u7-71xjNxy5n7_zyvy7_Jp_ZNxU_u1_tl-2Vjx_rDa__g-HVzx_c8VtV_B-rwd-yKyMtly-DWl-oT8AfmVbEVMHvp5gcUYUXG505hx_
E3OB_id2zv_7Pi7_w2miWDbPM02Zi-1_TXOMmEWi-2TBOvpUa8l-ZaKpkgM1_popix00HcV1FrdQurGpJdtaUOnQXlPlLRJPMLW0exFWVtGM5i3ZamN_ULPD
bcYXdmKGzvPbGNzzqSwzBbdmdsVTwpC0tlvyv2s_no8B_lFiUtq6m7i2Fxtvyra0xnbyv4rF1bdmdsRTMxi0q5zQj7Dj5W3-y-nhvFyzXy-yvRTpblof3xX9
tdF1Fmk01H1MwI6c3G3W2W1i0O4100m0sDCM07050Au0m0001W0S5a061i1v0rS0O0i8301W2mXi0O4h0B0510O0C020my0kS1Zux7zaIShZz7ZSe05mZ6ec
_ASNm38gch8m08vHpPI60H16HLCM1i3M3n8--lNCM00XcwPH6gu0swXeOW5aRmGVevef3GDW6HLDMTW27lquZuz-lTmNGCYcQLxAmXLWowTeoi8Lu8HFpPI6
0R0cVr6A0N16Vr2E0R3cVL6I1H2vzkUBik4w06Bo1wMv0kp9NvHd2tYCQgOq381bL3HbuJxWqOTvTTRF00YVehsKXGMmvLCqPU4es0aV_qh30D0lONGMz6js
5lnhT1RqIqPPNlZFOnH5w5UUqLdGhzbPyA_HMT2lbr4M_2lFw2pebnfbuIZOO-HVQHW0Ac1q5lHhTXRyx_iHGXMWFqtSJt2K1_y-0o1K0_hpdFlZR1Nne3_D
wZlzy-2_mG1OgWFzQQ99--FVOmiOgWJznGDWgvGN_cktWA5Qq5-w1Log1lrfLkdc3_y-0s2f7lIdYVBsnx_3Ry1G1z1VT0NOQa5mwAja2tZK1Dg_P00iTG7z
QQAi_V7liGKCzG7zQQ9WyuT_dm4Gchm0wF-3_Zpgm_7P_kC_psB_p-z_antWmnz09JS0WlPF8_dS0DopzNF_R-6V-__ev_mF_XCOdV-xyNNwyH-rn_zv043o
U028y_yy_tFGdqULdEh7V_7_k3pznVE_FF-_EVcRH_9v0L1yJVlZFngy_WlzlFyB_pMGfGjEDPjzweDt9Z-qVnwdba4_tt_edWN_PE7xFsHfX579qC_t_pZr
qRbeexFWdony_tji5aw2ZCx208ZHMLW0exFWVtOM5i3eBFWdIsUSQiQfZuP58qjldFuiHt-xeetEWl_PMLW0PFa2Z4hse3-Fq--bHXjP5i3eBFYVdOK5G9Pl
uJ4gcT2VnwbcdFfeKRJHMV0_EmiBO7GM_3jjPzyZSDemSUgZk6YZi-1_TXOMmEWi-9-TXGL0bj-s1yS2000008FyhMUngze1000000000000000000000000
0001
}

