sprite $text [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000000000000000002ONVj6S239eIZeS97mSF_RhZLQTLLZ11BnR7hnMVfD-VDgKJhv
ktrgOV2N7WWSzHq5uFzUfovCd_nwTLlAJ0EWRm7u3O2-1U0t0Fm6WDy0y1i0VWF0Rm3uxnY0pcf_vOCC0By1uFT507y70Fop1w33tz_V5G1-1m3-omQWizfV
sT-dfiRV0G0_V_vE0FmT05pzy_Vtvy__sQ-ZReh_uxtKZU6lkibVBp0lyjSRoplynL-lAD_xYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_uYx_u
Yx_uYx_uYt_yj_gRw2RwyszM6-VFlvliQd_-aN_ThVxyyulTwC__vDUxpfz_FkfSvSy_7tUHF_zyqRd4d__9TrtXppzVTu4___n6u_tvvxSQxiy_lzbeV_xv
xGRxyy-6nlhppvQ6-lEFx6ccF_ziwZFHdt-sDT2V_yc-vldppyt-_BErtVxypon__jdSRd_-Pv8__snlY3z__lppRsYlFt_-_7EAF__apvy_V_xy-vhXpp_N
-ek_dedUvg-ddkSgVptMFEly-R_vLd22lzvOtkElLvHh_FdpvtzM-_ElIVxYB_xYB_xYB_xYB_xYB_xYB_xpuo_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-y-Cl
_k8l_k8l_k8l_k8l_k8l_k8l_kBVNinhjp__sEtFFtRxyu_T_lnZjp__sEtFFtRxyu_T_lnZjp__sEtFFtRxyu_T_lnZjp__sEtFFtRxyu_T_lnZjp__sEtF
F-RxvrVY_qVjzkSVk_tvnsv__h7Rdt_izkSVk_tvnsv__h7Rdt_izkSVk_tvnsv__h7Rdt_izkSVk_tvnsv__h7Rdt_m5t_n5t_nlo3-uY_-uY_-uY_-uY_-
uY_-uY_-uY_-uZy__k8l_k8l_k8l_k8l_k8l_k8l_k8l_k8_F_xYB_xYB_xYB_xYFoZ-Pwq_V_xya__J-9_Q7F-w9lxfyFzZ_Cyz_lmhlzHvmFyt-lylBcYY
V-QBt_SN_V5_81gP2_tvFw_wuy-_E_x5lpt-dzN-_6kAF__Ytnp_ckFF_xFQdtzbTsUrF_-QvC-_-3V6lsRvywzU_cd-_3-h_VbN9_yyV_wLNPs9_lmhcwhD
_lnhfZ__wk6Vwi-_ElZd-lEl_6vdiZ__oczMe_tvLmF_O7_-bU_xr7X__fLlgxh0dt-T1lwv_loh6lW7-_El1lt1_lmh6lZd-lElEWtwS_tvLpNe3_RdN_Lf
rX_Yp_-d7Ztjd-_F_xTz7kBFz-V_s_heDT1V_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CLV_CN_UVnpbRy17FuE05VwAvzZvZP__hcJ
d_zlFNEDF__VYcPUvQ-J3StrL_ujdTeS_reV__-tQyS60C0G402xx3zobaY0kn7mNy41000000000000000_7TjN0TRl07nxkW3XTm6sxm9itmbiXELJiVK1
000000000000000000000000000000000000000000000000080B
}

