sprite $vmware_engine [512x512/16z] {
xD4X0G00308mU_V-RL5O4cmLzXC0000000000000000000000000001SuTz_sAC30W0048HX_LiRGuNHuEp2-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xyZR_nvy-VFt_-_Fdpvy-VFt_-_3NoryXV8t-D_3NoryXV8_-Bu-yR_hxXxnl-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_FbhvA-HlqR-6lbhvA-HlqRVQFIDHjyCUtUEth2E1M4qqIVSJFlVRQVzneW55XxElm4PFEMPj6TtP_dpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V_wJZpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VU__Vpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
dpz__lpvy-VFdpz__lpvy-VFdpz__lppHlduy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-TVPPIFFt_-_Fdpvy-VVoJ-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V_--FNU7FVsKl1l_M7g2lzUVlVxJovp_f-FFdpvy_
V_xy-VFdpvy_V_xy-VEt0Fu6mDy2-5i0VmFWRm7ywrgFlDc7-VDVyo-jm0BujnGw1Fyt_CD8Apa0_bkB7wRNd_ztotdux_NVvx8oByG_tzP3bVdpttsi9d_-
yt3Vm4loJpM1Lk1L-ITwxN1V_k_tvl4-_5_ky-u1F_nVxVKJyd-nLN16_e6wpl_v_Llyt-dJSipB_TsGVRc_HtBuxwxigFotrdTM_XihFEpYlwtAq_Alvi__
9A3NtnCuMsuBQFR7dxyhO3NxuyyFeDeVV_vJGBK__ln7W6P__7cTLUsFFyxJxOy_xiC_rLHrgZ__iD0L_lXddUgFFqlKxuy_QVGzm9z_48b_5R-7N_3pFxdr
9Dbn0-3_ADXf0-2_7kRYVrPFQXqt0Fu1A_xdj09Kvmo0Vm3gd07mJp7TvSy_DwnrWZ_-t03ur_j7jxNg_V571y2_spyzhyK_qocFRFBFDEa1VFWNzvc7MYSE
WFzCxm3uvvkR1y1_fdS0_FDDyG3uvni3UCWVVs00_BCr_-ac_ldcvW7mt_pd6nV_hgPu0FppZG4yvey_C03-oQPu0FppJS40klpvvmVmRHa0_u81yA_cZr1z
-JSqnGFWdsyA1b3lpxz_05CG_y00-0TRqpi0_ldUlYu5_lnB1y0_tnGFW7--WajJvi-_Vm1V_flzoxu9sUtFFzgwsf__RvNxy-yQmEwVPF5Fjwv-_-V_MrVx
y_-jgp_-y_-jg_tv_zRL_ln_w-hF__pdPd_-Lt_-vt_rzt_yvsP__dEpF_zfzkVVnV_vR_dpl_h-B_vpiR_x_tx3t_sV_Dze7SVFtmD01Vpyy_pyytdyZx_7
V_bNylFFrypFFzzv_9Cy1Vz-VluFLitFFrypF_zypVpvgwmt-5SDlwhvy_vgvi_xQpV_LF6hcZ_lhvFu5wx7EuX_Q3tVQkRF--iS_WKhq37ymohI7lvLwg-x
-RMQ-VF-olDFCRzMdB_QNoVmBqo7-jznUuq1HFa_a8Ajt01EkBjE2IJy1Z1d-Ejn9_m6CCVuQpr5XTzFWV4RmDpfpt_m6y3L_0Om_DqBV1g_BkSN_g8CO07P
dNT__XVpwt9-hRlvTJc_BkVNvVowd5-Ny-joVbtEh-_b_CA_EGFu_g-zEpW028YXA0Z8CVrtgmbW_qmBRmD0VmYLFVoavoSyF-dr2S-F-dUo0hR6h-8-ZVAC
jnLWzgs0vFgaroUzFfKUd_ZuL7nydEjZxhiPUEe1000000000000000000000000003W1
}

