sprite $datalab [512x512/16z] {
xDq5aWGX44N1a0weqBh_QTVTTtpucLTu1QFGlHS00000000000000000000000000000cFMYCwcVEGBKPnr4VWCWlm7mqcy0B7y38F-ZsQjZgn_qwgYVZ4wc
V_NQcFfR_h7zqLz_dm3r3ze0iF-ZF_gJsn_z2S-F_le7voUyF-7v2SzFU7xIV_WZlZvhnmS0000000008EplWRWY75T4CnEF2E68CAu8aTy0o6y0v3S0yXi0
_VMNtm1uE803mvR_iqR_KF8R0FtH7_tZoEyJeFxLvuV-w8_-w8_-w8_lVz0V_T4V__zGLd-hElt_l_RqfFxKPyFv3mzwrD-3NaFFVyfV8-7yDxiLN2G_kpPS
8Z_RpX7dslaj_zq7OEjrwU_-H_sVnP_uS8lVcajVVujP_-hbe3_sVtoBnvRTdzp-w4zuViBx4vmV_GdFJtX-qlCJNfyHNv-ZnWS000000000000000000000
PftHxFEYpgpZoB_x0A0_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-gC_-fEU7_MVSS1Gadz7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7V_H7
V_H7V_I_PUyEacC7WHWCRroqTxx_RRFFZaeebwol3_32l5yIz0o0ml-5mZz700f_XJ_y1_Z7240D_kn_W7-o0E377_yvfQRyOl_zVsyz1OL_KW30Vu1_Z03K
RD0I0Eml0E0l203yDve_0S3-WG9Gro5Egu0_-mi0-2q1yHS0y1zeB19BxoS0s9y0u7-cXJ_-0W1-FI3-0W1-FI3-0W1-0e3_kIhuuoy0uD__KnSI0Vnz2mX_
nGnWn__l4re2WFq50FnwGFm50Fpt_zSWaiD_3WW0aQ3qlxC5eEQFMLp0d_q50Fm207y10ByU47y107--0E3VtejX2SZ-0W3-ym9O-0Jm5m3mHmf0hQt_VBy3
ih-T87e_Uq7PNm30Jm3uum__nmHWqnV-x4y0y0ViG0qe_0K0_0GGySG7_knVFIJu1t_sDoZuXHB-XWL_ny3Wnnz_GzFxrMv8mz_Wu7-pLh00y1S0y1E0tWz_
zYS0zc-x58ZztGa2lnFXTlmB0FON07g_0_ml90Fi7tKd2Fphs5-DwW7Ptn8GVZE0tay0iByUKEz70Enl1h3dKm2mlm20NmzeyMSd4FiREFldtmg6lw7h_OpT
4ny2GFeRliMV6O3zVG2BFm76_Zw21xwyKs7Jbm2G_Zw6tiyYblrza6_QnYVnn8S0aFuQ6Ok_Ewm6xLtxn_4N0EnF0EoFF_iV503yWx_q9m3fhmTaVm70_Zq2
OF-fvkztlnpQ123zNGnhyIS0s9y0s1z_zhy9O5Bmuw_tMztd0QN_qoq0Yx_YlQ3iBm3qVW4xszbV04JKfFtk9m1yzJEz0G2_6S0N_nFG0x9_T03Wlt5Gt1AG
_GL0N1t0Nn407dSEsBXd2MZBzqRXlzFxDVF7__umV_pnnt_mvt_yySSVV_pr__ZZh_zFAm40lm30dm3WtwU8_qu90FW5WAiW1K23_GN0rOtVQw_ucm7WjmJ4
Nm0quXS0Wxy0WD_zVutu7GJ2tmm0lnuGVm40lnuGVm40lnwm1xzBuF4t0y2l1yHV09JY5m0BVm40lnuGVZqW_cO0-FM03lm80FPt70X_Iq3uzO0Vm6y6c1R-
1B2lW0By-BliWG0AztpYp_u4mFvwGFW50Fu403_-5dy4mFxuipy1iByU47u1W3y1m8y__WG0F_vwFm9WVpqW_080VmA0dm3W9m1BVmfWVWf0_wSzE1O00000
6EHlFOcTrGy00000000000000000000000000008
}

