sprite $home [512x512/16z] {
xDYt0GCX54H1kOLG_NUh3kJEVfY9BzjtZcSj0000000000000Aa100000000002uV7dPc4W4O7u1c5y0vfye07f-r4T28W3p2y3y0Z3_H07moDyUzP48mFm2
CBy0p2y0yml0_0AmVcq0002qRABLG280wmFU_Lu1dlu2CBy0h0y0-F4RvIEG0E3Txnl0ory0rWS0002S-XK-228V003WozzVW2z_06WlTkp207PS2uBeXssL
d7_0oqppSAwjhaxXb47QUwLtybzNTG3oLmSWVtK0yXk0_Aq1o6y0yXk0_9K1o6y0yXk0_0OWlm78VrtazCb__VE0r4x-3R1IE_ch0v3V0EHl3K1-0v3V0EHl
2q3-2mn0VWEGtm3aRmf0_eq1oDyPWFmBUWEGdz0SWFoXEG3vGsi0ykyaeJa0-KDp0FA7oW3altvMfJa0-KDp0FA7vW3a3yq1o1_g0f2VlF1l2K3-q1o0_A4h
0FbtNlWN1I1_Q0v0_b0KWFpNUk7V5O3yeJa0-KDp0FA7vW3a3oK1o4zU-FS587ze3a3-q120_3il_2i3a3yq1o1_E3u0-Q_rmhyr0Fb3Sm3oX-O0v0_D0SWV
ZWv0VlB2lpa0-KDp0FA7SmEGV-VbQ0v0_j0SWFpXq03alzOR_AS2S7mH_j0SWFoXEG3vGtC0yeS30v2VVEXe3a3-q1o0_E6q0EJV-OZH783yeJa0-SDH0SX_
VQG0pG787ve3a3yq1o1_Q0v0_d1C0FAJZn_D0SWVcWEGFvmHWFmxD_8tWFyyWpyy8u3_F6nFuGy7123_jGRydn-0_E6a0EIVzpS07iGV7XG0ZzZR-SbdZEO0
v0_D0SWVlkGCu9k7yOU71V3DhVTs_fq1_sC2a3yq1o1_U6m0ybzhmF-a0EGFpG787mu8GFvXVmF8s_d9i_nPSRVZ3yq1o1yU683yEmF-vmKWVsWEGFxmk03a
NxVnDu2LBxbzVS1M1lnl6i0QtY3_lBy1vEdyOIu0DyyVdXI0ttvoW3ySyGauWJy0jVy0yWS3UColtyun_X1t0_xG783yuI41oB_6_ES3yE1thTp4tsDWpk4F
eukRvG_D0SWVxX-0ttvo4t__0GRvv_qD88VnXvi7uBT_Py2_8m3vGtC0yeTR1o3_gl17_h_VIeS_UJ7v9_qDOCtnp_jx3p38F-zl09dW9rt-f60tum_D0SWV
RXc0_3l3_lC1o3_lRm1hZd_UtrD0HlXNhp--_A-LOdyY_td-1h06-9_fZ_pT_XJp4_sXcrz_kldrfv9_H_zVrislFzty-jF6l_J_uwhuhp_pwqytl_vqy-jF
Dx_-h0f-Sfo_Ru1rVJw__dJpwyywd7z7_v40v0_D0SWV362OV-a_5i0y_xMY_rG0yeVc0EGFpG787mnWZf_eFnc0_A4v0Fc30Gpnx-W_783yeJa0-OC1JF1V
I__v0EGFpG787ve3a3yq1o1_C81tynFzxn60_A4v0Fc30RoLVqV_smGWVsWEGFvW0E_ZlvR-NtHB_b5_0s2INtyUvBzodh_-e_pwynH_Sg2_0J3Chp_3_iFy
-dD__vqp_Gs0UNxzkRV_pc7-1h1-6NSu-UdFoipsBVZrPz9_dbz_9ltd-VNdbluhP_aRmFh3NlYJe_tz2TptuTUVIVzvVlsvbV_EwVu6i0VuX_mDOFrr-rxy
-hFUml_QVnNuUmhOT-FNdqd_UNxzcVTVEShV0DO_RD-GNt_M6_Z_sP-K-FiJk0Vvv_tTVi7Vvg__Jh6__Zl5_lhlDFlhlwhytGl-Ad_zLzgcVpE__kNy-lys
KZVzk_drB-VN_-VjD4x_Rdxzo_a3eF_IltJT_Ffty-lVpQz_ER_-HF_cHN_vzV-kFJeG0000003oVss41V______________________________________
________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________
__________________________________________________________________________zVLLLLLLLLLGK
}

