sprite $automl_natural_language [512x512/16z] {
xTq7ZhDO48LH1KILOkr_j_Cc_PrpvDrpTj3wkBInmPvF10000000000000000000000000000000000000000000000000000000G5_Fe7ya-Hq0ydTDAFsT
0EHV1lqpoUy0qF-ONF8lyq5KEm3CNt_vqmu0z9S_-03WwElnCO3vEm6uzdC0cB_-yY-3_b7aTm1uyUS0C7_zvLy6_KF9lmpw1v7V0U3Qp-U0vky48B_-ve_v
O_w1v3y6Pt-S_J5_p3-6_3Mlmn4zVpBouyKVve_vO_wuzkFCc3_E_dZnX_bZ_fW_lQDpNeUAdZyP-V7Y3_F7_35_FF13HI-EZFp8Z_x8ZnT_c3z1TzbY_iYF
_iXFxzeVyyVyCN_aHt_an-T-c3-9TzbY_iZFSTN-c3zk-iByaH_zaHzl_6F-kFR3_94V_P4VrtwOF_j_hJxcZ_peZ_nusXlpfxxqWH_C7_dnm0_cZsk_WD_t
Cd_zvTTVV_tb_vNzEVN_3EQllmT-z3T__UNNNt_zvT--VtVmNH_wLtUPVqzg_rxahzJ-_G_prr_-mFxzd-p--fVyYVtxZ-HhlqhjNtt3_FFwzor-uIUkVzzX
_lhB7zI_xyb-u4V_Cl-a_lr0-1l_FZStV_rJyyk_wAz_Qdxvb_2dlNrRHl3ypN-9dh_yNT7prx-Jyyk_PFVN_mZEB_yI_i2FRyi8w6_-pqWu_vVyJmkuySFy
Kqy0yZi0IlzddHltDtyd0B-HadeDQFvE07DRqls_tUa7WFxwJsh_RWU0_gzLc_QVrFwzE05KQl_gjzgo_wJsxyK9O5BxTwSV0FhhFwdzkuCF0FshRmHV0qvg
_-xW4u3-_K3avu2JtDy9O5BxTpi0z7-VOvl-azg_E_W4e7z_a3lQhj_V2U18xT-zE00ckR_-azg_sm6W_yUSdcYyQlzUd00gjN_rZU1hm4djt-q4u7cl3pkk
-NVg_qbyevtyL_jBzJ_qD_zFSEs_jUGFw7y6pz_yb-JyyY_wwv-QN_v5_rjAV_F_1DV-cy_9uUTnZ-3vc_-Id5_-9Rk__XMSN_ubkx-VIAha_EP_-sy_v4_y
aOpa-Pl_pLy_juNS_ol_qgs__XFPN_ubiRyNVpS-8R_-Ss7Tazg_GXxuULvaV_E_iM5_-VNtm8_-vg-_Qp_zpLz_-VNNNt_vzJzJ--jl_lgt_lhlc5z_-VNN
Nt_vzVV0Z_xchx_F_VGtV_tb9_7iZ_dZsezhv4T-z4T-_C8Fvezl-iByaH_zaHzt_6F-c3_cZ_peZ_ouwGlpfxV_bcVC7_bnqnVcZvk-C7zgd_oOF_BZZN_C
7zT-c3_oep_ouuv_p9_-9EUy3jKxcbT2Vlc3-cF-c3_cJ-_e69pzSVRFuwsVccTX_lZlpv6H7sT_dFqnVymVywUJt_hXt7h-EFlZnH_cZ_bZ_hZsmmC_fEN7
Yp_C7_FdpCvF-0C_PC-VyFnazoSyFzbl_7Dapv_m_6Jt9pm_sVq9pqzuVxBp4vwVxFw4voUxFvMTd_3F_SYUF-7voUvFU7woN_nHsVCdF3_P_GdFJs9_0000
00000000000000000000000000000000000000000000000000000Fu2
}

