sprite $certificate_authority_service [512x512/16z] {
xDd70G913CLGikVc_gibPwxa_zI2DBONEfcneuDXVqTrBkpd3G4inexC0b1ZXm8C_XqAODyfo7x24B3samlmz1N0lWJOLm3v2c1V0Kx-l_z5mDit13nz1R2l
08DV0Umx1Tat1Anz1NZw2c3V8S2-8K2-0jXN0FiE0VOLu6jV0Pw-Gu1z1R1l3R1l23Zw5E3fAu1zXm3xXe2rhm1FNm7iFxBgFuPzfw2rhm3s7GBiAy3Qbm3x
2Z3u5U3fAu1ztuFi6mBMlW8yVGMmxyyXzX-705OZbaQDQDXFPv6-zf5k7-doaMuVwVPHwVQH_hs7zAUFTFjOfTj7-byyyFHVJ9s9AO3zsh1p7rWIgpeKHIK1
2lCVyC_nnMeZL83l7a6jFZHW74PlJOJf_p6Bj3xKRhqvXFewcj2VuzQ7OHB8q7qJDXhJZqXNmmYOialxBlGCDprw1A2-QMEQ8jtE706eRwDH1kvstCqXr9-8
l-qGm2sU3rcdR39E6G7urnTQejls8m3rhJCj8xht983wZHx0CZ1FzwoVZp42VirthOyHWFhvMBUwEOJwtgcMw3vdGhZ5eqpbck5WsBTWGbynV0ilh--TlaNC
j_3c-ihqHTttO2-jxvs-YzKtySQtU8pfwxg_R0JuDWRjGCntyQhw9hI9uVjuJNzbsaP7_sg3TYA6_gKQxOKL_L-mzECq49TzNzu4eB_IdXhwLnYqAp7qhyYF
0R1ZV-GdOaF_fJhjZGtzY_DZ0DJtH_xw0O3-Wqx0Xlvb-J40wliZV_rb8FehdKFGFvlHIJhwvpAcempqJoLq64N_H8sEO-YVPj1vsD0_YTA96lhdCAOZTVHF
8NGeHVy4dKx5XlxJbCxLq7yQqy46-azgT3H3_obAPnFqdy9qk87-4peTpz3_CQFpDVH_JEW2YluF3Re1e_ypndI5WVwxRVwuTLKrymWpKnrDQ1tqVy9MfLUF
t-BMPPyRWUZVA5yR7d_4jVCMru3ehvHDXiS7h6rm3OZ-GhcwnwTSvSiJ0FehPUBXyICcbAa5-l-C5DGlN0OiqFydj63chvm3MWJwV-NVNpmU6vJ68j2__jgV
DMPueoGz8j2_-jg_UKnIIkBeN_xlFsAUSTvlGV_Aat-sc92z1d141Ff_X0isVkNRGFrm0A2_5kIltmH8_1twr-p-McGoIk3eNxRxwv7BEEiteN_1xgz7DalQ
0KQW__BTNujybhG3Z43_nTE_n0gQDYpHV-dqBnwR3e3u5_HVEFspnoAT9Ydwhv_-DPQHh7q9-Y-R_dkiuraBGA3_eZl_4YifpR7uD_HVC_rxBDNJ9YVqN_7E
tuYrdDDc9_JFF_kNM4rfYgF_ogi_Y-KaxU84_REN_nRh9Vv2z4zU_ZqAT9h0yR_GFtNvxr714uSe-cSk_nubUkBf9FhdBVyzQZXDwEY_QldtAD8Ihr3HF-lm
lqKLemdn2-YVTFXlKKOoPodqJzd-STGPgRUdqVy_wBaUTP9_9_h_YvPF__Kxm8R-AxR_4fKqTvr2_-djVuyuP068tu3-iwU_5gKa-PW2_ISl_w9Mpnwfw3zr
-ITHozAVJtP7VtfiHAtyd-heRsNB_pn9twcYlz9Z7iLQ_dqAzAUdEAgD1LkLj_UV-PjMMp9MNzw_JyofrNn5_q3_PqQKeyVGF_tuJwCSh-WVz_T7VyyU0EXl
KKxMz8ztzqV_GF-VyoYtxiU-jh-yex-XF_h_aSlxO_vF7W3eRtVrZwlxO_-VF03GNq_g7v-uip_E_z0Vzt-o1m3wzwZcg_l7pltn_8UjVrRfqlvu_kjJwF-n
g5RohDAs_V7yTwEd-ldzyVv7S4N_GFzD7m2reg6Az__st00EAZghmlk_Mzu1h7jJ7Tz_s743m7MNAlZ-otuR0AC5AnNwAnso0FJAWVgU_aQ7B01S-g4YVFzl
iri0MZnEyVtNlHQ0LlsTmhVqRqSi04xbmnJVVz_e26WiMgRGt-Y42O2f_Zhr7VsT3fW0nbS6wJlw2qtG_V_zoUAfL_Jl-qy0IZFYkJVqLzfz1-1C4oGclA2_
qmpsMAwl7A7eBpIZnsfEKonclA1_foaMYmbzSuToVt-ZARBrvezQJBg-lpDjl08upT6OTNt_HXkl049pFARTtb-9jhq6wBHwTK9_fqbIklZNdq_Sth_Hf5vw
ybF_YCBb_PLcZKtpI-IukxyppTB8vxBFkBoxVwDf5kc4fdbakRg_qeO3eD6q5kYViW3KBm4kc_sag_iFIg2xvUV8T7D_emoZSkTVVrLoSNzlbA5vf32c31wv
Bkwlb88j4WnAqGBzFoQKG-kM_lfBqelxAn5jiGOeKmw9VFVsTwOahF6SDygYiS2z_GUb4QjQ-UjlIbxRtvdoT2-Q-kjVJRcs_w1CtRzQdpXMkRM_CwLg5f_p
mPHAqV-d1YMJuV4HQvHCOfrR-pjJkgR-f_4xKpgDXMxjhxI2zDyV0puQqm8IIrtQtuKMaJRKud-vZIvCYrYiTMb_fQMOHQGr4MPQgiLgT_RtHbTmz7_6w0OZ
rhkplmywdqI5E_kxqF4iIcJap--F5Q17aIlxUwUpiR-vFrO0ZJ9tzZVC_f-wihyFpFwV-cjxzvdWE0u3KNXjmnAn2VS_xOO_6wo9QFIKrFLuXU-HeWnDZzIV
9u3-VwMK-lC4qF-lzE_l7-k7h-sY_8-K-UiF05u2Rml_eVMmVlZZlzzuyx-KFtV0I6D_xe3tbAmwXJy_0zqN_iChkFetZd-5Foy1U-8_l-xm2_tr0UnttlnE
xqy0M-Al201-lJy1R8c_9W3uixJ-1B2bhp-_0zpsp0z__DU-n2lurK_fNqkzdlpcVpP_0dYizFNdWv38zFNdDM3B4wpoyLyhkFY_h2NovprmfPF_pW7mijBA
lqxbZp_--EEF_-_E_lYlmXz_GG3uuuy__lXhbxK__kNiZ_ygGG3uuuy__lZZZxyDV-tM_lZNIVpnnnz__F4lPt_yLma3m5-syCSVV_pBsH__LO80yCSVV_pn
T-F77_ywXJ_--EE_E_lZlmf__2K1u8y__dxy-EDV-EEFF_xuM_9NMFlZNslXZp_-florM_lZNmj__F6tvCSV_y8VV_mz-V77l_377tzFVlpnB_pnnz-Mlmf_
_F777ty1lsS0-EEF_mfhV_ph90j__F4Ny9i6W3_--CTv_7VydRT_5Vxuus_BNuK__lWB-5rlWFZx7W3uhztQ7_ygtm3mNzx--5SH0FvlNVZVPYeIy1D0JF1d
FbtzyR-lp940uFzxRKB_Fd_cXl_CkfR_OsKE1N2z_-q1_qV-k_O1VxP_rONyu_zRoiiV_tWzKszlzeU_wYh-ptnTwsRWZ_-1VoG0-1i1wFot_DHQTmD__0_y
0m48-0aW-lpT0AxlZ_-UNrYFj_d3NtLk_zk1lnc0tX__UVxCLbK2VWA8thntA02zF_xp_Crvi82V0A8pxvqE0F_ZshN-VVxsF5Z0pm4GdN5_Fm2z_oz506t_
HtxFsYVzzTiV_yXynm04_0GGi_pT3mBExu__CxzbzUV10du2Y0P_8u2h--E_vRUj_ZXGm4y0qU1l181_QuNAly_V3m3-upg9_vxVlFhpO04_0KHdtZiVWDuV
_px_p3nOm4y0qPZtTbQe_LVMSN45Z6d-_ZnOiFqv0A8xxvqFGC1F0D7WRwxjQlxuFnhyxG04_0GG0-F-eNcmu2zz4a1qvxtp0OYsF_vz_j4F0WJy113zUU_q
F5ZmXru98Bhyym6m_GLVWqTtu3S_3XJmSm14bty-0C7Tdm2YopyVW6BxuzyTzy_FWmNy113TUUzy08BJdm2Yopy_3rPiV_oxyzxvSQ20dm2YopyVWE3q9u3e
pdldnu6A7_xmF_3B0X2S_WGGXt6_B001Fm54Tzm_FmyMdFvy3Hg7UQyi004_1q2e-8yV10XEVmA8xhntVXuiUFKZW3Zmom8GdFvS0Q8xy9iV1mhuEG3Ym2yB
GF3m9u0uyCi24F0JG7J7_VFpOC7TZm3YCE-L1I1u-FCvQ1puHIj-4l1p03nNdcGz5Gz_0iXBBRO_0S1F0F3NRXa03tyE0FW907u2EF9l0WG2uEudMmR-y7C0
yF0d0FW907wk0F0J0Fm4CFt13m7mvaS0y1C0_0HWUVSZ0FW907u2W9y0BFa9m9oVVnfkpiytmV0JW34_Tm3u2G1-0e2V02n7FWG0Fm7mjGy1yA-y2C3ovaS0
vlpy56ZEppJ8_EBFCy2Rdm3W9m1U-md0zkR7Qy3L-LcNzuUV052KFGFq-4l9Jm3U_3m3UFGJ0Fm4OCjF0Txw1C1h7m4ut_ifWCrF01zWyxEsfh_vg9yZm9oV
8y1SdoF0-piVZW3ppSyHyFxwfzxy707UcvyZm5oV0ipv-JB8N9yZm5kV0k0d06Tz2Z3Nfm3ll-P30UQRdmBG9m1dVGhmrkSNGNDz2Z3NPpHihiyV3_JMvofe
hay1tut_iVGfm7phau3trgS0ywzw-KN0VEjp29W_zKd0U-jJW3a-2PZZau0vFYy4B_Pc-4o8pF5v4d3gyoZOotZz2G
}

