sprite $cloud_storage [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000000000000000000000000000002OlJl6ZXi7eYXAOAGgPzx_RYTaOjkKm3um-z-tXNkOWR_U
ji_hVVntU_hiots-nBykzmf__Zyk5-tFlsFz-VFdNyd-_3lMdpz__fNgpvy__uxrvy-VVoNxy-zOV_xy-LUgFt_-_3lMdpz__fNipxzZ_Vdpvr-f_lpvy-zO
V_xy-LUoF_-EzUVFdt-b-lFdpxzZ_Vdpvr_9_lmxrfy_V_wLwi-VF_-EzUVFdtyb-_FlM7_-_FaN_t-ZESRnoyQO_D-yUVob-IB_vh-_SLneHFhJFnily2_-
Uvl75vft-_S3_F6VpKH__6VpNlzwX3_-ivdeZ_zitkZVJ_77VpRvlqV7DxlFl_ZlQtpNVzpbt_mtTdoxH7-V_zdW__oEXMxoB_xRcYl-ynR_vh-lOod-o_4l
_jkQQ_xp1l_clw-nvZ_uByQ_dkm_DhVgVooMxdzixld-7UlFdp__IlRdtx7-_FdphrH__lpvTwm_V_xyAzcVVqVwy-VFdp__IlRdtx7-_FdphsH__isVFt_-
aUy_lV-iv_glv_rtn_hpv-__hqhsz_zdH_hpvs__WR_zbqhsj__KiVxst_ZRVwnaV_kl7Ubl_vc__NV-xZzKih_xBnthx_uJV_VVAjNV_KV-xhzshB_xp_pT
VwyCV_tQlsFz-VFdNyd-_3l8N_p5_un_9VlpxrX__lpvLx8__mxo5t_nF-DVoVxyEzQVFt_-bUhFdp__ZlNdpvz_9VlpxrX__lpvLwe_V_xyEzQVFt_-bUpF
lsFznPz_fVgBF_-EzHT__fNipxzZ_SMVVoNxy-z8V_4NV_wrsVzwB_3NnnS0Vcv8aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9qbFtN_NPbtl7_MV-
FouNxS-_O_tvy-TVoVxyEzQVFt_-bUhFdp__ZlNdpvz_9VlpxrX__lpvLwe_V_xyEzQVFt_-bUpFlsFz-VFdNwd-_FdpxrX__lpvLx8__uxrvy-VVwNwy-VF
lsFz-VFdNyd-_3lMdpz__fNgpvy__uxrvy-VVoNxy-zOV_xy-HV_VwCvnl7BnfZytxnv_ANv8l_clxznN6X4-jC_6o_mB_vxcySNcdVxzmFyyP_DH7_yP_DU
_tg4F_wpcUYF_spUwDzFyST_Dlc_HyStky-_-EzhVDT_tENV_3TsVBj4Vv__sU3__8w5Rl8l_jkQA_xp5l_clwzZAVxByI_-svfh_lC6_-Q_hx7cF_Wlnh-U
x3ysj-f_B9RkVspk-VuTwy-VF_zAzkVViVxy-VElL7_-_Fbth3z__lmhsPz_H_hpvy-VF_zAzkVViVxy-VElP7_-pPy_V_wHxp-z_wpd-g_d_NV7-lFdx_-l
IlRt_sT7-lFdR_-1l_sNIlQt_zIn_lRV-Dj_h6H_-wyTwM__cR_zT_xkFrIol_il7Ull_XD_zzygrT_zH_xkltQil_lF_Dr_hmn__Tg_O_tvy-TVoVxyEyXV
_CN_Z7yb-_FlM7_-_FbNiZ__3l8NV_4_ur_9_lmxrfy_V_wLwi-VF_-EzUVFdtyb-_FlM7_-_FbNgZz__lmxrfy_V_wLxC-_O_t5dt-b-ei__uxr5t_-bUpF
lsFznPz_9VlpxqX_yHT__hNP_telyDV75m1-_jyU7CW000003FAtliTNRG40000000000000000000000000000000000000000000000000000000G
}

