sprite $advanced_agent_modeling [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000c5txH60WXg4e26oB-lwdJUy5fUUFSDWyETkUDUryPj2OlaMNWDMN0FtZz9amz1q1-1L0tvy0
VKS0_O02y2k0lW0yxLE0vSyfWBu0w2i0lmBeAu2-0EWh0By2w0l0upu5M7wV1j1t1D1N07u5q1S0VGNG_v42y0k0lWBeAm2_0kWBm9iU1LX-1T0N07q5uFTf
07r707q5q5S0VW7GLu37VGgm_0AWhm3w2i2l0Fe2eAy0-Wh0Bm3w2g3lqm3yZW3w2l2cHm6MNm3q5K3_YGNW5m1z1T1N07q5u1S0VGLutAS0ooy0-WgWd_ff
07v707q5qFSdGDyHW5y1z1L0Nm3u5K1V0TxqAC3o2u2-0l0BW7wTpMZtPvp_KW2VuUVVildvjsn-_YtRdt_3pp-Ndt_BzkVVyFFFvUVV-FFdpp-Jdt_Zpvy_
_qn-_eq_V_xy-VFdpvy_V_xy-I_PkvCinNKWZC83hEZslz_NTwIoJEWTbz7vkNTQddtXmeabyP7--EEFF_xuuuy__lZZZ_znNZnb9rVQi_znsWx--1_3NbLF
XLtMEDxhZ_zXKmt_hIS0_tx3tknlDjxcZx_P-_rjlCaVVzl2tyPR_F4Vc_ZRU8C__eVjuc_7_Vxuspx-utP__8-D_Esusn__iPF_kDiVVzl9tsxsn__0Vv_m
F-xpnnz__0V-dV3tg2zbV8e__b7VbgxhZ_-iFvSkxe-_rsdfolxuPxtATVtnptfTYFhZxzKg9VtnzsgMWlxuUxLBFN_yQw5KyyS_QwNGyiS_QYrNyiVVQx5K
yiS_lpMES8_8-gxGySVVpu4zQqx77__PDruEIAZuup_hUcD4LFpnZucsSv6B-EFVayrwBZNyyVUPlpK06lxuntHVD-T4mX__d5bR5uQ4F_xjZtMVhfJpnp_w
xmWL_F7tFchg-UCVVTJ0_z_mz-tyyHydTVpJJl9B_STP-5zvn4CVDM-u_pkznn__mX__xlE_WZ_-_Pkw1Fpnl-pxFm5__A_w_dz_V_mlVlydu8__LU__z_V7
_zhrFmB--5-s_cz_V_olNVyhu8__zUl_z_V7__hzF_lxy_xFLlV_-K_T_sVRlFzZ_tUj9hN_5t__qFt_-7F-1_wS_uE_rqAkve-_EP__dF_PpjNyyJVFwkTg
_lYRHRLBIN_E_s-Nclxy_aUtLFB7Vtq2ubFy-Vsl2i-QSWr__ESyClyIpmp_mQE1I_hZFtSs01wPVmvAHYZuuzyVWCXvsO2MF_xhJuQA_lXRLBSGzCVVijgv
aZ_-wmEGUlxuM_LBb_F7tsiXb_B7Vtq0fFpnNny0DN_yBMiX_sH_xlzAHNy-__kbb3_-MOlvPlxi_xp-zi-CYCZwjllEVyNVVdRVuSVv4kAGsV-DVzIKlrn4
BkEF_sIRZK-84F77toV-raKY_lZd9DkQ4jVmnx--r7nA20b__BrxNsSzbHB--CV4sXmK2N_yivxo_fKA_lZtx-gGzyS_-qyA8U2F_meg_l-6Vmhuy_xlYx_t
7nLJuFqVx_zN_6lo5tl_ZtzybZ_-zh_zGy8V__xV_yB--Az__oVWZ_zNrUX__x-HF_xtl_-JyCVVQd9jpKbe-dF-GxJuopNyyO-MRDQNJCCVVwklHMVzhue_
_l7ob8-eALFnnzzhBXh_hk6FlyKFVohIFRA-otJyyRVwsFs_-BF_7t-BMig5_F7d_1_yxRFF_yBVgrkOdZ_-vcr-EN_y-yy0RgB--5jqZd-MzSVVlF5_lvO_
_lq9I3TnV_pDeg6lwu-_cSV9SO1w_lZFvVIsRqj__0_xAGN-Y-6FF_wFHlXVsMVxupzsyXzt--D_xEH_tEsF_sCd_yVj_lWV-_WVz_lZ_nYx-8z78_mlRnV_
HoVyhsy3_pu__jSttky_7jtmlxxZ1l_x7_tmxtUCz_cFTNtyh-yuZd7Iob6j7a-TN7aS7NpytzzO-BmUouzs-EEFF_xuuuy__lZZZp_--EEFF_xuuuy__lZZ
Zp_--EEFF_xuuuy__lZZZp_--EEFF_xuuuy__lZZZp_-UuK__lZ3tmz__0b_gV1d0E377ty607xyyMS0uCSVVWO0VmO0VWO0VWO0VWO0VWO0_lu0q260pGHm
yy_zogwT700G0L4KjEKVinYSqBywXAat6nRTT_az0kWhWBu0w2i0lmBeAu2-Vq7y7W7q5K1V0DRw5U3cLm1z1U0N07q5q5S0VW7GLm1z1T1N07u1q5S0VGNO
wN4uXEdPq5U0Hxy0tFmAeAy0_0gWxrymJz_WLm1z0T1N07q5u5S0VV-2z3q2xFGemCql0FeAm2y0-lpfyyVFdpv_-lpfyyVFdpv_-lpnywVFdpv_c_pytVpy
wVF7pvy-V_hyyVEdp_z5VKEVFtx-zFdJvs-dXx-Rdpzz_Xxz_Dty_Edpny-VFd_w_Edpny-VFd_w_F7pfy__FtrZfuU_cvy_VVxu-TFdJvy_Vlxq-TFdZvy_
VVxq-TFdNuVVqETFdpz-_lJvq-VlV1V_Z9lVqEUFdpzz_lJvu-TFdt-6li7Fdpv_-lpfyyVFFqVVqEUFdt-ilW3e2y3vBW6u4hizE20000110FJ_TJCg1Mu1
00000000000000000000000000001W
}

