sprite $compute_engine [512x512/16z] {
xDotRILX08F1EqbSC5F_tQg5vntdozSEy8VytKgI94cI94cI94cI94cI94cI94cI94cI94cI94cI94dISNftkEczxigLl_YBl_YBl_YBl_YBl_YB_mV6N_p5
N_p5N_p5N_m7uY_-uY_-uY_-uY_-0_4NV_4NV_4NV_4N_u7uYx_uYx_uYx_u3yHV_CLV_CLV_CLV_0VYB_xYB_xYB_xYB_u3yHT_yHT_yL_g-_HoUjydzvFJ
U_AhVW_uYx_uYx_u3yHV_CLV_CLV_CL_8FxYB_xYB_xYB_xYFn1_yHT_yHT_yHT_yHT_yHT_yV-u-8k_-8k_-8k_-8k_-8l_oyR_kB9WFRMZL_O6_iu__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__loV
jF_xDgl2UTxtFp_-wR0__tJOdtywxCy_7VRddmxxyq-7_Vcdm_xyqs5__kcmF_zqs9z_EkpFFntsvvyE-_DFX_tvfyF-_DDXV_xfi3__TDYVVphippyTzkUV
3llpJuVz-QV3_lpJON_-wR0__tJOdtywxCy_7VRddmxxyq-7_Vcdm_xyqs5__kcmF_zqs9z_EkpFFntsvvyE-_DFX_tvfyF-_DDXV_uf__VOVxqJ_tFzqolZ
_o3-Vjp-B_zqs9z_EkpFFntsvvyE-_DFX_tvfyF-_DDXV_xfi3__TDYVVphippyTzkUV3llpJuVz-QV3_lpJON_-wR0__tJOdtywxCy_7VRddmxxyyynxCy_
nt7C-lF_O-U-SIDBWp08xew-_uL7MEKIIRAxgX7fFnd0RtxVV_phl3__pl-ly_xyE_-_3llpx_pJON_-dNywxC-_yq-7_Vbt_kcmF__EFntsvz_vfyF-_3l_
TDYVV-UV3llpx_pJON_-dNywxC-_yq-7_Vbt_kcmF__EFntsvz_vfyF-_3l_TDYVV-UV-7-2_xS7-NV-oVxhuVtdpZ_PVpxit_cdm_xyE_zqs9z_vv_E-_CV
_j9nV_x3tphjpt_uQuVz-Gz_xx0__-7l7VRdF_ozm_xyXxzts9__yFSE-lCV_lTtq9__yB-_W_xyX__zhVNd7_X3M_tv1_xIKd_-WJ-rqvz_u6-jzESV-6CR
_Va7_jf2V_w1FxVFdt_Wxwtpvr_uUzly-IV-tZ9__es_jykVV-JlhVBdN_bxc_pvP_xU8d_-dR-to9z_v-yjykVV-NkB_Fbt_juYV_wTlxV8dt_dxotovz_v
Unly-MV-zxV0dt_dVtyB_Fbt_lUtm9z_vtz_p_RdF_nFwSd-_8V_EHtmlxZ_Uo_xl_pvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
d_-D-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdh_VxBmohyq_ynL_ynL_ynL_ynL_ynVy5uo_-uY_-uY_-uY_-uY_-
uY_-hnX_yHT_yHT_yHT_yN_z-8k_-8k_-8k_-8k_-8k_-FzuUr_VtFTFkMk-QVT__NwzlN3JPztrJpjqKW00008Wh7zhWh1zlLrc0w0f0000082d0W00000W
6m00003G50000000NG400000a0m0000000000000000000000000000000G
}

