sprite $dataplex [512x512/16z] {
xD0X0G00308mU_V-RI44Sekmtm80000000000000000000000000002uiX1swK000000G92_zI37K6VzyG3y0j0tWFvk07q1y1j0tm3w0k0tWFvW07q3y0j0
tm3w1j0V1C1l07q3w1k0_nI0lW7q3S0l07q3w1j0Nm3y1j0tWBu1-0MWRm1z0-WBWDy0-WRG5m2_0VGDe6y0VW7e6q3V0Fe2u3U0lW7q3S0l07q3w1iGU_UI
93SC0q5qYrtT_xO-WUtHWAa0nEIwXGRuobIC-pUNFus7hG-0-adZWTiJeFu3_uybGFtA4_-F1K3-v9d_bn8W_zDAd_ho80EGN_llJu3-ISD_-qt00AJXl_q8
C019mtzv0lHF6lxRRm8680t_xKU0_ad3Vta2342hI9O7m004yD-I0FqJm7zB0Wn0EF_Ky0JeJvSm00qmF01mX4n07uiCG7X_Rm9zAB8ix-yHqDySe7I2-ti4
dDkQqxK3-vk0qzjoidn2-fi0PakEFKD0VmF0xSUPvqWmVnC0RqR_MHBCtmJmEz5zcW3-1W3WHmAG8Fucu00_7u1aWd_A1BmvUsFF60kFWAht0v0CyJS1Bu_-
u9A6lpU1iTclIgRucu2QEpZlxqsWz0UEWDlyQwU_2QXJQvk_0T3V1DIvjSlV1EXl0EhaskPl0af_DW5N-TSwVtvpFlDMx-_vUmGS_ogjLVuU0Oyx_vI_2NZU
zeVylGa0twAooDyZu5SDh_0t0PX_LlkRW3xaD_mD0F8LAYlyJO3-lZtizsrUwf-x_VLFxlRNFrVuOvVkzq_kzjS_kTjV_zpjhtzojR_-TQU__jx_zI___h_O
lqf___z7_y6xppw_h_-HCyv__KV_wG03zBVx5_apBhx_Otu0DXiCq5_lNzsTyFsVk_shlHE-_tkQVpy0mB3p_UjE_whsJlZvhzN-LTsTsEzVi_tvuPhxuET_
H_lpwuBF_-i_ocFmziG0VEhxV_GVI39uQs80TlXJst1j06gLV-b_VEtn1_V00CptB_sXjS6VtG03CDmVdl_s0DHiVtnw0p3Pdn_U09pm-VSGZUhwZmx0ppwQ
CFt5C0DGYQ-4U0GCMXUCxH50pXvmQ0Cmd_-nlm6e3-bp_Xu1y_aR_eiJ4201A_KR_di3S7JtzlFlztyyoDe48CtVzAl0m1ukvGVyfqS0sCQr-e3_w0XGExcJ
Vws_lunnec7Etm3CRtUjlma0MWNy3S3SHX5_4x25d_4t02kwJ1X_4x2ZISZV06neCe7yJS2A7Yb_0x2WnuJoDm4BCXhEtm2Cxp3X_4t0_0P1VmCmlS44z3S0
qniCwMy2XlUNOFu6OBv_M7yJSA8orXqzgW4uLfJeZeww2JXQ3-YDzJS0ZLfqlU3-9g1H1owPyFu6e564BPhm_YQWMu2gcs3-1e3dh-htnVkR04A_7u14Vs01
_CZ_sqP_QFM5-00a-cFhLVwgHa_wCwl3mmSWUS_V0C3ypvyYuVrT3Nuq0CcR_WO0vd_wB7dDt_KUVpNQmVnT3N_a04ZqVtUGGldvJTUVRsHY0FJNN__1_7ot
-kkl_tn-lbtzv_Fhht_fhp-mz1_4ppUil_xwww__J7w-O_trrrz__UVpyothhx_--kkll_xwww-__lhhhx_-FB_--kkll_xU__NNNt_zzTTVV_trrrz__VNN
Nt_ze_-UGVJNNt_zf_Bh3w-r_lhhhx_--llz3_hhhx_V_wM__lhx_O_www-_t_-il_xwt_px3_h_gCHaVltvt__9E_nlm-Z_tk-_DRg1blupV_zH-PVyn_x-
Q_Yb_-JVVnOVzs_mmFny0lJ_LHMMFut1z6-M3fW0i2Vz3nKE481sQVqH_vuIoSydGFzs7KG_wLolVxzeemPG4mc0_eSArVdMgl04w0zK0ken0T2_KOecur-j
rN_0dn9WDFNl5-DUH-Bl9lhtQzKtN-ZIlsgiFz-T_bMZjnZjJl-g6Xq0j3tzgsO7W6nF_wgQ7G2oF_shXWS0x4__gXeU0B11_Qkc1u1hKFy5dzJYEjI_Qdm0
i0xrt_1PJQn5_MkMFzUZ_dktjleh-g_PLxXH_UVlAjoh_lDt56XN_ttxoNSy92Yy_qPzkcbWlAd-M_cvle4H1_ilrYTQ1yQSxK_mhqq0CEbuVq1_QG28QUVx
0_m3fkNNH_nHVGCmtn_W7p6l2LYm3VkF0FsJUmEW_-YX-NMxVwEr__Tk08Rx7sZjNrslE08kzgTRYm4OxC-trgfl0EYfUNy3CDN_bTQcJgz_vliR07nStdzB
0gxopnR_w3zqr651wwzh_BFBF_hpO_B-ynDmXNys-aT_UaJUVtu2Fk-VlVvfpbobVpRx9zs95mO0qD_hd_R4D_jdlt_IdVXQ_-GJ_cbCl3400Fzk_wGvyOt-
8TRMuDtddqt-_6_5NEOVQ8tENlAD023y-_qJ_O7j7-YFtCQlySzt_QC_iFUZ_5kA-kTQV-3ITVx9nVxwvsP__NEll_x--zU_wW9__VtxJtzW6F_-z_z_zVVr
7_rz_NUklw__0GRw6u3z_WLSPm80Vwe3ajy4pFSlm7zt0YxphyP57W4p_VkMZMvDm3X_ylD_tWJc-vEV__K8cEyVuFF_7W4x_O6jCG7wUnEOx1-0_z8ZGFya
9c2PVqX_4p3VFnI_0T3V1CptptlyVZc4_Xu1q_m3yPi0td_-EUXDOBv_5lBlJm1OUS7Nf7WJ8ElE_vYKHm1QTlptf9W0jEYyJyeR0Dw_fS8ERG9u_oOBpsy2
GFy-3Cjl053_8pAOlWbW_O_X0FecWFO_wNDWHXFmhlzX8O3V8u3p9um0V8y0n1zZWl5D05saJqNYUnC0IWpZCW6iVotsDm7azVC3u4s0l7g-lqS0UV7y09W0
uDAX0J01H_shFk3l4K1UDpy09e2yQhw_Dm7WeaK1y0W0BbdaRmA02nO5m9i0yFX50J01mACN-NiJw3nsVm0y0ZeFtUzl0XeFNAzl07xiNoFvNRLaAVMdNJeM
000001ZaRps8lSNG0W0000000W000000000000000000000000000000000000000000000000000001
}

