sprite $container_registry [512x512/16z] {
xDor5OH0403GUpkNqt-rU8GbEFD_0pWh8zMZ0000000000000000000000000000000000000000002H6Bz4bpf3f0JyKrxqY7Wp0000002Wn2RAfyKY003C
-iatwmS009Hpefpp302GhzWL0030ZlHZrty0Q308lYiqxZmU0C3p4oFD-ddxhF-9v-Zx0J31KXzbRgej1W0073cLRjYx3-nML1W8mpwnDB3_3RzUBsdO7bbS
_xC2ZZunfEUsnD5VRBttKm6IUIsDncE3u7sH58NRDkR3W-6T_ieeglv5lyC2u2-LF0AQhi1ufxyKlQkV3GXFz4_2NFtUt7Pwed-J_kflN07uIz6n-jc0Yp6I
UmDYpAfShfiX-Y5frEzV0VXBQNpu-sy0_b8O7_x-6u2_qbZz_HS0VocDrTz_0_2NufdLpmP4KVHXChpLt-4BWaIV98tLtxy2y9V2MFtzDm1_PVYgl_y2u2_b
dhwSdFKRWByKDGy_6n1gcZ0-_Fv8SGI_vbJJfE_XzqTpgYNuEZwrJHYht-y_H_JNR-qlXQtw_VxTDq1pjlTN6glVxz_m4LWlZtedZTNlzvyZkrR_8VvIcAhV
xz_m4LWlZzedmrBzVl-6Zy1wUNH0qb7zVl-6Zy1wUNH4mb3zTl-6Zu3MevwH35_r-_tdL9FgFzLVIgE-tt-Ex53z1_jBSvxbt-iHq9oL_lYlKP_gz_lZt-SH
Y8_qnv0X-8yF1nvjgd_yWP_bUG7_b3J6wF48vFZitgSd-F-HCPxz2CHuzzghmXz_BKLG_0Ze8tk_F_uVxu3ggt-XB_F7VtqCHbPL_thjw_tnNujWH87-Qb_l
Z_-w0_uDq5BvJ_R7VtqCv7lu5_i6_lWlHP0UVYt1lp3FdZ_--EEFF_xuuuy__lZZZp_--EEFF_xuuuy__lZZZp_--EEFF_xuuuy__lZZZp_--EEF_uDJwp_g
WxzZ0Lpy-DUdod_e6S7_gqHgEqPz_ElZzn_pIS7VKG7EXv_tlty7kAkV_g-FoNyedXdylvktTFYF9mT_ns4xLp_zxpzjPtty_UVjNFtql__4dIy_zzz_PeS-
_drohxyCmR_F5mGxNtxy_GVlh8-__-JEwiU__oFG-VBZxpzzPtty_STtwkFVVmES_FZttm2dFlxz5y2fZt__3N3ouzz_0vpw-FTV08S-_hqJ-Pw_3C6_UmSu
Bp_-_HV0f8z___pZFnG717_7Xm76oy_zxnyvzV7l7vqH_8aa_F777t_yho-Ne_pHnz-l7orIwu__jMqkpk3lrEyV_DlfNshzyRyUa305_-jBXlkFFlvlvmFY
p-N7_tpztIh2dxkFF_pueu-_NpziCQZYp-N77ttyM-lVLVtuS_dv_W_Lp_qlrZ_mWtxyu_hp1N-g7t_qyKUVZ_-v_Dn_zF4lrN_RoGL_ap-N7t_qyKSVVtwm
-sqZ1_bp-Rd_JHSWz5aoYa_pyl__LufI_Ja-YvIL_9eR-Ldz2pT0OtxkNtgQ71D_ILAMpVjB_x8DY7_qyPUoPDxVz5SMLp_-KjZd_Nr_AOgh7t-bTzvx_bBK
LZ_-KXhdlUslBAv-_AMmpNlVNyhYwiTV6RPvx_jBKLlz-4jfcFU6ltKVGuig_al2zjJk-qjPNFtuIs6Rzxw_5CNLZx_ID-zzVsNKwkClXU6flTLVIjldVFXR
Da1ZFj9VYkA77t-beMnlzfUYjlhnb_BcUHlybSNLZxyKDytRuoz5SVNZhupjUVlyfQYjVlobt9otrLzPNFtuIx4nRxU_bCNLZxyoDkRjzfUYjlhnbt9ZtdP_
PTHMF_vIRCpRuB-tZ_beVFobsAX-jxyKtkh7VqrkpDlkhmo3Flxx6w0vJVx-q-2_cTXuQjt-KdW_vyD_JMwKhTrV2c_ruxycD-PjzrUQgn__DR4nRxU_bDxg
ntzDniQytVvIUAiV_pKR-dv_fQpq-A-PdVmryCV_4S4VV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yySSVV_pnnnz__F777t_y
ySSVV_pnnnz__F777t_yySSVV_opsdzyFoVvxwJKV-ZpPAd_6FZVkW6kWMUT_z1EZlBtRu1ltbdZFoJyRry0uxopmFzNziu3rv4OXg40R8c-_uMtU4kw427p
-2iF411wD1MXZJ8_6FyH0lctPyvsBSrVMyp-Lmn6CvVKu8yce8-VJ83wRX17qievC4sj9L7zantHy-xPKSyDmrzQItEW2ktsGlYhCt9ytXa0VywEDfWOk79j
IJL_kWF8LTk_1GNJh_bBQok7GNi9r15mN1dzUPDBGBoRgE4NrKyiWJ82ZZkJfxyL1_9NpXSK1Nou-kklt4W5Vom11lnRYWP_qaqyOE-f_lehLrB9lwyZ-EiW
FUD6V1RZ7low-labS3y2OGW0Ek_-wSMxYJlmtTLVV-fCqea_dG1WrHQAr_Zhk13g19-l_lutTwNDdqz0Vzxa9I3UJPmUlhFw-z_Sbi8G09v-9m7YtSG9lhVw
-nzUpYtslxUN_bRXHWOxQwjV_Vubu7XqRlor6ndS0DKFBG77etFJhnCWWvj6zRkL7F-SyJH_9QzuddyUAw3weINWU7GLVdy2P703L3-K04VjkkdNRcHmqwFl
rsa8ZaVdfb-xqRKR7Quy_VXudvh9ySyPvJPqAoh-Ia3_Xzjz_FubuAZTphnvDpAu0QeVkWKTZyvDlqw035K4t7pGBUWOUR5gRJgvaI6CmCs7QChnw3hpvjt8
u6PN_xSYjzpqwmG8TpC-bdwsSnTM4CCm5C3w0lR-4nypCqeR5CBvBi_J-lBxVqukAv_y-KjTOzheDj_t-xk0V6dZfqV6v-ZTrzy00D1kGlr60000030SGFrn
001G_bxzEm000DPyNwBL3yIl9nC00B0IG4RvcG000000000OwiEWdj6N0000IhqQlvvu1W30IW2rZxuL0000002WZ6XRem82e_yRvwI-0G00000000000000
00000000000000000000000000306
}

