sprite $configuration_management [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000cBrxnx4Ony4m6jY1Ckv_jnCDcCoZh-2YQV7yUKE5Ef_bVhlbpAxhYi73Fpe0_0BW
FpO0_0B0hm3y0mF0Bm3y0i0l0FvZ0Z3y-EVv6tx3R_TeVZkTt_2Rbx_XD_o6t_0R_Xn-_FZvupVyXd_M-EF7FpW3_2w4m2y2_1B0Bm7y4k0l0VmAm9-xOzpm
Am2_bm1-1V0NW00K80052C04SCOKa9md1s3_MFEU6e00SaC3441k-DyE5a3SXrq1zYlcq004a1lWBu3D0i84SFm44CS4O0AmQuDJ0Au00GZW-_uc0BiV2-2E
ByuU2o0UcArxS03qrxgkQsm0zDTwuJVvkt_yWJ_zzB-k3W5450T0VwtQN-Q-vhF-yDE_IG4HfG7GJ__SUm54jJ_zzC_TRmKGXG7GpxttE_tvqCVywUTUVAh-
ouaL5m3zz6zGGEHgBW3wwVzc0NbMRG3mq__L0lAWMd_wwVzg0hyTmlyP_Tot_dkxZKRfx_ZdejNuR-Xl-USEyAU_uPyx803w6_wv0_pXR_Zd3l2dl-EVEo40
-ll-rts0F_qD_zmP_lJJ_si5y7z0F_qtTe0__VJVMByN0FmA_roh2u1-dN-kap_zUl_hvjz1lzu_nx-3Vhr_heC__Nh_N8S0wDVxvphumw_tp_4lrk_Yd-DV
fz_H_xhvr-Xtyy_nBz1lw9_ZNw3Vq3_7lq2_eN-EVm5-G_yS_mBzZluv_WNwZVslct-1VaF_7Fy2_OR-EVu5-WtzS_mBz1lxFw-pSmByUlzSDt_wwL-ql_Id
tz__kXlvqq__mhNnfv_-fMlYJp_zY_SSVuv-V_zS1t_uwL-_X_tfVyK_z-Gd9Eb_p_-w2wv_-WtzS_nJVv9_xX7-Y_xN_7CF-DF_e7-km1z-G__SqEj_BVvf
kEqVS_pvN_pvy-Vlp_wy_-VvyuyZ-FdlCyxsvn-p_Vd76Vpyjnrd-_EFsV_eXt_CzkSVK__1F_yCu1xeppy3Y37-_FkFFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_FdplqVxym_-_0N0_vJnvy-VFt_-_Fdpvy-V
Ft_yEVxy-VFdFspy-VFdpvy__nWx_lpvy-S_OlpvyyUVuy-V_rcYW_tvB_u_xZwB_yS0-1_uEf_fptyTvyz_otAWF_-run_d-7lySoFzFVwvOVxy5t_y1G7m
vy-_7_zM0Fpvnqd--7DJ_Fal_lnt-IE6-kFdVyHs-VdZVpq0_Fpvly3Ftz_w-VVudyBFdt_yled-4Vpvu-VFFqxnT_q7Vu__xvlc7nv__lnp0_pny-VFF_dv
vxxlpp_uU_ntDzUVFt_-CS3VV_J7_-R_NpR3F_Zpz_hl4G1-_WLp_JSD03__DlpyOx8___e0yFElsys_MG0UV_wT-Fd7R7_-SQf_yEVFlrK03Vdvnud-mPy_
_sO1uEVVZfz_JFJdNn_0R7u1uEV_vxlvR-mS_-3VDG3y-ri71D2Kdpz_Bu0umJ_uxw-nF_vOtmy0F_y2VluD0-0lWExy_AEhF_vOdm_W5NuNG9ilHBx0xm9e
z8dGOduNGFunC_rT0As-4LpCpx_PHw9h-GNGxIlXbVpy-tqc7d_X1s1_AAKgW3f-0QpLBu0oVc-0jHe6KC3l0jZmhmfWDhy0y3_W_-402la5iFe5W7zZswuF
-4S3V_mRhZq3gELt0NGBu7lytW1Hwuz_dsGZWDe2PkiBu6_u-VztsTKgW1xy0jWuhzGV_pv8vm3gzGMm7WeWQltnxtDiN00r0Spc5q0Hlm1Mpm3Az0MmdlnJ
W5orF_vzZGSlW5ozF_vzZJy886hzwUzZfFBg4K0jlm0I-Wd_N84__OBxkFhCsVm2QAOlWE93k_4BeFRKTleAA3rrjhu0-dt8Gm6LfpPy-0LGUEpVwblt03hg
Aw3kr9OlVWMKdThpuLT0rR5DyHLGT6nFVGbKdTfINm9bXtRKbq3TcVtqHL1vOZjy_AMdDiF7Ntnmgx_LGtzLdzxgqSTV_XCCmgUVI_-1-FZpP-bYZ_-T7sY2
lOU_VeRVw1j-eqz_5B_XD_g6Nm3q1V1V-ErVxT61000030GXV-jnxAyKsgVVVtYVU3_s_OVxYVTZtt-ud_W-__e100000000000000000000000000000000
0000u
}

