sprite $os_patch_management [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000cBqxLdDMrw40sl0XTtx_jxstFENy2PlOrb8z4p1h2mW1awln_vfzYxy0yEyS0Fm2m7zSitFn
7pKx5_znpuR5tnw0Vzi0u1S0_WB0tuK0_WB0lrK0-0i0VW7WBm3y1O2_0F0N0Fuj0e1V0FWB07y1u2y0_0M0lm3W5m3-3GB0Nm1m2m1q0G0l0EHt3e2gaQfh
DYjjxyaGziSy7ipUIG1yXm3uzW3m1S3tF07G-W80Nm3e2u2ZlW1eVG7G-mAWzmM0lW3G5m3w0a2VFtt--FdJnq-_22NhNbl_8XGgvtsgEkih-lJfuy_2TT1t
vA_7bbHqJdfY_sHz_0ylQ-PBlNjXxa1z_1LON7Qet9_Zts3cjpkq5EVzaGM-677D_qL5bbXl9np_HnLQv0xpZEAl7Txx4Gep_YsEnQ4nkT4ZXFBhU9VcZs-b
MaBVBY2WlzHRVnExDlnNQC5R7DlmPvPSQtsjnP_SC2_epy0rBVoPPQU7zynGyMUMlSVlMVWp2z_ZfJFuAxBqfUzZBFpPdsCskPS9_vLOWGrkPCI_usPuz2Pc
_AqVOi3lAORE_FTH0nI0yqS_100__mTEZQwp-0NWEdlS_3rqEGBLaR_md-QV6JB_zGk_0DJfu-Nl8IYJpIRuJLo9V-THya_kwlYlNz_nywykxM_I-WEtYvX_
NVZvxreD-FdZvv-RQ9F_jjM0dt-Od_-DVyF1kW0KuEUFt_4VFt_-_F7pNxIkreyty3-Odpz-_lpvu_yy0FmdV_o1ui-VF_w50s0AlDdPN_lNgVxyx-2Wrh_a
xSV_Hlpc_t3onr_xc_yDFt_-qwtVtcoa_Hk_uhepl_QVi_hwu_V-3_wpyybVuP-b_NlwU__VZV_10CpExIy0rudZdZrA-tztwKS0Qch_ZUjgo5_y_rDHVks_
VWNuM_WBmEpCBm2pixy473lMQmf0G5_xU-lj2VuIS1qzojct0lhQNtSSCa0HQ19mTT9siVjNsb_nLtVB6p-KzbVyLUlTlwfDsb_P_PTClkv_BoJ_VZJvhsFV
CG9s_usVI-5VFxxrXly2-YqJmF-0co_v1_aFJe2BVpL6tm1e_mEUlk8Vv3yu0FolCVe6WFyOGm3mjmm0_ngD0y2_3fXzYt_uUiIf0U3_B-koHm1gvK1Us_1_
y_SBNCBK_d-f3zPZIVz7LuT_u9_Utg35_zErkGAf2TItMvB_vwkmGdPFzA_VhqpoN_alt_xV_FEzkJ__-kwweUF_bnTRVxqkWVZmNtIdzVNYS-lFFr_r_TAN
zY_-QRo51f1U5Vxv7G3_-kNkFnyY_aksVzv__UzI_0CVi-p6v5yT_FddtL9ZuB--Ft_-TO8___bnRUZFltB-D__rLtda_0V__VohjJ__DJwBVxBuy-VFdpz_
_lpvy-VFdp__gvS_VzT_-VFt-oz__dx_vrzzx__Yx_u__XV_1yhp7yNVyp-V5V_X-J_-gvy1hB_xv-_vV_xvoJkA_pzMBJt_KsNQd__xvopc_oh-MRzntFnl
_CTF-VdNAW78p__BVyqEkip_tMQjFrs7UdxT-Q_pTJJs_W_-zrgh-id6gyytEF-PNSVy2y3gYUtDVuC3qkA7hptvPsrrHVeFMtplzbVZaPgT_GLWTlONWDdP
Nm1QNqWNWDRNKGLWxk-lAi1_lhzTm3qR-ml0ikiwyoK1T-UVqPq5TBwDGWBEl8r6NOlhE_phhj-Tc8X0bu2g2cnNkt_5Frhyhwcql-Al-2lyYh_YVtxXhtbc
AUslRlxQdp__Dlmj4wtz-vxPEljlV7JJ_XKO8ly3HkX0K47_zR_SIi3X_867R_YVf1yOA_vr7hjecm3-JpnyZtySF3G1m7_Y5m7jVpqp_HB_0ovgT0k0zdzg
zasN_kf8V-S0sjyUOFoX6l3pnt_CuBN_60AW_GL0-_F7Bm3ylwZhG7dyTW3LrLy0j3__mV_0tm7i_HEb_VdZFsQt9W13-_C_RD3yjN-DKE4_PMJyAt3Pcx_s
vuz_zR49mCdZBVuHVkq_yFFVluh_XwNz-NVXl_WVwHyOA_yM_Fn76_wB_ud-NmsKV-5t_CVFVyiQ_Byi_FpnyyVFVwyQ_1ye_Fpndni0Ko3FplxkXwhJ_Fa7
HkZvduRyTW3Lcf__wNl2UTQpRVmztOI_wSED_Alpz5Rynnxyvl-BRFtBt3PR-8S-l9uU7F_iIWQQtzI6Y_kdFds7wrhc_w_GnzS6_Dx_4Vly3RxNy8zz_5YV
t_k_Ofy_bkVt_h-ABQ3mXm9GyPEpn5ZnptkjzWyk8JSoFmI_i3FwZVuzZwzb-8EBI0vC0DvOYzGU3l-S2_3d5X8Uc7E0fT-kFV3_fQuVVl6h6COzy8SRvRNb
hdXK4u1bPziPUNq9kDzRO1WV_mUdWMi-ThF5RQmUWe-8NEE9kcRZUal_UNyJsBpsYz3hFpdLc_SngEG6geTHFBwUgVL_XAtu0mpgsItpY8kfgzriwE5L-fgV
_WxDhwxbzMz8kQhMpQ_eyyVFdxu0q1S0-W90Nm0QwQlghQ-QwwkRlaD0OtrrDTTNy0M0lW305m3w0W1V0E0B07m1w6EltCaVAG5Wx-rZ_sldBWW010801kBq
Rqm9V7SLXhvz0V7qnCiJxquyDF7-n7_eYD_-nFiJxq-yF_7-n0_cONVxkm3qTm7exm98zcThzsTlzsU9voVUdtX_uls9zoVUdtX-uls9zoVUdtX_ulsvD3y0
00000000000000000000000000300G
}

