sprite $key_access_justifications [512x512/16z] {
xD4f0G0m3C10DZh_RYkXBxoJaFmx00000000000000000000000000000000hqui__4V__4V__4V__4V__4V__4V__4V__4V__4V__4V__4V__4V__4V__4V
__4V_mdsxclHRLm7et0AJUWEx_-sqmTJlRdrYmeWh7LzYi0FL1odxSXcn0vmxra2x1SpxndsaTyORfdi8rVZJR9Abma_4lsCzyWoNZfy_Iqm5lxhf1sppJkI
9lCtaNJ8yxR6-OSpfoN1fFZwupaj6IRLrv_FQGanARx-X4vBZ5dr8pltY4vBZled_lsTcinfwHedlVlwGpejIMQ--z69oTmZEdEqCr7Zyq_fj4IP-l97dv_C
QUac9xtx-dCwBM4cl_lHPoTpMhhBII-__g1EIvf9zVKdTVYNIiglF-c0Vwca-lgZ6lnBPUNN7nN-fTnjLkbJantD-QatFndyB41dVchEJytvgJa_DUUdjlo4
Fnsy_xd-B01V0R40yFTQ0EBxN_XP0FWxbUp0uR-xb4SD_tsbFUPdyRC0UP_Dl7N9xnUtVtVfZxSiFmjmf7z2Twfmjl1lhCJHmh-l8WSB_wwgdAl1lwSonmh_
dkgSAlnRglDbsXP-IgyVxU2dIcSA__N9bx_o0b2r0qsqhVXtVc3uUMRuApyrZQ87YV-FFaUU7Fwkpuu_3mz_ySSdgtv-qhT09F3Ndu2US7divWN0__1K7LNy
uQ-_07ppPq_Puy7rhyqVyGAuxODJwrNc-ZCC_2cxuGM0F_Cy9dlSSV42s7nQhKU2t_WHZUlFKF0t70j_viAVkU3lE1d-hKVZknyhF9k-05p_riDn_P-ztQFr
zST_ub_ZV9YF-t4Sl034QlEh2u1_QVwb1HYFzEVw7x_72q2eFF_F5HmIVvq_mlziLfU_wG9m_OC_mlzSnVcZWdDo_NN-gE2W-ElyaU4l-9VbZsR1IV7N-QFM
_l0VLczM_7N-o9xjZ__nlj7P7twxR5fpCVplvvyRfiM_3FzHULpyzPS__eNzTNxyD_AFylm-wYu0rz-EzrKU67-T7__2_Ze__dlzA__4Bohfp_MV6hy-Clv5
N_xr_V4Vf_ZndnUM-0V_16U2Vm5-_8Kgy-ElLvaVVxt2_FZ37-5_fihy-EjLviTVhp8__dgL-V7NAyoFlvuLviTVpmhpuwzNcLy_5Vmhy-Elbuj_u5ztKftV
wfuA_Zh_p7ug-1_7FluZxwdW7u9vNlxuwvqGJCEFlzuPmIpy-EkT4jpn6_tnJpwfe2NmuvzaKi5BuCS_oQIIsF51sKy5Vybi2lpu9vZK93KJ-F5FCEcKt8R0
Zt-2IKsJsyUFlvxabu0VVp79BnM_uNyYpIy1F_vIugUt1FpAeU0l_kpD4l3ZBoH_UIVmuvztLFqDi9yVVxqDlsbNuCS_mQWYvNv-_DCkG7r-_0LEWH__HBCA
e08__ebc5KWbVlprX5c51H3uaytSm7_V0Xpl6ub7nbzVWEDzbdXa_FK5EDut7V-y7m3q1JW-ACV4-EzP0E7bp_KlSHo7adbnV_nTuiS_e_-uQG5yNmF_s-w3
mb__-kC_1Fxw_lYx2Vpu9_1NJoGzF_wszKHCviS_qv5ysWT-kTfd8lBZN_rCD7xyonzARtxyNU37Vtypnm9K6nJ_zIH-_Ek_5WN-17FYlti12e-9lxu02SSq
loiMmE_8jWo9lxu01OR4Vzy2L9kH1HX-BecVwr__SXJWn__M1IW-82y0xRS4ZjhpyGBGVaEGSVrpD6uxeEE8PjRrDb-85u3w1gWx7Fuclm6iz6oy0CG5iBgZ
uQylW1MUJ8y5WB-yV--vy9_F7Ejm8HQ0eOfc_Fsd2MRYhZ0IBm2kFyTLOHxy9-Em0Fs6uHD0z21-yzxDKx7AJsae2r2VVtZ42w3mLwP7cJrc0Uhpup-j_0pr
_Jay-FMi-l7DdlwS7_oS8Fnwe_0PJlpLldyN5g0yF_m_zvfdimJw6Z_yFrVo92V-5_5_7_DyrVdX_xbNjTESyEjzZwPIANxyWpyQKydyrkmYVlYZLvqpdM8U
mIykG9HUFm8_-ACInshpYXp-VpSA7EkyAFYtBC1ChX_1_n-zfbvk_GZ-JGimK-j7yFz7ISzsxWZ-VpSo7kxS5FmR5Y3AYX_1ltK1PbBz2Fuz2n2bn8_W_tUl
38SyRmh-dGiG9REFuD-z054Y-WX-VG7qtommRVweu9SMe7xmim3mim3mim3mim3mim3m_zp0_rdyB03yB03ywxNcXz_zwCmF_y-rveVVlJK__Euj-U6FHaj-
-ADs_F0NNG1pluuV_gZGXPRvuQ-u025w8J_yKPqVpI_aXp_ApXzToGz_b5m_kf8V_iXoyqUNyiCVvTQFhkM7Fqgj7rtB3tyqCkj75_F37rbY_kXgVlYZcI7p
zmdyyET_1vpPKXU3FqfxzoE17_xC6-2BRU67Fyg97y7_SIzNiepw4VmV9H-D9SIFu7_V9OUJJp-2_rsNtOvi-17y7_1VTK2vy2Fu_wyIVsMlRmh-FSTSoHx-
o3tL2fZV4VnHjt-b5_xzftxCJpRyvk2FV4VPhptyKKj_-AEM_l17BVtXZrhwmnyzsn_-rtoVjVJdzaSj_RdzKKj_-AEM_l17hVtXdzRH7_x8Mlh37xNqXpzA
va_ZLlvvTFI7FyhaJzzkvSSV_gx-VFJZyp_yjVtXZmJ--lxm1y5ovi_nXz_TXDjVtXz-znFyEVnfwFm_9_3NzuVVNL0exm__keDvRN--zOjEG0n_bZ_yaI1G
rn_-I00ewm__keKdygSlb_57BOyV_gWbF_nH3Nwwc3zgoGz_r98V_gWbF_nHItxuevRyy4SFvOT_-5ff-MdSjW3mim3UCnPWzFvRrba0wttxMO3c_2o0_zGk
7HC030Cm37loXp_RmLZRI1Hi3801C006m00O00DW00o00J001i006003O00CW04mmDaCqDiH-GqWlm7aDu3y1f3V0F8RO2a_aTy0yXj0VWF8Rm3v3I2_0UGt
WFm6aDy0NM40-GqWlm7aDu3y1kWI8hy1v3U0_0ReCWDq4v7V05rcWBu700000000000000000000000000000E03
}

