sprite $data_qna [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000PfzURgGC0Z06ylwvVVbdIm2SbcQbwN4vXP9VebyVIdLy_OZpgwwlEB_Y
_8hpYp__CBzsRp_edVUqznT__c5-yRyo_k8l_k8l_k8l_k8l_k8l_kB_Xl4NV_4NV_4NV_4NV_4NV_4NV_4NV_4NV_4NV-scn7-g-wlkhxY_ulwA-olkhxY_
mlxYhx2_-2laB_xYB_xYB_vwLN_n5t_n5t_n__sXTBV_kRxkzZ_NrtluFo3_kJVmXtZGSxt_0_6eo_q17lQq_NMrFxxpBlR_GU-y7_Vwm_iVyV-K-D_1B_vN
nb_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynV_o-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8l_UTyFglhpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-Nmvg-lFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xyVntKzkVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lp_hktFVsr__clxyr_Rd__Q_lpNzkU_jZ__jVtvh-tFVsr__clxyr_Rd__Q_lpNzkU_jZ__jVtvh-tFVsr__clx
yzy5_lf4_xNz-Q_jptzjV_vh-_DVsv__slxyr_RdlxO__xNz-Q_jptzjV_vh-_DVsv__slxyr_RdlxO__xNz-Q_jptzjV_vh-_DVsv__slxyr_RdlxO__xNz
-Q_jptzjV_vh-_FVo_cBl_YBl_YBlvwqlrRr5t-jxAydxQ_nTt_KN-DFdp_zYl_U9hNvXPy_Vlxu-UFdZvy_Vlxu-UFdZvy_Vlv_sgCF0W1060104UpVrX2U
FQZ0kWO0000000000000000000000B0F_W400000000000000000000000000000000000000000002WeWq
}

