sprite $cloud_translation_api [512x512/16z] {
xD6n0G0G40ImxjlRVriZG8LFLaWU1000000000000000000000000000000000000000003Kek0V__Z7F_xnZt_yun__-CS__l6FV_pZ_s7-yOz__ECV__Z7
F_xnZt_yun__-CS__l6FV_nJ9_3_3V_unp_-yOz__ECV__Z7F_xnps2dFeW0Y44e2bvDfkFVRMnGzabWvyE_IVp5N_p5N_p5N_p5N_p5N_p5N_p5N_nxn5_y
nL_ynL_ynL_yYyPV_FbFOXH_uHT_VVpD7pz__lZvyyVFdpz-_lpnu-VFNzw_p5_yXL_yXL_yMyV_3vc_-0k_-7SCFt_--F7pvuyVFt_-EsedynT_uHT_uNT_
_eUzUzTkNeU1ADn88Bjv_xSzhTUf_iL0tgIrqUVw3SQAHJjlz9VV0EYlVz7F_JW32e3hRm7KEVxwb-jl0RZ-5e3y1a1__UKt0FhhBxy1U8U__aF-Xh40xZFz
zI_NtmButbUxyrjZ0RZ-1g2sytUkNXFvBG3zlGIKtmAGtm3ehx_y1g00VuV6SVqjWFtNtxaUvXclvlSHeFvvhX3ZzFdR_XQ0_0P0V_tbDm3rQdy3y7ly-j_o
Mm3xj__ynqcIE5U3rOxy-cDQ33_lRm3uzH-J3O3-nQu_wsy0wXZ_aVun03J_imMW_utnx-zl0HJj3mJ001p9hty_7C0F-1k0Zki8XDy0TDWDilrvVmjWJ_vC
BW06eEZsp-Jy3S00rX_prx_sQ_zC8006OE5ZnoRy-dSXrddhht_3O_X6_6C20V0HO1V-JCZV0DJ9_YD_6mCmjk0Vy-i5e7zjq_wPXBy1s8K_4mc00QXZrf_t
Dm3PqF_AvpZZGFunsmh0EOy_iz7VET2_Cm3ESVoj_iv5ylF-pbdyrsmEWFDJwy_x6u3ix5_v_pW_myyNW078c_tr3-VF1y00N1m_xsy0xfpfxvpG_cDk7G03
46xzUNy34C2_wnoeCmxcvml00iYR_Gt0uFpv01Y06-Jd_Gr0Vi7VEOg_Fm3Edlpww__c0DZ_ymN-Nl-X_iwnp_tp0V0e-1xyOVpbhzh1Fvo_hmKDV-S_6LW0
FFyHllx90l2Lu7pz9-0f0Cz_ulLF5e3yLUpwh_WxTpLEU7yW06x_Hl_e5_INd_y_xo7V3Kh-AdZzKsG1o5_5-8-4Um2G_tCG_zMFaBz_mFhd2q3-Ac3z-_tb
vry9Vgtu3pW0ybSDeFxf0f3_Sxxgl_HH9V-J0wp_FWKWVmrW_Mb_-JzdT_yf_xC3rFy-1I1_tS3wz_ZBppT0hViN603vF-ShjtuUBW3vntfmWFhlFmSg__S3
C5Vz-mj0VY00I_pz_l9VVxrs8Fn7Nm3a1mAmMl_z1I0_4e05_dv_-PCW0HWh_lq1a1yAm0f_lx_yG02w_1i283yKWDcWr-0lFnI01lu6V_c10BJvbm5eu4S2
qFFV7FHFSYrRWG6OBNI-53GPor9W04Q3lmNGu0G5e86_mT_j1mBGwZ-MhYBSVlYJpmR_XWAG7_hqBVpwty_o9xW_5m2tV_rBjF5p_lAlVv5hG_-HXP4_0TT_
XYu0-HFEFxo__0b_zHVk9f3y2RJ-8piKWFm9un_EN_xrBzZyZazy0EHFmFNd_ULFcAk_rfl99VyV1lpZdoy0-HEm_db_-PERgty-0F8dDxV-lB_yoQlzvK_-
_9MgmPyAWFm9kFwyl_m9TFNNr2j3_hyEUEk7Bm3v4x3-UN_vay7LFny0-PF1hJ_lBt-oe__ubh_yoTgN6nt-V078dmnk_Nb_-PF1NVtn0P0_6Tpwy_xo9zUR
_ULFBg3-6xx0aF-H0BJpMm3Nrln9GF_rcq2N_6tptAqV2s3ipvyyjVxwrmdy2N3rHmV0xVySOFrfVxV_Sq1__YQG_Cb2_SFpgs_iLLHQp-AVRd_p7EO_vF_g
Z6a18FokF-ylVwO1aF-5_lBhB_yrDnpvoVNdH_xT_0s0_1O0nwy_FoW_xsy0tislVr1-_VdvCVvwKD00vCthxtF0-KL_Jm78xqr0Zbz_Vb1-tjy0oEyn88vV
Vtum_ltFVHg0_Fpwwv_7-VKVsNdUpMy11ENNdv-7-VKVsNlaVtXoLW3kj8x-rra1U1k_1H2KNtz-K7xUtm2ycr__eFpwyuFoy_u6GFwZ_9qTVldOSu3E0Fdv
33fJVspqDm3oww__q1-PwxjNtXQ0ww-__WP0Vltrrrz_0o2__lfV-dzv2lZZtm9m_VNNtrC0ybi0mEZlx5QtFW2u_XQ0_dc5l-S-BG3NNt-l_hm2TFqj0Fqz
1shzMm3-clNtrtpakq79Rm7ehx_-1a1-_VK__oa0N_HPflF_u_hhhxytWUIt0FJNNty38B_--dTEwR_tqojcrFNNNty38B_--kllkKy3uFhhhx-d0831dbWn
gQw__lfx2a1-2-1yV_trh__QiGCP0000W47-rlVu2gDlLG0000000000000000000000000000000000000000000G
}

