sprite $catalog [512x512/16z] {
xD515G0G042naxF-RQK0_sqLDdC00000000000000000000000000000000000000000W15ds3_-yOz__ECV__YFyuz__ECV__Z7F_xnt-OV__Z7F_xnZt_y
ux_DF_xnZt_y7yHYxywrwxY1A8fwzgiE7l__Rnt2cgVR5AzgdvnOYxLBYfh0jzVdB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_w-r-3Fdpz__lpvy-VF_zlZpvy_
V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_NxYx_uYx_uYx_uYx_uYx_uYx_uYx_uYt--Vzzu_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VVtsF9lzyMkwlvVvQxg_b_jhjhmT_2x3ONqd_Gdu5_HlvbVElv5VClvDVAVzE
VZr2_gNy2lctykjd-EEVrown0FVx5umhq_GjmFt-_wIdnJ-_07d_F3___0BSxt_lhFZFZVu5__hv1nOWxf_dvvzVWFlzKuFYdr-0-_t_2i-9Vtu1ylvvVlxv
1RZV_xVKbFZd5-1-_rST4l-vmx-0dtzW0NB-UNx--GN8--Vv-USN8E-Vv-UV__q2_WNy_6Vtvn7yPpS__zdDptzsy_EVtVpyPpS__zdDptzsy_EVtVpyPpS_
_zdDptzsy_EVtVpyPpS__zdDptyw-VcBl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_YBl_ZV7t_n5t_n5t_nrxNn_azv_uczzp_XU_yR_iUwTlh3F-tq
ft_QwK__jDAV_kcvqX__QQS__TDAV_odbVxqJy-L_lXFA_tndrRwup-jzCT_uj_KzHBliTlV5rMFZVxuJ_mxkYhcoBzld2lzyPzM-kC_RVJ7VthopsMM_EkU
bblfZ_-qpfy_V_odwVV7_mC_-optvn_uyLf__84JQltv1ywezSSVEgRJdt_Wd5f__5Vk-u4-V_w1ithz-KSFkyhyyOUFw_Bd7pYlqvy_V_pv4uly-IUEvF_I
67_-j_ow_1lYpp_m-_Bdpty7_ua__y2v_Fdpx-4_yH_-_Fdpvy-VFt_-_Fdpvt-r-_Fdpz____pvy-VFdpz__lpvy-Vl-m_-_Fdpz_sdxx_vy-Vlxx_uy-Vl
xx_T_v2-Otlx_G_ytV_2t_rF_FdpT_yZV_U_ydV_Ct_tl_Ft_WD_xx_mz_uJV--_yVV-8t_ll_Bt_ZD_xx_pvyz_wlZvdofckTcV_vF_VVu5mvmtxiz_kYR9
__Jcnpa5_lolqZdoJrKmHlvjVr7rgF7dVnNmys_wfdgcoP__bF3pR_YgRkhy-Ky1F_-2xwgUmx-qpFGM-rk0MUnl0sRs-bk0vopsjm4pU_rjmCnUVnimizRV
2bmplwA_0jFgzbTWLEN-Yeoftr_N_uV3N_p5N_p5N_p5N_p5lpR--gyzEYG0001W6DI_zGFSJq45_ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz_
_ECV__Z7F_xnZt_yux_d_m40000000000000000000000000000000C
}

