sprite $filestore [512x512/16z] {
xDs5hSC040L1IrV0zL_jPsOGnJlJmkgT8B6z_mO000000000000000000000000000000000000000000000000000000C0nftJiZp0djITa_Ww0-Ji0vky0
cBy3OFuEWFax0ERl09Y_0s3-3e3vVty0q9y9s8-WFvEmxw4_4x5leJ-JiQ-XFnEoBw4_axBFq9-9sKVep-JiFVHdWlOM-ZD9kul-JDIYFvErw2z_rwA__5tw
woz_cFwdepy0000000000000FkB5qVvFD-Rl08JdZ_ax0E7vO_uEG7Z-cBy349u_vky0XETFkp_n_BJx4yzFkp_n_BJx4yzFkp_n_BJx4yzFkp_n_BJx4yzF
kp_n_BJx4yzFkp_n_BJx4yzFkp_n_BJx4yzFkp_n_EYl_wK3000000000000000000000000002ksQcZAeIX88YXNo-3VyMO06YRh8IzPyA_hrVzzLNy_Tpy
-UFbpp___77pvu-NF__yyyVDd_-vDl_9_ylddd_-kFdpF-hwvuzx_ldZviyVBt_--UUFcpz_lFpvvvy_RlxyyVBddt_-Urtebl_Fxqh-cFqBmFB_mqtDdp_k
-kS_zVppPsh-_77NF_-fvvy_K_FdZxl--Kyz__oPcZz_tFNFV-hvvy_K_FdZhd_-Kyy_VwRcpnzt_VEVUlxvCpL__hZhd__Kyy-VgVdpnrt__AUUV_vCpPy_
xlhdF_NyysTg_lnnrp__gUUVFrFpvu-x_lbFFV_ycPe_Vzprpt_g-UVFrFpvuwv__bFFFt_sbUFT7fq800030G3ojvx4xY-5_ECV__Z7F_xnZt_yun__-CS_
_l6FV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7_y1_ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__
-CS__l6FV_pZFv9__ECV__Z7F_xnZt_yun__-CS__l6FV_pZ7__unp_-yOz__ECV__Z7F_xnZt_yun__-CS__l6FV_pZt_zQ000000000000000000000000
000000000000000000000000000000003m
}

