sprite $speech [512x512/16z] {
xDqt0O0m54312SWM_swna5xlxQaduCVg94cI94cI94cI94cI94cI94cI94cI94cI94cI94cI9EdBA9uN_pSv_lp5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5
N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_pxnb_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynL_ynTzK_VFyVMfyqplCtwVovy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_FdpvvyOV_xy-VFdpvy_V_xy-VElYJz__lpvy-VF
dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lo_z6RxV-dnxx1f5__PLFpvy-VFdpz__lpvy-VFdpz__lpvy-VFdt_N-FFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-OVqPczwv5Nvy-yNV_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFd
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpxz7y_nzAd_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_EV5dpz__lpvy-VFdpz__lpv
y-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-TV7dy5l_gtHmS4000G3C3wjzO2VAkm0G0000000000000000000000_W40
0000y0y0000000000000000000000000000000000000G04
}

