sprite $cloud_scheduler [512x512/16z] {
xD6t4GH100B1gkNypJ_Qrrg_UtHdC31N1m00000000000000000000000000W9oLvu_PP-J1xDATdrUQ-kKNJo2_UO6bEt_ca_ByfRm_wSxNdu9y_Qq3ZFB-
_49_TNv6UNyAyllw3P0KzniWpVaMIFt_QPuWpVKcI7Ey3TByln7oB_VlTPVxFxNXm_y7g-ZUidSULWx3C1JBisNgzR__jZV0jJGAr0ynWKdWIk9MP_2u2wSz
y9pyt3EUObeiWjSF_lw_ucKkO1C60U13nri1Lc4G03Hp996m2xC0-94ZcGxWVix54yzOmWJMOQ0_UU1OIgbzjFu0qAECZmhWN3PjO20hyTT_fCZd4pYz0k17
ZH9q0CYWLvJXqdqS7nB0cJzd56FXObf_bAG3M3DZbAK3o9ymIjC1fCuteZo33S1PVsm26O2l_jW8BW1N_R4PL02U-cD3c00SzS_Oaaa4OAW_jaM_SaiBm4r_
R0qGW9N-s1uW01lzCmoOG00U-iE4bBF1fxl-C28ZWF7P-Zk0mrX_s94GGElVFe1X4C3RHmXJW02izNS0XZTwX3L000RwEm1B_uHz7fyRGrj_1m3exm0S_8Fs
UNoU3SBgxm04m-hl08PO0FqUlEjSm8x-OVlw6Rg0mze_hr_tSa47D3pzy_hr34G0Rlvv_NgDyW7Sn9AW7tSF7gB9vpzUlzuB482b_oLhLGvh2h3sl-0VRMMo
uk5XnYS0qxUfV6hz1X1E8VrQHA40n5D4lrPo5Gb01QYWVsev9G9G1N3zOk03K0bW_UAW0r0DIFrY6MG0gWAcNpm32q1rOFIh1fC9G9K0zAiE4mX0jLZzfQzg
aVGUYMtqIqjF-AaUIqy7gYBtFQF2It_-P3i_03HdIQhAo1akGNuYVn-df_tykXFa0xZh_sBlJWuWHq8WYbvI43VyztOki--jKeaausE1u0L8DKjtGuTU_4GS
VjCsuRVEEVxEhS9Frk4t3G3ybtFWuRU-UFWJUlXdrchi6_xvdSE_dAEFltVuuPzT101-0i3tJyRTWfy0m3-_bkiOrkvzw_UruHuip_Ml1lzVAcqc0N_f7seH
WBwUgzzVaeuV1lob_wWDleNWR_INaZV0pPhGhVvNzVvp0FYx_IK-0Tu9UstgBwal06cp_hMnlzHv5E7lzrSIW6_scRlxI_9O39ikfMyaW01CwL5tgjCV_dv_
BGBm-6-_6kGl7V5jnFgNRjS1yu6_H02syAzv_bARF_pz_WG0VsdqaE0lFHq03i2elZGf08Vohz7-Meq1OFtx_PKDazgsrgocz4WDlPIiVsbM00xqhnFyzTA_
9e5_KtyP703y-mC0_wx-gk80ZEj63nO78ApzrVbpcVNlzvV1ok3V703uD_QNzG70Np8-0DV0HlHuVTt_EcJzSwP_Vm0EyQz3_TFKF_0VTW1O_r9F0F1VO_tx
0y3wR-ulhmE0FmTWpUn08m_0sdpzyPVR0PZt_FXp_aip0x1O_ztzrN00nlhZV-7VKHfw0E3VtryUBm3yEG1Z7rrVBHV_nFzj_-JyFr7oFG2SV_pn_t9P-0V-
8my0wr_Y0E2FF_xp0k3DZtzCyCS_Z_R7dnV0M7xyyN-X1lhtP1R_rJ1C_AT-0NB-7_Bd1O0__lZtlm3Mk6bU-7STWCjw_V6F6Vxu2t_yySV_m7ds_JVB-BF-
G_npwWi0Vpu0yCSVVpu0yBzVMVYNiR_mnn__dGf_NlybVW3W_qhXZt_xJF777t_y-Vp77t_yyMy80Fxuuuy__lZZZp_--EEFF_xuuuz_uOy__lZZZp_--EC_
Nnz_StxyDwkGiJ_-ah4__ZBsnr_Qs3_nFu-VV_xlhO-_Dp_-tlpuU-lZxysFlxU-4dzdVXN-plpuXxE-XByrl_1trfVmj-ONV_uJ_E_xymD0ak_vnr-RLE6_
wlLA6Vlp0I3DyiSVVlpxzUT__kClOt_yKyR-141zrV_wnr_6_lXBW_q3__Fuyor__5CRLXtiVstrm9AH_rKSW4Vv-_tN_MdYByrVV_m7ykFV_yYfNIk_Fqpy
fHFMVzqR9Yy0IRRd7tyDuSS_1l2FyiS_TOn_u7_OyalrJNy285l_Almbu_N7N-FyyGydVJNCqUK0IAp_H7zlVlpZD7tyy-qdXp_BzmKWuLzp_GD-_6_NqfJA
BuumoZG0kbEi_tn_-F5FxLduhpSUNqFvd_TVvNS05lnzwz_VW3eA__uN0Fpzvxy_mHfL3SEpyMVzemW0ws_cN_2Fy2S0TPu_1u3rx-yZMV-T_Qyt_XaG_5Vj
MjzlP02_mVetTWB_nlu4e65cPlvbm6_Ytn-0VlxLu3_y0Am1_0RhtzTE6l1FyoS0nVg_rz0f_At-103-Vlyy8G25_zi_Q1pvLpNKhg7EdVXP__jTPTqhE_we
uW3ibe22lwynA_weKmDmZGr0iVxDhVNg6wm_0O1_w-vMgpx-_Uqb_5jLljxV4Ftx_5cJAiuEG3mmd6UdGm1goF9N6l3tPBnNd_Nlxx9N7_x-DZVNhp3mxytv
3lhmL_Prsgl_F7zMGysE-exuLV7MJ0X0DUl3tz_kLlXLCSv_VjwtmQzQ8_dd7xnemEVwxtNnye6_kuFhFxpfjzSU_bhxjHqtuFluLyskk5jrKYtVCH20gdGU
0W68sqNt1zHbFW7QlrlSF_YzHx2CUuyg0d31FxKOGphp4u1mvcSKWR_XCE1__bKOOQQVv_7dPmdmubSUnoyrd82f_58Uno-5IG3Ymv8avN7yKdnOHlpAF8vV
6H-MWVxlXdKG_rC121j-AUCOVfS0n8FyKiOX_8y687uYxqxIQuM160fFuEZEjF_TPfw62fWFIlPPGLt_UdqJTqqCz_snPk6l1v2_0CRx-LYJyCy_0CRxzR7o
-R_77Kse3v-VYNp-xp7R0dGZ__T4Fl_tkAT4_Ph_UoAV_tlCiu2Dk_c_9_BvlySa2n3tyKyr0C7d83730hYjwXjB83zwQ03awwFggUBugm5ykBDiVUflASJn
rmF8NS3Eq_oGnryF87C2y08_fF4_Fm2sF7puznEbyTS34BUd1FoBtqBo-E7pz020tlW3tpuY-1iC01hQZ_D37ZzwPm2mTyCVvuSa_l41ZDUAVfmVqlZ71p3U
07qtVaZZhmVmuP5wo8__n2YElnw0UB9tsSU_KmpWRpU0kXX-2E0V_Bppfv7dIEElF-zY6JJo777yrUUrMIZxQ02YBeuVTCXlUo7zem48g8lZ1ntpsolnsw3h
_1373phcjzVWFno086q0_3iTy4-tW1eDT9qVulY1Wj-UdVzu0E9CUVnGyDkUMlzu0E9SWVweuBVdvIy68FByEPqAVjkJwXS34ATBz4SLlpqZVpK04UZFbLJn
svvElng0k5AaFohvxRduom4izkzV9N0Ha-Gg49d-3EGoCK5o7Qpdx_z4VAbV8gtBtKGN-bLIMvqzWtxTKlxocKHaygaMyjzyCWBpsPRnzuNozUiMyVUrulNh
bl3tvTBrwnRmzqWRxTiyqlJ-7etMURJd-UFEJTQlo_BtAzS6wzTDxE_xYiMlQy2VSEnEctRVMfA_txoL5YM_wNWldvg8NvV3Rxz-QXv-NGw_tU3KDFow87-r
k3GBlow6tzwRN2eUINwa67wxqQKCblDHtAXUbsROrytn1J0tlr80VTaMms-tF7HdkBtZgxfZRGyLbrBNLtNRGh-FYZhRN-t1iG00003087_hIUoiPW000000
00000000000000000000000000000000001
}

