sprite $dataflow [512x512/16z] {
xDAvaTn050HH1KItLlvxooYHzx68FxqnxxcGcUy1000000000000000000000000003SUL_SbVV4NPMJxBqpH_tACTRUbJdgLywmgp98_JgfVcME_7LK_SeS
zIiljFQFhinHlqwgNvcZVkKbzgzbZlfrKlrQcQD-dLI_yd5Szz_BdBN_HZw8-zzaoFvRcQD-dLI_CaVzEgb-hSnHlwRhFty0N-wFEAb-vPzmVzHrKFvQcID_
dLI_LkQeNoVLhypHlrQUi_O3Cii1USYrdx7o2JbWFoUp3F2LlJjBajt6mIYS8P54ls7_k-r6ptO58v0kIY28SzxjEto_I5NUQMoZRmtD54U0wTTz-bc0LDRd
Au5Jz5a0-YmWJbyqItmbm6iVHy0eeCy2kFYv1D3d2E2rZmKKUkrZ09sZdoC0VHR0nSzN0bpy705IMPy59DCd6QighiyHKFftTx60FgJimyy2-dsl6e1eiXX0
RxVvZo45dtqMOFhcRqbIVVgDlZN-bLGw-Xb0l__J-4-IzE6dN-YR_t-JfFhqzMlVJtzB9AS-zQyl_f_-bYJL9x_-tD-IfFpallZd_fP8JdtoN_npVqkIwfF_
w9_xMv9Kd_pwStzBSdxUGuwBt-C_9Aa--VMjCKsIwjFajM_gxr-0PeZ4SV4x_8SarQUvlj_VagJyDB_u_VwMvDGdSUWx_8T8GdswVGr7ClJ0qBU6BpqnzCs_
xWBGD__22u3_7eK7WBxvrrq0-kPVTG7eMwFm0D0t_xeBWD_ygou0VMiK7W3wTniZ_GBG3_0VNHE4liE_x140l_aNM03w3lzo2q3V_0iC07s7Vu45eE_mhxC0
-Cs_m03GT_WNM03w3lyw2q3V_0iC07s7Vy45m6_-PHU0llaN603w3ly22q3VuLzd0UYRV-41m6_-1HQ0liE_t0BGD_yo0q1V9_ub5e2--lnLpri0_9Uw_OyS
00-_t__41Q3lzpzi0UZF_xTzuXKu0BeUuVVxdxW07dw__u4BGD_l_yW0cWQ7lj__W2C0_KkN-6lBkG1U-nRultO9q6Un_WB_j9S05_zYVvNq2q3Vx__e4I3w
OEWtdNRv_L-x1AWjvNVlx7j_7GaMm6lV4l-Kbm0N_pB_T9S0-hUkza_rbG3wA_spNGBeh_LFTmdmMUzw_oHV2V0L_sB_N0lWw0_mJt09eB_EF_yHWBxVFyS2
UEtxQA1__2N0mn_lhprg0UX7-ST_78J_gk_0SFZlTWdWhnhc7_yUYB-6-STV0lYhHld7NmBugsxghy_xuwyQuE_kON_y5ty7MckBV_uVzCTV4_IKF_wQf2Vy
yTSyjTN--5-QghN--6kwrldZhncJDVxuQzOM-EElcVkbF_vDSoU_ySTVyuV__rL0tx40_9twDGU0l_NcTsYt1U0Vy9tPPW7uHtrFjXW0_asVBcHvc_Zp_8Tz
qpluun_uZSVxS_w7hg-s_-Np_mHFy5n_Zl_0xm3-BTp_zdMcFy__xUmgxO__VQ8__hU_y_pnRwNzyR-_wJH__5jfV_plxph77t_yyRzA--D_Vnl--EEFF_xu
uuy__lZZ_u8B_eG_uK_uHuK_uLyn_E5d04huLmt_ZrQE0MZbyB_qk8Z77__2_5JSd_RWfx2NhNX-2lroEvYVhk2_wZsKd-9_uZVYRma_RyZ_Sxy9Vzg39__P
6w__INttv7_tYdxsPvNcjsAFtr8N49-znFoar_pwutBwVtW9uhFtshVWnQ-zyX9qukcF_-sBttl59OZ_SNrkT_pUQrw2yESGn1z__kpb4RMIFmVuSmZYh_ZZ
_sNudykFF_xuuuy__lZZZp_--EEFF_xuVpHz-FFH9_xuuuy__Wg_QjcN8Fmv18lpuu-_bluQk3W_bs1nVgkq_wSsFvTWSNukmLQO7t-hE3ylGSNv-Gk8z_b1
ntpJ_0N4E_oWhwt-zZTkmL8BBCiVV_fQL_pFV75zta0R_36rNGxVylfy0WM-Afz0Hyl3ptE8FmE0dm70Zp_-381__Rr0-7C0m8y__Wm0V_pXnn__g04G_eG_
26Vw4_uo_fYM2l_X37_yNmj__F777t_yySSVV_pnrwFyyLVyVU6FF_vwc3_-MjiV_nR87--FlwRn5_pF_FD_AHv__FL8V_orjZ_-6llju-yg-7kWv_hZhw7V
ElxnV_WwyDl6tzcfV_ac_bii84WV_st-zRChGby7_bzqt5--EV3_BisJNnz_VpNqyPztbZx-5HVGnYJyFTLu-F6VLqCV_tbdwEDVQm0o7E7lgyR3Z_-y4lhu
pwkXZ_-yCoz-_FrbVlZn3nv0-r4VFulGnz_VqZy2DduMee-_l-jP_o1z_FrjwZzUycS0zoB_jl2dVumeVnOGxpz6b3-NGBp_6FZx5LQrZV-8yUSI2FMFrsS1
0VxeB-YwLnNhtyFrkGG2_SVAcZuMbu3VFqY_Qxa-zwfM-YUy-3a2sZh_bFeiu5L_oQFF9R3UVwnCzFcu1Fp-UOz-5h32_q1z5k3txwdr6S3rvFEVL9yZmEyl
1pxyBC3lVu0-0_WizvTK-YnWiNzkVHRWzpzHdm7u_K_yj8y5-FrFUkrZ0R_sFqAV0VZzZzDd0NF_Fb4wJ9y5-FtFU-tZJufyut_YmyyHuFS_Kvy5UFsFrMS0
jyV_M7qMuF9ls_7JY_wLz1b0BwtF0dffVHRGI-ipW5wQdmNqqleie9VMPm2zj3uBwANrMK3Fo4yjr3zUdsBzu_Kfr3zUdwvz_9i6HBluQz9OG2-jpoNGi-jJ
gB-cZWMSyDf7dn3_hhj40VwQFnPGMvy5rDPd0BN_B2SBgFtmiu3Q-WoWjZuBgAtF0chpCu3Q-YpWL7sIjj1VaqMcrjRuYsY-qBSM-ClV_f7c2tsh-_td-aaN
WBxLVk4lnfzu0V1RVzdVz9CE07tV9U3MjqIJXBxt4d3evri0-kvBm77nfxW4ICQy-INWq4zt1F3m-oy1nz6VRW7e-nVWq4zt2Q3llmGS-kaMWBx_29XV_2ak
0MhZszhKtw6Vu0ZWuVTV0isXdsq1wFkFWERGpxO0zFqBQ0xzR0D0tty9DCThNxO5mEzVG7Cy_2Sk07shcR_frni0-bPl4_q22q3VChn42o0P2rFLPGCGVJvQ
h6-LF0BG5xLgBW3zeV-Vh1h0q8UY_e1-bYE0schziWlWjM-IrFbAW8kV8m1z5e0-bm0NVuKZ0FscgYo0ez-H55q0-Xm1wCSlWABr2_p2C0z_eIC0VHR0B_Dz
ttXv0HIg7ty4KAn-_08eb3_-uo1gE-bRgVmv0dHzQVHPW3vII_4n40je-bG97du6e4-skJuBqAVRM9y5w0ljUl4p07sfBVLPWBxNTleiG5zjhukV0UZhxQFF
0ZIaFVXPW4QrWJu340qiMfy5Q72H-Yn0uvDtzKaS-g4B47qqsahVUl_XPm6wKr9SdwIuFd7n_xqzE10000004EHlFS0ArG40000000000000000000000000
004
}

