sprite $partner_interconnect [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000000000000000000000000000000000000000WDcvZ-i8G1Y0Wev8D_hlrgx0tYXO
DBy3lI7ST5xZ-FgPudS0y3i0_FdZTm3uYx_uYx_uYx_uzuY_-8k_-8k_-8j_Z_YBl_YBl_YBl_ZtYB_uYx_uYx_uYt-J-8j_VOh_SMAAl_YBl_YBl_YBl_YB
l_YBl_YBl_YBl_YBl_Y_Qlp5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_dSLlhdSuD_MGN--uw6FsE5VsH9_2zeXN_MXF-IwlspghFy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpv__kA7WVsynRkWOV_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdR_-J_L_y-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VDV57_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-aJLzrVj_PKqn_yq3C0lyjntD0PW5_hkEvW-OSud_Rpky_Ihm5t_n5t_n5t_n5t_nFol-uY_-uY_-uY_-uY_-uY_-
uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-uY_-ug_H9DBynL_ynL_ynRz9_CLV_CLV_CLV_7l4N_p5N_p5N_p5lqVynL_ynRzZ_CLV_CLV_CLVZVd5NytvrPrV
z4kJVjg3Om400020GVxMazXPNG000000000000000000000000000000000000000000000000000000000000000000000002
}

