sprite $cloud_generic [512x512/16z] {
xC610000080WXFrj5wa20000000000000000000000000000Pky-qeK0WJ08RcVd_KzhLjO6y1kx-WJm5yQN_ccp8l6_4d_n5t_n5t_n5t_n5t_n5t_n5t_n
5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5t_n5_yxyHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_
yHT_yHT_yHT_yHT_yHT_yHT_yRyJV_4NV_4NV_4NV_4NV_4N_qrBnVpvTs_8ltjB_jsRyW_Vbd_vmlp3L-PVlZN_yBtv1s_E_rI-Et-tlv7xkt_t-WPewvkW
hM-4DhyLw7-DVvBV46r-IxJvJO7_nB-cRuqslpdQ_FPeynkapM-HDhz9slmsQVCRfSlFdxzLslncQVFRfSrlc32_PVZpJ_ER9inl6_xyq_p62VDRXp__DBzv
mlpsuS-_osyW_lox_1RYpx_BRoB-_BFy_FdRAChFdx-H-FDFyrkfRMwnDhpXslR6QziRiArlmZQ-5U5Vsv7_XrByz-aRiwrlpZQ_FTlw5gN_rrlbt-OtQflV
glJRk-9l3uk_lIpzQstnnnyU5__DblZZpywB_svB_F571yP_koN--9CJux_V0d_y_Fa7HyR_eYN--7CputyJ_mNnnnyR6l-h-2-8F_xKrFZVnNz1_F57nkRF
7__B-2-8F_x4tFpvutyR_mNnnnyOd3z__2_ZB_uBue__Hlp5Vs_yyVFN-itvy-VF7__Z-2lWB_xYlod--E_7Nm5_yHT_yHT_yHV_1V77Vo7-uY_--k_ynLz-
_vT__uk_-8k_-8k_-8k_-ClN_-1F-Ok_-8k_VFyV_3b_yHT_-Vw_-9F-uYy__mD_qb_yvUV_uG_vYx_y_6Vnr_nksmya_fe5_Xu0V_xyBnm9Ft_y2_mz0FuU
G61g_loVd4gpmTy3Y0tDd__zSsas-7i0kPddmSaq_1V4tmEeZJpNpwRPuEy192UUowVJ1Fm7yzA1v-hvD17_GRrothbuGat8Vt0l77V60oXlEnv0Ujhn0DBB
pdW1vLt70qZFEka7ODMv4Fss_-1l-f_eD_rFRNt-qzJdVuhgypyrzVcVclhyJr5y_gUeFlzJrPx_gOlF_zIMvwzFxT590G0048IW_gqD8lptd1K000000000
041K000000000000083M000000000000000000000000000WVm00000000000010_W00000000000000000000000000000000004
}

