sprite $onboarding [512x512/16z] {
xD4X0G1020Gm0o2_VziFWRojmjuD0000000000000000000000000000003CR2ncEldVVdzsxi8wT2280U37HDT_mM7UCESqRc6yUZh3LllJl_R_rtIvBlGh
vz_rvuA_rb_qywVVwa-VF_tftt0KKFfxvr_fvo_w-TFdJvy__U6_vr50wJV_IZz_qS-VFd_w_EaF_rsF0ag_-LVw-Oj-_lJvq-TFV_hlUXHG-is_qizVzFEd
pvy-V_hJVzUZWD9l_fL-_gAVFtt-zFdJd_wx7WMKVlElzFCN_VpfywVFd_xqt_KeeFIRVwMVl-ZdJvy_VVxqf_-kHm6bt_mh_Vn5Ft_w_Edpfp_zlzDHGEat
_qe_Vz7Fdpv_-lpfx-B_GF5L-is_qizVzFEdpvy-V_fx-olznVvAFt_Ht-nFdpzz_lJvLvP-_ae_Vz7Fdpv_-lpfywyi_VoLVlwYdpzz_lJvq-TVMVhvA_ty
HJz_-lpfywVFlxBqyrVw-Oj-_lJvq-TFdtzbwUUlzFCN_VpfywVFdpx_ojBFN-ddB_hvq-TFdpzz_fMbdx_Ipr_qywVFdpv_-lmhIpz_fP-_wETFdpzz_lJv
LvP-_ae_Vz7Fdpv_-lpfy-yi_VoLVlwYdpz__ddualyD_BqHm3zhy3l_5UaFViz_YlG7l-U_JVgJt_kV9lt9x_rlaVxa5m47-7t_rQ1_Fx_lFrlqx-Vt_NU3
_iFy_lzeq7-Ot_zV1VeFyuk0Wmh-LVPgc7_Mi_ZjVoZGNrMVX_3FUZQ__K-xwp_ER__Rxlghw1j1_ki-_f8xW7_Um6__yuRwAoLVYlFFUe2_uGxWlvx5ttGK
u9_ctuNuf_c7CVvf-6MGVywlU_bhxm3pd-RVXlcdUMq4_pHl3k2VvjqH_BFvzX3-6TVWBxq3p7-QDmZnJ_C6EVvfNYB6FyrhvFXdtqM2_FFODVZhxW3pd-Pb
elpJl4oQVwht2VDltYZDFrlk5EUVPrwsoll_vvYzEx6IMubX0FYF0P_oZzW9-BP7Q0sBAHGQ8dtiFZG1_FrU6VugWBy4y9S0_jUlp_CIm5y7y7SAy5S1_2M0
_-iFvka9u7_zqUW0_Iy1_9q2_5K0VmbuYF_hxum4FDB_-bkZ0_I_1F1t2l1N0Vmbu6J_rryV2NYE__M6qG7wNmBuEmNugm3-4d2S_-kT8m67-r_l7HsW_oM0
lrE0lmhWBm5d-Bzk6WauqV-wRNI0_fS0_au1_Yg0lmGK_L_tZmGSutyrHWVeVmdWxnGupj_CNv_T_lndZlEtq7zp9haX0LL_w_pt_Pi9qFzz_sO2-lxytvE0
_sQUuS-_M05zV_wd9c2EMlglZ_K_DG5ZwR_5lvm0_T_txoUWxy-_SGhq_VaNAw3lp__K18obl-1_JWB6qb_mBoH0_zVz-mde-_Fldm9zV_xz2kZxy-ydO8fB
F_z-0iRIN_0l943_r_tx2UZxy--V0dr__lqAwFlpxoTWxbpw-RSIuFsN_Ui9QFlpxoUWxy-_UGfK_VdtEw3ep__8Zy0Kbtx-_GGCdO9_Dm5TV_xz17Jz-VTF
WQu___ufqFVdt_y8J6lfvzzFmBlU_uNy5_oR2QZsF_z-0ch-_Fi9U5oS-2SxzVcV7u2Bz1t-oMvz_idkwkUVxDRdd-pMvv_T-loJtMiV_sItFlzaT_NpJtRh
yqzsw_FFRdt-oUwrZt-oMvz_ihdw-VldlFoJtM-VVtP_-Fadkzy-_sJts-UVR7xy_9q2_9FTRvz_Td_u-IUxtpx_PFVRvv_iVlpyaztw_9FT-lmpar-P3mFW
d-n--_oJtVpyaztw_9FD-lpzlH3_p6nU-ladkvkVVxARdt-oMvz_ibcVlrE0VsP2f-3_yHLW-1l-Xh-PuV-zaG3-0i1V0lXB0F_hKsU6lmxWBm7y1O2_1F2N
0FuIm5y2-4l0Bdy16FugWBy4y9S0_XB0NmBuEmNugm3-4i1V0ZxA_ogDVoBc_Ui0_au1_Yg0lmJmbu1Pi_Gx1Rn_7S3VAS1V1V2N0FuIC4zO-isCzwy3-3i5
-Ai0_XB0NmBuIm1_2U0l0Vm5WBy4bFolkyVCUFywWBy4xFKtmry5y9U0WlzrnfWPxry7BFOt_ytmTmhmzn5uj__hr36_d80lxTT10G0W00Ant_MFJ12s2gX2
LwNV5F3--mNaRmh8tnIGlq-Wwz9l2dHL-aq1xxzVGFwcWFnD0Vdx1Bek_QP0LwNV5F3--mNaRmh8tnIGlq-Wwz9l2dHM-Ydllr_WEtzJGFwU0Fax0RsMVkhx
_bFV-TDt_W000000000000000000000000000000000000000000m
}

