sprite $agent_assist [512x512/16z] {
xC6X0G0030AWkhR_lpNRZS2l000000000000000000000000000005m9EtTira0Kn60mLNRzTqiFWFNflECKWDMRF-RW0x2N07q9q5S0VGNWFn00VGNGLm1-
0T1N07q5q5S0VW7GLm1z1U0N07q5q7zv0VG5W5y1z1L0Nm7u1K1V0VGLG5y0-1L0Nm7q5O1V0FGLG5y1z0M0Nm7q5K1V0VW5G5y1z1L0Nm3u5K1V0VJx1U0N
07q5q5S0VG7WLm1z1T1N07u1q5S0VGNG5m1-1T1N07q5u1S0VGNGLm1z0U1N07q5q5S0VW7GLm1z1T0N07u5q5S0VGNW5m1z1T1N07q1u5S0VGNGLm1-0T1N
07q5u1S0VGNW5m1-0U0N07u1u1V0_FiU2W3_mAdyfz_p-mB0__Ah-VUVyIlyyPyzddzo-NxyboVmFpo2_-KT-4zFuNzv2__BQ_XVtiF_z2B-foVnlxo9_-bL
_FzurwjdyV-dYzuvZFz_NlEwPVp_-vHNJUF_aJksjl7lIxrY7FyFdj1Pnt_Ng32F_pHGOH__QPt6GFxBDAM5_0lyWm7mtrTfRkHVuky7mB_Flny0_tt-96_m
vvzaFW3-VVv-0Fod-Fi1yE_p3mN0lwzG2O1_tx_Ftm-0_pv_ikdFFzaEW7-VlubonPz_-1VyT_bJNCj_Zp_PykUV30R0_slv4_xy6tlvJ_8dA_xyC-3V6Cp_
6VBFXZ__P300_lpvB_Bl1y2VF_zz_eG__zPc_dFy2V-U_yEVVu5_vQPzV_xXN_3dpx_0Fn40V_xy-VFVv-VFFuNP_Fdp7-Fdpvy___0l-3_y-K_ofzuzV_xy
-VFdpvy_V_xy-VFV280_V_xy-Q-_CN_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvyz_yXr6_oX__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdp__FtnRuO_UyUVFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
dp__vwO_V_xy-VD_vltv5m8uwy__kUtF_tcE-FFFtV__nfy__zprvy-VV-xwy-VFFxVz-UUsF__SzkUVs_xySzkVVsxxyyzjV_x9RN_-oMr__ibjV_x9RN_-
IRBjp__4Xpz__lpvy-VFdpz__lpvy-VFdpz__kk8V_Zmvy-VFt_-_FddeZz__lpvyy-x_Fdp5m1-_cEJ-VCNm6lyyVDFtkal0Fpy2rD7_GM0dtzXv8o_0FQB
501-0U3dZry0-1M0Nm3u1O1V0VG5G5y1-1L0Nm7q1O1V0VGLG5y0z1M0Nm7q5K1V0FWLG5y1z0L0Nm7u5K1V0Ilw0i2l0FeAe2y0-Wh0hm3w2g0l0FmAeAy0
-WAWhm3y2g2l0Fe2mAy0-WgWBm3w2i2l0FeAe2y0_0gWhm3w_Edpny-VFd_w_F7pfy-VFd_w_F7pfy-VFd_y_Edpfy-VFd_y_7_OenC1000O2408vsyxZ7sb
K2R0ld_z_ktxj-_Vld_z_ktxj-zVlt_x_ktxr-_Vld_x_ktxr-_Vld_x_lNxj-z_rpxs_UltRz-_VV_w_TltRz-_VV_w_TltRz__lNxi-xVltxv__Vxj-xVl
Nxz_-_xj-zVltxx_d8Dz__hzs_Tltxz-__RzVzdthz-_VV_s_Tlthzz_jKS71020C0238jY_hJ7q7rJWH13VfzrFV9_sFlL-Fjq700000000000000000000
00000000k
}

