sprite $cloud_interconnect [512x512/16z] {
xC610000080WXFrj5wa2000000000000000000000000000000000000000006RdlWeGYg4e258lyQyO2TINTcOjpFykL0L5cx_uYx_uYtzG_CLV_CLV_CK_
9_xYB_xYB_xYdnD_yHT_yHT_yS-9l_YBl_YBl_Zdn5_ynL_ynL_yS-8l_k8l_k8l_il6dx-Ez1T_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_
yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHT_yHV_Qx_k_PhHdtzrYpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lndZpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz_
_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdt_xiJl_Ttkq7vlHl_Zpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpv-__oj__sV-PFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_FdpvpyW_lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF
dpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFlr_ynL_ynL_ynV_N-8k_-8k_
-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8k_-8l_-FYBl_YBl_YhWdgsHmT400001CGYwDzMZxyj0Im10000000007K10FmF00000000
0000000000000000000000000000000000000000000000007
}

