sprite $private_connectivity [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000000006RlBX8cnzKW08fTEz__j8yPozEMVa7aVZ1IdsHersPfVyXzIcX_
cVl4aDS2y6g0NWdOwm1x7M2l0-pdxu1SJ_GqmD9N0VWg05y5RFeQOEch07qDeAy1z3N0eKy3w6k0mVyy5wTX-eO0VJC0ln50NmCS-XN0ujS0-XfWz2k0nQy1
z3K0lmBGN_z-87uZ0By2qBS7u3S2y2i0VNi0VYC0lmBGjmVWDmBmAm1-1S2l0FWL0By2u5S0_0hW7Ly5iFZT2iHVQyavfPHpBgMUCWBmrv9JYk7VabAkcnS0
VqdXVoKEhO0ju1gD_qLIsMy0MFxrh_ZJLG1__vGO7YQEgm3-0VhF4-iE1S1VK_YDIQCQW7-8_lEajGk0FuTVJ5wt0FXpU25bpGBWh-6TnBfW0V2Ny5hASWN0
dyEBoOlT2UQVmgj9Amq0_3M6bnFhCWN0NqA7h580_3bqILdY2C0_XKx9-mm0_37bNFwKd5FSfG3uypVqfVw7zmFY35i0_hUEVizVyQev_lWXyEBVyvvl_Z-0
DVzq0V3tuy-_le74UNS0_2q-rN_UWBHa0HpzyzY_qVWZ0F_ytktRyfCN0VX_KyghGpjjSmPqzYilrwdr3lyN5soiRnSgh-Dl-SVwzbDaEy3pN3zrwHTx_4tJ
RFuEVtsauj83m9sVsE7lEzzT8Fwbrpgj2mm0_AsVKbtsEO27_gNZQ2dp-FFlkacdoMy2uSzzXIP_6On_vmbT5Xm0tlbAlIykwnG5mDzIx-LPVsW3kFX_amSw
0nesU03WB_rnwc9_8ipuJmF-6Na2V_njnDgi3-u13Zq1yAz3di-aEJS0_2qFaIahRG36_vX_J6pzWt_O-7--0SpfR_oNGLUPvQSBuFF-STIwz5ce0Sj_OfRu
y02W0DSG_r7dyhIAlu-ybc47ZJPX0NpbjGve6ly1_5EjoWTDUpdyPzYLv_iuFFuMnrsLnS7-ynU0V-R_W7_KvV-uhIRDvyy_Z_G_kG3y8_y1_FFwXtPA0VXd
_lpv_mG__yQVloU__CzS_lmRV_xu-SyR_Wh0dt_ZtoNy-VF_uaz_rIv94_dphpd5C4LYodMeF_wImcJ9TLG1-9SO9aoi8_pvrnWcJQhT_VcdC75oupzWyS-R
f03ZBlSEEmNmhs61rBFzhyFvGpZRl_LBNCC_7bs08IV_ymw1_7DO9kLS_zOjOQ4CyBVyZxmFTAf_3Kk5_u33tpa3W7zOA_5G_wlrIGcBfPxbR_pR08n_6u3J
_r_3_wpjtm60F__UD_yy0t3yNoDvJV_yIocz_VddNylY_lpBpFwrfpz__lphpFwjfpz__lmR_qd3l_Jtvr_upnV-_FbN_lpvy-VFdt-VLFvpXJz__lpvD_xy
-VFdpvz_f_2VAlpvy-VFlopXpvy_V_wfbDgkgzMIqs7-_7EzFl-GgwPZ_9t_OltyXvGp_FcNpt_ELVRtvv-lpt_DbJRtvry__pDbQt_-xVD_KlVrvn-lp_zD
s_Rv7__hyqNQflxU_sgVhrAtzETVFbycR-ZFFts-JjpFd__rlN_Rpfz__Zn8sktFV_6_dlXVc_dpBvz7oNlv-_x3zSo_RUNFFtuUPYj__kMfVzx9dtzxwbzt
-lwRx_zzdkRQo9z_-ZnEtEFxhxx_p9z_VkwVzld-kzz_AC_zypx-_Ejp_tA0_yI__sJz-_qt-pz__lnT__7_jSJd_c4VV_xXUihVTlBdNv_wbvty-QUd_d5I
_tloRFB-pnMsykTVd_cNlVpvny_Ax__o7pi0ocx-_EFLOVaFzx-dJp__SS-0yeJ-_8Uz0rh3XFxyHrq3jh2bF__u5VyLv_M_5yYy_Y4FUF0xhp__aAu1gt-0
F_zELu7jL_dvNpFxXz0wdFn7-TzBf8l_Y0_0jXHczUVVlG5N3k44V_uXvFgl-FKjVVvt3__Nasgx_cBVIbhYzpzk_YydnhZCx__mdp_y-VE_U_Zplq_rvy-V
_tMlL03-vov__lpv3-0_f03y-VDVA_pFvEVFdp__c__1_FpvlnV-rtro0VZV_Fcl5lxdylFdV_4Vm3zn-FFdFu1_rl3dpty0_yu5uCy_h-TVthlrgm3bNFyr
tVdNzvQ_0jJr_5zS_lmR_rLpw0L0VfEVVrbq--T_dxa1lClFFwx5dzxrLu2owFZ7Vr_d3O3qDhy1K2t_PNFQ9M0-cTy0YAFk_2g0wUyQ0F_yEUWrWD86-2i0
VYy27FVONm7grFgn7lpOrxk0kNNdvzzgMl2cB_-xRTs0LF4F_290pN4U-vXhUp4t_wzIQya_dLBgb_RyxoQ_mAy0-BqAWjy0uAy0-1K0loC0VWE0lmBWLm3y
ZW3u3G3-2e1V0V0h07u5mAy0-1K0lmBWLm3yRWJYdo1Dhbi1B7y5mAy0-1K0lm8u-haCjFYD0FmAW5y1y2i0VWN0hm3u5G2_0k1t9uY-4O1V0V3R0-WR0VWL
0ByzWBuHW5y1y6i0VGN0hm7q5S0xlXfWyMi0VGN0hm7qtH2cRmJWrm3w6a1V0-Xh07qDSAzN0-Yx7s3m6mBqDO2-2i1N0VWQuC2l0hzljxu9001X801kCEBV
BSmOIBkJaFed5pIVyRrdZ-yzuXxBucFj7-pyHpBKU7hs6m0000000000000000000000000000000000000000000000002u
}

