sprite $identity [512x512/16z] {
xC610000080WXFrj5wa200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001Wzkua
tL4b1gBmQzAIPjh_RcjQdMmI54IcYJDzpVN77-2cgEkBsR7o0ObV_kANl_XX_ihZBpcP7--lua04VhY_yfYAm8_oLt6oX6TWVpNYKc1-gB_oQ0Z8p_FNcS-V
WE7yLJG7u4VvAmz007w4lmfO07w0l_HnmVdn_jBdBy1H_jB7bwY8_jBdBy00_jA7D1ZyjRyQSNC4_j9V1I40FyTV-lm16CzV_Fm56C1V-lZOzt-h84Uz_ri5
FUhztzBdnxt_M_pyzhp_M_njCzhe_c_Tu-60HM7uvTzCDM3_vzNl_zRPFx3hydR-b7-RpnqBw-Ol_TLTJyuna_Voj_YBtszSMYT_Xx_uRtwbqST_tL_yVl_W
clppkh_u5_-X_ea_B_2Bd_Hp_SG0AkVJ_EBF_Xns1QYSJ_ABVoGar1MWSZx7Btxopy_P0LJEuWSS_WK7K3cB_yGpS8833A1o5l-lOVJv0wYSYVpYhnkm0UIl
JVBhwh_E4iVK00hdANxnUzvMxnIzS1R_p25FQFW1v1yH-CNF6a3-6PzV_7NuHoJ-mo-vhzrykUW0n8yxrFPx2mu0nI_-fhkh0VuAVvojwW434B-zwq4343z-
08bE_kJViUTx3K3ytGC0VoQjaFpu0UGwwVGtssm0oW7yW060_1M3trw4ZLBIap_-JK0kd4v__3E0Pv42d5WS_uHS01IGV_sNW6fiuvzh--lq7m1_tW3alznt
hJhGN_ph-oVfBO1E__Nz8-TJiPT_Bkolqn_Wpte587y7-6z-0T3fp_SVj_n66laxsny_MULHbglwc_pR2hO_zPgb9lWX0w2ELeqj_PFWhzDV_jpirvxahm5q
7Zpvr_t_zvBQi38EVns0d-pF7u2zon_fdr7btpQ0gMCe_yZl6W3dAERf0Fmm__K7yCA-YkBx8wUx_m1ORwDz_I_QZWSCWFOvAd-qUF_r1s0pxUoF6E_-0o3U
I77B0q-KFtK0V7_-9HJ7Z_Vd3u1_A_KTZprX_WCx03P_MjKw_WdW1ppybGVmuQ1X_T43y8JwWmT0uf_wD_W747lou_sv0pXmq1pbFx8b1-W3_0430F1V-BU8
nw_GH_llFu23HmtZZxjruPvRr-T5vxlNtm_U6388_hoO_l-JJ__wNvH_WFtn0pYk2lQNVzrj_Y-2l_oP0vX0dNm18F_6qFpp_WPu-IJ_iWNy1y1V_jm1J97Y
_ULVzmX_-TSzsb_-G_wqlC4VpY__uj5Hptyyl_o7LGtg-O_dr_i_-npf_8Vpw_CVEzhU_cF1pt-JxczpxUi_llNFVo3uTRwd__ZQF_z5wTTjw3_skly3xp_i
IhlvZpNl_sevV0uyz-kMlm6uvjVzdzOGnX_Fh_k_hIceFvwV__S_E8VFsXeaVnG__kz_yVsjjPnfTtxyt__4-rjpWCUFukV__M--lxL7y6VorstmycaO888_
axzk_VTF1edYFyylVmD5y2Vorot--Pd18lWJ-UkM_lL_BuCrBZrw9_2p1q3u3Le63B1U13--rxBVecFGyFvyVlwTTFB7y-C7a8_qZp8CFx6h-eYNK0OEuBzl
0_IB5ADiO_yychx_pJVorpT0pkB3tW7ANr__Qk3yqVxoDy0pbpf-68tlZp_zLPJ9Vzda7sMUBSdVz_HFTBe0yFqTxoz_v_gJB__oZntzioqDOApg7tH_NG0C
7VtoBtzd-lDFVmr0_he0BESVTIEnwGB0ztV0wI__glNyuod-ykVpQm3FzfT_iFtn_6eRVoVwwmB0zoVoQm1y_o3uor-FKWDuy8EKVpoRNmCmJPINZgxuTNnT
_ap_q3mrW6KVdEULp5B1Zl7wsxHV1Y3_gY_bJoCCG0DWF2utA_mjyMa0V7wpmjyoLNngR_u2sl03q03u3ycjW3R203G06d_zHKgfOgq1M2j_0MsB3a03YC_D
y1VGDZK03S1tvI-WJGC07FK5-GleSXZo9mx0-_aBQDC0fe-y9xW0yviL_Xf01lqICA9lWsv5bxv4NGDmyi-FQVu2sZI01W3Kym_oImehVnN7sk17sxlaVr71
IJytCbi6KFWhYuCvKX__5VM5l_AuVG41uFyuWC9VUI0ywe0_pjxLuAy1nDe_owRA8hq603qDHA2d9ly66Cm4Oh8yrIb_5TDn__zr07yDe0Ztl_Oy7S9V0wW3
_q_dap_mfNdTX3luamQalmQ0Bwzspbzjnb-thRy6uDdHfluQG3QrfRyMa6tjvwy1j8hivgy5P6zR-Mi08xixxQysE_dTpfHbolUwzBVxgxsU-FlzrLQV-03y
rKwl-X7-2dxkzxMTlnQGhM7y5Gg_FPI_0kWZWlah03wWzVtrcP0dCAY_uk7lV_-t9f1tXFTNphRdt_-j-DTy_ltVYWTV9_yVxS6n00000C0WV-j1xAqU0000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000W
}

