sprite $permissions [512x512/16z] {
xTr7bkD844J13HyzOrNtF-se7DKI8q4GRlyAvWYmgWK_Nf4aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIPAKtTfzj4Jzq-QJRhi4hNorsRMim5D_xB-xyGOyzv_w
ttK3oc5pr7qd07_xjqu0_lQlc81t_h5_pMS1Z_wd_fL7WFxsRrq0_UtVkW3wsxzr0VItV-i2w6__rWNGt_wj2w2__OiNW3zJC02_x3lmBro0XtytjGEWl_sB
5u0_Kpi0-jk_U07uCyq3m9zf7W3-p7yJZtVKt_wz9m1_fda0-3FD0y2VQHu0_app0F1dcWU0FzCy0FoPvW7WppGF07-cUG3uCyq3m9zf7W3-JFC0y6UQ1u0_
Om3y__julGT_fda0-3DJ_0R0dxd-0FGumR_j5U3nvuy_CyLl0FmP0-3V-WR0dsa-0FWp1i2_zGs0FzDy0F1d381_wni0VyO1uDzw0F1d703-hGS0VyO1uDzw
0F1d703-hGS0VyO1uDzw0F1d703-bpi0McVvDny0Zt-czG3mvuy_umN0l_K0uCyu0FolSm34N-j4_yO1UFpvy-Vl_6UQ1-3npqpfJu3yFV_uCmu0V_xysru0
_FdZptW1yEVF_xKl0F4NV-NE_eil_wBu7xy0n5_ynL-vj_yYp5_ynRyk_aEOl_YBl_YBl_YBVq7ynL_ynL_ynL_ynRyW_k8l_k8l_k8l_lBt_mlYB_xoxx_5
N_p5N_x_D_7Ne_l-wyx-TFdBzp-8ltp_a_YBltp_ftp_i_Wh9tQzyw_dFVr3zde7mFddttl-lG2wpxy3uFppxpp__XAGvzy1k2I_LhU_SbBu-NT--lC9qFFl
0FJo-mJ8tm70px_tqvy1UFpvzpx-1j3z-FiHeFlnTm0y_lnx7ty3wEOt0DUVV-_ZRm0UV_wzZxy1TFCRWElFl_VnDu1kVWFelVx-78Y_0z1z_GsW--atW5v-
7m7uEm3TBty3wEOtW6v-0-X-znj0Dx__5gxxFthpKs3tu-yDqFtPpmNevdS1klbTW6v-5w2Rtm2w-GsWczy2kd_iDu3kXzy0klaDe9lV0BhvBQ1Rtm2w-GsW
czy2klKDe9lV0hhr3Q2RtryAwFvzlnlG_UnRm6tqTPR_kW-_Vo3I_SyxB63-NkjU-bu3tUzz2-ZMz_k0xWzzZa3tesy2tVXU14Vsy_7UwN7WtuplLT1zz8sW
-vE-5Nm2_rLvIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP9yAV3C-gtvgCitWSyd-Iv8t_zUi0JkX_xl_Rt0Nkp_lV_kRJycUEIF
_GkEWMV-mFy6A_3Gd-I_k_O8q1_xTum0_R5_n-i0_QV-PIDW_wb_smROV-hVjW7sd_hVO0D-jZ_1_yGDw9bJcZDQuVctocdDMVt5Cw17pcnER0tTLxxnZ_qB
FWsu-WV-DMy2-Dk_TGBmjt_h1E1l_ye9mD_DQrlmE_tzHF1CQltzUZ0x_hi5lyJV199QVmj8Kkllms32_w05_uR-Za3Iw-y89Bt-5f3q-bj0qkjl0KcllmKa
lVuMaFJwMq3Iwsy1IQ-_1IIz_XQmqkjl0Kbw_IqWnVu6aFJwMq1Ix6y1AVOtWAJOtmB2_xJeNyhV2KYnlm6i5FjRGDBhRm3Fy7zHyV2_rjy9IB6_0Jp2_zLr
V-xdlzp-L_WRG9hz3I3D_WOG_XUgcv__TFFpdzuV-_dlkldvJ_Vjvxzgdtx-Euy__rv-_jFDpt_X___y3I3D_WQGLdy3uEypO9hz7O0q-nj0MlqDWB-F06dr
Tm3u6q2Q_Rq1qkhl0F1t0DBgxm3mTm3Iwky0y7S0LhM_0v1cVmVWMUtl0AJLdpz_Bu1LxUy0X3z__czPz_ddlseVV_xy-Gz__lpvT_BpN_pv7yJV2u0_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy
-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-RyyIP8aIP8aIP8aIP8aIP8aIP8aIP8aIPBq8m
}

