sprite $producer_portal [512x512/16z] {
xTo7SSCm40312HY1Sko_MtVWe801VNi5EAt9VqaaFnScIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIPBcQTAc_k8l_k8l_k8l_kA_V_p5N_p5
N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_p5N_pvfv8aIP8aIP8aIP8aIP8aIP8aIP8qvVu_yI_6_vZd
IRt3N_p5N_mLvrVFN_p5N_mLvrVFN_p5N_mLvzVc_k8l_ll7Vyno_W6c-8k_-DVYVvadJ4Vxy5VJN_p5N_4xFzKx_CLV_CLVSNxr_CLV_CLVyNV_r3lynL_y
nLznVlNynL_ynLyB-6_ujjfAOdz_7Jlvh-SN_nNnvy_V-BS0ykUVvJS0-FCVJNy3mFY_FVu7grFx6_yM0FxyB_mNjCqujlvP0FZpD_uj0Fpv7m5_2w3nRm7W
xnf0uzy2m9-_qxy5O4D_yTTOQDBYjm3mv-_TFmk0yNzx_0UZtGU0yS-VFt_hdu-0hNyMGAT_0u0_V_xyZNyB07_NW1Nu3G3-_FdpD_ujWFpvE_qR0FpvZ__d
ptyO_nO0pttZR_nR0FZpRpttZV_5-cS1uC_V-BS0yEVVklIV_s7yMm3ukmRG-BS0yEVlz6y1uC-Vl-V06VyM0FxyPyNVEu3yBO2U-sO06F_y-VFtuQy5OFBd
N-Ct0FZpvyz_p7EajVxYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xYB_xy
R-vwKn-VUtUzgUBFnvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xBui-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp
vy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdp5t_n5_zU_CLV_CM_5t_n5t_nxyLV_CLV_7ln
5t_n5_zU_CLV_CM_5t_n5t_nxyLV_CLV_7ln5t_n5_zU_CLV_CM_5t_n5t_nxyLV_CLV_7ln5t_n5_z8_7zEaYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9
aYH9aYH9aYHz0G
}

